### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by fishscene** [nextcloud/ios#10]
App was updated automatically on 12/12/2016. Open app, it prompts for security code (as it should), halfway through typing it in, it freezes for several seconds, then dumps me to the iOS home screen. 

App is still running in the background and I can switch to it, type in my security code, and get to the top-level folder list. I can see I have 5 files that need to upload. After a second or two, app dumps me to iOS home screen, but it is still running in the background. 

iOS 10.1

I'm now updating to iOS 10.2.

**Comment by marinofaggiana** [comment]
@fishscene terminate app and Clear cache in Settings.

**Comment by fishscene** [comment]
Resolved!
I'm now on iOS 10.2 and successfully cleared the cache, which was over 900MB.

For anyone else who might come across this, had to open app, quickly go to settings, then clear the cache. App worked perfectly after doing that.

Thanks!

**Comment by MorrisJobke** [comment]
@marinofaggiana This is not really a solution - the app should not require the user do some fast clicking to get it in a working shape again.

**Comment by marinofaggiana** [comment]
@MorrisJobke true but it's impossible understand the reason (sandbox), something being updated does not work properly,  i think problem database upgrade issue .. solution ? 
Clear cache, if possible, it's the first  try, after remove account and recreate, the last is remove and reinstall App. but ... none of these is good a solution.
