### ISSUE TITLE
Sharing problems (iOS iPhone and iPad)

### ISSUE THREAD

**Issue by olgsi** [nextcloud/ios#100]
Hello,

since two weeks a can't share items from the iOS App (Version 2.16 (00012).
I share a file, fetch the link and open it (on safari, firefox, chrome on Sierra and on Windows) and get a blank page. But if i share the file from the Web version or the Sierra App anything works fine and the link open with the file.

Thanks

**Comment by marinofaggiana** [comment]
Hi @olgsi is possible look a example link ?

**Comment by olgsi** [comment]
Of course,


https://wissowski.de/wolke/public.php?service=files&t=1Cv4CJB5SqmmlP0

**Comment by marinofaggiana** [comment]
If you want, please send me your address email for TestFlight beta version testing, i think that this issue it's correct with v 2.17

**Comment by olgsi** [comment]
Thanks: apple@nordbude.de

**Comment by marinofaggiana** [comment]
Done, please installa new beta version and verify the issue. Thanks

**Comment by olgsi** [comment]
Perfect. Works great and looks nice. Thanks a lot 

Von meinem iPhone gesendet

**Comment by marinofaggiana** [comment]
ok, close this issue
