### ISSUE TITLE
Hide Hidden Files

### ISSUE THREAD

**Issue by stephenthomas0** [nextcloud/ios#102]
It would be great if the iOS app didn't show hidden (.xxxx) files if at all possible 😊

**Comment by mr-manuel** [comment]
In my case i need the hidden files. It would be great, if you can select in settings, if displaying hidden files or not 😉

**Comment by stephenthomas0** [comment]
Yes definitely, can see the need to see them, but an option to hide them would  be brilliant 😊

**Comment by marinofaggiana** [comment]
Boy no option in settings for "technical question". 

The normal user do not know the different from .namefile and namefile (hidden file it's only form mac power user and unix user). 😄

**Comment by mario** [comment]
We do have such an option in Android, and it is not *that* technical so I
vote for including it.

**Comment by marinofaggiana** [comment]
@mario the normal user do not know the hidden file, this is a **technical** question.

**Comment by stephenthomas0** [comment]
Technical question or not, including it in the iOS app would give it parity with the web UI and the Android app. Not a biggie, but would be useful is all

**Comment by mario** [comment]
Give users what users want :p

**Comment by stephenthomas0** [comment]
Apologies. Probably shouldn't be posting feature requests here

**Comment by mario** [comment]
No need for apology - Marino, do it :)

**Comment by stephenthomas0** [comment]
Thanks Mario, very cool. I'll keep feature requests in the forum in the future. 👍

**Comment by mario** [comment]
@stephenthomas0 but why? (have you misunderstood me?) Issues are a better way to track both bugs and feature requests. If Marino doesn't get the time to implement this, I'll eventually do it for consistency reasons among platforms. 

While it is an advanced option, it is not *super* technical, and since it's included everywhere, should probably be included in iOS as well.

**Comment by marinofaggiana** [comment]
hahahah nooooo @stephenthomas0 this is the correct "place" for this conversation !!

**Comment by stephenthomas0** [comment]
Ah, I see what you mean now Marino about the technical question in the menu. I guess it's worth considering, for the non technical user, is it better for them to have a menu item that's automatically on that they don't understand, or to show hidden files in their storage? If you're right and the average user doesn't know what a hidden file is, they may try opening/deleting these files, as in their mind, they shouldn't be there

**Comment by stephenthomas0** [comment]
Ah cool. I'm just conscious of being a needy user disturbing the developers with "... and I'd like it to make my tea for me. Ou! Can I change the background of the app to a picture of Grumpy cat?" 😋 Glad to know this is the right place

**Comment by mario** [comment]
Gimme time until Monday and I'll check what exactly we do on Android so we can do something similar on the iOS (aka, I don't know if it's enabled or disabled by default, and the wording we use).

**Comment by rakekniven** [comment]
See option in TestFlight v2.17.6.3
Just tested it and it works from my POV.

**Comment by mr-manuel** [comment]
Tested with 2.17.6 (11). It's working great 👍
