### ISSUE TITLE
Show cache size again

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#103]
As Testflight user I noticed that settings do not show cache size anymore.

Please show cache size again. Action "clear cache" is useful to free space, but for decision to use it I need to know the actual size of it.

Using version 2.17 (022)

**Comment by marinofaggiana** [comment]
@rakekniven go to on settings of your iPhone, general, storage & iCloud Usage, Manage Storage.

**Comment by rakekniven** [comment]
Ok, that will work as well.
Personally I prefer to see size in settings and decide what to do.

**Comment by rakekniven** [comment]
It is there again in v2.17 (0027). Great.
Will it remain in final? If yes I would close issue.

**Comment by marinofaggiana** [comment]
yes !
