### ISSUE TITLE
Open Document file with Internal viewer

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1038]
For the documents exists, if installed, the on line viewer as Collabora or Nextcloud Text (18) but if you want view this document with the internal viewer now you can with: 

On document file touch long press or Peek/Pop for select the "Open with internal viewer" :

![Schermata 2019-12-11 alle 15 31 23](https://user-images.githubusercontent.com/8616947/70630123-5563d980-1c2b-11ea-8dda-f76263efbd39.png)

![Schermata 2019-12-11 alle 16 53 57](https://user-images.githubusercontent.com/8616947/70637043-dd9bac00-1c36-11ea-954a-534fd8219ae0.png)

**Comment by pierreozoux** [comment]
Arf, just tested, it wokrs for .doc but not for odt, can we just reopen this issue, or do you prefer we open a new one?

**Comment by marinofaggiana** [comment]
The odt file is unsupported (Apple)

**Comment by pierreozoux** [comment]
Im no is expert, but here, it looks like an odt viewer, so I guess the internal viewer is not an option, but then "open in..." should be if I'm not wrong (which I might:) )

I think it would be worth it for iOS users. But if you prefer I open another issue. As you like :)

**Comment by marinofaggiana** [comment]
I don't know if the "document" is visible with internal viewer, for example .odt NO, .doc, .docx yes, so other can be viewed or not ...

**Comment by pierreozoux** [comment]
Im no is expert, but here, it looks like an odt viewer, so I guess the internal viewer is not an option, but then "open in..." should be if I'm not wrong (which I might:) )

I think it would be worth it for iOS users. But if you prefer I open another issue. As you like :)

**Comment by pierreozoux** [comment]
Sorry forgot the link https://apps.apple.com/us/app/ooreader/id480844649
