### ISSUE TITLE
Label "Favorites" show singular on start and changes to plural 

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#104]
1. Start app
2. Favorites label show "Favorite" (singular)
3. Tap Favorite 
4. Label changes to "Favorite**s**" (plural)

![2017-03-01 18-36-19 6102](https://cloud.githubusercontent.com/assets/2069590/23579832/04205bd2-00f6-11e7-9a6d-f6cc6772bbf0.jpg) ![2017-03-01 18-36-51 6103](https://cloud.githubusercontent.com/assets/2069590/23579830/041f69a2-00f6-11e7-9453-d44f215816bb.jpg) ![2017-03-01 18-37-15 6104](https://cloud.githubusercontent.com/assets/2069590/23579831/04200d8a-00f6-11e7-9ee9-8ac6dfc7fe16.jpg)

It should show "Favorites" all the time.

**Comment by rakekniven** [comment]
Issue is still present with v2.17 (23)

**Comment by marinofaggiana** [comment]
yes yes @rakekniven it' normal, refresh Transifex for next version

**Comment by rakekniven** [comment]
Works now with v2.17 (24)
