### ISSUE TITLE
accept original file name

### ISSUE THREAD

**Issue by LBS-Immo** [nextcloud/ios#1047]
If you e.g. wants to share an image from the photo app with the nextcloud app, the image is saved in the nextcloud with a specified file name. It would of course be better if the original file name were used or the file name could even be changed.

**Comment by mghinch** [comment]
I upvote for a fix for this.

It appears to be the same problem as #876, 962, and 993. Seems 
to be bothering a number of us...

**Comment by mghinch** [comment]
Works! Thanks!!
