### ISSUE TITLE
Selection in iOS app doesn’t match the actual selection (or rather changes)

### ISSUE THREAD

**Issue by hannesfritz** [nextcloud/ios#105]
In the Nextcloud iOS app I selected three single photos on the root level (sorted by newest) in order to delete them. Meanwhile the instant camera upload synced photos from my camera roll to the „Photos“ folder. This folder then became the topmost entry.

The selection checkmarks were still on my three photos so I deleted them. But after the action was done one photo still remained, while my complete „Photos“ folder got deleted (thankfully I was quick enough to get to my Mac, switch the network off and backup this folder locally).

So apparently the visual selection does not match the actual technical selection when new files get added. The app seems to remember the selection on the order than the actual files?

It is contrary to user expectations and system status visibility as well as a bad bug because you can loose your files without the possibility of undo. Would appreciate it if this issue will be checked and resolved.

**Comment by jancborchardt** [comment]
@marinofaggiana @nextcloud/ios could you look into this? :)

**Comment by marinofaggiana** [comment]
for me : replace old - (void)alertView

**Comment by marinofaggiana** [comment]
Path available on next version 2.17.4
