### ISSUE TITLE
Simplify terms in German UI

### ISSUE THREAD

**Issue by sushidave** [nextcloud/ios#106]
Different terms are used in the German user interface:

- "Verschlüsselungsschlüssel" (welcome slideshow page 2)
- "Chiffrierschlüssel" ( " page 2)
- "Passwortschutz" ( " page 9)
- "PIN" / "PIN für den Verschlüsselungsschlüssel" (account setup page 1)

Some of them mean the same? Please simplify.

(see also [this post](https://help.nextcloud.com/t/nextcloud-ios-app-pin-for-encryption-key/9211) in the Nextcloud forum)

**Comment by rakekniven** [comment]
Will have a look at it.

**Comment by rakekniven** [comment]
Slideshow will look very different with next release.

**Comment by rakekniven** [comment]
Just checked latest Testflight version (v2.17 0027) and there are no different terms in UI and intro anymore.
Many strings at transifex are obselete.

@sushidave Are you using testflight versions?

**Comment by sushidave** [comment]
@rakekniven Thanks very much and sorry for not mentioning the version before. I was referring to version 2.16 which is in the App Store.

You know, I had quit the account setup process because the PIN/encryption thing wasn't transparent and I couldn't find any documentation either. So far, I was using ownCloud's app which worked fine with a Nextcloud server. However, I'll be happy to give it another go with the next release.

**Comment by sushidave** [comment]
@rakekniven If it helps I can contribute with a review of the testflight version. Just tell me how.

**Comment by rakekniven** [comment]
Beta testings always helps. See #72

**Comment by rakekniven** [comment]
Checked all strings at transifex again and IMHO issue is resolved.

**Comment by sushidave** [comment]
@rakekniven Thank you for resolving this issue. The procedure of the new release to setup an account is now transparent. I also like the new design.
