### ISSUE TITLE
Auto upload setup: Buttons (almost) invisible when selecting folder

### ISSUE THREAD

**Issue by MarcelWaldvogel** [nextcloud/ios#1064]
### Expected behaviour
When clicking on "Settings→Auto upload→Select folder", the "Create folder" and "Select" buttons at the bottom are clearly visible.

### Actual behaviour
The button text (at least in "Light" mode) is white on light gray. We did not notice the color difference at all at first.

### Steps to reproduce
1. In Settings app, select light mode
2. In Nextcloud, try to select an auto-upload folder ("Settings→Auto upload→Select folder")

### iOS version
13.3
### App version
2.25.3.6

![photo_2020-01-02_16-02-52](https://user-images.githubusercontent.com/3014737/71674893-cb67e600-2d7c-11ea-8e2b-aa0c05b64c5d.jpg)

**Comment by RobinFrcd** [comment]
Same issue when trying to move files inside the app.

**Comment by blackivory86** [comment]
Probably the same as #1071

**Comment by rules76** [comment]
Buttons are still invisible with today's update...

**Comment by rules76** [comment]
Fixed in v2.25.5, great!

**Comment by MarcelWaldvogel** [comment]
I can confirm that it is fixed; thanks!
