### ISSUE TITLE
Manual uploading of photos results in error

### ISSUE THREAD

**Issue by gbiggs** [nextcloud/ios#107]
Server: nextcloud-11.0.1.tar.bz2, nginx 1.6.2-5+deb8u3, php5 5.6.27+dfsg-0+deb8u1
Client: NextCloud iOS client 2.16 (00012)

Uploading a photo manually results in an error on the client, an error in the server log (only visible at debug log level), and no upload being performed.

Client error (in red banner):
"Server error
Read file WebDAV : [items NULL] please fix"

Server log:
`{"reqId":"muhNKRbZiNSdEjpcB7ic","remoteAddr":"192.168.0.134","app":"admin_audit","message":"Login attempt: \"geoff\"","level":1,"time":"2017-03-10T22:23:28+09:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Photos\/2003-09-03%2013-52-17%200702.jpg","user":"--","version":"11.0.1.2"}
{"reqId":"muhNKRbZiNSdEjpcB7ic","remoteAddr":"192.168.0.134","app":"admin_audit","message":"Login successful: \"geoff\"","level":1,"time":"2017-03-10T22:23:28+09:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Photos\/2003-09-03%2013-52-17%200702.jpg","user":"geoff","version":"11.0.1.2"}
{"reqId":"muhNKRbZiNSdEjpcB7ic","remoteAddr":"192.168.0.134","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name Photos\\\/2003-09-03 13-52-17 0702.jpg could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(939): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Photos\\\/2003-09-...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(336): Sabre\\\\DAV\\\\Server->getPropertiesForPath('Photos\\\/2003-09-...', Array, 0)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/nex:\"geoff\"}","level":0,"time":"2017-03-10T22:23:28+09:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Photos\/2003-09-03%2013-52-17%200702.jpg","user":"geoff","version":"11.0`

Other uploads (automatic photo uploads, manually uploading a PDF from Safari, creating a folder, etc.) work fine.

**Comment by marinofaggiana** [comment]
@gbiggs this error is not a problem of iOS but wrong response of server

**Comment by gbiggs** [comment]
OK, so I need to post a ticket over on nextcloud/server, I assume. What is different about manually uploading photos and all other uploads (automatic photos, manual files from Safari, etc.) that could be causing a different server response?

**Comment by MorrisJobke** [comment]
Does the folder you want to upload to still exist? Otherwise this could be the reason.

**Comment by gbiggs** [comment]
Yes, it does. Manually uploading other files to the same folder succeeds.

**Comment by MorrisJobke** [comment]
@marinofaggiana Why do you think this is a server error? It does a PROPFIND for this file, which seems to be not there and returning a 404 seems to be fine, if the file is not there.

**Comment by gbiggs** [comment]
@marinofaggiana The issue I reported on the server project (https://github.com/nextcloud/server/issues/4269) has been closed with the resolution that this is a bug in the iOS client.

**Comment by enoch85** [comment]
Is this fixed?

**Comment by gbiggs** [comment]
Not for me using 2.17.4.00038. I still get exactly the same symptoms.

**Comment by marinofaggiana** [comment]
@gbiggs have u a account test for me ?

**Comment by gbiggs** [comment]
It's a private server so I'm not keen on giving out accounts.

I am willing to try and debug the issue myself, but I have no experience with iOS development so I would need some pointers on where to get started.

**Comment by enoch85** [comment]
@gbiggs Private or not, you can give an account without admin rights, I don't think @marinofaggiana  will hack your server. :) Send it to him in an email instead of here on Github. Now in 12.0.1 you can use the new send with email function, you don't even have to set a password yourself. You just enter his email and it will be set automatically.

User settings --> Send email to new users --> Enter user name (no password) --> Enter email -->  Create
