### ISSUE TITLE
Icon for "Remove from cache" should be overworked

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#108]
Just seen new icon in file options dialog. Should be changed IMHO :-)
Testflight version 2.17 (0027)

![2017-03-13 16-18-46 6119](https://cloud.githubusercontent.com/assets/2069590/23894626/28a17a54-08a3-11e7-9f75-0a15d539bd7d.png)

**Comment by marinofaggiana** [comment]
hahahahah

**Comment by marinofaggiana** [comment]
i love this icon

**Comment by rakekniven** [comment]
Icon is nice. Could not get a connection from icon to function :-/

**Comment by marinofaggiana** [comment]
why not ? for example Tumblr (c) use (a bomb) for clear cache

**Comment by timbru31** [comment]
I'd never seen such an icon before, but do like it, too

**Comment by rakekniven** [comment]
@jancborchardt What do you think about the icon? Personally I would hesitate to touch a bomb ;-)

**Comment by jancborchardt** [comment]
I do have an issue with the function being there at all. The menu is very long as it is and we should really reconsider having so much in there.

- Favoriting could be done by a swipe to the right instead and be removed from this menu
- »Add to local storage« is done by opening / downloading the file. This function shouldn’t be here
- »Remove from cache« is way less important than all the rest here

What do you think @marinofaggiana?

**Comment by marinofaggiana** [comment]
Ok tomorrow pen and paper :-)

"Leave your opinion on App Store, it is important to us"

Marino Faggiana (ios@nextcloud.com)
Nextcloud App iOS Project Manager

oOo - Nextcloud - A safe home for all your data

**Comment by jancborchardt** [comment]
Yup! :)

**Comment by rakekniven** [comment]
The bomb is still there at v2.17 0040.
Still think icon is not suitable.

Have no better idea 👎 .

**Comment by marinofaggiana** [comment]
@rakekniven  it's funny !!! hahahah

**Comment by timbru31** [comment]
Idea: a mop/broom 
(something like https://lh6.ggpht.com/HOq-ACovA0SKns26rSfvuerzNwI4JMAKkF0pxCjEXBjsBqQw24e_IEQf3b76u6ASlw=w300)

**Comment by jancborchardt** [comment]
Maybe the broom is indeed better, it's still funmy while looking less destructive.

What do you think @marinofaggiana? :)
