### ISSUE TITLE
Lock feature no longer working

### ISSUE THREAD

**Issue by timbru31** [nextcloud/ios#109]
## Actual behavior

I'm using the beta build 2.17 (27 & 28) on my iPhone 7 10.2 and upon launching Nextcloud there is no prompt for my TouchID or password.
Neither does disabling the lock feature and re-enabling fix this issue

## Expected behavior

App is asking for password/TouchID.

**Comment by marinofaggiana** [comment]
mmm i don't have modify the password code ... strange ...

**Comment by timbru31** [comment]
Some more information:

App says lock is active, to disable it I need my fingerprint/password.
It's just not asking on launch.

Cleaning cache and rebooting phone did not help.

**Comment by marinofaggiana** [comment]
Is ON "Lock only for protected folders" ?

**Comment by timbru31** [comment]
No it's off

**Comment by marinofaggiana** [comment]
I have remove post ;) (confusion)

**Comment by marinofaggiana** [comment]
But if you protect a folder ?

**Comment by timbru31** [comment]
Yes, folder protection works fine - seems like the root folder does not work

**Comment by marinofaggiana** [comment]
@timbru31 find the issue 👍

**Comment by timbru31** [comment]
Confirming that 2.71 (31) fixes the issue.
Thanks!
