### ISSUE TITLE
Please use your real GitHub username

### ISSUE THREAD

**Issue by jacboy** [nextcloud/ios#11]
Hey @marinofaggiana,

I am pretty sure you're the guy behind these commits (https://github.com/nextcloud/ios/commit/42f3829193b8db61eebfbaf4085780fa43750afc). Please use your real GitHub user name and e-mail adress to assign your commits to your user.

A guide can be [found here](https://help.github.com/articles/setting-your-email-in-git/).

Jakob

**Comment by marinofaggiana** [comment]
@jacboy yes, too many things to do, soon i will take time to configure such github.

Thanks !
