### ISSUE TITLE
All favourites are synced without opt-out

### ISSUE THREAD

**Issue by maprambo** [nextcloud/ios#110]
In 2.17.00028, all favourites are synced automatically. This is a nice feature, but I tended to have gigabytes of favourites.
An opt-out to sync a specific or all favourites would be nice, maybe also a question when Nextcloud is first installed if the user wants the favourites to be synced.

**Comment by marinofaggiana** [comment]
mmm a possibility is if synchronized only struct (directory/file) without downloads the file ... but i down't like too option ....

**Comment by maprambo** [comment]
Yeah the structure is most important. You could also sync it optionally like you would normally with other folders if you wanted to...

**Comment by rakekniven** [comment]
@maprambo Could you explain why you have so many favorites? 
The more I have the more I loose the advantage of favorites, or? Would be interesting to hear your use case.

**Comment by maprambo** [comment]
I don't have many favourites, but part of them are very big folders. Especially media folders sum up pretty fast.

**Comment by cal940** [comment]
Me too, And I need these folders.

**Comment by rakekniven** [comment]
Just for the records:
Feature will not be implemented at the moment?

**Comment by marinofaggiana** [comment]
it's already present in 2.17

**Comment by rakekniven** [comment]
Tried to figure out how to opt-out subitems of a folder. Did not manage to get the trick. Any hints?
