### ISSUE TITLE
After #1101 Menu displayed as drawer lost ADD FOLDER INFO

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1102]
After the new Menu displayed as drawer #1101 the option for Nextcloud 18 : add folder Info appear lost.

**Comment by marinofaggiana** [comment]
@immortal79

**Comment by immortal79** [comment]
Thank you for the line ref, I was writing to ask where I could get the info ^^
I will fix it right now.

**Comment by marinofaggiana** [comment]
Yes but now the problem is: where restore this voice of menu ? ... In "Filter icon" is not correct.

**Comment by marinofaggiana** [comment]
> Thank you for the line ref, I was writing to ask where I could get the info ^^
> I think it's my merged commit which removed the feature.
> I will fix it right now.

The item must appear only if: 

if (capabilities.versionMajor >= k_nextcloud_version_18_0 && self.richWorkspaceText.length == 0)

**Comment by immortal79** [comment]
Shouldn't this item be in the create button ?

**Comment by marinofaggiana** [comment]
yes !
