### ISSUE TITLE
Authentication error (triggering bruteforce protection) due to share extension since v2.25.0

### ISSUE THREAD

**Issue by bcutter** [nextcloud/ios#1113]
THIS issue is still existing:

https://github.com/nextcloud/ios/issues/1022

As nobody with a bit of power is listening to that issue, here‘s a new one related to the same problem. Just please don’t close issues as long as things are not fixed - proven by data provided.

**Comment by marinofaggiana** [comment]
Sorry @bcutter but this issue is not generated from the App iOS, I don't know how to help you

**Comment by bcutter** [comment]
> Sorry @bcutter but this issue is not generated from the App iOS, I don't know how to help you

Why not? The problem was introduced with the update to v2.25.0. Unfortunately I can not downgrade to test but... even if it would not be the app I was hoping you guys talk to each other (app developers with server guys and therefore the 2FA/security/authentication team)... don‘t you?

**Comment by bcutter** [comment]
I think you guys really messed up something in terms of proper authentication. Me personally using 2FA and having this issue only with the iOS app in combination with the bruteforce protection (blocking IPs after 5 failed logon attempts). The iOS app is definitely doing something wrong in terms of authentication.

Would be great to have someone take a look into this, people are suffering from this and no one is taking responsibility, not even asking for debugging information or sth. similiar.

**Comment by crsqq** [comment]
Got the same problem. Redownloading the app didn't help. Now i get that error when I try to login.

**Comment by GCHPX** [comment]
soooo, i think i found something that may help the devs..i just deactivated 2fa and removed the account on the app and added it again and the error is gone. can anyone of you guys confirm this? i know this isn´t a solution but my help to narrow it down a bit.

**Comment by bcutter** [comment]
Since app version 2.25.8 this error (code 401) seems to be fixed. Can others confirm?

**Comment by crsqq** [comment]
> Since app version 2.25.8 this error (code 401) seems to be fixed. Can others confirm?

yes

**Comment by bcutter** [comment]
I´ll close this issue. Unfortunately more issues introduced with the v2.25.8.0 update (e. g. https://github.com/nextcloud/ios/issues/1161).
