### ISSUE TITLE
Missleasing translation to german

### ISSUE THREAD

**Issue by Dirk23** [nextcloud/ios#113]
There is one translation to German wich is misleading: The Switch in the automatic picture upload wich enables the background upload. It is translated to "Hintergrundbilder hochladen" wich is translated to english with: "Upload Backgroundpictures"!

I guess that is not what it's meant to be. It should be translated to German with:"Bilder im Hintergrund hochladen" wich means to upload Pictures in the background!

**Comment by marinofaggiana** [comment]
@rakekniven ping

**Comment by rakekniven** [comment]
Just changed it to "Bilder im Hintergrund hochladen" at transifex.
Will provide PR to improve english text.
