### ISSUE TITLE
NextCloud App - fulltextsearch - returns no results

### ISSUE THREAD

**Issue by gionxdata** [nextcloud/ios#1152]
I have installed a NextCloud server.  The server has all the updates applied and your fulltext search add-on applied. Using a browser and logged into our NextCloud server I am able to successfully perform fulltext searchs on .txt .docx. .xls and .pdf documents.

To clarify if I was searching for the string 'fox' and it was within the content of the mentioned files types (.txt .docx. .xls and .pdf) I would get a successful search.

If I use a smartphone with the NextCloud app installed and used the search feature. I would not get any successful searches.

Is there a way to get this working? Who can I approach? If there is a cost involved would still be very interested in going forward.

Thanks

**Comment by gionxdata** [comment]
I understand that if I pledge some funding I might get this request looked at...

**Comment by wiswedel** [comment]
Full text search is not yet available in the iOS app: https://github.com/nextcloud/ios/issues/1167#issuecomment-589607457
