### ISSUE TITLE
Share private link

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1162]
There are two different ways to share a file via uri
in Nextcloud web:

On one hand, multiple "public" links can be created for a file (/s/ uri). The Nextcloud app contains this functionality already.

On the other hand, the "unique" link (/f/ uri) references the "private" file. This link exists exactly once for every document. The file can be shared via this link with other users, as long as the users are logged into Nextcloud and the owner has given the receivers access to the resource.

**Comment by shurik-io** [comment]
Do you have any plans when the development of this starts?

**Comment by justin5150-hub** [comment]
Considering it

**Comment by justin5150-hub** [comment]
I’m currently having issues with my systems security. I have several viruses that are not being detected by malwearbyts

**Comment by justin5150-hub** [comment]
I will be done the radio station software completed in 6 days ready to open a repository by the 15th

**Comment by SaschaT667** [comment]
Interested as well :+1:  
Are there any updates on the current plans for this issue?
