### ISSUE TITLE
File list - empty block at the start

### ISSUE THREAD

**Issue by Haxy89** [nextcloud/ios#1165]
What is this empty space for and how to remove it. Layouty look sick with it.

![29C71A4F-FB86-49F0-8B79-E48ADFC8F42F](https://user-images.githubusercontent.com/37550896/74917691-340c3000-53c8-11ea-8707-a05af63bfa5b.jpeg)

**Comment by marinofaggiana** [comment]
Hi, but what is the content of readme.md ?

**Comment by Haxy89** [comment]
It is empty but How it is related?
It looks but with this empty space and i want to remove it from gui

**Comment by marinofaggiana** [comment]
if readme.md lenght > 0 appear the workspace, remove the readme.md for remove the workspace.

**Comment by Haxy89** [comment]
Ok, Thanks
