### ISSUE TITLE
Rework cloud accounts section

### ISSUE THREAD

**Issue by timbru31** [nextcloud/ios#117]
The space for the account switch is IMHO way to big, especially if you have only one account in use.
Maybe this section can be reworked to use the space more efficient.

See attached screenshots of v2.17 (31) on iPhone 7 iOS 10.2

---
![img_1458](https://cloud.githubusercontent.com/assets/838003/24122331/bc2b715e-0dbb-11e7-9362-f94161ebfbd2.PNG)
---
![img_1459](https://cloud.githubusercontent.com/assets/838003/24122332/bc2dd62e-0dbb-11e7-9487-2d4c559bd8ad.PNG)

**Comment by melikyuksel** [comment]
Seems to be smaller in the later releases. Would you consider this fixed and able to be closed?

**Comment by johkoenig** [comment]
Fixed for quite some time
