### ISSUE TITLE
How to disable the „take quick note“ area from NC 18 ?

### ISSUE THREAD

**Issue by F3000** [nextcloud/ios#1174]
When I open the app there is a big empty area above the files . How can I hide this area ?

**Comment by raimund-schluessler** [comment]
I think it would make sense to add a setting in the app for this.

**Comment by sheepchen** [comment]
who thought a big empty box in the middle of the screen is a good idea?
why is quick note in files when the is also a note-function in calender?

**Comment by marinofaggiana** [comment]
If exists the file readme.md with length > 0 this area appear, remove the readme.md for remove this area.

**Comment by sheepchen** [comment]
thanks. This file was created automaticly by the upgrade. I couldn't remove it in the iOS app but after I removed it via the PC the box vanishes!
