### ISSUE TITLE
Last Nextcloud logo in tutorial is misleading

### ISSUE THREAD

**Issue by timbru31** [nextcloud/ios#118]
Using v2.17 (31) on an iPhone 7 with iOS 10.2
The last screen of the welcome tutorial is quite misleading, since the Nextcloud logo looks like a video, but touching it does nothing.

See attached screenshot

---
![img_1456](https://cloud.githubusercontent.com/assets/838003/24122417/0b844dfc-0dbc-11e7-92ca-5d1700abf3e6.PNG)

**Comment by rakekniven** [comment]
Yeah, tried to touch it as well.

**Comment by marinofaggiana** [comment]
@rakekniven play music : tadaaaaaaa !!!!    hahaha i change this before final build.

**Comment by rakekniven** [comment]
Why not playing a jingle.  Good idea :-)

**Comment by timbru31** [comment]
Icon has been changed in v2.17 (32)
