### ISSUE TITLE
Nextcloud iOS V 3.0 - Code name: Coherence

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1182]
The new "big" next version of Nextcloud iOS will have all internal viewers totally rewritten and **coherent** with each other.

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-05 at 10 09 20](https://user-images.githubusercontent.com/8616947/75965820-a5b8a380-5ec9-11ea-8205-dbc117a34180.png)

Each viewer will always have the menu with the available options and always at touch:

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-05 at 10 15 29](https://user-images.githubusercontent.com/8616947/75966523-ca614b00-5eca-11ea-9833-6bda284d28ba.png)

The use with ipad has been totally revised

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-05 at 10 22 39](https://user-images.githubusercontent.com/8616947/75966963-668b5200-5ecb-11ea-9ee6-bc75ec109d81.png)

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-05 at 10 21 51](https://user-images.githubusercontent.com/8616947/75966955-63906180-5ecb-11ea-8c8a-848261fc1127.png)

The new PDF (Apple PDFKit) viewer will now be able to view the notes you have inserted in your PDFs

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-05 at 10 29 51](https://user-images.githubusercontent.com/8616947/75967724-866f4580-5ecc-11ea-9ee3-f4cad955371c.png)

Browsing your images is now easier

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-05 at 10 34 18](https://user-images.githubusercontent.com/8616947/75968003-faa9e900-5ecc-11ea-9a28-d7edd65fe40b.png)

With a improved zoom

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-05 at 10 34 34](https://user-images.githubusercontent.com/8616947/75968028-072e4180-5ecd-11ea-9630-43ce4b4d1efd.png)

And more convenient to edit your texts with iPad & Only Office 

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-05 at 10 37 51](https://user-images.githubusercontent.com/8616947/75968284-6a1fd880-5ecd-11ea-84e0-4329550812ca.png)

... and much more in development.

Available an **Alpha** version in TestFlight, today !

https://testflight.apple.com/join/GjNbfo2a

**Comment by jancborchardt** [comment]
Good good stuff! :) Some design review points, not only about the viewers but generally while we’re at it:

----------------

> ![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-05 at 10 09 20](https://user-images.githubusercontent.com/8616947/75965820-a5b8a380-5ec9-11ea-8205-dbc117a34180.png)
- [ ] The filter/funnel icon for sorting is a bit strange. Better would be a "Sort" icon like this: https://material.io/resources/icons/?search=sort&icon=sort&style=baseline
- [ ] The "Select" action next to it can also be moved into that "Sort" menu. Otherwise there’s too many icons up top there.
- [ ] The Share icon in the list seems rather large, and the 3-dot icon rather small, that should be adjusted

---------------

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-05 at 10 15 29](https://user-images.githubusercontent.com/8616947/75966523-ca614b00-5eca-11ea-9833-6bda284d28ba.png)

- [ ] "Close" should be in the top left instead of the 3-dot menu
- [ ] The "Share" action should be left of the 3-dot menu, to mimic how it is in the file list
- [ ] Same for the actions, they should be the same as in the file list:
   - Add to favorites ("o", not "ou" spelling)
   - Details
   - Open in …
   - Rename
   - Move
   - Delete

------------------

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-05 at 10 37 51](https://user-images.githubusercontent.com/8616947/75968284-6a1fd880-5ecd-11ea-84e0-4329550812ca.png)

cc @juliushaertl and @tobiasKaminsky on these for Android & iOS cross-platform coordination

- [ ] We are duplicating the document title there in our header bar, this doesn’t seem necessary?
- [ ] Same for undo/redo, it’s duplicated from the OnlyOffice bar

**Comment by marinofaggiana** [comment]
Hi @jancborchardt can you explain this ? Remember the use with iPhone:

>  "Close" should be in the top left instead of the 3-dot menu
  The "Share" action should be left of the 3-dot menu, to mimic how it is in the file list
  Same for the actions, they should be the same as in the file list:
Add to favorites ("o", not "ou" spelling)
Details
Open in …
Rename
Move
Delete

![Simulator Screen Shot - iPhone 11 - 2020-03-06 at 09 05 27](https://user-images.githubusercontent.com/8616947/76064584-42db1100-5f8a-11ea-9664-f7889d71b355.png)


cc @juliushaertl and @tobiasKaminsky on these for Android & iOS cross-platform coordination

  We are duplicating the document title there in our header bar, this doesn’t seem necessary?
  Same for undo/redo, it’s duplicated from the OnlyOffice bar

the header bar is necessary because I want always the "menu ..." available, and the redo/undo in bottom is the automatic bar of webview

**Comment by tobiasKaminsky** [comment]
Header bar is on ios needed as long as thgere is no back button in OnlyOffice.
On Android I show OO in fullscreen, as there is always a back button/gesture.

@juliushaertl do you know if/when they implement this?

**Comment by juliushaertl** [comment]
> Header bar is on ios needed as long as thgere is no back button in OnlyOffice.
On Android I show OO in fullscreen, as there is always a back button/gesture.
> @juliushaertl do you know if/when they implement this?


I think this should be there with their next document server release 5.5.0 but I've no idea if that fix has made it in.

**Comment by juliushaertl** [comment]
> "Close" should be in the top left instead of the 3-dot menu
Why would there be a close action anyway, isn't that what the back button in the top left is for on iOS?

**Comment by marinofaggiana** [comment]
@juliushaertl some issue with iOS 

![IMG_0003](https://user-images.githubusercontent.com/8616947/76067327-78362d80-5f8f-11ea-8790-85843d6fb6cd.PNG)

![IMG_0002 2](https://user-images.githubusercontent.com/8616947/76067390-8edc8480-5f8f-11ea-8c07-7e887d4bee41.PNG)

**Comment by marinofaggiana** [comment]
P.S. remember all iOS is not Android and do not exists a button hardware for back and exists iPhone and iPad with different view (split mode o single view mode), so every detail view must have a Navigation Bar + back button "<" or magnification button "\" for iPad + title + menu button "..."

**Comment by juliushaertl** [comment]
@marinofaggiana Second one is expected as we center the editor. For the first one please open an issue in https://github.com/nextcloud/text with details on which version this happens.

**Comment by marinofaggiana** [comment]
Build 4

![IMG_0008](https://user-images.githubusercontent.com/8616947/76201943-5c7f9100-61f4-11ea-9002-a36f50454a75.PNG)

![IMG_0006](https://user-images.githubusercontent.com/8616947/76201951-62757200-61f4-11ea-9ce6-1d77cf54838d.PNG)

**Comment by JorisBodin** [comment]
Hello,
> We are duplicating the document title there in our header bar, this doesn’t seem necessary?
Maybe display "Only Office" in the Navigation Bar to avoid this duplication?
Or maybe customize the display of the Onlyoffice bar, not to display a title?

> The "Select" action next to it can also be moved into that "Sort" menu. Otherwise there’s too many icons up top there.
I think the "Select" should not be displayed in the "sort" modal. It's an inconsistency. 

The sort button could be on the right side of the search bar. This would prevent too many buttons on the navigation bar.

**Comment by marinofaggiana** [comment]
Build 6

View video & audio when viewing images. [ touch for view ]

![IMG_0010](https://user-images.githubusercontent.com/8616947/76221135-e04b7480-6218-11ea-804f-3bb932a5f0ab.PNG)

**Comment by marinofaggiana** [comment]
> Hello,
> 
> > We are duplicating the document title there in our header bar, this doesn’t seem necessary?
> 
> Maybe display "Only Office" in the Navigation Bar to avoid this duplication?
> Or maybe customize the display of the Onlyoffice bar, not to display a title?
> 
> > The "Select" action next to it can also be moved into that "Sort" menu. Otherwise there’s too many icons up top there.
> 
> I think the "Select" should not be displayed in the "sort" modal. It's an inconsistency.
> 
> The sort button could be on the right side of the search bar. This would prevent too many buttons on the navigation bar.

For now I have only removed the title:

![IMG_9AD5F1BAC58E-1](https://user-images.githubusercontent.com/8616947/76226896-c9a81c00-621e-11ea-9b29-c652d37dbe42.jpeg)

**Comment by yadayadaydadaa** [comment]
Internal viewers are bull. Just make the sync actually work (you need to wait the app on screen for an hour for offline downloads to even start) and make the iOS a Files integration work. There are a zillion much better apps then than shoddy internal *nonsense*. 

Completely misplaced priorities in this piece of shit project.

**Comment by yadayadaydadaa** [comment]
If I wanted to be locked into just a single app having access to my files I’d be using PDFExpert. Its WebDAV-based sync from the nextCloud server is much more reliable and faster than the shoddy pile of garbage that this official iOS app is. Instead I’m using PDFViewer which is much better as a PDF app but I’m suffering daily from the garbage that this formerly sync app but now apparently a closed micro-ecosystem is. Surely to include a total pile of crap for a PDF editor.

**Comment by jancborchardt** [comment]
@yadayadaydadaa this tone is not welcome here, and it won’t help to motivate anyone improving the app. If you want to participate, read and respect our community code of conduct: https://nextcloud.com/contribute/code-of-conduct/ – and at the very least, don’t be counter-productive with inflammatory comments. Thank you.

**Comment by yadayadaydadaa** [comment]
Deleting my comments describing the true “quality” this app. Flash-closing my bug reports. Says a lot about the priorities, just like this present “issue” that should not even be listed, at the very least not until the plentiful problems are fixed.

**Comment by yadayadaydadaa** [comment]
There's pretty much no point in even trying to contribute to this project, because based on my experience the next update will undo any fixes done in the previous one.

**Comment by jancborchardt** [comment]
@yadayadaydadaa your comments were merely hidden, which is what we do with any comments which contribute nothing. It’s also unnecessary to still comment if you use iCloud instead of Nextcloud now as said in [the other issue](https://github.com/nextcloud/ios/issues/1229#issuecomment-620734320). Bye

**Comment by yadayadaydadaa** [comment]
Again. No discussion allowed. No critique allowed. Just pushing fingers into the ears and singing. To avoid hearing about the impending doom. Bye.
