### ISSUE TITLE
Create .txt files (without encryption) using the app

### ISSUE THREAD

**Issue by cal940** [nextcloud/ios#119]
In the web GUI there is an option to add a .txt file to a folder. I would really appreciate it, seeing that feature in the app.

**Comment by rakekniven** [comment]
You can use the notes app to create txt files. That app is specially made for making notes and edit them

**Comment by cal940** [comment]
I don't want to use the app for my notes. I'm the admin of 3 different Nextcloud application (personal, school, scouts) and I want to share Information like Wifi Keys, Links an so on with my colleagues. And I need a system, which works on different OS like Android or iOS.

**Comment by rakekniven** [comment]
Notes are just text files. They can have any content.
You wrote "add a .txt file to a folder". Do you like to edit them inside the app as well?

**Comment by cal940** [comment]
Yes, I also want to edit existing .txt files. Just like in the web GUI.

**Comment by cal940** [comment]
Sorry, there already is a similar issue (#21)
