### ISSUE TITLE
Rename pictures on upload

### ISSUE THREAD

**Issue by seraphyn** [nextcloud/ios#12]
It should be possible to rename pictures by my own schemata.
I use the exifdata a.e._IMG_%Y%M%D_%H%M%S_ with Photosync on ios.
This comes years ago from Android and it keeps my data consistent till now.

Would be great to have this option.
This makes it possible to put _VACATIONS_FRANCE_%Y%M%D_%H%M%S_ etc on it

**Comment by marinofaggiana** [comment]
hi @seraphyn ... mmmm this is a good option but very technical ... I do not know where and how could be put this option ... idea ?

**Comment by seraphyn** [comment]
That's a good Question.
It is an option I use very often in [Photosync](https://photosync-app.com/) on iOS.
As I see in [Dataname change after uploading #395](https://github.com/owncloud/ios/issues/395), they had a problem with that.
And [filename of uploaded images should use timestamp of image](https://github.com/owncloud/ios/issues/57) it is mentioned, too.

Sorry I'm not an iOS Developer :(

**Comment by marinofaggiana** [comment]
@seraphyn is't a problem of iOS Developer, this is a problem of usability for users for create an option for this example : VACATIONS_FRANCE%Y%M%D_%H%M%S_ etc ... 

Create you a subfolder VACATIONS FRANCE and put your image.

For exifdata a.e.IMG%Y%M%D_%H%M%S_  i add this in to.do

**Comment by khlschrnk** [comment]
filename of uploaded images should use timestamp of image - this would be great!

**Comment by cal940** [comment]
an option to type in a custom filename would be great (not only for images).

**Comment by marinofaggiana** [comment]
feature already present in 2.17 beta 😄

**Comment by cal940** [comment]
ok, but right now I'm not in the program.

I already sent a request for that (see #72)

**Comment by cal940** [comment]
@marinofaggiana: You  wrote me that there already is a way to set a custom filename on the 2.17 beta, but I can't find an option for that.

**Comment by marinofaggiana** [comment]
Upload a new file ...

**Comment by cal940** [comment]
I already tried it with 2 email attachments (pdf and image)

**Comment by marinofaggiana** [comment]
done.
