### ISSUE TITLE
App crashes when trying to upload file

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#120]
1. Press +-Button
2. Select "upload file" from dialog
3. App closes withoud any message

Version 2.17 (0031)
System language: german

@marinofaggiana Do you have crash reporter included in given version? How to provide best feedback for you?

**Comment by marinofaggiana** [comment]
yes @rakekniven I know, new version correct this issue.

**Comment by rakekniven** [comment]
Any words regarding crash reporter?

**Comment by marinofaggiana** [comment]
excuse me @rakekniven, with TestFlight I see the crash log 

<img width="1019" alt="schermata 2017-03-21 alle 20 51 23" src="https://cloud.githubusercontent.com/assets/8616947/24167750/31d7a636-0e78-11e7-8fc7-45ff007c15fd.png">

**Comment by rakekniven** [comment]
Oh, first thought was "Hey, that is my good old 5s". But model ID differs.
