### ISSUE TITLE
What does this code do in OCCommunicationLib/Utils/NSString+Encode.m?

### ISSUE THREAD

**Issue by jamesstout** [nextcloud/ios#1207]
After creating a new string with `CFURLCreateStringByAddingPercentEscapes` it loops through the whole string, and lowercases the two characters after a %? Is that right? If so, what's the reasoning? Just interested as I was looking at replacing `CFURLCreateStringByAddingPercentEscapes` as it's deprecated and wondered why we had this code to lowercase some chars.

https://github.com/nextcloud/ios/blob/b738135e785b5e4b0fb5ab871297863ab4a65656/iOSClient/Library/OCCommunicationLib/Utils/NSString%2BEncode.m#L42-L62

The RFC for URIs re [percent-encoding](https://tools.ietf.org/html/rfc3986#section-2.1) says:

> The uppercase hexadecimal digits 'A' through 'F' are equivalent to the lowercase digits 'a' through 'f', respectively.  If two URIs differ only in the case of hexadecimal digits used in percent-encoded octets, they are equivalent.  For consistency, URI producers and normalizers should use uppercase hexadecimal digits for all percent-encodings

So I wonder why we lowercase them?

In my tests to replace `CFURLCreateStringByAddingPercentEscapes` with `stringByAddingPercentEncodingWithAllowedCharacters` and not loop through the string to lowercase, it performs ~1400% faster. (0.7s for 10000 iterations using old code, 0.05s for 10000 iterations with new code, without lowercasing, it's about the same if I lowercase as well.)

thanks

**Comment by marinofaggiana** [comment]
Hi @jamesstout this is the old library of owncloud, we are migrating to this:

https://github.com/nextcloud/ios-communication-library

Cheers

**Comment by jamesstout** [comment]
Aw man, does this mean I'm finally going to have to learn Swift properly? ;)
