### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#121]
Next beta version 2.17 are activate the Activity server & client mode Ver 0.1 , for look the transfers of Nextcloud iOS and, why not, the debug for developer team : 

On Settings/Help new option : 

![simulator screen shot 21 mar 2017 16 56 15](https://cloud.githubusercontent.com/assets/8616947/24156755/c2d2ced4-0e57-11e7-88f6-5c51533986d2.png)

On Control Center : 

![simulator screen shot 21 mar 2017 16 55 47](https://cloud.githubusercontent.com/assets/8616947/24158677/43b68d56-0e5d-11e7-9a84-7bf471431131.png)

Please, make test for this new and just burn feature.

Thanks

**Comment by marinofaggiana** [comment]
@MorrisJobke ping

**Comment by rakekniven** [comment]
@marinofaggiana What does "Activity verbose high" mean? Could you please explain?
Need it for translation and understanding.

btw. the bomb is here as well

**Comment by marinofaggiana** [comment]
ihhihihihih 💣 
Verbose high = more information and more detail for event for example 
add "selector" status,   
date with HH:MM:SS, 
minor event in error but important for debug.

This option isn't for the normal user.

**Comment by rakekniven** [comment]
We are all not normal at all ;-)

Do you have verbose, verbose high and Most verbose?

Idea : Verbose activity output

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers for input - maybe @jancborchardt can also check this out.

**Comment by MorrisJobke** [comment]
But the Activity pane itself looks good :)

**Comment by enoch85** [comment]
> Verbose activity output 

:+1: 

Other suggestions:
- Detailed Activity Feed
- (edit this comment)

**Comment by marinofaggiana** [comment]
Show more information ?

**Comment by rakekniven** [comment]
> Show more information ?

For me this is very general.

**Comment by enoch85** [comment]
> For me this is very general.

@marinofaggiana is the Activity Feed always the same, or is it even more detailed if you flip the switch?

**Comment by marinofaggiana** [comment]
more detail and more event

**Comment by enoch85** [comment]
@marinofaggiana Ok thanks, then I think `Detailed Activity Feed` is the correct term to use. @rakekniven what do you think?

**Comment by rakekniven** [comment]
> Detailed Activity Feed
Like it and it hits the bullet.

**Comment by marinofaggiana** [comment]
ok.

**Comment by jancborchardt** [comment]
I’d remove the verbosity option for sure. We don’t have that on the web interface and won’t in the Android app either. Let’s keep it simple please. :)

@marinofaggiana can you show a screenshot of the non-verbose normal activity view? Is it possible to also use relative dates like »Today« and »Yesterday« etc?

**Comment by marinofaggiana** [comment]
@jancborchardt please before download last beta. all options have a reason, Ee have to study them

**Comment by jancborchardt** [comment]
@marinofaggiana what _is_ the reason though? It seems to be for debugging and should not be in a release. We strive to design stuff simply to focus on the essential info.

Again:

> We don’t have that on the web interface and won’t in the Android app either. Let’s keep it simple please. :)

**Comment by marinofaggiana** [comment]
@jancborchardt this option it's important for for customer problem debug, registered several info  ... what do you think ?

**Comment by jancborchardt** [comment]
@marinofaggiana as discussed, let’s maybe put it in an »Advanced« section. :)

**Comment by marinofaggiana** [comment]
@jancborchardt  (in build)

![schermata 2017-04-12 alle 14 47 44](https://cloud.githubusercontent.com/assets/8616947/24958255/023d6c76-1f8f-11e7-99f4-f7501dafbb5a.png)

**Comment by jancborchardt** [comment]
Great work @marinofaggiana! :) Will open small design issues separately, after I checked the new Testflight version.

**Comment by marinofaggiana** [comment]
Great work tanks to you @jancborchardt

**Comment by marinofaggiana** [comment]
Close this issue. 
Open a new ticket for build 38
