### ISSUE TITLE
Design refresh

### ISSUE THREAD

**Issue by JorisBodin** [nextcloud/ios#1218]
Hello,

After discussion with @marinofaggiana and @jancborchardt, here are our mokups to refresh the current design.
The iOS and Android apps will be aligned designwise.
https://infomaniak.invisionapp.com/share/AQWL9RLZR6G#/410807685_App_Nextcloud_IOS_-_Home

In the new design only the header bar is going away, the rest should still be themed.

Android: https://github.com/nextcloud/android/issues/5207

**Comment by jancborchardt** [comment]
Perfect, thanks a lot @JorisBodin! :)

**Comment by jancborchardt** [comment]
This was mostly done back then, so let’s close it. :)
