### ISSUE TITLE
No data available

### ISSUE THREAD

**Issue by DenisRuss93** [nextcloud/ios#1226]
in the new TestFlight Version (35) are no Data in the Nextcloud 
If I downgrade to (24) are all data available 

![68CA3E90-B63A-41EA-BE33-AB2DB833ED4A](https://user-images.githubusercontent.com/49836741/80260750-e2fb0f80-8688-11ea-9e6a-e2d74535d252.png)

**Comment by MaestroJAL** [comment]
Me too. I've had this issue for the last couple of beta builds. All other ways (web interface, WebDAV, etc.) seem to work fine.

This morning I very briefly noticed a 500 error pop up behind the beta testing splash screen. It does not show after, even if I quit the app and reload.

**Comment by marinofaggiana** [comment]
Please test with Build 36.

**Comment by DenisRuss93** [comment]
Thank you
Now it works again!
