### ISSUE TITLE
Issue from Transifex:  Wi-Fi network required, %lu %@ to upload

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#124]
Hello @marinofaggiana ,

just working to decrease open issues on transifex and only one is iOS app related.

String: Wi-Fi network required, %lu %@ to upload
Question: What %lu and %@ means?

Thank you for enlighten us.

**Comment by rakekniven** [comment]
@marinofaggiana Would be nice if you could spent a minute here.

**Comment by marinofaggiana** [comment]
%lu = number
%@ = element or elements (if > 1)

![2017-03-25 11-09-42 4339](https://cloud.githubusercontent.com/assets/8616947/24321406/3f2192b2-114c-11e7-805f-e5bbfd64d0d1.png)

**Comment by marinofaggiana** [comment]
@rakekniven close ?

**Comment by rakekniven** [comment]
Yes, referrenced issue at github comment.
