### ISSUE TITLE
Remove From Camera Roll After Successful Upload

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1240]
*** For now only in Test ***

**Description:**

In case of successful auto upload a message will require the deletion of the photos or videos from the camera roll, remember that the deleted photos or videos will be available for 30 days in the trash.

![20-05-09 14-44-39 9638](https://user-images.githubusercontent.com/8616947/81474214-21a1d580-9204-11ea-87c7-11c532136a59.png)

[ TestFlight V 3 build 46 ]

**Comment by Happyfeet01** [comment]
Nice

**Comment by HobbledGrubs** [comment]
This would be great but I would love to see a verification system first.  I have a lot of images and videos which are uploaded corrupted.  The files probably failed during upload due to poor connection quality.   We are using a S3 type backend which could also be causing trouble internally for Nextcloud.  The S3 backend is used for hundreds of other services which are not experiencing file corruption.     
Ultimately I would love to delete files off my phone but only if I was 100% sure they had been correctly uploaded.  Is there any verification process available? eg. checksum?

**Comment by marinofaggiana** [comment]
@HobbledGrubs https://github.com/nextcloud/server/issues/11138

**Comment by Happyfeet01** [comment]
Is the V3 46 build not available at the TestFlight? The latest version is 3.0.0 45.

**Comment by marinofaggiana** [comment]
today.

**Comment by Happyfeet01** [comment]
Thanks

**Comment by HobbledGrubs** [comment]
@marinofaggiana thanks I had completely forgotten about that issue.  No sign of it getting into NC 18 yet.

**Comment by rakekniven** [comment]
Hello @marinofaggiana ,

first question.
Is the following dialog mandatory on iOS?
Can we also omit the dialog and automatically delete the pictures after successful upload?
<img width="375" alt="PNG-Bild" src="https://user-images.githubusercontent.com/2069590/81809772-304cfd00-9522-11ea-8324-e51e44292e7e.png">

I would like to adjust text for this option. There has been a question at Transifex regarding the meaning. Need to get the answer of first question to do that.
<img width="375" alt="2020-05-11 13-52-53-1" src="https://user-images.githubusercontent.com/2069590/81809782-3347ed80-9522-11ea-8b23-78f95667f657.png">

btw: Images taken on dark iOS 13.4.1 using iPhone 8

**Comment by rakekniven** [comment]
Forgot to add: I really appreciate this option. Thank you.

**Comment by marinofaggiana** [comment]
> first question.
> Is the following dialog mandatory on iOS?

Yes

> Can we also omit the dialog and automatically delete the pictures after successful upload?

No

> I would like to adjust text for this option. There has been a question at Transifex regarding the meaning. Need to get the answer of first question to do that.

Ok, now I look

**Comment by marinofaggiana** [comment]
@rakekniven I don't find the question in Transifex ...

**Comment by rakekniven** [comment]
@marinofaggiana See https://www.transifex.com/nextcloud/nextcloud/translate/#af/$/290402437?q=issue%3Aopen

Is the dialog created by you or a system dialog from iOS?

**Comment by marinofaggiana** [comment]
> @marinofaggiana See https://www.transifex.com/nextcloud/nextcloud/translate/#af/$/290402437?q=issue%3Aopen
> 
> Is the dialog created by you or a system dialog from iOS?

System dialog from iOS, it's standard and not uneditable

**Comment by rakekniven** [comment]
Just typed a proposal for the message at Transifex. What do you think?

**Comment by rakekniven** [comment]
>not uneditable
You mean "not changeable", or?

**Comment by marinofaggiana** [comment]
yes, not possible nothing... the message box compare automatically after the request for delete a one or more photo

**Comment by rakekniven** [comment]
Is it the same for photes and videos?

Have you seen my posting 20 minutes regarding the text proposal?

**Comment by marinofaggiana** [comment]
> Is it the same for photes and videos?

yes 

> 
> Have you seen my posting 20 minutes regarding the text proposal?

"In case of a successful automatic upload, a message confirmation is required to delete the photos or videos from the camera roll. Remember that the deleted photos or videos are available in the Trash for 30 days."

good for me, I change it.

**Comment by rakekniven** [comment]
Thank you!

**Comment by Valdnet** [comment]
@marinofaggiana In Transefix the dot is missing at the end of the sentence. Can you improve?
Thank you.

**Comment by Happyfeet01** [comment]
works really good 👍

**Comment by rakekniven** [comment]
@marinofaggiana It does not work anymore since Testflight v3.0.0.70. Have you removed the feature for release?

Can anybody else please test?

**Comment by marinofaggiana** [comment]
yes sorry, a little bug, roll back it next build  :-)

**Comment by rakekniven** [comment]
Works again with build 3.0.0.72 👍

**Comment by harbdans** [comment]
This option seems to have been removed from the latest version of the app. Is this happen with others also?

**Comment by marinofaggiana** [comment]
> This option seems to have been removed from the latest version of the app. Is this happen with others also?

It's in Settings/Advanced and now works for all upload (non only for the auto upload)

**Comment by harbdans** [comment]
Worked for me too. Thanks
