### ISSUE TITLE
App crashes when server responds with a 500

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#125]
* configure the app
* cause a 500 error on the server (in this case the LDAP server was down) causing this:

```
HTTP/1.1 503 Service Unavailable

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>
  <s:message>OC\ServerNotAvailableException: Lost connection to LDAP server.</s:message>
</d:error>
```

@marinofaggiana Please fix this. This is quite high, because I can't use the app anymore (even remove the malicious account is not possible, because the app immediately crashes).

**Comment by marinofaggiana** [comment]
mmm I need a service test for this issue.

**Comment by MorrisJobke** [comment]
What do you need for this? How can I help?

**Comment by MorrisJobke** [comment]
@marinofaggiana Any news on this one?

**Comment by marinofaggiana** [comment]
@MorrisJobke I need, if possible, an server that's return this error for identity where is the point.

**Comment by MorrisJobke** [comment]
Just put the server in maintenance mode ;)
