### ISSUE TITLE
New ( + ) in Tab Bar

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1255]
![Senza nome](https://user-images.githubusercontent.com/8616947/81837413-2092e000-9545-11ea-806e-e5a55f5e5bbc.png)

@immortal79 if I touch up the read line (limit of tab bar) touch the Cell and not the button [+]

**Comment by marinofaggiana** [comment]
Good but not is not transparent 

![F8D10C07-4F29-4D4D-BA0F-D6139507E0C3](https://user-images.githubusercontent.com/8616947/81932271-d3b61480-95eb-11ea-9b52-afa48dbae3bc.jpeg)

**Comment by joshtrichards** [comment]
Fixed in #1257
