### ISSUE TITLE
Go back even if folder is currently loaded

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#130]
* browse into a folder that has a lot of entries (which takes some time to load)
* I don't want to wait for this to finish, but immediately go back again
* expected: pressing the back button in top left leads to parent folder
* actual: loading circle is there and the UI doesn't react at all

**Comment by melikyuksel** [comment]
Seems to work now. I can go back even while a folder’s contents are still being loaded and the spinner is visible. I think this can be closed.
