### ISSUE TITLE
Don't show empty user information fields

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#131]
* expected: only list fields that are actually set
* actual: all fields are set (I only modified the email address)

![2017-03-22 00-47-50 3285](https://cloud.githubusercontent.com/assets/245432/24185570/6fb3e12e-0e99-11e7-8541-f0eb99f22c7b.png)

**Comment by timbru31** [comment]
Instead it would be assume to be able to edit/add these information instead.

**Comment by MorrisJobke** [comment]
> Instead it would be awesome to be able to edit/add these information instead.

I would say, that this is a separate enhancement request.

**Comment by cal940** [comment]
> I would say, that this is a separate enhancement request.

I think it's ok. Too many requests are confusing.

**Comment by marinofaggiana** [comment]
@MorrisJobke this is not a bug.

**Comment by MorrisJobke** [comment]
Fixed with 3cc81a0

**Comment by MorrisJobke** [comment]
@marinofaggiana Tip: next time use "fixes #NUMBER" in the commit message to automatically close the issue when the commit enters the master branch - https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by timbru31** [comment]
I'd like to re-open this issue: When no user information is entered/added at all (e.g. synced from LDAP) then the section is completley empty and misleading.
@MorrisJobke What do you think?

See attached screenshot (iOS 10.3, iPhone 7, Nextcloud v2.17 (35)

---
![img_1514](https://cloud.githubusercontent.com/assets/838003/24614513/b954beba-188b-11e7-805a-80fb5e4ebf91.PNG)

**Comment by marinofaggiana** [comment]
@timbru31 this view will be rebuild.
