### ISSUE TITLE
End-to-end encryption broken on version 3

### ISSUE THREAD

**Issue by th3m** [nextcloud/ios#1317]
After the version 3 update the e2e encryption seems broken. It was enabled before the update and worked fine, after the update it stayed enabled but it wasn't working as intended.

 I could encrypt an empty folder, but afterwards that folder seemed completely locked, with broken desktop syncing, and when i try to decrypt it, i get the red msg of operation failed no permission.

I disabled e2e encryption on the iOS app, and now when i try to enable it back, after i enter the 12 word phrase the app crashes and e2e encryption cant be enabled anymore.

**Comment by Tucubanito07** [comment]
Did you fix this? I don't see the option for end to end encryption any more on the app.
