### ISSUE TITLE
Adjust icon set to our icon set

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#132]
* use for example the Nextcloud folder icon (like on Android and in the web UI

cc @jancborchardt 

currently:

![2017-03-22 00-52-47 3286](https://cloud.githubusercontent.com/assets/245432/24185675/1108305c-0e9a-11e7-8157-88694ab17047.png)

Android and web:

<img width="328" alt="bildschirmfoto 2017-03-22 um 00 53 17" src="https://cloud.githubusercontent.com/assets/245432/24185652/f48e90f6-0e99-11e7-9c9b-ce9b31585dc3.png">

![files_grid](https://cloud.githubusercontent.com/assets/245432/24185655/f7bacefc-0e99-11e7-8e40-8f078807e2c4.png)

**Comment by rakekniven** [comment]
This issue is solved, or?
@marinofaggiana Would you like to work with "releases" on github? I can help and support/guide you.

**Comment by MorrisJobke** [comment]
> This issue is solved, or?

Yes.


![2017-03-24 11-19-46 3294](https://cloud.githubusercontent.com/assets/245432/24305860/1235d740-1084-11e7-96f6-034b28bdbb50.png)


> @marinofaggiana Would you like to work with "releases" on github? I can help and support/guide you.

This would be awesome to help @marinofaggiana with that and also with changelings. Currently there are changelogs in the test flight, but maybe have them here as well would be super nice.

**Comment by marinofaggiana** [comment]
@rakekniven ohhh! Yes !! Thanks a lot !!

**Comment by jancborchardt** [comment]
@MorrisJobke was a duplicate of https://github.com/nextcloud/ios/issues/67 btw ;)
