### ISSUE TITLE
Offline files broken once again

### ISSUE THREAD

**Issue by yadayadaydadaa** [nextcloud/ios#1333]
Once again the latest update completely broke offline files. Accessing any directories via Files.app complains that “no can do, we’re offline”.  Yet the files are there and available through the shitty NextCloud  app itself. Just not in other apps. 

This project is such utter and total garbage, every update breaks something, half-fixed in next update, once again broken in the following one.

**Comment by marinofaggiana** [comment]
offensive content

**Comment by yadayadaydadaa** [comment]
> offensive content

Offensive project that doesn't respond to bug reports, never fixes bugs, and just keeps filling the app with internal garbage.
