### ISSUE TITLE
Recent files tab

### ISSUE THREAD

**Issue by cal940** [nextcloud/ios#134]
In the new beta (2.17) there is a tab for photos.

 My idea is to switch between photos and recent files (just like in the favs tab).

**Comment by cal940** [comment]
Otherwise you can also integrate an option for activities (like in webgui) instead of recent files.

**Comment by MorrisJobke** [comment]
> Otherwise you can also integrate an option for activities (like in webgui) instead of recent files.

@marinofaggiana That is what I meant with "Nobody will find the activities pane". 

The activities can be found to the right of the uploads (swipe down from the header).

cc @jancborchardt @oparoz

**Comment by marinofaggiana** [comment]
new intro ...

![1](https://cloud.githubusercontent.com/assets/8616947/24222390/2d361baa-0f52-11e7-95f4-964b12e9bc32.png)

![simulator screen shot 22 mar 2017 22 51 15](https://cloud.githubusercontent.com/assets/8616947/24222397/317f46aa-0f52-11e7-916b-570286fb1cfe.png)

**Comment by MorrisJobke** [comment]
> new intro ...

This is still not user friendly UX. Maybe you should go over the app with @jancborchardt next week :)

**Comment by rakekniven** [comment]
Missed this issue.
Have the same thoughts.

**Comment by jancborchardt** [comment]
Yeah, I agree this is not obvious. We shouldn’t need to introduce design decisions in the intro, which might be skipped.

Transfers/Activities should definitely be an entry in the menu on the bottom, just like it is in the Android app in the sidebar.

Account switching is interesting via the header – can we do that via the avatar like on Android to have a signifier? It’s not very obvious that the header is clickable. Should be in the bottom bar too, in extended options.

**Comment by MorrisJobke** [comment]
> Transfers/Activities should definitely be an entry in the menu on the bottom, just like it is in the Android app in the sidebar.

The bottom menu is full. There only fits 4-5 entries. I guess we need the sidebar 🙈 Maybe you sit together during this week and look at the current state of the app together.

**Comment by marinofaggiana** [comment]
iOS is not Android, please, read 
https://developer.apple.com/ios/human-interface-guidelines/overview/design-principles/

No sidebar :-)

**Comment by jancborchardt** [comment]
This is a very cool solution that another open source app ([Maps.me](http://maps.me)) uses.
Last icon on the bottom right is »More« and clicking on it moves the bottom bar up to expose a list with more entries:
![](http://a4.mzstatic.com/us/r30/Purple82/v4/5d/3e/89/5d3e8967-5a3d-245c-3607-3795e7474fad/screen696x696.jpeg) ![](http://a3.mzstatic.com/us/r30/Purple122/v4/d4/21/cc/d421cca5-871e-2196-84e5-868222ab932d/screen696x696.jpeg)

What do you think @marinofaggiana?

**Comment by marinofaggiana** [comment]
@jancborchardt tomorrow we see it together

**Comment by rakekniven** [comment]
Hey, just for the records:
I am a heavy user of wrike, a project management too.
See how their app looks like:

![2017-04-18 12-06-11 0146](https://cloud.githubusercontent.com/assets/2069590/25546080/be523bec-2c61-11e7-9111-d2d9c93aebe3.png)

Nextcloud has some similarity.

@marinofaggiana @jancborchardt What do you think about the darkened background on the bottom to highlight where you are?

**Comment by MorrisJobke** [comment]
> @marinofaggiana @jancborchardt What do you think about the darkened background on the bottom to highlight where you are?

I guess a new issue is better suited to discuss enhancements 😉

**Comment by jancborchardt** [comment]
Yep, new issue is always better. However I would say a lighter bar on the bottom just also gives a lighter feel. :) The standard blue bar at the top is enough already, having that at the bottom too would make it feel boxed in.
