### ISSUE TITLE
E2E: shows uuid named files/folders first

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#1342]
- set up e2e
- go into a folder with lots of encrypted files
- see first encrypted file names
- manually refresh to see decrypted names

**Comment by marinofaggiana** [comment]
@tobiasKaminsky version of Nextcloud ios ?

**Comment by tobiasKaminsky** [comment]
latest Testflight, so 3.0.1 (17)

**Comment by marinofaggiana** [comment]
fixed
