### ISSUE TITLE
Error in String "Is not possible move files to encrypted directory"

### ISSUE THREAD

**Issue by JSoko** [nextcloud/ios#1354]
In transifex there ist the string
"Is not possible move files to encrypted directory"

Shoudn#T this string be corrected to
"It is not possible move files to encrypted directory"

https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/295934839?q=text%3A'Is+not+possible+move+files+to+encrypted+directory'

**Comment by marinofaggiana** [comment]
Good, done. thanks
