### ISSUE TITLE
Switch accounts in icloud drive/import window

### ISSUE THREAD

**Issue by cal940** [nextcloud/ios#136]
![](http://i.imgur.com/jVGQzGL.jpg)

**Comment by marinofaggiana** [comment]
Why you do not use share extension ? 

http://www.imore.com/sharing-ios-8-explained

**Comment by cal940** [comment]
Because it would be the same. Right now I use 5 different accounts in the app. And I want to switch the accounts easily than I upload a file. Right now I have to open the app first an select the right account.
