### ISSUE TITLE
Cannot upload live photos correctly

### ISSUE THREAD

**Issue by atomusr** [nextcloud/ios#1367]
This is on the latest nextcloud version 19.01, iOS App 3.0.3 and also the non-test flight version....both versions have the same issue.

When I select 100 photos to upload (some live photos), the upload counter on the bottom of the app shows 300+ files and then as the upload counter starts decreasing, it's showing a error "Error photo/video not found, removed from upload". When I checked what has been actually uploaded, almost all of the live photos are missing the video file. Only 1 live photo was correctly uploaded, the rest are missing the video file. It looks like when it splits the HEIC file to JPG and MOV components, either the MOV file goes missing OR the app is checking the wrong path etc.

I have the following options turned on in the app: Most Compatible, Live Photo, Disable Files App Integration, Disable local cache.

**Comment by marinofaggiana** [comment]
Thanks @atomusr,
for try it:  https://testflight.apple.com/join/GjNbfo2a

**Comment by atomusr** [comment]
@marinofaggiana , this time it uploaded all the images and videos for the live photos without any errors.

However, all of the videos for the live photos are the wrong video. It is uploading the same exact video for all the live photos which is wrong.

**Comment by marinofaggiana** [comment]
Haha this is very strange ... cache problem ... maybe ... I don't have this issue in my test

**Comment by marinofaggiana** [comment]
Maybe... wait next build.
Thanks

**Comment by atomusr** [comment]
Just tried 3.0.3 (6), same issue. All of the live photos have the same video (wrong video).

**Comment by marinofaggiana** [comment]
Something in cache is corrupt ... can you clear cache or reinstall the App.

**Comment by atomusr** [comment]
Just delete the cache and tried, same result.

Then uninstalled the app completely, reinstalled it and used the default settings and tried it. Same result.

Does it work for you when you try to upload 100 live photos?

**Comment by marinofaggiana** [comment]
Have you look the "MOV" file in server Nextcloud ? it's the same video ? (with different name file)

**Comment by marinofaggiana** [comment]
P.S. happen only with 100 ??

**Comment by atomusr** [comment]
It's the same video with different file name. I tried uploading just 5 live photos, same result. All 5 photos have the same MOV video file uploaded but with different file names.

**Comment by marinofaggiana** [comment]
try, create new 5 photos end upload this new 5 photo

**Comment by atomusr** [comment]
Weird. So I did the following:  reinstalled the app 3.0.3 (6), took 5 new live photos and uploaded them. This time, ALL of the live photos uploaded correctly with the correct matching video.

I tried with the old live photos and it uploaded the wrong video.

Do you know what it could be causing this?

**Comment by marinofaggiana** [comment]
No! Sorry. (Reopen if you have more data)

**Comment by atomusr** [comment]
@marinofaggiana I just tried version 8 today and now it works! All of the live photos have the correct matching MOV file uploaded.
