### ISSUE TITLE
Option to add a new Nextcloud account is too hidden

### ISSUE THREAD

**Issue by timbru31** [nextcloud/ios#137]
The option to add a new Nextcloud account is very well hidden and a normal user won't find this place.
It's under `Settings -> Change your credentials`

The UX of the location to add something **new** by visiting a page to manage a **current** account is terrible. (And I'm a developer, too - so I like functional design ;))

**Comment by rakekniven** [comment]
I am use too it. But @timbru31 is right IMHO. Account management could be improved. Not priority 1 at the moment I thing. New version has so many features and changes. Time for feature freeze :-)

**Comment by ho1ger** [comment]
Cool, this feature exists!? Didn't find it in the first place.

Maybe switching between accounts could be done using force push? That would be very elegant.

**Comment by marinofaggiana** [comment]
Change Settings. This post il old. Close

**Comment by timbru31** [comment]
@marinofaggiana Could you clarify? Have you changed the location to add new user accounts?

**Comment by marinofaggiana** [comment]
yes ( @jancborchardt remove section "cloud account" on Settings)

https://cloud.twsweb.it/index.php/s/HVz556Kk9duHw5r
