### ISSUE TITLE
IOS 14.0 (18A5342e)

### ISSUE THREAD

**Issue by Tucubanito07** [nextcloud/ios#1376]
I have iOS 14 installed on my device and the version of (3.0.3 CLOSE VERSION) keeps crashing when it has to upload items. I know iOS 14 is not supported but wanted to let the developers know and I can help test if needed be.

**Comment by Tucubanito07** [comment]
![image](https://user-images.githubusercontent.com/54116766/89695662-ce165500-d8e2-11ea-8de7-aeee7909e1c8.jpeg)

This is what keeps happening to me.

**Comment by marinofaggiana** [comment]
Yes, not compatible yet, too many library are not compatible with the Xcode 12.

**Comment by Tucubanito07** [comment]
> Yes, not compatible yet, too many library are not compatible with the Xcode 12.

Do you by any chance know when will you guys have something for this? Not in a hurry just want to know.

**Comment by crazybadger** [comment]
3.0.1 onwards isn't all the compatible with iOS 13 either!  What changed between 3.0.0 and 3.0.1 to cause the upload and freezing issues, as it worked fine in the first release?
