### ISSUE TITLE
Q: What is the capability "Paginated file listing"?

### ISSUE THREAD

**Issue by Alphakilo** [nextcloud/ios#1378]
I found this in the `Capabilities` section, under `Settings`, `Advanced`. 
Couldn't find any reference in the (Server) Docs.

### App version
3.0.3.9

**Comment by jippi** [comment]
Bump - spent like 30min trying to google this up

**Comment by marinofaggiana** [comment]
Hi sorry for the delay, it's a module only in test for the "Files" app of Apple; not available yet.

**Comment by Alphakilo** [comment]
Thanks!
