### ISSUE TITLE
Copy text from pdf

### ISSUE THREAD

**Issue by cal940** [nextcloud/ios#138]
At the moment u can't copy text from pdf files to the clipboard.

**Comment by enoch85** [comment]
@cal940 Have you tested the latest version? Does it work?

**Comment by the-sane** [comment]
@marinofaggiana Using the current beta v2.23.8.15, I am not able to select text in a pdf to copy it.  I tried the standard methods: force pressing and long pressing, and also various combinations of frantic tapping and swiping just for thoroughness.  This remains an issue.

**Comment by Daenou** [comment]
It seems like this problem is this occurring, a customer complained that you cannot open Hyperlinks from a pdf.

**Comment by Daenou** [comment]
Any news on when this will be fixed?

**Comment by marinofaggiana** [comment]
Please try with the version 3 in TestFlight

**Comment by johkoenig** [comment]
Fixed on v3.0.10 (or earlier)
