### ISSUE TITLE
Upload failes from ios, Can't upload nor photo neither video+IOS app 3.0.3 hangs

### ISSUE THREAD

**Issue by alex-roma** [nextcloud/ios#1383]
Server configuration detail
Operating system: Linux 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64
Webserver: Apache/2.4.38 (Debian) (apache2handler)
Database: sqlite3 3.27.2
PHP version: 7.4.7
Nextcloud version: 19.0.0 - 19.0.0.12
ios 3.03

**Comment by alex-roma** [comment]
![photo_2020-08-10_14-34-57](https://user-images.githubusercontent.com/69501728/89867601-1327d900-dbba-11ea-89c4-4d30ba4c027f.jpg)

**Comment by alex-roma** [comment]
{"reqId":"w8EoIAhqvBh4hEaO9xWE","level":3,"time":"2020-08-10T20:44:49+00:00","remoteAddr":"134.249.120.13","user":"admin","app":"PHP","method":"DELETE","url":"/remote.php/webdav/%D0%90%D1%80%D1%85%D0%B8%D0%B2/Toesto/IMG_0432.JPG","message":"rename(//data/Toesto/IMG_0432.JPG,//var/www/html/data/admin/files_trashbin/files/IMG_0432.JPG.d1597092289): Operation not permitted at /var/www/html/lib/private/Files/Storage/Local.php#339","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/3.0.3","version":"19.0.0.12","id":"5f324554da5df"}

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/1377
