### ISSUE TITLE
Split view support for iPad

### ISSUE THREAD

**Issue by cal940** [nextcloud/ios#139]
![](http://i.imgur.com/Tn02qNu.jpg)

**Comment by marinofaggiana** [comment]
Please ?

**Comment by cal940** [comment]
Sorry, I meant split view.

This feature is available since iOS 9 for the iPad.

**Comment by marinofaggiana** [comment]
Close this, if for you it's ok.

**Comment by cal940** [comment]
Why should I ? In my opinion the issue isn't solved yet.

I already use an cloud (client) app named [Micro Focus Filr](https://appsto.re/de/s6ouI.i) which support split view.

**Comment by MariusBluem** [comment]
Split View is supported on iPads and the newest Nextcloud app for iOS :)
