### ISSUE TITLE
PDF files are not recognized

### ISSUE THREAD

**Issue by tiitschei** [nextcloud/ios#1398]
PDF files are not recognized. The thumbnail remains gray. Clicking on it will not open the file, but it will select to share the file. I can't open the pdf in the app. I have to export it to another app to be able to read it. Reinstallation did not help. Other file types work fine. All other files I can open normally. Only PDF not.
When I use another iPhone-app to access the Nextcloud, for example "FE File Explorer", everything works normally.
Thanks for your help!
Kind regards 
Thomas Wettstein

_Originally posted by @tiitschei in https://github.com/nextcloud/ios/issues/1336#issuecomment-654221998_

**Comment by marinofaggiana** [comment]
Hi @tiitschei .. do you have installed in your iPhone some app that use the PDF ?

We use the Apple UTI for decode the extension:

https://github.com/nextcloud/ios-communication-library/blob/432171924ef7170bdfce3e0aa5f1f3822dc58dda/NCCommunication/NCCommunicationCommon.swift#L221

**Comment by tiitschei** [comment]
Hi Marino, thanks for the hint. I actually already suspected pdf-apps, but none of the installed apps were the cause. Now after your reply I searched again and found the XPS program "XPSView". After I deleted this, it works again!
Special is that I have installed this program for a long time, but so far without problems.
Anyway thanks a lot for the help
Thomas
