### ISSUE TITLE
Allow to create new folder when uploading files

### ISSUE THREAD

**Issue by tflidd** [nextcloud/ios#14]
Steps to reproduce:

1. Select photos you want to upload
2. Choose to pass them to Nextcloud
3. Navigate to destination folder

Here I wanted to create a new folder to place the files. I don't have such a button, the owncloud ios-client could do this and I used it often.

**Comment by marinofaggiana** [comment]
Hi @tflidd  User this : 

![schermata 2016-12-16 alle 17 35 02](https://cloud.githubusercontent.com/assets/8616947/21270230/00cdd586-c3b6-11e6-89c5-cee726b5b148.png)

**Comment by tflidd** [comment]
I don't use the automatic upload (yet). So I suppose you would have this problem if you pass a file from any app to Nextcloud, it will be this problem.

**Comment by marinofaggiana** [comment]
ops. @tflidd I did not understand your request for create new folder when upload file. ok !

**Comment by marinofaggiana** [comment]
Done.
