### ISSUE TITLE
App crashes on iPad Pro when activating "Favorites available offline" in settings

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#143]
Steps to reproduce:

1. Open app
2. Go to settings
3. Enable config switch "Favorites available offline"
4. App crashes

App version: V2.17 (0033) Testflight user
iOS version: 10.2.1

**Comment by marinofaggiana** [comment]
@rakekniven it is repeatable ?

**Comment by rakekniven** [comment]
Yes, tried it 5 times. Rebooted iPad as well. Can you get details via Testflight?

**Comment by rakekniven** [comment]
Will try it on next Testflight release. 
Miss the daily update ;-)
