### ISSUE TITLE
Files are not moved

### ISSUE THREAD

**Issue by lisetauber** [nextcloud/ios#1433]
Hello Marino, 
I already noticed this bug via TestFlight. 
As I wish to move photos from the directory Photo/2020/10 to another one, only one is moved, the others stay in he initial directory. 

Nextcloud 3.0.10 (4)
iPad Air 3, iPadOS  

![IMG_2527](https://user-images.githubusercontent.com/31109077/95000496-944f8b00-05c1-11eb-8adf-d87db010befc.jpeg)
![IMG_2528](https://user-images.githubusercontent.com/31109077/95000501-987ba880-05c1-11eb-9e0c-d010decfd26f.jpeg)

**Comment by marinofaggiana** [comment]
Hi ! @lisetauber I have try but I don't have this issue ... I don't understand, this happen only in  " Photo/2020/10 " folder ?

**Comment by lisetauber** [comment]
Hello Marino, 

Thanks for your answer!
No, it happens with other folders! but only if I create a new directory to move photos  to this  directory. 

If I create a new folder,  photos cannot be moved anymore (sometimes. only one is being moved). 
If I relaunch the app, I can move photos again.

**Comment by lisetauber** [comment]
With the last beta, 3.0.10 (5), all the screen captures are not being uploaded to the server. 

Nextcloud 3.0.10 (4)
iPad Air 3, iPadOS 14.0.1

![F9FAE02D-DA3C-4349-8F3A-2DD986685A3A](https://user-images.githubusercontent.com/31109077/95012617-593d6e00-063a-11eb-93f0-c81f32e752b4.jpeg)

**Comment by marinofaggiana** [comment]
?  please ?

**Comment by lisetauber** [comment]
I did some screen captures, they are normally automatically uploaded to the server, as other photos. 

But, as as you can see on the last screen capture, 0 bits from one image are 'uploaded'. One image (201004_2534.png with Zero ko) couldn't be uploaded to the server... the other (201004_2535.png with 220 ko) yes.

**Comment by lisetauber** [comment]
@marinofaggiana 
Thank you for the update, it seems to work 😀 
Lise
