### ISSUE TITLE
Activity: Messages are incomplete

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#144]
Steps to reproduce:

1. Select files view
2. Open activity
3. Some activity entries are not complete. End of sentences are missing e.g. calendar event type (changed, deleted) is not shown for long named calendars. Same for file action e.g. if multiple files are added. Only first ones are shown.

App version: V2.17 (0033) Testflight user
iOS version: 10.2.1

**Comment by marinofaggiana** [comment]
Yes, this is the limit of the first Nextcloud Server API Activity ... in future several improvements

P.S. Legenda 

![2017-03-25 12-04-14 4342](https://cloud.githubusercontent.com/assets/8616947/24321724/1741d9de-1154-11e7-9a5f-da7eff3f7f74.png)

**Comment by marinofaggiana** [comment]
@rakekniven ping

**Comment by rakekniven** [comment]
@marinofaggiana thank your for explanation. My topic is about incomplete server strings. Will look to provide screenshot

**Comment by rakekniven** [comment]
Looks like this is fixed in v2.17.4 Testflight version.
Will check with golden master and maintain this issue

**Comment by marinofaggiana** [comment]
@rakekniven  for review Activity I wait the new API Server.
