### ISSUE TITLE
Mobile App for IOS shown hiden files

### ISSUE THREAD

**Issue by hebertviniciusviana** [nextcloud/ios#1440]
Dear all,

I have identified that the IOS App allow to see images and videos inside hide folders, even when the option "Show hide files" is disable and after clear the cache memory.

Best regards.

**Comment by marinofaggiana** [comment]
Hi @hebertviniciusviana ... this happens in the Media tab ?

**Comment by marinofaggiana** [comment]
fixed in 3.0.10 (15)

**Comment by hebertviniciusviana** [comment]
Hi Marino, Yes. This happens in the Media tab.

Às 11:08 de 09/10/2020, Marino Faggiana escreveu:
