### ISSUE TITLE
No more integration with the Files app

### ISSUE THREAD

**Issue by lisetauber** [nextcloud/ios#1448]
Nextcloud 3.0.10.21
iPad Air 3 iPadOS 14.0.1
iPhone 8 Plus iOS 14.0.1

Hello Marino, 
Since the latest versions of Nextcloud, it is impossible to connect the Files app to the Nextcloud server. However, I have not deactivated the integration of NC with the Files app. The server is well accessible from third party apps such as Documents, Notebooks...

Lise

**Comment by lisetauber** [comment]
Hello Marino,

As I said for some days, it’s no more possible to connect the Files App to the Nextcloud server. 

However, even if I deactivate the integration from the app Nextcloud to the Files App, I can access to the files on the server from  other apps as Documents, PDF Expert or Only Office. 
But in all cases, I cannot access to the files on the Nextcloud server from the Files app. 

Is it due to the Nextcloud app or the Files app?

iPadOS 14.1
Nextcloud 3.0.11

**Comment by marinofaggiana** [comment]
Hi 3.0.11 fixed your first post.

> But in all cases, I cannot access to the files on the Nextcloud server from the Files app.

Do you have an error when view the files in the app Files ? ... what's happens ?

**Comment by lisetauber** [comment]
As I enter login and password and want to connect to the server, I've the  message  : 
"The connection to the server has failed. 
Please check the IP address."

I have, of course, checked the server address, login and password. 😀

**Comment by marinofaggiana** [comment]
login and password ?? nooo :-) you must select "Modify" and activate Nextcloud in the list of available Position

**Comment by lisetauber** [comment]
Sorry 😀 i did ‘ modify anything, since I use  Nextcloud and didn’t think to verify the available position!

**Comment by thgoebel** [comment]
For anyone else affected by this, here’s how to reenable it:

![C834EAB7-7D4D-4E3C-A1E3-46CDC2C1D43E](https://user-images.githubusercontent.com/33295590/96870193-d22d2a00-1470-11eb-80be-3961fb54115d.jpeg)

Though it may disappear again :/

**Comment by pie-ai** [comment]
Great! I think a help is missing?
