### ISSUE TITLE
Show issuer in activity log

### ISSUE THREAD

**Issue by cal940** [nextcloud/ios#145]
Screenshot from web application:
![](http://i.imgur.com/3YrDYDc.jpg)

Note: The user (Anja) shared 2 different folders with the same name.

**Comment by marinofaggiana** [comment]
?? Please ?

**Comment by rakekniven** [comment]
@cal940 Your screenshot is web UI. Could you please explain in more detail about your idea?

**Comment by cal940** [comment]
My mistake, I just compared my activity log from web UI with the app.
