### ISSUE TITLE
Activity: Move settings to main menu. "Help" is too hided and unfitting

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#146]
Currently settings for activity log are in "Settings" > "Help".

Idea: Create item at "Settings" called "Activity" and place settings below it.

**Comment by marinofaggiana** [comment]
Yes i want this, this option is only for "debug" (too hide is perfect).

**Comment by rakekniven** [comment]
Help is for help IMHO.

Will it be removed in final version?

**Comment by marinofaggiana** [comment]
Activity V 2.17 is in more tab. close.
