### ISSUE TITLE
.noimage / .nomedia broken

### ISSUE THREAD

**Issue by tolotos-rgu** [nextcloud/ios#1474]
The media view ignores the .noimage / .nomedia files completely with NC 20.0.0 and iOS app version 3.0.11.1.

**Comment by marinofaggiana** [comment]
What's the .noimage / .nomedia ?

**Comment by thgoebel** [comment]
They're very common on Android. Gallery apps scanning the storage for media files ignore media files in a directory that contains a `.nomedia` file.
See https://www.lifewire.com/nomedia-file-4172882

So as I understand it the request is to have the same behaviour in the `Media` tab: hide images/videos that belong to a folder with a `.nomedia` file.

**Comment by marinofaggiana** [comment]
Ah no, don't exists in iOS

**Comment by tolotos-rgu** [comment]
It was working with NC <= 19.x. 
I don't know if it is a server function or app related.

**Comment by jonastr** [comment]
@marinofaggiana can you explain your rationale a bit more in depth, please? i would like to understand why this is not an option to consider for the iOS app. from my point of view there are two very valid arguments to consider `.nomedia` excludes:

1. consistency. the nextcloud web interface (photos view) does consider the `.nomedia` file just perfectly fine. and i would argue the photos view is roughly the counterpart for the media view, isn't it? it might even make sense to use the same name (either photos or media) for the two views. :) so, even if only in terms of consistency and feature parity across platforms, i would argue it should be considered on iOS as well.
2. i think it's also a very valid usecase. for example, i do have a ton of camera raw files stored on my nextcloud, but i don't possibly want to see them on the mobile device, just those that i have developed to jpeg and that are usable for viewing+sharing. so, i would love to be able to exclude the raw files to not have lots of noise in there.

the only solution i see so far is two have two accounts. one for raw files, one for "the rest". not so great, imho.

is there any other existing option for the iOS app to accomplish this?

cheers,
jonas

**Comment by douglasparker** [comment]
@marinofaggiana why was this closed?

The whole point of the `.nomedia` file is to exclude images from being included in the Nextcloud Photos app.

For example, I want all of my mobile photo uploads to show up, but other images such as those found in design projects to be excluded.

If we add `.nomedia` to the `Documents/` folder, it prevents all of these images from being shown in Nextcloud Photos / Memories.

However, the iOS mobile app doesn't seem to respect these files.

Please consider filtering out all images from directories with the `.nomedia` file present. This should include all subdirectories under the root directory to be consistent with Nextcloud Web.

This is actually a major problem for people that use Nextcloud Photos for their personal photo library. I've got thousands of images being included on mobile that are related to work and not related to personal photos.

**Comment by douglasparker** [comment]
Please reopen this issue. This is critical functionality that needs added to the mobile apps.
