### ISSUE TITLE
Uploading progress should be adapted to app style

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#148]
Sometimes I save images from twitter to my nextcloud.
Following screenshot show progress dialog.
IMHO the blue style with black lines does not fit.

@nextcloud/designers Any ideas?

![2017-03-26 10-39-17 0161](https://cloud.githubusercontent.com/assets/2069590/24330680/7761b1a6-1224-11e7-9ecb-4654b9bdcaa8.png)

**Comment by jancborchardt** [comment]
@marinofaggiana can you use the default iOS loading bars?

**Comment by marinofaggiana** [comment]
This is not a BUG, please use correct Labels !

**Comment by jancborchardt** [comment]
@marinofaggiana design issues can be bugs too. :) Every issue should have either the `enhancement` or `bug` label.

(Also please don’t necessarily use exclamation sentences in our issue discussion – let’s keep things friendly. :)

**Comment by marinofaggiana** [comment]
yes yes @jancborchardt :-) (!)  this is not a bug it's a library ... to review it's correct for me.

**Comment by marinofaggiana** [comment]
@rakekniven the extension share on ipad it's horrible :(

**Comment by rakekniven** [comment]
Thanks for going through horrible stuff fo us.
