### ISSUE TITLE
Context needed for string "_dimension_"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#1483]
https://github.com/nextcloud/ios/blob/e8bb5dbe89965ae681f7023b7fc009b10987345f/iOSClient/Supporting%20Files/en.lproj/Localizable.strings#L149

What is the meaning of dimension here?

There is size as well one line above.

Context requested at Transifex.

@marinofaggiana please.

**Comment by marinofaggiana** [comment]
Sure! Dimension "image" example 4096 x 2048 px

**Comment by rakekniven** [comment]
Thank you
