### ISSUE TITLE
Only one server side menu entry is shown

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#149]
* configure Nextcloud external app to contain more than one link
* open iOS app and press on icon
* actually: one entry is shown
* expected: all entries are shown

with nightly 33

cc @marinofaggiana

**Comment by marinofaggiana** [comment]
?

![simulator screen shot 27 mar 2017 10 25 46](https://cloud.githubusercontent.com/assets/8616947/24347221/db143724-12d7-11e7-8958-1c01aae98640.png)

**Comment by jancborchardt** [comment]
The top bar is the wrong place to do this. Can we put it in the »more settings list« mentioned here: https://github.com/nextcloud/ios/issues/134#issuecomment-289396839

What do you think @MorrisJobke @marinofaggiana?

**Comment by MorrisJobke** [comment]
With 2.17 36 I see all entries now.
