### ISSUE TITLE
Share folder contains "&" 

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#15]
The iOS app gives an error "Wrong path, file/folder doesn’t exist" when sharing an external folder where the folder name contains an ampersand (&). The external folder type is SMB/CIFS and we're on Nextcloud 10.0.1. The Android app succeeds as does the Nextcloud web interface. It seems to be an iOS only problem.

https://help.nextcloud.com/t/ios-bug-cannot-share-when-external-storage-folder-name-contains-an-ampersand/6329

**Comment by brianbgness** [comment]
I'm the discoverer of this suspected glitch, and created this GitHub account to help in any way I can.  Thanks.

**Comment by marinofaggiana** [comment]
Thanks @brianbgness, bug fixed.
