### ISSUE TITLE
Simplify search

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#150]
Currently you are faced with two options, searching in current folder and everywhere:
![1](https://cloud.githubusercontent.com/assets/8616947/24101630/5e8a0660-0d79-11e7-8d94-f97d6f329854.png)

This should not be necessary to switch between. First of course the current folder should be searched for performance reasons, but then automatically results from other folders should be loaded. Just like we do on the server.

@marinofaggiana

**Comment by marinofaggiana** [comment]
No, this is a request. I think we should plan. Each has its say. This option required several several work ! This is not photoshop.

**Comment by MorrisJobke** [comment]
> No, this is a request. I think we should plan. Each has its say. This option required several several work
> . @MorrisJobke

What do you mean? It makes sense to remove stuff that should work without a user having a choice. Nobody said, that there should be two buttons. We only want to search ;) Or does Google has an input field for different search scopes 😉

**Comment by marinofaggiana** [comment]
:speak_no_evil:

**Comment by MorrisJobke** [comment]
The only thing that was said was:

* filter current folder
* search other folders

Which does not imply to have separate searches, but maybe this was also a bit unclear. Basically we want the same behaviour as on the web: first filter (for fast feedback) and also search in the background (for full results).

**Comment by MorrisJobke** [comment]
See #272 for an interim solution.
