### ISSUE TITLE
Split view on iPad

### ISSUE THREAD

**Issue by aniqueta** [nextcloud/ios#1504]
Hello. Just updated to v3.1.0.7 and saw that split view was removed. Is this temporary or permanent? In case it's a permanent change: On a large iPad screen, this turns the app into a blown up version of the phone app. It does not use the screen size effectively, and we lose functionality like browsing files while having one open. Thanks.

**Comment by kbeerepoot** [comment]
> Hello. Just updated to v3.1.0.7 and saw that split view was removed. Is this temporary or permanent? In case it's a permanent change: On a large iPad screen, this turns the app into a blown up version of the phone app. It does not use the screen size effectively, and we lose functionality like browsing files while having one open. Thanks.

I beg to differ on your preference for the split view. The problem with the split view was that on an iPad screen it made browsing files difficult because most of the times you could not see the full file names which, if you had many similar file names in a directory, made it very hard to choose the right file to display.

This difference of opinion might be solvable with a view toggle, though I do not know it that is a workable solution ...

**Comment by dietze** [comment]
Hello, I also do not like the missing split view. Since new iOS 14 there are sidebar/folder views introduced on almost all (Stock) apps, and now the NC client removes this. In my opinion this decision has bad impact on usability. Optional toggle would have been better. This is so much wasted screen estate.

**Comment by DMuckerman** [comment]
I’d like to third this. Losing the split view on the iPad basically renders the app useless to me because it just becomes a very poorly blown up phone app.

**Comment by marinofaggiana** [comment]
The removed of split view is permanent, maybe that in future we can added the Slide Menu Controller.

**Comment by aniqueta** [comment]
@marinofaggiana Thanks for clarifying. Out of curiosity, what problem is solved by removing it instead of leaving as-is?

**Comment by kbeerepoot** [comment]
> @marinofaggiana Thanks for clarifying. Out of curiosity, what problem is solved by removing it instead of leaving as-is?

The (or at least a) problem with the split view was that on an iPad screen it made browsing files difficult because most of the times _**you could not see the full file names**_ which, if you had many similar file names in a directory, made it very hard to choose the right file to display.

**Comment by dietze** [comment]
The truncated file/folder names could have been fixed by smaller font size, wider folder list, proper wrapping of strings in the left pane. Simply removing the pane is the easiest but worst solution to be honest.

**Comment by kbeerepoot** [comment]
> The truncated file/folder names could have been fixed by smaller font size, wider folder list, proper wrapping of strings in the left pane. Simply removing the pane is the easiest but worst solution to be honest.

Personally I think that an even better solution would be to **only** show the view pane when a **file** is selected, and **not show** the view pane when just a **directory** is selected. The problem with the permanent view of the view pane is that it was empty until a file was selected. I think that was such a waste of space ...

**Comment by DMuckerman** [comment]
File explorers having a multi-column view with long filenames is not a new or unique problem, and if this truly was the reason for the change, there has to have been a better way to fix it than to delete the iPad-unique view and blow up the iPhone view for tablets.

This is a _huge_ loss in functionality, and personally I find the ability to view a file while continuing to browse my folders incredibly valuable on a larger screen. It would be one thing if the new blown-up view was at least truly aware it was on a larger screen, but even the grid view shows this isn't the case. ( #1503 )

> The truncated file/folder names could have been fixed by smaller font size, wider folder list, proper wrapping of strings in the left pane.

A solution like this would benefit _both_ iPhone and iPad in the use case of a lot of similar very long file names far more than crippling the iPad app would, in my opinion.

**Comment by gennaios** [comment]
If it behaved more like the native iPadOS Files app, perhaps that would help.

- tap and hold: row remains visible with file name.
- dynamic type adjusts to settings
- share button could be moved to more so there is only one icon per row

Somewhat unrelated. Concerning the details panel, it could show the folder path too. With search or recent (activity), it is hard to know where the file is located. A way to go to that folder would also help.
