### ISSUE TITLE
Closing OnlyOffice documents not possible

### ISSUE THREAD

**Issue by dietze** [nextcloud/ios#1505]
Hello, after updating to version 3.1.0, the split view is gone. Also gone is the menu option „Close“ when viewing or editing OnlyOffice document. Also the Back button to the parent/current folder on the left top is not visible. 
This means, when editing or viewing office documents, the App is stuck on this document view. The menu only has 2 entries, one for „add to favorites“ and one for „details“. No way to close document or go back. Only closing the app via app switcher is possible.

**Comment by litauer** [comment]
Same problem here with all my IOS devices.

**Comment by litauer** [comment]
Version 3.2.0 is out and installed, but no change regarding this issue.

**Comment by marinofaggiana** [comment]
mmm strange ... who can share with me a test account ? thanks

**Comment by litauer** [comment]
Please try with:

https://cloud.uni-koblenz.de
testcloud3@uni-koblenz.de / fAdxug-jebti3-nycbom

> Am 01.02.2021 um 18:04 schrieb Marino Faggiana <notifications@github.com>:
> 
> 
> mmm strange ... who can share with me a test account ? thanks
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-- 
Kind regards
Christoph
_________________________________________
Christoph Litauer
Uni Koblenz, Computing Centre, Office A 022    
Postfach 201602, 56016 Koblenz     
Fon: +49 261 287-1311, Fax: -100 1311

**Comment by dietze** [comment]
Thank you litauer, I was also preparing a test account. Marino if you want to try another account let me know, I would send the data in private message since I don’t want to expose our company’s server here. Thank you for looking into this!

**Comment by dietze** [comment]
I discovered the same problem applies to editing txt files with the Texteditor. In issue #1532 there is a screenshot showing the menu open while editing file, clearly missing the Close option. At least in Texteditor there is an "X" icon allowing to close the editor and leave the file view, going back to the file explorer - in OnlyOffice that's impossible and we have to force quit. Also we discovered, that because the Onlyoffice documents are not closed correctly, the changes are not saved.

**Comment by marinofaggiana** [comment]
@juliushaertl can you look into this ?

**Comment by dietze** [comment]
Thank you very much for the solution!

**Comment by chkpnt** [comment]
So how can I close the document? (v4.0.3.0)
