### ISSUE TITLE
Live Photo Doesn't work on iPhone 12

### ISSUE THREAD

**Issue by llsszp** [nextcloud/ios#1507]
Expected behaviour
Live photos to get uploaded

Actual behaviour
The video component of the file is not uploaded，Only JPG/heic  was uploaded

Steps to reproduce
Take a live photo and allow auto upload

Reasoning or why should it be changed/implemented?
iOS version
14.2 

App version
3.1.0

Web server:
Apache

Nextcloud version: (see Nextcloud admin page)
19.0.6

**Comment by Tronnic** [comment]
I have the same exact problem, got an iPhone 12 Pro, neither manual or auto upload works. There are "SOME" photos that worked. But very rarely. From my entire gallery (700 photos) maybe 20 have worked.

**Comment by HannesJo0139** [comment]
Same here on a 12 mini. Upload seems to work but just no Live Photos.

**Comment by haijeploeg** [comment]
Same here on a iPhone 12. Uploads are working and are being uploaded in the `heic` format. When I upload them, it shows the live photo sign, but it does not upload the mov file for some strange reason...

Is there anyone that has more information regarding this issue?

**Comment by dukey** [comment]
I originally reported the problem under #1459 .  I haven't seen any acknowledgement from the developers on that issue either.

**Comment by sionicion** [comment]
Just tested the latest build from TestFlight and this has been resolved for me!
