### ISSUE TITLE
"Set as available offline" Files are not available offline

### ISSUE THREAD

**Issue by o4ier** [nextcloud/ios#1508]
### Expected behaviour
A txt/md file that is "Set as available offline" is available (aka readable &, writeable via the Nextcloud App) while being offline (aka Flightmode, or "no connection to the nextcloud server")

### Actual behaviour
A txt/md file that is "Set as available offline" is not available offline. When trying to access it via the Nextcloud app or the files app, an error appears: 

Files app:
"You're Offline
Check your internet connection, then try again"

Nextcloud app:
"Info
Go online to see the document"

### Steps to reproduce
Be online (having connection to nextcloud server)
Mark file as "Set as available offline"
Wait until the red dot on the lower left corner on the "Files" icon is gone (aka "finished downloading")
Go offline (e.g. Flightmode, or just no connection to the Nextcloud server)
Try to open file
See error message

### Reasoning or why should it be changed/implemented?
When a file that is "set as available offline" is not available offline, this feature is senseless

### Additional information
It worked fine a few versions back (iOS and Nextcloud App/Server), but since CoVID-19 I didn't need the feature very often. I just have ~20 txt files marked as available offline, totaling 1,1MB, to be able to e.g. see my collection of PlayStation Games, to avoid buying one of them a second time, and updating the list of games automatically when I come back home. My Nextcloud instance runs on a server only accessible from my local network.
iPhone has ~230 GB free space.
Long tap on file -> "Open with Quick Look" shows the correct content of the file when offline, so the file contents are actually somewhere on the iPhone, but the Nextcloud App cannot open them without connection to the Nextcloudserver.

Things I tried:
Mark file as "Remove as available offline"
Clear cache
Mark file as "Set as available offline"

### iOS version
14.3

### App version
3.1.0.7

### Server configuration

**Operating system:**
Ubuntu 20.04.1 LTS

**Web server:**
apache2
2.4.41-4ubuntu3.1

**Database:**
mariadb-server-10.3
1:10.3.25-0ubuntu0.20.04.1

**PHP version:**
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
7.4.3-4ubuntu2.4

**Nextcloud version:** (see Nextcloud admin page)
20.0.4

**Comment by sfatula** [comment]
Same issue, seems like he fixed this and hopefully it will go into 3.2.0. Trying to keep all my notes app file offline.
