### ISSUE TITLE
Make system bar text & icons white too

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#151]
See the text on the very top, the system info like time, phone network, battery icon etc:
![](https://cloud.githubusercontent.com/assets/2069590/23276721/b48e237e-fa0b-11e6-90de-2d00955831e3.jpg)

Now that the top bar is dark (blue) and has white icons, this system text should also be white to fit that.

 (and thanks @rakekniven for the screenshot :)

cc @marinofaggiana (this is a design bug for example ;)

**Comment by marinofaggiana** [comment]
Correct several day ago. please view the current version.

**Comment by rakekniven** [comment]
Updated screenshot to v2.17 0033

![2017-03-27 16-32-09 6162](https://cloud.githubusercontent.com/assets/2069590/24361763/0bc01be4-130b-11e7-8110-e31847ec9ce4.jpg)
