### ISSUE TITLE
App crashes when renaming epub files

### ISSUE THREAD

**Issue by Julrob** [nextcloud/ios#1511]
How to reproduce:
1. Have an epub file on the server
2. Click on rename
3. Place the text cursor before the dot left of the file type, so to the point „here“: xyzfilename“here“.epub
4. Press the space bar
5. The app crashes (however not everytime, which makes it harder to reproduce... sometimes it works, but I dont see any other pattern there why it crashes or not).

Normally when I finish a book I name it as „read“, so for example I rename a file from:
a) Microelectronics.epub
to
b) Microelectronics (read).epub

Device Info:
-iPad Air 2 (2014)
-iOS 14.3 (but it already happened on older versions iOS 13 too)
-Version: 3.0.6 (I guess it already happened in older versions)

But thats (often) not possible on the iPad App, because it crashes.
I havent had the problem with other file types yet, but only because I havent experienced it yet, doesnt mean the bug could not be triggered by other files types.

**Comment by marinofaggiana** [comment]
Hi @Julrob the last version of App is the 3.1, can you try ?

**Comment by Julrob** [comment]
Hello @marinofaggiana , 

although I didn't see any solved issues regarding the problem from Version 3.0.6 to 3.1., the bug is not occuring anymore.

Seems to be solved, thanks for the hint :)
