### ISSUE TITLE
Can't build or run without having a Firebase account

### ISSUE THREAD

**Issue by sirnacnud** [nextcloud/ios#1519]
As mentioned on #642 you can't build the app unless _GoogleService-Info.plist_ exists. If you just remove the step from Copy Bundle Resources phase, the app then crashes at runtime due to missing GoogleService-Info.plist. This effects 3.1.0.

It would be nice if a Firebase account wasn't required for development/debug build, as not everyone has a Google account or wants to use Google's services.

**Comment by marinofaggiana** [comment]
please remove GoogleService-Info.plist from project and set the NCBrand disable_crash_service to true
