### ISSUE TITLE
[Bug] App crashed when there is a percent sign in file name

### ISSUE THREAD

**Issue by andrewhotlab** [nextcloud/ios#152]
We noticed that, as for version 2.16, the app crashes each time it has to display a list containing a file with the "%" character in its name. Verified on iOS 10.2.1.

See the [help request](https://help.nextcloud.com/t/app-v2-16-crashes-when-there-is-a-percent-sign-in-filename/10716) in forum.

**Comment by marinofaggiana** [comment]
@andrewhotlab this issue is correct (available for the next 2.17) 

Thanks for you report.

**Comment by andrewhotlab** [comment]
Thank for your fix, Marino! :)
