### ISSUE TITLE
Cannot Build APP in Xcode 12.3

### ISSUE THREAD

**Issue by lemhteske** [nextcloud/ios#1526]
I downloaded last code an install all dependencies with

/wcarthage update --no-use-binaries --platform iOS --cache-builds

Build failed with this message 

![Bildschirmfoto 2021-01-20 um 00 08 15](https://user-images.githubusercontent.com/56629175/105105034-9cb9cc00-5ab3-11eb-863d-42aaa601c58e.png)

Anybody can help?

**Comment by freumichCH** [comment]
Was `/wcarthage update --no-use-binaries --platform iOS --cache-builds` successfully? or did you get errors?

**Comment by lemhteske** [comment]
The wcartahge was not successfully I attached the error Message 

![Bildschirmfoto 2021-01-25 um 11 50 04](https://user-images.githubusercontent.com/56629175/105696364-81abe980-5f03-11eb-910e-2f04768ac29d.png)

**Comment by marinofaggiana** [comment]
Hi, do you have resolved ?
