### ISSUE TITLE
Internal Error image/video not found

### ISSUE THREAD

**Issue by togglecode** [nextcloud/ios#153]
I keep getting this error when I try this:

1. take some pictures
2. Try to upload the pictures from "My Photo stream"
You will get the error in screenshot.

However you can upload the **SAME** pictures from other folders like "Camera Roll" or "Recently Added"

### Screenshots:

First I try to upload some pictures from "My Photo stream"
![2017-03-27 13-06-16 0505](https://cloud.githubusercontent.com/assets/17141698/24353560/67d2f0fe-12ee-11e7-9113-aa19d078cb37.png)

# Logs (Not really that much of log)

```
2017-03-27 13:16:03.925106 Nextcloud[1269:445314] [LOG] [OPTIMIZATION] Rebuild Data Source File : https://demo.nextcloud.com/testcloud/remote.php/webdav - 2017-03-27 11:15:34 +0000
2017-03-27 13:16:10.406616 Nextcloud[1269:445314] [LOG] [OPTIMIZATION] Rebuild Data Source File : https://demo.nextcloud.com/testcloud/remote.php/webdav - 2017-03-27 11:15:34 +0000
2017-03-27 13:16:10.532239 Nextcloud[1269:445314] [LOG] Asset N. 1
2017-03-27 13:16:11.027113 Nextcloud[1269:445314] [LOG] [OPTIMIZATION] Rebuild Data Source File : https://demo.nextcloud.com/testcloud/remote.php/webdav - 2017-03-27 11:15:34 +0000
```

**Comment by marinofaggiana** [comment]
@togglecode interesting ... how do u have make this ? "My Photo stream" ?

Thanks

**Comment by togglecode** [comment]
@marinofaggiana hmmmm ... I think you have to activate it with using icloud https://support.apple.com/en-us/HT201317

so basically settings - icloud - photos - My Photo Stream - turn on

**Comment by marinofaggiana** [comment]
Very interesting  ... :-) I will try ...

**Comment by marinofaggiana** [comment]
P.S. Problem with Automatic upload of camera images  too ?

**Comment by togglecode** [comment]
No, it seems fine to me from what I have tried:
1. Turn on "automatic upload of camera images"
2. take some pictures
3. open the app
4. pictures got uploaded in "Photos" folder automatically

**Comment by rakekniven** [comment]
Who needs iCloud if there is nextcloud. Just disable it :-) SCNR

**Comment by togglecode** [comment]
I don't mind disabling it, but the error message is confusing so maybe that can be changed. Or the file picker should just hide the "My Stream" folder.

**Comment by enoch85** [comment]
@marinofaggiana I've seen this as well.

In my setup I have `Remove files after upload to cloud` (but they are not removed from camera roll, bug?), could that be it? 

It would be great if the file got deleted after it was confirmed to be uploaded and then removed from the que so that it doesn't try to upload photos that doesn't exist.

Also, what's the difference between enabling `Upload the all photos in camera roll` and not activate that option?
