### ISSUE TITLE
Sharing files from iCloud Drive app with "Import with Nextcloud" fails

### ISSUE THREAD

**Issue by robposch** [nextcloud/ios#154]
Using Nexcloud 2.17.00033 and iOS 10.3:

1. Open iCloud Drive app
2. Long press any file
3. Select share
4. Tap "Import with Nextcloud"
5. File size is shown as 0.00 bytes which is incorrect
6. Tap "Upload a file"
7. Error message appears "Error, file not present, please reload"

In 4. When sharing with "Nextcloud" and using the subsequent dialog instead of "Import with Nextcloud" upload works but file name is changed to a date.

**Comment by marinofaggiana** [comment]
Hi @robposch type of file ?

**Comment by robposch** [comment]
Tried with .vcf and .xlsx both had the same result.

**Comment by jparnzen** [comment]
I also ran into this error message when setting up the Nextcloud iOS app (v2.17.3.00009, iOS 10.3.1) to automatically upload photos and videos to my Nextcloud instance (v11.0) on Linux. While most photos and videos uploaded without the error during the initial upload from my phone, some photos would error, but then be re-added to the transfer queue and seemed to upload correctly later.

Please let me know if you need any further information for this, or if I should open a different issue for this.

Thanks in advance for your help!

**Comment by dziemann** [comment]
Same issue here with the latest iOS app. If I activate automatic upload, videos are uploaded with 0 byte and I get the error "Error, file not present, please reload". Also the app crashes very often during automatic upload and upload do not happen in background. App needs to stay active to keep upload alive.

App: 2.17.3.00009
Nextcloud: 11.0.3
iOS: 10.2.

**Comment by marinofaggiana** [comment]
@dziemann several news for the next version 2.17.4 .. if you want, u can try the beta version.

**Comment by dziemann** [comment]
@marinofaggiana Sure! Would appreciate it to help you with that.

**Comment by marinofaggiana** [comment]
If you want : https://github.com/nextcloud/ios/issues/260

**Comment by nikogh** [comment]
I had a similar issue: To get my iphone back working normal (there was 1 video file in the upload queue, which failed to upload every 10 sec.) I had to deactivate the automatic upload of camera images. After I reactivated it, everything went back to normal. I deleted the file from the phone earlier, so I do not know if this is necessary as well, but it could sure be.

**Comment by henkim21** [comment]
I get similar errors with auto uploaded photos on iOS. Any update?

**Comment by bencomp** [comment]
Is this issue still relevant, looking at the version numbers of the app that showed the behaviour?

**Comment by nikogh** [comment]
I cannot test it as I am not using ios anymore. Anyhow I agree this is well outdated...
