### ISSUE TITLE
Download stops when locking the iPhone/iPad

### ISSUE THREAD

**Issue by HeyWatchOutDude** [nextcloud/ios#1545]
Hi,

anyone else has noticed when you start a download via nextcloud iOS app and lock the phone and unlock it again the download gets canceled.

When you leave the iPhone unlocked (within the app) the download can be completed without any issues.

- iOS 14.4
- iPhone 11 Pro / Max / XR (I think it's a general issue)
- Nextcloud server version: 20.0.7
- Nextcloud client version: 3.2.0.30 @ 2020
- Local caching is disabled

**Comment by marinofaggiana** [comment]
Because in download we don't use the background mode.

**Comment by HeyWatchOutDude** [comment]
> Because in download we don't use the background mode.

So this is an expected behavior?

Will this feature added in a future release?

It's really important because I don't want to leave my iPhone all the time turned on while the download is active.

**Comment by marinofaggiana** [comment]
For now is not in TO-DO.

**Comment by ObiWahn** [comment]
Please add this. I have tried several times to download a bigger file. And the download failed 7 times to finish on a slow connection (something that can not be fixed here). After 10 minutes or so the screen goes black as I forget to press. Or I select accidentially/willingly a different app or i buy something form the store in the split screen. It seems that there are a lot of triggers that halt the download. This makes nextcloud really unusable with bigger files on slow connections.
