### ISSUE TITLE
Nextcloud (iOS) constantly crashing

### ISSUE THREAD

**Issue by HeyWatchOutDude** [nextcloud/ios#1546]
Hi,

when I browse through the NC data on my iPhone the app stucks and afterwards it crashes.

Nextcloud client version: 3.2.0.30 @ 2020
iOS version: 14.4

**Comment by HeyWatchOutDude** [comment]
Edit: Furthermore it seems like that app stucks when the sync is active.

**Comment by HeyWatchOutDude** [comment]
Same issue like this:

https://github.com/nextcloud/ios/issues/1514

**Comment by marinofaggiana** [comment]
Hi, for this issue I need an account test with this crashes

**Comment by HeyWatchOutDude** [comment]
How we do proceed?

**Comment by marinofaggiana** [comment]
can you send me ios @ nextcloud dot com a test account with this "visible" crash.

**Comment by HeyWatchOutDude** [comment]
So you want a test account in my NC environment?

**Comment by HeyWatchOutDude** [comment]
So? :)

**Comment by marinofaggiana** [comment]
> So do you want a test account in my NC environment?

Yes, sure, with this issue present and immediately visible.

**Comment by marinofaggiana** [comment]
sorry I haven't received your mail. Can you resend it

**Comment by HeyWatchOutDude** [comment]
Please check again.

**Comment by marinofaggiana** [comment]
A directory with over 700 files ?

**Comment by marinofaggiana** [comment]
ok tested with emulator and iPad, no issue.

**Comment by HeyWatchOutDude** [comment]
When you open the "Test" folder and start a sync request, it freezes for 3 seconds is that normal? (Folder size = 2,9GB)

**Comment by marinofaggiana** [comment]
iPhone model ?

**Comment by HeyWatchOutDude** [comment]
iPhone XR, iPhone 11 Pro, iPad Pro 11 (2018).

iOS/iPadOS: 14.4.1 (Same issue was on 14.3/4)

**Comment by marinofaggiana** [comment]
ok, no issue registered and nothings crashing. REOPEN if you have more data.
