### ISSUE TITLE
Request account

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1547]
![Schermata 2021-03-08 alle 10 37 17](https://user-images.githubusercontent.com/8616947/110303212-6b14aa00-7ffa-11eb-9611-10811421590d.png)

1) Enable the request account at startup

![Simulator Screen Shot - iPhone 12 - 2021-03-08 at 08 48 35](https://user-images.githubusercontent.com/8616947/110303427-a9aa6480-7ffa-11eb-8aa4-bad897b27d03.png)

1) Touch on background for remove the change account (or leave the current account)
2) choice the account
3) or after 3 sec. the countdown close automatically the view (progress view blue in bottom) 
4) or scroll the table for cancel the countdown

**Comment by tomcatcw1980** [comment]
Hello,

Thank you very much for taking on this topic and developing it further. I think this is a step in the right direction. The following suggestion:

Currently, when activating the "Request Account" button, a selection field appears. But if you have activated the Face-/Touch-ID on opening, this query "blocks" the Request Account query. Especially for the iPad, which is probably accessed by several family members, the Face/Touch ID should only be requested when using one account.For multiple accounts, the Face/Touch ID request should rather be linked to the Nextcloud account password or how do you see it?

I hope you understand what I mean.

Greetings

**Comment by tomcatcw1980** [comment]
For example I unlock the ipad for my kids or they have the code/touch/faceid doesnt matter. 

If they choose their account or even my account unintended, they have to be asked for the password of there nextcloud account or the faceid/touchid which is linked to the nextcloud login password. Actually when they overcome the touchid they can enter my nextcloud account. that has to be denied.

I hope I can transported it the right way.

**Comment by marinofaggiana** [comment]
Your request don't have a solution because (for now) the passcode request is the same for all account, create a passcode for every account would be a tedious option for the 99% of users, I understand your problem, but now, I don't have a solution without modify the code.
