### ISSUE TITLE
Upload menu is at wrong position on iPad at landscape mode

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#155]
1. Use iPad Pro
2. Use landscape mode
3. Open nextcloud app
4. press + Button on the right
5. menu opens in the middle

IMHO the menu should be centered above + button
At the moment you have to move to the right to go ahead.

Screenshot:
![2017-03-28 21-06-03 0162](https://cloud.githubusercontent.com/assets/2069590/24522081/b5784712-158e-11e7-9f58-2ea3904531c2.png)

**Comment by rakekniven** [comment]
Same in portrait mode

**Comment by marinofaggiana** [comment]
@rakekniven try with next build

**Comment by rakekniven** [comment]
Ok, just tried with TestFlight v2.17.6.3 and it is fixed imho.
