### ISSUE TITLE
Nextcloud + Files App

### ISSUE THREAD

**Issue by HeyWatchOutDude** [nextcloud/ios#1555]
Hi,

When you open a large folder (10-50GB) from nextcloud via the files app (Bundle-ID: com.apple.DocumentsApp) im getting this error:

![image](https://user-images.githubusercontent.com/61534143/111783750-d3953e00-88ba-11eb-9887-8d116d98d2f6.png)

Edit: When I click on "Try Again" same issue occurs again.

Error is present on all of my devices. (iPad Pro 11, iPhone 11 Pro Max, iPhone XR etc.)

In comparison I opened the same folder directly in the nextcloud app .... it kinda takes long to get the full content loaded completely (10-20 seconds) - while this process the whole app freezes.

=================================================

**Expected behaviour**
Load content

**Actual behaviour**
Error occurs in the Files App // Long loading times in Nextcloud App

**Steps to reproduce**
Open the files app, navigate to "Nextcloud" and open a large folder. (10-50GB)

Open the Nextcloud app and navigate to a large folder. (10-50GB)

**iOS version**
14.4.1

**App version**
3.3.1.1 @2021

**Server configuration**
**Operating system:**
Intel NUC10i5FNH with Proxmox

**VM Settings:**
Ubuntu 20.04.2 LTS - 64Bit
8GB RAM
2TB SSD
4 Cores assigned

**Web server:**
Apache2

**Database:**
MySQL v8.0.23

**PHP version:**
7.4.3
MEM Limit -> 6GB
Execution Time -> 3600
Max Upload Size -> 60GB

**Nextcloud version: (see Nextcloud admin page)**
20.0.8

**Comment by marinofaggiana** [comment]
Hi, yes, we know this issue but, for now, is not possible a fix; the problem is of Files App that has a very limited memory available and because via webdav I cant paginate the results so appear this message for a "simple" out of memory.

**Comment by HeyWatchOutDude** [comment]
Is the apple files app still limited to memory?

**Comment by marinofaggiana** [comment]
> Does the apple files app still use limited memory?

yes. no news ..
