### ISSUE TITLE
Clicking on login notification from notification centre does not open approval screen

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/ios#1556]
### Steps to reproduce

1. Configure 2FA via Nextcloud Notification
2. Login to your Nextcloud instance
3. Click on the notification "Login attempt from XYZ" in the notification center

### Actual behaviour

Nextcloud opens on the normal main screen (the files list).
To actually approve the login, you need some extra steps:

4. Click on the "More" tab
5. Click on "Notification" (btw: should be better called "Notifications", plural)
6. Click on "Approve"

### Expected behaviour

Nextcloud opens directly on the "Notifications" screen, so that the user can immediately approve/deny the login attempt.

### Reasoning or why should it be changed/implemented?

1. First time users may not find where to approve the login, and may be confused.
2. It's 2 extra clicks that the user needs to do. These clicks can trivially be automated.

### iOS version

iPadOS 14.4.1

### App version

3.3.1.1

### Server configuration

n/a

**Comment by tanc** [comment]
Agree this is annoying. BTW I think you've got 'expected' and 'actual' behaviour mixed up in your report. Also this looks like a dupe of #867

**Comment by thgoebel** [comment]
Your right, edited.
Also, closing since I didn't search properly :see_no_evil:
