### ISSUE TITLE
Chunked file upload

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1559]
https://docs.nextcloud.com/server/stable/developer_manual/client_apis/WebDAV/chunking.html

**Comment by ne20002** [comment]
Hi Marino

I'm glad to see that this long awaited feature is coming to the iOS client. Thank you very much.

Looking on the documentation I wonder if there is any way to configure chunking on server side and I found 'cache_chunk_gc_ttl' in config parameters on the server side.
I also found 
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html#adjust-chunk-size-on-nextcloud-side
but I don't know how this is really working as it is not mentioned in the developers manual. But I'd like to have an option to reduce the chunk size down to 1 MB as I have a friend in India which has very instable connections (often even failing uploads of 2 to 3 MB).

**Comment by marinofaggiana** [comment]
Some clarification of chunked file upload:

Why YES:

- The big files requires time without resume and several modification server side (not always possible)
-  It can also be useful for dirty connections 
- It's not require anything parameter or changed server side

Why NO:

- The chunked works only in "foreground" 
- At the same time it is slower because need the chunk file, the creation directory TMP and other task.

The size of chunk is variable according to your needs (min 1 MB, max 100 MB - default 10 MB)

![Simulator Screen Shot - iPhone 12 - 2021-04-06 at 12 13 39](https://user-images.githubusercontent.com/8616947/113697246-3c5e2200-96d3-11eb-84df-6ce268409e1e.png)

**Comment by ne20002** [comment]
Hi Marino

What exactly is "foregroud"? Even though I'm not a iOS developer or user but I would see these 
1 app is on screen (and active)
2 user takes another app on screen, app is still active and in the list of started apps
3 app is not activly used by user and put into standby by the system
4 app is not even started
5 app is not in the browse list of apps but nevertheless active (waiting for events)

"foreground" is 1 and 2? 5 is background? 3 and 4 is inactive?

I have tracked iOS development of the Nextcloud app some time (to give support to me friend in India) and for me it seems as if there are especially two issues popping up from time to time.

One is not successfully ended uploads which seems to be addressed with this issue. Second is uploads are not done in background es expected by many users. Having both together would solve issues for a lot of people.

But I'm unsure if real background activity is possible in iOS (and that it is not is also the reason for the GPS trigger?). The Android apps works well in background, does not even need to be started. Is the 'not working /uploading in background' a general iOS issue? Or is there a chance this can be solved somehow also?

But for the chunked upload: thank you very much. Even if it is only working in foreground, it will help my friend to hoplefully upload larger files in future without restarting all the time from the beginnig.

**Comment by marinofaggiana** [comment]
> Hi Marino
> 
> What exactly is "foregroud"? Even though I'm not a iOS developer or user but I would see these
> 1 app is on screen (and active)
> 2 user takes another app on screen, app is still active and in the list of started apps
> 3 app is not activly used by user and put into standby by the system
> 4 app is not even started
> 5 app is not in the browse list of apps but nevertheless active (waiting for events)
> 
> "foreground" is 1 and 2? 5 is background? 3 and 4 is inactive?

Hi, I have modified for a more understandable language, and yes the app must be active but don't worry if the app go in NON active mode (background or terminated) the transfer is automatically resumed.  

> 
> I have tracked iOS development of the Nextcloud app some time (to give support to me friend in India) and for me it seems as if there are especially two issues popping up from time to time.
> 
> One is not successfully ended uploads which seems to be addressed with this issue. Second is uploads are not done in background es expected by many users. Having both together would solve issues for a lot of people.

he he he because don't exists a real background in iOS only dome little strategy, for the upload exists a type of background but works only for big file because don't exists a control (it's complicated). 

> 
> But I'm unsure if real background activity is possible in iOS (and that it is not is also the reason for the GPS trigger?). The Android apps works well in background, does not even need to be started. Is the 'not working /uploading in background' a general iOS issue? Or is there a chance this can be solved somehow also?
> 
> But for the chunked upload: thank you very much. Even if it is only working in foreground, it will help my friend to hoplefully upload larger files in future without restarting all the time from the beginnig.

Exactly, the chunked works good in this case.

**Comment by ne20002** [comment]
Hi Marino
Thank you for clarification. I googled a bit and found some information on how iOS works with foreground, background and suspend.
Reading the docs I understand that the following shall be possible, but I'm not sure and I don't know if Apple would accept it.

For iOS 13 there is a new background mode 'Background processing' (BGTaskScheduler) besides 'Location Update' and 'Background Fetch'. Ain't that an option?
Besindes this, as I understand, the Background Fetch' is called regularly for an app to give it possibility to check for information. Wouldn't that be a way to do a single chunk upload (not a big task, only one chunk) and then wait for the next background activation?

Looking on an article (https://www.andyibanez.com/posts/modern-background-tasks-ios13/) it states 
`BackgroundTasks is a new framework introduced in iOS 13 to offer developers more ways to execute background work. Background task offers two type of classes:

BGAppRefreshTask: To refresh your app in the background periodically and always have up to date content.
BGProcessingTask: To perform possibly longer operations related to mainenance, backup, and cleanup of the app. We can set tasks of this type to execute when our devices are connected to power and/or have internet connection available.
`
So wouldn't the second option (BGProcessingTask) be a way for working background updates?

**Comment by marinofaggiana** [comment]
Hi, in my code you can found all answer.

bye

**Comment by marinofaggiana** [comment]
Available in TestFlight 

https://testflight.apple.com/join/GjNbfo2a

**Comment by Whissi** [comment]
@marinofaggiana Seeing that iOS screenshot... are you taking care of server settings, too? From my understanding, Nextcloud server can set `occ config:app:set files max_chunk_size` in which case the app shouldn't be able to set an own chunk_size which is larger than chunck_size set at server.

**Comment by ne20002** [comment]
I really like to do the test .. but unfortunately the iPhone 6 I use (just for support for my friend in India) does not allow to install Testflight app. :(

**Comment by marinofaggiana** [comment]
> @marinofaggiana Seeing that iOS screenshot... are you taking care of server settings, too? From my understanding, Nextcloud server can set `occ config:app:set files max_chunk_size` in which case the app shouldn't be able to set an own chunk_size which is larger than chunck_size set at server.

The server setting have nothing to do with the client's chunk parameter (size)

**Comment by vpistis** [comment]
Hi,

first of all thank you for your great work and all your support.

I use nextcloud daily and I noted from some time that the instant upload is not runnning very well...but runs in some way. With the chunked upload seems the upload is not runs good at all, the upload runs well only if the app is open, why?
For upload some image I must open the app many times at day, but for upload some video heavy than 100MB I must keep open the app otherwise the upload restarts from zero. I make some test with and without chunked enabled, but is the same.

I can support you making some tests to solve this problem if it helps in some way.

Thank you

**Comment by marinofaggiana** [comment]
> Hi,
> 
> first of all thank you for your great work and all your support.
> 
> I use nextcloud daily and I noted from some time that the instant upload is not runnning very well...but runs in some way. With the chunked upload seems the upload is not runs good at all, the upload runs well only if the app is open, why?
> For upload some image I must open the app many times at day, but for upload some video heavy than 100MB I must keep open the app otherwise the upload restarts from zero. I make some test with and without chunked enabled, but is the same.
> 

must keep open the app? YES
otherwise the upload restarts from zero ? NO, start from the last chunk uploaded

> I can support you making some tests to solve this problem if it helps in some way.
> 
> Thank you
