### ISSUE TITLE
issues with XML parsing, hardcoded namespace names

### ISSUE THREAD

**Issue by jkraemer** [nextcloud/ios#156]
I stumbled across this while pointing the app to an alternative server implementation which speaks WebDAV and outputs valid XML, but uses `D` as the namespace name, i.e.

~~~~
<?xml version='1.0'?>
<D:multistatus xmlns:nc='http://nextcloud.org/ns' xmlns:oc='http://owncloud.org/ns' xmlns:D='DAV:'>
  <D:response>
...
~~~~~

This kind of response is perfectly valid and works with the android / desktop client apps and any other webdav client I've tried so far. Unfortunately it couldn't be parsed by the iOS app and led to an `[items NULL] please fix` error and an always empty directory listing.

After checking out the code I found that `OCXMLParser.m` does things like `elementName isEqualToString:@"d:collection"` or `elementName hasSuffix:@"d:getcontentlength"` which, while working against owncloud / nextcloud, isn't a proper handling of XML since it hardcodes the `d` as the namespace name, while it would be valid for a server to pick any random string for that as long as it's declared properly.

Knowing what the problem is I could work around it now, but I still thought it might be worth reporting to avoid future interoperability problems.

**Comment by marinofaggiana** [comment]
Oh @jkraemer ! Thanks for your work, can you create a PR for this issue ?
