### ISSUE TITLE
Context needed

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#1561]
Hello @marinofaggiana ,

the following new sentence is not clear to me:

`Make your users more readable like home, office, school ...`

https://github.com/nextcloud/ios/blob/0ab533fe1bce53b1f22a7425f9dc13343f8b4493/iOSClient/Supporting%20Files/en.lproj/Localizable.strings#L168

Do you want to provide details where the user is currently?

Or do you want to classify user like "Related to school"?

**Comment by rakekniven** [comment]
Ah, just seen the new option at Testflight version.

What about the following string:
`Make your account name more readable like home, office, school ...` ?

**Comment by marinofaggiana** [comment]
Hi @rakekniven, yes, for a single account you can associate an alias, so for example marino.faggiana in nextcloud.com can be simply Office so .. :

![Simulator Screen Shot - iPhone 12 - 2021-03-29 at 08 42 25](https://user-images.githubusercontent.com/8616947/112796836-d4706180-906a-11eb-9385-c283e4b14414.png)

**Comment by rakekniven** [comment]
Hello @marinofaggiana ,

what about `Give your account names a descriptive name such as Home, Office, School ...` ?

**Comment by marinofaggiana** [comment]
Hi @rakekniven what's in not clear ?

![Simulator Screen Shot - iPhone 12 - 2021-03-29 at 17 54 09](https://user-images.githubusercontent.com/8616947/112864381-0d82f300-90b8-11eb-9dc0-f985483aab3f.png)
