### ISSUE TITLE
Scanning multiple pages, “save-screen” shows only last scanned Page

### ISSUE THREAD

**Issue by trvrcr** [nextcloud/ios#1566]
NC server 21.0
iOS Nextcloud Coherence 3.3.1.1

When scanning multiple pages in app and pressing save (showing x-pages scanned). Only the last scanned page is visible on the save screen.

When pressing on arrow button on left to scanned pages only the last page is added to the list.

It's impossible to create a multi page scanned document.

**Expected behaviour** 

On save page see the scanned pages on top
And be able to add them all to the document with down arrow button.

**Comment by marinofaggiana** [comment]
Hi @trvrcr can you post a small video ? ... I don't understand

**Comment by trvrcr** [comment]
https://user-images.githubusercontent.com/64335794/113832865-4d696a80-9789-11eb-858c-2755c9c4d8b4.mp4

**Comment by trvrcr** [comment]
https://user-images.githubusercontent.com/64335794/113833172-9de0c800-9789-11eb-9791-e3e06c4e556b.mp4

**Comment by marinofaggiana** [comment]
Ah very strange ! thanks for your video, what's iOS and iPhone you use ?
Can you clear the cache ?

**Comment by gruenekokosnuss** [comment]
Dear Marino, thank you for your invitation.
I have exact the same problem: iPhone XS Max, iOS 14.4.2, Nextcloud 21.0.0, App Version 3.4.0

gk

**Comment by marinofaggiana** [comment]
@trvrcr @gruenekokosnuss  Please, it's available in Testflight the new 3.5.0 (1) test it

**Comment by gruenekokosnuss** [comment]
Hi Marino,

no, the testflight-version doesn't work out this problem.

gk.

**Comment by trvrcr** [comment]
In the version 3.2.0.30 there is no problem with multiple pages. (From a family member's phone)
Are there instructions on how to test the TestFlight app? 
How to install
How to return to previous app?

**Comment by marinofaggiana** [comment]
@gruenekokosnuss can you test the 3.5.0 build 3 and post the screenshot of debug filename as below : 

![Immagine PNG 2](https://user-images.githubusercontent.com/8616947/114370310-a1a48e00-9b7f-11eb-9916-23588d6d62f0.png)

thanks

**Comment by gruenekokosnuss** [comment]
Hi Marino,

i have made two different pictures with following Debug:

![grafik](https://user-images.githubusercontent.com/82165884/114434212-0c2aed80-9bc3-11eb-9df7-58767ea70900.png)

**Comment by marinofaggiana** [comment]
Great ! thanks.

**Comment by Maxence1502** [comment]
Same problem for me

**Comment by gruenekokosnuss** [comment]
Hi Marino,

your new beta 3.5.0.7 works for me. Thanks.

gk.

**Comment by marinofaggiana** [comment]
Thanks all.
