### ISSUE TITLE
Scan function not available on iPhone 6 / iOS 12.5.2

### ISSUE THREAD

**Issue by gataloca** [nextcloud/ios#1568]
### Steps to reproduce

1. Open iOS app 
2. Look for scan function
3. Fail to find scan function

### Expected behaviour

I've had the Nextcloud app on my phone for a year or two. It used to have a scan function, which I used often. I believe I accessed this function by pressing the large "+" button and selecting "Scan document".

### Actual behaviour

I no longer see the scan function when I press the large "+" button. I've looked elsewhere in the app and could not find it. Is it possible that the scan function is unavailable because my phone (iPhone 6) cannot be updated to iOS 13 or 14?

### Logs

I don't think there's anything worthwhile in the logs since I don't see any crash behavior. But I'd be happy to share something if someone tells me how to do so.

### Environment data

**iOS version:** 12.5.2 (that's as high as iPhone 6 can go right now)

**Nextcloud iOS app version:** 3.4.0.29

**Server operating system:** Nextcloud Server 20.0.8

**Web server:** I don't know; I use the app to connect to my account at cloud01.opsdata.ch. I browsed around my account there and couldn't find information about web server, database, or PHP. 

**Database:** I don't know.

**PHP version:** I don't know.

**Nextcloud version:** I don't know.

**Comment by marinofaggiana** [comment]
Sorry but now it's available only for iOS >= 13.
