### ISSUE TITLE
Photo auto upload file mask time format bug

### ISSUE THREAD

**Issue by krejcar25** [nextcloud/ios#1569]
### Steps to reproduce

1. Set phone to 12 hour time.
1. Add `HH` to file name and see that `9 PM` is shown in preview.
1. Set phone to 24 hour time.
1. See that `21` is now in the preview.
1. Try setting the mask to `hh` and see that it is always in the 12 hr format.

### Expected behaviour

`HH` should always use 24 hour time, regardless of system settings.

### Actual behaviour

`HH` reflects system settings in displaying the time. `hh` is always 12 hr. There is no way to have a time of 21 hrs in the filename on a 12 hr system phone.

### Reasoning or why should it be changed/implemented?

It is a bug from my point of view.

### Environment data

**iOS version:** iOS 14.4.1

**Nextcloud iOS app version:** 2.4.0.29

**Server operating system:** Docker on Ubuntu Server 20.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** Whatever latest Docker image has 😁

**Nextcloud version:** 21.0.1

**Comment by marinofaggiana** [comment]
Hi @krejcar25 can you try with the version in TestFlight if is fixed ?

**Comment by krejcar25** [comment]
@marinofaggiana Yes, it looks like it is fixed in the Autoupload UI, I will reply later with actual uploaded file names.

Did I miss a bug report here somewhere?
