### ISSUE TITLE
As a user I want to delete photos / videos from camera roll after upload to nextcloud

### ISSUE THREAD

**Issue by kenthinson** [nextcloud/ios#157]
This is a feature request to be able to have the app automatically delete the original photos and videos from the camera roll after they have successfully uploaded to nextcloud.

**Comment by rakekniven** [comment]
Would like to see this feature as well.

**Comment by dgtadmin** [comment]
I have also been looking for this feature, it could an option to turn on/off, for more flexibility. I predict it would be a very useful and popular feature.

**Comment by rakekniven** [comment]
Apple has restrictions what you can do with items of your camera roll.
Let's see what our developers could could arrange.

**Comment by medcloud** [comment]
+1 for this feature : it would be great to have such a feature !

**Comment by kenthinson** [comment]
I did a little research today this should be possible on iOS 8 and newer. Using PHAssetChangeRequest

Seems like real low hanging fruit. I'm busy for the next two weeks out of town. However if it's still not in the App by then I will take a stab at adding the feature and create a pull request.

**Comment by dgtadmin** [comment]
That would be a fantastic addition to the client, a huge ‘selling’ feature. Think family members.


Sent from my iPhone

On Aug 23, 2018, at 1:09 PM, Kent Hinson <notifications@github.com> wrote:



I did a little research today this should be possible on iOS 8 and newer. Using PHAssetChangeRequest

Seems like real low hanging fruit. I'm busy for the next two weeks out of town. However if it's still not in the App by then I will take a stab at adding the feature and create a pull request.

**Comment by dgtadmin** [comment]
Hello Kent I think your suggestion of "batch" processing the upload and 
deletes meets the need that I imagined.

That type of prompting also gives me the control, confidence and 
feedback to know that my images are now safely in nextcloud before I 
delete them.

At present I am performing the validation manually, and i am sure that 
in the past I have inadvertently missed a few images.

The batch feature provides the opportunity to upload/delete -> move the 
images as seldom or often as each person needs, so I see it as a good 
option.

Are you tracking the image assurance metadata on the phone and syncing 
it to nextcloud as well. ( Just in case) ?

If you need another pair of eyes to test let me know I would be happy to 
help

Thanks again for your efforts.

**Comment by archont00** [comment]
A duplicate of https://github.com/nextcloud/ios/issues/34 `Remove From Camera Roll After Successful Upload`?

**Comment by kenthinson** [comment]
> A duplicate of #34 `Remove From Camera Roll After Successful Upload`?

Yes. I am closing this issue as it is a duplicate. I also dont have time right now to work on making it a feature.

**Comment by privettoli** [comment]
@kenthinson looks like the referenced issue was also closed. Is it planned to solve this problem in some other feature request?

**Comment by clayrisser** [comment]
I'm still interested in this feature. It's what is holding me back from switching to nextcloud from Google photos.

**Comment by dgtadmin** [comment]
> I'm still interested in this feature. It's what is holding me back from switching to nextcloud from Google photos.

This feature has been working, and working very well for several years now.
Once again thanks to the devs who listened and implemented a very useful feature, I use it every day.

if you would like some feedback on using it prior to your migration away from your current solution I would be happy to help.

David
