### ISSUE TITLE
Do not log out when receiving a 403

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/ios#1573]
Only a 401 should be a reason to log out the user because that means that the app token has been revoked.

https://github.com/nextcloud/ios/blob/master/iOSClient/Networking/NCService.swift#L100
https://github.com/nextcloud/ios/blob/master/iOSClient/Networking/NCNetworking.swift#L328
https://github.com/nextcloud/ios/blob/master/iOSClient/Networking/NCNetworkingE2EE.swift#L317

**Comment by marinofaggiana** [comment]
Maybe but the 403 is a security issue dangerous ... I have to work on it ... for example for required the ok for change the new certificate

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/1036

**Comment by nickvergessen** [comment]
403 means forbidden. This does not mean the user is invalid and should be removed. Removing should only happen on 401.
