### ISSUE TITLE
Use BGTaskScheduler for auto upload 

### ISSUE THREAD

**Issue by ckoehler** [nextcloud/ios#1575]
### Expected behaviour

See https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler

Sounds like this could check for new photos periodically and upload them, if I understand correctly. 

### Actual behaviour

Tell was what instead happens.

### Screenshots

If applicable, add a screenshot showing the issue.

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Environment data

**iOS version:** e.g. iOS 14.4.1

**Nextcloud iOS app version:** see More > Settings

**Server operating system:**

**Web server:** Apache, nginx

**Database:**

**PHP version:**

**Nextcloud version:** see Nextcloud admin page

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/215
