### ISSUE TITLE
[UX] Registration form's URL field should use the URL keyboard

### ISSUE THREAD

**Issue by jlfranklin** [nextcloud/ios#158]
iOS has a special keyboard optimized for entering URLs that puts slash (`/`), dot (`.`) and `.com` on the bottom row. Holding `.com` for a second brings up other common TLDs.

The URL field should be set to use this keyboard instead of the standard keyboard.

**Comment by rakekniven** [comment]
@marinofaggiana IMHO this should be in the next release. Unfortunately I do not know if that is a big task or not.

**Comment by jlfranklin** [comment]
It is a trivial change in CCLogin.storyboard, and looks like the change was made in another commit (@2bfce3f8, for reference).  I'll close this one.

**Comment by jancborchardt** [comment]
@jlfranklin thank you for the great issue reports & enhancement requests, please keep them coming! :)
