### ISSUE TITLE
Application extensions and any libraries they link to must be built with the `APPLICATION_EXTENSION_API_ONLY` build setting set to YES.

### ISSUE THREAD

**Issue by hungHatto** [nextcloud/ios#1587]
I have an issue with when update to Xcode 12.5
"Application extensions and any libraries they link to must be built with the `APPLICATION_EXTENSION_API_ONLY` build setting set to YES." in all Extensions. I've tried to set "Require Only App-Extension-Safe API" to true and change some "UIApplication.shared" but not working.

**Comment by marinofaggiana** [comment]
The "devevelop" branch has already this settings
