### ISSUE TITLE
UTF-8 encoded textfiles are not displayed correctly

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/ios#159]
I guess the headline says it all: when opening UTF-8 encoded files (.md, .txt, etc.), non-ASCII characters are not displayed correctly. 

V: 2.17.00033

**Comment by rakekniven** [comment]
Works here pretty well. Could you provide screenshot or example file?

Do you have UTF-8 with BOM?

**Comment by rakekniven** [comment]
Related to #13 . Maybe a dup.

**Comment by ho1ger** [comment]
I do not know if BOM is used or not. Editor is Atom on a Mac. The file opened in the screenshot is also attached.

![2017-04-03 15-56-26 0695](https://cloud.githubusercontent.com/assets/8535968/24612881/cc0db372-1886-11e7-84aa-8891f84afb32.png)
[test.txt](https://github.com/nextcloud/ios/files/890279/test.txt)

**Comment by rakekniven** [comment]
Added more information to #13 and closing this one to stay with the previous.
