### ISSUE TITLE
Meaning of "_background_"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#1595]
https://github.com/nextcloud/ios/blob/38c8c5b94f491a053fdfe062050cd0dee75eda06/iOSClient/Supporting%20Files/en.lproj/Localizable.strings#L177

Hello @marinofaggiana , 

is "background" a optical thing? Background of the file listing for example?

Or is it related to a "background task"?

**Comment by castillo92** [comment]
Thanks you Rakekniven for asking =)

**Comment by marinofaggiana** [comment]
> is "background" a optical thing? Background of the file listing for example?

Exactly!!
