### ISSUE TITLE
Allow login with 2FA without app password

### ISSUE THREAD

**Issue by wallenium** [nextcloud/ios#16]
Would be great, if you are able to Login with the 2FA tocken instead of an app Password. Currently, a "normal" user is lost when forced to use 2FA....

**Comment by marinofaggiana** [comment]
yes @wallenium this is a important modify

**Comment by wallenium** [comment]
@marinofaggiana If this gets implemented, please check this here as well: https://github.com/nextcloud/server/issues/2906

**Comment by timbru31** [comment]
This is basically the first issue ever: #1  
I'd like the approach to either support app passwords are the possibility to enter a two factor code in a second screen after the password.

**Comment by mario** [comment]
This should be possible to implement starting NC v12 hopefully :)

Patience, we are hard working on this!:)

**Comment by MariusBluem** [comment]
@marinofaggiana What is the state with the login flow, Talk app already has?

**Comment by marinofaggiana** [comment]
January

**Comment by wallenium** [comment]
Any news regarding this Feature request? January definitly Passed ;)

**Comment by MariusBluem** [comment]
Done.
