### ISSUE TITLE
PDF viewer: too much space of screen wasted by top/bottom bars

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/ios#160]
When you view a PDF file in "widescreen mode" I think the top and bottom bars (displaying file name (top) and two icons (bottom)) use way to much space. Taken together this is about 20% of the screen height. Is it possible to hide the bars? Or to make them smaller!?

V: 2.17.00033

**Comment by rakekniven** [comment]
@marinofaggiana  Can you hide top and bottom bar when touching pdf view to get fullscreen view.
Same as for photos?

**Comment by ho1ger** [comment]
Sorry for late response. Meanwhile I am on 2.17 (40).

No, I cannot go full screen with PDF files in widescreen. By tapping on the PDF I can hide or show small icons representing each page of the PDF but I cannot hide any bars.

![2017-04-19 15-15-49 0845](https://cloud.githubusercontent.com/assets/8535968/25181913/5544f680-2513-11e7-8743-2eeab33ceefa.png)
![2017-04-19 15-15-53 0846](https://cloud.githubusercontent.com/assets/8535968/25181914/555261b2-2513-11e7-9142-9b73624c5700.png)
![2017-04-19 15-16-03 0847](https://cloud.githubusercontent.com/assets/8535968/25181915/558503ec-2513-11e7-99d5-85b709dee72b.png)

**Comment by rakekniven** [comment]
Hello @ho1ger My questions have been addressed to @marinofaggiana

**Comment by marinofaggiana** [comment]
I am here ! 😄 Yes this is a goood question YES !

**Comment by marinofaggiana** [comment]
done. next version
