### ISSUE TITLE
Show folders after rotation of screen

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/ios#161]
When I browse to a folder (phone upright) and then rotate the phone to widescreen, *sometimes* the file/folder list at the left is not shown. I only see an empty screen with a "<"-symbol at the top bar.  When I press on "<" the file/folder list is shown as I want. 

Unfortunately I do not know how to replicate the issue. 

V: 2.17.00033

**Comment by rakekniven** [comment]
Could not manage to reproduce issue. Could you provide screenshot as soon as issue is present again?

Which phone model are you using?

**Comment by ho1ger** [comment]
iphone 7 plus, latest OS. Will try to reproduce the issue later.

**Comment by ho1ger** [comment]
Playing for 10 mins now. Bug won't show up anymore. Maybe he is scared ;-) I close this one.

**Comment by ho1ger** [comment]
I must correct my initial bug report as follows: 

When I have a file, e.g. PDF, opened in portrait mode (phone upright) ...

![2017-04-19 15-15-33 0842](https://cloud.githubusercontent.com/assets/8535968/25182240/44a0fcec-2514-11e7-989f-bae0ade076d4.png)

... and then rotate the phone to widescreen, I get an almost blank screen:

![2017-04-19 15-15-38 0843](https://cloud.githubusercontent.com/assets/8535968/25182238/449e701c-2514-11e7-8f91-530a7ad5363f.png)

I need to press on the "<"-symbol at the top bar to get back to the folder view

![2017-04-19 15-15-45 0844](https://cloud.githubusercontent.com/assets/8535968/25182239/44a0040e-2514-11e7-802e-eecf0e713587.png)

However, I actually expect when I rotate the screen that my PDF is rotated, not exited.
