### ISSUE TITLE
background media playback is interrupted when I launch nextcloud ios app

### ISSUE THREAD

**Issue by not-mms** [nextcloud/ios#1610]
### Steps to reproduce

1. Launch youtube (with premium subscription) or music app, start playback.
2. Launch nextcloud app.

### Expected behaviour

Youtube or music playback continues in the background, while I manage my nextcloud documents in the foreground.

### Actual behaviour

Background playback is interrupted and I have to switch back to youtube or use playback controls to resume it. That's really annoying, especially if I listen to some live stream and I miss some part of it. Then I switch back to nextcloud again to work with documents while I listen something in the background.

### Reasoning or why should it be changed/implemented?

That's really annoying, especially if I listen to some live stream and I don't want to miss a part of it when I launch nextcloud.

### Environment data

**iOS version:** iOS 14.5.1

**Nextcloud iOS app version:** 3.4.2.0

**Server operating system:** FreeBSD 12.2-RELEASE-p6

**Web server:** NGINX 1.20.0_1,2

**Database:** MariaDB 10.4.18

**PHP version:** 7.4.16

**Nextcloud version:** 21.0.1

**Comment by pwhack** [comment]
I'm experiencing this too. I'd expect existing background audio playback to be interrupted by Nextcloud app only when I open a video or audio file in the app.

iOS: 14.4.2
Nextcloud iOS app: 3.4.2.0

**Comment by marinofaggiana** [comment]
> I'm experiencing this too. I'd expect existing background audio playback to be interrupted by Nextcloud app only when I open a video or audio file in the app.
> 
> iOS: 14.4.2
> Nextcloud iOS app: 3.4.2.0

This is correct ! only one application can be execute the audio system, if you under Nextcloud listen a file audio or video this stopped the other background audio

**Comment by pwhack** [comment]
> > I'm experiencing this too. I'd expect existing background audio playback to be interrupted by Nextcloud app only when I open a video or audio file in the app.
> > iOS: 14.4.2
> > Nextcloud iOS app: 3.4.2.0
> 
> This is correct ! only one application can be execute the audio system, if you under Nextcloud listen a file audio or video this stopped the other background audio

That makes sense, that's what I expect. However, Nextcloud is stopping background audio even when I am only looking at pictures, for example. As soon as I open Nextcloud, background audio is stopped, no matter what content is in Nextcloud app. This is not what I expect to happen. Nextcloud should only stop background audio when an audio file or video is played inside Nextcloud app.

**Comment by marinofaggiana** [comment]
@pwhack  ok, you can try the new V 4 build >= 13 in TestFlight

**Comment by foss-** [comment]
https://testflight.apple.com/join/GjNbfo2a

Can confirm this no longer is a problem using NextCloud 4.0.0 (13)

**Comment by not-mms** [comment]
> @pwhack ok, you can try the new V 4 build >= 13 in TestFlight

nice! I've tried v4 too and nextcloud didn't interrupt youtube playback after I started the former. more to that it didn't interrupt youtube playback when i decided to listen to a short audio file in nextcloud. great! :)

**Comment by marinofaggiana** [comment]
Fixed V 4

**Comment by not-mms** [comment]
Unfortunately it doesn't work in all cases. I've checked v4.0.1 and it works not as expected with airpods. As if it breaks the audio routing: the background playback itself is not interrupted, but the audio output is switched to the phone's speakers. It would be great if you check that case too. Thanks in advance :)

**Comment by foss-** [comment]
Maybe a new issue would be appropriate as the original problem has been addressed and this remaining problem is separate although related.

**Comment by marinofaggiana** [comment]
Wait (soon) the 4.0.2 in TestFlight.

**Comment by not-mms** [comment]
I've tested nextcloud ios v4.0.4 and it works as expected with airpods: youtube background playback is not interruped in any way, yay! :)

**Comment by pwhack** [comment]
I can confirm that Nextcloud mobile app v4.0.4.0 on iOS 14.6 is no longer interrupting background audio when the NC app is opened and when opening images and text documents. Many thanks for fixing that!

I did notice that when playing an audio file or video inside the NC app, the background audio continues so the audio is then blended. I'm not sure if that was the intention and is probably best discussed in another GitHub issue. But the original issue (merely opening the app, viewing pictures, viewing text documents should not interrupt background audio) is resolved. Thank you again!
