### ISSUE TITLE
Bug with deleting photos

### ISSUE THREAD

**Issue by lisetauber** [nextcloud/ios#1612]
Hello Marino,

Version 3.5.0.27 on iOS crashes from time to time. 

The deletion of the photos from the iPhone after the automatic sending also bugs, you have to tap on the "delete" button maybe as many times as there are photos!
Impossible to exit the app until the pictures are deleted. 

And once the pictures are finally deleted, the app freezes. You have to close it. 

NC iOS 3.5.0.27 
NC server 20.0.6
iPhone 8 Plus - iOS 14.6

I haven't noticed these bugs on iPadOS. 

Best regards
Lise

![IMG_5693](https://user-images.githubusercontent.com/31109077/120223700-4b300380-c242-11eb-8987-0121e2b61eaf.jpg)

**Comment by marinofaggiana** [comment]
hi, this view is managed completely from iOS ... so I cant change nothing.

**Comment by lisetauber** [comment]
Hello Marino,
I just tested with the previous version (3.5.0.25) and I haven't this problem.
Lise
