### ISSUE TITLE
Can't input korean in file name when creating text document/voice memo

### ISSUE THREAD

**Issue by hellojaccc** [nextcloud/ios#1613]
### Steps to reproduce

1.Touch upload button
2.Touch 'Create text document' or 'Create voice memo'
3.Touch 'Filename'

### Expected behaviour

Show keyboard with korean, emoji

### Actual behaviour

Showed keyboard without korean, emoji. (Only English)

### Screenshots

https://user-images.githubusercontent.com/71537512/120764033-c5b69700-c552-11eb-9bbc-02702172ab44.MP4

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Environment data

**iOS version:** e.g. iOS 14.4.1

**Nextcloud iOS app version:** see More > Settings
iOS 3.2.2.0

**Server operating system:**

**Web server:** Apache, nginx

**Database:**

**PHP version:**

**Nextcloud version:** see Nextcloud admin page

**Comment by marinofaggiana** [comment]
Fixed V 4
