### ISSUE TITLE
Functional enhancement: Allow editing of .txt/.md-files

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/ios#162]
It would be awesome if you could integrate a basic function that allows editing text files. 

V: 2.17.00033

**Comment by rakekniven** [comment]
Related to #21

**Comment by sushidave** [comment]
This function is available in the ownCloud iOS app. Could it be copied to the Nextcloud app?

**Comment by MarcusE1W** [comment]
.txt files can now be edited.
Still, .md and .org would still be desirable .

.org is also a plain text markdown language that also supports tasp management

**Comment by rakekniven** [comment]
IMHO we should split issue and have seperate ones for each file type.
@marinofaggiana Could you remember the version you introduced editing of text files?

**Comment by rakekniven** [comment]
Ah, just saw new issue. Please split it. Thank you @MarcusE1W

**Comment by MarcusE1W** [comment]
I have added #471 for markdown and #472 for org-mode. As .txt support is already available I guess this issues could be closed.

**Comment by rakekniven** [comment]
@marinofaggiana Could you remember the version you introduced editing of text files?

**Comment by rdxmb** [comment]
Since the last update it is not possible anymore anymore to edit .md-Files via the iOS-App. I also cannot add new text-files via the app anymore. What's up here?

**Comment by rakekniven** [comment]
Just did it and it works. Client app v3.0.0 and NC v19.0.0. iOS v 13.5.1

>  I also cannot add new text-files
Please explain more in detail.

> Since the last update it is not possible anymore anymore to edit .md-Files
Did you change something server side? I am using the text app and loads pretty well.

**Comment by rdxmb** [comment]
`Just did it and it works. Client app v3.0.0 and NC v19.0.0. iOS v 13.5.1`

Oh, this is good news! Thanks for your answer! 

Ok, let me explain more: 
* Client app v3.0.0 on iOS 13.5.1
* Server Version nextcloud:17.0.3 in Docker

`Did you change something server side?`
Definitely no.

`Please explain more in detail.`

Touching the big blue `+` I am able to:
* add new photos or videos
* upload files
* scan documents
* record notice with the microphone
* create folder

There is not a point to create a textdocument anymore.

When I touch a .md-file, it opens to read and there is a button to share, but I do not find anything to edit.

![20-06-29 13-59-29 0612](https://user-images.githubusercontent.com/30314040/86003676-71d23280-ba12-11ea-9219-68b7b3c39b73.png)
![20-06-29 14-08-53 0613](https://user-images.githubusercontent.com/30314040/86003685-7565b980-ba12-11ea-8554-4d08e449ca0c.png)

**Comment by rakekniven** [comment]
Version 3 is a rewrite in many ways.
Could you try to enable app "Text" (https://apps.nextcloud.com/apps/text) ?

Maybe the integrated editor component has been removed and the app uses the server app for editing. At least that is my idea :-)

**Comment by rdxmb** [comment]
"Text" ist still enabled. I can also use it within my browser.

> Maybe the integrated editor component has been removed 

Integrated in what? In the nextcloud app?

**Comment by rakekniven** [comment]
> Integrated in what? In the nextcloud app?

Integrated in iOS Nextcloud app.

> Maybe the versions are not compatible and I have to update to use it with the iOS-app (?)

Maybe, not sure to be honest.

**Comment by rdxmb** [comment]
status: Upgraded to NC 17.0.7 - same problem
going on ...

**Comment by rdxmb** [comment]
upgrading to 18.6
```

The following apps have been disabled:
...
text
...
```

:confused:

**Comment by rdxmb** [comment]
Working again with 18.0.6

seems like the edit functions within the app has changed: In the last app I had to click to edit - here it appears like the editing in the browser

I didn't have to activate the app "Text" again.

**Comment by rdxmb** [comment]
@rakekniven thanks for encouraging me to update ;)
