### ISSUE TITLE
Bug: Not possible to select photos from shared photo library

### ISSUE THREAD

**Issue by wiegell** [nextcloud/ios#1624]
### Steps to reproduce

1. Click plus
2. Upload photos and videos
3. Try and find iCloud shared photo library

### Expected behaviour

Should be possible - google drive sees it

### Actual behaviour

Is not listed

### Reasoning or why should it be changed/implemented?
It's annoying since the context share button, when used from within the shared album, only supports 20 photos at a time

### Environment data

**iOS version:**
14.4.2

**Nextcloud iOS app version:** see More > Settings
3.4.2.0

**Nextcloud version:** see Nextcloud admin page
21.0.2

**Comment by marinofaggiana** [comment]
@wiegell should be available from the V 4 correct ?

**Comment by wiegell** [comment]
Yes, gj!
