### ISSUE TITLE
Bug: iphone SE plays sound on the top speaker instead of main speaker (barely audible)

### ISSUE THREAD

**Issue by wiegell** [nextcloud/ios#1627]
### Steps to reproduce

1. play a video, live photo or mp3 on an iPhone SE (original)
2. sound is barely audible bc it's coming from the top speaker (meant for use when talking on the phone)

### Environment data

**iOS version:** e.g. iOS 14.4.1
14.4.2

**Nextcloud iOS app version:** see More > Settings
4.0.1.1

**Server operating system:**
Armbian, Docker Linuxserver image

**Nextcloud version:** 
21.0.2

**Comment by marinofaggiana** [comment]
Hi, Can you try with the 4.0.2 in TestFlight if resolved ?

**Comment by wiegell** [comment]
It is! Perfect, great response time!
