### ISSUE TITLE
firebaselogging-pa.googleapis.com continuously contacted with crash reporter disabled

### ISSUE THREAD

**Issue by vszakats** [nextcloud/ios#1628]
### Steps to reproduce

1. Settings → Advanced → Disable crash reporter → Enable (= _disable_ crash reporter)
2. Re-launch Nextcloud iOS app
3. Watch DNS queries initiated by the device and see `firebaselogging-pa.googleapis.com` being queried on startup and while using the app.

### Expected behaviour

When crash reporting is disabled, the app should not make request to the related Google service.

### Actual behaviour

App looks up the DNS entry `firebaselogging-pa.googleapis.com` on startup and then continues doing so while using it.

### Reasoning or why should it be changed/implemented?

Nextcloud users can rightfully expect/prefer that Google data collection services are not being contacted with crash reporting explicitly disabled.

### Environment data

**Nextcloud iOS app version:** 4.0.1.1
**iOS version:** 14.6

Maybe related:
https://github.com/firebase/firebase-ios-sdk/issues/8220
https://github.com/firebase/firebase-ios-sdk/issues/5837

**Comment by vszakats** [comment]
The [suggested](https://github.com/firebase/firebase-ios-sdk/issues/8220#issuecomment-858742232) (and subsequently confirmed) solution is to add this key to the app's `Info.plist` file:
```xml
<key>FirebaseDataCollectionDefaultEnabled</key>
<false/>
```

**Comment by fireglow** [comment]
I'm also seeing this.
I feel the App Stores "App Privacy" needs to be updated to show that diagnostic data is being collected.
![Nextcloud-web](https://user-images.githubusercontent.com/16845/124387394-c2900180-dcde-11eb-878d-099eff2501b6.jpg)

**Comment by vszakats** [comment]
Tracking requests seem to be no longer made as of Nextcloud iOS 4.0.6. But there was no commit or changelog message about it.

@marinofaggiana: Can you confirm that a fix have been applied for this issue?

**Comment by vszakats** [comment]
I'm closing this as resolved, based on the observed DNS request activity alone.

**Comment by juju4** [comment]
I see firebaselogging-pa.googleapis.com in my proxy logs each time i do a manual refresh.
Crash reporter disabled

Nexcloud liquid for iOS 4.3.1.0
iOS 15.4.1
