### ISSUE TITLE
Resolution of the Loading Icon

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/ios#163]
Its not important but I think this icon needs to be renewed when the data is loaded. Because image is not clear. :) 

![2017-04-02 13-00-28 0906](https://cloud.githubusercontent.com/assets/297968/24617716/6cd5b3a2-189d-11e7-90ea-eb8cd52b83bf.png)

**Comment by rakekniven** [comment]
Which Apple model are you using?
Which app version is installed?

**Comment by emresaracoglu** [comment]
@rakekniven iPhone 5S - Nextcloud 2.**17**

**Comment by emresaracoglu** [comment]
Maybe?

![balls 1](https://cloud.githubusercontent.com/assets/297968/24628727/3484d488-18c0-11e7-9c5d-5e248886cffb.gif)

**Comment by emresaracoglu** [comment]
The blurry image is still going on with the new update (Cache cleaned / 2.17-38)

**Comment by marinofaggiana** [comment]
39 :)

**Comment by emresaracoglu** [comment]
Right now 38,

**Comment by emresaracoglu** [comment]
I laughed the first time I saw this "Loading" 😆
It's nice that you prefer writing instead of icon:)
![2017-04-19 12-06-00 1607](https://cloud.githubusercontent.com/assets/297968/25172498/f45a108a-24f9-11e7-80f6-5e8ad80a2ea3.png)
