### ISSUE TITLE
Three dot icon for expanding menu options overlaps text field in portrait mode on iPhone 12

### ISSUE THREAD

**Issue by aveng3rr** [nextcloud/ios#1634]
### Steps to reproduce

1. Open text document on iPhone 12 while in portrait mode

### Expected behaviour

Menu icons should not overlap text area. 

### Actual behaviour

Three dot icon for expanding menu options overlaps text field in portrait mode. 

### Screenshots

![Screenshot 2021-07-05 at 09 57 22](https://user-images.githubusercontent.com/55419992/124512371-06d9db00-dd8d-11eb-9d14-3f23132a1702.png)
![Screenshot 2021-07-05 at 10 00 56](https://user-images.githubusercontent.com/55419992/124512399-1e18c880-dd8d-11eb-92a9-54445f00fb81.png)
![Screenshot 2021-07-05 at 10 02 34](https://user-images.githubusercontent.com/55419992/124512426-312b9880-dd8d-11eb-9b3b-283f28de642b.png)
![Screenshot 2021-07-05 at 10 02 52](https://user-images.githubusercontent.com/55419992/124512445-3daff100-dd8d-11eb-9818-20f1dafe4ced.png)

### Reasoning or why should it be changed/implemented?

Menu icons overlapping the text field interfere with text input on the first line of the text area. 

### Environment data

**iOS version:** iOS 14.6

**Nextcloud iOS app version:** 4.0.4

**Server operating system:** Ubuntu Server 20.04.2

**Web server:** Apache

**Database:** mariadb

**PHP version:** 7.4.3

**Nextcloud version:** 21.0.1

**Comment by marinofaggiana** [comment]
Duplicated

https://github.com/nextcloud/text/issues/1708
