### ISSUE TITLE
Extended menu icons don’t collapse into the the three dot menu icon after leaving landscape mode

### ISSUE THREAD

**Issue by aveng3rr** [nextcloud/ios#1635]
### Steps to reproduce

1. Open text document on iPhone 12 while in landscape mode and then rotate iPhone to portrait mode. 

### Expected behaviour

Menu icons should collapse into three dot menu icon after iPhone is rotated into portrait mode. Menu icons should not overlap text area in portrait mode.  

### Actual behaviour

Extended menu icons don’t collapse into three dot menu icon when iPhone is rotated into portrait mode. Extended menu icons overlap text field in portrait mode after rotation from landscape mode. 

### Screenshots

![Screenshot 2021-07-05 at 10 06 27](https://user-images.githubusercontent.com/55419992/124514639-5d95e380-dd92-11eb-90e3-b19e00b15c6c.png)

### Reasoning or why should it be changed/implemented?

Menu icons overlapping the text field interfere with text input in text area. 

### Environment data

**iOS version:** iOS 14.6

**Nextcloud iOS app version:** 4.0.4

**Server operating system:** Ubuntu Server 20.04.2

**Web server:** Apache

**Database:** mariadb

**PHP version:** 7.4.3

**Nextcloud version:** 21.0.1

**Comment by marinofaggiana** [comment]
Duplicated

https://github.com/nextcloud/text/issues/1708
