### ISSUE TITLE
Problem when using mobile Data

### ISSUE THREAD

**Issue by Max123459** [nextcloud/ios#1636]
### Steps to reproduce

1. Using mobile Data (good connection), current iOS Version. 
2. Try to download a pdf file or create a folder

### Expected behaviour
Opening files (pdf for example) or creating folders

### Actual behaviour
Doesn‘t work SOMETIMES, app shows „Datei herunterladen - Verbindung zum Server konnte nicht hergestellt werden“. Translated: Download file - Connection couldn‘t be established.

Works fine when using WLAN or using the webbrowser.

Also happens with different locations, … - network speed isn‘t the problem. It works sometimes at the same location!

### Screenshots
![foto_no_exif](https://user-images.githubusercontent.com/34142332/124629482-c6a85480-de81-11eb-9fda-bc9cbb07d21d.jpg)

### Environment data

**iOS version:** 14.6

**Nextcloud iOS app version:** 4.0.4.0

**Server operating system:** Debian

**Nextcloud version:**
20.0.8 (NextcloudPi)

**Comment by marinofaggiana** [comment]
Hi @Max123459 but the error say already:  Connection couldn‘t be established.

**Comment by Max123459** [comment]
Yes, but it has to be a App (or server) issue.
The connection is stable and with the web browser it works without problems.

Sometimes it works to open a JPEG but not a PDF.

But its not only opening files, also uploading pictures for example. They don‘t start 5 seconds later, they just don‘t upload.
