### ISSUE TITLE
Not working or respoding late - Share button in Photos

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/ios#164]
If there are more than 100~ photos in the gallery, the share button does not work or responding late

![2017-04-02 13-01-32 0907](https://cloud.githubusercontent.com/assets/297968/24618015/55e52dac-189e-11e7-8db6-322b51bfd174.png)

**Comment by rakekniven** [comment]
Which Apple model are you using?
Which app version is installed?

Which button is the share button? Top right like in other apps?

**Comment by emresaracoglu** [comment]
@rakekniven iPhone 5S - Nextcloud 2.**17**
Yes right-top

**Comment by marinofaggiana** [comment]
Do you want share 100 images ???

**Comment by emresaracoglu** [comment]
Of course no @marinofaggiana I tested only for the performance of the application

**Comment by marinofaggiana** [comment]
yes but do not exists a solution, the images must be transferred in local sandbox ... and this required time ...

**Comment by emresaracoglu** [comment]
I understand, I can close the ticket.
