### ISSUE TITLE
Images can't be zoomed in app

### ISSUE THREAD

**Issue by CircuitC** [nextcloud/ios#1649]
### Steps to reproduce

1. Upload image through computer (web browser), likely does the same when uploaded from phone
2. Load the image in the iOS app
3. Attempt to pinch or double tap the image to zoom

### Expected behaviour

The image should be able to be zoomed by pinching or double tapping the screen.

### Actual behaviour
Through the iOS app, it's not possible to pinch to zoom into an image. This happens minutes after the image has been uploaded (meaning the image has been processed and viewable), and after several days since the image was uploaded and processed. This doesn't seem to happen based on image resolution because, I have images of differing sizes and all are affected the same. 

### Screenshots
From phone:
![126837202-21827f74-8db1-405e-8061-9ca655dcfdb4](https://user-images.githubusercontent.com/67488680/127377364-de19db95-6d67-4388-9611-09d0401ae814.png)

### Reasoning or why should it be changed/implemented?
This should be improved to make it possible to view details in an image, and make the resolution of an image able to be used to its full capacity. 

### Environment data

**iOS version:** iOS 14.6

**Nextcloud iOS app version:** 4.0.4

**Server operating system:** Dietpi v 7.3.2

**Web server:** Apache(?)

**Database:** Unknown/ N/A(?)

**PHP version:** 7.3.29~deb10u1

**Nextcloud version:** 22.0.0

**Comment by marinofaggiana** [comment]
Hi ! it's a preview or an image with max resolution ? (use the "Download the images in full resolution")

**Comment by CircuitC** [comment]
The issue that I'm attempting to describe is that when an image is opened by clicking on it, and it is displayed in the NextCloud app or in a mobile browser, it is not able to be zoomed.

**Comment by CircuitC** [comment]
I see the recent app update includes an improvement for zooming in images, thank you. I'll write here as soon as I get a chance to test it.

**Comment by CircuitC** [comment]
The issue persists in version 4.2.0 (the images aren't able to be zoomed into/ enlarged by pinching the screen). This also still occurs in iOS Safari.

Also updated NC server to 23.0.0
