### ISSUE TITLE
Search box is not fully visible on screen in app

### ISSUE THREAD

**Issue by CircuitC** [nextcloud/ios#1650]
### Steps to reproduce

1. Click the magnifying glass close to the top of the screen

### Expected behaviour
The entire search box should fit on the screen.

### Actual behaviour
When the magnifying glass is selected to search, the search box shows up but only part of it is visible and there doesn’t seem to be a way to center it. This issue also seems to occur through mobile browsers based on this forum post: https://help.nextcloud.com/t/search-box-cut-on-mobile-browsers/112634. Typing in the search field doesn’t affect the behavior. Attempting to pinch and zoom the screen out to center the search, closes the search box.

### Screenshots
![Search box bug screenshot](https://user-images.githubusercontent.com/67488680/126850991-b5e5a0b2-051a-4366-9fff-5b98b20011ab.png)

### Reasoning or why should it be changed/implemented?
Improving this would make the text typed in the search field and the results of the search visible.

### Environment data

**iOS version:** iOS 14.7

**Nextcloud iOS app version:** 4.0.4

**Server operating system:** Dietpi v 7.3.2

**Web server:** Apache(?)

**Database:** Unknown/ N/A(?)

**PHP version:** 7.3.29~deb10u1

**Nextcloud version:** 22.0.0**

Side note: not sure if it’s meant to be, but the UI of the app is similar if not a down sized version of what I see on a computer’s browser, and this look is different to what is displayed in the screenshots of the app on the app store and in the guthub readme.

**Comment by marinofaggiana** [comment]
Hi, but about Safari ?

**Comment by CircuitC** [comment]
Safari has the issue too, the only difference is that I can pinch to zoom the page without the search box closing immediately (it's still only partially visible though).

**Comment by CircuitC** [comment]
The issue seems to be fixed (in the app and Safari) after updating the server software (what runs on host computer) to version 22.2.0 (using iOS app version is 4.0.6).
