### ISSUE TITLE
Text file preview is showing korean letters as box

### ISSUE THREAD

**Issue by hellojaccc** [nextcloud/ios#1652]
### Steps to reproduce

1. Long press text file

### Expected behaviour
Show korean/number/alphabet properly

Tell us what should happen.

### Actual behaviour
Showed boxes instead of korean letters

Tell was what instead happens.

### Screenshots
![21-07-28 19-29-00 0249](https://user-images.githubusercontent.com/71537512/127308065-a59a4cd7-d4f6-4925-80b6-d6b23e2f511c.png)

If applicable, add a screenshot showing the issue.

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Environment data

**iOS version:** e.g. iOS 14.4.1
iOS 15 
**Nextcloud iOS app version:** see More > Settings
4.0.5.8
**Server operating system:**

**Web server:** Apache, nginx

**Database:**

**PHP version:**

**Nextcloud version:** see Nextcloud admin page

**Comment by marinofaggiana** [comment]
Hi, this view show the "preview" of Text file generated server side.

https://github.com/nextcloud/text/issues/1799
