### ISSUE TITLE
Markdown editor - wrong position of three dot button

### ISSUE THREAD

**Issue by hellojaccc** [nextcloud/ios#1658]
Sorry, i'm on mobile and cannot load the format of issue

That 'three dot button' is over the text, and pops up when i try to edit text. 

Device : iPhone SE 2
OS : iOS 15
Nextcloud app version : 4.0.6.0

![image](https://user-images.githubusercontent.com/71537512/128338381-4d08be72-d3b1-49b8-81a8-024951c53079.jpeg)

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/text/issues/1708
