### ISSUE TITLE
app freezes when synching photos

### ISSUE THREAD

**Issue by tommyguuuun** [nextcloud/ios#167]
When i try to synch all my existing pictures (iphone 6s, latest ios), what are about 3000, the app freezes and doesn't respond anymore. It closes after a certain amount of time. Also the menu point where i can select the photos upload folder is gone with switching to the beta version.

**Comment by marinofaggiana** [comment]
Have you selected : use subfolder ?

**Comment by tommyguuuun** [comment]
negative, i'd like to have an all-in-one synchfolder, like it does on the drop**x app... the timestamps are useful, but it's slow. And it spams the cache - currently it's loaded with 3gb data and counting. When i'm going to delete the cache, the file upload stops.

**Comment by tommyguuuun** [comment]
and is it a problem of mine, that the ability to choose the directory of the photo upload is gone? Is has been there in the normal version..

**Comment by marinofaggiana** [comment]
This is not a issue, the app creates a DB of 3000 records ... wait the end ..

**Comment by marinofaggiana** [comment]
If news please reopen this.
