### ISSUE TITLE
Nextcloud iOS App - Invalid Certificate

### ISSUE THREAD

**Issue by williamsth** [nextcloud/ios#1682]
### Steps to reproduce

Re-opening a new issue as I see similar issue was closed a few years ago

1. Valid LetsEncrypt certificate. Apache/2.4.6 (CentOS). PHP 7.3.29 
2. Open iOS App - see error "The certificate for this server is invalid"

### Expected behaviour

App should work without any error. The SSL certificate is valid and works on every other device/browser. The certificate is not self signed and is signed by LetsEncrypt. Qualys SSL Labs gives the server A+ rating on SSL.

### Actual behaviour

Error message is shown "The certificate for this server is invalid". I have no reason to suspect MITM - happens on both WiFi/Cellular on multiple iOS devices. Couple of comments on closed issue 1036 recently so problem seems like it could effect others

### Screenshots

![Screenshot 2021-08-27 at 12 46 45](https://user-images.githubusercontent.com/51209085/131122708-8e21ba48-66a2-442b-98b1-f656606425c8.png)

### Logs

Various logs upon request

### Reasoning or why should it be changed/implemented?

N/A

### Environment data

*iOS version:** iOS 14.7.1

**Nextcloud iOS app version:** 4.0.6.0

**Server operating system:** CentOS Linux release 7.9.2009 (Core)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3.29

**Nextcloud version:** 21.0.4

**Comment by jatofg** [comment]
I have the same issue. Same iOS and app version, also a Let’s Encrypt certificate. I’ve attached screenshots of the certificate details, the server https://cloud.qto.be can be used to reproduce the issue.

The problem only occurs in the iOS version of the Nextcloud app.

<img width="810" alt="Screenshot 2021-08-30 at 22 13 22" src="https://user-images.githubusercontent.com/10060641/131399730-8c9d7a59-0859-4a67-b100-cf477a8dcf97.png">
<img width="810" alt="Screenshot 2021-08-30 at 22 14 23" src="https://user-images.githubusercontent.com/10060641/131399929-eaeb2167-b2b0-4e26-8565-6922cbee9a73.png">

**Comment by williamsth** [comment]
Just to add - clearing the app cache doesn’t resolve the issue. I’m happy to provide logs or a cloud account or potentially even server access to Nextcloud staff but it’ll need to be done in a controlled way.

**Comment by houdini69** [comment]
Same issue for me on iOS 14.7.1 with a personal account. Let's Encrypt valid certificate, Nextcloud 21.0.4 with Nginx web server (Armbian 21.08.1 Buster). Interestingly, I haven't this behaviour with another corporate account.

**Comment by snarman** [comment]
Also happens for me since a couple of days with iOS 14.7.1 and Nextcloud 22.1.1 with Let's Encrypt certificate that is valid using Nginx Reverse Proxy to serve the certificate.

**Comment by ge-fa** [comment]
People told that they're affected as well. A fix would be very much appreciated. Thank you!

**Comment by pwaring** [comment]
As mentioned in #1036, I'm experiencing the same issue with the latest versions of Nextcloud (server and app) and iOS. I'm using LetsEncrypt and my server runs Nginx, but as a normal web server (no proxy). All other methods of accessing Nextcloud work - Linux desktop client, web interface in a browser (even on the same device as the iOS app) and Android app.

**Comment by diikhub** [comment]
Me too. iOS 14.7.1, Nextcloud 4.0.6.0. My Lets Encypt certificate was actually few days expired (my bad). Once renewed it has worked everywhere (Android, Linux client, Web version using FF) but iOS no go. It says the cert is invalid. Server restarted, still the same.

**Comment by marinofaggiana** [comment]
Hi all, 
if can help you:

https://community.letsencrypt.org/t/connection-is-not-trusted-ios-only/55374

**Comment by williamsth** [comment]
@marinofaggiana According to SSL Labs I am sending all intermediate certificates and there are no advised chain issues.

**Comment by pwaring** [comment]
I'm also sending the full chain (SSL Labs agrees). Plus this was working a few months ago - well after the 2018 date in the LetsEncrypt thread.

**Comment by jatofg** [comment]
@marinofaggiana No, this issue occurs in the Nextcloud app only. Neither Safari nor iOS itself (CalDAV/CardDAV) report any issues with the certificate.

**Comment by diikhub** [comment]
@marinofaggiana Nextcloud Talk on the same iOS device reports no certificate issue :-) Also SSL Labs test did not report any chain issues...

**Comment by jetpigeon** [comment]
Hello, I'm new here. But just to confirm am experiencing the same issue.

Worked fine this morning with certbot issued cert that was originally using `nextcloud.enable-https lets-encrypt`.

However, since migrating to HAProxy today, also with a valid LetsEncrypt cert (albeit muti-SAN) the IOS app is now complaining that the certificate is invalid.

Verified working fine on Android and multiple browsers. SSLLabs also is very happy with the cert / chain.

Pleased to see this is not just me.

**Comment by errolsancaktar** [comment]
I am running into this as well I use haproxy and a wildcard cert that is valid.

**Comment by laolux** [comment]
I have the same issue, running nextcloud behind a nginx proxy which handles the tls stuff. Certificate from letsencrypt.
Works fine on my desktop, any browser I have tried, nextcloud app works fine on **iPhone** but **not** on my **iPad**.
version of the app in both cases 4.0.6.0

**Comment by williamsth** [comment]
Interestingly, I’ve updated to iOS 14.8 and I’m not seeing the issue now (so far). Not sure if anyone else is seeing this behaviour?

**Comment by pwaring** [comment]
I updated to iOS 14.8 yesterday and am still experiencing this behaviour.

**Comment by ne20002** [comment]
I'm also affected by this problem.
It popped up after moving my reverse proxy from Apache with LE RSA certificates on Raspian Buster to nginx with LE ECDSA cetificates on Debian Bullseye.

**Comment by KaraokeStu** [comment]
I have the same issue, running the latest NextCloud Docker PHP Docker image, surfaced using Traefik with LetsEncrypt.
All browsers, SSL Labs etc confirm the certificate is OK, but iOS (Running version 15, but also happened on 14.x) has the issue.

I can create a test account for you on my server if you need to reproduce

**Comment by eibex** [comment]
I have this issue on my iPad but not iPhone. They are on the same iOS version and NC app version.

**Comment by tokudan** [comment]
I'm also seeing this issue. iOS 14.7.1 with Nextcloud 21.0.3.
The Version of the iOS App is Nextcloud Liquid 4.0.6.0.

Curiously, my automatic camera upload is happily uploading files as soon as I open the App, either indicating that there is a severe security flaw in the certificate check or that the iOS app fails to accept a perfectly valid certificate.

**Comment by didaktiik** [comment]
My iOS devices are on iOS15 now and the problem is still there. As suggested earlier I double-checked cert files and correct versions of cert,pem and fullchain.pem are there.

My Nextcloud server config is as follows: Ubuntu 18.04 LTS + "snappy" Nextcloud (latest 22.1.1snap1 on stable-channel) + Let's Encrypt SSL cert.

I have tried several "virgin" computers and browsers (where I have never accessed my Nextcloud server) without problems.

**Comment by KucharczykL** [comment]
For me on iOS it actually says the invalid certificate is not my own but `Subject: CN=push-notifications.nextcloud.com`.

**Comment by julianpoy** [comment]
Experiencing the same issue

**Comment by stjeanp** [comment]
I'm running in to this as well. I've got a LetsEncrypt cert on the machine (CN=foo.bar.com; SAN=DNS:foo.bar.com, DNS:nextcloud.bar.com). I also have an argo tunnel to Cloudflare. It has its own cert (CN=sni.cloudflare.com; SAN=DNS:*.bar.com, DNS:sni.cloudflare.com; DNS:bar.com). It's set up that way so that I can access it locally, without hitting the Internet and from the Internet, via the argo tunnel, when I'm not at home, using the same URL (https://foo.bar.com/).

I'm getting this invalid certificate message for BOTH certificates. If I connect on the LAN, then kill wireless, it'll start complaining about the Cloudflare certificate. If I then turn wireless back on, it'll complain about the LetsEncrypt certificate. And I've already verified that I'm sending the full chain with the LetsEncrypt certificate. This is ONLY happening on the iOS app. My MacOS clients aren't complaining about the LetsEncrypt certificate. Hitting the public side from a system NOT on my LAN gets the Cloudflare certificate, which passes validity checks, as well.

**Comment by dawid-woitaschek** [comment]
Just wanted to leave a "#metoo" here... Just the iOS app is complaining about the valid LE cert. Currently on iOS 15.1 Beta 4, but got this issue on 15.0 as well.

**Comment by didaktiik** [comment]
Well, the de-linking and re-linking process has certainly cleared the issue. No more certificate warnings on both iOS devices. Thanks!

**Comment by bpottle1** [comment]
I'm having the same issue as @stjeanp above with the cloudflare tunnel and local Nginx connection. The iOS app complains about each certificate any time it has to switch between the one it uses.

**Comment by marinofaggiana** [comment]
Please try the last version in TestFlight if solved.

**Comment by bpottle1** [comment]
I just tried the TestFlight beta and it still has the same error about the certificate having changed and if I want to trust it.

**Comment by marinofaggiana** [comment]
But only the first time ? Or every time that restart the app ?

**Comment by stjeanp** [comment]
Have I just missed something super obvious? How would I get the testflight invite so that I can test it?

**Comment by bpottle1** [comment]
I didn’t know there was one either haha. I just googled it and found this link:
https://testflight.apple.com/join/GjNbfo2a

the beta kept crashing on me though but it still had the certificate error, so I just went back to the release version.

**Comment by bpottle1** [comment]
> But only the first time ? Or every time that restart the app ?

Every time I restarted the app or switched from internal to external network

**Comment by eibex** [comment]
The error still happens in the new app version. The message has just been changed to "Do you want to connect to the server anyway? Do you consider this server trusted?"

**Comment by williamsth** [comment]
I’m still getting this. I’m concerned about the priority assigned to this one as it’s quite a breaking bug in the app? Advising my users to bypass the error is not good practice and causes a security concern. 

Issue seems to reoccur with each certificate rotation which is 3 months for LE certs.

**Comment by vszakats** [comment]
HTTPS is not [TOFU](https://en.wikipedia.org/wiki/Trust_on_first_use). Instead, the client, after verifiying that the certificate is valid, non-revoked and matching the domain, is supposed to automatically trust a renewed/new certificate without asking the user about it. Passing this decision to the user by default seems inconvenient and also insecure (how could someone tell if a cert is valid by reading a leaf cert from a screen?).

Also, why does the client detect a new certificate at all? It means that the certificate, the verification result or some other state is cached somewhere, which is quite unusual and seems to break the protocol.

**Comment by marinofaggiana** [comment]
@vszakats we will check this point. But that this to break the protocol is not correct

**Comment by oberlon** [comment]
@vszakats As I wrote in my post some weeks ago the app use UICKeyChainStore and build its own truststore. On 2021-09-30 the "DST Root CA X3" has expired - which is saved in your local Nextcloud truststore - and breaks the chain of trust for your LE certificates. There is a function "CCUtility.deleteAllChainStore" which cleans this truststore but is only called when you remove your account in the app. After adding your account again everything works like expected.

**Comment by williamsth** [comment]
@oberlon That still sounds like a bug to me because root certificates expiring will happen periodically. The user shouldn’t be expected to do this.

**Comment by stjeanp** [comment]
Not only that, but for my instance, I have two different certificates for the same instance. One is provided by Cloudflare for public access. The other is provided by LetEncrypt for private access. I was running it such that, at home, the DNS resolved to the internal IP and outside of personal networks it resolves to the public IP. Changing IPs breaks it badly because of that caching.

**Comment by eibex** [comment]
@oberlon I've re-added my account multiple times on my iPad and the issue appeared for the first time today on my iPhone. LE root expiring was not the issue.

**Comment by tinus-github** [comment]
Would it be an option to just use the root certificate store provided by the OS? Let’s encrypt and similar certificates are trusted by that.

**Comment by vszakats** [comment]
@marinofaggiana: I may be missing something here, but browsers and HTTPS API-based clients rarely work by saving cert chains in permanent storage. HTTP/HTTPS is stateless by nature, except maybe cached [session keys](https://www.cloudflare.com/learning/ssl/what-is-a-session-key/) but these are stored only in memory for short periods.

If cert/domain validation is only done when first seeing a cert, that would be quite of bit of security issue, thinking of revocation as an obvious example. If this is something done _in addition_ to the normal way of validating HTTPS certs on each connection, I wonder why is this necessary and if there could an option to disable it, or to disable it unconditionally, and reserve such prompt to the case when there is an actual cert verification issue.

**Comment by oberlon** [comment]
Seems that some parts changed in the code. CCUtility.deleteAllChainStore is called in AppDelegate.swift and NCUtility.swift. Im not a Swift Dev but it looks like that NCManageDatabase.shared.getAccounts must be null to clean the truststore. So you have to remove all accounts in your app??? (Don´t trust me, i was reading the code for 5 min)

@tinus-github Thats right. But the developers store more information like client certificates oder encryption keys with this extern library. So it is not so easy to recode I think.

**Comment by marinofaggiana** [comment]
You can try with the 4.2.0 available on TestFlight if solved

**Comment by bpottle1** [comment]
Just installed the beta and so far so good! Will update if the issue resurfaces. Thanks for all your work on this!

**Comment by ict** [comment]
I'm still seeing this with the current TestFlight version.
@thisIsTheFoxe

**Comment by Jc-L** [comment]
Having the same error on IOS app connecting to a local Nextcloud using a self-signed certificate managed by `ha-proxy`. App complains very frequently (matter of seconds) that the certificate seems to have changed, which it didn't. Certification life is less than 365days, certification chain is provided, root CA added as a new trusted root CA, and everything runs fine on the Safari browser.
