### ISSUE TITLE
App should stop trying to login if login failed.

### ISSUE THREAD

**Issue by weiw11** [nextcloud/ios#1689]
### Steps to reproduce

1. Login to app
2. Change password on another device
3. Leave app alone
4. App continues trying to login even if credentials are incorrect.

### Expected behaviour

App should stop trying to login/connect if password is wrong more than a set amount of times, possibly 3?

### Actual behaviour

App keeps trying to login and continues to do so even after server has prevented login.

### Reasoning or why should it be changed/implemented?

If a password was changed remotely and one device is still logged in without updating it's credentials, it will limit access for everyone else. 

This has occurred on my network and I had no clue that it was going on and why I wasn't able to access nextcloud from time to time. I was only able to find this when I saw the prevented login for [time] seconds for incorrect login after logging in due to cookies being deleted.

### Environment data

**iOS version:** 14.7.1

**Nextcloud iOS app version:**  4.0.6.0

**Server operating system:** 21.0.4snap2

**Comment by marinofaggiana** [comment]
Hi, will be possible remove the active account
