### ISSUE TITLE
EXIF data view accessible from application?

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/ios#170]
Is it possible to see the EXIF information of the photos? 
Dropbox is using it and I think it will be very useful for photo enthusiasts (like me :) )

_Sample screenshots:_

![2017-04-09 10-27-09 1424](https://cloud.githubusercontent.com/assets/297968/24840763/56c732be-1d7c-11e7-9100-bbe7a5adb950.png)

![2017-04-09 10-26-56 1423](https://cloud.githubusercontent.com/assets/297968/24840830/bb188474-1d7d-11e7-9f4a-4b0ea8fb279c.png)

![2017-04-09 10-27-31 1427](https://cloud.githubusercontent.com/assets/297968/24840829/bb181eee-1d7d-11e7-9a66-1c927d322259.png)

![2017-04-09 10-27-13 1425](https://cloud.githubusercontent.com/assets/297968/24840767/750ab746-1d7c-11e7-89a5-b4e7a0b16280.png)

cc @marinofaggiana

**Comment by rakekniven** [comment]
That would be cool!
