### ISSUE TITLE
Interactive notifications

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#1702]
always show primary button first (left)
if more than 2 buttons -> show primary button, "three dots" for all other options

How to test:
in apps/notifications/lib/Notifier/AdminNotifications.php

find:
`
$notification->setIcon($this->urlGenerator->getAbsoluteURL($this->urlGenerator->imagePath('notifications', 'notifications-dark.svg')));
`

after add:		
```
$notification->addParsedAction($notification->createAction()->setParsedLabel('Label 1')->setLink('https://localhost', \OCP\Notification\IAction::TYPE_DELETE));
$notification->addParsedAction($notification->createAction()->setParsedLabel('Label 2')->setLink('https://localhost', \OCP\Notification\IAction::TYPE_GET));
$notification->addParsedAction($notification->createAction()->setParsedLabel('Label 3')->setLink('https://localhost', \OCP\Notification\IAction::TYPE_POST));
```

**Comment by marinofaggiana** [comment]
![Simulator Screen Shot - iPhone 13 - 2022-08-31 at 17 08 15](https://user-images.githubusercontent.com/8616947/187713378-916e2965-aa1f-4f4a-83c7-31e2d6ae22ac.png)
