### ISSUE TITLE
Can see/write comments from files

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/ios#171]
View and write comments for files, comment feature available in server edition. Would not it be better to use the same feature in the application?

_Sample screenshot from Dropbox iOS app:_

![2017-04-09 10-27-56 1428](https://cloud.githubusercontent.com/assets/297968/24840848/4b89dcd8-1d7e-11e7-87b0-607b5f5b2a68.png)
cc @marinofaggiana

**Comment by rakekniven** [comment]
Hey @emresaracoglu You like to comment on files from iOS app?
Just recap your issue because the word "furniture" bemused me.

**Comment by emresaracoglu** [comment]
@rakekniven I now notice the spelling mistake :) 
I'm talking about accessing file comments from the application

**Comment by melikyuksel** [comment]
This can now be done by pressing the 3 dots next to the file name, going to Details, and going to the Comments tab. Can make new comments and view existing ones. Can this be closed?
