### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#1715]
On click on each avatar let the user select one of those option:
- profile: opens (public profile) page in web browser
- mail: mailto link handled by OS
- talk: either native app if installed or opens in web browser

Server API: in https://github.com/nextcloud/files-clients/issues/1

**Comment by thisIsTheFoxe** [comment]
# 🚀 
<img src="https://media4.giphy.com/media/SVH9y2LQUVVCRcqD7o/200w.gif?cid=6889e3d5f280qjbz30t36edmh9tf8wtilu541zuwsycu3v2s&rid=200w.gif&ct=g" width="300"/>
