### ISSUE TITLE
Autoupload of files before update doesn't work

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#172]
* having some photos in the upload queue (from the auto uploader)
* install the latest beta from test flight
* expected: files are uploaded once I'm in wifi and open the app
* actual: files are never uploaded (I killed the app, I changed wifi, I disabled wifi and re-enabled)

@marinofaggiana

**Comment by rakekniven** [comment]
Any update on this?
Still open? Any changes code side?
Asking to adjust milestone correctly.

**Comment by MorrisJobke** [comment]
I didn't run into this again with the fixed version ... I think this specific item is fixed.
