### ISSUE TITLE
Upload via Share Menu Silently Overwrites Existing Files

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/ios#1737]
### Steps to reproduce

1. Click "Share" in another app and select Nextcloud in the Share Menu
2. Select a target folder where a file with the same name as the to-be-uploaded file already exists.
3. Click "Upload"

### Expected behaviour

Some warning or even error should be displayed to the user.

### Actual behaviour

The existing file is *silently* overwritten.
Furthermore, since the preview shows only folders and not files, there is currently no way for the user to know that a file will be overwritten.

### Screenshots

This is how Android handles it:

<img src=https://user-images.githubusercontent.com/33295590/140603601-52006d2a-8de4-4a66-80ea-f1a5e0fd1cc7.png width=40%> <img src=https://user-images.githubusercontent.com/33295590/140603602-36347564-dd24-4c71-819a-45d87f386336.png width=40%>

### Reasoning or why should it be changed/implemented?

Even though Nextcloud allows you to revert to previous versions of a file, this is a destructive action about which the user should be notified.

### Ideas how to implement it

Idea 1 ("Blocking error"):
- Proper conflict handling and explicitly force the user to choose between files (like Android)
- Cons: there are many cases where you do want to overwrite the old file. More work to implement, and we would need to think more about the exact UX flow.

Idea 2 ("Non-blocking warning"):
- Show a warning for those files that are affected. 
  I.e. when uploading multiple files and only 2 out of 4 are a conflict, you would show 2 warnings right next to these files.
- Pros: preserves current behaviour while also notifying the user without interrupting him/her. Much simpler to implement.

<img width="50%" alt="nextcloud-upload-conflict-ios-suggestion-C" src="https://user-images.githubusercontent.com/33295590/140604073-6f860b66-e931-4bdb-923b-ef73dd6e930f.png">

### Environment data

**iOS version:**  iPadOS 15.1

**Nextcloud iOS app version:**  4.0.6.0

**Comment by tvwerkhoven** [comment]
As a workaround, it should be possible to make a rename script [using workflow](https://github.com/nextcloud/workflow_script), however I haven't succeeded in doing this.

**Comment by Hukuma1** [comment]
Ran into this a while back. Glad someone reported it. If exporting from the Notes app it doesn't even give you the option to re-name it I don't believe. It'll just be `image.png`. I overwrote all the files and was thoroughly confused when I only had one file in my Nexcloud afterwards. 

Please at least do what Windows does and add a `(1)` etc to the name to differentiate among different files. If it's truly the same one (same name and filesize and perhaps even date/time) then present an overwrite dialogue. Otherwise it should save them all.
