### ISSUE TITLE
Not uploading all photos/videos in every sync 

### ISSUE THREAD

**Issue by manches** [nextcloud/ios#174]
Hi,

I am seeing that sometimes there are some photos that does not uploading to the cloud nor appear in the PHOTO tab. The photos exists and it is taken with the same app (ios cam) and the same way as usual.
IOS app version 2.16 (00012)
IOS version: 10.2.1
Nextcloud version: 11.0.2

This problem occured in previous versions and i just did a fresh instalation on the phone.
The last picture ended up with a 207 and did not upload to nextcloud. i don't see any logs on the nextcloud

xxxxxxxxx - lueas [21/Mar/2017:00:14:00 +0100] "PUT /nextcloud/remote.php/webdav/Photos/2017/03/2017-03-18%2017-20-58%206279.mp4 HTTP/1.1" 201 1515 "-" "Nextcloud/00012 CFNetwork/808.0.2 Darwin/16.0.0"
xxxxxxxxx - lueas [21/Mar/2017:00:14:02 +0100] "PUT /nextcloud/remote.php/webdav/Photos/2017/03/2017-03-20%2020-07-45%206293.jpg HTTP/1.1" 201 1681 "-" "Nextcloud/00012 CFNetwork/808.0.2 Darwin/16.0.0"
xxxxxxxxx - lueas [21/Mar/2017:00:14:04 +0100] "PUT /nextcloud/remote.php/webdav/Photos/2017/03/2017-03-20%2020-47-25%206294.jpg HTTP/1.1" 201 884 "-" "Nextcloud/00012 CFNetwork/808.0.2 Darwin/16.0.0"
xxxxxxxxx - lueas [21/Mar/2017:00:14:05 +0100] "PUT /nextcloud/remote.php/webdav/Photos/2017/03/2017-03-20%2020-51-38%206295.jpg HTTP/1.1" 201 884 "-" "Nextcloud/00012 CFNetwork/808.0.2 Darwin/16.0.0"
xxxxxxxxx - lueas [21/Mar/2017:00:14:34 +0100] "PROPFIND /nextcloud/remote.php/webdav/Photos/2017/03/2017-03-18%2000-40-01%206276.jpg HTTP/1.1" 207 2593 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.16"

Any ideas? did you report this problem?

**Comment by marinofaggiana** [comment]
@manches test with new version 2.17 now build 38

**Comment by manches** [comment]
Hi. 

 I am trying the new version these days and I found a couple of issues.  With the automatic upload  videos and photos,  I am seeing that the app is not uploading any videos.  Also I see that in a couple of photos it gives an error  " error, file not present,reload"  and the photo does have  exist ( one of them was a png from the whatsapp) and it does upload more photos until you close and open the app again.

**Comment by marinofaggiana** [comment]
under investigation

**Comment by enoch85** [comment]
> until you close and open the app again.

https://github.com/nextcloud/ios/issues/192

**Comment by manches** [comment]
For example, i have being on holidays a couple of weeks ago and i took 53 photos, 2 videos and the app only uploaded 52 photos leaving the other behind and never picking them up.

I have been using the new version (2.17) and for now it seems ok (i haven't tried a strees test yet...)

i will wait a little longer and then i will close the issue

**Comment by enoch85** [comment]
@manches Does your photos and videos upload even if the App is closed, or do you have to open it for the uploading to happen?

**Comment by manches** [comment]
i have the background upload turn off, so it uploads every time I open the app

**Comment by marinofaggiana** [comment]
@manches close ?

**Comment by enoch85** [comment]
This is what he means I think: https://github.com/nextcloud/ios/issues/215

**Comment by enoch85** [comment]
@manches This should be fixed in the latest version. Please reopen if not.
