### ISSUE TITLE
Create/access local links

### ISSUE THREAD

**Issue by cal940** [nextcloud/ios#175]
In Nextcloud 11  (webgui) you can show a local link to a file or folder (see screenshot). I would like to see this feature in the app.

![](http://i.imgur.com/kDpHv4F.jpg)

**Comment by marinofaggiana** [comment]
iOS : select file or folder, share, Share link ON, [Send link to ...],  Copy

done.

**Comment by cal940** [comment]
I don't want to share a public link.

Benefits of local links:

- only one login instead of many passwords
- only users with the right permission have access
- useful for homepage admins (like me)

**Comment by newalias** [comment]
Hello, I would really appropreate if this feature will get in the app. Cause at the moment the missing prevent me to change to Nextcloud on ios side. BTW. the link to the corresponding github issue of the owncloud ios client. https://github.com/owncloud/ios/issues/896

Regards
newalias
