### ISSUE TITLE
Add capability send_password_by_mail

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#1754]
https://github.com/nextcloud/server/pull/29332/files#diff-2f474cd876a5cee804e810c6b97cba8d45cc43afdce5ba7d17e037de4a150f12R68

adds a new capability send_password_by_mail for >= NC23:

show this capability only if it exists :)

**Comment by thisIsTheFoxe** [comment]
After checking again there already exists a method to [`getCapabilities`](https://github.com/nextcloud/ios-communication-library/blob/06d78653b5f2067f644eceb3e7541290ca1fce82/NCCommunication/NCCommunication%2BAPI.swift#L425) from the API. 
So, `send_password_by_mail` can be accessed using this line:
```
NCManageDatabase.shared.getCapabilitiesServerBool(account: <#User account#>, elements: ["ocs","data","capabilities","files_sharing","sharebymail","send_password_by_mail"], exists: false)
```
Or using #1753:
```
NCManageDatabase.shared.getCapabilitiesServerBool(account: <#User account#>, elements: NCElementsJSON.shared.capabilitiesFileSharingSendPasswordMail, exists: false)
```

**Comment by marinofaggiana** [comment]
@tobiasKaminsky where is used this capability ? written like this, without the context, is useless.
