### ISSUE TITLE
End2End Encryption + Media Preview

### ISSUE THREAD

**Issue by JimLoose** [nextcloud/ios#1760]
### Steps to reproduce

1. save an image in an end2end encrypted folder
2. show the image in the app
3. go to the media preview folder and see yourself

### Expected behaviour

When using the media tab in the app i see a preview of images in my end to end encrypted folder. I expect them to be hidden or visible (you guys decide)

### Actual behaviour

Unfortunately after a couple second seeing these images in the media tab as a preview, they get hidden there.

### Environment data

**iOS version:** e.g. iOS 15

**Nextcloud iOS app version:** 4.0.6.0

**Server operating system:**

**Web server:** Apache

**Nextcloud version:** 22.2.3

**Comment by eibex** [comment]
Can reproduce on iOS 15.5 with iPhone and iPad on Nextcloud 4.4.

**Comment by eibex** [comment]
Seems fixed in 4.4.1
