### ISSUE TITLE
The option for saving a photo to the album is visible for documents

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1769]
Precondition: A document is already created in the app

1. Open the app
2. Tap on the select option
3. Select a document
4. Tap on the button with three dots

Expected Result

The option for saving into the photo album shouldn't be available for documents.

Actual Result

The option for saving into the photo album is available for documents.

**Comment by thisIsTheFoxe** [comment]
Will be fixed in v4.3.0 by #1894
