### ISSUE TITLE
Select all from All files get selected with the count of '0'

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1771]
Steps to reproduce:
Open the app and let display the dashboard
Click on 'Select' from header of the app
Again click on round 3-dot magenta filled icon from top
A dialog box gets displayed below of the dashboard app, their 'Select all' option.
see the header name- 'Selected : 0/39' and all folders and files get selected upon.

Actual result:
We can see 'Selected : 0/39' even though all folders and files already has selected with all radio check boxes are in green.

Expected result: 
When we select all then on header should get display 'Selected : 39/39' (depending on number of files and folders have on out off)

Note: Here in iOS don't have 'Deselect all' option, once when user Select all

**Comment by thisIsTheFoxe** [comment]
Thanks for your report. I believe this has already been addressed in #1763
If the issue persists feel free to reopen this.

About the note: Canceling and re-selecting takes the same amount of taps as a "Deselect all" would (2). I can see how it might be nice to have, but I don't think it's a necessity as of now.
