### ISSUE TITLE
"Open in" button without function

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1774]
Frequency
Every Time

Actions Performed
1. Open app and log in
2. Upload any file 
3. Tap on Files tab
4. Open file
5. Tap on 3 dot menu and select View in folder
6. On any file tap on 3 dot menu and Select "Open in"

Expected Result
When pressed, a button will appear with the choice of the app to open the file

Actual Result
Nothing happens after pressing on "Open in" button

**Comment by melyux** [comment]
I noticed this too. Noticed it when my shortcuts that open things in Nextcloud stopped working.

**Comment by marinofaggiana** [comment]
Fixed
