### ISSUE TITLE
Support for iOS 7

### ISSUE THREAD

**Issue by caco3** [nextcloud/ios#178]
I still know several users who have an iPhone 4 and are happy with it.
Is there a reason for the requirement of >= iOS 8 for the Nextcloud client?
Is the limitation based on a valid reason or a mistake or simply because you did not test it with iOS 7?

**Comment by rakekniven** [comment]
Supporting older devices takes much effort. Open source communities do often not have the resources to support a wide range of OS versions.

Apple is pushing developers to 64-bit world. 32-bit is dead if you listen to Apple.
Builds for older iOS version will not be supported in upcoming Xcode releases.
Older iOS releases will not getting any security fixes and 3rd party toolkits do not support older iOS versions as well.
