### ISSUE TITLE
Trust prompt for a valid TLS certificate chain

### ISSUE THREAD

**Issue by piru** [nextcloud/ios#1784]
### Steps to reproduce

1. Configure client to use server using Lets Encrypt certificate
2. Use the client

### Expected behaviour

Client should connect to the server without certificate trust prompt.

### Actual behaviour

Client prompts for "Do you want to connect to the server anyway? Yes / No / Certificate Server details"

Note that all other clients (such as browsers) can connect to the server okay. Also, the certificate chain is complete (it is not missing any intermediate certs).

```
Certificate chain
 0 s:CN = sintonen.fi
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
```

### Screenshots
![signal-ios-cert-rror](https://user-images.githubusercontent.com/1134152/144211362-d890f754-c219-4997-b2ce-d2a38bf85cd4.jpg)

### Environment data

**iOS version:** iOS 15.1

**Nextcloud iOS app version:** 4.1.0

**Server operating system:** Debian 11.1 - 5.10.0-8-amd64 #1 SMP Debian 5.10.46-5 (2021-09-23) x86_64 GNU/Linux

**Web server:** Apache 2.4.51-1~deb11u1

**Database:** mariadb-server-10.5 1:10.5.12-0+deb11u1

**PHP version:** php-7.4  7.4.25-1+deb11u

**Nextcloud version:** 22.2.3

**Comment by marinofaggiana** [comment]
Hi @piru do you have a test account for me ? we knows this issue but don't  understand why happens ..
You can send the credential to ios at nextcloud com

**Comment by piru** [comment]
@marinofaggiana 
Sure, account created and creds sent. Let me know when the account is no longer needed.

**Comment by marinofaggiana** [comment]
Tested, nothing issue registered, all works fine.

**Comment by blaine07** [comment]
I am probably not smart enough to provide useful feedback with this issue but as of recently it's affecting my device, too. Per above, I did try logging out of user on current phone and logging back in; still prompts quite often. Kind of annoying.

**Comment by blaine07** [comment]
Wanted to add, certs are fine. Have a Android device logged into same NC instance and have NO certificate issues on Android. Something specific to iOS app; whatever it is that's wrong.

**Comment by marinofaggiana** [comment]
You can try with the 4.2.0 available on TestFlight if solved

**Comment by marinofaggiana** [comment]
Duplicate https://github.com/nextcloud/ios/issues/1682
