### ISSUE TITLE
Favorite folders appear empty

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#179]
Currently when you have a folder favorited but nothing inside of it, opening that folder in the favorites view will show no contents at all.

Instead, Favorited folders should act as a kind of bookmark, simply showing all of their contents on opening.

@marinofaggiana would be very good to fix for the release as this is quite confusing. cc @nextcloud/ios

**Comment by marinofaggiana** [comment]
Hi @jancborchardt ... i don't understand .. but if inside the content is nothing, how I have to see ?

**Comment by jancborchardt** [comment]
Ahaa, it seems that this occurs only for folders which I haven’t opened yet through the normal »Files« section.

So try this:
1. Create a new folder on the server, put some files in it
2. Favorite it on the server
3. On your iPhone go to the Favorites section and open the folder → it will be empty
4. Now go to the Files section and open the folder, it will load
5. Repeat step 3 → the folder will show the files

**Comment by marinofaggiana** [comment]
ok. Thanks

**Comment by marinofaggiana** [comment]
The procedure it's correct, the sync favorite occurs  when the app is reactivate.

For new issue re-open.

**Comment by jancborchardt** [comment]
Sorry, don't fully understand it - was the issue fixed? :)

**Comment by marinofaggiana** [comment]
@jancborchardt  try this:

- Create a new folder on the server, put some files in it
- Favorite it on the server
- Open Nextcloud iOS (if it's already open) close (non active) and reopen
