### ISSUE TITLE
Nextcloud 4.1.0 IpadOS issue with all servers

### ISSUE THREAD

**Issue by dwprod38** [nextcloud/ios#1791]
### Steps to reproduce

1. Installation Nextcloud iPadOS 4.1.0 on iPad Pro M1
2. logging to my private Nextcloud server installed on RaspberryPi --> host "https://dwpcloud.xxx.xxx" and access button is displayed
3. After button clicked: welcome page works with user/password invitation for logging

### Expected behaviour
 
After user/password validation in Nextcloud iPadOS app: a dashboard is displayed correctly

### Actual behaviour

After user/password validation in Nextcloud iPadOS app message display as below:
"**Internal Server Error**
_This server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log._"

### Remarks

I've installed **Nextcloud iOS 4.1.0 in iphone12pro** (iOS15.1.1) : everything works fine with NextcloudPi/RaspberryPi !
I've tried to connect to Nextcloud server with **Safari installed in iPadPro M1** (same tablet used for Nextcloud iPadOS 4.1.0) :  everything works fine with NextcloudPi/RaspberryPi !

I've tested with other Nextcloud server (Server company name "cloud.esrf.fr") : I have same "Internal Server Error" issue after user/password logging with Nextcloud iPadOS app but works fine with **Safari/iPad Pro M1 and Nextcloud iOS app/iPhone12pro** !

Uninstall of Nextcloud iPadOS app, clean restart iPadPro and download/install Nextcloud iPadOS app : same behaviour described above nothing changed with both servers.

### Reasoning or why should it be changed/implemented?

How explain on same  iPadPro M1 tablet that Nextcloud running on **Safari** works fine but not with **Nextcloud iPadOS** app on different Nextcloud servers (private and professional) ? This issue didn't exist with previous Nextcloud iPadOS version 4.0.6 ...

### Environment data

**iOS version:**  iOS 15.1

**Nextcloud app:**  iPadOS 4.1.0

**Server operating system:** linux 5.10.63-v8 aarch64 (raspberry)

**Web server:** Apache

**PHP version:** 7.3.31

**Database:**  MariaDB

**Nextcloud version:** 22.2.2

**Comment by dwprod38** [comment]
Edition with precise information done

**Comment by dwprod38** [comment]
Full installation Nextcloud Server to version 22.2.2 on Raspberry Pi 4 : Nothing changed as shown below

- login to Raspberry Pi 4 Nextcloud Server with **Safari** on iPhone12pro : OK
- login to Raspberry Pi 4 Nextcloud Server with **iOS Nextcloud app** on iPhone12pro : OK
- login to Raspberry Pi 4 Nextcloud Server with **Safari** on Macbook Pro 17" : OK
- login to Raspberry Pi 4 Nextcloud Server with **Safari** on iPad Pro M1 : OK
- login to Raspberry Pi 4 Nextcloud Server with **iPadOS Nextcloud app** on iPad Pro M1 : NOT WORKING
- login to other Nextcloud Server with **Safari** on iPad Pro M1 : OK
- login to other Nextcloud Server with **iPadOS Nextcloud app** on iPad Pro M1 : NOT WORKING

Uninstall of Nextcloud iPadOS app, clean restart iPadPro and download/install Nextcloud iPadOS app : same behaviour described above.

**Comment by dwprod38** [comment]
Hello @marinofaggiana please find the result of login error 👍 

_{"reqId":"Ya-XSFODlrg3U1c62u3QsAAASxg","level":3,"time":"2021-12-07T21:51:05+00:00","remoteAddr":"2.7.152.240","user":"ncp","app":"index","method":"POST","url":"/index.php/login","message":"An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xE9phane...' for column `nextcloud`.`oc_authtoken`.`name` at row 1","userAgent":"Stéphane's iPad (iOS Files)","version":"22.2.2.0","exception":{"Exception":"OC\\DB\\Exceptions\\DbalException","Message":"An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xE9phane...' for column `nextcloud`.`oc_authtoken`.`name` at row 1","Code":1366,"Trace":_

**_Incorrect string value: '\\xE9phane...'_** give me a clue about special character “é” conflict. I’ve tested Nextcloud app again with my ipad pro M1 by renaming “Stéphane’s iPad” by “Stephane’s iPad” in « Setting/About/Name » : login to server works !

And one more thing: I can create this common issue with my iPhone12pro  by renaming “Stef’s iPhone” by “Stéf’s iPhone” in « Setting/About/Name » : login to server fail ! 

So I concluded something have been changed during Nextcloud iOS 4.1.0 compilation since release 4.0.6 (iso-8859-1 character not included in app that explain why safari app have iso-8859-1  compliant and works fine with nextcloud server login access)

perhaps it should help you

**Comment by t-markmann** [comment]
Related?
https://github.com/nextcloud/ios/issues/1803
https://github.com/nextcloud/ios/issues/1800

**Comment by dwprod38** [comment]
> Related?
> 
> https://github.com/nextcloud/ios/issues/1803
> 
> https://github.com/nextcloud/ios/issues/1800

Perhaps 🙂

**Comment by bh11** [comment]
Same issue here (Nextcloud 22.2.3/mariadb), iOS client 4.1.0.17.

Changing the device name while logging in resolves the issue. (Once logged in, the device name can be changed back.)

Btw., I don't see why the device name should be stored in the oc_authtoken database table at all.

**Comment by thisIsTheFoxe** [comment]
@bh11 thanks for your report.

> Btw., I don't see why the device name should be stored in the oc_authtoken database table at all.

I'm not a 100% on this, but I think the goal was to make it easier to identify which devices have access to your account and consequently spot devices that shouldn't have, which is a good thing, imo. 
If I understand correctly the device name should then be displayed at: *cloud.tld/settings/user/security*

But, as I saw there's more going on , since the server also [parses the user agent](https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/lib/public/IRequest.php#L83) to check if it comes from the app. So, I think the best thing *for now* is to just use the default Nextcloud iOS agent.

**Comment by Holt59** [comment]
Same issue here, this is very annoying because the App is 100% useless. Do you think there is a way to fix this on the server side? Because the release frequency of the iOS seems pretty slow.

**Comment by marinofaggiana** [comment]
Will be correct with the next version in December, for now you can modify the name of you device without "special" chars.

**Comment by Holt59** [comment]
> Will be correct with the next version in December, for now you can modify the name of your device without "special" chars.

Thanks, I thought this was linked to the iCloud name, which I do not want to change, but if it's only the device name I can do with it.

**Comment by marinofaggiana** [comment]
ohh, true,  sorry, but soon a new fix.

**Comment by marinofaggiana** [comment]
Fix will be available on TestFlight (V 4.0.2 build 2)
