### ISSUE TITLE
More / Trash - Sort options are not updated correctly

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1798]
Frequency
Every Time

Actions Performed
1. Open the app
2. Click on more, go to trash section
3. click on sorted by name (from A to Z)
4. select "sort by name (from Z to A)
5. open again sort options and check name "sort by name (from Z to A)
6. try the other sort options "sort by newest" / "sort by oldest" and "Sort by smallest" / "sort by largest"

Expected Result
Sort options works fine and names changes after every selection.

Actual Result
Sort options works fine. But names of sort options does not changes.
Sort options are shown:
Sort by name (Z to A"
sort by oldest
sort by largest
They changes only when try another sort option.

**Comment by thisIsTheFoxe** [comment]
Fixed in e9b97f86740b79824ecd2c89c2e725b5c6a3a542
