### ISSUE TITLE
Share a link without password protection

### ISSUE THREAD

**Issue by togglecode** [nextcloud/ios#18]
Currently it is only possible to share a link with password, this is really annoying since everytime I want to send a link to a friend I have to also send them a 8 charachter long password with it. Is it possible to make this also available without password protection?

**Comment by jancborchardt** [comment]
@marinofaggiana is it possible to remove this quickly? Sharing is a pretty essential function and should be as seamless as possible.

cc @nextcloud/ios

**Comment by cal940** [comment]
I think you have to change that in the web application. There is a setting for that.

Disable the following setting:

Admin -> Sharing -> Enforce password protection

**Comment by jancborchardt** [comment]
cc @schiessle @nextcloud/sharing since this is sharing-related and maybe to the server part of it.

**Comment by togglecode** [comment]
Actually it's working on nextcloud 11 now that I tested. I think it was indeed because of the Web application settings. (Although last time I tried it on nextcloud demo server)
