### ISSUE TITLE
Grey background behind filetype icons

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#180]
Just a small detail, but it would be good to remove the grey-ish background behind the filetype icons to make the row completely white.

cc @marinofaggiana or anyone of @nextcloud/ios who wants to dive into development :)

**Comment by marinofaggiana** [comment]
done.

**Comment by rakekniven** [comment]
Is that included in v2.17 and it's golden master?

**Comment by marinofaggiana** [comment]
No, @rakekniven but after 2.17 I want make faster updates, this version is too big and there will be many bugs.

**Comment by rakekniven** [comment]
Just created next milestone. Named it v2.18. We can change it if we need.
