### ISSUE TITLE
Internal link (sharing) can no longer be copied (App crashes afterwards)

### ISSUE THREAD

**Issue by Gianni154** [nextcloud/ios#1809]
### Steps to reproduce

1. Open the Nextcloud iOS app
2. Select a file and click on the Sharing icon
3. In the tab "Sharing" click on Internal link (copy to clipboard symbol)

### Expected behaviour

App should not crash. The internal link is copied in the clipboard (As in the web, a green tick is visible after copying.)

### Actual behaviour

Internal link of a file cannot be copied in the clipboard. The app crashes.

### Screenshots

no screenshots

### Logs

no logs

### Environment data

**iOS version:** iOS 15.1

**Nextcloud iOS app version:** 4.1.0.17

**Server operating system:**

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** 20.0.14

**Comment by marinofaggiana** [comment]
Hi @Gianni154 thanks for your report, can give me more detail ?
