### ISSUE TITLE
Testflight - Crash after update with NextCloud V 2.14.00040

### ISSUE THREAD

**Issue by manches** [nextcloud/ios#183]
Hi,
After updating to the version 2.17.00040, it crashes in a couple of seconds after opening. There are 5 photos pending to upload
Here is the IPS logs of the crash
https://pastebin.com/Fzn5Pga8

**Comment by marinofaggiana** [comment]
Hi @manches nothing good information on Logs ...  now work ?

**Comment by manches** [comment]
No, nothing. This crash was a couple of minutes ago.
All was working before with the other versions

**Comment by marinofaggiana** [comment]
clear cache .. possible ?

**Comment by manches** [comment]
Solved this that. 
Now the problem is that the photos that was pending before, now it does not upload. It only uploads new ones after cleaning the cache

**Comment by marinofaggiana** [comment]
ok. close this . Now the 2.17 version in on App Store
