### ISSUE TITLE
App crashes when entering folder with txt-file(s) containing special ASCII-characters

### ISSUE THREAD

**Issue by markus-lorenz** [nextcloud/ios#1831]
### Steps to reproduce

1. save a txt-file (UTF-8) in a folder with a ASCII-character like the one attached (ALT-191,192,193,...) > [ascii-examples.zip](https://github.com/nextcloud/ios/files/7757489/ascii-examples.zip)
2. open folder containing file with iOS-client

### Expected behaviour

1. folder should be listed
2. file should be accessable / "pre-rendered"

### Actual behaviour

app crashes completely.

### Screenshots

-

### Logs

-

### Reasoning or why should it be changed/implemented?

-

### Environment data

**iOS version:** iOS 15.1.1

**Nextcloud iOS app version:** 4.1.10.17

**Server operating system:** Ubuntu 20.04.3 LTS Server

**Web server:** Apache, nginx

**Database:** MariaDB 10.5.13

**PHP version:**  7.4.26

**Nextcloud version:** 22.2.3

**Comment by tux1337** [comment]
Same behavior on
iOS 15.2 
Nextcloud 23.0.0

**Comment by barrydegraaff** [comment]
I am seeing lots of app crashes since the update to Nextcloud IOS app version 4.2.0.5 on IOS 15.2 and Nextcloud 22.2.2. The App is the only thing that was updated since I see the app crashes

**Comment by tux1337** [comment]
I found a workaround, disabling previews in config.php fixed that the apps crashes. 

config.php:
`  'enable_previews' => false,`

So it seems that it has something todo with the previews of txt / md files.

**Comment by barrydegraaff** [comment]
In some folders it indeed seems to no longer crash, but it still crashes 
for other folders, so it is not a workaround for me.

**Comment by thisIsTheFoxe** [comment]
@markus-lorenz thanks for your report.
I sadly was unable to reproduce this by just adding the linked folder into the root directory of my Nextcloud. Can you confirm that this is the correct setup? My file structure looks something like:
> /
> > ascii-examples/
> > > 1.txt
> > > > ┌

etc. where the last one is the content of the file _1.txt_.
Also, if possible please confirm that the same happens with the current app version (4.2.0) and if turning off the previews helps (as suggested @tux1337).

**Comment by barrydegraaff** [comment]
I have a folder:

      [root]/Engineering/

In said folder I have 2 files that crash the app, the file names are: "arduino mega2560 pro fusebit anti bootloader avrdude.txt" and "readme avrdude.txt"

If I remove those files from the folder, the app no longer crashes. The setting `enable_previews` does not seem to matter for me. App version 4.2.0.5, Nextcloud server 22.2.3 IOS version: 15.2.

**Comment by barrydegraaff** [comment]
When I create an empty file `test.md` in a folder it works, if I type `test` in that file and save on the web browser, then the IOS App crashes... so maybe something in the encoding of the file contents.

**Comment by barrydegraaff** [comment]
here is a video where I create a text file from the IOS app, after saving, it's done, app crashes and cannot be reopened.


https://user-images.githubusercontent.com/4353213/147948969-23c45414-5b28-43a2-95b6-016f9efa88bf.mp4

**Comment by thisIsTheFoxe** [comment]
@barrydegraaff There are multiple builds available in TestFlight. Please check the TestFlight.app > Nextcloud > Previous Bilds

**Comment by barrydegraaff** [comment]
@thisIsTheFoxe thanks, 4.1.0 also does not work. I started seeing this issue when I upgraded to IOS 15.2....

**Comment by tux1337** [comment]
> here is a video where I create a text file from the IOS app, after saving, it's done, app crashes and cannot be reopened.

i did the same on my instance with same results, nextcloud 23.0.0, nextcloud app 4.2.0.5 and iPadOS 15.2 

when I disable the previews this works. 
could it be that the crashing folders has already rendered previews in it, and that’s the reason why it crashes for you in some folder and it is working in other. 
so maybe clearing all previews is an additional measure to try out. 

btw remove nextcloud app and reinstall them does not change anything. 

For me it is only “fixed” with disabled previews.

**Comment by barrydegraaff** [comment]
With previews disabled, when I create a file with random name on the IOS 
app, it still crashes upon saving.

I am not sure if there is a way to selectively delete the preview cache 
on the server, I already cleaned the app cache, that does not do a thing.

Destroying all cache on the server side will impact the performance too 
much, so can't do that, also disabling previews is not a solution for 
me. Will try an reproduce this on a test instance later.

**Comment by markus-lorenz** [comment]
@thisIsTheFoxe 
Can confirm /ascii-examples/1.txt for example is good to reproduce.
Can confirm, that the app crashes with 4.2.0.5 on my iPhone.
Can confirm, that disabling preview (as suggested @tux1337) helps - no more app-crash, but only for new files.
Files that exist "with a preview" in the app still let the app crash. See my testing-results down below (step 17 / 18).

Steps I did:
(all creation / copy of folders / files is done with a windows 10-pc with installed nextcloud-client 3.3.6)

1. create folder "/ascii-examples"
2. copy 1.txt from my examples to "/ascii-examples"
3. check on iPhone: preview processes ok, can open and read file successfully
4. quit app on iPhone (back to home)
5. copy the rest of my examples 2-7.txt to "/ascii-examples"
6. check on iPhone: app crashes
----------
7. create folder "/ascii-examples2"
8. copy 1.txt from my examples to "/ascii-examples2"
9. check on iPhone: app crashes
----------
10. config.php: 'enable_previews' => false & sudo service php7.4-fpm restart
----------
11. create folder "/ascii-examples3"
12. copy 1.txt from my examples to "/ascii-examples3"
13. check on iPhone: preview not processed as expected, can open and read file successfully
14. quit app on iPhone (back to home)
15. copy the rest of my examples 2-7.txt to "/ascii-examples3"
16. check on iPhone: preview not processed as expected, can open and read all files successfully
----------
17. check on iPhone folder "/ascii-examples"
> app still crashes
18. check on iPhone folder "/ascii-examples2"
> app still crashes

**Comment by barrydegraaff** [comment]
In the meantime I am using this app as a work-around it is a kinda 
Spartan WebDAV app, but search works and I can access my files without 
having to re-authenticate in Safari twice a day.

https://apps.apple.com/nl/app/webdav-nav/id412341302

Hope the Nextcloud App is back soon!

**Comment by thisIsTheFoxe** [comment]
@markus-lorenz Thanks for the details.
Are you still sure this is related to the special ASCII examples as it says in the title? Because as you describe it it might be related to https://github.com/nextcloud/ios-communication-library/pull/107

Sadly, I'm still unable to reproduce this for any Markdown or Text files using Nextcloud 23.
However, I originally noticed the app crashing when loading compressed `png` preview images of Open Document files.

If you believe this issue is related to the preview images, could you please provide the images as the server provides them? Using the following url-format (you need to be logged or use an Authentication header):

```
https://cloud.example.com/index.php/core/preview.png?file=ascii-examples/1.txt&x=1024&y=1024&a=1&mode=cover
```

[Here](https://user-images.githubusercontent.com/18512366/148219794-cbef7ebb-3f63-411d-b93c-4cc7a9484231.png) is my preview of _1.txt._

**Comment by barrydegraaff** [comment]
confirm fixed in latest testflight release 4.2.1

**Comment by markus-lorenz** [comment]
@thisIsTheFoxe 
Sorry for the delay.
Here are my preview-images as you described to get them:
[1](https://user-images.githubusercontent.com/91191843/150543684-b2bbf9ec-1383-4e8c-b124-167d40713acb.png)
[2](https://user-images.githubusercontent.com/91191843/150543683-b82560a8-91e4-47a4-9f99-432fdd306aef.png)
[3](https://user-images.githubusercontent.com/91191843/150543681-cf090200-2007-4e20-9fc5-34328bacd5a7.png)
[4](https://user-images.githubusercontent.com/91191843/150543677-911623d8-db90-40de-87c6-ffd36821df73.png)
[5](https://user-images.githubusercontent.com/91191843/150543673-95de2c67-bb63-449c-abd7-dc7dd2b270ee.png)
[6](https://user-images.githubusercontent.com/91191843/150543688-2e626564-779b-46be-9279-7dea1dde8000.png)
[7](https://user-images.githubusercontent.com/91191843/150543686-3a5fe4f9-5306-4b9a-815f-066680a182b3.png)

Sadly I do not understand, what nextcloud/ios-communication-library#107 is 100% about.
That´s why I do not want to say a "yes" or "no" and a "maybe" will not help here,...
I´m sorry :-(

**Comment by thisIsTheFoxe** [comment]
No worries, thanks @markus-lorenz
And yes, you can see these images are **tiny** somewhere ~600 Bytes (even tho they are 1024x768 px), note how the example I provided is ~7KB. So we assume that we have way more data available and when we try to access data that technically doesn't exits the app crashes (as it should in such a case).
I'm not 100% sure why your preview images are compressed (which is good in general, I guess) or why it crashed for some users and not for others. But the PR should've fixed it.

Please feel free to try the [TestFlight](https://github.com/nextcloud/ios#testflight) version to verify that it's fixed, before the bugfix becomes available as an App Store update.

**Comment by tux1337** [comment]
I can confirm that the current TestFlight version fix the issue for me. 
When do we expect that the version will go to production/App Store?

**Comment by markus-lorenz** [comment]
I can also confirm that the current TestFlight version fix the issue described here.
I can open the folder, the previews get rendered and I can edit the files (ascii-examples).
