### ISSUE TITLE
Auto upload of photos silently fails if file with same name already exists, silent data loss

### ISSUE THREAD

**Issue by eharris** [nextcloud/ios#1835]
### Steps to reproduce

1. Take lots of photos
2. Setup auto-upload of camera roll, use "Maintain original filename"
3. Take lots more photos, enough that the IMG_NNNN.jpg (or .heic) number wraps
4. New photos that conflict with already uploaded photos with the same name are silently lost (not uploaded) 

### Expected behaviour

At a minimum, as far as the auto-upload feature, I would expect that a name conflict would still get uploaded with an additional suffix tacked on to the filename that avoids the conflict (e.g. `IMG_3124.jpg` might become `IMG_3124 1.jpg`)
A more advanced method might be to first check if the already uploaded file is identical (byte for byte compare) with the uploaded file, and if so, skip uploading.  If not identical, add suffix to filename to avoid conflict and upload.

As far as a general issue, I would expect any upload conflict of any type at any time to BOTH generate a notification of the problem with enough details to correct it, and an easy ability to either re-queue failed upload(s) to the same or an alternate destination, or with ability to choose that an alternate suffix should be added to avoid conflict.

### Actual behaviour

Photos that have the same name as an already existing file in the destination are silently skipped, resulting in silent data loss.

### Additional Notes

The iPhone appears to be able to store multiple photos in the camera roll at the same time with the same IMG_NNNN.xxx name.  This means that even if no photos are ever deleted from the phone, name conflicts and data loss will still occur.  It seems likely that the iPhone developers made this possible specifically to avoid name conflict/uniqueness problems.

### Environment data

**iOS version:** iOS 14.8.1

**Nextcloud iOS app version:** Nextcloud Liquid 4.2.0.5

**Server operating system:** Debian Linux, Buster

**Web server:** Apache

**Database:** MariaDB 10.3

**PHP version:** PHP 7.3

**Comment by eharris** [comment]
It should be noted that this problem can also be caused by common circumstances other than just rollover of the iphone image counter used in the filename.  Conflicts can occur due to photos saved to the camera roll from other apps which may have the same name, including Airdrop photos received from another iOS device (which has its own counter that can easily cause name conflicts with existing photos).  iOS seems to be able to store and handle multiple files with the same "name" without causing problems.

**Comment by Popcorncandy09** [comment]
I also have this issue, i found that out today and had to painstakingly rename the conflicts one by one.

**Comment by eharris** [comment]
I can't believe that there doesn't seem to be any interest in an issue that can result in massive (and silent) data loss, since the conflicts/failures are silent (no notification) and any camera roll spanning more than a few months is quite likely to have name conflicts.

**Comment by eraser2021999** [comment]
As a workaround I would suggest to activate the "Use subfolders" option, so each photo will be uploaded in a structure folder structure like Year/Month. However, this won't fix the issue if the photo is from another source (e.g. AirDrop) with the same name as an existing one, but I think it is less likely to happen.

**Comment by eharris** [comment]
The subfolders option does help in reducing the name conflicts, but the chance of name collisions still exists, especially for edited photos where the changed image may be saved back to the camera roll with the same name.

**Comment by adrhc** [comment]
additional insights are presented at [#2392](https://github.com/nextcloud/ios/issues/2392) though I'm not sure they are the same issue
