### ISSUE TITLE
Account is automatically logged out if app is closed

### ISSUE THREAD

**Issue by CircuitC** [nextcloud/ios#1837]
### Steps to reproduce

1. Log into app
2. Use app as usual (not necessary)
3. Close app (by swiping it away, after double pressing home button or swiping up on iPhone X+)
4. Open app again

### Expected behaviour

Like in iOS Safari, the app should not automatically log out after it's been closed. 
There should be an option in the app's settings to control if an when the logged in account is automatically logged out, such as if the app is closed or if it's been inactive for a set amount of time.

### Actual behaviour

If the app closes (by swiped away from recently opened apps), the account that's logged in is automatically logged out.

This is a screen recording (don't mind the glitch artifact of the video displayed at about 35 seconds):

https://user-images.githubusercontent.com/67488680/147992469-f68645e8-e955-4593-98ed-3bf4a8d0e568.mp4

### Reasoning or why should it be changed/implemented?
It can be annoying to have to repeatedly log into the app.

### Environment data

**iOS version:**14.8.1

**Nextcloud iOS app version:** 4.2.0

**Server operating system:** DietPi

**Web server:** Apache, nginx

**Database:**

**PHP version:**

**Nextcloud version:** 23.0.0

**Comment by AInteriorB** [comment]
Cannot confirm this behaviour. Account(s) are still logged-in even if you close the app from background.

**Comment by CircuitC** [comment]
Interesting, while you exit the app (but don't close it from background) does it display the NC logo instead of the files you were viewing?

Side note: Does the app look like the images on the App store's page, mine looks like a resized version of the desktop browser client.
![image](https://user-images.githubusercontent.com/67488680/147888822-3d9317df-8862-439f-b61b-5f382f11c1c6.png)

**Comment by CircuitC** [comment]
I've added a screen recording to my original issue.

Side note: why does the app show a different UI before the log in compared to after the log in, the one before looks like the one displayed in the app's screenshots on the App store, while the one after is basically a resized version of what's in the web browser?

**Comment by CircuitC** [comment]
The issue seems to be fixed after deleting and re-downloading the app.
I probably messed up when setting the app for the first time (but somehow have been able to update and use it since then), which caused the app to default to the browser layout causing the repeated log in prompts.
