### ISSUE TITLE
Check if there are pending photos to upload after a crash or a button to scan

### ISSUE THREAD

**Issue by manches** [nextcloud/ios#184]
Hi,

After the testflight 2.17.00040, I had to clean the cache to solve a issue that crashes the app. 
It could be a good idea to check if there are pending photos to upload because after crashing, these photos are ignored and only the new ones are uploaded.
Or a button to force a scan of pending photos.

**Comment by marinofaggiana** [comment]
No, the true issue is : why crash after update ? ... on my TestFlight no Crash found from testing ... 😡

**Comment by manches** [comment]
I have checked on my girlfriend version and after updating to the new version it crashs in seconds (2 seconds) and there is no time to clean the cache

**Comment by marinofaggiana** [comment]
Without a log this is a mystery ... sorry.

**Comment by manches** [comment]
Hi, sorry about the delay. On my girlfriend's phone there is no crash log (very strange...)
The only way i saw that the app didn't crash was to put the phone in airplane mode and when i switch off the airplane mode, tried to clean the cache and that didn't work because the app crash before it finishes cleaning. 
At the end i had to delete the account on the app and that was the only way (i didn't try to delete and install the app again)
So i can not help with anything else... :(

**Comment by marinofaggiana** [comment]
@manches install the last 2.17.1

**Comment by enoch85** [comment]
Closing in favor of https://github.com/nextcloud/ios/issues/306 which should be fixed.
