### ISSUE TITLE
Build failed OpenSSL - mb air m1

### ISSUE THREAD

**Issue by satiromarra** [nextcloud/ios#1841]
### Steps to reproduce

1.- git clone
2.- carthage update --use-xcframeworks --platform iOS --cache-builds 
3.- build project (cmd + b)

### Expected behaviour

Build success

### Actual behaviour

Build failed

Showing Recent Messages
Could not find or use auto-linked framework 'OpenSSL'

### Screenshots

<img width="334" alt="image" src="https://user-images.githubusercontent.com/1863162/147695821-8ee0719f-fd22-4871-b0a3-6cff65d861a1.png">

### Environment data

**iOS version:** e.g. iOS 15.2

**Nextcloud iOS app version:** 4.2.0 (5)

**Server operating system:** macOS Monterey
 MB Air M1

**Comment by thisIsTheFoxe** [comment]
Hi, this is a known issue, compare: https://github.com/krzyzanowskim/OpenSSL/pull/111
As a temporary workaround feel free to use the branch `fix/m1`. 
Or apply / cherry-pick 6fc9e5edbc2bdc0b7018d631085b9857649eace5 directly onto your working branch.

**Comment by marinofaggiana** [comment]
I have already prepared a fix with the last OpenSSL, in January will be done.

**Comment by satiromarra** [comment]
Changing to branch fix/m1 works, thanks.
