### ISSUE TITLE
Some PDF preview images are broken

### ISSUE THREAD

**Issue by AInteriorB** [nextcloud/ios#1844]
### Steps to reproduce

1. enable PDF preview in Nextcloud
2. Some PDF preview images are broken in the app, not so in the web

### Expected behaviour

The preview images shouldn‘t be broken

### Actual behaviour

Some PDF preview images are broken if you browse by app. If you access Nextcloud via browser, everything is good and the mentioned preview images are not broken.

### Screenshots

![IMG_2742](https://user-images.githubusercontent.com/49516700/147857433-f9b04ed3-4f74-4e5b-9f90-d2670e2db2da.jpeg)

### Environment data

**iOS version:** iOS 15.2

**Nextcloud iOS app version:** 4.2.0.5

**Web server:** Apache

**PHP version:** 7.4

**Nextcloud version:** 23.0.0

**Comment by thisIsTheFoxe** [comment]
Thanks!
This seems like a known bug, that sometimes also causes the app to crash. Can you confirm that only the 'preview' images are affected and not the PDFs themselves?

https://github.com/nextcloud/ios-communication-library/pull/107

**Comment by AInteriorB** [comment]
Yes, I can confirm that only the preview images in the app are broken. The PDFs themselves are o.k.. I can also confirm the crash of the app. Happens almost all the time, if no preview image is generated yet. For instance, if you have just uploaded a new PDF. There doesn‘t seem to be a problem with the preview images when working in the browser.
