### ISSUE TITLE
"Picking folders" in the iOS-Files app

### ISSUE THREAD

**Issue by rhilliges** [nextcloud/ios#1858]
I would like to create a cryptomator vault inside my nextcloud instance and access it on my iPhone. 

### Steps to reproduce

1. Open cryptomator app
2. Create new vault
3. Select "Open existing vault"
4. Try to open vault in nextcloud via iOS-files app

### Expected behaviour

It should be possible to select nextcloud.

### Actual behaviour

"Nextcloud" is grayed out because it does not support selecting a folder.

According to the cryptomator repo "Apps need to support "picking folders" via NSExtensionFileProviderSupportsPickingFolders in the Info.plist of the file provider extension. However, this key doesn't seem to be officially documented anywhere by Apple."...
https://github.com/cryptomator/ios/issues/51

**Comment by hpfr** [comment]
I just came across this issue with [Beorg](https://appsonthemove.freshdesk.com/support/discussions/topics/14000018888), which implements picking a folder for task management files.

From the [Twitter thread](https://twitter.com/palmin/status/1178031204018380800) in the linked Cryptomator issue it looks like it's possible to support this, but it depends on how Nextcloud is implemented. Working Copy and Secure Shellfish apparently support it.

**Comment by michaelstingl** [comment]
Related: https://github.com/nextcloud/ios/issues/943

**Comment by marinofaggiana** [comment]
Hi, not possible because for iCloud a directory it's only a container but for Nextcloud a directory is really a folder in the file-system.

**Comment by rbajevs** [comment]
It's possible for SecureShellfish which is definitely a folder file system. It should be possible on Nextcloud too

**Comment by hpfr** [comment]
As @michaelstingl mentioned, it looks like this issue (and #1452) appear to be duplicates of #943, the oldest and largest thread. It might be good to consolidate discussion there for watchers
