### ISSUE TITLE
Media tab: use correct size for thumbnails

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#1861]
### Steps to reproduce

1. go to media tab on e.g. iPad
2. see thumbnails downloaded
3. change grid to only show one big image per row

### Expected behaviour
High res thumbnail

### Actual behaviour
See blurry image

**Comment by marinofaggiana** [comment]
mmm @tobiasKaminsky  I use the 1024 px ... I don't want to burden the server too much ...
