### ISSUE TITLE
More tab: Text color for Settings row

### ISSUE THREAD

**Issue by rygen** [nextcloud/ios#187]
Tiny detail, but... is there any reason for it to have a lighter color? 
Upon first use I thought it was disabled, due to its gray color.

**Comment by marinofaggiana** [comment]
done.

**Comment by rygen** [comment]
I was asking about the rationale for having it in gray instead of black. So what does "done" mean? :)

**Comment by marinofaggiana** [comment]
@rygen It's correct black color, grey was an oversight.
