### ISSUE TITLE
App crashes after update to 4.2.1 on iOS 12.5.5

### ISSUE THREAD

**Issue by franztv82** [nextcloud/ios#1876]
### Steps to reproduce

1. Update to version 4.2.1 on iOS 12.5.5 / iphone6
2. Open app

### Expected behaviour

App should open

### Actual behaviour

App opens for a second an then crashes. Tried to reinstall, same behaviour.

Settings > Nextcloud > Version shows "0"

### Environment data

**iOS version:** iOS 12.5.5

**Nextcloud iOS app version:** 4.2.1

**Server operating system:** Ubuntu 20.04

**Web server:** Apache

**Database:**  MariaDB 10.3.32

**PHP version:** 7.4

**Nextcloud version:** 23.0.0

**Comment by marinofaggiana** [comment]
Hi all, I can't test it with the 12.5.5 ... I have tested with 12.4 without problem.

**Comment by franz-tv** [comment]
I had a similar behaviour with joplin app some time ago - this was the solution: [https://github.com/laurent22/joplin/issues/5671](https://github.com/laurent22/joplin/issues/5671)
I'm just a user, not a developer, but perhaps it helps finding a solution...

**Comment by rbiegel** [comment]
Same here on iPhone 6, iOS 12.5.5

**Comment by gyurix1968** [comment]
Hi All, same issue of mine on the same versions of iPhone. The biggest problem is that it is not possible to revert to the previous version (4.2.0) via AppStore unfortunately.

**Comment by gyurix1968** [comment]
@thisIsTheFoxe thanks for your answer, your opinion is not working unfortunately because the minimum required iOS for installing Testflight is 13 - the mentioned iPhone has only 12.5 and it is a latest available actually. But I understand the developer don't want to make software for unsupported models.

**Comment by marinofaggiana** [comment]
No no @gyurix1968 is a problem with the last XCode 13.2.x (?) and some old iOS (12.5.x); we are trying to figure out how to fix

**Comment by foss-** [comment]
For what its worth, here's the crash log (1 month): https://bin.disroot.org/?d5abb813c56edc33#H9XTx59mhvwb883Ttmp2hNuw5VdHkvyUEM7D9ukZU6vV

Hope you can tackle the crash. You are in good company by the way - there were a few other apps suffering from the same problem I think, amongst them the popular 1Password iOS app.

**Comment by japrenticeuk-141** [comment]
Apologies if this suggestion is too obvious but it might help someone. On our old iPads (iOS 9.3.5) it is not possible to use the NextCloud web interface. Chrome fails to display the user/password entry fields - just the Change Password link. They can, however, be used with the old vestion of the App as mentioned above (you have to juggle with the Apple Account on a modern device to persuade the appStore to offer it to you).

On iOS 12.5.5 it **is** possible to run Chrome 92.0.4515.90 and with this the web interface login works fine so it is possible to access the NextCloud files despite the death of the app.  It is not so easy to use as the app but better than nothing. 

FWIW I am running the rather ancient Nextcloud server version 21.0.1 on a CloudAmo server. 

HTH - John

**Comment by ufitec** [comment]
> Apologies if this suggestion is too obvious but it might help someone. On our old iPads (iOS 9.3.5) it is not possible to use the NextCloud web interface. Chrome fails to display the user/password entry fields - just the Change Password link. They can, however, be used with the old vestion of the App as mentioned above (you have to juggle with the Apple Account on a modern device to persuade the appStore to offer it to you).
> 
> On iOS 12.5.5 it **is** possible to run Chrome 92.0.4515.90 and with this the web interface login works fine so it is possible to access the NextCloud files despite the death of the app. It is not so easy to use as the app but better than nothing.
> 
> FWIW I am running the rather ancient Nextcloud server version 21.0.1 on a CloudAmo server.
> 
> HTH - John

Sorry, this thread is not about the web interface. It's about the Nextcloud App. Because of that your comment is not helpful.
Nobody of us is interested in any kind of workaround, we need the funcional native IOS app back again.
Have a nice evening all

**Comment by sujeethreddy567** [comment]
Even I am facing the same Issue with my iPad mini 2 IOS 12.5.5 Its impeding my productivity.

**Comment by ObiSandwich** [comment]
Same here with iPad Mini 12.5.5

QUICK FIX ACCESS: WEBDAV with this free app...

https://apps.apple.com/us/app/fe-file-explorer-file-manager/id510282524

**Comment by onkelbeh** [comment]
Is there a way to install the last version?

**Comment by ajay-gh** [comment]
Same problem on another iPad with iOS v12.5.5, after updating the Nextcloud app: the app quits immediately after start, without any message etc. Further information:
=> when I try to read the version of the Nextcoud app in the iOS settings menu/dialog, that version is listed as 0 (zero).
=> Nextcloud app ran flawlessly on this iPad for years.
=> an iOS restart has not helped, an uninstall / reinstall cycle through the app store hasn't helped either.

Looking at the earlier comments it seem clear to me that the devs need to allow the users with iOS v12.5.5 to download an earlier / compatible version of the Nextcloud app. This is foreseen in the iOS App store, just a matter of a few settings. But it can only be done by the devs.

**Comment by japrenticeuk-141** [comment]
> Same here with iPad Mini 12.5.5
> 
> QUICK FIX ACCESS: WEBDAV with this free app...
> 
> https://apps.apple.com/us/app/fe-file-explorer-file-manager/id510282524

Thank you @ObiSandwich - a better workaround than using a web browser but as everyone says we **do** need the dev to do a fix to the NextCloud app.

**Comment by rakekniven** [comment]
Same here on an iPad Air 2013 (A1474) using latest iOS version 12.5.5

@marinofaggiana Anything I can help to figure out the problem ? Testflight version?

**Comment by foss-** [comment]
If you are affected by this problem please use the thumbs up reaction in the original report instead of posting a comment with no value which triggers a notification to all subscribers. Thank you.

**Comment by marinofaggiana** [comment]
Soon available the 4.2.2 Build 7

**Comment by marinofaggiana** [comment]
V 4.2.2 available on Apple Store

**Comment by japrenticeuk-141** [comment]
Thank you. Now works on iOS 12.5.5 on iPad Mini 3 and also ckecked with iOS 15.2.1 (iPhone) and is OK

John

**Comment by franztv82** [comment]
Works on iphone6 / 12.5.5, too. 
Thank you very much!

**Comment by divaylo** [comment]
Works perfectly on iPhone 6+ (iOS 12.5.5), too! Many thanks for the fix!
