### ISSUE TITLE
Feature request (bug?) Generate thumbnails for videos

### ISSUE THREAD

**Issue by via-justa** [nextcloud/ios#1877]
### Expected behaviour

When the media app generates thumbnails it would generate thumbnails for videos as well without the need to open the video

### Actual behaviour

Picture thumbnails are created while scrolling but video thumbnails are not (gray square with play icon). the thumbnails are created only after opening the video for the first time (both *.mov and *.mp4 are the same)

### Reasoning or why should it be changed/implemented?
When loading multiple videos and pictures it's hard to locate the right video and instead one need to click on each and every video to find the one looking for.

### Environment data

**iOS version:** 15.2.1

**Nextcloud iOS app version:** 4.2.1.7

**Server operating system:** n/a

**Web server:** n/a

**Database:** n/a

**PHP version:** n/a

**Nextcloud version:** 22.2.0

**Comment by Bellusterra** [comment]
I don’t know if you are using the Nextcloud docker image, but you can adjust accordingly for your configuration I created a comment at the bottom to reference. https://github.com/nextcloud/previewgenerator/issues/233
It will still require you to scroll to pull in the thumbnails just like the images, but will not require opening each video as you are doing now.

**Comment by vpistis** [comment]
@Bellusterra thank you! from many years I was looking for this solution.
I have not see in any doc that can be add `ffmpeg` path into `config.php`. Now I have also Video thumbnails!

**Comment by darguez** [comment]
Hi there, do you distinguish between photo and video previews? The app shows a play icon over the preview image on videos, but the web doesn't. Am I missing something?

Thanks!

**Comment by ChildLearningClub** [comment]
> Hi there, do you distinguish between photo and video previews? The app shows a play icon over the preview image on videos, but the web doesn't. Am I missing something?
> 
> Thanks!

@darguez have you cleared the cache in your browser? That one often tricks me?

**Comment by kamikazeedriver** [comment]
> Hi there, do you distinguish between photo and video previews? The app shows a play icon over the preview image on videos, but the web doesn't. Am I missing something?
> 
> Thanks!

I am looking for this solution also.  
Using Preview Generator (and ffmpeg installed on server), my videos now have a nice thumbnail, but without the "play button" overlay you see in the app, it's difficult to distinguish them apart from photos.

Would love to see this be standard.

**Comment by via-justa** [comment]
Closing as it doesn't look like it's getting any traction.
