### ISSUE TITLE
Location information has coordinates converted to positive values

### ISSUE THREAD

**Issue by dukey** [nextcloud/ios#1896]
### Steps to reproduce

1. Open a geotagged image with coordinates in the western hemisphere
2. Download full resolution version
3. Display location.  Location is at the same coordinates, but the eastern hemisphere

### Expected behaviour

Tell us what should happen.
Correct location should be displayed
### Actual behaviour
  
Tell was what instead happens.
A negative value for longitude becomes positive ie 42.0,-79.3 becomes 42.0,79.3 (42.0N, 79.3W becomes 42.0N, 79.3E) 
### Screenshots

If applicable, add a screenshot showing the issue.

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Reasoning or why should it be changed/implemented?
Location is  is incorrect for half of the world
### Environment data

**iOS version:** e.g. iOS 14.4.1
15.3.1
**Nextcloud iOS app version:** see More > Settings
4.2.1.7
**Server operating system:**
Fedora 24
**Web server:** Apache, nginx
Apache
**Database:**
MariaDB
**PHP version:**
7.4.28
**Nextcloud version:** see Nextcloud admin page
23.0.2

**Comment by dukey** [comment]
The issue is also with version 4.2.2.7

**Comment by thisIsTheFoxe** [comment]
Thanks a lot for the report.
I was able to reproduce this and even more, the same happens for coordinates in the southern hemisphere. But good news: as far as I can see the wrong coordinates aren't actually saved so it should work normally after fixing it without the need to re-uplaod.
Could you just let us know if you see an address being displayed below the map view, and if so if the address is correct and only the map location is wrong?
