### ISSUE TITLE
Selected Item count shows wrong number after Selecting

### ISSUE THREAD

**Issue by togglecode** [nextcloud/ios#19]
If you select some files and then deselect them, the counter of the selected files will not update.

P.S as you can see in the screenshot the description about last update time is wrong, instead of "1 hours ago" it should be "1 hour ago".

![2016-12-20_11-30-56_0481](https://cloud.githubusercontent.com/assets/17141698/21347527/4cf1bdb0-c6a9-11e6-9a4e-32391c20be6c.png)
![2016-12-20_11-31-04_0482](https://cloud.githubusercontent.com/assets/17141698/21347528/4cf1e59c-c6a9-11e6-9751-8f65ab8403e1.png)

**Comment by marinofaggiana** [comment]
Thanks @togglecode !
