### ISSUE TITLE
Support JavaScript in built in web browser

### ISSUE THREAD

**Issue by timbru31** [nextcloud/ios#190]
This is more like a question if it's possible at all or an iOS limitation.

Given I have an `.html` file in my Nextcloud, I'd like to use the built in web browser of the app to display the page - however JavaScript is not supported.
Is it possible to enable this?

**Comment by timbru31** [comment]
Just gave Dropbox a try, their web browser is able to load pages with JS.

**Comment by timbru31** [comment]
ping @marinofaggiana is this possible with minor effort?

**Comment by marinofaggiana** [comment]
please patient @timbru31 I am very busy in this time :-) sorry

**Comment by timbru31** [comment]
Just re-checked, seems to work now.
