### ISSUE TITLE
l10n: Context needed for string "of"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#1906]
Hello @marinofaggiana,

can you provide some context for:
https://github.com/nextcloud/ios/blob/c56ee9238ae0c67c5ae55df7306f9c4e5e138843/iOSClient/Supporting%20Files/en.lproj/Localizable.strings#L127

**Comment by rakekniven** [comment]
Ok, did a checkout of the repo and found the following occurences:
./iOSClient/Viewer/NCViewerPDF/NCViewerPDF.swift
./iOSClient/Supporting Files/en.lproj/Localizable.strings
./iOSClient/Utility/ParallelWorker.swift
./Share/NCShareExtension.swift

That means "of" as in the following examples:
Page 2 of 17
Task 4 of 21
Uploaded 12 of 25 files

**Comment by meskobalazs** [comment]
In that case I am pretty sure, that these should not be a separate strings, as this way we can't reorder the string. E.g. in Hungarian "Page 2 of 17" would be "2 / 17. oldal" as we don't say "page two", we say "second page". And I am quite sure this is true in other languages.

**Comment by rakekniven** [comment]
Hello @meskobalazs ,

nice to see you over here.

Please feel free to open a new issue addressing your issue. In english it works, in german as well (the languages I speak 😄). Maybe other languages have trouble as well.
