### ISSUE TITLE
iOS App 2.17 keeps crashing on iPhone / iPad 

### ISSUE THREAD

**Issue by d1ffuser** [nextcloud/ios#191]
The App crashes within 3 seconds after configuring the account / logging in.
Deleting, rebooting, reinstalling doesn't help.

Stats:
App Version 2.17
iPhone 5, iOS 10.2.1
iPad mini 2, iOS 10.3.1
Nextcloud 11.0.2
PHP 7.0.16
MySQL 5.5.54

**Comment by marinofaggiana** [comment]
Hi @d1ffuser thanks for your collaboration, can you send me an account test of your server Nextcloud on ios@nextcloud.com

Thanks.

**Comment by d1ffuser** [comment]
Ah, some progress. I have created a new test account. 
The app works with a new account and the sample files. But crashes again, after I enter my old credentials to log into my old account. Sadly, I can't provide access to that account.

Maybe it has something to do with the files / previews. Will do some testing.

**Comment by marinofaggiana** [comment]
mmm verify the favorite file ? at start the app sync the favorite files/Dir

**Comment by d1ffuser** [comment]
I don't understand, which favorite file?
The app crashes directly after entering the credentials. (I can see, that the app accesses my files and folders for a second.) I can't access the settings..

**Comment by marinofaggiana** [comment]
On Nextcloud server have you select Favorite files ?

**Comment by d1ffuser** [comment]
No, not using favorites.

**Comment by marinofaggiana** [comment]
mmm ok, verify file / directory at home ... attached device external ?

**Comment by d1ffuser** [comment]
The test account works with the same external storage..

**Comment by d1ffuser** [comment]
I think I've found the problem. The app crashes, when the username is not entered case sensitive.
I successfully logged in with "adam", but the username is "Adam". Here's the error:

`initMountPoints() called with wrong user casing. This could be a bug. Expected: "Adam" got "adam". Stack: [{"file":"\/var\/www\/apache\/nc\/lib\/private\/Files\/Filesystem.php","line":375,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"\/var\/www\/apache\/nc\/lib\/private\/legacy\/util.php","line":235,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"\/var\/www\/apache\/nc\/apps\/provisioning_api\/lib\/Controller\/UsersController.php","line":683,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"\/var\/www\/apache\/nc\/apps\/provisioning_api\/lib\/Controller\/UsersController.php","line":258,"function":"fillStorageInfo","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->"},{"file":"\/var\/www\/apache\/nc\/apps\/provisioning_api\/lib\/Controller\/UsersController.php","line":197,"function":"getUserData","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->"},{"function":"getUser","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->"},{"file":"\/var\/www\/apache\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":160,"function":"call_user_func_array"},{"file":"\/var\/www\/apache\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":90,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/var\/www\/apache\/nc\/lib\/private\/AppFramework\/App.php","line":114,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/var\/www\/apache\/nc\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"\/var\/www\/apache\/nc\/lib\/private\/Route\/Router.php","line":299,"function":"call_user_func"},{"file":"\/var\/www\/apache\/nc\/ocs\/v1.php","line":79,"function":"match","class":"OC\\Route\\Router","type":"->"}]`

Logging in "case sensitive" works!

**Comment by marinofaggiana** [comment]
OMG ... can you re-create this issue on your server ? (account test)

**Comment by d1ffuser** [comment]
More or less; the app doesn't crash, but the log shows a lot of errors:

`initMountPoints() called with wrong user casing. This could be a bug. Expected: "TestUser" got "testuser". Stack: [{"file":"\/var\/www\/apache\/nc\/lib\/private\/Files\/Filesystem.php","line":375,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"\/var\/www\/apache\/nc\/lib\/private\/legacy\/util.php","line":235,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"\/var\/www\/apache\/nc\/lib\/base.php","line":1009,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"\/var\/www\/apache\/nc\/index.php","line":40,"function":"handleRequest","class":"OC","type":"::"}]`

`OCP\Files\NotFoundException: 
/var/www/apache/nc/apps/files/lib/Controller/ViewController.php - line 136: OC_Helper getStorageInfo('/', false)
/var/www/apache/nc/apps/files/lib/Controller/ViewController.php - line 199: OCA\Files\Controller\ViewController->getStorageInfo()
[internal function] OCA\Files\Controller\ViewController->index('', '', NULL, false)
/var/www/apache/nc/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/apache/nc/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files\Controller\ViewController), 'index')
/var/www/apache/nc/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
/var/www/apache/nc/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/apache/nc/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/apache/nc/lib/base.php - line 1010: OC\Route\Router->match('/apps/files/')
/var/www/apache/nc/index.php - line 40: OC handleRequest()
{main}`

Both, multiple times...

**Comment by marinofaggiana** [comment]
@MorrisJobke can you help we ?

**Comment by marinofaggiana** [comment]
@d1ffuser but do not crash .... but in your home yes ...

**Comment by d1ffuser** [comment]
Yes, with the test account the app doesn't crash (but creates a lot of errors.)
With my old account the app crashes..

If I find the time, I'll do some more testing. Maybe it's a combination of folders / external storage and the above error that causes the crash...

**Comment by marinofaggiana** [comment]
@d1ffuser yes, thanks

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/server/issues/4445

**Comment by marinofaggiana** [comment]
Version 2.17.1 available - bugfix for this issue.
