### ISSUE TITLE
Photos is not uploading in the Background if the App is closed

### ISSUE THREAD

**Issue by enoch85** [nextcloud/ios#192]
Up until now I've been using the ownCloud iOS app mainly because it's capable of uploading both Videos and Photos in the background, even if the app is closed (as in totally closed, not in foreground, not in background, not active - just installed with an account setup). Photos *should* be uploaded not only when you open the App, but also in the background.

We had a discussion about this before on the help forums, and now I'm posting an issue instead, as this really is a dealbreaker for me to start using the iOS app from Nextcloud. So when will this be introduced in the Nextcloud app?

Btw, great release 2.17. :)

**Comment by marinofaggiana** [comment]
Hi @enoch85 I don't understand your issue, the political Apple and the NSURLSession API and the capabilities of background are clear. 

In IOS do not exist a true background but only (callback) limitate. If you want a true background system switch to Android. 

All the app (Dropbox, one drive but Facebook twitter as well) have this limit, only the app Apple can use a sub API private for background. 

This is IOS (ps the first version of iOS was single-task).

Conclusion : you request is not possible for IOS. Sorry

**Comment by enoch85** [comment]
Then the ownCloud devs are doing the "impossible". :)

Somehow they manage to upload pictures in the Background even with the app not open. It's based on location so it's not instant, but still - without opening the app photos gets added to Instanupload on the server.

**Comment by marinofaggiana** [comment]
The procedure of Nextcloud, ownCloud and Dropbox are the same, use the location capabilities for "wake up" the app after the app have 30 sec for loading new image video but (if this do not crash for intensive use of CPU .. iOS check the process ;-) and send this on NSURLSession in background mode ... but the new task create in background more are very slow ... for example if you are 50 images the firs 1,2....5 are uploaded ma the other remains in queue ... this is not a background system, this is a tarot or if you want an illusion. This is not a multithreaded system !! Try ! Do not open Dropbox or OwnCloud e make 25 photos and 10 videos ... Make a serious measurement and then write a issue with times for uploaded the 35 item without open the app. Bye

**Comment by enoch85** [comment]
> use the location capabilities for "wake up" the app after the app have 30 sec for loading new image video 

Ok, so maybe that's how it's done. As I said, it's not instant, but at least the pictures gets upload over time (a few days) I've not seen the same with the Nextcloud app, so maybe this is a bug?

**Comment by enoch85** [comment]
This is what I mean: https://github.com/nextcloud/ios/issues/215
