### ISSUE TITLE
Confusing duplicated feature producing different results (Open in... > Save image vs. Save to photo gallery

### ISSUE THREAD

**Issue by mailinglists35** [nextcloud/ios#1925]
One adds full original image to iOS Photos, the other compresses the image and strips exif

![image](https://user-images.githubusercontent.com/2054302/157949613-6fb298a3-6dc5-4cd6-9185-6fe6444ee851.jpeg)

![image](https://user-images.githubusercontent.com/2054302/157949715-1e7a919e-3dba-4125-b823-eba22ae1cc8e.jpeg)

![image](https://user-images.githubusercontent.com/2054302/157949748-7cf06752-fe0f-4a54-accb-f7378975a4c2.jpeg)

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/2243

**Comment by mailinglists35** [comment]
@marinofaggiana please note that the issue you duped against only talks about exif.
My report is also about losing picture quality.

**Comment by marinofaggiana** [comment]
> @marinofaggiana please note that the issue you duped against only talks about exif.
> My report is also about losing picture quality.

Try the 4.5.5 (build >= 2) when available in TestFlight

**Comment by mailinglists35** [comment]
thank you. both ways seem now to export the same photo including exif
