### ISSUE TITLE
Login mask

### ISSUE THREAD

**Issue by ghost** [nextcloud/ios#1928]
### Is your feature request related to a problem? Please describe.
Users are confused when a web page opens and they are asked to enter their username and password. Especially with mobile or bad internet this takes a moment until the page is completely displayed.

### Describe the solution you'd like
When logging into the Nextcloud app, do not redirect to the login page of the Nextcloud instance, but create a mask in which you can log in without opening an external page.

### Additional context
Many companies use such a login mask like for example Synology at their Diskstation.

[ Login mask #9968 ](https://github.com/nextcloud/android/issues/9968)

**Comment by joshtrichards** [comment]
See comment on nextcloud/android#9968 explaining why this isn't feasible.
