### ISSUE TITLE
App store entry style

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#193]
Some apps on the app store have this new big banner and colored background:
![image](https://cloud.githubusercontent.com/assets/925062/25315222/070a3506-2852-11e7-8891-b2a9d4b2be85.png) ![image](https://cloud.githubusercontent.com/assets/925062/25315223/0752b1c8-2852-11e7-95a0-2956af9e9bc4.png)

@marinofaggiana do you know how we can do that?
- banner should be the usual image: https://github.com/nextcloud/server/blob/master/core/img/background.jpg
- background Nextcloud blue #0082c9
- foreground white

**Comment by marinofaggiana** [comment]
A internet post : 

This is not something you can do on your own. If Apple would like to feature your app (there are many levels of featuring an app) they will contact you, usually last minute to prepare image assets to give to them to use on your product pages in the App Store.

This is usually reserved for very popular or high profile apps, however sometimes large companies have special relationships with Apple and have a higher frequency of having their apps featured at the basic level (customs colors and image background) but this isn't that common.

**Comment by jancborchardt** [comment]
Ah, too bad. :( Thanks for the info! :)

**Comment by marinofaggiana** [comment]
When Nextcloud is 10.000.000 users ....

**Comment by jancborchardt** [comment]
Soon … ;)
