### ISSUE TITLE
Specific upload error files to Nextcloud

### ISSUE THREAD

**Issue by Bijdrager** [nextcloud/ios#1934]
I've moved NextCloud to a different server and now the following error happens:

### Steps to reproduce

1. In your Iphone, go to for example, files
2. Select a file 
3. Keep pressed -> click share -> choose NextCloud app
4. NextCloud App opens -> Click upload 1 file. 
5. When uploading from a mobile device AND filesize is  > 100Kb on average. A loading wheel appears  with the text "upload file 1 of 1" and nothing happens. At that point, only "cancel" is possible. With small files it works

Everything works fine when uploading files to NextCloud:
- Mobile device (IOS) from any other app AND a file size on average smaller than 100Kb (this is not a hard line. Accepted files can be 86Kb or 112Kb at times)
- Mobile device (IOS) trough the big plus in the NextCloud app.

- Desktop (OSX & Windows) : outside the NextCloud client environment.
- Desktop (OSX & Windows): inside the NextCloud client environment.

### Expected behaviour

When uploading files from a mobile device (IOS) using anything else than the native NextCloud App AND the file size is on average bigger than 100Kb. The file should be uploaded to Nextcloud.

### Actual behaviour

When uploading files from a mobile device (IOS) using anything else than the native NextCloud App AND the file size is on average bigger than 100Kb. I get a loading wheel and nothing happens. 100Kb is not a hard line, sometimes 120Kb will work, sometimes 80Kb will not work. 

### Screenshots

[https://triotech.nl/stuck.png](url)

### Logs

```
**IOS log:**

2022-03-23 11:21:41 Network request started: GET https://domain.com/cloud/ocs/v2.php/apps/user_status/api/v1/user_status?format=json (404)
2022-03-23 11:21:41 Network response request: https://domain.com/cloud/ocs/v2.php/apps/files_sharing/api/v1/shares?reshares=false&shared_with_me=false&subfiles=false, result: success(138 bytes)
2022-03-23 11:21:41 Network response request: https://domain.com/cloud/ocs/v2.php/apps/user_status/api/v1/user_status?format=json, result: failure(Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 404)))

**Acceslog server:**

"GET /cloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
"POST /cloud/index.php/login HTTP/2" 303 0 "-" "Device (Nextcloud iOS)"
"GET /cloud/index.php/login?redirect_url=/cloud/index.php/login/flow/grant?clientIdentifier%3D%26stateToken%fornowrandomlettersandnumbers&user=User&direct=1 HTTP/2" 200 4440 "-" "Device (Nextcloud iOS)"
"GET /cloud/index.php/core/js/oc.js?v=fornowrandomnumbers HTTP/2" 200 1502 "-" "Device (Nextcloud iOS)"
"GET /cloud/cron.php HTTP/2" 200 24 "-" "Device (Nextcloud iOS)"

**Error log Cpanel:** 

nothing

**Error log one of the mobile devices:** 

It's already from the day before yesterday and the only log related to NextcCloud in the device. 
If I upload a file from, for example excel, it will not work but there will be no error either..

{"app_name":"Nextcloud","timestamp":"2022-03-22 18:35:10.00 +0100","app_version":"4.3.1","slice_uuid":"********-****-****-****-**********","adam_id":"**********",
"build_version":"0","platform":2,"bundleID":"it.twsweb.Nextcloud","share_with_app_devs":0,
"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 15.2 (19C56)","incident_id":"62690D1E-268A-472F-A3DC-CD0C11F9EA10","name":"Nextcloud"}
{"uptime" : 86000,"procLaunch" : "2022-03-22 18:25:18.5540 +0100","procRole" : "unknown","version" : 2,"userID" : 501,
"deployVersion" : 210,"modelCode" :
 "iPhone11,2","procStartAbsTime" : 2070606781848,
 "coalitionID" : 1140,"osVersion" : {"isEmbedded" : true,"train" : "iPhone OS 15.2","releaseType" : "User","build" : "19C56"},"captureTime" : "2022-03-22 18:35:10.2088 +0100","incident" : "62690D1E-268A-472F-A3DC-CD0C11F9EA10",
 "bug_type" : "309","pid" : 4047,"procExitAbsTime" : 2084741466123,"cpuType" : "ARM-64","procName" : "Nextcloud",
 "procPath" : "\/private\/var\/containers\/Bundle\/Application\/B70EADAA-9201-462F-8AA0-CC6GD791DE1\/Nextcloud.app\/Nextcloud","bundleInfo" : {"CFBundleShortVersionString":"4.3.1","CFBundleVersion":"0","CFBundleIdentifier":"it.twsweb.Nextcloud","DTAppStoreToolsBuild":"13E112"},
 "storeInfo" : {"storeCohortMetadata":"7|date=1621002600000&sf=143452&pgtp=Search&pgid=0f453a21-0a9b-4f1e-b727-9270fdf798a1&prpg=Genre_179183&ctxt=Search&issrch=1","itemID":"1125420102","deviceIdentifierForVendor":"Af39-C3FF-4212-45BE-1BS1-092675B2CD3",
 "softwareVersionExternalIdentifier":"123456789","thirdParty":true,"applicationVariant":"1:iPhone11,2:15"},"parentProc" : "launchd","parentPid" : 1,
 "coalitionName" : "it.twsweb.Nextcloud","crashReporterKey" : "f8960e7ac2a69c475e90431b74cfb742b3cce0d7","basebandVersion" : "4.02.02","isCorpse" : 1,"exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL"},"termination" : {"namespace":"RUNNINGBOARD","flags":6,
 "code":3735883980},"ktriageinfo" : "VM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\n","faultingThread" : 0,
```

### Reasoning or why should it be changed/implemented?

It worked before moving to the new server, but I don't get any errors why it doesn't work anymore. 

### Environment data

**iOS version:** 
15.2

**Nextcloud iOS app version:** 
4.3.1.0

**Server operating system:**
Server old: Linux 3.10.0-962.3.2.lve1.5.33.el7.x86_64 x86_64
Server new: Linux 4.18.0-348.12.2.lve.el8.x86_64 x86_64

**Web server:** 
Apache / Cpanel 

**Database:**
mysql

**PHP version:**
7.4 (tried 8.0 also)

**Nextcloud version:**
23.0.3.2

Already tried:
I made a testcloud (which is empty and login can be provided if needed) beside the cloud which gives the problem. The problem persists.
Tried different PHP versions. 
Tried different PHP cache settings.
Reset the App.
Tried different devices (iphone and ipad, even with old IOS versions)
Posted this issue on Reddit and they suggested I post it here.
Followed this tutorial: https://github.com/JuanRodenas/Nextcloud_server

**Comment by thisIsTheFoxe** [comment]
Hi,
Thanks for letting us know about your issue and thanks for all the logs you attached.
I assume you got the iOS logs from the Nextcloud.app > More > Advanced > View log file. Could you please try to reproduce the error with the log level at maximum? When checking the logs afterward they should include the full request and the failing server response (apparently with with status code 404). This will hopefully help us narrow down the problem.

Also please note that we are currently trying to generally improve our error handling throughout the app.

**Comment by Bijdrager** [comment]
Hi @thisIsTheFoxe 
Thank you for your quick reply. 
The full log of the test NextCloud is attached!
[communication.log](https://github.com/nextcloud/ios/files/8340675/communication.log)

**Comment by thisIsTheFoxe** [comment]
Thanks!
And I need to apologise, the errors in the logs you added initially seem to be unrelated to this issue.
It looks like the server responds with a file size of 0. I'm still unsure what is the cause of that... Are you able to upload larger files in general (> 1MB) in the app and via the Share extension?

However, I can confirm the behaviour you mentioned in step 5. We'll fix this soon.

**Comment by Bijdrager** [comment]
Thanks again!
I hope this answers your question:

I just tried to upload a 5MB file in the App (trough the big +) : works fine
If I try to upload the same 5MB file from files (IOS) to NextCloud : doesn't work
If I upload a 17MB PDF from my OSX environment to NextCloud : works fine
