### ISSUE TITLE
Gone From Canada App Store

### ISSUE THREAD

**Issue by cbrompton** [nextcloud/ios#194]
Today, the iOS App was removed from the Canadian App Store. I went to add it onto my phone and it said its no longer available. Just curious if this was intentional. It was there yesterday.

**Comment by stijnhaezebrouck** [comment]
It is gone from the Belgium and US App store as well.

**Comment by marinofaggiana** [comment]
Sorry, be patient, Nextcloud iOS is in maintenance mode for a problem on AppStore.  

Soon new version 2.17.1
