### ISSUE TITLE
Stop retrying up-/download after server rejection [M]

### ISSUE THREAD

**Issue by thisIsTheFoxe** [nextcloud/ios#1955]
### Steps to reproduce
1. Upload / Download a file
2. Get a rejection form the server (e.g. because share permissions have changed and server returns a 403 error)

### Expected behaviour
Alert user. Possibly ask user if transfer should be retried. Or just show an alert that it failed and remove the transfer.

### Actual behaviour
The app alert the user, but automatically retries the up-/download after a timeout when `NCNetworkingProcessUpload` is called again. 
This loops endlessly, without hope for success, unless changes are made on the server side.

### Related
- #770

### Reasoning or why should it be changed/implemented?
It's not easy to find a solution that fits everyone. On the one hand it makes it clearer for single files. On the other hand if I want to upload multiple files (e.g. auto-upload) it would be overwhelming to ask for every file.
Maybe this could be an app setting: "Automatically retry failed transfers? (on/off)

### Environment data

**iOS version:**  iOS 15.3
**Nextcloud iOS app version:** 4.3.1

**Comment by marinofaggiana** [comment]
For now I don't have find a (simple) solution ... and the app setting: "Automatically retry failed transfers? (on/off) is not a solution acceptable, if anyone has any good ideas ?!

**Comment by tobiasKaminsky** [comment]
At least for above use case we can check if target folder is still writable, and if not, we do not retry.

**Comment by marinofaggiana** [comment]
Fixed with two possibility:
- save with a different name (1,2....n)
- discard

![Simulator Screen Shot - iPhone 14 - 2022-11-25 at 16 15 26](https://user-images.githubusercontent.com/8616947/204023554-50ef6958-6016-4ccf-9360-20bf4cd911b0.png)
