### ISSUE TITLE
Enabled Officeonline via mobile app

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/ios#1965]
Please see https://github.com/nextcloud/officeonline/issues/231 & 

https://github.com/nextcloud/server/pull/17625

**Comment by andyxheli** [comment]
@marinofaggiana  Hello any news on this and if its something that going to get supported. You currently support Only office and nextcloud office but not this. If not I'll close this. 

Thank you!

**Comment by AndyXheli** [comment]
Closing as there hasn't been any response on this from the dev. If dev wants it they can reopen it.
