### ISSUE TITLE
Fix the user-agent for online editing

### ISSUE THREAD

**Issue by thisIsTheFoxe** [nextcloud/ios#1967]
### Steps to reproduce
1. Create blank Xcode project with a single `WKWebView`
2. Set the `WKWebView`'s`.customUserAgent` to *Mozilla/5.0 (iOS) Nextcloud-iOS/4.4.0*
3. Load a *directEditing* url with that webview
4. Try e.g. passing an image
5. Do the same but adding *AppleWebKit/605.1.15 Mobile/14E304* to the user-agent

### Actual behaviour
When loading without the additional user-agent components pasting images fails. 

### Proposed solution
Change the user-agent at least for `NCViewerNextcloudText`. 
Or if it's needed for other competent of the web app change the user-agent in general. ~~However, this would also require changes in the server.~~

### Reasoning or why should it be changed/implemented?
Some 3rd party libraries and frameworks use the user-agent for platform specific workarounds.
This might be also be the root cause for other issues and glitches with office apps using the Nextcloud iOS app.
Would probably also be a good idea to check the Android app for similar issues @tobiasKaminsky @juliushaertl 

E.g. 3rd party libraries used by nextcloud/text:
https://github.com/ProseMirror/prosemirror-view/blob/d8c4bb1c238d814359a345e576fdfcaaa17aabd2/src/browser.js
https://github.com/ueberdosis/tiptap/blob/e07a5b625d90c77fc5820e5eefa093d3cfb96512/packages/core/src/utilities/isiOS.ts

### Logs

JS Text logs using a WKWebView, attempting to paste an image:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) - http://localhost:8080/s/%7Btoken%7D/download?files=blob%3Ahttp%3A%2F%2F[...]
```

### Environment data

**iOS version:** e.g. iOS 15.4

**Nextcloud iOS app version:** `develop` branch

**Nextcloud version:** 24.0.0RC1

**Comment by tobiasKaminsky** [comment]
@juliushaertl do you see any problems with this?
As far as I know this direct editing web url is unauthenticated, so it is not needed to have a whitelisted user agent?

**Comment by juliushaertl** [comment]
From the direct editing perspective I don't see any reason to have a custom user agent at all.

**Comment by tobiasKaminsky** [comment]
But it would also not harm server side? E.g. csrf check, etc?

**Comment by juliushaertl** [comment]
I don't see a problem with that. We use some user agent checks but as far as I see only for backend checks on API requests, not any browser loading.

**Comment by juliushaertl** [comment]
Looks like the suggestion from above should still match the regex rules in https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/public/IRequest.php#L65-L88

**Comment by tobiasKaminsky** [comment]
@thisIsTheFoxe then go for it 👍

There seems nothing similar specific for Android…

**Comment by juliushaertl** [comment]
@tobiasKaminsky Do you have an example how the Android user agent look like in total?

**Comment by thisIsTheFoxe** [comment]
@tobiasKaminsky 👍 I assume we go with proposal 1, since the additional user agents wouldn't be necessary for any other request apart from Text (e.g. API / Collabora)..?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Do you have an example how the Android user agent look like in total?

Mozilla/5.0 (Android) Nextcloud-android/3.20

**Comment by juliushaertl** [comment]
Then it still doesn't match the expected ones from the javascript library which assume a digit after the "Android" https://github.com/ProseMirror/prosemirror-view/blob/d8c4bb1c238d814359a345e576fdfcaaa17aabd2/src/browser.js#L20 which is a bit bad because with adjusting that it would not fit our server regexes anymore.

Do you have a code pointer so that we could maybe build an APK for testing if any of the known mobile issues on android may get fixed by that?

**Comment by tobiasKaminsky** [comment]
I can build a test version with any user agent.
I can also do this just for text/direct editing.

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/pull/10148

QA system will build an APK, which you then can test.
If you want, you can also change the user agent in the PR and after ~10min you have a new APK for testing.
