### ISSUE TITLE
Allow user to change target folder for "Automatic upload"

### ISSUE THREAD

**Issue by togglecode** [nextcloud/ios#197]
The title says it all, it would be great if the user could pick other folders than just "Photos" for Automatic upload.

**Comment by rakekniven** [comment]
AFAIK that has been possible in previous versions. Am I wrong?

**Comment by togglecode** [comment]
hmmm as much as I remember, it was available only for normal upload and not auto upload, but I might be wrong :)

**Comment by tzapu** [comment]
i can confirm that at least in the latest version you can set folder for auto upload and it works.
detailed here https://help.nextcloud.com/t/change-folder-autoupload-uploads-to/8900/6

**Comment by rakekniven** [comment]
Hello @tzapu That was it. Thank you for linking forum topic.
@togglecode Is your issue solved? If yes please close it.

**Comment by togglecode** [comment]
sorry for the delay, but yes this solved my issue.
