### ISSUE TITLE
Login via SSO/SAML doesn’t create app token

### ISSUE THREAD

**Issue by stsp1** [nextcloud/ios#1984]
I‘m using the SSO & SAML app in Nextcloud and authenticate via Azure AD. When I type in the server the Microsoft login page is correctly shown, but after logging in I just see my Nextcloud as a mobile website in a webview. It still shows the back button in the top left, so the only option is to go back to the server select screen. It seems no app token is created so the app doesn’t connect.

The app can be connected via an app password, but this is not optimal since it allows users to circumvent login restrictions (conditional access). 

Server version 23.0.2
SSO & SAML authentication app 5.0.0

**Comment by idominiki** [comment]
Hello,

we also have this problem with our UCS System and Nextcloud iOS App. This bug exists also in the actual TestFlight Beta Version. 

Please look into this problem, its very frustrating for our teachers.

Thanks and Greets
Dominik

**Comment by tgurr** [comment]
For anyone wondering, the problem has been in the SSO & SAML authentication (user_saml) Nextcloud App and has been fixed with the latest update to version 5.0.1: https://github.com/nextcloud/user_saml/releases/tag/v5.0.1
