### ISSUE TITLE
Play full-screen presentation in NC app with Collabora Online / Nextcloud Office

### ISSUE THREAD

**Issue by thebearon** [nextcloud/ios#1998]
With Collabora Online / Nextcloud Office installed on Nextcloud, open an ODP/PPTX presentation, and tap the play button on the top toolbar, which should launch a full-screen presentation.

-> There is a download popup instead (COOL prepares an SVG from the presentation, which the webview should display, probably that's what's downloaded instead).

Tested with:
iPhone (iOS 15.4.1),
Collabora Online 22.05 development build,
Nextcloud 24.0.0,
Nextcloud app 4.3.1.

Some work has been done on this in August, 2020, but not sure if ideas/patches from the time got into the official Nextcloud app.

CC @marinofaggiana and @mmeeks for comments.

Sidenote: not sure if there's an established way of quitting the slideshow, in the Collabora Office app (local editor version of Collabora Online for iOS), swipe up / swipe down are used as gestures to trigger that.

**Comment by juliushaertl** [comment]
Seems only the downloadas post message is handled:
https://github.com/nextcloud/ios/blob/master/iOSClient/Viewer/NCViewerRichdocument/NCViewerRichdocument.swift#L189

There was a related fix on the android side but nothing I can find about iOS:
https://github.com/nextcloud/android/pull/5557

**Comment by juliushaertl** [comment]
Reference as this seems to have been broken again, should now be fixed with https://github.com/nextcloud/ios/pull/2356
