### ISSUE TITLE
Increase visibility of File actions

### ISSUE THREAD

**Issue by gillisig** [nextcloud/ios#20]
Currently to access the actions for a file or a folder you have to swipe left. At first you see a red "Delete" button and then once you swipe a bit further you see a grey "More" button. 

I was in trouble finding these "More" actions for a long while because:

- When I swiped left I saw a red "Delete" so I stopped swiping left since on some apps with a similar functionality swiping further and letting go will actually delete the file. 

![2016-12-20 13-32-13 0682](https://cloud.githubusercontent.com/assets/5390864/21352646/5d541278-c6ba-11e6-83d8-f7ff24b05f48.png)

- When I swiped right it did nothing

- When I pressed for a long time it did nothing. 

So as a result I thought the app was just lacking all the extra functionalities. It wasn't until much later that I actually found the "More" button.

![2016-12-20 13-33-27 0683](https://cloud.githubusercontent.com/assets/5390864/21352647/5d57ac76-c6ba-11e6-91f2-4b7156970690.png)

I suggest to improve this by either making swipe right reveal the "More". Or making a long press go straight into that function. Or both. 

Cheers!

**Comment by jancborchardt** [comment]
@nextcloud/ios @marinofaggiana please check out how the Apple Mail app does it: They don’t reveal the actions from one side, but have them all start with a very small width and expand all of them equally. That way you see from the beginning that there are multiple actions.

We should do it like that for sure. :)


Also @gillisig great to see you in here! Keep the good feedback coming :tada:

**Comment by enoch85** [comment]
@gillisig This is fixed now right? Please check the latest version and close if it is. Thanks!

**Comment by jancborchardt** [comment]
Yep, this is fixed and done as per usual Apple Mail working. :)
