### ISSUE TITLE
german translation wrong?

### ISSUE THREAD

**Issue by jones1008** [nextcloud/ios#201]
In the "settings - advanced" part there is a checkbox called "Dateien nach dem Hochladen entfernen".

The explanation for that is kinda confusing (see screenshot):
<img src="https://cloud.githubusercontent.com/assets/25104859/25440585/299eea6c-2aa0-11e7-8c6a-14730af0273d.png" width=300>

Can you please explain what this checkbox means or improve that translation?

Regards
jones1008

**Comment by rakekniven** [comment]
Hallo,
Dein Gerät hat einen lokalen Speicher der App und den Kameraspeicher (Apple App Fotos zeigt den Inhalt).
Bei aktivierter Option werden Bilder in die Cloud hochgeladen und verbleiben im Kameraspeicher aber nicht im Nextcloud App Speicher. Möchte man Bilder von der Cloud betrachten, so muss man diese erst wieder herunterladen.
Bei deaktivierter Funktion bleiben die Bilder nach dem Hochladen ebenfalls im lokalen App-Speicher.

Der englische Ursprungstext:
_"Files will be removed from _brand_ memory after they’ve been uploaded to the Cloud. They will remain in the camera roll. Just download the files to see them."_

Du kannst gerne einen Vorschlag für verbesserten Text beisteuern.

**Comment by rakekniven** [comment]
Du kannst diese Art von Anliegen gerne im Forum anbringen oder direkt auf Transifex, dort werden die Übersetzungen vorgenommen und es kann auch diskutiert werden.
