### ISSUE TITLE
Move/copy dialog: bottom item hidden

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/ios#2016]
### Steps to reproduce

1. Click the … button on a file
2. Click *Move or copy files*
3. The destination chooser dialog comes up
4. Navigate to a folder with many folders

### Expected behaviour

The entire content of the scrollview is visible.

### Actual behaviour

The bottom of the scrollview is cut off, since it goes behind the buttons.

In the list view, the bottom row is hidden. In grid view, the bottom labels are hidden. In both views the "n folders" label is hidden.

Since iOS has this overscroll behaviour, if you scroll really hard they become visible. But ofc it snaps back into hiding once you release it.

### Screenshots

<img width="75%" alt="nextcloud-move-hidden-item" src="https://user-images.githubusercontent.com/33295590/169315351-3645ceb5-4d30-4d3c-b113-9b93d0dec6d2.png">

<img width="75%" alt="nextcloud-move-hidden-item-2" src="https://user-images.githubusercontent.com/33295590/169315360-ca7a37f1-9cc4-4445-918a-90be996f0436.png">

### Logs

n/a

### Reasoning or why should it be changed/implemented?

It's a bug.

### Environment data

**iOS version:** iPadOS 15.5

**Nextcloud iOS app version:** 4.3.1.0

**Comment by marinofaggiana** [comment]
thanks @thgoebel
