### ISSUE TITLE
Add the option to choose between auto uploading photos in JPG and HEIC format

### ISSUE THREAD

**Issue by S0ulf3re** [nextcloud/ios#2031]
Right now, the Nextcloud app provides you with the ability to automatically upload your camera roll. But it always uploads your photos in JPG format, with no option to turn this off. I would like my photos to auto upload in the format they currently are taken as, which is most efficient (HEIC), I live fully within the apple ecosystem which makes the need to convert my photos into jpeg unnecessary.

**Comment by Norjek** [comment]
Under Settings > Advanced you can choose to safe Photos "Most Compatible". This will attempt to save them in JPG, if possible, all the time. According to it's description, at least.
I assume, you have turned this on. Have you tried to turn it off?

**Comment by S0ulf3re** [comment]
Well now I have
