### ISSUE TITLE
Nextcloud loses login session on WiFi with captive portal

### ISSUE THREAD

**Issue by majewsky** [nextcloud/ios#2036]
### Steps to reproduce

1. Be logged into Nextcloud on the app.
2. Connect to a public WiFi with captive portal.
3. Do not immediately go through the captive portal to login. (In my case, I was not using the phone and had not noticed it entering the WiFi.)
4. Open and interact with a different app that does not need internet access (in my case, I just retrieved a TOTP token from an Authenticator app).

### Expected behaviour

When the Nextcloud app tries to connect to the server and sees the captive portal instead, it should retry later.

### Actual behaviour

While using the Authenticator app, I got an error about an incorrect TLS certificate from the Nextcloud app because access to `https://<my-nextcloud-server>` returned the captive portal's TLS cert instead.

After that, I found out that the Nextcloud app had logged me out entirely. Therefore, as far as I can see, I also lost all downloaded files and all sync settings.

### Screenshots

I forgot to capture a screenshot at the time.

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Reasoning or why should it be changed/implemented?

Losing the entire login session because of this momentary disturbance in internet is quite frustrating for me as a user. The app should ignore failed connections like this at least for a short amount of time (e.g. a couple hours).

### Environment data

**iOS version:** 15.5

**Nextcloud iOS app version:** 4.4.0.18

**Server operating system:** NixOS 21.11

**Web server:** nginx

**Database:** PostgreSQL

**PHP version:** I cannot log onto the server to check right now. If this turns out to be relevant (which I don't think it is), let me know.

**Nextcloud version:** 23.0.5

**Comment by bencomp** [comment]
This looks related to #2033

**Comment by majewsky** [comment]
Yes, that's the same. I'll close this to deduplicate.
