### ISSUE TITLE
App does not generate previews for RAW images

### ISSUE THREAD

**Issue by charles-997** [nextcloud/ios#2049]
### Steps to reproduce

1. Save a .ARW or .DNG file in your Nextcloud files
2. Open this image in the Nextcloud app on iPhone
3. No thumbnail/preview/image appears- only a generic icon of a photograph appears.

### Expected behaviour

A preview/thumbnail/image should appear.

### Actual behaviour

Nextcloud does not show the image.

### Screenshots

![image](https://user-images.githubusercontent.com/52077853/176256648-760f36f8-15cd-4ddf-a2db-5fe4ebcbae22.png)

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```
I'm not sure which logs would be applicable, please let me know and I can add.

### Reasoning or why should it be changed/implemented?
I think viewing images is a reasonable expectation of software that is at Nextcloud's development stage.

### Environment data

**iOS version:** iOS 15.5

**Nextcloud iOS app version:** see More > Settings  Nextcloud IOS 4.4.0.18

**Server operating system:** Nextcloud in Docker

**Web server:** Nextcloud in Docker

**Database:** MariaDB 10.5 via Docker

**PHP version:** Nextcloud in Docker

**Nextcloud version:**  Nextcloud 24.0.2

**Comment by bencomp** [comment]
Perhaps the RAW preview app needs to be installed on the Nextcloud server for this to work, as it appears that the server is responsible for generating thumbnails and previews.
