### ISSUE TITLE
"Download files" button doesn't work on a folder

### ISSUE THREAD

**Issue by delitestudio** [nextcloud/ios#205]
Hello,

here are the steps to reproduce the problem:

1. Tap the three dots button
2. Choose "Select"
3. Select a folder (e.g. Documents)
4. Tap again the three dots button
5. Choose "Download files"

An activity indicator appears for a very short time, but nothing is downloaded.

**Comment by marinofaggiana** [comment]
Hi @delitestudio  Folder is not a "File", this download only selected "**files**" ... whats do you think ?

**Comment by delitestudio** [comment]
Hello Marino! First of all thanks for your answer.

Intuitively I would think that downloading a folder is equivalent to downloading its contents (recursively). The Android app for example behaves this way...

**Comment by marinofaggiana** [comment]
Yes ! sure ! it's possible :-)

**Comment by delitestudio** [comment]
Oh, that would be great, thanks :)

**Comment by enoch85** [comment]
@delitestudio Is this fixed? Please close fixed issues, thank you!
