### ISSUE TITLE
Login - User gets locked out after changing password

### ISSUE THREAD

**Issue by togglecode** [nextcloud/ios#206]
Hello,
I have the following issue and I am not sure if this happens only on my server. 

so the scenario is like this:

1. A user changes password
2. User opens the app
3. The app sends some requests to the server, gets error 401 and logs the user out

But, sometimes the App sends **too many requests** before it forces the user to logout. This causes the user to get completely locked out (because the brute force count get's too high on the server side).

As you can see in the following picture, the app get's seven 401 errors from different requests before it logs out the user which completely locked my user and I could not login with my new password. Any suggestions?

![bug2](https://cloud.githubusercontent.com/assets/17141698/25533070/a787456a-2c2f-11e7-8cbf-7116149387e7.png)

**Comment by togglecode** [comment]
Server version 11.0.1.2
App version 2.17.2(2)

**Comment by marinofaggiana** [comment]
It's normal, when the app go back active send the requests (NON serialized) for update status and view. (why too many request ?)

**Comment by togglecode** [comment]
@marinofaggiana but this causes my user to get locked out because the brutforce count get's more than 3 times and the user cannot login into the app anymore... is there anyway I can change this?

**Comment by marinofaggiana** [comment]
This is not a Nextcloud iOS issue. sorry. new version beta improves the request, but this is not an issue.
