### ISSUE TITLE
E2E mnemonic/passphare: make it copy-able

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#2072]
### Steps to reproduce

1. setup E2E
2.retrieve passphrase
3. cannot copy it to clipboard

### Expected behaviour

Being able to copy passphrase.

### Actual behaviour

Manually type it.

**Comment by marinofaggiana** [comment]
/Users/marinofaggiana/Desktop/Simulator Screen Shot - iPhone 13 - 2022-07-13 at 15.02.27.png
