### ISSUE TITLE
Double tap on document view does not close the file list

### ISSUE THREAD

**Issue by adityamj** [nextcloud/ios#208]
App version: 2.17.2 beta

When double tapping on a document shown on the right hand side of the screen, the file list is not closed and document is zoomed. Attaching screenshots. The document section needs to be expanded by tapping the expand button on the top.

![photo-2017-04-29-12-08-57_0014](https://cloud.githubusercontent.com/assets/6848434/25553595/34aa75b6-2cd5-11e7-8b11-f19643ea16ab.PNG)
![photo-2017-04-29-12-08-48_0013](https://cloud.githubusercontent.com/assets/6848434/25553596/34afdd26-2cd5-11e7-9eda-03bcffe1c812.PNG)

**Comment by rakekniven** [comment]
Not sure if your issue is a general rule.
Is it common to show images fullscreen after double tap in other apps?

**Comment by adityamj** [comment]
I am new to iOS so might be wrong there; Photos go full screen on single tap, Pdf readers usually go full screen on single tap. Email goes full screen on single tap. So I think there is an expectation when the user taps for the view to go full screen.

**Comment by adityamj** [comment]
Following is the behaviour of different apps:

Photos app: Full screen on single tap
Google drive: Full screen on single tap, opens opens google docs if installed and file is a document.
One drive: Full screen on single tap for all files
Owncloud: Full screen on single tap for all files
Email: email goes full screen, hides email list
Email attachment: Opens in full screen

In the first post I mentioned only photos however the behaviour is same with PDFs as well.
