### ISSUE TITLE
Testflight 2.17.2 - App closes after 5-10 seconds

### ISSUE THREAD

**Issue by derkostka** [nextcloud/ios#209]
I just updated from the (very perfectly working) 2.17 to the new Beta.

What i noticed is: The skin color changed and matches my NC-Setting now. But, the app is not usable anymore, it closes without any message after 5-10 seconds, no matter what i navigate to.

I see that the amount of pending uploads changed, then, after some time, is closes.

Now to help: How can i gather a logfile or someting that might be of interest ?

Thanks!

**Comment by marinofaggiana** [comment]
Hi @derkostka if you create a new account crashes ad well ? Thanks

**Comment by derkostka** [comment]
I have reset the app. It works now, i receive a lot of timeouts which have not been there before but the app does not close unexpectedly.

Shall i remove the app, install the app store version and try to reproduce the whole thing or do have an idea already ?

**Comment by marinofaggiana** [comment]
Timeout ? please make a god setting on your Server ;)

**Comment by derkostka** [comment]
Okay, the timeout problem is solved. I changed the app password and banned myself as brute-force protection kicked in :-)

Back to the topic: I could not reproduce the issue. I installed the App Store version, played a bit with it and updated then to the latest test flight. No problems !

-> I will close this, we may re-open in case that anybody else has this issue. One final question: Do you plan to add some kind of connection or crashlog, so that one is able to find out the root cause for issues of that kind ?
