### ISSUE TITLE
Allow creation of non-encrypted notes

### ISSUE THREAD

**Issue by jamieadamsuk** [nextcloud/ios#21]
The app currently allows us to create and modify encrypted notes, but these can only be edited or viewed on the device.

It would be useful if the application would allow the creation, and modification, of non-encrypted notes too - which could then be manipulated on other synced devices.

I use the iOS app every day and find it a pleasure to use. My thanks go out to those who contribute to this project.

**Comment by marinofaggiana** [comment]
Yes @iamjamieadams thanks !! this feature it's in to-do list :bowtie:

**Comment by rakekniven** [comment]
Workaround for all iOS app users until this feature is available:

Use the app https://github.com/owncloud/notes-iOS-App . App is specially made for managing and editing notes.

**Comment by cal940** [comment]
> Use the app https://github.com/owncloud/notes-iOS-App . App is specially made for managing and editing notes.

Yes, but there is no possibility to share these notes with other nextcloud users or via link.

**Comment by rakekniven** [comment]
Notes are stored as plain text files inside your nextcloud. You can share them like any other item in your cloud.

**Comment by johkoenig** [comment]
v3.0.14 (and most certainly some earlier versions) has an integrated markdown editor.
