### ISSUE TITLE
Cache not celaring

### ISSUE THREAD

**Issue by krisj** [nextcloud/ios#211]
ios 8.4 nextcloud 2.17.1

Just tried uploading a few video from the library. For example a 480MB large MOV. It uploads quickly but stays in the phone cache somewhere taking up extra 480 MB space and the only way I can clear it by deleting the Nextcloud app - this is a big problem. If I have to upload a 500MB file and phone only has 300MB available - it wouldn't work? Is there a workaround or a fix? Or at least a warning?

thanks

**Comment by enoch85** [comment]
@krisj Is this still the case? Now you can clear cache at least. Please close this issue if this is fixed.
