### ISSUE TITLE
Manual photo/video upload not working

### ISSUE THREAD

**Issue by krisj** [nextcloud/ios#212]
ios8.4 nextcloud. 2.17.1

manual upload via "+" end us in this on sever logs:
`Fatal	webdav	OCA\DAV\Connector\Sabre\Exception\FileLocked: HTTP/1.1 423 "Photos" is locked`

and in iOS app Activity log:
`Automatic Upload: https://ourserver.net/remote.php/webdav/Photos
Folder could not be created`

Notice - I never selected "Photos" folder anywhere! I am selecting a custom folder.

It does work perfectly fine if I am uploading the same files to the same folder using the iOS share file > Nextcloud functionality.

**Comment by gbiggs** [comment]
Possibly related to #107

**Comment by enoch85** [comment]
Is this fixed?
