### ISSUE TITLE
Media detail view

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#2121]
To improve the media detail view with new data and a different animation.

![Simulator Screen Shot - iPhone 13 - 2022-08-17 at 16 07 57](https://user-images.githubusercontent.com/8616947/185155389-dccfe809-f020-41f4-878b-498497f88b8b.png)

**Comment by InsanelyHarsh** [comment]
I would like to take this task, can you make me go through the workflow?

**Comment by tobiasKaminsky** [comment]
- show all info known by server, e.g. ratio, meta data
- show other data, which are known by client
- show it on map

**Comment by mpivchev** [comment]
Are there some designs for this? @tobiasKaminsky 

This is the screen currently:

![image](https://github.com/nextcloud/ios/assets/6960329/532efd89-c183-4da0-a306-3ff5aa3e85c2)

Since we have 2 tabs that take the whole screen, not sure where I can make space for a map etc.

**Comment by mpivchev** [comment]
@tobiasKaminsky @marinofaggiana 

Can I get some more info on this? 
Besides the additional data that can be added, what new animation do we need?

**Comment by jancborchardt** [comment]
So @mpivchev and I talked about this:
- The view is going to be adjusted to look like it is in iOS Photos, for familiarity
- To improve discoverability of that viewnot only by swiping up, next to the 3-dot menu there will be a new icon for photos
