### ISSUE TITLE
Version 4.4.1 completely breaks search

### ISSUE THREAD

**Issue by jacotec** [nextcloud/ios#2125]
### Steps to reproduce

After updating from 4.4.0 to 4.4.1 the search did fully break on all IOS devices. Users are complaining. Search does find nothing at all, not even filenames.

### Expected behaviour

Search, as one of the most important function, needs to work. We did even expect a massive improvement due to the announced unified search support, instead all users are forced to use the web browser now.

### Actual behaviour

Search is completely broken and does not find anything.

### Screenshots

If applicable, add a screenshot showing the issue.

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Environment data

**iOS version:** e.g. iOS 14.4.1

15.6

**Nextcloud iOS app version:** see More > Settings

4.4.1

**Server operating system:**

Ubuntu 20.04

**Web server:** Apache, nginx

Apache

**Database:**

MariaDB

**PHP version:**

8.1.8

**Nextcloud version:** see Nextcloud admin page

24.0.4

**Comment by marinofaggiana** [comment]
Hi @jacotec the 4.4.1 use the unified search automatically included in your 24.0.4; please check your server log.

**Comment by jacotec** [comment]
Hi @marinofaggiana ,
nope, that does not produce any entries in the server log, even not when I go down to debug log level. So there is nothing weird happening on the server.
Also the unified search on the server itself (NC web interface) works perfect.

I have the same issue on 3 different NC servers. None of them is producing server entries in the NC log when searching, and all are behaving correct when searching via web browser.

I think there's an issue with the app ...

**Comment by jacotec** [comment]
@marinofaggiana I've sent you an email to your ios@... address with a link to a full app log (highest log level) when I did a search. Including a screenshot of the web interface with all the results for the same search.

I dod not want to post the full log with all the URLs, filenames etc. in public.

**Comment by marinofaggiana** [comment]
@jacotec https://testflight.apple.com/join/RXEJbWj9
V 4.4.2 fixed.
