### ISSUE TITLE
Latest update broke usernames containing a plus

### ISSUE THREAD

**Issue by csware** [nextcloud/ios#2128]
### Steps to reproduce

1. Have an old username containing a + sign
2. Update iOS app
3.  Open the iOS app

### Expected behaviour

The iOS app works as before the update and I can access the files on the nextcloud instance.

### Actual behaviour

The iOS app tells me that I need to relogin because the password is wrong.

The path name is double encoded and the username is decoded.
(when I add a new account in the app, the visible username contains a space instead of the plus sign)
(when the server is queried, the plus is encoded as %2b instead of a plus as with old versions.

### Logs

```
"PUT /remote.php/dav/files/username%2Bowncloud@domain.de/exchange/FILENAME HTTP/1.1"
```

The nextcloud desktop version works like a charm and uses the right webdav URIs:
```
"PROPFIND /remote.php/dav/files/username+owncloud@domain.de/exchange HTTP/1.1"
```

### Environment data

**iOS version:** 16.1

**Nextcloud iOS app version:** see More > Settings latest, cannot access

**Server operating system:** Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud version:** 24.0.4

**Comment by marinofaggiana** [comment]
Hi, https://docs.nextcloud.com/server/19/admin_manual/configuration_user/user_configuration.html

>  Login names may contain letters (a-z, A-Z), numbers (0-9), dashes (-), underscores (_), periods (.) and at signs (@).

**Comment by csware** [comment]
For historic reasons I still have such a username (was possible owncloud and upgraded to nextcloud)....
