### ISSUE TITLE
Ios document picker does not save files

### ISSUE THREAD

**Issue by zigulle** [nextcloud/ios#213]
Hello,

every time I use the new document picker in an other app, all changes were not saved after I closed the document.
This behaviour is reproducable with textastic and word for ios. 
Opening a document with the document picker is no problem.
Creating a new document and save it with the document picker results in an emty document.

Saving the document picker with the app "Trasnmit" (nextcloud as a webdav server configured) is no problem.

There are no entries related to this behaviour in the server logs.

Greetings,
Daniel

Server: nextcloud 11.0.3
Client: iOS client (Nextlcoud vor iOS) 2.17.1.00001

**Comment by si458** [comment]
Hi
I also have this issue but with Microsoft Word,Excel,etc...
I Create a document then save to places, select nextcloud then save here and it just uploads a blank document with 0kb of data???
Simom

**Comment by vomout** [comment]
I open a PDF in Foxit Reader through the document picker, and annotated it. It was not updated on nextCloud.

**Comment by andrewperry** [comment]
I am really surprised that this fundamental issue hasn't received any attention in 2 years! It seems more important than pretty much any potential new feature - there's nothing worse than thinking you've saved a file to Nextcloud to then only find it is empty when you actually go to open it on another device (and at a later time on the source device). Am I missing that there's some work around that makes this not a priority?
