### ISSUE TITLE
Even disable "Most Compatible", Live photo still converted to picture and video then uploaded.

### ISSUE THREAD

**Issue by Halry** [nextcloud/ios#2132]
### Steps to reproduce

1. enable auto upload in settings
2. Disable "Most compatible" and left "Live photo" enabled.
3. take a "live" photo then waiting for upload

### Expected behaviour

Tell us what should happen.

Photo should uploaded as *.heic and with video inside *.heic file.

### Actual behaviour

Tell was what instead happens.

Photo is divided into *.heic and *.mov, and no video inside *.heic file.

### Screenshots

If applicable, add a screenshot showing the issue.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/5312805/186101876-edb62ef2-e756-4fef-bebf-07054d548e9a.png">

![image](https://user-images.githubusercontent.com/5312805/186102132-955f6a4e-5e33-43ff-af30-debbebd20efe.png)

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Reasoning or why should it be changed/implemented?

Live photo should be saved as one file, however now has been split.

### Environment data

**iOS version:** e.g. iOS 14.4.1
15.6.1
**Nextcloud iOS app version:** see More > Settings
4.4.2.0
**Server operating system:**
CentOS Stream 8
**Web server:** Apache, nginx
nginx
**Database:**
PostgreSQL
**PHP version:**
8.1.9
**Nextcloud version:** see Nextcloud admin page
24.0.4

**Comment by Halry** [comment]
Has been updated to iOS16, Nextcloud Server 24.0.5 and Nextcloud iOS 4.4.4.0. Problem still exist.

**Comment by Hyoengju-Johannes-Lee** [comment]
@Halry Most Compatiable has nothing to do with the live photo, and it is about whether the picture would be jpeg or heic.

And, live photos are always a combination of .heic + .mov files.
It is not possible to have one file that can contain a picture and a video.
But, the ios app has a functionality that makes two files look like one.

So, if you want to see the two files as one, then I think you should close this issue and open in nextcloud/nextcloud, not here.!

**Comment by Halry** [comment]
Oh, thanks. I was made a mistake that take the play button in nextcloud as play the video inside the heic. It actually is the play the slideshows.
