### ISSUE TITLE
Mirror of Nextcloud Web Application to IOS/Android

### ISSUE THREAD

**Issue by Pavithra-S1** [nextcloud/ios#2133]
Hello,

I need a solution for Nextcloud Web application of all apps in single bundled Mobile application for IOS & Android.

Nextcloud has separate applications for Files, Talk, Deck etc.. I want all those applications in a single application how can we make this solution workaround.

1) Is there any possibility to get a single bundled application of Nextcloud
2) Can we convert it as a hybrid mobile app from Web
3) How we can build a native apps which is clubbed together of Nextcloud

**Comment by marinofaggiana** [comment]
Argument not possible.

**Comment by Pavithra-S1** [comment]
why it is not possible ?
