### ISSUE TITLE
4.4.x: Search not working when word with Umlauts is in the search term

### ISSUE THREAD

**Issue by jacotec** [nextcloud/ios#2135]
### Steps to reproduce

1. Search for a word which contains a German Umlaut (äüö...)

### Expected behaviour

The search should return the results

### Actual behaviour

The search never returns any result

### Reasoning or why should it be changed/implemented?

It breaks search for some German words (and probably special characters in other languages as well)

### Environment data

**iOS version:** e.g. iOS 14.4.1

15.6.1

**Nextcloud iOS app version:** see More > Settings

4.4.2.0

**Server operating system:**

Ubuntu 20.04 LTS

**Web server:** Apache, nginx

Apache

**Database:**

MariaDB

**PHP version:**

8.0

**Nextcloud version:** see Nextcloud admin page

24.0.4

**Comment by marinofaggiana** [comment]
Fixed V 4.4.3
