### ISSUE TITLE
Stop resetting auto upload configurations

### ISSUE THREAD

**Issue by stratacast** [nextcloud/ios#2144]
### Steps to reproduce

1. Update the app, or do nothing at all

### Expected behaviour

User defined configurations never change. Or if they do, the user is notified.

### Actual behaviour

The app silently resets auto upload configurations or changes them.

### Reasoning or why should it be changed/implemented?

You may go quite some time without realizing photos aren't synchronizing with the server or going to the wrong place. When setting configurations again you may miss a step and now photos are in all the wrong places. This is frustrating if you are managing users and they are unaware or unable to comprehend or reset auto upload settings. Then new uploads either don't happen or are in the wrong places and any new uploads in the wrong places have to be reorganized by hand.

### Environment data

**iOS version:** 15.6.1

**Nextcloud iOS app version:** 4.4.2

**Server operating system:** FreeBSD 13.1-RELEASE

**Web server:** nginx

**Database:** PostgreSQL

**PHP version:** 8

**Nextcloud version:** 24.0.4

**Comment by marinofaggiana** [comment]
V. 4.4 : Due to a change in the Nextcloud application identifier (Apple application ID), the settings and password for accessing your cloud are reset, so please re-enter your account data and check your Settings. We are sorry about that.
