### ISSUE TITLE
Background fetch/processing notes

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/ios#2158]
Hello Marino,

I was looking through the code and noticed a few things regarding background fetch/processing.

* Background fetch and processing are correctly scheduled after the app enters the background ([here](https://github.com/nextcloud/ios/blob/785041f03cbbc0c015eee227b6b3cf344440d84d/iOSClient/AppDelegate.swift#L299-L302)). The problem is, they are never scheduled again in the corresponding `handleRefreshTaks` / `handleProcessingTask` methods, therefore only executing once after the app moved to the background, but not continuously (see the example at the bottom of [this page](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app)). 
So basically in `handleRefreshTask` there should be a call to `scheduleAppRefresh` and in `handleProcessingTask` there should be a call to `scheduleBackgroundProcessing` at the beginning of the method.
It's not a problem if a task is submitted before the previous was executed, according [to the docs](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler/3142252-submit): 
   > Submitting a task request for an unexecuted task that’s already in the queue replaces the previous task request.

* Background processing is intedend for [time-consuming tasks](https://developer.apple.com/documentation/backgroundtasks/bgprocessingtask). I'm wondering if that that would work better for auto upload in contrast to app refresh? I'm not sure, maybe app refresh + url session background uploading is enough, but my first thought was to flip app refresh and processing task around.

* I'm not quite sure I get the purpose of your dispatches. In `handleProcessingTasks` it looks like you want to kill the task after 25 seconds (although a processing task can run for several minutes). In `handleAppRefresh` there are additional 5 seconds after auto upload finished, before the task is completed (although here you only get 30s max). 
In the first case a completionHandler for `synchronizeOffline` would be better I guess, then one can wait for both tasks to complete and then call the completion handler. 
In the second case I'm not quite sure what the intention here is, but it might make sense to implement a expirationHandler instead (maybe even in both cases) as seen again [in this example](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app)

**Comment by marinofaggiana** [comment]
Hi @SystemKeeper welcome !!
Yes, I realized that something still wasn't working properly, I promised myself to review it for the next 4.5.
Thanks for you consideration !

For the asyncAfter timing this exists because I don't know when are concluded  the process for calling the setTaskCompleted, now I have already modified the initAutoUpload so when return the completion has effective concluse the process but not yet for the synchronizeOffline. 

Always feel free to propose a PR !! \o/
