### ISSUE TITLE
Connection Warning

### ISSUE THREAD

**Issue by maege** [nextcloud/ios#216]
Dear all,

First of all. Thanks for the fantastic app!

We have the following use case for your app:
We have several product catalogs in our Nextcloud and wan't this catalogs on several iPads. We marked the Folders as Favorites to have a local copy of the catalog. We don't have a internet connection anytime. The sync works perfectly!

We receive the following warning when we have no internet connection:
![image](https://cloud.githubusercontent.com/assets/25299891/25651516/cd5671dc-2fe3-11e7-9c49-8536589cddc6.png)

This is normaly not a Problem, but we don't want that out customer see the the error message when we pressenting our catalogs.
Is it posible for you to integrate a config option to disable this warning screen in the settings?

Thank you! :-)

**Comment by marinofaggiana** [comment]
Hi @maege, yes this issue is already in to-do list for the next version. thanks for your question

**Comment by enoch85** [comment]
This should be fixed, please reopen otherwise. Thanks!
