### ISSUE TITLE
Remove cached files within a folder

### ISSUE THREAD

**Issue by mind22** [nextcloud/ios#217]
Would be helpful to integrate this option in the "More"-Tab of folders or under properties where you could do this by selecting through a folder structure. Now it is a little bit cumbersome to clear every file to gain some space if you don't want to remove all cached ones.

**Comment by veddox** [comment]
This would still be a very useful thing to have! Trying to clear some storage space, I found myself going through three months' worth of pictures, manually removing every single one from the cache (that's three taps per picture...). Would be great to be able to do this in one fell swoop.
