### ISSUE TITLE
QR code login not working

### ISSUE THREAD

**Issue by redm123** [nextcloud/ios#2174]
### Steps to reproduce

1. Open NC app
2. go to App-Token login (?)
3. I should see something to scan an QR code...

### Expected behaviour

I'm under the impression that I can scan a QR code instead of entering the lengthy device password. There should somewhere be an option to activate the camera and scan the code.

### Actual behaviour

I don't see any possibility to scan a QR code. All I can do is to enter text, either password or "App-Token".

Ok, it already starts with that I have no idea what that "App-Token" thing is. And the app does not explain it! Are that those device specific passwords with the QR code that I can generate in NC Security settings? If so, why is it not called the same? If not, then I have no idea what that should be and the app should give me a clue!

Anyway, there are those device specific passwords, that come with the QR code, so I don't have to type that password. (At least that's my guess again. Of course NC chooses not to tell me, what the QR code is for...). I should be able to scan that code...

Background:

In case it matters, I transferred my apps and data to a new iPhone. I started the NC app and it told me that I have to reregister or something like that (I don't quite remember anymore). Then it opens the server and asks me to login.

### Reasoning or why should it be changed/implemented?

Because it is so tremendously confusing, buggy and user unfriendly! This whole password/login handling in the app and NC in general, FWIW.

### Environment data

**iOS version:** iOS 15.6.1

**Nextcloud iOS app version:** 4.4.4 (I think ...)

**Server operating system:** Linux

**Web server:** Apache, nginx

**Database:**

**PHP version:**

**Nextcloud version:** 22.2.3 (I think ...)

**Comment by marinofaggiana** [comment]
You must go in Nextcloud Server / Security at the end of Devices & sessions there is a Create new app password, insert a name (es. Test) and finally "Show QR code for mobile apps".

**Comment by redm123** [comment]
Erm, yes, that much I got...But I cannot use it! To quote myself: "I don't see any possibility to scan a QR code." For instance I would expect a button "Scan QR code", which activates the camera to scan the code. But I can't find any such thing.
