### ISSUE TITLE
App Switcher | Show live preview

### ISSUE THREAD

**Issue by HeyWatchOutDude** [nextcloud/ios#2190]
Hi,

when I open the "app switcher" (swipe from bottom up) on my iPhone to show all apps which are running in the background, the nextcloud app is changing to a "default" screen. Is it possible to add a live preview so I can get important information of my cloud data without actually entering the app? (Multitasking) 

![image](https://user-images.githubusercontent.com/61534143/194785239-674b406f-dcca-4fbc-ad60-1fd1c21e8f12.png)

https://developer.apple.com/design/human-interface-guidelines/patterns/multitasking/

**Comment by marinofaggiana** [comment]
hi @HeyWatchOutDude , what you mean for:  live preview so I can get **important information** ?

**Comment by HeyWatchOutDude** [comment]
Like shown in the screenshot, I want sometimes to check something quickly without actually entering the app. Example: I have a word file open and I'm checking a note or something like that.

**Comment by marinofaggiana** [comment]
![Simulator Screen Shot - iPhone 14 - 2022-10-15 at 11 21 20](https://user-images.githubusercontent.com/8616947/195979118-3bed4cb5-65ad-49ab-9bdb-62f136742b52.png)

**Comment by HeyWatchOutDude** [comment]
Is that new? Thanks, "issue" solved.

**Comment by marinofaggiana** [comment]
No, was already present.
