### ISSUE TITLE
Add option to only upload photos while charging 

### ISSUE THREAD

**Issue by thomascobb** [nextcloud/ios#22]
The Android app has it, and I'd love to see it on the ios app too!

**Comment by marinofaggiana** [comment]
hi @thomascobb "upload photos while charging" ? i don't know this feature ... you describe me thanks :raised_hands:

**Comment by thomascobb** [comment]
The Android app has an option "Upload while charging only". There is an upload queue of all new photos and videos that have been taken. If the option is ticked, then the upload queue is only processed while the device is plugged into it's charging cable. If the device is not connected to a charging cable then uploading is paused, and the item in the queue displays the status "Waiting for device charging...".

I enable this feature because I take lots of pictures at a time and I don't want them all uploaded to nextcloud before I've had a chance to sort through them. I generally do this in the evening before I charge my phone, so this allows me to delete all the blurry shots before they are uploaded overnight when the phone is on charge.

**Comment by thomascobb** [comment]
There are some screenshots here:

https://github.com/nextcloud/android/issues/300

**Comment by marinofaggiana** [comment]
ok @thomascobb sorry but in iOS is not possible, the queue in background is managed from iOS if lower battery of not in charging or low memory etc. etc. iOS suspend the transfer ...

**Comment by thomascobb** [comment]
Sorry, I don't think I made myself clear. At the moment, something is calling uploadAssetsNewAndFull:
https://github.com/nextcloud/ios/blob/master/iOSClient/PhotosCameraUpload/CCPhotosCameraUpload.m#L1088

This function seems to call uploadFullAssetsToNetwork on the main thread if a number of checks pass. One of the checks is if we are allowed to create the given folder name on nextcloud, if it fails then the upload is cancelled. I am imagining similar code that gets:

`UIDeviceBatteryState currentState = [UIDevice currentDevice].batteryState;`

And doesn't do the upload if the currentState is unplugged and the user has requested "Upload while charging only". I suspect you would have to do something like this to get notifications that we were plugged back in to trigger another uploadFullAssetsToNetwork:

```[[NSNotificationCenter defaultCenter] addObserver:self
                                         selector:@selector(batteryStateChanged:)
                                             name:UIDeviceBatteryStateDidChangeNotification object:nil];```

By the way, I have never done any programming for iOS, so this might be complete rubbish, but I did read this:

http://stackoverflow.com/a/33169943

**Comment by marinofaggiana** [comment]
Yes it's true but [UIDevice currentDevice].batteryState is only a call for know if is in charge o battery but the system NSURLSession do not use this status. 

Example : 
[DEVICE IN CHARGE] -> start upload file 
[CHANGE DEVICE ON BATTERY] -> stop ? ... if is in background mode not possible the queue is managed on iOS. in foreground mode i must stop all task-session .. oh my god !! too complicated ... 

iOS do not use charge for managed the session, manually is too costly

This is only my idea ... but if someone wants to try i am very happy !! 👍

**Comment by thomascobb** [comment]
Hmm, iOS is a very different world...

For me, it would be enough to suppress uploadAssetsNewAndFull if not charging, and trigger it when starting charging. I wouldn't mind if disconnecting the phone in the middle of an upload allowed the upload to continue...

**Comment by marinofaggiana** [comment]
> Hmm, iOS is a very different world...

I don't know Android 😄
