### ISSUE TITLE
4.5.0 app crashes when adding second server

### ISSUE THREAD

**Issue by thomasgg23** [nextcloud/ios#2202]
### Steps to reproduce

1. add first nextcloud server via qr code (app password), server is added correctly without error
2. add second nextcloud server via qr code (app password), server is added correctly without error
3. after 2 seconds app crashes
4. When opening the app again, after 2 seconds the app crashes again

### Expected behaviour

App didn't crash with stable version before.

### Actual behaviour

App crashes after adding the second server. And keeps crashing everytime opening the app again.

### Screenshots

none

### Logs

can't get the logs because the app crashes after 2 seconds.
Is there any other chance to get to the logs?

### Environment data

**iOS version:** e.g. iOS 16.0.3

**Nextcloud iOS app version:** 4.5 released 19.10.22

**Server operating system:** ubuntu 22.04 LTS

**Web server:** Apache

**Database:** mariadb

**PHP version:** 8.1

**Nextcloud version:** first server 24, second server 25

**Comment by marinofaggiana** [comment]
Hi follow this instruction 

![image](https://user-images.githubusercontent.com/8616947/196802100-7de24ea7-5b7e-4709-b0a8-47fe6f9e43d1.png)

**Comment by thomasgg23** [comment]
Thanks, found it.
Is it save to share the ips files to github?

**Comment by marinofaggiana** [comment]
Yes, do no contain private data.

**Comment by thomasgg23** [comment]
Debug File

**Comment by daCaPo** [comment]
Same problem here. This bug actually renders the client totally useless when you need access to multiple NC instances - hope this can be fixed quickly with an emergency update. Should I provide another debug log?

**Comment by marinofaggiana** [comment]
Soon a (hope) fix in TestFlight

**Comment by marinofaggiana** [comment]
@daCaPo use:

https://testflight.apple.com/join/RXEJbWj9

**Comment by thomasgg23** [comment]
Tested the testflight build which is version 4.5.0 (19) on my device. 
Problem the same.

**Comment by marinofaggiana** [comment]
No, must be 4.5.1 Build 0 - when available (under verify from apple)

**Comment by daCaPo** [comment]
4.5.1 fixes the problem for me

**Comment by thomasgg23** [comment]
Same for me with 4.5.1,
Thanks.

**Comment by thomasgg23** [comment]
Works also with 4.5.1 (build 2)
