### ISSUE TITLE
Issue: Captured Date in EXIF-Data is lost when saving a photo to camera roll

### ISSUE THREAD

**Issue by SirBuvex** [nextcloud/ios#2209]
When I open a photo with containing EXIF-data about the time when it was taken and swipe up, the right time and date is displayed 
![image](https://user-images.githubusercontent.com/68827249/197403616-bed0b3e9-f034-4ca6-b0e3-31c0c0d5e1df.jpeg)

But if I choose to save the image to my camera roll somehow this information gets stripped and the photo app sets the current time as creation date. 
When I download the image via my browser everything works as intended. Would be great if this could be fixed!

**Comment by ldavis9600** [comment]
I'm having the same issue myself

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/2243
