### ISSUE TITLE
Big video files can not be uploaded

### ISSUE THREAD

**Issue by uyelci** [nextcloud/ios#221]
I managed to increase max file size to 2GB on Server side. Using Raspbian and Nextcloud on it.
From client side, Nextcloud 2.17.2 on iPhone

It starts to upload all videos and photos. When it arrives to big files which is 16:22 mins, it couldnt continue. It gives error as "Uploading File / Read File Error"  and then stucks at that point, no other file uploading continues.

are there any way to split big files and upload by chunks=? If you have any big files on iOS, it doesnt sync.

I am looking alternatives to sync my photos/videos with my home systems. NextCloud is not going to be an option if I cant resolve the issue

**Comment by enoch85** [comment]
@uyelci It would be helpful if you could use the issue template and also show us the logs.

**Comment by enoch85** [comment]
@uyelci Can you test with the latest release? Does it work?

**Comment by danaivehr** [comment]
Hi!

I can confirm am issue on the latest ios app release. Seems like critical size is around 300-400 mb.

I can provide some useful data to you, if you tell me what data do you need.

**Comment by marinofaggiana** [comment]
Hi @danaivehr please specific your hardware version etc.

**Comment by danaivehr** [comment]
On client side:
* iphone 5s
* iOS 10 / 11 beta
* Nextcloud 2.17.5.00005

On server side:
* Nextcloud 11.0.0 stable

**Comment by danaivehr** [comment]
Some more observations:

Video upload goes well till the very end - see screenshot.
Error appears only in the end.

**Comment by danaivehr** [comment]
![image](https://user-images.githubusercontent.com/1226019/29519833-83003e56-8687-11e7-8ba5-3625b90eb812.png)

![image](https://user-images.githubusercontent.com/1226019/29519849-8d820008-8687-11e7-86d8-37aa3ced7f16.png)

![image](https://user-images.githubusercontent.com/1226019/29519866-968142a4-8687-11e7-94d6-3e263a487a32.png)

**Comment by marinofaggiana** [comment]
try with 2.17.6 https://github.com/nextcloud/ios/issues/321

**Comment by danaivehr** [comment]
Unfortunately have no iOS 10 device, but tried with 2.17.8 on iOS 11 - same issue.

**Comment by Fake4d** [comment]
Any updates on this issue?

**Comment by danaivehr** [comment]
It may be server setup / version issue, since it is not reproducing for me after upgrade to nextcloud 16

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/1559
