### ISSUE TITLE
Automatic upload broken if folder structure exists or setting for subfolders turned off.

### ISSUE THREAD

**Issue by hendrikreimers** [nextcloud/ios#2211]
### Steps to reproduce

1. Enable automatic upload with subfolders
2. Take a picture with the iOS Camera App
3. Open Nextcloud iOS App and wait for upload

### Expected behaviour

The automatic upload of new pictures should start and done.

### Actual behaviour

Automatic upload only works if the folders doesn't already exist and only if "auto upload with subfolders" is enabled. If automatic upload without subfolders is set, nothing will be uploaded.

If the current subfolders exist already the app doesn't upload any new pictures.

After deleting the whole Upload folder, made some pictures again and opened NC App it starts uploading again.

Maybe it's happend just in the last one or two updates of the Nextcloud App for the NC Server 25 version. A few days ago with one of the last versions, it worked fine as is remember (i think)

PS: This happens if the app doesn't run in the background. Take a picture open it (folder structure creating and pic uploading). Completely close the app, take another picture and open the App again, no picture will be uploaded anymore.

### Environment data

**iOS version:** iOS 16.0.1

**Nextcloud iOS app version:** Nextcloud Liquid for iOS 4.5.3.0 @ 2022

**Server operating system:**

**Web server:** Apache,

**Database:** SQLITE

**PHP version:** 7.4 FPM

**Nextcloud version:** 25.0.0

**Comment by marinofaggiana** [comment]
Hi @hendrikreimers seems strange, have you look the log in Nextcloud iOS for read what's happen ?

**Comment by Lebernd** [comment]
I can confirm the upload is broken. 
I don't open another issue but there is a slightly different behavior in my environment:
Only the folder or folder struture is created, when it is missing. The new images won't get uploaded even to the newly created folders. (If the folder exists nothing is uploaded.)

Just before posting: 1 photo I took for testing is uploaded to a newly created folder. But the 4 others aren't. Strange...

The log shows errors like:
`2022-10-24 14:13:12 Network response request: https://nextcloud.domain.de/remote.php/dav/files/myname/Fotos/2022/10, result: failure(Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 401)))`

Environment data
iOS version: iOS 16.0.3
Nextcloud iOS app version: Nextcloud Liquid for iOS 4.5.3.0 @ 2022
Server operating system:
Web server: Apache,
Database: MYSQL
PHP version: 8.0 / 7.4
Nextcloud version: 25.0.0 / 24.0.6

**Comment by marinofaggiana** [comment]
Need to look entire log

**Comment by hendrikreimers** [comment]
**Additional bug in combination with that...** 
If you try to upload a picture in the Folder which is selected as automatic upload (because auto upload doesn't work) you can select pictures and press "upload" button, but upload doesn't start. Same in the root folder (user home "/" ) !!!
If you create a folder somewhere else (for example /another-pictures ) and do it again, it will work.

**Comment by Lebernd** [comment]
I think I'm out of here - somewhere between asking how to provide the logs, deleting the old log (1,6MB), having a new logfile on ios and making pictures to provide a more problem focussed log: The automatic upload is - of course - working now as expected...

**Comment by stratacast** [comment]
Automatic uploads are plain broken. After the last update of the iOS client (which tells me there were improvements to auto upload management) did the complete opposite. I can no longer auto upload photos.

**Comment by marinofaggiana** [comment]
Repeat: share with we the log of Nextcloud iOS so we can look where is the issue.

**Comment by kotli1** [comment]
@marinofaggiana in a meantime I think it can be analyzed by NextCloud IOS app Team as without logs bad behavior is really very easily to be reproduced - I see that issue in my case as well - automatic upload is really broken.

**Comment by stratacast** [comment]
[INFO] Automatic upload, new 1 assets found [Init Auto Upload]
Network request started: MKCOL .....
[INFO] Automatic upload added $filename with Identifier $identifier
[INFO] Start createProcessUploads

and that's it. Nothing else beyond that point. No indicator of transfers in the UI, the log makes no mention of converting my heic file to jpg, and nothing gets to my server (latest version 24)

**Comment by krlls** [comment]
I also had this problem after upgrading to the latest version.

I found a fix in build 4.5.2 (0) from TestFlight. 

As a temporary solution you can install the latest version from TestFlight, I think in future releases this will be fixed.  [Link at the end of the readme](https://github.com/nextcloud/ios#testflight)

**Comment by kotli1** [comment]
That is actually very good hint.
There is difference in 4.5.3 vs 4.5.2 in file "NCAutoUpload.swift". I am not expert in IOS development but it can be analyzed by those who know :)
In 4.5.3 we have line "    private var applicationState = UIApplication.shared.applicationState"
In 4.5.2 we have "    private let applicationState = UIApplication.shared.applicationState"
+ applicationState variable assignments in few places.

**Comment by marinofaggiana** [comment]
You can try the new version in TestFlight 5.4.4

**Comment by jcaesar-ondeck** [comment]
I’m having similar issues with auto-upload. Ie it’s not working. This is despite being enabled and having the same folder (/Photos) set as the location and the sub-folders option enabled - all of which are the same options which I’ve had for the past 3+ years and had photos auto-uploading fine until about 3 or 4 days ago. 

I’ve installed the 4.5.4(3) test flight version but unfortunately it’s still not uploading automatically for me.

I have to manually add photos each day, and when i use the ‘use auto-upload location’ option it works fine.

Developers, do you still want logs? If so, what actions should I take and get the logs for? Eg should I clear the log, set logging to full, take a photo, come back to nextcloud and then wait x minutes? Then send the logs? The fact that nothing seems to happen makes it hard to know what logs you would like to see

thanks!

**Comment by semiligneous** [comment]
I’m having similar issues with auto-upload. Ie it’s not working. This is despite being enabled and having the same folder (/Photos) set as the location and the sub-folders option enabled - all of which are the same options which I’ve had for the past 3+ years and had photos auto-uploading fine until about 3 or 4 days ago.

I’ve installed the 4.5.4(3) test flight version but unfortunately it’s still not uploading automatically for me.

I have to manually add photos each day, and when i use the ‘use auto-upload location’ option it works fine.

Developers, do you still want logs? If so, what actions should I take and get the logs for? Eg should I clear the log, set logging to full, take a photo, come back to nextcloud and then wait x minutes? Then send the logs? The fact that nothing seems to happen makes it hard to know what logs you would like to see

thanks!

**Comment by marinofaggiana** [comment]
> I’m having similar issues with auto-upload. Ie it’s not working. This is despite being enabled and having the same folder (/Photos) set as the location and the sub-folders option enabled - all of which are the same options which I’ve had for the past 3+ years and had photos auto-uploading fine until about 3 or 4 days ago.
> 
> I’ve installed the 4.5.4(3) test flight version but unfortunately it’s still not uploading automatically for me.
> 
> I have to manually add photos each day, and when i use the ‘use auto-upload location’ option it works fine.
> 
> Developers, do you still want logs? If so, what actions should I take and get the logs for? Eg should I clear the log, set logging to full, take a photo, come back to nextcloud and then wait x minutes? Then send the logs? The fact that nothing seems to happen makes it hard to know what logs you would like to see
> 
> thanks!

Simple, clear the log, move the app in background, take 1 o 2 photo, and after max 30 min. open the app and send me the log

**Comment by kotli1** [comment]
On my side works good when you take photo and open app - then it is synchronizing correctly in last test flight. With app in background with scenario mentioned by @marinofaggiana it is not synchronizing. Starts synchronizing when I click on app being in background.
In my app I see not registering app on location change. Am I missing something ?

**Comment by semiligneous** [comment]
> > I’m having similar issues with auto-upload. Ie it’s not working. This is despite being enabled and having the same folder (/Photos) set as the location and the sub-folders option enabled - all of which are the same options which I’ve had for the past 3+ years and had photos auto-uploading fine until about 3 or 4 days ago.
> > I’ve installed the 4.5.4(3) test flight version but unfortunately it’s still not uploading automatically for me.
> > I have to manually add photos each day, and when i use the ‘use auto-upload location’ option it works fine.
> > Developers, do you still want logs? If so, what actions should I take and get the logs for? Eg should I clear the log, set logging to full, take a photo, come back to nextcloud and then wait x minutes? Then send the logs? The fact that nothing seems to happen makes it hard to know what logs you would like to see
> > thanks!
> 
> Simple, clear the log, move the app in background, take 1 o 2 photo, and after max 30 min. open the app and send me the log

@marinofaggiana - 
Do you have a way for me to send logs to you privately? I’ve increased the logging to maximum and I don’t want to spend ages redacting stuff in order to post it publicly. Thanks!

**Comment by semiligneous** [comment]
@marinofaggiana - I’ve emailed full logs to the address in your profile.

I noticed that one of the lines is referring a path /Photos/(null)/(null)

But it should be year/month ie /photos/2022/10

Is this part of the problem?

```
2022-10-28 22:53:16 [INFO] Automatic upload, new 65 assets found [Init Auto Upload]
2022-10-28 22:53:16 Network request started: MKCOL https://cloud.mydomain.com/nextcloud/remote.php/dav/files/myuser/Photos
2022-10-28 22:53:16 Network request started: MKCOL https:/cloud.mydomain.com/nextcloud/remote.php/dav/files/myuser/Photos/(null)/(null)
2022-10-28 22:53:16 [INFO] Initialize Auto upload with 0 uploads
```

**Comment by stratacast** [comment]
How about putting out a release that rolls back 4.5.3's "Improved auto upload management in the background"? I would rather have unimproved and working than "improved" and literally 0 function. This is bad code QA to push something out this broken.

**Comment by js521458741** [comment]
Autoupload not working on 16.1 w/Version [Nextcloud Hub 3](https://nextcloud.com/) (25.0.0)
Confirmed the Auto-Update works as expected when not "Use Subfolders" is off.
Setup a 2nd - Toggled "Use Subfolders" to and and the Auto upload failes to start. 

=========================================================================================
[PHP] Error: Error: Undefined variable $folder at /usr/local/www/nextcloud/apps/notes/lib/Service/NoteUtil.php#154 at <<closure>>

 0. /usr/local/www/nextcloud/apps/notes/lib/Service/NoteUtil.php line 154
    OC\Log\ErrorHandler::onError(2, "Undefined variable $folder", "/usr/local/www/ ... p", 154)
 1. /usr/local/www/nextcloud/apps/notes/lib/Service/NotesService.php line 153
    OCA\Notes\Service\NoteUtil->getOrCreateFolder("/REDACTED/files/Notes", false)
 2. /usr/local/www/nextcloud/apps/notes/lib/Service/NotesService.php line 30
    OCA\Notes\Service\NotesService->getNotesFolder("REDACTED", false)
 3. /usr/local/www/nextcloud/apps/notes/lib/Service/NotesService.php line 69
    OCA\Notes\Service\NotesService->getAll("REDACTED")
 4. /usr/local/www/nextcloud/apps/notes/lib/AppInfo/SearchProvider.php line 52
    OCA\Notes\Service\NotesService->search("REDACTED", "log")
 5. /usr/local/www/nextcloud/lib/private/Search/SearchComposer.php line 160
    OCA\Notes\AppInfo\SearchProvider->search(OC\User\User {}, OC\Search\SearchQuery {})
 6. /usr/local/www/nextcloud/core/Controller/UnifiedSearchController.php line 105
    OC\Search\SearchComposer->search(OC\User\User {}, "notes", OC\Search\SearchQuery {})
 7. /usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OC\Core\Controller\UnifiedSearchController->search("notes", "log", null, null, null, "/apps/files/?dir=/&view=recent")
 8. /usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Controll ... {}, "search")
 9. /usr/local/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controll ... {}, "search")
10. /usr/local/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main("OC\\Core\\Contr ... r", "search", OC\AppFramework\ ... {}, ["notes","ocs.core.UnifiedSearch.search"])
11. /usr/local/www/nextcloud/ocs/v1.php line 63
    OC\Route\Router->match("/ocsapp/search/providers/notes/search")
12. /usr/local/www/nextcloud/ocs/v2.php line 23
    require_once("/usr/local/www/nextcloud/ocs/v1.php")

GET /ocs/v2.php/search/providers/notes/search?term=log&from=%2Fapps%2Ffiles%2F%3Fdir%3D%2F%26view%3Drecent
from 192.168.REDACTED by REDACTED at 2022-11-06T08:00:41+00:00
=========================================================================================

**Comment by js521458741** [comment]
![IMG_6551](https://user-images.githubusercontent.com/39466074/200161034-c9c5e9bd-9978-4690-bc70-3d16cbbb265d.jpg)

**Comment by marinofaggiana** [comment]
@js521458741 which version you use ?

**Comment by js521458741** [comment]
> 16.1 w/Version [Nextcloud Hub 3](https://nextcloud.com/) (25.0.0)

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/2247

**Comment by keesfluitman** [comment]
Me and my users are also experiencing a lot of trouble with the automatic upload.
- Changing the folder has no effect. It still uploads to the old folder.
- It keeps requesting Files and checking / starting uploads. (load on phone and server).
- It does not upload everything for one of my users. (a video was once missing)

I will go to a thirdparty sync tool for now. I need this to be reliable. Gl :) Thanks for all the hard work.

**Comment by rrik** [comment]
This issue appears closed, but I am getting the same error - `Network request started: MKCOL` and photos fail to upload.
