### ISSUE TITLE
Widgets are not sticking to the account

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/ios#2217]
### Steps to reproduce

1. Set up 2 profiles, one with Nextcloud 24, one with Nextcloud 25
2. Select the 25 profile
3. Add the "Talk mentions" widget
4. Select the 24 widget

### Expected behaviour

Widget remains working and shows the 25 profile content

### Actual behaviour

Widget breaks and shows Widgets only work with 25+. If both profiles would be 25 I would still see the emptiness of my private instance talk mentions and missout on the company mentions, making this a very dangerous thing with negative impact. For me it is totally unexpected that the widgets change the profiles.

### Screenshots
![2022-10-26 08-30-39-0](https://user-images.githubusercontent.com/213943/197955326-6101b9bc-aefe-49b2-9af7-f5c91914bb51.png)

**Comment by marinofaggiana** [comment]
@tobiasKaminsky how works in Android ? you select the widget account or the widget are connect to the active account ?

**Comment by nickvergessen** [comment]
> you select the widget account or the widget are connect to the active account ?

Yes, the first option of the widget is an account switcher
![Screenshot_2022-10-26-09-55-36-335_com nextcloud client](https://user-images.githubusercontent.com/213943/197968423-397e81d0-b095-4320-bd88-2a018af91141.jpg)

**Comment by tobiasKaminsky** [comment]
The account switcher is only shown if there is more than one account set up.

**Comment by marinofaggiana** [comment]
ok, I will study something for iOS
