### ISSUE TITLE
🪄 iOS Machine Learning - Scan / Viewer

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#2219]
With the last iOS (>= 14) there have been major improvements on ML's API that allow for better handling of the detection of text in images and filters applied to them.

Certainly the Document Scan application and the image viewer can benefit from this.

**Comment by tobiasKaminsky** [comment]
Can you please describe a bit more what the use case for ML would be.
E.g. scan text: what is improved?
What filter can applied to which files? Images I guess.
