### ISSUE TITLE
ios Nextcloud loose configuration after device reboot

### ISSUE THREAD

**Issue by ASC-DE** [nextcloud/ios#2222]
Hi team,

using ios APP for upload Photos with Filename Mask and Subfolders. Till version 4,5 released I had no issues with but since the new releases v 4.5 the App loose the configuration completely after restart the ios Device. After restart or turn on the mobile device I have to reconfigure everything in the nextcloud app.
ios Version tested: 15 and 16 with remove app and install the app again.
Nextcloud version 24.0.6 hosted with All-inkl. With Desktop apps I do not have any issues.

best regards
ASC-DE

**Comment by marinofaggiana** [comment]
Hi @ASC-DE this is very strange ! ... I honestly can't think of anything, but you can try with a Nextcloud Demo for look if happen the same.

**Comment by ASC-DE** [comment]
Hi,
I tested with two different nexcloud installations and with both the issue with loosing the connfiguration after reboot the iphone happen.
With my Android Phone there is no issue.

BTW, the autoupload function does not work on ios too, this issue is already open in another thread.

Br
ASC-DE

**Comment by Kl120** [comment]
Hi,
I can confirm the error. It also occurs by my iPhone13 since the last or penultimate nextcloud update. I have to login again and to set all changed configuration entries after switching on the phone.
It is very annoying.
BR

**Comment by ASC-DE** [comment]
Dear Mr. Faggiana,

today received the updated 4.5.4 and tested 3 times. After turn off / turn on the iPhone the configuration remain. Seams to be fixed.
Kind regrads
ASC-DE
