### ISSUE TITLE
E2E encrypted folders are not accessible in iOS files

### ISSUE THREAD

**Issue by gorootde** [nextcloud/ios#2229]
### Steps to reproduce

1. Create an E2E encrypted folder `e2etest` in the nextcloud iOS app
2. Go to iOS files app
3. Select "Nextcloud"
4. See that `e2etest` folder is missing

### Expected behaviour

The folder should show up in iOS files the same way as every other unencrypted folder does. Technically this should be possible somehow, as e.g. Cryptomator app does the same.

### Actual behaviour

Only unencrypted folders show up

### Reasoning or why should it be changed/implemented?
E2E folders cannot be used as destinations for other apps to save / open data.

### Environment data

**iOS version:** 16.0.3
**Nextcloud iOS app version:** 4.5.3.0
**Server operating system:** Linux
**Web server:** Official Docker container
**Database:** MySQL
**PHP version:** N/A
**Nextcloud version:** 24.0.6

**Comment by marinofaggiana** [comment]
Our version of E2EE is not compatible with the Files app.

**Comment by gorootde** [comment]
I know. That's why I opened this issue. But seems like a discussion about this topic is not welcome.

**Comment by marinofaggiana** [comment]
No no @gorootde it's technically impossible with our E2EE. sorry.
