### ISSUE TITLE
E2E: better UX

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#2236]
- when e2e already works on server, click on encrypted folder should directly ask for menomnic
- like in linked issue, please change it to reflect all three states in settings
  - e2e not set up (on any client)
  - e2e is set up on server, but not on the device
  - e2e is fully set up (possibility to show passphrase, remove local key)

**Comment by marinofaggiana** [comment]
- when e2e already works on server, click on encrypted folder should directly ask for menomnic

done.

**Comment by marinofaggiana** [comment]
> * like in linked issue, please change it to reflect all three states in settings
>   
>   * e2e not set up (on any client)
>   * e2e is set up on server, but not on the device
>   * e2e is fully set up (possibility to show passphrase, remove local key)

sorry, I don't undenstand ... ?
