### ISSUE TITLE
Folder Title Color

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/ios#224]
When you want to upload a file directly to the Nextcloud server, we see this screen
At the top of the screen is the name of folder but it's quite difficult to read because it's a black color 
[no problem it the background color is white :)]

This color can be made more readable?

![ortaklar-ddo](https://cloud.githubusercontent.com/assets/297968/25768391/e4b4d038-320b-11e7-90a8-f68f9bb3f8a3.png)

cc @marinofaggiana

**Comment by marinofaggiana** [comment]
@emresaracoglu where is this capture view ? I Don't find this issue

**Comment by emresaracoglu** [comment]
Hi Marino
![gif](https://cloud.githubusercontent.com/assets/297968/25771096/6b7391f6-3250-11e7-8dfa-1551e8d8125b.gif)
@marinofaggiana

**Comment by marinofaggiana** [comment]
Oh ! Yes ! Thanks
