### ISSUE TITLE
Auto Upload Error creating subfolders due to requesting wrong url

### ISSUE THREAD

**Issue by MrSpuddy** [nextcloud/ios#2247]
### Steps to reproduce

1. Enable “Use Subfolders” in Auto-Upload Settings
2. Attempt to start auto-upload, only to be met with error in about a second.

### Expected behaviour

Folders should be created successfully, and auto-upload of images should begin.

### Actual behaviour

The device results the server url incorrectly to create the subfolder, going to “https:/example.com” instead of “https://example.com”, as shown in the logs.

### Logs

(Applicable Section)

2022-11-09 23:38:49 Network request started: PROPFIND https://example.com/remote.php/dav/files/user
2022-11-09 23:38:49 Network response request: https://example.com/remote.php/dav/files/user, result: success(1684 bytes)
2022-11-09 23:38:57 [INFO] Automatic upload, new 1857 assets found [Auto upload full]
2022-11-09 23:38:57 Network request started: MKCOL https://example.com/remote.php/dav/files/User/Photos
2022-11-09 23:38:58 Network request started: MKCOL https:/example.com/remote.php/dav/files/User/Photos/2021/10

### Reasoning or why should it be changed/implemented?

Auto upload does not seem to work with subfolders without it, which is quite frustrating.

### Environment data

**iOS version:** iOS 16.1

**Nextcloud iOS app version:** Nextcloud Liquid 4.5.4.9

**Server operating system:** Ubuntu

**Web server:** Nginx

**Database:** SQLite

**PHP version:** 8.1

**Nextcloud version:** 24.0.1

**Comment by Weng-OU** [comment]
Thanks your report.
I have the same problem as you.
The root cause is the same too.

**log**
```
[INFO] Automatic upload, new 385 assets found [Auto upload full]
Network request started: MKCOL https://example.com/remote.php/dav/files/Photos
Network request started: MKCOL https:/example.com/remote.php/dav/files/Photos/2021/02    # change from https;// to https:/ here
```

**Env**
iOS version: iOS 15.7.1
Nextcloud iOS app version: Nextcloud Liquid 4.5.4.9
Server operating system: Ubuntu
Web server: Apache
Database: mysql
PHP version: 8.1.2
Nextcloud version: 25.0.1

**Comment by marinofaggiana** [comment]
Try the version in TestFlight
https://testflight.apple.com/join/RXEJbWj9
