### ISSUE TITLE
The latest version of uploaded files cannot be used to create subfolders

### ISSUE THREAD

**Issue by dake2007** [nextcloud/ios#2252]
### Steps to reproduce

1.Click Upload
2.Select uploaded photos
3.Tick "Auto upload" and "Use sub folder"

### Expected behaviour

Create subfolders in year and month to upload photos

### Actual behaviour

The error prompt "Error creating subfolders" pops up

### Screenshots

![image](https://user-images.githubusercontent.com/113051283/201113988-170b69a0-9f84-481d-972e-b87f3387eebf.png)

### Environment data

**iOS version:** e.g. iOS 15.7.1

**Nextcloud iOS app version:4.5.4.9 see More > Settings

**Server operating system:centos7.9

**Web server: nginx

**Database:mysql

**PHP version:7.4

**Nextcloud version:24.0.7

**Comment by marinofaggiana** [comment]
Try the version in TestFlight
https://testflight.apple.com/join/RXEJbWj9

**Comment by dake2007** [comment]
Thanks, I'll try @marinofaggiana

**Comment by dake2007** [comment]
Tested, problem solved
