### ISSUE TITLE
Editing Markdown file should name user in activities

### ISSUE THREAD

**Issue by kurb70** [nextcloud/ios#2253]
Since two releases of this app, the attempt to edit a Markdown file, results in an activity note stating that an "remote user" was editing this file.
The user name should be used for this activity entry.

BTW I reinstalled the app on my device running iPadOS 16.1.1 (20B101), but no diffence.

**Comment by kurb70** [comment]
Uups. I am communicating with an Nextcloud 24.0.6 Instance.

**Comment by klingon00** [comment]
I can reproduce this issue on an iPhone 8 Plus running iOS 15.7.1 and Nextcloud app build 4.5.6 connected to Nextcloud server 25.0.1

**Comment by kurb70** [comment]
Does not occur anymore.
