### ISSUE TITLE
Unable to print from app

### ISSUE THREAD

**Issue by Ho551** [nextcloud/ios#2278]
### Steps to reproduce

1. Open Document/Image in app
2. Select print in menu
3. Nothing happens

### Expected behaviour

Print menu should open after selection

### Actual behaviour

Print menu does not open after selection

### Logs

No info in log about printing

### Environment data

**iOS version:** iOS 16.1.1

**Nextcloud iOS app version:** 4.5.7.0

**Server operating system:** Ubuntu

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.1

**Nextcloud version:** 25.0.1

**Comment by marinofaggiana** [comment]
thanks @Ho551
