### ISSUE TITLE
Let me choose the upload folder

### ISSUE THREAD

**Issue by awlx** [nextcloud/ios#228]
Hey,

I tried to enable the automatic uploads to Nextcloud. But it provokes a case sensitivity clash between photos and Photos. 

Why can't we just choose the upload destination folder? 

Cheers.

**Comment by marinofaggiana** [comment]
https://help.nextcloud.com/t/change-folder-autoupload-uploads-to/8900

**Comment by samwh1te** [comment]
Hi there! I'm on 5.5.4.13 and the "Folder for Automatic upload" option doesn't show. iPadOS 17.4.1
![24-08-21 00-44-10 2137](https://github.com/user-attachments/assets/93c89fe6-3b83-4e6f-ab8c-221ee934efff)
