### ISSUE TITLE
Live image is shown as 2 files (HEIC + MOV) after deleting cache

### ISSUE THREAD

**Issue by sdalmeida** [nextcloud/ios#2280]
### Steps to reproduce

1. Go to nextcloud iOS settings > advanced
2. Enable "Live Photo"
3. Disable "Most Compatible"
4. Upload a "live" photo
6. Delete cache

### Expected behaviour

Under the "media" tab, there should only be 1 HEIC image with the "live" feature.

### Actual behaviour

For some reason, after a while (mostly a few weeks), the "live" photo shows up as "HEIC" and another as "MOV". The "live" feature of the image is lost and now you have 2 files.

### Screenshots

If applicable, add a screenshot showing the issue.

![image](https://user-images.githubusercontent.com/1103528/204952575-053b4c79-c39c-4873-82ca-204a8dc07cf2.png)
In the DB, you can see that both HEIC and MOV files are there (as expected), but on the iOS app, they are shown as seperate entities instead of 1 HEIC file with "live" support.

### Logs

```
None
```

### Environment data

**iOS version:** e.g. iOS 16.0.0

**Nextcloud iOS app version:** 4.5.6.4

**Server operating system:** Truenas (jail)

**Web server:** iocage

**Database:** MySQL

**PHP version:** 7.4.15

**Nextcloud version:** 25.0.1

**Comment by marinofaggiana** [comment]
Hi @sdalmeida yes, the HEIC do not contain a live (movie) but it's only the image.

**Comment by sdalmeida** [comment]
Hi @marinofaggiana 
Yes, I see 2 files in the iOS app

![photo_2022-12-01_13-33-40](https://user-images.githubusercontent.com/1103528/205132666-b8577677-8ba4-4d00-b3c8-992fd63ea700.jpg)
![photo_2022-12-01_13-33-35](https://user-images.githubusercontent.com/1103528/205132677-1ed69754-7cb7-4a8f-aa57-9563cdd4c7b5.jpg)

In the iOS app, under "media" I see 2 files. `IMG_2080.HEIC` and `IMG_2080.mov`.

**Comment by marinofaggiana** [comment]
@sdalmeida You can try the test flight version if solves : 
https://testflight.apple.com/join/RXEJbWj9

**Comment by sdalmeida** [comment]
Hi @marinofaggiana 
It fixed some images but not all. The blue image above is still shown and HEIC and mov.
Are there any logs I can share?

**Comment by marinofaggiana** [comment]
very strange ... the remove cache do not help you ?

**Comment by sdalmeida** [comment]
@marinofaggiana clearing the cache doesn’t fix it. How does Nextcloud know to link the HEIC with the mov? Is it by file name or is there a metadata in the db?

**Comment by marinofaggiana** [comment]
This is for all HEIC ? (HEIC + MOV)

**Comment by sdalmeida** [comment]
@marinofaggiana not for all of them. Some of the newer HEIC images its fine, but images from about a month ago, are split into 2 (they initially were only 1 file)

**Comment by marinofaggiana** [comment]
they initially were only 1 file ? I don't understand what's you mean ?
but is simple LivePhoto = **same name** (mov+heic) or (mov+jpg)

**Comment by sdalmeida** [comment]
@marinofaggiana I meant that initially, only 1 file showed up under the "media" tab. A HEIC photo with "live" enabled. 
If the "live" feature is determined by the file name (mov+heic), you can see that the name is the name, and I'm seeing 2 files
https://user-images.githubusercontent.com/1103528/205132666-b8577677-8ba4-4d00-b3c8-992fd63ea700.jpg
https://user-images.githubusercontent.com/1103528/205132677-1ed69754-7cb7-4a8f-aa57-9563cdd4c7b5.jpg

**Comment by marinofaggiana** [comment]
very strange, sorry but I don't know how help you (without debug) but in the normal directory (always in the iOS app) you see 1 o 2 files (not in Media) ?

**Comment by sdalmeida** [comment]
@marinofaggiana interesting, seems like this is a bug in the "media" view. If I go to the "Files" tab and find my image, it is showing up as a single HEIC file with the "live" feature enabled.
![photo_2022-12-06_11-20-06](https://user-images.githubusercontent.com/1103528/205965828-cd197426-4710-4c53-be0e-a09f94c0ba8f.jpg)

**Comment by sdalmeida** [comment]
@marinofaggiana copying the image to new a folder and then going to "media" shows up correctly.

**Comment by sdalmeida** [comment]
In media it only shows 1 file.

**Comment by marinofaggiana** [comment]
with the Live icon ?

**Comment by sdalmeida** [comment]
No live icon :( (as you can see from the 2nd picture above).

**Comment by marinofaggiana** [comment]
no, with the Live icon in Media (for now I am interested only a media) :-)

**Comment by sdalmeida** [comment]
oh oh, in the media. Sorry.
Yea, in the media tab, it shows with the live icon.

**Comment by marinofaggiana** [comment]
ok good, I have understand. probabile fix next build.

**Comment by marinofaggiana** [comment]
@sdalmeida fixed ?

**Comment by sdalmeida** [comment]
@marinofaggiana Sorry for the late reply, I'm on vacation and the internet here is pretty bad haha. 
Is the fix in the latest version published to the iOS store? Or do I need to download it from test flight?

**Comment by sdalmeida** [comment]
hi @marinofaggiana 
Just wanted to let you know that the issue has been fixed! I'll be closing this issue.
Thanks!
