### ISSUE TITLE
Chunk size setting is not heeded if files have already been marked to upload

### ISSUE THREAD

**Issue by eharris** [nextcloud/ios#2286]
### Steps to reproduce

1. Disable chunking in Advanced settings (Chunk size in MB = 0)
2. Have large video over 1GB in camera roll, and Apache LimitRequestBody set to default 1GB
3. Enable camera roll auto upload videos
4. See that the over 1GB file fails to upload with a "413: The file is too large" error (and remains queued for retry)
5. Change setting to use chunked file upload (I used Chunk size in MB = 50)
6. Manually kill app.  Restart and verify that chunked file setting is still enabled.
7. See that already queued file retries and continues to fail to upload with same "413: The file is too large" error, despite that it should now be using chunked upload.

### Expected behaviour

The setting for the upload chunk size should be heeded, even for files that have already been marked to be uploaded, and even if they have previously caused errors.

### Actual behaviour

As above

### Logs

Verified in my app logfile that even after the chunk setting was enabled, the already queued files were still being attempted WITHOUT chunking:

```
[INFO] PROCESS-UPLOAD find 2 items
[INFO] Upload file <fname> with Identifier <ID> with size 1855868615 [CHUNCK false, E2EE false]
[INFO] Network start upload file <fname>
...
Network completed upload file: <path> with error code 413 and error description 413: The file is too large
```

### Environment data

**iOS version:** 16.0.3

**Nextcloud iOS app version:** Nextcloud Liquid for iOS 4.5.7.0

**Server operating system:** Debian 11 (bullseye)

**Web server:** Apache 2.4.54-1

**Database:** Mariadb 10.5.15-0

**PHP version:** 7.4.33

**Nextcloud version:** 22.2.10

**Comment by marinofaggiana** [comment]
Hi @eharris this request is not possible, when a file is ready in queue (or requeque after an error) is not possible modify the type. You can remove it and resend it (after the change the Chunk).

**Comment by eharris** [comment]
Why is it not possible to change this?  It would seem like it only depends on the network connections made to the server, which are entirely under the control of the app, and if transfers fail for some reason, there is already a retry mechanism in place.  Why is how the transfer should be accomplished something that is immutable?

**Comment by eharris** [comment]
Also, doesn't seem like this ticket should be closed as "completed" when it's not.  If it's really impossible to fix, perhaps "won't fix" is more appropriate?

**Comment by marinofaggiana** [comment]
Hi @eharris because after an error (413, but there are dozens of errors) in this case with change automatisms are not acceptable, It is up to the user to figure out what to do.
However you can always propose a PR
