### ISSUE TITLE
Chunking size settings do not work on iOS - fidelity of backup set lost

### ISSUE THREAD

**Issue by EagleDTW** [nextcloud/ios#2288]
### Steps to reproduce

1. Set chunking size to anything that the SW coder likes - it still will not upload the files that are larger than 100mb.
2. Error is 413 that is explanatory, but file is supposed to be uploaded and it is not!
3. There is a bug in the iOS implementation that is not being captured as a workaround for the error 413 file too large and that correction is chunking and this is not working!
4. If the coder feels that anything over 100mb should not be uploaded then I have serious concerns about the fidelity of critical photos and videos backup solution that cannot capture all items in storage!

### Expected behaviour

Tell us what should happen.

### Actual behaviour

Tell was what instead happens.

### Screenshots

If applicable, add a screenshot showing the issue.

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Environment data

**iOS version:** e.g. iOS 14.4.1

**Nextcloud iOS app version:** see More > Settings

**Server operating system:**

**Web server:** Apache, nginx

**Database:**

**PHP version:**

**Nextcloud version:** see Nextcloud admin page

**Comment by marinofaggiana** [comment]
Hi @EagleDTW load a video of your issue. thanks

**Comment by EagleDTW** [comment]
Will do, Marino! Give me a few days to coordinate the effort and upload a video. Really appreciate you looking into this further!Thanks,DanielOn Dec 13, 2022, at 1:21 AM, Marino Faggiana ***@***.***> wrote:﻿
Hi @EagleDTW load a video of your issue. thanks

**Comment by EagleDTW** [comment]
Hi Marino,

I got to it sooner than expected! It just keeps cycling through 53 qty of too large error files and chunk size is 100mb. Several minutes later it is still at 53 and just keeps running through them faster than any uploads could take place.

Thank you,
Daniel

**Comment by EagleDTW** [comment]
File trimmed for size limits…
https://user-images.githubusercontent.com/62778358/207766598-84e5c03a-a8ff-472f-af22-eb0aac4a4eaf.MOV

**Comment by marinofaggiana** [comment]
This files are not set as Chunk. Which value is set the Chunk size in MB ?

**Comment by EagleDTW** [comment]
More --> Settings --> Advanced --> Chunk size in MB

**Comment by marinofaggiana** [comment]
if 100 it too large set less 50 , 10 etc.

**Comment by EagleDTW** [comment]
I’ve set to 10, 25, no luck function is not working!On Dec 17, 2022, at 3:11 AM, Marino Faggiana ***@***.***> wrote:﻿
if 100 it too large set less 50 , 10 etc.
