### ISSUE TITLE
Offline favorites are not downloaded completely

### ISSUE THREAD

**Issue by sippnex** [nextcloud/ios#229]
If you add a Share to your favorites and you have the "Offline available favorites" settings active,
the nextcloud app will download the most files, but some files are missing and do not appear in the transfers view. The problem especially occurs with large file numbers (500+) I think.

Are there any similar experiences with large file numbers and offline favorites?

**Comment by marinofaggiana** [comment]
mmmm no ... but 500 or more file is not "Favorites" 😃

**Comment by ho1ger** [comment]
uhm, just a question. Maybe @sippnex and I have the same misconception about the Favorites: 

For me Favorites are the files I want to have downloaded on my device (I have plenty of space free; hence I do not care about the number of files that are downloaded). You @marinofaggiana say "500 ... is not Favorites" which indicates that for you Favorites are 10 files with important info and Favorites is kind of a shortcut to those files. I'd agree to that meaning... 

However, to my understanding there's no different way of downloading folders to the device? So somehow naming of the function and what it does is not well aligned?

**Comment by sippnex** [comment]
Ok, I already thought that favorites are not constructed for a complete offline availability of shares. But I think in the future there could be cases where a complete offline availability is useful for some people. I mean the feature is given with offline favorites, but it does not work reliable with a big number of files.
Maybe one can fix it? If it is really not possible and the favorites are not constructed for such a use case I would close that issue.
