### ISSUE TITLE
Moving files overwrites file with same name 

### ISSUE THREAD

**Issue by JuliCodes** [nextcloud/ios#2293]
### Steps to reproduce

1. Create Folder /Test
2. Create File in /Test with name a.txt 
3. Create File in / with Name a.txt
4. Move file via context menu to /Test

### Expected behaviour

A message box asking for the wanted behavior or just a simple error message like in the web frontend.

### Actual behaviour

The app silently deletes the existing files and writes the new one.

### Environment data

**iOS version:** iPadOS 16.2

**Nextcloud iOS app version:** 4.5.7.0

**Server operating system:** hosted by Hetzner

**Web server:** hosted by Hetzner

**Database:** mysql 10.5 hosted by Hetzner

**PHP version:** 8.0 hosted by Hetzner

**Nextcloud version:** 24.0.7

**Comment by JuliCodes** [comment]
Issue does persist in Nextcloud iOS app version: 4.6.0.19

**Comment by marinofaggiana** [comment]
If is set the overwrite no.

![Screenshot 2022-12-20 alle 14 19 15](https://user-images.githubusercontent.com/8616947/208676654-89e664e9-7b1a-4f12-b998-18569845df2b.png)

**Comment by JuliCodes** [comment]
Uff, totally didn’t saw that option. I looked into the system settings, app settings and Nextcloud server settings. I am sorry bothering you.
