### ISSUE TITLE
Nextcloud iOS 2.17.3 beta

### ISSUE THREAD

**Issue by Kylobayd** [nextcloud/ios#230]
Hello,

I have installed the beta today through TestFlight. 
However when I want to open the app, it shows my folders but after that it immediately crashes and returns me to the home screen.
Im testing it on a iPhone 6s iOS 9.0.2. My device is jailbroken, however I also tested it in SafeMode, but the same result, the app crashed aswell.

**Comment by marinofaggiana** [comment]
Hi, strange :( can you send me the crash log ?

**Comment by Kylobayd** [comment]
I can't find it back in the crash log, it does not show up in diagnostic and usage.

**Comment by Kylobayd** [comment]
I can navigate in the app before it crashes, but after 4 seconds it crashes and returns to the home screen.

**Comment by marinofaggiana** [comment]
test, if possible, disable auto upload

**Comment by Kylobayd** [comment]
Cant do it in time, it crashes when I'm at the settings tab unfortunately.

**Comment by marinofaggiana** [comment]
ok, wait, do not remove App :-) thanks

**Comment by Kylobayd** [comment]
![img_1237](https://cloud.githubusercontent.com/assets/28253562/25949799/10f96644-3659-11e7-9193-facfb775e684.PNG)
I also installed the app on my iPad, same story also crashes but I got the error as you can see above in the picture. Maby this is has something to do with it?

**Comment by marinofaggiana** [comment]
Server Certificate Untrusted, maybe .. please, if possible, wait next beta on your iphone. thanks

**Comment by Kylobayd** [comment]
Okay I will wait for the next beta, am I included in the next beta automatically? Thanks for your help and time by the way.

**Comment by Kylobayd** [comment]
When I look in the logs from my Nextcloud server, it shows me this error:
I get this error when I open the app and when it crashes it shows this error below in the logging.

Fatal	webdav	Exception: {"Message":"HTTP\/1.1 415 Unsupported Media Type","Exception":"Sabre\\DAV\\Exception\\ReportNotSupported","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/usr\/pbi\/nextcloud-amd64\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/usr\/pbi\/nextcloud-amd64\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#3 \/usr\/pbi\/nextcloud-amd64\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/usr\/pbi\/nextcloud-amd64\/www\/nextcloud\/apps\/dav\/lib\/Server.php(184): Sabre\\DAV\\Server->exec()\n#5 \/usr\/pbi\/nextcloud-amd64\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#6 \/usr\/pbi\/nextcloud-amd64\/www\/nextcloud\/remote.php(165): require_once('\/usr\/pbi\/nextcl...')\n#7 {main}","File":"\/usr\/pbi\/nextcloud-amd64\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","Line":719,"User":"Kylobayd"}

**Comment by Kylobayd** [comment]
The new version you just released still crashes on my iPhone.

On my iPad it works now, no more crashes, iPad Air 2 iOS 8.1.2

**Comment by Kylobayd** [comment]
Edit: When I open the app on the homescreen on my iPad it still crashes, but when I open it through the TestFlight app, it works.

**Comment by marinofaggiana** [comment]
`Edit: When I open the app on the homescreen on my iPad it still crashes, but when I open it through the TestFlight app, it works.`

Not possible ... do you have more Nextcloud app ???

**Comment by Kylobayd** [comment]
It sounds weird but I am not kidding. I can make a video of it if you want to see it. 

No I dont have the official Nextcloud app from the appstore yet, low on budget at the moment and I dont have iTunes credits sadly.

**Comment by marinofaggiana** [comment]
please reinstall all

**Comment by Kylobayd** [comment]
I reinstalled on my iPhone still crash, on iPad when launched from TestFlight it works, from homescreen it crashes. I will record it and send it so you can see it.

**Comment by marinofaggiana** [comment]
please send me (if possible) an account test ... ios@nextcloud.com

**Comment by Dirk23** [comment]
Same issue for me, App Crashes allmost immediately. I'm not able to access anything. I have letsencrypt certificate for my server.

**Comment by marinofaggiana** [comment]
@Dirk23 : Jailbroken ?

**Comment by Dirk23** [comment]
No, iOS10.3 Beta

**Comment by Dirk23** [comment]
iPad 3 iOS 9.3.5 everythings Fine!

**Comment by marinofaggiana** [comment]
ok , I have find 2 bugs ;)

**Comment by Dirk23** [comment]
Latest Update fixed it

**Comment by Kylobayd** [comment]
Mine still crashes :(

**Comment by marinofaggiana** [comment]
please patient ... we resolve all bug :-)

**Comment by Kylobayd** [comment]
Any news on the bug fix? @marinofaggiana

**Comment by marinofaggiana** [comment]
yes, I have send you a Invite for build 00005 .. not receive ?

**Comment by Kylobayd** [comment]
Nope, the latest I have is Version 2.17.3 (4)

**Comment by Kylobayd** [comment]
I have updated to 00005, but it still crashes I reinstalled, and its still the same problem as before.

**Comment by marinofaggiana** [comment]
Wait automatic log ... :(

**Comment by Kylobayd** [comment]
what do you mean with automatic log?

**Comment by marinofaggiana** [comment]
Symbol debug crash.

**Comment by Kylobayd** [comment]
I updated my Nextcloud server to 10.0.5 but did not solve the problem, app still crash.

**Comment by marinofaggiana** [comment]
Is not a problem of Nextcloud Server ... iOS version ?

**Comment by Kylobayd** [comment]
I have iPhone 6s iOS 9.0.2

**Comment by Kylobayd** [comment]
The 00006 fixed the crash issue. Good job! Do you have specific things for me to test or to help you with? @marinofaggiana

**Comment by marinofaggiana** [comment]
Thanks, yes, automatic upload and share folders/files thanks. close this issue.
