### ISSUE TITLE
Screen rotation setting on iPad Pro 9.7 completely ignored ;)

### ISSUE THREAD

**Issue by justinclift** [nextcloud/ios#231]
Installed the iOS app from the Apple store, loaded it... and the whole thing is upside down.

It's the only app I've seen yet which has this problem, so hopefully it's easy to fix. :wink:

As to why it's "upside down", I normally use my iPad with the home button at the top, as the stand I use needs the connection cable to be at the top.  I'm completely used to it now, so that's the "normal" for me.

Is there any chance of getting the NextCloud app to honour the screen rotation setting? :smile:

**Comment by marinofaggiana** [comment]
Hi @justinclift, sure ! available from next version :-)

**Comment by justinclift** [comment]
Awesome @marinofaggiana, thanks. :smile:
