### ISSUE TITLE
Add a setting for the max number of parallel uploads

### ISSUE THREAD

**Issue by hunhejj** [nextcloud/ios#2315]
Recently I can't upload images in batches to my Nextcloud server anymore. I figured out by experimenting that my server (Nextcloudpi running dockerized on a rPi4-4MB) can handle 5-6 uploads in parallel at most, otherwise it sort of dies. 

IIRC correctly indeed the iOS app used max. 5 concurrent threads earlier. Now it seems to be 10 default. Did it change recently?

Would it be possible to add a setting so one can limit the number of concurrent threads? Or is there a way to limit that on the server itself?

**Comment by marinofaggiana** [comment]
Hi @hunhejj yes, now is set to 10 because the hardware and the actual network permits it.

**Comment by kallegrens** [comment]
Why was this marked as completed? The issue remains. Even with a more than capable server, not comparable to RPi and whenever auto-upload tries to upload videos a couple of hundred MB each in parallel it freezes or even makes my server unreachable for a while. Error 404 or 502, as if I'm DDoS'ing my own server.

**Comment by pdsrebelo** [comment]
I'm having the same issues described above. Please re-open the issue
