### ISSUE TITLE
Personal Info - Synchronisation bug iPhone 6s

### ISSUE THREAD

**Issue by mind22** [nextcloud/ios#233]
Nextcloud v2.17.2 on iphone 6s is not synchronizing the personal info (picture + info).

P.S. I removed the account and added it again, didn't change anything.

**Comment by rakekniven** [comment]
Could you please add additional account and try?
Which version version?
Which OS?

**Comment by mind22** [comment]
Hmm ok, i created a new account, which synchronized the personal infos as it should be. But the behavior stays the same for the standard account, which was added with v2.17(.1). When switching to the standard account the login screen also appears every time. I know that this didn't occur from the beginning 3-4 weeks ago, so it must be due to the new updates .1 or .2.

iOS 10.3.1
Nextcloud 11.0.2

**Comment by marinofaggiana** [comment]
hi @mind22 ... the login appear if the password is changed ... or exists problem with account ...

**Comment by mind22** [comment]
@marinofaggiana what i meant with the comment above ... that when i am switching to my standard account the login screen appears **but** i can press cancel in the right top corner and use the account as usual with no problems. I never changed the password, i've set an app-pin for it (totp).

**Comment by marinofaggiana** [comment]
Do you have insert the new password app ? Error on Nextcloud server ?

**Comment by mind22** [comment]
No errors on the server. There was an update of the TOTP app but nothing else. 

I suggest you also close this thread, because i have identically set up three iphones (se, 6 and 6s) and only the 6s shows this specific behavior. Maybe the update to .3 will also solve the problem here.

**Comment by marinofaggiana** [comment]
ok.

**Comment by mind22** [comment]
yep, update .3 solved this problem. thx
