### ISSUE TITLE
Option to Manually Upload to "Autoupload" folder (& subfolders) missing on 4.7.0

### ISSUE THREAD

**Issue by fservida** [nextcloud/ios#2333]
### Steps to reproduce

1. Upload media from + button
2. Choose photos to upload

### Expected behaviour

Should be able to upload to "Autoupload folder" and choose upload by subfolder

### Actual behaviour

Only possible to choose single flat directory, defaults to / which is not ideal

### Screenshots

N/A

### Logs

N/A

### Environment data
**Nextcloud iOS app version:** 4.7.0 (Testflight)

**Comment by marinofaggiana** [comment]
Hi @fservida don't worry is only in develop :-)
