### ISSUE TITLE
Unable to add a comment

### ISSUE THREAD

**Issue by jsalort** [nextcloud/ios#2343]
### Steps to reproduce

1. Go to a picture and tap on it
2. Tap the three dot button and go to "Details"
3. Enter some text in the "new comment" area, and tap Return.

### Expected behaviour

A new comment should be created.

### Actual behaviour

Nothing happens.

### Environment data

**iOS version:** e.g. iOS 15.7.3

**Nextcloud iOS app version:** 4.6.0.19

**Server operating system:** Raspberry Pi OS (32 bits)

**Web server:** Apache/2.4.38

**Database:** MySQL

**PHP version:** 7.4.33

**Nextcloud version:** 25.0.2 RC1

**Comment by marinofaggiana** [comment]
@jsalort thanks for your report, already fixed in 4.7.0
