### ISSUE TITLE
Translation at Transifex should be the same

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/ios#236]
Only german translation related.

The german translations (formal and non-formal) should be fully and nearly the same.
The non-formal version should not have place holders they link to the formal version in Transifex.

Many strings are the same and can be copy and pasted simply between these two languages.

**Comment by rakekniven** [comment]
Hallo @Siggi0904,

aktuell unterstützt Apple iOS nur die formelle Version.
Daher ist eine informelle Übersetzung nicht notwendig.
In der Vergangenheit haben einige Übersetzer auch hier gewirkt und die Übersetzungen liefen stark auseinander.
Ich habe schon angeregt die Dateien von Transifex zu entfernen. Das ist aktuell technisch nicht möglich. Ein sperren der Dateien ist ebenso nicht möglich.

Habe Deine Arbeit gesehen und schätze die Mitarbeit am Projekt.
