### ISSUE TITLE
Filename for scanned images should be date/timestamp instead of always 'Scan.pdf'

### ISSUE THREAD

**Issue by atomtigerzoo** [nextcloud/ios#2372]
### Steps to reproduce

1. Open app, scan new image
2. Save the image
3. Filename is always 'Scan'

### Expected behaviour

The filename should be a unique date-timestamp (with a suffix maybe) - same as before in the older versions.

### Actual behaviour

Filename of every scan is always 'Scan'

### Reasoning or why should it be changed/implemented?

That way, one can take multiple images of e.g. bills or documents and save those without editing the filename on every save/scan. It should be easier for people that scan lots of documents for archiving reasons or where filenames doesn't matter (but shouldn't be all Scan.pdf, Scan-1.pdf,...).

It also makes saving easier and faster, because the unique date/timestamp is somehow unique and makes it easy to find documents.

### Environment data

iOS Latest, App latest, Nexcloud server latest

**Comment by vszakats** [comment]
The "File conflict" popup shows "Keep both" in the middle. There is a chance for mis-tapping and losing a previous scan.

The default name with a timestamp (e.g. `Scan-20230228-123456`) would be neat indeed.
And/or a sticky option for "Keep both", perhaps even enabled by default.

![File conflict](https://user-images.githubusercontent.com/1446897/222897046-f62b0c2c-db97-4c8a-b5c0-037344190f18.PNG)

**Comment by atomtigerzoo** [comment]
Hi vszakats - I think your annotation about the 'File conflict' should be a seperate issue and not be buried in mine, which is not about conflicts while saving. Consider moving it into a new issue maybe?

**Comment by vszakats** [comment]
I aimed to make the unique-filename proposal stronger, by telling the "user story" when experiencing the same UX issue. IMO the best fix for the popup is to not need it for every scan. A unique default filename fixes this.

**Comment by marinofaggiana** [comment]
already fixed for the next 4.8.0 now available in TestFlight

**Comment by atomtigerzoo** [comment]
That is great news @marinofaggiana - thank you!
