### ISSUE TITLE
App crashes trying to upload a big video file

### ISSUE THREAD

**Issue by togglecode** [nextcloud/ios#238]
On the beta version 2.17.3 (7) when I try to upload a big video file the app will crash and I cannot open the app after that anymore.

**Comment by marinofaggiana** [comment]
dimension ? (big)

**Comment by togglecode** [comment]
850 MB mov fole taken with camera (13 min)

The issue seems to be from firebase, i can give you the logs tomorrow if u need

**Comment by marinofaggiana** [comment]
try next version (8)

**Comment by togglecode** [comment]
@marinofaggiana It works, but if I completely close the app while downloading, then open it again the app keeps crashing. (Same file 850 mb)

**Comment by enoch85** [comment]
@togglecode Is this fixed in the latest version? Please close if it's the case.

**Comment by togglecode** [comment]
fixed in new version
