### ISSUE TITLE
Nextcloud Office in iOS mobile app unusable slow and always asking "nickname"

### ISSUE THREAD

**Issue by Andriel00** [nextcloud/ios#2380]
### Steps to reproduce

1. Opening eg. word document in Nextcloud iOS app
2. Setting editors nickname when prompted
3. Trying to use office by typing something

### Expected behaviour

Opening word document without asking for editors nickname and being able to normally use office without extreme lagging.

### Actual behaviour

On mobile (not on Web) it asks for an editors nickname always, before opening the document (which is the first unexpected thing). Editing the document is not possible due to extreme lagging (being the second unexpected). Everything works fine using the web platform via browser.

### Environment data

Recently updated to nextcloud v26 (hub 4).
Running up to date stand alone (not integrated CODE app) Collabora Server in Docker.

**Comment by G-T100** [comment]
Same here. 26.0 and latest Collabora Docker

**Comment by G-T100** [comment]
Is it realted to this...

[https://github.com/nextcloud/richdocuments/issues/2873](url)

**Comment by Andriel00** [comment]
> Is it realted to this...
> 
> [nextcloud/richdocuments #2873](https://github.com/nextcloud/richdocuments/issues/2873)

Seems like, thanks! There was an update to Nextcloud app today I think but did not change the behavior elaborated here unfortunately. It also looks like as it (the lagging) is more a problem with docx files. The undesired guest user login happens for all files.

**Comment by G-T100** [comment]
This is fixed with the latest Nextcloud Office release 8.0.1.
