### ISSUE TITLE
Favourites synchronisation and offline files between iOS and iPad

### ISSUE THREAD

**Issue by ghost** [nextcloud/ios#239]
I just installed the latest version of the nextCloud app from the AppStore on both my iPad and iPhone. I added several directories as favourites on the iPad, and flicked the switch to make favourites to be downloaded on the device. The iPad is currently in the process of downloading the files; hopefully there will be no problem here (the old ownCloud app had problems downloading the several gigabytes).

However, adding the nextCloud app on my iPhone as well, I was surprised that I could not see exactly those directories that I added to favourites on the iPad in the directory listing at all! Even more surprised, I found them in the favourites listing, however unable to access contents. I flicked the 'download favourites' switch, but my iPhone did not start downloading. I refreshed the main directory listing and those directories showed up there, but still no download happening. I added additional directories to favourites on the iPhone, but still nothing is being downloaded. I restarted the app (by shutting it down from the app switcher), but this also did not help. Again, the favourites are not shown in the directory listing unless I refresh it.

To me, there seems to be three issues:

1. Favourites somewhat undesirably synchronised between devices or, rather, downloaded files linked to favourites. This is a minor issue, and more of a request to think about. To me, Favourites stand for the few important documents I want to have quick access to. But I want all my research paper PDFs and other documents automatically synchronised on my device, for access on the plane, etc. (I used to use PDFExpert's WebDAV support for this, but that app has recently degraded into a total pile of you know what, so am looking for alternative solutions.) Also, I may not want to download the same set of files on all devices. 
2. The iPhone version of the app not showing favourites in the directory listing (without a manual refresh).
3. The iPhone version of the app not downloading favourites.

**Comment by vomout** [comment]
Update: after the file synchronisation finished, also the iPad app lost all favourite directories from the directory listing.
