### ISSUE TITLE
Connection Error : You do not have permission to complete the operation

### ISSUE THREAD

**Issue by puccaso** [nextcloud/ios#2394]
Hello everyone, 

is anyone else having this issue? i've seen many online regarding cloudflare tunnels but not this specifically. 

the website is setup behind cloudflare zerotrust/access, using a tunnel. https is provided via cloudflare. 
i can access the url via a browser, on mobile and desktop, but the app gives me this error. 
i've reset the app, hoping this would resolve it, then uninstall and reinstall but no juice 

i have a local nextcloud session running on nc.local, which works fine. complains about self signed ssl but i can add the domain fine.

what would be causing this?

### Steps to reproduce

1. install ios app
2. enter self hosted url
3. cry on the inside

### Expected behaviour
like accessing url via browser, should take me to login or confirmation screen. 
### Screenshots
![IMG_2873](https://user-images.githubusercontent.com/3234729/233670813-8318ebcc-be81-4fcd-b3fd-378aaeda2dba.png)

### Logs

**iOS version:** e.g. iOS 16.4.1

**Nextcloud iOS app version: 4.8.0.5

**Server operating system:**
ubuntu/docker

**Web server:** Apache, 

**Database:** POSTGRES

**Nextcloud version:** 26.0.0

**Comment by joshtrichards** [comment]
https://help.nextcloud.com/t/connection-error-you-do-not-have-permission-to-complete-the-operation/160765/5?u=jtr

**Comment by joshtrichards** [comment]
Closing since this is a config matter and there's a forum thread for it.

**Comment by joshtrichards** [comment]
@qoq The iOS client does support client certs (i.e. #2908).
