### ISSUE TITLE
Unable to use .txt or .csv offline despite "make available offline" marked

### ISSUE THREAD

**Issue by erikpaasonen** [nextcloud/ios#2404]
### Steps to reproduce

1. Create a `.csv` or `.txt` file on a computer
2. Sync the file to NC
3. Sync the file down to iOS device
4. Set the file as "Available Offline"
5. Download the file as any other "available offline" file, make sure it opens successfully
6. Disconnect networking, activate a VPN or otherwise simulate being out on the road with no access to the NC server (available only via LAN)
7. Try opening the file again (generates "The request timed out." error message)

### Expected behaviour

would like to open and edit any `.txt` and `.csv` files marked as available offline when actually... you know... offline.

### Actual behaviour

Error: `The request timed out.` 
in red at the top of the screen as a notification.

### Screenshots

![IMG_8797](https://user-images.githubusercontent.com/17558034/235306413-f0f0771f-66da-4404-a7b3-2cbd9c67c1de.PNG)
![IMG_8798](https://user-images.githubusercontent.com/17558034/235306414-2eff815b-93f4-4911-9a4c-2aaab791c10e.PNG)

### Reasoning or why should it be changed/implemented?

intuitively the term "make available offline" means I can still open the file from the local cache even if connectivity to the NC server is lost. this seems to work as expected for any other file type.

however, I noticed that for particular file types listed, with arbitrary file contents, there is something special about the file extension which causes the NC app to make a network request to the NC server. at face value it appears to be ignoring the "make available offline" flag.

would like to access files of these types even if truly "offline" from the NC server.

### Environment data

**iOS version:** iOS 15.7.5

**Nextcloud iOS app version:** Nextcloud Liquid for iOS 4.8.0.5

**Nextcloud version:** 25.0.3

**Comment by erikpaasonen** [comment]
yes this is still an issue on iOS 16.5.

what is the recommended path to achieve the offline functionality for text files then? all I need is the most basic of file text editing, but I do need to 1) store it in Nextcloud so it syncs across all my devices, and 2) edit it while offline (because I do not want to expose my NC server to the public internet at all).

it seems intuitively backward to disable offline for these types. instead it seems the functionality to _enable_ the offline types ought to be written instead? can there instead be a simple text editor bundled right into the NC app itself to perform these offline views/edits?

**Comment by mpivchev** [comment]
@tobiasKaminsky Is this the same for Android? Does the server manage text files as well? Meaning we can't make them offline.

**Comment by mpivchev** [comment]
Yes, I'm aware. But I'm not sure if it's the same on Android and if it's worth trying to improve this.

**Comment by mpivchev** [comment]
Makes sense. @tobiasKaminsky does Android work the same way?

**Comment by phil-lipp** [comment]
> yes this is still an issue on iOS 16.5.
> 
> 
> 
> what is the recommended path to achieve the offline functionality for text files then? all I need is the most basic of file text editing, but I do need to 1) store it in Nextcloud so it syncs across all my devices, and 2) edit it while offline (because I do not want to expose my NC server to the public internet at all).
> 
> 
> 
> it seems intuitively backward to disable offline for these types. instead it seems the functionality to _enable_ the offline types ought to be written instead? can there instead be a simple text editor bundled right into the NC app itself to perform these offline views/edits?

You could use the 'Nextcloud Notes' App from the iOS AppStore (not sure about android).

For that you would need to store the files in the /Notes/ Folder.

I personally would like the two applications to be merged, to make it more user-friendly. Having to install an individual App for each use-case is kinda bothersome

**Comment by mpivchev** [comment]
> > yes this is still an issue on iOS 16.5.
> > what is the recommended path to achieve the offline functionality for text files then? all I need is the most basic of file text editing, but I do need to 1) store it in Nextcloud so it syncs across all my devices, and 2) edit it while offline (because I do not want to expose my NC server to the public internet at all).
> > it seems intuitively backward to disable offline for these types. instead it seems the functionality to _enable_ the offline types ought to be written instead? can there instead be a simple text editor bundled right into the NC app itself to perform these offline views/edits?
> 
> You could use the 'Nextcloud Notes' App from the iOS AppStore (not sure about android).
> 
> For that you would need to store the files in the /Notes/ Folder.
> 
> I personally would like the two applications to be merged, to make it more user-friendly. Having to install an individual App for each use-case is kinda bothersome

This can be done but it's going to be a relatively big undertaking IMO. Also, what if someone only wants the Notes app and not Files? Or do you suggest having the Notes app integrated in Files while also having it separately in the AppStore?

**Comment by phil-lipp** [comment]
> > > yes this is still an issue on iOS 16.5.
> > > what is the recommended path to achieve the offline functionality for text files then? all I need is the most basic of file text editing, but I do need to 1) store it in Nextcloud so it syncs across all my devices, and 2) edit it while offline (because I do not want to expose my NC server to the public internet at all).
> > > it seems intuitively backward to disable offline for these types. instead it seems the functionality to _enable_ the offline types ought to be written instead? can there instead be a simple text editor bundled right into the NC app itself to perform these offline views/edits?
> > 
> > 
> > You could use the 'Nextcloud Notes' App from the iOS AppStore (not sure about android).
> > For that you would need to store the files in the /Notes/ Folder.
> > I personally would like the two applications to be merged, to make it more user-friendly. Having to install an individual App for each use-case is kinda bothersome
> 
> This can be done but it's going to be a relatively big undertaking IMO. Also, what if someone only wants the Notes app and not Files? Or do you suggest having the Notes app integrated in Files while also having it separately in the AppStore?

IMO Notes is the best example of the Nextcloud Apps that should be integrated as it provides offline access to files that are shown in the Files App - as presented in this issue. Other Apps like Deck or so on don't match that criteria so clearly and provide bonus features as I would call it.

**Comment by mpivchev** [comment]
I think it's clear that for now we will not implement this, as we rely on 3rd party dependencies that can't work offline. Changing this will be a very big undertaking that we currently can't do. Closing this for now.
