### ISSUE TITLE
Add test infrastructure

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#2417]
Similar to Android, Android Talk
- create CI test infrastructure
- add unit test
- add integration test
- add end to end test, with real server
- add screenshot test

**Comment by mpivchev** [comment]
Some more points:
- The build times for our [build](https://github.com/nextcloud/ios/actions/workflows/xcode.yml) iOS job are pretty high (50+ min each). There is most likely a way to optimize this, although it's out of the scope of this ticket.
- On Android side we use codecov as the test coverage suite, and we should probably use it on iOS as well.
