### ISSUE TITLE
Drop support for iOS 14

### ISSUE THREAD

**Issue by mpivchev** [nextcloud/ios#2436]
The project still supports iOS 14 and it causes problems with some functionality. Since iOS 14 is barely used anymore (<1%), we should remove it and the legacy code that goes with it, like `NCCreateFormUploadAssets`.

We might also consider dropping iOS15 since iOS17 is coming soonish.

**Comment by SystemKeeper** [comment]
Talked with @Ivansss about this and should be no problem from the talk side of things.
CC @nickvergessen for info

**Comment by Ivansss** [comment]
All good from Talk iOS side 👍
We will drop support for iOS 14 in the next major release

**Comment by SystemKeeper** [comment]
Also https://github.com/nextcloud/spreed/blob/master/docs/user-requirements.md for talk
