### ISSUE TITLE
SwiftLint pulled from Docker on every CI check, reached limit, check failing

### ISSUE THREAD

**Issue by mpivchev** [nextcloud/ios#2445]
We are getting this error with SwiftLint and the check fails:
```
  Step 1/11 : FROM norionomura/swiftlint:swift-5.1
  toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning: Docker build failed with exit code 1, back off 1.561 seconds before retry.
  /usr/bin/docker build -t d94681:8528efa20c424346995fabeca52067a1 -f "/home/runner/actions-runner/_work/_actions/norio-nomura/action-swiftlint/3.1.0/Dockerfile" "/home/runner/actions-runner/_work/_actions/norio-nomura/action-swiftlint/3.1.0"
  Sending build context to Docker daemon  145.9kB
```

Maybe we can find a way to cache this, change this action or [authenticate our PRs](https://docs.docker.com/docker-hub/download-rate-limit/?_gl=1*10cpogm*_ga*NzA1OTE3Njc3LjE2ODQ4NjMyMDE.*_ga_XJWPQMJYHQ*MTY4NTQ1MTEzNS40LjEuMTY4NTQ1MjI5NC4zNi4wLjA.#how-do-i-authenticate-pull-requests).

**Comment by tobiasKaminsky** [comment]
Where do you build this? Maybe you do not need to build it every time?
There is a GitHub action for it: https://github.com/norio-nomura/action-swiftlint#usage

Also there is a docker container: https://github.com/norio-nomura/docker-swiftlint/pkgs/container/swiftlint
It is directly available within GitHub and thus does not have this pull rate limit.

**Comment by mpivchev** [comment]
We are using the same GitHub action, but it still reached a limit.

**Comment by tobiasKaminsky** [comment]
I see that 3.2.1 is released, maybe this helps?

**Comment by tobiasKaminsky** [comment]
Hmm. Cannot help.
I see that this is indeed every time build…

**Comment by tobiasKaminsky** [comment]
Maybe create an issue and ask if the can provide a prebuilt docker image?

**Comment by mpivchev** [comment]
> I see that 3.2.1 is released, maybe this helps?

This seems to have worked. Closing this unless I see another error.
