### ISSUE TITLE
App uploads photos twice 

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#245]
* enable auto upload and pressing the "upload all existing photos" button
* having some files to be uploaded
* check the server logs:
   * PUT -> response 201 (new file created)
   * PUT to the same file -> response 204 (file overwritten) -> not needed
   * GET to the same file -> not needed

cc @marinofaggiana 

App version was build with 792a3a3

**Comment by MorrisJobke** [comment]
cc @cguerra @maej90

**Comment by marinofaggiana** [comment]
Bug why ? who has found this and why, this is not a bug this is a choice ? If I send to server 10.000 photos i need send 10.000 request to server exists file ?  
The correct procedure is ? rewrite ? skip ? question ?

**Comment by MorrisJobke** [comment]
> Bug why ? who has found this and why, this is not a bug this is a choice, If I send to server 10.000 photos i need send 10.000 request to server exists file ?
> The correct procedure is ? rewrite ? skip ? question ?

But you send 30.000 requests. We started the app and hooked up a proxy to monitor the network traffic. That is what we have seen. Why should you upload a file, upload it 2 seconds later again and then after this directly download it? This happened for dozens of files and was only triggered by enabling the "upload all existing photos" and then no interaction with the app happened.

**Comment by marinofaggiana** [comment]
Download ?  are you sure that the folder isn't favorite (sync files?) mmm no here is a strange ... it's possible reproduce the issue ?

Thanks

**Comment by MorrisJobke** [comment]
> Download ? are you sure that the folder isn't favorite (sync files?) mmm no here is a strange ... it's possible reproduce the issue ?

We did this on a device that I currently don't have - will retry next week, but I'm pretty sure it will happen again.

**Comment by marinofaggiana** [comment]
for security today I see this issue but now I have the 2.17.3 ... after I try. Thanks

**Comment by marinofaggiana** [comment]
For me is correct ...  4 file on camera roll, Send all ... only 4 upload, nothing download, no resend ... 
![schermata 2017-06-02 alle 14 20 02](https://cloud.githubusercontent.com/assets/8616947/26725393/a6b721b6-479e-11e7-8bdd-ec82c9c99d58.png)

**Comment by MorrisJobke** [comment]
I just experience in the past months a lot of those "WebDAV locked errors". Recently I noticed that some files are queued twice and then sometimes are being processed in parallel, which causes obviously a "Locked" error, because the iOS app wants tp upload to the very same location. Removing one of those two entries solves the issue:

![18-05-12 00-28-46 0541](https://user-images.githubusercontent.com/245432/40002108-01bf3b28-5790-11e8-8c8c-66c968394f29.png)

@marinofaggiana Could you check why some files are queued twice? This is quite critical, because this is the main reason I need to go into the app to check if the upload worked and fix the problem manually.

**Comment by marinofaggiana** [comment]
Yes @MorrisJobke I know this issue, is in ToDo the remake of queue.

**Comment by MorrisJobke** [comment]
> Yes @MorrisJobke I know this issue, is in ToDo the remake of queue.

Is there any ETA when this will make it into the app?

**Comment by MorrisJobke** [comment]
@marinofaggiana Any updates on this?

**Comment by marinofaggiana** [comment]
yes, I have correct several month ago :-)

**Comment by MorrisJobke** [comment]
> yes, I have correct several month ago :-)

Then close the ticket if this is solved :)
