### ISSUE TITLE
Comment is translatable _file_upload_not_exitst_

### ISSUE THREAD

**Issue by comradekingu** [nextcloud/ios#246]
https://github.com/nextcloud/ios/blob/9948b66226cabf6b16330b6d146d8f10ac8fa670/iOSClient/Library/OCCommunicationLib/OCCommunication.h

 OCErrorFileToUploadDoesNotExist = 120 //The file that we want upload does not exist

I don't think marking this as non-translatable is the solution, because that would probably already be in place were it spelt correctly in the translation resource string:

_file_upload_not_exitst_

And that comes from here I think: https://github.com/nextcloud/ios/blob/82359d9b0e7bf25b081afbb4da4b9b38f673141f/iOSClient/Supporting%20Files/en.lproj/Error.strings

**Comment by rakekniven** [comment]
Hmmh, why not editing file given with last link? Should I do that?

**Comment by comradekingu** [comment]
@rakekniven Yes, i wasn't 100% on that fixing the issue myself.

**Comment by rakekniven** [comment]
Outdated.
