### ISSUE TITLE
Add other Nextcloud apps to settings as suggestions

### ISSUE THREAD

**Issue by mpivchev** [nextcloud/ios#2460]
iOS Files:
- in settings: above "Transfers" with gap: Talk, Notes, "more apps"
- use same "more" icon as Desktop
- opens app if installed, if not open link to AppStore
- "more" -> open Appstore with filter for "Nextcloud"
- with multi account: open another app with correct account

_Originally posted by @tobiasKaminsky in https://github.com/nextcloud/files-clients/issues/10#issuecomment-1560748782_

Update:

- [ ] When opening another app from the Files app we should switch to the same account in the other app. This should only happen if that account is logged in the other app, otherwise we just open the app as if opening it from the app drawer.
- [ ] Notes app does not have multi-account support, or a deeplink URL. https://github.com/nextcloud/notes-ios/issues/40
- [ ] Talk app has no deeplink URL for switching accounts when opening app. https://github.com/nextcloud/talk-ios/issues/1286
- [x] Files app for now has implemented switching apps, but without account switching: https://github.com/nextcloud/ios/pull/2461

Until the above are finished, we will just open the apps as if opening them from the file drawer. No account switching or other functionality.

**Comment by mpivchev** [comment]
@tobiasKaminsky Not sure where to find this "More" icon. I can't find it on the site

**Comment by mpivchev** [comment]
This is rolled back for now since a bug was found where "Settings" would not show among other things (oops)

**Comment by mpivchev** [comment]
@marinofaggiana you mentioned you are not a fan of the design. Maybe we can discuss it here? @jancborchardt 

Current design: 

<img src="https://github.com/nextcloud/ios/assets/6960329/83b85ed5-3884-4aba-8c7f-8668dd724733" width="300" height="650">

**Comment by mpivchev** [comment]
Hmm, personally I'm not a fan of hamburger menus and they are not a native iOS component. No official iOS app uses them, and I've noticed apps that did use them slowly transitioned to removing them and using a tab bar instead, just as how we are now.

**Comment by mpivchev** [comment]
We can instead have an account tab with all the most useful and needed settings, and have a separate settings icon on the top right for more advanced settings that people don't use often. This is how Dropbox does it:

![image](https://github.com/nextcloud/ios/assets/6960329/6db60172-110f-42d4-a910-86fe2d74d392)

**Comment by mpivchev** [comment]
If we do decide on using a hamburger icon, then we can replace the More tab with a Shared tab instead, so users can quickly go to that instead of through settings as they do now

**Comment by mpivchev** [comment]
Better yet, we can let users customize where the last tab can lead to? Maybe Transfers, Recent, Activity, Shares, Group Folders, or Trash?

**Comment by mpivchev** [comment]
@marinofaggiana Should i reimplement the current design with the bug fixes or stop working on this for now?

**Comment by mpivchev** [comment]
We can also definitely redo this screen with SwiftUI, it's going to be easier to add Snapshot tests for it as well.

**Comment by tobiasKaminsky** [comment]
In my opinion, this issue/PR should be a quick win and not end up in a whole rewrite of UI.
This can and should be discussed in another issue, and then properly planned, as this might be a bigger task.

**Comment by mpivchev** [comment]
I'll reimplement this while fixing the bugs we found + adding the suggested design

**Comment by mpivchev** [comment]
> This way seems good but remain the issue with iPAD
> 

Yes, iPad might be a problem.

**Comment by mpivchev** [comment]
I also think the UI in general looks a bit dated in some regards, so a UI redesign might be a good thing, but it will require a lot of time obviously. @marinofaggiana We might propose this in next Clients Team meeting?

**Comment by tobiasKaminsky** [comment]
Please then create a new issue, with some proposals :)
