### ISSUE TITLE
Top buttons for create folder, upload, scan redundant

### ISSUE THREAD

**Issue by gennaios** [nextcloud/ios#2473]
Hello, 

I think there was a tine before such buttons were added. As they are already available with the plus button, i think they are unnecessary and removing them i think would make the app look much cleaner. I don't recall many other apps having such buttons outside of the title bar or bottom tab bar. As such, i think they do not look too great or fit the iOS look. At least an option to turn them off would be nice.

**Comment by jth134** [comment]
I agree. In the case you select a file, it would be nice if the buttons turned into “Select All”, “Move or copy files”,  and “Copy”. This would make the real estate the buttons take up more useful.

**Comment by gennaios** [comment]
Related,

When viewing deleted files, or other screens, perhaps such buttons could be moved to the action menu in the title bar. Example screen shots from Files iOS and Gmail; one can long hold a table row to have it selected, and then a bottom toolbar to delete or empty then appears.

![IMG_0032](https://github.com/nextcloud/ios/assets/12172/6e5395af-8166-440a-bfda-d89861a7f3be)
![IMG_0033](https://github
![IMG_0034](https://github.com/nextcloud/ios/assets/12172/7a88aa5c-a988-46cf-94f8-ad84e49fb6b5)
.com/nextcloud/ios/assets/12172/d09fdb86-d719-4f79-86d7-6944c302b54d)

**Comment by mpivchev** [comment]
Personally I agree with this sentiment, IMO the buttons don't need to be there anymore and look ugly. But, we also need to be mindful of users who are used to these buttons and use them often.

@marinofaggiana do you also think they should be removed?

**Comment by jancborchardt** [comment]
Agree they could be removed, doesn't seem like an iOS pattern do they? @marinofaggiana

**Comment by gennaios** [comment]
With the removal, the deleted files menu could use an easier way to select. With Mail, there's a select/deselect all in the title bar and then at the bottom restore, file, and delete. 

![image](https://github.com/nextcloud/ios/assets/12172/4b5ed4d5-2973-4650-8a3d-6fcb702f3f80)![image](https://github.com/nextcloud/ios/assets/12172/30b1e4bd-078c-4396-87fa-e1bbbe6f9c75)

**Comment by mpivchev** [comment]
Hi @gennaios. This issue has already been passed to `develop`. If you want to suggest something else, please create a new issue.
