### ISSUE TITLE
No editing of offline files possible, data loss

### ISSUE THREAD

**Issue by HansBorelius** [nextcloud/ios#2477]
Unfortunately, I'm not a developer and I can't judge if it's particularly hard to program the basic feature, namely the cloud function of nextcloud-ios-app. But that is the original task of nextcloud, the synchronization of files between the server and the end devices. As I understand it, this includes that you can work with the files even if the end device has no connection to the nextcloud server. For this purpose, you can mark the files as "available offline".

Most of the errors here describe exactly this unsolved problem. And it does not depend on the file type (application), but affects all applications (PDF, txt, Pages...). You can't work (change) properly with offline files on an Ipad. If you save the file after the first change, it is marked for synchronization and cannot be opened. If you cancel the synchronization, the changes are lost. Sometimes a first save works, sometimes not. If you use the Save as copy option, you have to create a new copy every time you close the program after a change.

I was able to reproduce this problem on my own server installation, as well as with a service provider.

The first message I found about the offline problem was from 2020 (https://help.nextcloud.com/t/nextlcoud-ios-integration-files-app-im-offline-modus/89732) and nothing has changed since then.

On the other hand, you should be able to synchronize calendars and contacts, even AI is integrated into nextcloud. This is also very commendable, because nextcloud offers companies the possibility to build a private cloud (on premise) or to rent from a European provider (to avoid the privacy problem of the US Cloud Act, Schrems II).

Unfortunately, one of these projects is now failing because the employees were equipped with IPads, but there is this problem with offline files in the IOS.

**Comment by HansBorelius** [comment]
Cooler Trick! Weil wir einen Grund gefunden haben, weil Text-Files nichjt funktionieren ( https://github.com/nextcloud/ios/issues/2404 ) , können wir auch den Fall schliessen, der grundsätzliche Probleme mit Offline Files meldet!

Die nextcloud-server wurden inzwischen ersetzt, damit auch die ios-user zuverlässig arbeiten können!

**Comment by mpivchev** [comment]
Hi Hans, please use English as the default language in this repo. Me and majority of others don't speak German (yet). In any case, I'm happy you seemed to have fixed the issue you have.
