### ISSUE TITLE
Why is there a fee for the official Nextcloud app on iOS but not Android?

### ISSUE THREAD

**Issue by schnappijedi** [nextcloud/ios#248]
Just wondering happy to pay. However why is there a fee for the official Nextcloud app on iOS but not Android?

Maybe a better place for this question would have been the community forums as it is not an issue per se.

**Comment by rakekniven** [comment]
Hello @schnappijedi ,

yes better discuss this on the forums. 
IIRC it has been discussed in the past. At least at the ownCloud forums.
That times to official Android app at googles play store was one buck as well.
