### ISSUE TITLE
Icloud

### ISSUE THREAD

**Issue by Gitter470** [nextcloud/ios#2482]
$ ssh-keygen -p -f ~/.ssh/id_ed25519
> Enter old passphrase: [Type old passphrase]
> Key has comment 'your_email@example.com'
> Enter new passphrase (empty for no passphrase): [Type new passphrase]
> Enter same passphrase again: [Repeat the new passphrase]
> Your identification has been saved with the new passphrase.

**Comment by mpivchev** [comment]
Please explain your issue in more detail. Reopen if this is updated.
