### ISSUE TITLE
IOS App 4.8.3.1 Not Recognizing when Multiple Files are selected to upload

### ISSUE THREAD

**Issue by blaine07** [nextcloud/ios#2492]
### Steps to reproduce

1. iOS APP Version 4.8.3.1
2. Try to upload MORE THAN one file at a time. 
3. Only one file will upload; of the few selected the one that uploads is at random. 

Logs appear as if the app thinks only ONE file was selected despite that several files were selected this started with iOS app update about 7 days ago. 

### Expected behaviour

If multiple files are selected in iOS app they should all upload. 

### Actual behaviour

Only one file uploads at random. 

### Screenshots

If applicable, add a screenshot showing the issue.

### Logs 

![IMG_5809](https://github.com/nextcloud/ios/assets/63940698/a144b082-bd40-4058-9dc6-ed92fce5ad2e)

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Environment data

**iOS version:** e.g. iOS 16.5.1

**Nextcloud iOS app version:** 4.8.3.1

**Server operating system:** Unraid 

**Web server:** Nginx Proxy Manager

**Database:**

**PHP version:**

**Nextcloud version:** 27

**Comment by mpivchev** [comment]
Thanks for the bug report. How are the files named? Do they have same or similar names?

**Comment by blaine07** [comment]
> Thanks for the bug report. How are the files named? Do they have same or similar names?

Different names, not particularly similar. PDF and ePUB file types mostly. Messing with different files doesn’t seem to change that it only wants to upload “one” file per attempt.

**Comment by mpivchev** [comment]
This is fixed here: https://github.com/nextcloud/ios/pull/2537 If you still have issues, please reopen this.
