### ISSUE TITLE
External share with email - 2 mails sent instead of 1

### ISSUE THREAD

**Issue by mpivchev** [nextcloud/ios#2521]
According to the report, 2 emails are sent when adding an email address to external share, one with the invite and the other with the invite + notes. Also, the email template they have is wrong.
The expected outcome is that only 1 email is sent with the invitation and the note with the proper template. The report says that on server and android it works fine.

I tried this and I get the same emails:

**First email with invite:**

<img width="500" alt="image" src="https://github.com/nextcloud/ios/assets/6960329/66442777-0771-4886-bd7d-032dd0dc27a2">

**Second email with invite + note:**

<img width="500" alt="image" src="https://github.com/nextcloud/ios/assets/6960329/7a534b63-e1de-4e66-8f05-6fb9d10caba8">

-------
When I looked at our email request, we send the request to `ocs/v2.php/apps/files_sharing/api/v1/shares` with the following params:

```
▿ 7 elements
  ▿ 0 : 2 elements
    - key : "password"
    - value : ""
  ▿ 1 : 2 elements
    - key : "hideDownload"
    - value : "false"
  ▿ 2 : 2 elements
    - key : "shareType"
    - value : "4"
  ▿ 3 : 2 elements
    - key : "permissions"
    - value : "31"
  ▿ 4 : 2 elements
    - key : "shareWith"
    - value : "someEmail@gmail.com"
  ▿ 5 : 2 elements
    - key : "publicUpload"
    - value : "false"
  ▿ 6 : 2 elements
    - key : "path"
    - value : "Test6"
```

This is the response we are getting:

```
 {"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"id":"5","share_type":4,"uid_owner":"ios","displayname_owner":"ios","permissions":31,"can_edit":true,"can_delete":true,"stime":1688721859,"parent":null,"expiration":null,"token":"bRGyA3Pjc6Z6JA2","uid_file_owner":"ios","note":"","label":"","displayname_file_owner":"ios","path":"\/Test6","item_type":"folder","mimetype":"httpd\/unix-directory","has_preview":false,"storage_id":"home::ios","storage":7,"item_source":781,"file_source":781,"file_parent":644,"file_target":"\/Test6","share_with":"someEmail@gmail.com","password":null,"password_expiration_time":null,"send_password_by_talk":false,"share_with_displayname":"someEmail@gmail.com","mail_send":0,"hide_download":0,"attributes":null}}}
```

**Comment by mpivchev** [comment]
From what I can see we don't handle emails or templates on the client side and only send a request for share with email, is that correct? @marinofaggiana

**Comment by tobiasKaminsky** [comment]
On Android we have a specific API, which allows to create share with note directly.
https://github.com/nextcloud/android-library/pull/772

**Comment by mpivchev** [comment]
Added this to a board as a planned feature
