### ISSUE TITLE
String "Loading..." is way to small

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#253]
While downloading file from cloud for viewing the following screen shows up.
On my 5s it is very hard to see and read the string.

Idea: Make font size bigger. Also the color could be more dominant e.g. black

![2017-05-29 20-46-24 6330](https://cloud.githubusercontent.com/assets/2069590/26575321/04a266cc-4525-11e7-9014-44b2b6591b32.png)

**Comment by rakekniven** [comment]
Issue #258 is related.

**Comment by marinofaggiana** [comment]
@rakekniven test 2.17.4 (5)

**Comment by rakekniven** [comment]
Latest Testflight version is 2.17.4 (4).
There a cannot see any changes. 

Have you seen #258 ?
Using a spinner would be awesome.

**Comment by marinofaggiana** [comment]
5 is available ... the #258 is a good

**Comment by rakekniven** [comment]
May I have to wait a little ... the german app store still shows (4).
Will provide feedback asap.

**Comment by rakekniven** [comment]
Hello @marinofaggiana it is better now with named Testflight version.
Will close this issue and hopefully you have time to make #258 possible.
👍
