### ISSUE TITLE
Cant update from Testflight to Build 2.17 (40)

### ISSUE THREAD

**Issue by Dirk23** [nextcloud/ios#254]
Hi,
i can see that there was/is a update for Nextcloud Beta App in Testflight, but i cant Update. Reason: "This Build i no longer available"
At the moment i have 2.17.3.0008 installed on my iPhone

Testflight still tells me that i could update!

**Comment by rakekniven** [comment]
Testflight for 2.17.3 is closed AFAIK.
New Testflight will be announced here for upcoming v2.17.4

And yes, I am seeing mentioned version as you.
And no, I do not know why ;-)

**Comment by rakekniven** [comment]
See new issue #260
