### ISSUE TITLE
Nextcloud App - Your input can't be opened. VLC is unable to open the MRL

### ISSUE THREAD

**Issue by DCCInterstellar** [nextcloud/ios#2563]
I am able to watch any videos on any web browser. Why am I getting this error when I play it on the app? Any idea's how to fix this or is it a bug?
The file I'm trying to open is owned by me. Not shared to anyone else. ![image](https://github.com/nextcloud/ios/assets/124222270/c0df0e28-6a18-4f8b-ba63-938e63ca65ff)

### **Marking this Issue as resolved. Please see: #2658**

**Comment by ioleto** [comment]
I have the same problem with the IOS app when I want to watch my videos

**Comment by Dimtar** [comment]
Also having the same issue, are you running NC behind a cloudflare tunnel?

**Comment by DCCInterstellar** [comment]
> Also having the same issue, are you running NC behind a cloudflare tunnel?

Yes I am.

**Comment by anderszon61** [comment]
Same problem here, NC behind a cloudflare tunnel?

**Comment by miles170** [comment]
I'm encountering the same problem with the iOS app, and Nextcloud is situated behind the CloudFlare proxy.
However, I can play the movie using Nextcloud on the web.

**Comment by DCCInterstellar** [comment]
So a little update. As of October 5, 2023, I'm still having this issue. However, I did find an alternative way to go around the issue. It's not the greatest but it works!

 When you go to your website through Google Chrome, Safari, or whatever browser you use on your mobile device. You can actually add a shortcut to your home screen to it and it's basically like the app! The downside is, that you always have to be connected to the internet for it to work. You can't have your files offline. But hey, it works!
![IMG_4043](https://github.com/nextcloud/ios/assets/124222270/a4ed58f7-b75d-4d6b-8b37-670b057b2070)

**Comment by nemeth27** [comment]
It’s still not fixed in version 4.9.  It’s now been months since this issue popped up.  There was a fix committed for 4.7.  Any idea what’s going on?

**Comment by vwccvr6** [comment]
Some with my girlfriends Iphone. On my Android device (and all other devices) everything is working normal.

**Comment by DCCInterstellar** [comment]
> Some with my girlfriends Iphone. On my Android device (and all other devices) everything is working normal.

That is good to know that your Android device is working but your girlfriend's iPhone is not. I'm using an iPhone as well. My brother has an Android device, I'll try the Nextcloud app on his phone to see if I get the same error.

**Comment by PnjDbq** [comment]
I'll add that I'm having the same issue.  Didn't have the issue before the iOS client changed media players.

My Nextcloud server is behind a NGINX Reverse Proxy.  
Can confirm the issue has something to do with proxy setup because (when I'm on home WiFi) I can use the iOS app with the 192.168.1 IP address, without going through the proxy, and media plays.

**Comment by ioleto** [comment]
My server is on ubuntu and I have this error on all the iOS I have tested. When you click to save the video offline, the video can be read in the application. Does anyone know where I can investigate or debug on the vlc stream?

**Comment by DCCInterstellar** [comment]
### **Marking this Issue as resolved. Please see: #2658 **
