### ISSUE TITLE
"Notifications" option missing in iOS App

### ISSUE THREAD

**Issue by leandro1212** [nextcloud/ios#2565]
### Steps to reproduce

1. Open App
2. Go to Hamburger option
3. "Notifications" missing

### Expected behaviour
Notifications option as in the last version.

Tell us what should happen.

### Actual behaviour
Missing the Notification option in Menu Options.
Notifications is quite important for login with a device.

Tell was what instead happens.

### Screenshots

If applicable, add a screenshot showing the issue.

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Environment data

**iOS version:** e.g. iOS 14.4.1

**Nextcloud iOS app version:** see More > Settings

**Server operating system:**

**Web server:** Apache, nginx

**Database:**

**PHP version:**

**Nextcloud version:** see Nextcloud admin page

**Comment by nickvergessen** [comment]
The notification bell icon is now in the top right on the home screen
