### ISSUE TITLE
Picture view is aliased

### ISSUE THREAD

**Issue by Gronis** [nextcloud/ios#257]
When comparing the quality of a photo opened in the Nextcould ios app, with the same photo opened in the original photos app from Apple, the quality of the picture is very different. There is nothing wrong with the image, as zooming in removes the aliasing artifacts. Is it possible to improve the quality somehow?

<img src="https://cloud.githubusercontent.com/assets/5390421/26788256/f1111422-4a0c-11e7-8814-5555652a596d.png" width="320px"/><img src="https://cloud.githubusercontent.com/assets/5390421/26788253/f0e685d6-4a0c-11e7-8e8b-b1c749f46773.png" width="320px"/>

**Comment by rakekniven** [comment]
Hey @Gronis Please add version of app when filing issues. Thank you.

**Comment by Gronis** [comment]
I'm using Nextcloud iOS v2.17.3.00009

**Comment by marinofaggiana** [comment]
Strange ... but the image in question is uploaded with Nextcloud iOS ? and the dimension ?

**Comment by Gronis** [comment]
Yes, it is uploaded automatically through ios app. Dimensions are 4032 × 3024. It seems to be sampling too few pixels during interpolation when zoomed out.
