### ISSUE TITLE
Use thumbnail while picture is downloading

### ISSUE THREAD

**Issue by Gronis** [nextcloud/ios#258]
When an image is clicked from the photos view, the image is fetched from the server if it does not exist locally. The loading-screen makes it hard to see what image is being loaded, which is very unsatisfying. 

Displaying the thumbnail and a loading circle instead of the current "Loading" label would give a much better user experience.

Something like the image to the right (blured thumbnail + loading spinner) should be better than the current implementation shown to the left:

<img src="https://cloud.githubusercontent.com/assets/5390421/26788834/c0ca54ac-4a0e-11e7-8366-c26fb971e548.png" width="320px"><img src="https://cloud.githubusercontent.com/assets/5390421/26804615/dd1ad6ba-4a48-11e7-857f-58749eaa6ecf.png" width="320px"/>

**Comment by Gronis** [comment]
Why is this closed? Was it not a desired change? Is it implemented? Was another conflicting design choice used?

**Comment by marinofaggiana** [comment]
sorry !
