### ISSUE TITLE
Theming does not work well with light colors

### ISSUE THREAD

**Issue by marbetschar** [nextcloud/ios#259]
It's awesome that the iOS app of Nextcloud applies the theming configured in the Nextcloud administration!!

Unfortunately this does not work well, if a light color is used such as `#F8F8F8`. In this case, the elements in the app are quite impossible to see - but in the web UI it looks gorgeous together with the chosen logo.

So it would be awesome to have this color in the web UI, but still the iOS app with readable colors. Maybe using same behaviour as in the web UI, which makes the icons dark automatically if a light color is used.

**Comment by marinofaggiana** [comment]
New algorithmic  for detect the theming light color, if  is too light color the tema is skipped and write a message error in Activity, available from 2.17.4.00011.

**Comment by marinofaggiana** [comment]
Solved.
