### ISSUE TITLE
Adjust or remove sort options in Media screen

### ISSUE THREAD

**Issue by mpivchev** [nextcloud/ios#2607]
While reviewing #2606, into discussion came the possibility of removing or changing the sorting options on the iOS side, since Android doesn't have them.

<img width="319" alt="image" src="https://github.com/nextcloud/ios/assets/6960329/b6ae3553-8ae1-4a20-9833-33c0a6fd4f10">

<img width="319" alt="image" src="https://github.com/nextcloud/ios/assets/6960329/9aa8bc02-e413-4e2e-956b-e13d2d10c996">

@marinofaggiana @jancborchardt @tobiasKaminsky what do you think?

**Comment by mpivchev** [comment]
IMO I think they should stay and Android should implement them as well.

**Comment by jancborchardt** [comment]
As during the discussion, I would still say the sorting options can be removed as they are much too detailed. Haven't seen another app either which does that, not even desktop file managers.

Agree with @marinofaggiana that a more relevant filter would be for pictures/videos like on Android.

**Comment by mpivchev** [comment]
So I will remove the sorting and change the filters

**Comment by intergalactic-mammoth** [comment]
Personally, I really really like the sorting options and do use them quite a bit. I'm not sure if that's a common experience for other users too though.

**Comment by juergen852** [comment]
There should be an option to chose "Default Sort Order".
Each folder I open is set to "Name" and I have to switch it every time to "Newest first".
