### ISSUE TITLE
In Media View, show new photos as indicator instead of auto scrolling to top

### ISSUE THREAD

**Issue by mpivchev** [nextcloud/ios#2612]
Related to: https://github.com/nextcloud/ios/pull/2606

Currently we scroll to the top when we load new photos in the Media View.

We should remember the position and instead add an indicator for new items, the way Twitter does it for example:

![image](https://github.com/nextcloud/ios/assets/6960329/dea5b514-c39a-485c-8f01-f131c52cbda2)

**Comment by tobiasKaminsky** [comment]
Estimation: 3 days (8h)

**Comment by mpivchev** [comment]
@nextcloud/designers @tobiasKaminsky @marinofaggiana 

This is how the button looks like. Is it ok?

<img width="555" alt="image" src="https://github.com/nextcloud/ios/assets/6960329/fe3ffc7b-d36b-4156-a1f8-ab6a20720cd0">

**Comment by nimishavijay** [comment]
Looks super nice! Would only add like 2-4px padding on the right, other than that all ok 👍
