### ISSUE TITLE
View "Capabilities" should not show red error icons

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#2625]
### Steps to reproduce

1. Open > Settings > Advanced > Capabilities

### Expected behaviour

Non-existing modules should NOT be displayed in red (error).
e. g. it is not an error if OnlyOffice is not present.

### Actual behaviour

Missing skills are indicated with a red cross.

### Screenshots

![2023-09-15 12-34-54 6962](https://github.com/nextcloud/ios/assets/2069590/9e806faa-55ce-4d93-9acc-e87347703f13)

**Comment by marcoambrosini** [comment]
I agree @rakekniven

**Comment by mpivchev** [comment]
@jancborchardt @tobiasKaminsky I agree with this, what do you think?
