### ISSUE TITLE
"More Apps" launches "Apple Store" not "App Store"

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/ios#2628]
### Steps to reproduce

1. Go to the "More tab"
2. Click on "More apps"

### Expected behaviour

The App Store launches.

### Actual behaviour

The Apple Store launches.

### Screenshots

<img src=https://github.com/nextcloud/ios/assets/33295590/017e591d-2e38-4ab6-abd3-867c578b15c2 width=60%>
<img src=https://github.com/nextcloud/ios/assets/33295590/5e15ecbe-f939-4ca0-987c-52d6f201bfe3 width=60%>

### Logs

```
n/a
```

### Environment data

**iOS version:** iPadOS 17.0.3

**Nextcloud iOS app version:** 4.9.0.16

**Server operating system:** Ubuntu

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.2

**Nextcloud version:** 27.1.1

**Comment by mpivchev** [comment]
This URL is supposed to open: https://www.apple.com/us/search/nextcloud?src=globalnav, but since you have the Apple Store app installed it leads to that instead.

**Comment by mpivchev** [comment]
Also let's please avoid snarky comments, I edited your post.

**Comment by thgoebel** [comment]
Why not use "itms-apps://search.itunes.apple.com/WebObjects/MZSearch.woa/wa/search?media=software&term=nextcloud" as the link? That [should open the App Store's](https://stackoverflow.com/questions/37576482/ios-app-store-search-url-scheme) search view, at least it does on my iPhone.

**Comment by mpivchev** [comment]
That might work, thanks, will try.
