### ISSUE TITLE
Double login!

### ISSUE THREAD

**Issue by JmeLche** [nextcloud/ios#264]
![regift gif](https://user-images.githubusercontent.com/29265841/26907330-991e2ad4-4bfb-11e7-9854-215e3d7e2404.gif)
Double login!

**Comment by marinofaggiana** [comment]
Hi @JmeLche do you have changed the password on server or do you have activated the 2fa ?

**Comment by JmeLche** [comment]
No

**Comment by marinofaggiana** [comment]
but if you re-insert the password ?

**Comment by JmeLche** [comment]
Ever its ok this

**Comment by marinofaggiana** [comment]
Very strange ... try Exit (Advanced Options, this remove Database) and try ricreate your account.

**Comment by mind22** [comment]
@marinofaggiana i think it's the same problem occurred a while ago #234  ... i closed it that time because it was to specific, but didn't appear again after update to .3

**Comment by rakekniven** [comment]
@JmeLche Which app version? Which iOS version?

**Comment by JmeLche** [comment]
10.3.2 iOS

**Comment by rakekniven** [comment]
And your nextcloud app version?

**Comment by JmeLche** [comment]
problem solved when I changed the password

**Comment by JmeLche** [comment]
11.0.2

**Comment by JmeLche** [comment]
The version of app is 2.17.3

**Comment by rakekniven** [comment]
@JmeLche So we can close issue?

**Comment by JmeLche** [comment]
Yes,thanks
