### ISSUE TITLE
Make downloaded files indicator more obvious

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#265]
The only indicator if a file is downloaded or not is a little filled circle. If the file is not downloaded yet it is an empty circle:

![2017-06-07 22-10-14 5144](https://user-images.githubusercontent.com/245432/26910845-05678d2a-4bcf-11e7-9df6-e798aa34dec5.png)

On android we use a green checkmark as badge to indicate a downloaded file, which is a bit more obvious.

![screenshot_20170607-221444](https://user-images.githubusercontent.com/245432/26910877-43ee3cc4-4bcf-11e7-9de7-8ddd5be09931.png)

any other feedback @nextcloud/designers @marinofaggiana @oparoz ?

**Comment by oparoz** [comment]
Good idea to make them match. The green check mark is indeed more obvious.

**Comment by marinofaggiana** [comment]
@MorrisJobke @oparoz @jancborchardt true, the green mark  is more obvious but we want this ? 
The "normal" user don't know the difference from "local file" "cloud file" ... the normal user tap on file and stop ... others "cloud app" don't view this difference ... 

I think that this icon is only a nerd icon :D no ??

**Comment by oparoz** [comment]
I think this is more than just indicating if a file is local.
We want to know if the file has been synchronised, because it's important that both the local and remote files are the same.
I also find it useful to know if I already have a local copy, but I haven't done any usability study on that...

**Comment by marinofaggiana** [comment]
Available on TestFlight 2.17.4 (6)

![simulator screen shot 08 giu 2017 12 54 26](https://user-images.githubusercontent.com/8616947/26925321-abec5d40-4c49-11e7-9a5f-abcf89952983.png)

**Comment by MorrisJobke** [comment]
You rock :rocket:

![img_5145](https://user-images.githubusercontent.com/245432/26930614-8a52cd8e-4c23-11e7-9784-5fa8715a9f3b.PNG)

**Comment by jancborchardt** [comment]
@marinofaggiana just two details: Can we move the sync status to the bottom right (like it is on macOS desktop). And the star to the top right?

**Comment by MorrisJobke** [comment]
> @marinofaggiana just two details: Can we move the sync status to the bottom right (like it is on macOS desktop). And the star to the top right?

Let's create a new ticket for this

**Comment by MorrisJobke** [comment]
#270
