### ISSUE TITLE
Nextcloud App  BUG REPORT - Your input can't be opened. VLC is unable to open the MRL

### ISSUE THREAD

**Issue by DCCInterstellar** [nextcloud/ios#2658]
**### Original Post: #2563** 

### Steps to reproduce

1. Nextcloud is being hosted via Docker Container, using Cloudflare Tunneling, and behind Nginx Proxy Manager to export it out to the internet
2. Play any video using the Nextcloud App that is not downloaded to your iPhone.

### Expected behaviour
- _Allows you to play any videos through the Nextcloud app without receiving any errors_

### Actual behaviour
- _When you play any video on any IOS device. You get an error that says "Your input can't be opened. VLC is unable to open the MRL"_

### Screenshots

![image](https://github.com/nextcloud/ios/assets/124222270/b135da13-0186-4bc2-b35c-309b3d064f2f)

### Logs

```
[internet_connection_check] Error: GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 30000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://www.nextcloud.com/ at <<closure>>

 0. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 158
    GuzzleHttp\Handler\CurlFactory::createRejection("*** sensitive parameters replaced ***")
 1. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 110
    GuzzleHttp\Handler\CurlFactory::finishError(["GuzzleHttp\\Handler\\CurlHandler"], "*** sensitive parameters replaced ***", ["GuzzleHttp\\Handler\\CurlFactory"])
 2. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 47
    GuzzleHttp\Handler\CurlFactory::finish(["GuzzleHttp\\Handler\\CurlHandler"], "*** sensitive parameters replaced ***", ["GuzzleHttp\\Handler\\CurlFactory"])
 3. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 137
    GuzzleHttp\Handler\CurlHandler->__invoke("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
 4. /var/www/html/lib/private/Http/Client/DnsPinMiddleware.php line 154
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 5. /var/www/html/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 35
    OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}("*** sensitive parameters replaced ***")
 6. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 31
    GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
 7. /var/www/html/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 71
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 8. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 63
    GuzzleHttp\RedirectMiddleware->__invoke("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
 9. /var/www/html/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php line 75
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
10. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 331
    GuzzleHttp\HandlerStack->__invoke("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
11. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 168
    GuzzleHttp\Client->transfer("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
12. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 187
    GuzzleHttp\Client->requestAsync("*** sensitive parameters replaced ***")
13. /var/www/html/lib/private/Http/Client/Client.php line 230
    GuzzleHttp\Client->request("*** sensitive parameters replaced ***", "http://www.nextcloud.com/", ["/var/www/html/ ... e])
14. /var/www/html/apps/settings/lib/Controller/CheckSetupController.php line 224
    OC\Http\Client\Client->get("http://www.nextcloud.com/")
15. /var/www/html/apps/settings/lib/Controller/CheckSetupController.php line 206
    OCA\Settings\Controller\CheckSetupController->isSiteReachable("www.nextcloud.com")
16. /var/www/html/apps/settings/lib/Controller/CheckSetupController.php line 921
    OCA\Settings\Controller\CheckSetupController->hasInternetConnectivityProblems()
17. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Settings\Controller\CheckSetupController->check()
18. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Settings\ ... "], "check")
19. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Settings\ ... "], "check")
20. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "check", ["OC\\AppFramewo ... "], ["settings.CheckSetup.check"])
21. /var/www/html/lib/base.php line 1068
    OC\Route\Router->match("/settings/ajax/checksetup")
22. /var/www/html/index.php line 36
    OC::handleRequest()

GET /settings/ajax/checksetup
from PUBLIC IP ADDRESS by daviscoleclark at 2023-11-06T23:55:21+00:00
```

### Environment data

**iOS version:**
- iOS 17.1

**Nextcloud iOS app version:** see More > Settings
- Nextcloud Liquid for iOS 4.9.1.0

**Server operating system:**
- Unraid

**Web server:**
- Ngnix

**Database:**
- MariaDB - MySQL v10.11.5

**PHP version:**
-  8.2.12

**Nextcloud version:** 
- 27.1.3

### **IMPORTANT UPDATE AS OF DECEMBER 24, 2023 ABOUT THIS ISSUE**

**FIX**
- According to @Nikki1993's, @evsrt's, and including a Reddit post that I posted about a month and a half ago. Nextcloud's video player in the Nextcloud app doesn't support TLS 1.3, only 1.2. In my Cloudflare Account, I was forcing TLS 1.3 but I did downgrade it to TLS 1.2 which did solve the issue!

I'm keeping this issue open for a couple of more weeks just in case if anyone has any questions, issues, or suggestions.

Thank you everyone for sharing your logs, devices you have used, and your configuration of Nextcloud Instance that you are using. Hopefully, Nextcloud will be able to fix this issue in the coming months

**Comment by MK796** [comment]
Same for me... 

But the problem has worsened. Now I'm not able to view media within my priv network and from remote...

Client and Server are up to date. (22.11.23)

**Comment by evsrt** [comment]
I faced this problem and I managed to solve it in the following way.

1. Enabled info for error.log

```
# logging in server context
access_log              /var/log/nginx/access.log combined buffer=512k flush=1m;
error_log               /var/log/nginx/error.log info;
```

2. When trying to play the video, an error appeared in the log

```
2023/12/21 09:30:12 [info] 33343#33343: *2410 SSL_do_handshake() failed (SSL: error:0A000102:SSL routines::unsupported protocol) while SSL handshaking, client: 213.247.231.106, server: 0.0.0.0:443
2023/12/21 09:30:12 [info] 33343#33343: *2411 SSL_do_handshake() failed (SSL: error:0A000102:SSL routines::unsupported protocol) while SSL handshaking, client: 213.247.231.106, server: 0.0.0.0:443
2023/12/21 09:30:12 [info] 33343#33343: *2412 SSL_do_handshake() failed (SSL: error:0A000102:SSL routines::unsupported protocol) while SSL handshaking, client: 213.247.231.106, server: 0.0.0.0:443
```


3. Included the following parameters in the nginx.conf in the http context
```
# Mozilla Intermediate configuration
# https://ssl-config.mozilla.org/#server=nginx
ssl_protocols          TLSv1.2 TLSv1.3;
ssl_ciphers            ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

```

In conclusion, the error was that in my nginx.conf only TLSv.1.3 was enabled.

**Comment by Nikki1993** [comment]
> I faced this problem and I managed to solve it in the following way.
> 
> 1. Enabled info for error.log
> 
> ```
> # logging in server context
> access_log              /var/log/nginx/access.log combined buffer=512k flush=1m;
> error_log               /var/log/nginx/error.log info;
> ```
> 
> 2. When trying to play the video, an error appeared in the log
> 
> ```
> 2023/12/21 09:30:12 [info] 33343#33343: *2410 SSL_do_handshake() failed (SSL: error:0A000102:SSL routines::unsupported protocol) while SSL handshaking, client: CLIENT_IP, server: 0.0.0.0:443
> 2023/12/21 09:30:12 [info] 33343#33343: *2411 SSL_do_handshake() failed (SSL: error:0A000102:SSL routines::unsupported protocol) while SSL handshaking, client: CLIENT_IP, server: 0.0.0.0:443
> 2023/12/21 09:30:12 [info] 33343#33343: *2412 SSL_do_handshake() failed (SSL: error:0A000102:SSL routines::unsupported protocol) while SSL handshaking, client: CLIENT_IP, server: 0.0.0.0:443
> ```
> 
> 3. Included the following parameters in the nginx.conf in the http context
> 
> ```
> # Mozilla Intermediate configuration
> # https://ssl-config.mozilla.org/#server=nginx
> ssl_protocols          TLSv1.2 TLSv1.3;
> ssl_ciphers            ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
> ```
> 
> In conclusion, the error was that in my nginx.conf only TLSv.1.3 was enabled.
> 
> ```
> # comment this string
> #ssl_protocols          TLSv1.3;
> ```

hm doesn't work for me. I have both TLS 1.2 and 1.3, same ciphers (even 1 more). I don't see same error in error.log so far. I am using linuxserver setup if that at all relevant.

**Comment by Nikki1993** [comment]
@DCCInterstellar I figured it out (at least for me). Courtesy of @evsrt I realized that while my NGINX config did accept 1.2 and 1.3 TLS, Cloudflare minimum was set to TLS 1.3. Setting TLS min to 1.2 fixed the issue for me entirely. 

![image](https://github.com/nextcloud/ios/assets/1446529/bcafa4b1-7389-471d-9547-f1c98f3f85b7)


![image](https://github.com/nextcloud/ios/assets/1446529/b0b73550-d063-456d-912c-8292cb67c36f)

**Comment by tflidd** [comment]
I just got a bit involved in a topic on the forum (https://help.nextcloud.com/t/ios-app-cant-play-mp4-from-smb-storage-browser-can/177307), and for my setup it works with nginx and TLSv1.3. But I don't use any additional proxy.

So as far as the current problems were analyzed and fixed, it is not related to the media player at all. Not sure why it only happens to the media player, and what cipher each part (NC app, media player, ...) supports.

**Comment by DCCInterstellar** [comment]
### **IMPORTANT UPDATE AS OF DECEMBER 24, 2023 ABOUT THIS ISSUE**

**FIX**
- According to @Nikki1993's, @evsrt's, and including a Reddit post that I posted about a month and a half ago. Nextcloud's video player in the Nextcloud app doesn't support TLS 1.3, only 1.2. In my Cloudflare Account, I was forcing TLS 1.3 but I did downgrade it to TLS 1.2 which did solve the issue! 

I'm keeping this issue open for a couple of more weeks just in case if anyone has any questions, issues, or suggestions.

Thank you everyone for sharing your logs, devices you have used, and your configuration of Nextcloud Instance that you are using. Hopefully, Nextcloud will be able to fix this issue in the coming months

**Comment by Nikki1993** [comment]
Wouldn't go as far as to claim Nextcloud in general doesn't support TLS 1.3, I've tested on Android with TLS 1.3 only and it does work, the issue seems to be only for iOS client and only with video player specifically so it could be a very specific bug with cloudflare tunnel + nginx + iOS combo. 

I do agree and hope that Nextcloud team will be able take it from here.

**Comment by ioleto** [comment]
Hello I’m on apache2, I’have test site only tls 1.3 and only tls 1.2 and nothing appened. It’s doesn’t work for me

**Comment by tflidd** [comment]
> Hello I’m on apache2, I’have test site only tls 1.3 and only tls 1.2 and nothing appened. It’s doesn’t work for me

As I mentioned, my nginx config with TLSv1.3 only, it works with the iOS app (in the linked forum topic, I shared the cipher selection that worked for me). And I don't use any proxies.

> it could be a very specific bug with cloudflare tunnel + nginx + iOS combo

Yes, it seems a bit if like an additonal reverse proxy is involved, the available SSL ciphers seem to play a crucial role.
The only thing the iOS client can do, is to check the current available ciphers, if they are up to date (perhaps cloudflare requires a different set of TLS 1.3 ciphers). Or between cloudflare and the Nextcloud server.

**Comment by ondrejlohnisky** [comment]
The issue still persist for me on iOS.
Server runs on nginx without any proxy or cloudflare.
I tried every possible combination of ssl setting and it seems for me it is not a ssl problem.

**Comment by ioleto** [comment]
> The issue still persist for me on iOS. Server runs on nginx without any proxy or cloudflare. I tried every possible combination of ssl setting and it seems for me it is not a ssl problem.

Same for me, server run on Apache and the problem still persist on IOS but not on android and not on the web.

**Comment by obervinov** [comment]
The same problem. It only works if you download the video file offline and after that it will be played.

**Comment by ioleto** [comment]
Exactly the same thing for me…

**Comment by weijiangan** [comment]
If you are using Nginx make sure your ssl_protocols version specifies TLS 1.2, or simply remove the ssl_protocols line, and make sure that your config is included BEFORE other sites. You can include it manually if you are using the sites-available pattern or name it in such a way it gets loaded first such as 00_nextcloud.conf. Took me a long time to figure this out

**Comment by ondrejlohnisky** [comment]
I made sure and did everything that people was suggesting but i can't get rid of the error. I feel like it must be problem with the iOS app.
Here is my nextcloud cleared log of that specific error:
```
2024-11-26 06:38:09 Network request started: POST https://<redacted-domain>/ocs/v2.php/apps/dav/api/v1/direct
2024-11-26 06:38:09 Network request headers: ["User-Agent": "Mozilla/5.0 (iOS) Nextcloud-iOS/6.1.6", "OCS-APIRequest": "true", "Content-Type": "application/x-www-form-urlencoded", "Accept": "application/json", "Authorization": "Basic <redacted>"]
2024-11-26 06:38:09 Network request body: fileId=9822175&format=json
2024-11-26 06:38:10 Network response result: 2024-11-26 06:38:10 [Request]: POST https://<redacted-domain>/ocs/v2.php/apps/dav/api/v1/direct
    [Headers]:
        Accept: application/json
        Authorization: Basic <redacted>
        Content-Type: application/x-www-form-urlencoded
        OCS-APIRequest: true
        User-Agent: Mozilla/5.0 (iOS) Nextcloud-iOS/6.1.6
    [Body]: 26 bytes
[Response]:
    [Status Code]: 200
    [Headers]:
        Cache-Control: no-cache, no-store, must-revalidate
        Content-Encoding: gzip
        Content-Length: 186
        content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
        Content-Type: application/json; charset=utf-8
        Date: Tue, 26 Nov 2024 05:38:10 GMT
        feature-policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
        referrer-policy: no-referrer
        Server: nginx
        Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
        x-content-type-options: nosniff
        x-download-options: noopen
        x-frame-options: SAMEORIGIN
        x-permitted-cross-domain-policies: none
        x-request-id: <redacted>
        x-robots-tag: noindex, nofollow, noindex, nofollow
        x-xss-protection: 1; mode=block
    [Body]:
        {"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"url":"https://<redacted-domain>/remote.php/direct/<redacted>"}}}
[Network Duration]: 0.4087810516357422s
[Serialization Duration]: 1.5874999917286914e-05s
[Result]: success(196 bytes)
2024-11-26 06:38:10 Network response all headers: 2024-11-26 06:38:10 Optional([AnyHashable("Strict-Transport-Security"): max-age=15768000; includeSubDomains; preload, AnyHashable("x-content-type-options"): nosniff, AnyHashable("x-robots-tag"): noindex, nofollow, noindex, nofollow, AnyHashable("Cache-Control"): no-cache, no-store, must-revalidate, AnyHashable("Content-Encoding"): gzip, AnyHashable("referrer-policy"): no-referrer, AnyHashable("Date"): Tue, 26 Nov 2024 05:38:10 GMT, AnyHashable("feature-policy"): autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none', AnyHashable("Content-Type"): application/json; charset=utf-8, AnyHashable("x-frame-options"): SAMEORIGIN, AnyHashable("Server"): nginx, AnyHashable("x-request-id"): <redacted>, AnyHashable("x-download-options"): noopen, AnyHashable("x-xss-protection"): 1; mode=block, AnyHashable("x-permitted-cross-domain-policies"): none, AnyHashable("Content-Length"): 186, AnyHashable("content-security-policy"): default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'])
```
