### ISSUE TITLE
@SystemKeeper, I got an update on the backslash issue in Nextcloud Talk iOS (v17.1.1).

### ISSUE THREAD

**Issue by tktbobto** [nextcloud/ios#2671]
@SystemKeeper, I got an update on the backslash issue in Nextcloud Talk iOS (v17.1.1). 
When I type paths like c:\test\test.txt or use backticks like `c:\test\test.txt`, it looks fine in the browser. 
But in the iOS app, backslashes are missing (shows as c:testtest.txt). 
Attached screenshots for clarity :

![image](https://github.com/nextcloud/spreed/assets/150776239/caca7add-a1e0-4599-abd2-8a5d9d77af3e)
![image](https://github.com/nextcloud/spreed/assets/150776239/d2e82b4b-916d-4e26-9e2a-052e098f9e22)
![image](https://github.com/nextcloud/spreed/assets/150776239/24c1c5da-aba3-45fe-8375-897b91da9d9c)

Could this be a Markdown feature bug? How can I disable markdown to test if it fixes the problem?

Thanks for any help!

_Originally posted by @tktbobto in https://github.com/nextcloud/talk-ios/issues/1422#issuecomment-1809812042_

**Comment by SystemKeeper** [comment]
Thanks :) The issue got already moved: https://github.com/nextcloud/talk-ios/issues/1422 so closing this for now.
