### ISSUE TITLE
Integration into Files (iOS 11)

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/ios#268]
![img_0006](https://user-images.githubusercontent.com/19711361/26948494-db8103ce-4c96-11e7-9cf5-fae075af1b95.JPG)

New Files-app in iOS 11 provides the possibility to integrate external storages... Currently Dropbox and Box... Microsoft and Adobe will come. I think it would make sense to integrate Nextcloud here.

@marinofaggiana @MorrisJobke

**Comment by MorrisJobke** [comment]
👍

**Comment by marinofaggiana** [comment]
@MariusBluem  sure !

**Comment by koalalorenzo** [comment]
Do we have an ETA for this? It would be awesome!

**Comment by MariusBluem** [comment]
@koalalorenzo There is no stable iOS 11 yet, so no 🙈🙈😅

**Comment by koalalorenzo** [comment]
What about, after iOS 11 is published? Will it be considered as high priority task?

**Comment by MariusBluem** [comment]
> @MariusBluem sure !

I think the „sure“ of our iOS developer indicates, that there is some priority on this task. But if you want to contribute to it - go for it 🙈

**Comment by marinofaggiana** [comment]
The last beta 7 of iOS 11 and Xcode 9 Beta is a good version (near to GM), after this 2.17.6 I start with compatibility of iOS 11 (bug, fix, etc.) but for now some library (for ex. Realm) are not yet available for iOS 11 ...

**Comment by vekunz** [comment]
iOS 11 is now released

**Comment by MariusBluem** [comment]
> iOS 11 is now released

Thanks for keeping us updated 😜🙈

**Comment by Tmargo101** [comment]
Any idea if integration into Files or the new Drag and Drop features is coming to the Nextcloud App?  Would be absolutely amazing!

**Comment by koalalorenzo** [comment]
The File integration, BTW, seems possible! I am using File with Transmit. Cool uh? 👍

**Comment by marinofaggiana** [comment]
In this moment we are develop the compatibility of iOS 11 API and iPhone X, the integration with new File App is calendarize in a second moment

**Comment by vekunz** [comment]
Any news yet? After the release notes of the latest updates, iPhone X seems to be supported by now.
Nextcloud, however, would still be faster than Microsoft if files are supported in the near future 😁

**Comment by MariusBluem** [comment]
@vekunz the Nextcloud iOS App receives permanent improvements and we focus on stability instead of mass of unstable features - files integration is on the roadmap and should arrive in the more or less near future ... but please understand that improvements and bugfixes of features that are already implemented come always first. 

Asking for this again and again will not make this real faster in any way ... the feature is tracked - this is everything that can be done now by somebody who is not an magician 🎩 or - well an iOS developer...

**Comment by koalalorenzo** [comment]
@MariusBluem hopefully somebody will define the priorities (the one coming after the bugfixes) based on the customers'/users' requests 👍 Please tell us that this is one of them

**Comment by jeromeof** [comment]
How do we get this prioritized? Of all the cloud file applications I have (Dropbox, Box, iCloud Drive, Google Drive and recently OneDrive) NextCloud is the only one now not integrated correctly with IOS11 Files. It would be fantastic to have all these services available with simple drag drop between them or even use the Files App Favourites and Tags functionality with my NextCloud files.

**Comment by pagaille** [comment]
+1 :-)

**Comment by matamn** [comment]
+1

**Comment by marinofaggiana** [comment]
Hi boys, work in progress 👍

**Comment by vekunz** [comment]
It‘s finally there. Thank you!

**Comment by borco** [comment]
Enabling **Background App Refresh** in the **Settings > Nextcloud** allowed _Files_ to download 212KB out of 4.2MB. And then is stopped at that. After 30 sec, still nothing else.

**Comment by vomout** [comment]
Not working: "Content unavailable. The folder contents could not be displayed because of an unknown error."

**Comment by marinofaggiana** [comment]
Please this issue is closed. Create a new issue. Thanks
