### ISSUE TITLE
List of files currently uploading

### ISSUE THREAD

**Issue by wallenium** [nextcloud/ios#269]
When in enable the upload feature (photos/videos), the red batch with the number of files is visible. Is there an additional list of files currently uploading? Would be nice to have :)

**Comment by marinofaggiana** [comment]
The red budget number cont the files in upload+download queue

**Comment by wallenium** [comment]
Yes. And is there a possibility to see these files? A list of it?

**Comment by marinofaggiana** [comment]
on Transfer View (last 10+)

**Comment by wallenium** [comment]
Ah, ok. Got it. Searched in the menu on top, not under more.. works for me. Anyway, maybe add a link to the three-dot-menu in files?

**Comment by rakekniven** [comment]
Hello @wallenium See my comment on Testflight thread. 
Please open new issue for your latest idea if you like to see it added.
Will close this one.
