### ISSUE TITLE
Multiple files upload at the same time

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/ios#27]
Hello

I have a idea, multiple images upload to server at same time for mobile app, like OneDrive app
Is it possible?

Photos one by one uploading and It can take a long time. For this reason, application can be upload photos more than one, maybe 5 or 6 photos uploading at the same time.

[#793 - ownCloud](https://github.com/owncloud/ios/issues/793)

**Comment by marinofaggiana** [comment]
Hi @emresaracoglu increasing the number of files simultaneously does not increase the efficiency (perhaps best for very small files) and if you upload file of big dimensions the memory is quickly saturated, I think it is not a good idea ...

**Comment by ahmedvolks** [comment]
Hello,
I have a 10 internet DSL lines and I need to upload a file to next cloud in my company, 
I know that I can compress file into zipped parts. But after doing this. Can next cloud accept multiple files upload at same time?

**Comment by johkoenig** [comment]
Parallel up/download is implemented for quite some time.
