### ISSUE TITLE
Improve badges

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#270]
By @jancborchardt from #265 

Can you move the green status icon to the bottom right (like on MacOS), and the star to the top right (next to the filename)?

cc @marinofaggiana @mario

**Comment by oparoz** [comment]
This would actually make it look different than on Android and it's more important than macOS.

**Comment by marinofaggiana** [comment]
please one style for all systems :-)

**Comment by jancborchardt** [comment]
Well on Android it should be the same. Amd @mario and I talked about this last hackweek already.

**Comment by mario** [comment]
Favorite icon - top right of the mimetype icon/content preview
Status icon - bottom right
Downloaded/synced status - left of the status icon

I'm sure there's fourth icon somewhere between favorite and status icon but I forgot what xD

This is of course in the list view.

All of this was implemented under @jancborchardt supervision, and is actually one of his better ideas :p

**Comment by marinofaggiana** [comment]
better ideas .... OMG ... 🙈

**Comment by marinofaggiana** [comment]
done.

**Comment by jancborchardt** [comment]
Thank you! :)
