### ISSUE TITLE
Being in a subfolder searching "all folders" is not possible

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#272]
* browse in a subfolder
* open the search
* expected: there should be a way to search in "all folders"
* actual: there is only "this folder" and "this folder and all subfolders"

I think this is similar to what @jancborchardt proposed in #150 we should do a filtering by default (I guess this is what "this folder" does) and then do a search in "all folders" instead of "this folder and all subfolders".

As a first iteration it's fine to change the "this folder and all subfolders" to a "all folders", but as big goal we should do it like it is described in #150.

@nextcloud/designers @marinofaggiana

**Comment by MorrisJobke** [comment]
@mario @marinofaggiana This is done in the develop branch, right?

**Comment by marinofaggiana** [comment]
yes.
