### ISSUE TITLE
Notification when upload finished

### ISSUE THREAD

**Issue by ghost** [nextcloud/ios#273]
Hi!

This issue is rather a suggestion of extending functionality of the app than it's an issue. The suggestion applies also to the Android project.

### Actual behaviour
After I have selected say 15 photos for upload via the share-button in the iOS gallery app and upload finished, it will finish without notification.

### Suggestion
I would like to get a notification telling me something like "Finished uploading 15 files".

**Comment by contribguy** [comment]
Nextcloud/android#1092
