### ISSUE TITLE
🗃️ "Personal files" view

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/ios#2748]
Client alignment with newly introduced server view via https://github.com/nextcloud/server/issues/42919

**Comment by tobiasKaminsky** [comment]
@marinofaggiana @mpivchev do you have an idea where to put it?

On Android it is very straight forward.
It is a filter on root view only, limiting files/folders to
- owned by user
- no groupfolders
- no incoming shares

![2024-01-26-081730](https://github.com/nextcloud/ios/assets/5836855/c41c009c-00aa-4be1-8096-42a6578f6665)

**Comment by mpivchev** [comment]
![image](https://github.com/nextcloud/ios/assets/6960329/8feb9e6c-6585-4b0c-86a4-496fedd3887f)

We are planning to add a dropdown menu to top right bar in #2744 , so we can put it inside.

**Comment by AndyScherzinger** [comment]
@marinofaggiana bug to be fixed, reported on server: https://github.com/nextcloud/server/issues/44359
