### ISSUE TITLE
original filename is ignored when document is handed over from another app

### ISSUE THREAD

**Issue by Chingato** [nextcloud/ios#275]
Hello,

I am using an app to take photos and save them as PDF. This PDF I am then transferring to the Nextcloud app to upload the PDF document to my nextcloud instance. I am transferring the document by pressing the "export" button within the app I used to generate the PDF.

Unfortunately the original filename of the uploaded document is ignored and the Nextcloud app is using the current date & time as filename (e.g. 2017-06-15 19-06-38-1.pdf)

I also tested an export to the Google Drive app. Within the Google app the original filename is kept and is not overwritten. As a conclusion the issue should be located within the Nextcloud app and not within the apps I am using for the photo and PDF generation.

Please fix this issue as it makes the whole scenario unusable as it is not reasonable for end-users to rename all uploaded files again.

Thanks a lot.
Chingato

**Comment by marinofaggiana** [comment]
Thanks @Chingato for your issue 👍

**Comment by marinofaggiana** [comment]
Available to next version 2.17.5
