### ISSUE TITLE
Battery bar visible as only icon of system bar during first use

### ISSUE THREAD

**Issue by khlschrnk** [nextcloud/ios#276]
I see this behaviour with 2.17.3(9) and 2.17.4(14). I did not test other versions.

This only occurs if you open the app the very first time.
If you open the the app while charging and switch back to iOS homescreen then going back to the app the battery icon is still visible on top (at least the green part of it). All other icons on top are not visible. 

Unfortunately I can't add pictures here. But if you open the app store and search for the nextcloud app the very first picture shows this behaviour:
https://itunes.apple.com/de/app/nextcloud/id1125420102?mt=8
The green battery bar above "cancel".

**Comment by khlschrnk** [comment]
I have tested this a few times during the last days. For me this is fixed with version (26).

**Comment by marinofaggiana** [comment]
ok close.
