### ISSUE TITLE
German translation findings

### ISSUE THREAD

**Issue by khlschrnk** [nextcloud/ios#277]
A few minor things about the german translation:
* During first use of the app it says "skip" in the bottom right corner. It should be "Überspringen"
* When you are asked to enter the server and user details: "Serveradresse" instead of "Server address" and "Benutzername" instead of "Username" and "Passwort" instead of "Password".
* For reset to initial state in settings: "Achtung! Nextcloud wird in den Ausgangszustand zurückgesetzt. Fortfahren?" instead of "Attention! Will be reset to initial state. Continue?". This was already correctly translated in nextcloud 2.17.3.00009.

**Comment by Chingato** [comment]
I would use "Achtung! Nextcloud wird auf die Werkseinstellungen zurückgesetzt. Fortfahren?". This is the typical wording in German.

**Comment by rakekniven** [comment]
Hallo @khlschrnk 
Die App ist komplett übersetzt. Die von Dir in Punkt 1 und 2 genannten Strings sind lokalisiert.
Welche iOS Sprache ist bei Dir eingestellt?

**Comment by rakekniven** [comment]
Hallo @Chingato 
bei Werkseinstellung bin ich etwas vorsichtig. Das sehe ich eher beim Rücksetzen des iPhones so.
Bist Du auf Transifex oder im Nextcloud-Forum aktiv? Dort sind mehr Leute um dies zu diskutieren.

**Comment by khlschrnk** [comment]
I use "Deutsch" in iOS settings.

2.17.4(20):
1) It still says "skip"
2) It still says username and password
3) To reset to initial state is no show correctly in German.

**Comment by rakekniven** [comment]
Latest Testflight 2.17.4(29) fixes intro strings. They are in german.

But account strings are still in english.
@marinofaggiana Could you have a look?

**Comment by marinofaggiana** [comment]
Where @rakekniven ... Intro.strings are ok ... for me ...

**Comment by rakekniven** [comment]
After intro you are prompted to create your first account.
Serveradress, username, password. These dialog is still in english.

**Comment by marinofaggiana** [comment]
Arrgghhh the placeholder ...

**Comment by rakekniven** [comment]
Will try next Testflight. Grazie!
