### ISSUE TITLE
Description panel redesign

### ISSUE THREAD

**Issue by mpivchev** [nextcloud/ios#2776]
![image](https://github.com/nextcloud/ios/assets/6960329/8308710b-8a22-4a0e-b972-3aad8cda5ea1)

   - Maybe change the formatting of the readme file, disable emojis
   - Remove or reduce opacity of top line separator
   - Improve the fade between description and folder
   - Improve spacing
   - Add the the option to hide it

Edit: Put an option to hide in menu ("Show folder description"), hide is optional, enabled by default

**Comment by jancborchardt** [comment]
Here I think the main reason it looks off is the line break of the heading, so dependent on the content.
I wouldn't do anything like disable emojis as it will change content unexpectedly.

Is there any standard iOS sizing for headings from h1 to h6 that we can use here? Maybe the h1 is just a bit too big, should maximally be as big as the the big main title of apps in the top left like in "Messages".
