### ISSUE TITLE
Account switcher redesign

### ISSUE THREAD

**Issue by mpivchev** [nextcloud/ios#2777]
![image](https://github.com/nextcloud/ios/assets/6960329/87477fe9-1527-45e8-9ea7-4f54be144ed8)

  - Replace full email with alias or something shorter
    - Can do something similar to Talk iOS: 
    
     ![IMG_4083](https://github.com/nextcloud/ios/assets/6960329/c993cdfd-1b1e-4d3e-af70-ae2c84dc7a5d)

**Comment by mpivchev** [comment]
@marinofaggiana @jancborchardt I suggest we change the switcher to how it looks in Talk, with the drop down. However, we will still keep it attached to the profile picture.

**Comment by jancborchardt** [comment]
@mpivchev yep, doing it like in Talk looks great to me, good suggestion. :)

**Comment by jancborchardt** [comment]
@marinofaggiana it's good that we are using the system menus, styles, icons etc. :)
It's much easier for people to understand and use since they are familiar with these patterns from other iOS apps and the system itself.

**Comment by phil-lipp** [comment]
> @marinofaggiana it's good that we are using the system menus, styles, icons etc. :)
> It's much easier for people to understand and use since they are familiar with these patterns from other iOS apps and the system itself.

As a normal user I can fully support this! 'Personality' at the cost of UX isn't good, which is imo the case here
