### ISSUE TITLE
Favorite folders are not being downloaded

### ISSUE THREAD

**Issue by khlschrnk** [nextcloud/ios#278]
Currently I use 2.17.4(14).
I have enabled to keep favorites available offline in settings.

When I set the favorite flag to a file it gets automatically downloaded.
When I set the favorite flag to a folder it does not automatically get downloaded.

I prefer to use this flag instead of manually downloading a folder as later changes (for example adding more files in this folder) will not be automatically downloaded.

**Comment by khlschrnk** [comment]
A quick update on this with version 2.17.4(20).

When I now set a folder to have the favorite flag within the app it automatically downloads the folder if the settings for offline availability is enabled. So this is fixed.

I still have another point regarding this issue but I am not sure if I should open another issue.
When I have reset the app and start a new cloud account and also enable the setting for offline availability It does not download any favorites. It only starts to download them if I remove the flag and reapply it on folder. I have not tested this with a favorite flag on a file.

**Comment by marinofaggiana** [comment]
mmm strange I have try, after reset account the all favorite folder are loading ...

**Comment by khlschrnk** [comment]
Yep, I can confirm. See the attached video.


[2017-06-25 14-33-26-1.mp4.zip](https://github.com/nextcloud/ios/files/1100316/2017-06-25.14-33-26-1.mp4.zip)

**Comment by marinofaggiana** [comment]
Thanks for your video, mmmm very strage ..with my test is correct ... ok, try, after login do not load dir but touch Home button iPhone, and open Nextcloud ... now ?

**Comment by khlschrnk** [comment]
Unfortunately it is the same. I tried to go back to iOS Home via pressing the home button. Then opening again the nextcloud app and the favorites are still emtpy. I also tried to quit the app completely by double clicking on homebutton and swiping the app to the top and reopening it. Favorites are still empty.

**Comment by marinofaggiana** [comment]
2.17.4(20) ?

**Comment by khlschrnk** [comment]
Yes and server 12.0.0

**Comment by marinofaggiana** [comment]
I have remake your example and for me it's ok ... @rakekniven can you make a test ? 

p.s. @khlschrnk error LOG on server on Activity ?

**Comment by khlschrnk** [comment]
Last entry in Nextcloud.log is from two days ago.

**Comment by marinofaggiana** [comment]
@khlschrnk news ?

**Comment by khlschrnk** [comment]
It's still the same with all versions until 2.17.4 (25).

Some more information: When I set a folder as favorite via the app it gets instantly downloaded. The contents are then shown immediatly in the favorite file view even I did not enter the folder in normal file view. It just does not work when I try to see the contents of folders that were flagged as favorites before (before reseeting the ios app via the app or if the flag has been set via the webinterface).

**Comment by marinofaggiana** [comment]
No ... can you create for me ad account test ? and send the credential to ios @ nextcloud . com ?

**Comment by khlschrnk** [comment]
I did just sent the account details.

**Comment by khlschrnk** [comment]
The problem is gone now. Version (26) works as expected.

**Comment by marinofaggiana** [comment]
close.

**Comment by khlschrnk** [comment]
I'd like to reopen this as this problem came back up. I can't tell when but with version 2.20.7.00003 folders markes as favorites are not downloaded any more even if the option "Offline available favorites" is active.
