### ISSUE TITLE
Nextcloud ios vs Owncloud ios

### ISSUE THREAD

**Issue by herohamp** [nextcloud/ios#280]
So I used to be running owncloud so I bought the owncloud ios app. Should I buy the nextcloud ios? are there any advantages?

**Comment by rakekniven** [comment]
Hello @herohamp 
I have been using the ownCloud app until last year and after switching to Nextcloud I changed app as well.
For me it was a huge step. The Nextcloud had so many more features and development speed is amazing. Next release will be ready soon.

btw. Haven't tried old app the last 12 month and cannot tell you any about its progress. Give Nextcloud a try. It is just one dollarl, it is worth it and developer @marinofaggiana is working like a maniac.

**Comment by rakekniven** [comment]
Please close issue if my answer satisfies you.

**Comment by herohamp** [comment]
Thank You so much @rakekniven
