### ISSUE TITLE
pdf editing

### ISSUE THREAD

**Issue by Slevin7** [nextcloud/ios#281]
Hello, is it possible to add the fiction to edit a pdf?
I used nextcloud for studying and it would be great if I could make notes in my files.
Thank you.

**Comment by MariusBluem** [comment]
I think this is nothing what should be handled over the Nextcloud iOS application. What about 3rdparty-Applications (PDF-Editors) or the coming changes in Notes (iOS 11)?

**Comment by Slevin7** [comment]
it is possible to use 3rdparty-applications but moste time I want to make a quick note, like "learn this; important".
I think what could be great about that is, it upload to nextcloud after saving the change.
And not like now, download the pdf open in 3rdparty app, save, and reupload to nextcloud.
Or is there an app with sync with nextcloud?

**Comment by MariusBluem** [comment]
Generally every app with WebDAV support. Just find this one after a quick search: https://itunes.apple.com/de/app/documents-6-pdf-reader-dateien-medien-cloud/id364901807?mt=8

**Comment by Slevin7** [comment]
Shame on me, I forgot webdav. I only search especially for nextcloud and own cloud.
