### ISSUE TITLE
Nextcloud cache is backed up to iCloud

### ISSUE THREAD

**Issue by oxivanisher** [nextcloud/ios#283]
It seems that iOS is backing the cache up to the iCloud Backup, which uses up the 5GB free space very fast!

I do not know if this is by design, or if the app even can specify to ignore this folder during the backup process. If it is not possible to remove the folder from the backup, backing it up makes no sense IMHO, it should be possible (and default) that the cached objects get cleared after some time (i.e. one month).

**Comment by mrnoisytiger** [comment]
If you go into iCloud storage usage, and select the backup of the device you are currently using, you can turn off Nextcloud data from being backed up to iCloud.

This is by design of iCloud backup, specifically backing up all related app data unless you explicitly turn it off.

**Comment by manches** [comment]
Hi, i have it turned off and it still tries to backup all the cache.
Can you please reopen these thread?

**Comment by oxivanisher** [comment]
Also, this link might help fix it that the files do not get uploaded: https://developer.apple.com/icloud/documentation/data-storage/index.html

I talked to a IOS App dev and got told, that there is the possibility to not upload everything automatically.

**Comment by doomi** [comment]
Using the right folders or attributes for the cache will prevent it from backing up to iCloud.
This is not by design of iCloud.
As already said in a comment earlier, read this:
https://developer.apple.com/icloud/documentation/data-storage/index.html

Please reopen this issue, should be easy to fix.
