### ISSUE TITLE
New swipe cell 

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#284]
Hi, do you like ?

<img width="376" alt="schermata 2017-06-26 alle 13 12 33" src="https://user-images.githubusercontent.com/8616947/27536930-9753e1a6-5a71-11e7-8bf7-1ac054535f2a.png">

Video : 

https://cloud.twsweb.it/index.php/s/KyGWG4oRGGPmHxw

ping @jancborchardt

**Comment by jancborchardt** [comment]
Cool! :) Can you make the background yellow like the star though, and the star white?

**Comment by jancborchardt** [comment]
And instead of the red background the color should stay the same, but text should say "Unfavorite".

**Comment by marinofaggiana** [comment]
yellow ... @jancborchardt send me a yellow color :-)
 
<img width="373" alt="schermata 2017-06-26 alle 15 09 09" src="https://user-images.githubusercontent.com/8616947/27540724-838abffe-5a81-11e7-92dd-ebeddacb8da2.png">
<img width="376" alt="schermata 2017-06-26 alle 15 09 24" src="https://user-images.githubusercontent.com/8616947/27540729-8701dd34-5a81-11e7-9372-df132effba86.png">
<img width="373" alt="schermata 2017-06-26 alle 15 09 35" src="https://user-images.githubusercontent.com/8616947/27540735-88cfc450-5a81-11e7-80b3-99161eac7075.png">

**Comment by marinofaggiana** [comment]
Yellow : 242,220,132

<img width="376" alt="schermata 2017-06-26 alle 15 20 53" src="https://user-images.githubusercontent.com/8616947/27541128-1472786c-5a83-11e7-8233-49ed5f4947ac.png">

**Comment by jancborchardt** [comment]
For favoriting, the star icon should be filled.
For unfavorite, the star icon can be the outline, but the background color should be the same yellow. Red is absolutely only for deletion. :)

**Comment by marinofaggiana** [comment]
<img width="278" alt="schermata 2017-06-26 alle 16 39 39" src="https://user-images.githubusercontent.com/8616947/27544666-1f993540-5a8e-11e7-9ebc-32931543adab.png">
<img width="271" alt="schermata 2017-06-26 alle 16 39 53" src="https://user-images.githubusercontent.com/8616947/27544671-218a2832-5a8e-11e7-87b2-4a1a5703198e.png">

**Comment by jancborchardt** [comment]
Good stuff! :+1:

**Comment by marinofaggiana** [comment]
Ok, thanks @jancborchardt, I close

**Comment by marinofaggiana** [comment]
@jancborchardt last question ... a doubt ... With description : DELETE MORE FAVORITE or without ? example Mail Without .... ?

**Comment by jancborchardt** [comment]
If you mean whether the icons should have text, then yes, absolutely. Icons alone are harder to understand, especially because they are hidden in a swipe view. :)

**Comment by marinofaggiana** [comment]
ooook 👍
