### ISSUE TITLE
NC Assistant

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#2840]
See https://github.com/nextcloud/files-clients/issues/50#issuecomment-1909730092

**Comment by alperozturk96** [comment]
Certain task types are not supported on mobile devices. Therefore, we are excluding these task types from the incoming tasks received from the backend.

```
   val excludedIds = listOf("OCA\\ContextChat\\TextProcessing\\ContextChatTaskType")
             val result = arrayListOf(TaskType(null, allTaskType, null))
             val taskTypesResult = repository.getTaskTypes()

            if (taskTypesResult.isSuccess) {
                val excludedTaskTypes = taskTypesResult.resultData.types.filter { item -> item.id !in excludedIds } 
                ...
            }
```

**Comment by alperozturk96** [comment]
> @alperozturk96 in't only "OCA\ContextChat\TextProcessing\ContextChatTaskType" excluded ?
> 
> @mpivchev

When you fetch, you should get two task type and only that one should be excluded
