### ISSUE TITLE
Bug in the iOS Nextcloud App 5.2.4.2: Error uploading files when uploading a 1 GB .mov file

### ISSUE THREAD

**Issue by WeskerC** [nextcloud/ios#2870]
### Steps to reproduce

1. download the iOS nextcloud 5.2.4.2 app 
2. preset the following variables in config.php
```
php_value upload_max_filesize 16G
php_value memory_limit 16G
php_value post_max_size 16G
php_value max_input_time 72000
php_value max_execution_time 72000
```
3. select a random .mov file from the album which is around 1.5GB in size and upload it to local-hosted docker deployed nextcloud
4. the app would prompt the error

### Expected behavior

It should be uploaded seamlessly.

### Actual behavior

The app would prompt a "not enough space" message on the main page, yet no error message shown in the app log.
Meanwhile, the same amount of space will still be occupied in the cache space.  
(shown in the ADVANCED - DELETE FILES TO FREE UP SPACE)
Also, I have tried to disable chunk transmission using 

```
php occ config:app:set files max_chunk_size --value 1000000000000
```
but still not working.

### Screenshots

![IMG_2616](https://github.com/nextcloud/ios/assets/48875935/de512f3b-d899-4bd6-8dd7-83c69f203b24)
![image](https://github.com/nextcloud/ios/assets/48875935/8fcd8dcb-7876-41d7-b8b0-c691abe5a5d5)
![image](https://github.com/nextcloud/ios/assets/48875935/363059cd-f838-4259-a8c0-ebda5e69ad09)

### Logs
**_From the communication.log:_**

[Network Duration]: 0.20260107517242432s
[Serialization Duration]: 2.041662810370326e-06s
[Result]: success(1987 bytes)
2024-04-08 10:01:37 Network response all headers: 2024-04-08 10:01:37 Optional([AnyHashable("X-Robots-Tag"): noindex, nofollow, AnyHashable("Connection"): Keep-Alive, AnyHashable("X-XSS-Protection"): 1; mode=block, AnyHashable("X-Debug-Token"): qS81p9bCIzgdlyeqN9vM, AnyHashable("Cache-Control"): no-store, no-cache, must-revalidate, AnyHashable("X-Content-Type-Options"): nosniff, AnyHashable("Content-Type"): application/xml; charset=utf-8, AnyHashable("Expires"): Thu, 19 Nov 1981 08:52:00 GMT, AnyHashable("Vary"): Brief,Prefer, AnyHashable("Pragma"): no-cache, AnyHashable("Content-Security-Policy"): default-src 'none';, AnyHashable("Content-Length"): 826, AnyHashable("Content-Encoding"): gzip, AnyHashable("X-Permitted-Cross-Domain-Policies"): none, AnyHashable("Server"): Apache/2.4.57 (Debian), AnyHashable("Date"): Mon, 08 Apr 2024 02:01:37 GMT, AnyHashable("Referrer-Policy"): no-referrer, AnyHashable("X-Request-Id"): qS81p9bCIzgdlyeqN9vM, AnyHashable("X-Powered-By"): PHP/8.2.17, AnyHashable("Keep-Alive"): timeout=5, max=100, AnyHashable("X-Frame-Options"): SAMEORIGIN, AnyHashable("DAV"): 1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, nextcloud-checksum-update, nc-calendar-search, nc-enable-birthday-calendar])
2024-04-08 10:01:46 [INFO] PROCESS (UPLOAD) find 1 items
2024-04-08 10:01:47 [INFO] Upload file 24-01-23 22-15-51 1683.mov with Identifier 83A98BE1-20BA-4DA2-BD27-8208B308714B/L0/001 with size 1131992108 [CHUNK 100000000, E2EE false]

### Reasoning or why should it be changed/implemented?
It should be able to upload .mov files larger than 1 GB using iOS nextcloud app
### Environment data

**iOS version:**  iOS 17.2.1

**Nextcloud iOS app version:**  Nextcloud Hydrogen for iOS 5.2.4.2@2024

**Server operating system:**

**Web server:** Apache

**Database:** redis, mariaDB

**PHP version:**  Version: 8.2.17
![image](https://github.com/nextcloud/ios/assets/48875935/98885a4c-c47c-4bcd-855a-ddc9ac7f74c8)

**Nextcloud version:** 28.0.4

**Comment by WeskerC** [comment]
I would suggest to post an error code for this situation in iOS app interface and also after revising the LimitRequestBody to 0 problem still exits.

**Comment by jth134** [comment]
I have this same issue

**Comment by WeskerC** [comment]
> I have this same issue

@jth134 let‘s hope that they can narrow the cache size.

**Comment by Tak-MK** [comment]
I'm having this issue too with 2G files. I have set up PHP to max 5G in upload files and 0 (disable limit) in post, but still nothing.

**Comment by WeskerC** [comment]
Then I guess the problem still occur.
在 May 2, 2024, 1:18 AM +0800，jth134 ***@***.***>，写道：

**Comment by pmelikov** [comment]
**This error is still actual!**

**Environment data**

**iOS version:** 17.5.1
**Nextcloud iOS app version:** Nextcloud Hydrogen for iOS 5.4.1.0@2024

**Server operating system:** Debian
**Web server:** Nginx
**Database:** redis, mysql 10.11.6

**PHP:**
Version: 8.3.9
Memory limit: 512 MB
Maximum execution time: 7200
Maximum upload size: 33 GB
OPcache recheck frequency: 10
Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** [Nextcloud Hub 8] 29.0.3

**Comment by rahulc07** [comment]
I have the same error on 29.0.4

**Comment by happy2rock** [comment]
Error still persists with iOS version: 17.6.1
Nextloud iOS app version: 5.5.5.0@2024

Nextcloud version: 30.0.0

**Comment by april83c** [comment]
Experiencing this too... trying to upload a 69 GB file which I guess would require me to have 276 GB of free space on my 256 GB phone

**Comment by WeskerC** [comment]
> Experiencing this too... trying to upload a 69 GB file which I guess would require me to have 276 GB of free space on my 256 GB phone

Seems like no one is checking this issue, which is important

**Comment by Acliad** [comment]
This is also a big issue for me. It makes it impossible to free up space on my iPad when I have a really large files I need to move off.

**Comment by ccll** [comment]
It's 2026 and the issue still exists, please fix this.
