### ISSUE TITLE
SOLUTION for SSL certificate error when uploading through iOS application

### ISSUE THREAD

**Issue by WeskerC** [nextcloud/ios#2876]
I have been searching for the repository for the whole day looking for the solution regarding this issue but none of them works
![image](https://github.com/nextcloud/ios/assets/48875935/ac40863d-bd7f-4a8b-a30c-58b06f1d856f)

Eventually, I figured out a less perfect but workable solution:

1. simply download the SSL certificate from your host (Cloudflare / Let's Encrypt)
2. import the full-chain PEM file into iOS device and then choose Trust in Settings -> General ->VPN & Device Managament.
3. Problem gone.

Make sure that your certificate is up-to-date and useable.

I am new to SSL so if this action is risky I hope you can leave a feedback.

Best Regards.

**Comment by mritzmann** [comment]
> I am using Cloudflare 15-year certificate at the moment

If you are using a certificate from Cloudflare that is valid for 15 years, then I assume you are using a Cloudflare Origin CA certificate. This certificate is not intended for public use, the intended use is for encryption between your server and Cloudflare (and as a side note: iOS supports a maximum of [398 days](https://support.apple.com/en-us/102028) for every certificate).

See also the [Cloudflare documentation](https://developers.cloudflare.com/ssl/origin-configuration/origin-ca/
) about Origin CA certificate:

> Site visitors may see untrusted certificate errors if you pause or disable Cloudflare on subdomains that use Origin CA certificates. These certificates only encrypt traffic between Cloudflare and your origin server, not traffic from client browsers to your origin. 

You have the following options:

* If you want to use this certificate, you must trust/import the certificate (or the CA root/intermediate) manually
* Or you have to use a "real" certificate that is trusted by iOS

This is not a Nextcloud iOS bug.

**Comment by WeskerC** [comment]
@mritzmann  Thank you Mritzmann for sharing this piece of information.

I am fully aware of the situation now. If there is a need in the future for public use I will try let's encrypt instead of Origin CA.

Thank you so much for your explanation.
