### ISSUE TITLE
Folder not changeable in share extension

### ISSUE THREAD

**Issue by wallenium** [nextcloud/ios#288]
Hi folks,
when i go to photos app, share, than enable nextcloud as a share extension, and then upload a photo, it is not possible to change the folder. The folder says data, when i click on it i am back in photos app without any warning or notice.

If you need further information, feel free to ask here ;)

Running latest beta version...

**Comment by marinofaggiana** [comment]
Hi @wallenium , try next beta :) thanks

**Comment by wallenium** [comment]
Works. Thanks a lot
