### ISSUE TITLE
issue uploading files in ios 11on iPhone 6

### ISSUE THREAD

**Issue by ezekiel-lemur** [nextcloud/ios#290]
I click on the + symbol
then Upload photos and video
then Camera roll (or an other option)
then I select the image 
then I press done
then I press photos as destination folder and the app crashes

**Comment by marinofaggiana** [comment]
@ezekiel-mongoose 

https://github.com/nextcloud/ios/issues/292

**Comment by marinofaggiana** [comment]
iOS 11 is in beta version & Xcode 9 as well.
