### ISSUE TITLE
iOS app shows "No Files In Here with NC 12.0.0 and SMB shares

### ISSUE THREAD

**Issue by Whatever2017ldskfj** [nextcloud/ios#291]
Two instances of 12.0.0 where there are ONLY SMB shares in NC. The web client shows the SMB shared folders, but the iOS app shows only "No files in here".

Has been this way for two months+; since we upgraded the first install to 12.0.0. The other install is clean from a VHD.

**Comment by enoch85** [comment]
@marinofaggiana Can you please have a look?

Similar to this issue: https://github.com/nextcloud/server/issues/5604

**Comment by enoch85** [comment]
cc @icewind1991 for the SMB issues.

**Comment by fsmeets** [comment]
Hi,

any update on this? We can confirm that SMB shares are not shown in the NC iOS and Andorid App. Using the Owncloud Android App with the same NC Server does show the SMB shares. The SMB shares work fine, in the web GUI and using the OC mobile apps, they are just not shown in the NC mobile apps.

Is there anything we can do? Logs, tests anything?

Thanks,
Florian

**Comment by Whatever2017ldskfj** [comment]
Still broken. Can't use this system in business deployments if the team can't fix major usability issues like this in a timely manner. This is out over six months now. It's not an issue with v11, just 12 and up. We're having to hold deployments at 11 and had to reinstall to rollback those that had been upgraded to 12.

**Comment by segdy** [comment]
This bug still seems to be around with the latest versions (iOS ver 2.22.7.4 and server 13.0.8).
Any hope for a fix?
