### ISSUE TITLE
Color issues on iOS11

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/ios#292]
- iOS 11; TestFlight v2.17.4 (25)

![img_5441](https://user-images.githubusercontent.com/19711361/27764332-350350fc-5e97-11e7-8767-8f6caf865262.PNG)

@marinofaggiana

**Comment by marinofaggiana** [comment]
OMG a Horror movie .. ok remove theme detect , new build 15 available, sorry.

**Comment by marinofaggiana** [comment]
AAAAA Horror movie !! 😆

**Comment by marinofaggiana** [comment]
Recompile with Xcode 9 beta ...  It's too early for test with iOS 11 ... ;) 

<img width="332" alt="schermata 2017-07-02 alle 11 01 24" src="https://user-images.githubusercontent.com/8616947/27768515-e7d05e4a-5f15-11e7-8b2a-0a7066ced10a.png">

**Comment by marinofaggiana** [comment]
@MariusBluem only this issue ?

**Comment by rakekniven** [comment]
@marinofaggiana Is this fixed or delayed until iOS11 is out?

**Comment by marinofaggiana** [comment]
delayed, the Xcode 9 is in beta and unstable, swift 4 as well  ... and ios 11 beta 3 dev too ...

**Comment by rakekniven** [comment]
So wouldn't it be better to keep it open and label it e.g. iOS11?

**Comment by marinofaggiana** [comment]
No, this issue now is not sense, for example the same test on emulator is ok, on ipad too but for @MariusBluem no ... the ios 11 is unstable, users should not install iOS 11 ... but only the developer for study the new features...

**Comment by MariusBluem** [comment]
@marinofaggiana Well... this repo is **not** a support-portal, where users come to report their problems. It is for developers and testers, reporting bugs. I have tested Nextcloud iOS-application with iOS 11 ... a typical testing/development task, and saw this issue. 

I've opened simply to track when its fixed. This is how issue-tracking works for me 😉

**Comment by marinofaggiana** [comment]
yes yes @MariusBluem it's correct ! but with the rebuild xcode 9 the issue is not present, and I have close this issue ... for example the app crash if you send a new image/video ... I have investigate for this issue but with recompile on xcode 9 the issue is absent ...
