### ISSUE TITLE
Can't Preview/Share Downloaded Mobi Files. iOS 11?

### ISSUE THREAD

**Issue by Jon-Schneider** [nextcloud/ios#293]
Device: iPad Air 2 running iOS 11 Beta 2
If I download a mobi file within the app by clicking on the file in the file nav, it will display the download progress but it will not open a "Preview" (which in OwnCloud is the placeholder icon preview for an unknown file type) after the download completes, or if I click on the file again after downloading. If I swipe on the filename and select the "Open In" option from "More" I have the same problem - the download will complete but the preview will not open, and the system share menu never opens.

Edit: 9/12/17
Further testing revealed that this appears to affect both iPads (but not iPhones) running iOS 10 and iOS 11, and it affects sharing of all files from the Main File menu, not just files without previews - it's just more obvious with files that can't be previewed because it should open the Share menu automatically.

**Comment by marinofaggiana** [comment]
Thanks ! Can you test last beta ?

**Comment by marinofaggiana** [comment]
iOS 11 is in beta version.

**Comment by Jon-Schneider** [comment]
Still present in iOS 11 GM. Fixing in PR.
