### ISSUE TITLE
iOS App does not sync after upload

### ISSUE THREAD

**Issue by Knutowskie** [nextcloud/ios#2939]
### Steps to reproduce

1. Download existing PDF file from server with iOS App. (just saying this problem does NOT occur with android or windows clients)
2. Edit PDF on iPad (completing and signing it)
3. Upload PDF back to server

### Expected behaviour

After uploading the app should show the new file only.

### Actual behaviour

The app shows the new file and the old one. User may be confused which to use in next steps.

### Screenshots

Asked for permission to upload screenshot of the problem, was not granted. Its simply the same PDF two times.

### Logs

```
I am sorry, i dont know where to get app logs.
```

### Reasoning or why should it be changed/implemented?

After uploading it should automatically sync and show only the correct structure of the server, where the file NEVER is duplicated visible. Neither in Android Apps nor in Windows Clients this happens. And if you check those clients and the browser, the file is only there once in the new edited state.

The problem is, the file needed to be signed by different people in different spaces. So we open the file, edit it and sign it. Then we close it, walk to the next station, open the very same file and add a signature. This happens 3 times. No one knows which file is the new one.

### Environment data

**iOS version:** e.g. iOS 14.4.1

**Nextcloud iOS app version:** Nextcloud Hydrogen 5.3.1.2

**Server operating system:** Debian 12

**Web server:** Apache behind HAProxy

**Database:** MySQL 11.3.2

**PHP version:** 8.2.19

**Nextcloud version:** 29.0.0

**Comment by devo001** [comment]
We are experiencing the same issues posted above after upgrading to iOS 5.3.1

The issue appears to be contained to annotating PDF files only - .md files work as expected.

We have tested using multiple iOS devices against server v28 (latest) as well as unsupported server v24 (latest), for verification.

Selecting 'Save as copy' after annotation works as expected.

Selecting 'Overwrite original' causes duplication.

The annotated PDF does upload back to server v28 but not to server v24.  Against both servers the PDF file gets duplicated on the mobile.  The duplicates appear to be stuck in upload and download conditions respectively (referring to up/down arrows displayed below file name).  Clicking on the files names or the circle indicator to the right, causes further unexpected results.

The user is now unable to determine which of the duplicates to continue editing.  In our case, this issue breaks team collaboration.

**Comment by Knutowskie** [comment]
In latest version 5.4.1.0 this seems to be fixed.
