### ISSUE TITLE
BUG: LDAP users cannot mark folders/files as Favorite

### ISSUE THREAD

**Issue by derWeihnachtsmann** [nextcloud/ios#294]
Hey there devs,

As described here: https://help.nextcloud.com/t/nextcloud-ios-2-17-errors/11606/2  I'm also struggling to mark folders/files as Favorites for offline access. When choosing a folder I get a "Request failed: not found (404)" error. 
So far the "mark-as-favorite" option seems to be the only one to save your files for Offline usage on iPhone.
The crazy thing about this is, on iPad it's easy possible by swiping the choosen folder to the left to download the folder for offline usage. 
The iPhone-app is missing that option. So here could be a feature-request coming in. :-)

It seems that only LDAP users are affected, says the website above, this matches my experience, also I am using LDAP in my enviroment.

V. 2.17.3
iPhone 6 and iPad Pro(for testing swipe-option)

Thanks and keep up the good work!

**Comment by wizdude** [comment]
+1

i have the exact same problem with my LDAP integrated nextcloud and cannot favourite any files. i receive the same "Request failed: not found (404)" error.

cheers, wizdude

**Comment by marinofaggiana** [comment]
@wizdude fixed ?
