### ISSUE TITLE
Quota and total size of all files do not match

### ISSUE THREAD

**Issue by threonin** [nextcloud/ios#295]
With the iOS app the used quota of a user and the total of all files in the root directory do not match. On the web interface they do match and are reported as 6.5MB on a clean install. The difference is too big to be due to rounding, so there must be a minor bug in the calculation of the total size.
Nextcloud server is 12.0.0 running in a docker container and the app is version 2.17.3.

![2017-07-05 16-51-08-1](https://user-images.githubusercontent.com/2266609/27870242-a7db0eea-61a2-11e7-8e2a-54c6190e14c0.PNG)
![2017-07-05 16-50-33-1](https://user-images.githubusercontent.com/2266609/27870241-a7d57d36-61a2-11e7-922d-b9ef280e3ca2.PNG)

**Comment by rakekniven** [comment]
Do you have "versions" enabled on server?
Do you use additional apps on server?
AFAIK the quota value is calculated on server and app is showing it.

**Comment by threonin** [comment]
Yes, versions is enabled, but this happens also with no changes in the files. The sizes are the same after recreating the docker containers, so there can not be any versions created yet.
Additionally to the default apps there is nextant, antivirus, collabora and circles enabled, they get added directly in the deployment process.
The quota value is the same on the server and on the app, only the total number of all directories and files differ.

**Comment by marinofaggiana** [comment]
This value is not calculated from nextcloud client, if you have other question reopen this.

**Comment by rakekniven** [comment]
Hello @marinofaggiana you did not answer the issue regarding not marching number of directories and files.
Are these server side numbers as well?

**Comment by marinofaggiana** [comment]
No @rakekniven, I don't see this issue, where is this  : 

> The quota value is the same on the server and on the app, only the total number of all directories and files differ.
