### ISSUE TITLE
[iOS app] Upload doesn't work when uploading many heavy pictures/videos

### ISSUE THREAD

**Issue by brice-shadow** [nextcloud/ios#2962]
# Reproduction
**Reproducible ?**
- [x] Yes.
- [ ] No.

**Regularity ?**  
- [x] Always.
- [ ] Sometimes.
- [ ] Unable to reproduce.

**Regression ?**
- [ ] Yes.
- [x] No.
- [ ] New Feature.
 
**Steps to reproduce ?**

1. Open iOS app
2. Click on "Upload" button
3. Select many heavy pictures and videos
4. Immediately click on "Save"

**Obtained results :** Upload doesn't happen if we don't wait for the pictures thumbnails to load

_If we wait for the thumbnails to load, this works properly_

# Environment and versions
 
| Client Environment | Device used |
| ------------------- | --------------- |
| 5.2.1 | iPhone X - iOS 16.2 |

**Comment by brice-shadow** [comment]
@Jb-tauch-shadow FYI

**Comment by Jb-tauch-shadow** [comment]
Hello,

I can confirm that this seemed to have fixed the issue ! Thank you for the support
Do you know when that fix will be pushed on the branded app ?

Greetings,
JB
