### ISSUE TITLE
Picture/ Video upload filename format

### ISSUE THREAD

**Issue by mdax82** [nextcloud/ios#297]
There is a different naming format at upload to NC on the iOS client owncloud vs. nextcloud.

Example uploading the same file:
nextcloud client:
2017-07-06 06-40-56 1623.jpg

owncloud client:
Photo-2017-07-06-06-40-56_1623.JPG

I would like to have the capability upload with the same format from nextcloud client. Possibly a more enhanced rename mechanism could do where all variables could be accessed and add Photo/Video as prefix based in file extension (agree its a matter of argument but I like it sorted based on filename rather then only look on the extension).

Thank you!

// Raised based on https://help.nextcloud.com/t/picture-video-upload-filename-ios-nextcloud-client-vs-owncloud-client/14996/3

**Comment by marinofaggiana** [comment]
Sound good, available from next beta ;)

**Comment by mdax82** [comment]
awesome :)

**Comment by mdax82** [comment]
Just testet the update version. Looks we are on the right way to replicate the owncloud behavior. 

Now:
Foto 17-07-15 11-14-53 1690.jpg

Owncloud:
Photo-2017-07-15-11-14-53_1690.jpg

Open:
- Photo rather then Foto (seems a bit inconsistent as client creates folder "Photos" while its called Fotos in the bottom menubar but never mind)
- add a "-" after Photo
- YYYY rather then YY
- add a "-" after YYYY-MM-DD
- add a "_" after HH-MM-SS 

:)

**Comment by fmjensen** [comment]
This change makes the iOS client upload everything from scratch... Doubling the amount of space needed for photos, and in some cases hitting the allocated storage quota. 

Messing around with users photos is dangerous, and could very easily harm Nextcloud reputation... You really need to EXPLAIN / INFORM users when chambering stuff like this. 

I love Nextcloud - don't get me wrong - but being forced to sort more than 6000 photos is NOT fun :-/

**Comment by fmjensen** [comment]
Duh... chambering --> changing  ;-)

**Comment by marinofaggiana** [comment]
Next version a (swich) for enable/disable prefix

**Comment by fmjensen** [comment]
An option to switch between naming conventions was not what I asked for 😉
 I like file naming convention consistency between clients so this fix is fine with me... I just would have loved to be warned that all auto uploaded iOS photos now are prefixed with "Photo-" and that it would result in re-upload of everything... but do as you please - cause generally y'all do a heck of a job here👍🏼

**Comment by marinofaggiana** [comment]
This modify was already in To-Do list.

**Comment by Luto73** [comment]
I do have mir than 4000 uploads due to the name change. Sorry, this is not a good way to get nextcloud desktop and iOS app in sync.🙁

**Comment by marinofaggiana** [comment]
fix on 2.17.5

**Comment by mdax82** [comment]
Awesome guys, using
YYYY-MM-DD-HH-mm-ss
is something I can live with ;)

Just recognized when switch on the Foto/Video addition and using custom filename it would create
Foto -YYYY-MM-DD-HH-mm-ss....

So there is a space between Foto and first character of the custom name.

I guess I can workaround this but might be something to beautify :)

Overall great work 👍
