### ISSUE TITLE
5.4.0: image preview fixed to square

### ISSUE THREAD

**Issue by bcutter** [nextcloud/ios#2971]
Since 5.4.0 the preview of HEIC files is only shown as square/quadratic. That of course hides parts of the image making the preview useless in many cases.

- It does not affect PNG or other file types.

- Once the full size of the image is loaded (manually), the HEIC is shown fully (in original aspect).

Random example:

1) Full image
![image](https://github.com/nextcloud/ios/assets/13799156/464b2b55-eae5-4e0a-a006-ea7081aab98c)

2) Nextcloud iOS 5.4.0 preview
![image](https://github.com/nextcloud/ios/assets/13799156/987eae48-b506-4125-b56b-146f28ddcff7)

3) Nextcloud iOS full size view
![image](https://github.com/nextcloud/ios/assets/13799156/8eb0c318-2463-487b-b04c-b8e9090f29f2)

**Comment by rightsaidfred99** [comment]
For me, it happens with regular jpegs

**Comment by bcutter** [comment]
The image itself is irrelevant. You should get the point with the description only. Otherwise... you could just try it on your own I guess?

**Comment by bcutter** [comment]
Did you read the issue description?

In basic words: the image preview only this this and cuts other parts.

![image](https://github.com/nextcloud/ios/assets/13799156/5e5c2459-abca-495e-ba0f-2441d9f0653c)

**Comment by bcutter** [comment]
> the preview image is requested with the dimensions (H-W) resized based on the values ​​given by the metadata, if they are not there (probably they are not given for HEIC files) I cannot know the size to request.

Well, something changed compared to the version before 5.4.0.

This behavior is definitely new and introduced with 5.4.0.

Previews were working fine before, now they are broken.

**Comment by bcutter** [comment]
Here's a way better example image (widescreen).

Upload it and check the preview:

![image](https://github.com/nextcloud/ios/assets/13799156/2430749f-0ecc-4150-9372-ec1d961c389b)

**Comment by bcutter** [comment]
No, @rightsaidfred99 is right: also for JPEGs (like the last widescreen one I provided before).

**Comment by rightsaidfred99** [comment]
Nextcloud Hub 8 (29.0.3)
It's just the iOS update from today or yesterday that broke things. Server hasn't updated for a few weeks
