### ISSUE TITLE
Too many "file not present"

### ISSUE THREAD

**Issue by Kumapapa2012** [nextcloud/ios#299]
I have upload problems when uploading 1073 images/videos. 
I tested on Ubuntu 16.04LTS 64bit, NextCloudpi and Ubuntu MATE on Raspberry pi 3.
I got too many "file not present" errors on iOS app. NextCloud replies HTTP 201(Created) but looks like it does not willing to receive data of object from iOS.
This is image from iOS.
![file-1](https://user-images.githubusercontent.com/17864941/28008766-cccdf6fa-6593-11e7-87e7-ce752f64cc5c.png)

**Comment by marinofaggiana** [comment]
Version ?

**Comment by Kumapapa2012** [comment]
iOS 10.3.2
NextCloud 12 + php 7.1 on nginx.

**Comment by marinofaggiana** [comment]
Try with beta 2.17.4 and write report, thanks.

**Comment by Kumapapa2012** [comment]
So far so good!

Thank you. But did you reduce concurency?
This is uploading screen shot before testing:
![img_1666](https://user-images.githubusercontent.com/17864941/28017221-39b0844e-65b3-11e7-9168-785ca3a2938c.PNG)
This is now:
![img_1680](https://user-images.githubusercontent.com/17864941/28017281-7e998cae-65b3-11e7-88c3-24ca45082373.PNG)

I suppose iOS client should have ability to adjust concurrency.

**Comment by Kumapapa2012** [comment]
And now the client keeps crashing.
I can see a red alert icon right before crashing.
Should I remove nextcloud app then reinstall?
![img_1683](https://user-images.githubusercontent.com/17864941/28018004-814fc46a-65b6-11e7-9f9d-0d1eeb9aaa5a.PNG)

**Comment by marinofaggiana** [comment]
?

**Comment by Kumapapa2012** [comment]
I thought some local iPhone data is corrupted.
Anyhow I removed the iOS app then re-installed.
Nothing changed.

Then I copied all the user data to another folder "NextCloud-old" as backup, removed user and re-created user. 
And started uploading all the video/photos(1084 files) from iPhone. 
Now it finished with no single failure nor crash.

Maybe these empty media files (generated by public version) somehow caused crash of test flight version. 

root@km-NextCloud01:/media/NextCloud01/NextCloud-old# **find . -type f -empty**
./ncdata/.ocdata
./ncdata/index.html
**./ncdata/kumapapa2012/files/Photos/2017/05/2017-05-20 15-03-54 1202.mov
./ncdata/kumapapa2012/files/Photos/2017/05/2017-05-20 14-57-20 1180.mov
./ncdata/kumapapa2012/files/Photos/2017/05/2017-05-20 15-25-58 1216.mov
./ncdata/kumapapa2012/files/Photos/2017/05/2017-05-20 15-29-40 1219.mov
./ncdata/kumapapa2012/files/Photos/2017/05/2017-05-20 14-58-48 1182.mov
./ncdata/kumapapa2012/files/Photos/2017/05/2017-05-20 15-03-04 1188.mov
./ncdata/kumapapa2012/files/Photos/2017/05/2017-05-20 15-00-08 1183.mov
./ncdata/kumapapa2012/files/Photos/2017/05/2017-05-20 15-24-41 1215.mov
./ncdata/kumapapa2012/files/Photos/2017/05/2017-05-20 14-58-44 1181.mov
./ncdata/kumapapa2012/files/Photos/2016/10/2016-10-25 22-29-12 9823.mp4**

FYI: Although these files became 0KB every time on NC server with public version, Test Flight version uploaded them correctly.

Anyhow, now test flight version's auto upload is working fine! I love this so much :heart_eyes:
Thank you very much and I hope a new version with this fix is released soon :+1:

**Comment by Kumapapa2012** [comment]
Since auto upload works fine, I close this issue.
