### ISSUE TITLE
Support adding folders as favorites (including multiple files) to make them offline available

### ISSUE THREAD

**Issue by marcusvetter** [nextcloud/ios#30]
As a user of the nextcloud ios app
I would like to add folders as favorites
In order to make multiple files offline available

Currently I'm able to add only single files as favorites to make them offline available (swipe to the left, "More", "Add to favorites"). If I have a folder with a huge amount of pictures and I would like to have those pictures offline available, I have to select each file separably and star it - that's very effortful.

**Comment by marinofaggiana** [comment]
Yes @marcusvetter now you use synchronized Folder, it's the same, in future favorite change to off-line and and synchronized Folder too ... stay tuned

**Comment by rakekniven** [comment]
So issue is solved due to availability of synchronized folders?

**Comment by marinofaggiana** [comment]
Ja @rakekniven the "function()" it's the same it's only a "name" problem and a "graphics" problem, but now i don't have time for this, now only Document Picker in swift 👍

**Comment by rakekniven** [comment]
From my POV you can close issue. Function is present.

**Comment by marcusvetter** [comment]
Ah nice, thanks a lot :-)
