### ISSUE TITLE
Nextcloud and iOS 11

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#300]
**IMPORTANT** : For now, Nextcloud iOS is not compatible with the beta version (3) of iOS 11, this required a recompile with the new Xcode 9, but is too soon for this.

**Comment by budachst** [comment]
Any ETA on a version for iOS 11b3 (and probably later)?

**Comment by marinofaggiana** [comment]
Try with last beta of iOS 11 (now is more stable)

**Comment by andyxh** [comment]
Hello I’m on iOS 11.1.2 and nextcloud 2.18.2 and still having this issue and I’m getting the same error

**Comment by MariusBluem** [comment]
Done. Even with iOS 12 now :)
