### ISSUE TITLE
Login stuck when account deleted

### ISSUE THREAD

**Issue by bentuna** [nextcloud/ios#3018]
### Steps to reproduce

1. Log in to your Nextcloud account via the iOS app.
2. Close the app and delete the account via the Nextcloud web interface.
3. Reopen the app and see that the blue login screen is shown that forces you to login to the Nextcloud instance you had an account on before and you cannot change the URL of the instance.

### Expected behaviour

The URL on the login page should be editable.

### Actual behaviour

Login screen is shown and forces you to login to the Nextcloud instance you had an account on before and you cannot change the URL of the instance.

### Screenshots

![IMG_3967](https://github.com/user-attachments/assets/5087aca8-3962-4ba7-b63c-115506856a4c)

### Environment data

**iOS version:** 17.5.1

**Nextcloud iOS app version:** 5.5.3

**Nextcloud version:** 28.0.8

**Comment by qasamppa** [comment]
Same here, after changing the phone, NC iOS app stucks to the same screen.
