### ISSUE TITLE
IOS Login does not work

### ISSUE THREAD

**Issue by Biolaxy** [nextcloud/ios#3020]
After filling in the server IP address sometimes you will get the certificate message, after saying yes the app does nothing.
Reinstall of the app, same problem.
I think it might be the SSL Certificate:
Login with Local IP does not work (self signed SSL from Nextcloud)
Login with DDNS does not work ( self signed SSL from Nextcloud)
Only DDNS with Reverse Proxy works (Let’s Encrypt SSL)

**Comment by mpivchev** [comment]
Hi, we are aware of this. Fix is coming.

**Comment by robo667** [comment]
How can I fix it to login app locally ??

**Comment by Biolaxy** [comment]
> How can I fix it to login app locally ??

You can‘t fix it, Nextcloud will fix it in a new Update

**Comment by mpivchev** [comment]
Pull `develop`. Should be fixed there.

**Comment by Nullvoid3771** [comment]
I also have this issue. I’ve closed my bug report since it’s a duplicate issue. Hopefully fixed soon using the browser is slightly more annoying.

**Comment by robo667** [comment]
In App Store it’s still bug version.

**Comment by mpivchev** [comment]
App Store will be updated soon
