### ISSUE TITLE
"Photos" folder created at Photo upload while should not

### ISSUE THREAD

**Issue by mdax82** [nextcloud/ios#303]
I've deleted the default folders e.g. "Photos" and upload pictures into a folder e.g. upload. In Nextcloud this folder is selected as target directory (disable use folder Photos) and upload.

Once completed I see in the root directory the folder "Photos" was created but with no content (which is not expected) - this is unexpected as the picture was uploaded to "upload" and the "Photos" folder is not wanted.

I can delete the folder "Photos" then again but the story repeats at next upload.

Automatic upload is disabled, I really see no point for this behavior.

// transferred from https://help.nextcloud.com/t/photos-folder-created-while-not-required/16808 //

**Comment by marinofaggiana** [comment]
fixed on 2.17.5

**Comment by mdax82** [comment]
confirmed, looks good 👍
