### ISSUE TITLE
Don't show Libre office files

### ISSUE THREAD

**Issue by meaz** [nextcloud/ios#304]
The nextcloud ios app is great, but there is one problem: the app doesn't open libreoffice files, as it does with microsoft office files. So, one has to download the libreoffice file he wants to read, then open it with another app like OOreader. It is regrettable.

**Comment by marinofaggiana** [comment]
Hi @meaz , do not exists a standard reader (now) for iOS devices.

Sorry

**Comment by jagallas** [comment]
Hi 

About the issue #, we want to know about the roadmap to solve the ....

It's important for our organization to , because we are evaluating cloud files solutions and NextCloud is now our best solution analyzed but the dependence of this issue can change the position of your product.

**Comment by marinofaggiana** [comment]
Hi @jagallas, the develop is in w.i.p. for more detail please call our sales unit. 

Cheers
m.
