### ISSUE TITLE
Server URLs in punycode are treated as invalid

### ISSUE THREAD

**Issue by vlabmichl** [nextcloud/ios#305]
The app treats server URLs written in punycode as in valid.
Punycode allows special chars like "ä", "ö", "ü",... in the URL string.

This issue is blocking if your server has a punycode URL only.

See also:
* https://en.wikipedia.org/wiki/Punycode

**Comment by marinofaggiana** [comment]
mmm the managed is UTF8 ... can you create an account for test ?

**Comment by marinofaggiana** [comment]
@vlabmichl solved ?

**Comment by marinofaggiana** [comment]
If not solved, please reopen.
