### ISSUE TITLE
Backup your device option

### ISSUE THREAD

**Issue by Rotvig** [nextcloud/ios#308]
Is it possible to create a backup option ? For my iPhone and iPad.

**Comment by rakekniven** [comment]
Please explain in more details what you try to achieve.

**Comment by Rotvig** [comment]
Would it be possible to create a feature like the iCloud backup (https://support.apple.com/en-gb/HT204136 - https://support.apple.com/en-us/HT203977)

To enable people to backup there devices, and restore them at a later point in time.

**Comment by marinofaggiana** [comment]
Not possible, only Apple App can make the backup of iOS system
