### ISSUE TITLE
Support of "Locations" in iOS cloud integration

### ISSUE THREAD

**Issue by timbru31** [nextcloud/ios#31]
It would be nice if Nextcloud supports both import and export of the document, so it can be used directly as a storage in e.g. Pages or Word.

Notable ownCloud refs:
https://github.com/owncloud/ios/issues/361
https://github.com/owncloud/ios/issues/362
https://github.com/owncloud/ios/issues/389

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/tree/DocumentPicker

it's in progress.
