### ISSUE TITLE
[uploadAutoUpload] Video Uploads are broken

### ISSUE THREAD

**Issue by enoch85** [nextcloud/ios#310]
Auto Upload of videos doesn't work, not even in foreground. 

### Steps to reproduce
1. Close the Nextcloud app
2. Shot a video (in my case 39 seconds long)
3. Wait a few hours (move around to activate the "Change in location")
4. Notice that the Video isn't uploaded
5. Open the Nextcloud app in foreground
6. Notice that the Video sill isn't uploaded.

![photo 17-07-19 17-23-33 5256](https://user-images.githubusercontent.com/4511254/28375444-c78cbcd8-6ca7-11e7-92cd-93b0f44b15ef.png)

### App
2.17.4.00038

### Server
Nextcloud 12.0.0
PHP 7.0
Ubuntu Server 16.04
Apache 2.4
MySQL 5.7

**Comment by mkleger** [comment]
I have the same problem, but not only with videos but also with photos. When the ios app is closed, nothing happens.
If the app is open in the background, the photo is uploaded ...

**Comment by enoch85** [comment]
@mkleger Have you updated to the latest version? Photos work as expected now, at least for me.

**Comment by marinofaggiana** [comment]
This error is generate from AVAssetExportSessionStatusFailed (eg. low memory) from next version after this error the system do not remove from queue the item.

**Comment by marinofaggiana** [comment]
fixed on 2.17.5

**Comment by enoch85** [comment]
This still doesn't work on 2.17.5. Changing back to ownCloud soon if this isn't fixed. :/

**Comment by marinofaggiana** [comment]
please more info thx

**Comment by enoch85** [comment]
@marinofaggiana Please look in #306 for errors. We can close this and track it there instead.
