### ISSUE TITLE
MP3 Playback changing pitch slightly

### ISSUE THREAD

**Issue by meiersmarkus** [nextcloud/ios#3101]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Start Playback of a mp3 file with headphones
2. 
3.

### Expected behaviour
Tell us what should happen
It should be playing the file just Like it is

### Actual behaviour
Tell us what happens instead, if possible also add a screenshot
Slightly changing the pitch of the Music in waves. Very Hard to notice

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Environment data

**iOS version:** 18.0.1

**Nextcloud iOS app version:** 5.5.5.0

**Server operating system:** Linux?

**Web server:** Apache

**Database:** mariadb

**PHP version:** 8.2

**Nextcloud version: ** 29.0.7

**Comment by HadronSounds** [comment]
Same issue here. It especially happens when locking the phone or leaving the app. Then it goes wildly up and down. Problem exists on various iOS versions and various iPhones with all Nextcloud versions since 2022 (including the current one).
