### ISSUE TITLE
Office 365 and NextCloud IOS app not saving modification to document

### ISSUE THREAD

**Issue by jclgs** [nextcloud/ios#311]
With the version of NextCloud for IOS 2.17.4, we are now able to open file from Office 365, but when I modified a document and save it, it does not save to NextCloud. It looks like it save it directly on the iPhone.

OwnCloud app, when I hit save, it saves the document to NextCloud server. The only thing, I need to go on the OwnCloud IOS app to trigger the transfer between iPhone and NextCloud server.

It should be cool also if the NextCloud IOS app allow direct save to the NextCloud server.

How to reproduce:

1) Open Office Excel 365.
2) Select Open an Excel document in Excel 365.
3) Follow the step to open it from NextCloud IOS app.
4) When the file is opened, change something in it.
5) Save the file.
6) Close Excel 365 and wait.
7) No changes are pushed to the NextCloud Server.

****** You can create a new document via NextCloud IOS app. It creates it on the server, but with no data in the file. 0kb

OwnCloud App works, except that you need to return to the OwnCloud IOS app to get the upload finished. If it can be automatic without going back into the app...

**Comment by enoch85** [comment]
@jclgs Please close if fixed. Thanks!

**Comment by jclgs** [comment]
I tested a little bit the 2.17.6. It's working pretty fine. Creating file works. Adding data to a file works. Solves issue for us.

One improvement to add. :)
- Trigger the File Cache update when using Document Extension Provider.

If we use External CIFS mount linked on a  Windows Server, for example, If the file is modified into the Windows Network and not from NextCloud, when you open that document from the Document Provider Extension in O365 (Maybe other app too), the version opened is not the updated version on the CIFS server, but the one in the File Cache.

To get the latest version, you need to go back into the NextCloud IOS app, the File Cache update will be trigger and finally, when we will opened the document into O365, we will get the latest version.

Having the File Cache update trigger when using the Document Provider Extension can avoid going back into NextCloud IOS app, to update the cache and going back into O365 to open the latest version of the file.

Don't know if it's possible. :)

Thanks
Jonathan

**Comment by marinofaggiana** [comment]
Mmm the logical of extension is limitate ... for example is not possible send immediately from office a new file ...., for now sorry but I have other timeline ... but this is a good observation

**Comment by marinofaggiana** [comment]
If new issue, reopen

**Comment by RicoLaaa** [comment]
This issue is back on 7.1.3
7.1.2 worked fine, but issue was there before that from 7.0.7
It's like the 4th time it appears again this year...
What was fixed in 2017 that could be fixed now?
