### ISSUE TITLE
Build fails with Xcode 16

### ISSUE THREAD

**Issue by securitykernel** [nextcloud/ios#3110]
### Steps to reproduce
1. Install Xcode 16
1. Clone GH repo
2. Run `carthage update --use-xcframeworks --platform iOS`
3. Open project in Xcode and build

### Expected behaviour
The build should succeed.

### Actual behaviour
The build fails, because of an incompatible version of the referenced OpenSSL-Swift package.

### Logs

```
/Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Development-iphoneos/OpenSSL.framework/Headers/e_os2.h:265:9 Declaration of 'uint64_t' must be imported from module 'DarwinFoundation.stdint.uint64_t' before it is required
```
![Image](https://github.com/user-attachments/assets/37d27318-c30a-4189-8e0b-13b86201206c)

### Reasoning or why should it be changed/implemented?

In order to build the app with latest Xcode, OpenSSL needs to be updated to at least 3.3.2000 (https://github.com/krzyzanowskim/OpenSSL/issues/222).

### Environment data

**iOS version:** N/A

**Nextcloud iOS app version:** 5.5.5 (master also affected)

**Server operating system:** N/A

**Web server:** N/A

**Database:** N/A

**PHP version:** N/A

**Nextcloud version:** N/A

**Comment by Rello** [comment]
Hi,

please see the information in the readme. XCode 15 is currently required
https://github.com/nextcloud/ios?tab=readme-ov-file#xcode-15-project-setup

Regards,...

**Comment by securitykernel** [comment]
@Rello Works with Xcode 15, thanks. May I suggest however that you add a note to the README section explicitly warning that Xcode 16 is not supported, yet? I am probably not the only one misinterpreting this headline as "Xcode 15+". When is Xcode 16 support coming?

**Comment by toshanmugaraj** [comment]
Old Xcode 15  doesn't works with the latest Mac OS Sequoia.

**Comment by toshanmugaraj** [comment]
I updated the Openssl version 3.1.5006 and build succeeded.

**Comment by deveeloperuidai** [comment]
XCode 16.1--  with   pod 'OpenSSL-Universal', '3.3.2000'   installation getting  There is no XCFramework. found
