### ISSUE TITLE
AutoUpload bug

### ISSUE THREAD

**Issue by bmf89** [nextcloud/ios#313]
Hi guys,

I got a problem with the auto-upload function. If all photos and videos are backed up, the app will upload photos and videos again if I watch them through the Photo App or send them via iMessage etc. It is still annoying and I have tried to delete and restall the app ... 

Is there any option get this problem solved?

Best
Thorsten

**Comment by marinofaggiana** [comment]
Hi @bmf89 if you modify a foto or video the nextcloud ios resend it ... but only if changed the "modify data item" on camera roll

**Comment by bmf89** [comment]
Ok but why are these "modified" photos and videos still in the "today" view under "Photos"? 

Example:
- I open a photo which I took month ago and just send it via iMessage
- Nextcloud load it up
- under "photos" it is on the "today" view but this photo is an old one and I haven't change anything on this photo

On my point of view there are two possibilites:
1. The view von Photos is totally wrong and the App just check recently changed meta data or what else and ignore the creation date. It is really better at Dropbox ...
2. There is a bug

**Comment by enoch85** [comment]
@marinofaggiana I agree with @bmf89. The photos view in the app should respect creation date and not modification date.

For example; when I browse photos with the app, the app **should not** update the meta data and put that photo / video on todays date. It **should stay** as the date it was taken/created.

**Comment by bmf89** [comment]
@marinofaggiana Is it possible to implement an option to choose between a sort by "creation date" and "modification date"?

**Comment by marinofaggiana** [comment]
For now the API from server detect only the lastmodifieddate for item (item = files, directory etc)

**Comment by enoch85** [comment]
@bmf89 

>  Is it possible to implement an option to choose between a sort by "creation date" and "modification date"?

Please open another ticket for that. Thanks!
