### ISSUE TITLE
App crashes instantly after start up

### ISSUE THREAD

**Issue by Luto73** [nextcloud/ios#314]
Since the change of the picture names some days ago the app tries to upload more than 3000 old pics as news. This is already reported. Today I received an error message after that the app did not restart. If I start the app nothing happens. But: if I open up the "task manager" at iOS I see the app is still open but produced an error (see picture below). Killing the app and restarting it does not help. Any ideas?
![img_5515](https://user-images.githubusercontent.com/26164833/28476724-569e02f6-6e51-11e7-91ef-a7a51e3ba683.PNG)

**Comment by marinofaggiana** [comment]
Try with next version soon on App Store

**Comment by enoch85** [comment]
@Luto73 New version available today. Have you tested?

**Comment by Luto73** [comment]
I just updated the app but it still crashes :-(

**Comment by marinofaggiana** [comment]
@Luto73, crashes, errors .. ? Thanks

**Comment by Luto73** [comment]
Same error codes as I posted already. I rebooted my device but this did not help either. Is there any way I can debug the app?

**Comment by marinofaggiana** [comment]
@Luto73  same error code (see up) .. and  after crashes ?

**Comment by Luto73** [comment]
The app does not really start at all. I open it up and it seems like nothing happened. I can only see that it started by double clicking the home button. I will try to get some server logs to see what happens there.

**Comment by Luto73** [comment]
I just checked the server log. The app crashes before it establishes a connection to the nextcloud server. I deleted and reinstalled the app. This worked and the app uploads all pictures and videos again. Unfortunately none of the now possible names match the old one (but this is another issue).

**Comment by marinofaggiana** [comment]
Ok I closed
