### ISSUE TITLE
Timer based background sync for photos.

### ISSUE THREAD

**Issue by cycotron69** [nextcloud/ios#315]
Would be nice to have a timer/schedule based background photo sync trigger in addition to a GPS trigger.  Here are my 3 reasons for your consideration:

1. For privacy reasons, I turn off GPS for many apps and only use the "While in use" options for the ones I allow.  I prefer not to have GPS always on for just a file sync. 

2. Aside from the privacy reasons, it seems it would increases power consumption by having location service on all the time.  If I'm on the road, battery life becomes important.

3. Finally, I'm not sure how "significant" a location change would be required to trigger a sync.  What if I'm at a single location for extensive amount of time, like a party, sports event, or holiday at the rents?

A timer/scheduled sync trigger would seem to be a good alternative for at least some of us, that's until Apple get off their ass and provide a change observer for their camera roll.  I hope you will consider it, and keep up the great work you guys are doing with the server and the client apps.

**Comment by marinofaggiana** [comment]
Read : https://github.com/nextcloud/ios/issues/215

**Comment by enoch85** [comment]
@cycotron69 It's not possible due to Apple restraints. Sorry! Closing this.
