### ISSUE TITLE
Collapsible viewer area

### ISSUE THREAD

**Issue by cycotron69** [nextcloud/ios#316]
Is it possible to make the file/photo viewing area collapsible or adjustable in size?  Especially on iPad, it takes up significant screen real estate. If I'm simply trying to browser and locate a file or photo, seems it would be nice to have the use of the entire screen to display longer file names or more photo thumbs, maybe even bigger thumbnails.  Otherwise it just seem like wasted good white space.

**Comment by kbeerepoot** [comment]
> Is it possible to make the file/photo viewing area collapsible or adjustable in size? Especially on iPad, it takes up significant screen real estate. If I'm simply trying to browser and locate a file or photo, seems it would be nice to have the use of the entire screen to display longer file names or more photo thumbs, maybe even bigger thumbnails. Otherwise it just seem like wasted good white space.

Agreed !  I would appreciate it if the file/photo viewing area would appear only **after** a specific file/photo is **selected**, and would be absent/disappear when it is just a folder/directory that is selected. That would make it much easier to read the longer file/photo/folder/directory names when browsing the directory structure.
