### ISSUE TITLE
Image files "upload" in wrong format

### ISSUE THREAD

**Issue by biggreenogre** [nextcloud/ios#3163]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Open Nextcloud from IOS home screen
2. Select "More" in bottom right of screen
3. Tap "Settings"
4. Tap "Advanced"
5. Ensure "Most Compatible" is turned OFF
6. Select "Files" in bottom left of screen
7. Tap "+" n bottom centre of screen
4. Tap "Upload photos or videos"
5. Select a photo
6. Tap "Done" in top right of screen
7. View file list

### Expected behaviour
Photo has been "uploaded" as "IMG_1234.HEIC" 

### Actual behaviour
Photo has been "uploaded" as "IMG_1234.PNG" 
 
### Logs
```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```
N/A
### Reasoning or why should it be changed/implemented?
File format should not be converted unless option "Most Compatible" is turned ON.
I noticed this whilst creating and attaching screenshots for two other bug reports with this release.
https://github.com/nextcloud/ios/issues/3161
https://github.com/nextcloud/ios/issues/3162

### Environment data

**iOS version:** e.g. iOS 17.6.1
17.7.1
**Nextcloud iOS app version:** see More > Settings
6.1.3.0
**Server operating system:**
"Raspbian GNU/Linux 10 (buster)" 
**Web server:** Apache, nginx
Apache
**Database:**
Mariadb
**PHP version:**
7.3
**Nextcloud version:** see Nextcloud admin page
23.0.12

**Comment by i2h3** [comment]
@biggreenogre Can you tell which format your taken photos usually have? You can check in the iOS system settings under _Camera_ → _Formats_. May be labelled differently, I only have it set to German at hand right now.

**Comment by i2h3** [comment]
@marinofaggiana I took a HEIC photo on my iPhone, uploaded it in the described way with the maximum compatibility setting of the Nextcloud app turned off and it ended up as HEIC on the server. With the app setting turned on, it ended up there as JPG. Appears to work as expected for me.
