### ISSUE TITLE
PDF page overlaps when zoomed in in expanded viewer.

### ISSUE THREAD

**Issue by cycotron69** [nextcloud/ios#317]
If I open a multi-page PDF doc, then expand the viewer, 1 and 1/2 page of the doc is displayed.  When pinch to enlarge the first page, the 2nd page (half of it) remains in place, blocking texts on the zoomed in 1st page. Same behavior whether I'm in portrait or landscape mode.  If I change orientation after expanding the viewer, then the viewer will correct into a single page display mode without page overlap.  However, if I then go back to landscape mode and shrink the viewer again, the page is displayed offset, only half page is on screen.  I haven't really tried to test every combinations of steps, but there seems to be some inconsistency with how the PDF is displayed when viewer size changes.

**Comment by rakekniven** [comment]
Which iOS app version are you using?

**Comment by cycotron69** [comment]
NextCloud for iOS 2.17.5.00005
