### ISSUE TITLE
Files in favorites are not updated on real files update

### ISSUE THREAD

**Issue by Xld137** [nextcloud/ios#3175]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Add file to favorites. 
2. Wait some time (in my case a day or two). 
3. Change the file content (I do it on macOS that is also connected to my NC service).
4. Open favorites tab in IOS app.
5. See problems:
- file date (modified date) is not updated,
- if you try to open file with respective app or choose to share -> open with another app (in my case  xlsx via Collabora/MS Excel) the app doesn't start at all. 

To fix this I go to place in IOS app where the file is stored and then go back to favorites. It makes favorites update the file.

### Expected behaviour
Immediately updated favorites after changing of original file, no matter from which device it happened

### Actual behaviour
Favorites contains not updated or maybe corrupted file version.

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Environment data

**iOS version:** iOS 17.7

**Nextcloud iOS app version:** 6.1.3.0

**Server operating system:** Debian 12

**Web server:** Nginx

**Database:** default in AIO

**PHP version:** the latest from AIO

**Nextcloud version:** 29.0.8

**Comment by i2h3** [comment]
## Remarks
 
* A reproduction attempt with most recent iOS 18.1 (Simulator), development state and most recent AiO Nextcloud 30.0.1 failed.
* I do not have an iOS device with iOS 17.7 at hand. I can only attempt to reproduce with app 6.1.3.0 on iOS 17.5 (Simulator) against Nextcloud 29.0.9 RC1.
* The device from which the change originates should be irrelevant. It is a matter of the iOS app learning about the updated state on the server. For the test, I replaced an existing Markdown file with a changed revision through the web user interface.

## Environment

* App 6.1.3.0 deployed from Xcode
* iPhone 15 Simulator with iOS 17.5
* Local Nextcloud 29.0.9 RC1 Deployment

## Result

I can confirm that the reported issue of outdated time information exists with the exception that the download (Share → Save in Files) of the subject works with the latest revision being fetched. A pull to refresh updates the metadata of the favorites just like reentering the parent directory in the app's file browser does.

Interestingly, a second try with the latest released app version on iOS 18.1 in connection to a Nextcloud 30.0.1 renders the sharing indeed broken. Nothing happens after the app apparently failed to file download the content silently. A pull to refresh in the favorites does not help. The parent directory of the file must be reentered in the app's file browser.
