### ISSUE TITLE
New naming feature in 2.17.5 is not applied

### ISSUE THREAD

**Issue by Luto73** [nextcloud/ios#318]
I just changed the naming convention in the iOS app to YYYY-MM-DD_HHmmss (see screenshot). Unfortunately the files uploaded still use the name YYYY-MM-DD-HHmm-PICNUMBER:

xx.yy.zz.aa - username [23/Jul/2017:21:22:09 +0200] "PUT /remote.php/webdav/Photos/2017/06/2017-06-29-0852-5408.jpg HTTP/2.0" 201 0 "-" "Nextcloud/00005 CFNetwork/811.5.4 Darwin/16.6.0"

It seems, that if the list of uploads is created with another naming convention there is no change possible.

![img_5519](https://user-images.githubusercontent.com/26164833/28502197-6d15391c-6fed-11e7-8246-80470e881f42.PNG)

**Comment by marinofaggiana** [comment]
Yes, it's correct

**Comment by enoch85** [comment]
@Luto73 This is not a bug. Please close.

**Comment by Luto73** [comment]
Although I see it as bug (but know that this is an end user view) I close this issue.

**Comment by mario** [comment]
How is this not a bug? It does something unexpected...

**Comment by marinofaggiana** [comment]
Hahaha naaaaaaa

**Comment by enoch85** [comment]
@mario It doesn't. The 'PICNUMBER' is default. Maybe add it do the description text? Or am I missing something here?
