### ISSUE TITLE
After latest Nextcloud iOS update (6.1.5.1), Files integration is not working

### ISSUE THREAD

**Issue by Fletch-99** [nextcloud/ios#3180]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new

### Steps to reproduce
1. Open iOS Files app
2. Go to Nextcloud
3. No files/folders are shown, just “Loading”spinning 

### Expected behaviour
Show my files/folders

### Actual behaviour

No files/folders are shown, just “Loading”spinning. It was working fine before the latest Nextcloud iOS update

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Reasoning or why should it be changed/implemented?
Because it’s not working

### Environment data

**iOS version: 18.1**

**Nextcloud iOS app version: 6.1.5.1**

**Server operating system: Raspberry Pi OS Linux**

**Web server: Nginx**

**Database:PostgreSQL**

**PHP version:8.3**

**Nextcloud version:30.02**

**Comment by NextClaus** [comment]
@marinofaggiana @Fletch-99 
We have the exact same issue! It also affects iOS 17.7.1 devices. In our case, I still can see the top-level folders but I cannot access them.
In case of iOS 17 the following error appears:
![Image](https://github.com/user-attachments/assets/5942ac4c-58ba-4910-abf3-653915070a14)

In case of iOS 18 just a "loading circle" appears.

As there were many app updates by @marinofaggiana in the last couple of days, I'm not sure if I installed really each of them but I think so. As @Fletch-99 already reported, the issue appeared with 6.1.5.1 for the first time. I think previous releases were not affected (not 100% sure).

Our setup: Nextcloud Server 28.0.10

@marinofaggiana If you need log files, please let me know.

**Comment by NextClaus** [comment]
Works again! Thank you.
