### ISSUE TITLE
Problems with missing files in nextcloud/ios

### ISSUE THREAD

**Issue by josaladino2** [nextcloud/ios#319]
I am having some problems with iphone sync client. A while back I tried to put some files in the favorites area and they never showed up there, and then I could no longer see them in the normal folder structure. Now I have some of those file with the favorites star but they are not in favorites. After I send the file to someone, the file disappears from the standard folder. I the files still show up in the master database but just don’t show up on my iphone. I have delete and reinstalled the app several times and it still has the same problems. Any ideas?

**Comment by marinofaggiana** [comment]
@josaladino2 this item are "external mont" ?

**Comment by marinofaggiana** [comment]
Close, if you haven't resolved reopen.
