### ISSUE TITLE
Order [+] 

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#320]
@jancborchardt Order Item ?

<img width="416" alt="schermata 2017-07-26 alle 16 57 18" src="https://user-images.githubusercontent.com/8616947/28627975-9581e908-7223-11e7-9dcf-a3eed1aa1a37.png">

**Comment by jancborchardt** [comment]
1. Upload photos or videos
2. Upload file
3. Create text file
4. Create folder

Also please use that wording. :)
And except the folder icon, which should be theme color, the icons should be grey as they are in the file type icons. Not themed. :)
(And one more detail: The icons should just move a bit to the right, to be centered between the left border and the text.)

**Comment by marinofaggiana** [comment]
<img width="396" alt="schermata 2017-07-26 alle 18 52 45" src="https://user-images.githubusercontent.com/8616947/28633321-b0e9d72c-7233-11e7-9ed8-2afe4d504999.png">

**Comment by marinofaggiana** [comment]
<img width="392" alt="schermata 2017-07-26 alle 18 58 33" src="https://user-images.githubusercontent.com/8616947/28633556-7b1eebe0-7234-11e7-88f6-dd9c959dd182.png">

@jancborchardt

**Comment by jancborchardt** [comment]
Looks good! Cancel should always be red though and not affected by theming, just like the delete action background color. ;)

**Comment by marinofaggiana** [comment]
Cancel it's now black, this is not delete.

**Comment by jancborchardt** [comment]
Ah right, of course! :)
