### ISSUE TITLE
Automatic upload stops after around 200 images

### ISSUE THREAD

**Issue by alexhass** [nextcloud/ios#323]
I configured to upload my phone content to nextcloud if WLAN is enabled. This means 6000 images and videos need to be uploaded. After around 200 images (just a guessed estimate) it stops uploading. It is just a guess, but it could stop once the lock screen becomes active.

This does not mean it is a background upload to be honest. Please upload until completed.

**Comment by marinofaggiana** [comment]
hi @yamlfd  please, before read old post, use search Issue with background (for example).

**Comment by yamlfd** [comment]
Cannot find any duplicate...
