### ISSUE TITLE
Automatic upload uses GPS, but should not (extreme battery drain)

### ISSUE THREAD

**Issue by yamlfd** [nextcloud/ios#324]
I have no clue why you require GPS for background uploads, but it drains my battery to empty.

I see no reason for this behaviour and GPS is knonw to be the most heavy battery leaching process you can think off. All images are already GPS tagged by the iphone. Sooo no need to tag again, what also meens no need to calculate my position at all and no need to waste my battery!

If the phone is inside WLAN it need to upload the files - only than. WLAN on/off can be detected by the app without GPS.

The battery drain with this app is really extreme... ~800 images, 30% battery loss. I hope you can improve this and I hope it does not get empty before I'm back to a charger... :(

**Comment by marinofaggiana** [comment]
read : 

https://github.com/nextcloud/ios/issues/215

**Comment by yamlfd** [comment]
Could be true - I'm not in the code. The app request GPS from me and the description does not tell anything about Cell radios. The battery drain is EXTREME and I still see no reason why this is needed. Only WLAN on/off is an indicator that should start the sync... normally. At least I do not have a 100GB LTE flat on mobile... :). I do not get the design idea why my movement should start a sync. Whereever I am, after the photo is taken it should be uploaded if there is wlan. if no wlan, wait until wlan comes up and than sync. To detect a wlan goes on and off you should not require my position... also if one kilometer inaccurate.

**Comment by enoch85** [comment]
@yamlfd Blame Apple. Their the ones who demands this to be able to upload photos in the background.

**Comment by yamlfd** [comment]
Can you extend the description in the app, please?

I fighted with myself to enable this setting in a way that I was more 99% on the side to NOT enable GPS for nextcloud app as it looked like a serious privacy issue to me. The enable must explain why the app need this in a way that do not concern people. Please explain in details why you need it, please.

**Comment by marinofaggiana** [comment]
![img_6646](https://user-images.githubusercontent.com/8616947/28744606-b1aab540-7464-11e7-8430-ef1086bc0709.PNG)

The description is clear and correct

**Comment by yamlfd** [comment]
What concerns me is the last part. My location does **not** change significantly when I make photos. However I expect that the app uploads them once I made them and I have seen it uploads more or less directly. I think it is not correct that I need to move 1km to get my photos uploaded, isn't it? If WLAN is active it will be uploaded immediately after the photo has been taken. Correct me if I'm wrong.

I think this info is _inacurrate_ than or at least misleading. It sounds like I need to move 1km to start the sync. Can you think of other wording for this?

Your sentence may be technically correct, but it is too technical. Hell - that I'm saying this... normally it cannot be enough technical details to understand how something works. May blame Apple the unfriendly way.

**Comment by marinofaggiana** [comment]
I agree butthis  is Apple system and political, do not exists a background system for app iOS, when your app is in background your app if freeze ... Dropbox (I think) has find for first this possibility... but is only a ploy.. several users are complaining but this is only way for detect new item in camera roll ... work it ?? Mmm for me  it's ugly but the users want this ugly possibility... if you don't want is simple ... set off :-)

**Comment by yamlfd** [comment]
If you could just give the users a better fealing that this is only required to make this feature working and you are not using it to track their position (for privacy reasons) it would be more than helpful. Can you do this, please? I have a very bad fealing if a software tracks my position and it is **not** a navigation or related software.

**Comment by mario** [comment]
@jospoortvliet can we mention this somewhere on our website?

Good explanation: https://www.dropbox.com/help/mobile/background-uploading-location-data

@all I understand your complaints. This is how it is. It is a technical limitation, and similar things exist on Android (however, they are resolved differently). We will try to make this more clear, but technically there's not much we can do except for allowing to disable background uploading. cc @marinofaggiana

**Comment by marinofaggiana** [comment]
Oh yes good solution @mario ... it's a start for next manual

**Comment by yamlfd** [comment]
Has one of youa screenshot of dropbox app. It seems to require an expensive upgrade of dropbox to see how the app interface looks like.

**Comment by yamlfd** [comment]
Found something that is much better info.

Why does the app stop uploading even when the Background App Refresh is turned on?

Because Apple only allows background apps 10 minutes of execution time before being forcefully suspended.

**Comment by thibaultamartin** [comment]
Hi @marinofaggiana 
Wouldn't [this (Observe and Response to Changes)](https://developer.apple.com/documentation/photokit/browsing_and_modifying_photo_albums#3035833) allow to not use location services, but be notified when an event occurs in the Photos library instead?

**Comment by ndarr** [comment]
Battery drain problem occurs again on client version 2.25.0.15 and server version 17.0.1. iOS is running on version 13.2.3
![Battery Usage](https://user-images.githubusercontent.com/14993570/69524980-74921400-0f67-11ea-9355-d48e2ae282a0.png)

**Comment by stevenwcarter** [comment]
Over 50% of my battery use the past two days has been NextCloud in the background on 2.25.0.15. I’ll need to disable background photo sync now. Best part is I only took like 8 photos with my phone 😀
