### ISSUE TITLE
Photo view - Sort by options

### ISSUE THREAD

**Issue by bmf89** [nextcloud/ios#326]
As in another ticket required here it comes:

Can you implement an option to choose between "creation date" and "modified date" in the photo view? As described in the other ticket at the moment all uploaded videos and photos are sorted by the modification date which isn't efficient if you want to search for a video / photo.

**Comment by marinofaggiana** [comment]
@bmf89 I don't have this date

**Comment by bmf89** [comment]
Because the API provides a modification date only? That isn't really satisfying :( 
And there is no possibility to change this in nextcloud 12.x ?

**Comment by marinofaggiana** [comment]
This is not a nextcloud server issue but a limitations of WebDAV driver for now is in enhancement request :-)
