### ISSUE TITLE
What should "Label" and the line mean?

### ISSUE THREAD

**Issue by yamlfd** [nextcloud/ios#329]
It is shown with a 50% blue bar... ? Cannot find an issue about this. Looks like an unfinished feature... maybe planed to show my usage?

Client 2.17.5 on both ipad and iphone.

![img_0128](https://user-images.githubusercontent.com/4450722/28747734-1fe89770-74a6-11e7-95a2-34ce63c0e510.PNG)

**Comment by rakekniven** [comment]
Run v2.17.5.0005 and it's is different. Instead of Label it shows my current quota in words and the line is a "progress bar" to show it graphically

**Comment by rakekniven** [comment]
Have the same issue on an iPhone 4S. Which model are you using?

**Comment by marinofaggiana** [comment]
🙄🙄🙄 What's is this !??!?

**Comment by rakekniven** [comment]
Maybe iOS related?

**Comment by marinofaggiana** [comment]
Mmm I think this is a problem before crash... maybe a fatal exception

**Comment by yamlfd** [comment]
iPad Pro and IPone 7S both iOS 10.3.2. 

After I ran a occ filescan on server side it changed. Looks like the ios app has a bug when the server has a counting problem or does not provide the usage. 

The counting problem an unknown bug in 12.0 server. There is a related bug known with 32bit php, but not with php 64bit and counters.

The bug in the app is that it has an unhandled error condition. Better the app says it cannot get the value from server and tell the user that there is a problem getting the usage.

**Comment by marinofaggiana** [comment]
But i don't understand this capture is on "Fotos" tab ?

**Comment by yamlfd** [comment]
No, on More tab.

**Comment by marinofaggiana** [comment]
Ahhhh ok, now i more clear !

**Comment by rakekniven** [comment]
I have a few devices running iOS 10.3.2 and everything works like expected.
Only the iPhone 4S with iOS 9 show that issue.
Server is v11.0.3

**Comment by wallenium** [comment]
Working for 2.17.6 (3) on my iPhone 6s.. Maybe related to NC Server Version? I run 12.0.1 RC4...?

**Comment by rakekniven** [comment]
V2.17.6 is not out.

**Comment by marinofaggiana** [comment]
@rakekniven do u have this issue with iOS9 ? confirm ?

**Comment by rakekniven** [comment]
See my comment above. https://github.com/nextcloud/ios/issues/329#issuecomment-319795569

**Comment by rakekniven** [comment]
Does this mean you hide label and bar by default and only show it if rel values are present?

**Comment by rakekniven** [comment]
Hello @marinofaggiana just tried TestFlight v2.17.6.11 and now it is a bug.
See attached screenshot. 
![2017-08-15 23-08-30-6573](https://user-images.githubusercontent.com/2069590/29412399-dfb075b2-8358-11e7-861c-b42349290c8a.png)

 Value is not visible anymore.

**Comment by marinofaggiana** [comment]
Please @rakekniven,  error in Activity ? try with clear cache

**Comment by marinofaggiana** [comment]
Very strange, @rakekniven I have changed a constraint type ... please try with next build, thanks

**Comment by rakekniven** [comment]
Still not working, but it looks different now. Tested using build 13 on iPhone 5s.

See
![2017-08-29 22-50-53-6582](https://user-images.githubusercontent.com/2069590/29923571-536d1ad0-8e5a-11e7-8012-7693f6c12a5f.png)

**Comment by marinofaggiana** [comment]
Version iOS ?

**Comment by rakekniven** [comment]
10.3.3

**Comment by marinofaggiana** [comment]
Oh ! Very strange ... Oo .. same server same account ?

**Comment by rakekniven** [comment]
Yes, same account on same server.
Please fix it for next release. Or hide label and line.

**Comment by marinofaggiana** [comment]
I don’t understand where is the issue ...

**Comment by yamlfd** [comment]
Hiding is not bugfixing. At my case it was a server problem... may better to increase debugging on the phone to find the source of the issue.

**Comment by rakekniven** [comment]
@yamlfd  Hiding is better than showing wrong numbers, or?
What did you change server side?

@marinofaggiana I will check server issues. Got v12.0.2 running and web UI tells me that my user is using 0Bytes.

**Comment by yamlfd** [comment]
Occ file scan all on server

**Comment by yamlfd** [comment]
'sudo -u www-data php occ files:scan --all -v'

**Comment by yamlfd** [comment]
I's better you show the error from the server... so I know where to look for what's wron. Or at least show a line like "failed to get data from server" if the server returns wrong infos or no integers.

**Comment by rakekniven** [comment]
In my case it was not server side issue.

There is a bug in v12.0.2 of server:
See https://github.com/nextcloud/server/issues/5031

Fix:
https://github.com/derkostka/server/commit/09b120c6dafa9327b2c2b61efcb59376b944d622

Now it works as expected. We can close this from my POV.
