### ISSUE TITLE
Change default file name schema to YYYY and not only YY

### ISSUE THREAD

**Issue by yamlfd** [nextcloud/ios#332]
I'm quite new to this app, but what stesses me extreme is - I configured auto upload with a useful default of YYYY (4 digits) - so it cannot confuse me if 17-06-05 is shown and I'm not sure if this 17 is the day of a month or the year.

I vote for changing the default of the app to YYYY and not just YY.

**Comment by rakekniven** [comment]
I fully support this. Having full year as prefix has benefit for existing archives.

**Comment by rakekniven** [comment]
We stay with #359
