### ISSUE TITLE
Use configured timestamp for filename instead of random ID

### ISSUE THREAD

**Issue by phieber** [nextcloud/ios#333]
Hi,
in the latest version when I upload a photo, an ID is used as filename. The filename should respect the settings in the APP and should include the timestamp in the filename.

Steps to reproduce: 
Install the app (2.17.5.00005) latest
Make a photo and store it via the APP in a folder.

**Comment by rakekniven** [comment]
Please provide an example. 
Write actual name and desired name.

**Comment by phieber** [comment]
![iosfilenameissue](https://user-images.githubusercontent.com/1208351/29110162-fc2c037e-7ce5-11e7-871c-0ff044eb9187.png)

**Comment by rakekniven** [comment]
Hmmh, cannot reproduce it.
Have been on vacation with family and took more than 200 pics and vids with 4 devices. All went right like you first two images.
Two devices have same version like yours.
Other two used new Testflight versions.

**Comment by phieber** [comment]
Weird... have you uploaded them from within your Camera App?

Von meinem iPhone gesendet

**Comment by rakekniven** [comment]
I took pictures with camera app. 
Selected Nextcloud app and pictures got uploaded to my NC.

**Comment by marinofaggiana** [comment]
When you use the extensions  (share or document) Nextcloud take the source filename

**Comment by phieber** [comment]
In other words, this is due to an iOS update and not caused by the App 
itself?

**Comment by marinofaggiana** [comment]
No, in other word from external upload mode use the source filename without conversion

**Comment by phieber** [comment]
Thanks Marino for the clarification but it would be technically possible if I am not mistaken

Von meinem iPhone gesendet

**Comment by marinofaggiana** [comment]
sure this is a choice ! but this choice is important for upload document from external extension without change filename ;-)
