### ISSUE TITLE
401 responses are ignored

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#334]
* setup an account in the iOS app
* change the password on the server
* actual: the app retries all requests (PROPFINDS, SEARCH, GET, MKCOL, ...) that cause a 401
* expected: the app should stop doing requests to not run into the brute force protection and ask the user for the password

See https://github.com/nextcloud/server/issues/6010

We got complains that the log is spammed by to many tried logins.

cc @marinofaggiana

**Comment by marinofaggiana** [comment]
@MorrisJobke fix build 00006

**Comment by MorrisJobke** [comment]
Works 👍
