### ISSUE TITLE
"more" screen shows name as GUID when using LDAP integration

### ISSUE THREAD

**Issue by wizdude** [nextcloud/ios#339]
i have my nextcloud LDAP integrated with active directory. when i go to the "more" screen in the ios client all i see at the top of the screen is my active directory GUID (ie: A27BE271-1234-6676-........)

i assume i am meant to see my name here.

to the left of this i see an icon of a head. is that meant to be my profile picture from nextcloud?

cheers, wizdude.

**Comment by marinofaggiana** [comment]
@wizdude is this fixed?

**Comment by marinofaggiana** [comment]
@wizdude ping
