### ISSUE TITLE
select file and "save images and videos on photo album" does not work

### ISSUE THREAD

**Issue by wizdude** [nextcloud/ios#344]
if i "select" and choose one or more files and then use the "save images and videos on photo album" i receive the error:

(X) Save Images and videos on photo album
Error: File not saved on photo album

cheers, wizdude

**Comment by marinofaggiana** [comment]
Hi @wizdude, please, more info here, is the photos/Video compatible with cameraroll of iPhone ?

**Comment by user23498723452** [comment]
I know this is an old issue, but I believe in seeing the same issue.

I am trying to place some random pictures in nextcloud into an ipad photo album.

it doesn't seem to do anything.

**Comment by marinofaggiana** [comment]
@user23498723452 Can be an incompatibility  format for the photo album ?

**Comment by swifty99** [comment]
I would like to bump this up.

The issue for me is in the multiple files action.

The files (pictures) can be selected indivually, "open with" and stored on the iphone. However, if select multiple pictures, the option "open with" is not availble.

The feature I am missing: select multple pictures and store them on the device locally.

Awesome app and nextcloud!
