### ISSUE TITLE
Files uploaded via "Favorites" tab end up in the root folder

### ISSUE THREAD

**Issue by jcgerhard** [nextcloud/ios#346]
If you are going to upload a file or create a folder in a location that is starred/marked as favorite and you choose this location via **Favorite** tab it is going to end up in the root/base folder and not in the desired place. If you use this feature frequently, this behavior is going to be very troublesome.
I picked this up on 3 different iOS devices.

**Comment by rakekniven** [comment]
Hello @jcgerhard 
Please test with new release and provide feedback. Thank you.

**Comment by jcgerhard** [comment]
Hey Devs, I have tested the new release today. The issue seems to be fixed! Thank you guys. Great work! The app runs like a charm!
