### ISSUE TITLE
moving file totally killed ios client

### ISSUE THREAD

**Issue by wizdude** [nextcloud/ios#347]
i was testing the "move" of a file and the ios client kicked me back to the initial login screen with an animated "moving file" dialog on top. i eventually had to terminate the app.

i'm now unable to use the client at all. first time in i could see the old version of the file system before i moved the file in question. now i can't see any files at all. each time i try to refresh a folder it takes me back to the login screen. i enter credentials but it doesn't appear to do anything for me.

i've managed to get into the settings and select "exit" to wipe all settings. i can no longer log back into nextcloud. i get errors such as "Error: The request timed out".

i can use my nextcloud server via the web interface ok, and the desktop client is still syncing files ok.

i even went to the extent of restarting apache on my nextcloud but this made no difference.

i've restarted the client many times and eventually i've been able to login, however everything is very slow and unreliable. folders will not come up.

how do i reset the client completely?

cheers, wizdude.

**Comment by marinofaggiana** [comment]
Go to Settings -> Advanced -> Exit

**Comment by wizdude** [comment]
as mentioned, i've already tried that. i did it again, but i still can't login.

first time i login it spins and then goes back to the login screen again.
second time it comes up with the error "Error: The request timed out".

after a while it goes into the file view with no files visible.

i can't use the app at all now.

i can see on my nextcloud server that even though the client has timed out and failed that it is still trying to retrieve information from nextcloud.

this is what the nextcloud logs show even though the client is reporting errors and is unusable.

```
192.168.80.141 - wiz [10/Aug/2017:07:45:15 +1000] "PROPFIND /remote.php/webdav HTTP/1.1" 207 830
192.168.80.141 - wiz [10/Aug/2017:07:45:15 +1000] "PROPFIND /remote.php/webdav/Photos HTTP/1.1" 207 2889
192.168.80.141 - wiz [10/Aug/2017:07:45:17 +1000] "REPORT /remote.php/dav/files/wiz HTTP/1.1" 404 225
192.168.80.141 - wiz [10/Aug/2017:07:45:17 +1000] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 1026
192.168.80.141 - - [10/Aug/2017:07:45:47 +1000] "GET /apps/theming/loginbackground HTTP/1.1" 200 96764
192.168.80.141 - wiz [10/Aug/2017:07:45:17 +1000] "PROPFIND /remote.php/webdav HTTP/1.1" 207 830
192.168.80.141 - wiz [10/Aug/2017:07:45:46 +1000] "PROPFIND /remote.php/webdav HTTP/1.1" 207 22422
192.168.80.141 - wiz [10/Aug/2017:07:45:47 +1000] "GET /ocs/v2.php/cloud/user?format=json HTTP/1.1" 200 329
192.168.80.141 - wiz [10/Aug/2017:07:45:47 +1000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 200 74
```
i'm going to uninstall and reinstall the app now and will report back.

**Comment by wizdude** [comment]
strange. even though i uninstalled and reinstalled the app, as soon as i launched it i can see from the nextcloud server end that it starting talking using my previous credentials.

after a while it's gone to the login screen, but i can see that it's still polling my nextcloud server.
the login screen shows my server name and username even though i removed the app.

something is strange here. i don't think the app is cleaning up after itself correctly.

**Comment by marinofaggiana** [comment]
@wizdude wait next build

**Comment by wizdude** [comment]
thanks will do.

i can't get past the login screen now to do anything else. the "cancel" button is no longer on the login screen so i can't do another "exit" or change any settings.

**Comment by marinofaggiana** [comment]
@wizdude remove all and install last build 00007

**Comment by marinofaggiana** [comment]
@wizdude solved ?

**Comment by wizdude** [comment]
no. i'm not having any success at all.

i can't even go back to using the nextcloud app from the app store. if i reset everything and uninstall the testflight build and install the original app from the app store, as soon as it launches it immediately exits back to iOS. i don't even get a chance to login.

i've been doing a whole pile of testing. i've tried using non-LDAP credentials on the client without success.

i keep getting errors like "Error. It is not possible to connect to the server at this time. Request failed: unauthorised (401)" and "Error. It is not possible to connect to the server at this time. The request timed out".

i have no problems using safari on my phone to access my nextcloud at all. i can happily log in with no issues and use the web interface.

i can't see anything useful in the nextcloud logs. i'm continuing to see what i can debug from the server end.

**Comment by wizdude** [comment]
ok. i'm a step closer now! i've partially worked out why things were going so wrong.

the brute force detection in nextcloud is added my account into the oc_bruteforce_attempts table. this is why i couldn't log in from the nextcloud ios client. 

there were heaps of entries in this table for my phone's ip from work, home, and while mobile. i erased all of the entries from this table and i could instantly log back in again with nextcloud ios.

however it only lasted for a few minutes, and now there is an entry back in the oc_bruteforce_attempts table again.

this is only happening with the testflight build. i erased the table again and tested using the app store version from my iPad and i didn't see any listings, however if i fire up the testflight build on my iPhone i get entries in this table the second I launch the application.

i just tried it now and the testflight client is sitting on the login page, and it keeps adding more and more entries into the oc_bruteforce_attempts table (i've got around 28 entries added now as i am writing this comment).

but i haven't even logged in yet! as i'm completing this comment i'm up to 34 entries in the table.

**Comment by wizdude** [comment]
i can see what's changed. if i look at my webserver logs on the nextcloud box, i can see the testflight ios client is now trying to authenticate using my LDAP GUID and not my username.

here is me using my iPad with the app store nextcloud:
```
x.x.x.x - wiz [12/Aug/2017:23:11:39 +1000] "PROPFIND /remote.php/webdav/test%20offline%20folder HTTP/1.1" 207 1008
x.x.x.x - wiz [12/Aug/2017:23:11:39 +1000] "PROPFIND /remote.php/webdav HTTP/1.1" 207 988
x.x.x.x - wiz [12/Aug/2017:23:11:42 +1000] "PROPFIND /remote.php/webdav/ZZZ HTTP/1.1" 207 988
x.x.x.x - wiz [12/Aug/2017:23:11:42 +1000] "PROPFIND /remote.php/webdav/ZZZ HTTP/1.1" 207 6027
```
and here is me using my iPhone with the testflight nextcloud - using the same account as above (i've slightly obsfucated the GUID): (note also the 401 errors)
```
x.x.x.x - A27BE999-1061-4199-A994-B1CC52699999 [12/Aug/2017:23:13:13 +1000] "GET /index.php/apps/files/api/v1/thumbnail/128/128/2016-11-14%2021-15-57%200293.png HTTP/1.1" 401 43
x.x.x.x - A27BE999-1061-4199-A994-B1CC52699999 [12/Aug/2017:23:13:13 +1000] "PROPFIND /remote.php/webdav/Photos HTTP/1.1" 401 234
x.x.x.x - A27BE999-1061-4199-A994-B1CC52699999 [12/Aug/2017:23:13:13 +1000] "GET /index.php/apps/files/api/v1/thumbnail/128/128/2016-12-18%2021-45-41%200296.png HTTP/1.1" 401 43
x.x.x.x - A27BE999-1061-4199-A994-B1CC52699999 [12/Aug/2017:23:13:13 +1000] "PROPFIND /remote.php/webdav HTTP/1.1" 401 234
x.x.x.x - A27BE999-1061-4199-A994-B1CC52699999 [12/Aug/2017:23:13:13 +1000] "GET /index.php/apps/files/api/v1/thumbnail/128/128/2016-12-18%2021-45-41%200296.png HTTP/1.1" 401 43
x.x.x.x - A27BE999-1061-4199-A994-B1CC52699999 [12/Aug/2017:23:13:13 +1000] "GET /index.php/apps/files/api/v1/thumbnail/128/128/2016-11-14%2021-15-57%200293.png HTTP/1.1" 401 43
```
ok. so the reason why i'm getting locked out is because the testflight client keeps trying to access the nextcloud server using invalid authentication.

are you able to fix this problem in the next build?

cheers, wizdude.

**Comment by marinofaggiana** [comment]
@wizdude this is not a bug, read here : 

https://github.com/nextcloud/ios/issues/331

**Comment by wizdude** [comment]
i've done further testing. everything is fine until i try to view a file.

i've reset all settings, cleared the oc_bruteforce_attempts table and can log back into the app.
i can view all folders, bring up share information and so forth.

but as soon as i go to select any file you try to authenticate using the LDAP GUID and i'm immediately locked out.

this is what the apache log shows as soon as i select the Nextcloud.mp4 file as an example:

```
x.x.x.x - wiz [13/Aug/2017:11:09:25 +1000] "GET /index.php/apps/files/api/v1/thumbnail/128/128/Nextcloud.mp4 HTTP/1.1" 404 29
x.x.x.x - A27BE999-1061-4199-A994-B1CC52699999 [13/Aug/2017:11:09:25 +1000] "GET /remote.php/webdav/Nextcloud%20Manual.pdf HTTP/1.1" 401 234
```
the nextcloud log shows:

```
{"reqId":"SGai2\/JZ3\/ozouszarVb","remoteAddr":"x.x.x.x","app":"core","message":"Login failed: 'A27BE999-1061-4199-A994-B1CC52699999' (Remote IP: 'x.x.x.x')","level":2,"time":"2017-08-13T01:09:26+00:00","method":"GET","url":"\/remote.php\/webdav\/Nextcloud%20Manual.pdf","user":"--","version":"11.0.2.7"}
```
are you saying there is something in nextcloud which i am meant to fix?

everything works fine on the appstore version of the app.
