### ISSUE TITLE
Missing Files in Xcode

### ISSUE THREAD

**Issue by rebeccaformfx** [nextcloud/ios#348]
Hi there!  I just downloaded the source code from this Github but am seeing about 400 missing files in Xcode when I try and run the app.  Do you know where I can find these missing `Libraries external` dependencies?

**Comment by marinofaggiana** [comment]
Hi, inside the code exists all library, no missing dependencies

**Comment by rebeccaformfx** [comment]
OK.  I am still having trouble running this from XCode in Simulator, and Xcode is saying there are 3900 runtime errors.  Is there a quickstart guide or documentation on getting this running on xcode?

**Comment by rakekniven** [comment]
@rebeccaformfx Can we close issue? I suggest to use IRC or forum to work on such tasks.

**Comment by rebeccaformfx** [comment]
yes, it can be closed!  I solved the issue... beginner's issue with choosing the wrong target.  Thanks for being so responsive!
