### ISSUE TITLE
uninstalling app does not remove server and user credentials

### ISSUE THREAD

**Issue by wizdude** [nextcloud/ios#349]
uninstalling the app (holding down icon, wait for it to jiggle, click on X) still leaves data on the device.

if you re-install the testflight version and launch it, it pops up with the "Nextcloud would like to send you notifications" but you can see the login screen behind has the old servername and username.

it immediately starts pushing traffic to the nextcloud server with the previous set of credentials used - before you even acknowledge the notification popup.

performing a settings > advanced > exit appears to successfully erase all user data.

i found myself in a few situations where it wasn't possible to get to the "settings > advanced > exit" so it was challenging to erase all data. perhaps this "exit" option should exit in the iOS "settings >  nextcloud" so it is possible to clear all data when locked out of the application.

what would also be nice is to have an iOS "settings > nextcloud" option to "flush credentials" so that you can logout of the application in case the device is temporarily being used by someone else that you don't wish to have access to your nextcloud.

**Comment by sunjam** [comment]
I want to agree on it being helpful to flush credentials as a Nextcloud setting on the app.  Also, I've not found the login information remains once I delete and re-install the iOS app (current version) on latest version of iOS.

**Comment by rakekniven** [comment]
@sunjam Your first sentence is a different issue in my opinion.
Anyone else having the reported issue?
Tried it on three devices and no credentials remain.

**Comment by johkoenig** [comment]
"Reset app" button exists in v3.0.14. Also, deleting the app also deletes the credentials on current iOS versions.
