### ISSUE TITLE
Preview of non-UTF-8 text is not working

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#351]
- open a file with special characters, that is not UTF-8 encoded (like an ó)
- actual: the file is not properly rendered
- expected: proper rendering

**Comment by marinofaggiana** [comment]
- Use library : https://cgit.freedesktop.org/uchardet/uchardet/ the universal charset detection library by Mozilla
- Write a wrapper NCUchardet
- Include wrapper on Swift

**Comment by marinofaggiana** [comment]
Apply version 0.0.6 stable : https://github.com/BYVoid/uchardet/issues/36#issuecomment-323332542

**Comment by rakekniven** [comment]
Related: https://github.com/nextcloud/ios/issues/13

**Comment by rakekniven** [comment]
@marinofaggiana This is working AFAICS, or?

**Comment by marinofaggiana** [comment]
yes thanks
