### ISSUE TITLE
Error code 500 on creating folder with "é" character in name

### ISSUE THREAD

**Issue by Tsintaow** [nextcloud/ios#352]
If I create a folder via the Nextcloud iOS client that has the "é" character in the name the folder cannot be created. The app throw the following message in red : "erreur error code 500". Creating the same folder via the web interface works.
I can give more information if needed, what sort if issue model/template do you prefer ?

**Comment by marinofaggiana** [comment]
Hi @Tsintaow , strange, the 'é' is a character accepted ... sure ?

**Comment by Tsintaow** [comment]
Hi @marinofaggiana , here is an screenshot from the app when trying to create a folder named "Santé" : 

![fullsizeoutput_a04](https://user-images.githubusercontent.com/31100265/29789524-9a9d5d78-8c36-11e7-8027-56abe52b64ec.jpeg)

Does the Nextcloud admin log reports this at the same time : 
 
Fatal | webdav | Guzzle\Http\Exception\ClientErrorResponseException: Client error response [status code] 400 [reason phrase] Bad request [url] https://storage.gra3.cloud.ovh.net/v1/AUTH_face19c98e7749119ea04db930ce2f9a/william/Santé/

For info I'm using swift Openstack container for storage.

**Comment by marinofaggiana** [comment]
Sorry @Tsintaow I don't know Openstack, I don't know if exists an incompatibility or issue with WebDAV :/

**Comment by Tsintaow** [comment]
@marinofaggiana I changed my storage setup to use Nextcloud local storage and not an external Openstack container. Creating a folder named "Santé" using the iOS app works this way.

Seeing as creating that folder using the WebUI works with Openstack but not with the iOS app I would asume that it is the way the app passes the command through the Nextcloud instance that generates the problem. 

So it may be a problem with the iOS app or it may be a problem with the Nextcloud Openstack storage implementation. 

Just trying to help Nextcloud better, I'm not a developper so I can't help much more than this. 
Thanks for help.
