### ISSUE TITLE
Some auto uploaded videos is 0 kb 

### ISSUE THREAD

**Issue by spridarn** [nextcloud/ios#355]
Hi,

I use Nextcloud iOS app version 2.17.5.00005 and Nextcloud version 12.0.2 and have some problem with the auto upload function and video files. I upload all these files to a folder named MobilePhotos and sub directory for each months. 

For some weeks ago, not sure if it was with an iOS update, some auto uploaded movies is uploaded and removed from the upload queue but when I check Nextcloud at my computer or the web interface it is 0 kb in size and not working as this picture, http://imgur.com/8uyYg1t. Then when I manually try to upload the same movie file manually from the Nextcloud iOS app in the same folder it says that a file with the same name already exist and if I want to overwrite. I choose yes and then the file is uploaded and everything look as it should, http://imgur.com/IdODm4C

**Comment by roedie** [comment]
I can confirm I have exactly the same issue with the latest Nextcloud IOS app.

**Comment by marinofaggiana** [comment]
It's possible replicate the issue ?

**Comment by spridarn** [comment]
@marinofaggiana: It is not all videos who gets 0kb in size, it's random I think so far so hard to trigger the problem manually. What do you need next time it happens? Nextcloud server logs?

**Comment by marinofaggiana** [comment]
lock Activity on Nextcloud iOS (Advanced) :-)

**Comment by roedie** [comment]
I've sent my activity to ios[AT]nextcloud.com.

**Comment by marinofaggiana** [comment]
@roedie version Nextcloud iOS ?

**Comment by spridarn** [comment]
@marinofaggiana 
Here is my output with that specific filename my print screens in the first post shows
https://gist.github.com/spridarn/abaecb65e9f4bc8e8630e45e2900b66b

I am using iOS version 10.3.3

**Comment by roedie** [comment]
Nextcloud iOS: 12.17.5.00005
Nextcloud Server: 12.0.2
iOS: 10.3.3

**Comment by marinofaggiana** [comment]
Try with Beta 2.17.6 ;-) Fixed

**Comment by spridarn** [comment]
@marinofaggiana how to I get the beta app on an iPhone?

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/321

**Comment by spridarn** [comment]
@marinofaggiana when installing the app via TestFlight it says all app data will be removed, will all my settings be removed? May that also include remembered auto uploaded images?

**Comment by spridarn** [comment]
@marinofaggiana I think this issue is solved in the beta version, I have uploaded several videos last week and all videos are correct and working as it should

**Comment by marinofaggiana** [comment]
boys, I close this, if exists a new issue reopen
