### ISSUE TITLE
please make the instant upload folder configurable

### ISSUE THREAD

**Issue by mbiebl** [nextcloud/ios#358]
Version: 2.17.5

I'm using the auto/instant upload feature. It appears that the target folder is hardcoded to "Photos". 
I already have a "photos" folder and would like to change the instant upload folder to some different folder (windows file systems are not particularly happy if you have a photos and Photos folder)

**Comment by spridarn** [comment]
@mbiebl in previous versions you could change the folder for auto upload and I have made it before but in version 2.17.5 I can´t find that setting under Settings - Auto upload. Maybe something that was removed by mistake

**Comment by rakekniven** [comment]
Just do a manually upload and in that dialog you can change upload folder. 
Already discussed a few times here IIRC.

**Comment by mbiebl** [comment]
Hm, the functionality is there but I completely missed it.
It's not under Settings, where I would have expected it, but when using the file browser you can find in the context menu for folders the option to declare it as target for the instant upload feature.

So, I'm not sure what to do about this bug report.
Tbh I find it a bit unintuitive that there is this disconnect regarding settings and setting the default upload folder via the context menu. But if this intended then this bug report should be closed I guess.
