### ISSUE TITLE
unable to access the settings dialog if at least three external site links have been added

### ISSUE THREAD

**Issue by j-ed** [nextcloud/ios#360]
I installing the app and was instantly able to connect to my Nextcloud server. After selecting the More button in the lower right corner, the app menu opened and showed the following menu entries:

![nc-1](https://user-images.githubusercontent.com/2572764/29749332-30ead954-8b29-11e7-8324-c0be0fa2ff4e.png)

When I tried to scroll downwards to select the Settings entry, it was shown as long as I hold my finger on the screen. As soon as I remove my finger it automatically scrolled back to the beginning of the menu so that I wasn't able to select that menu entry.
For testing purposes I decided to remove the `External Link 3 (USV-Status)` from the list of menu entries by adjusting the app configuration using the Web GUI. Right after I had restarted the app the Settings menu entry was shown and selectable. 
**Conclusion:** The app can only handle a limited number of menu entries at the moment, because the automatic scroll-back function prevents a user from accessing/selecting other available entries.

***Environment:***
Nextcloud server : 12.0.1
iOS App: 2.17.5.00005
Phone type: iPhone 5s

**Comment by rakekniven** [comment]
Would you mind to attach screenshot?

**Comment by j-ed** [comment]
[x] done.

**Comment by marinofaggiana** [comment]
Thanks @j-ed try with next build

**Comment by rakekniven** [comment]
Hello @j-ed 
Please provide feedback. Thank you.

**Comment by j-ed** [comment]
I can confirm that the problem has been solved in v2.17.6.00014.
