### ISSUE TITLE
Video Upload Bug - iMovie

### ISSUE THREAD

**Issue by mind22** [nextcloud/ios#362]
If a video gets edited (or duplicated and then edited) with iMovie, the saved video with e.g. some effects is not uploaded and the following error is showed:

![17-08-31 11-54-45 1875](https://user-images.githubusercontent.com/26789520/29917836-7ad61f70-8e43-11e7-82ce-91f3f75b27c2.png)

nextcloud app 2.17.5

**Comment by marinofaggiana** [comment]
try with last version @mind22

**Comment by mind22** [comment]
Tried, but the error still exists. No error logs on the nextcloud server.

iPhone SE
nginx 1.12
nextcloud latest

**Comment by mind22** [comment]
Sry, i forgot to mention that i already have installed iOS 11 public beta. I don't know if this makes a big difference here...

**Comment by marinofaggiana** [comment]
I don't know ... can you allegate a video test ?

**Comment by Dodiwahyupurnomo** [comment]
i'm have same error in simulator IOS 10.3

**Comment by Dodiwahyupurnomo** [comment]
if size of file is small process upload normally. but if the file size is large like 120MB. app failed to upload file.

**Comment by bmf89** [comment]
can you tell us something more about the file size?

And Check the "client_max_body_size" (See http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size)

**Comment by mind22** [comment]
Okay, so now i've made a short video.

app version 2.17.8

The test video is a slow motion vid with about 10s.

After iMovie export i have uploaded it first directly by the sharing symbol in the photos app what surprisingly worked correctly. And then i tried the other way (also with auto upload), that means opening the nextcloud app and pressing the + icon. This led to the error shown above.

![screen](https://user-images.githubusercontent.com/26789520/30350086-a26ac9f6-9815-11e7-991c-646b60267717.gif)

PS: i know about the client_max_body_size and i can upload to 16GB ... so this shouldnt be the problem.

**Comment by Dodiwahyupurnomo** [comment]
on version 2.17.5 the upload process is running normally.

**Comment by mind22** [comment]
fixed in newer versions.
