### ISSUE TITLE
App show the login page all the time (v2.17.6)

### ISSUE THREAD

**Issue by tomaaa** [nextcloud/ios#365]
I can’t use anymore Nextcloud since the last update. Sometime, I can see for a short time my directories but cannot view files and pictures. The app show the login page all the time.

Users are in Active Directory.
IOS 10 and IOS 11 beta.

**Comment by marinofaggiana** [comment]
Hi @tomaaa without log is not simple for me detect the issue ... can reinstall ?

**Comment by DOWAIZA** [comment]
I have the same problem, on my Android smartphone too, so maybe a server site problem?

**Comment by DOWAIZA** [comment]
This Problem seems only to appear when i login with an LDAP (openLDAP) user. When i use the local admin user i stay logged in.

**Comment by jazzdd86** [comment]
Same for me:
iOS app won't work since the last update.
server: Nextcloud 12.0.2
server logs: 
```
Warning | core | Login failed: 'uuid' (Remote IP: '80.187.103.3') | 2017-09-04T18:47:23+0200
-- | -- | -- | --
```
I am using ldap and logging in with the username and not the uuid

**Comment by tri2000** [comment]
Same for me:
iOS app keeps prompting login when active directory login after attempting to view a file
server: Nextcloud 12.0.2
Log is the same as previous posting by jazz...
