### ISSUE TITLE
Disable IOS client side app encryption

### ISSUE THREAD

**Issue by prilly** [nextcloud/ios#37]
i see there are some new encryption stuff in the IOS nextcloud app.

i cant find any way to go around that, i dont understand that anyone want this, sharing phone encrypted files to you computer results in non readable data, so nextcloud is reduced to a online vault.

So the problem is that current IOS app has NO possibility to deactivate this encryption.

**Comment by prilly** [comment]
Its not possible to deactivate folder encryption on the default "photos" folder used for autoupload of images/video

**Comment by MorrisJobke** [comment]
cc @marinofaggiana 

@prilly You maybe also want to check out #51  ;)

**Comment by jancborchardt** [comment]
Closing in favor of #51 and #65 because we have more info in there. :)

**Comment by prilly** [comment]
Finaly it seems that the guys behind the iOS app is taking to senses. this client side encryption is cousing more problems than good, and it also crashens with the nextcloud vision. 

If a function like this is still wanted, it should have been optional with opt in as default.

**Comment by marinofaggiana** [comment]
It' already optional in as default.

**Comment by jancborchardt** [comment]
@prilly a little more friendliness would be nice if you are asking people for favors, who release all the software as open source. ;) The work @marinofaggiana has done on the iOS app is pretty amazing, and he deserves a lot of praise!

**Comment by prilly** [comment]
@jancborchardt A little more friendlyness? are you joking with me?.. If nextcloud is going to have a userbase of this software that uses it for CRITICAL stuff this kind of cowboy coding that clearly violates the nextcloud idea cant be accepted, the result of this code is that all of our IOS devices that relayed on this app has been using alternativ solutions for 4-5 moths, when this clientside encryotion was introduced it BROKE the app, and it has been BROKE for almost 5 months.. do you know how much time i have used to find alternative solutions for our ios userbase??  and you ask me to be friendly? daaam you have i reached the code of this crap i would have told him exactly what i mean.

If the coder cant stick to the idea of nextcloud and contribute to a clear and stable developing way that promote stability i think its better he finds something else to do. if i cant trust the app, its better the app is removed.

**Comment by MorrisJobke** [comment]
I can fully understand you, but also have a look at the other side: we spend the last months hard working on making the iOS side a lot more stable. And shouting on people doesn't solve problems at all.

**Comment by marinofaggiana** [comment]
This is the statist of today with 98.8% crash free Users, 29 crash today about thousands of users is not a bad result. 

Several crash are for concurrency of CoreData on several thread but now I migrate CoreData on Realm DB project opensorce, the target is over 99.5% creash free users, be patient :-)

Thanks.

<img width="981" alt="schermata 2017-05-08 alle 16 38 18" src="https://cloud.githubusercontent.com/assets/8616947/25809378/0a2290f0-340d-11e7-943a-1caff418906a.png">
