### ISSUE TITLE
Wish list: create a camera qr code to grant access

### ISSUE THREAD

**Issue by Spacial** [nextcloud/ios#374]
The main idea is using a qrcode on server (on sync clients), so you dont need to type the app specific password, just point and everything is configured (server, user and otp).

Could even (in qr code) some hash of the server's certificate to guarantee no MITM attack.

**Comment by tflidd** [comment]
ref: https://github.com/nextcloud/server/issues/5659

**Comment by ChristophWurst** [comment]
Server ticket: https://github.com/nextcloud/server/issues/429
Server PR: https://github.com/nextcloud/server/issues/429
Android implementation: https://github.com/nextcloud/android/pull/3383

@marinofaggiana any status on this? Is it feasible to integrate a qr code reader into the login screen?

**Comment by marinofaggiana** [comment]
@ChristophWurst it is in TODO ... :fearful:

**Comment by marinofaggiana** [comment]
Available on TestFlight 2.23.2 (Build 3)

![19-03-05 10-25-27 2667](https://user-images.githubusercontent.com/8616947/53797372-54807780-3f36-11e9-9276-501ba0faedbc.png)

![2019-03-05 11-04-24-1](https://user-images.githubusercontent.com/8616947/53797496-96a9b900-3f36-11e9-99dd-cd2022a64552.png)

**Comment by ChristophWurst** [comment]
Awesome!

**Comment by AndrewwHummer** [comment]
It works, with the example provided in the "server Issue #429" ... so now how do I enable it for my own server 😆

**Comment by ChristophWurst** [comment]
Thanks for testing @AndrewwHummer! That's great to hear. You'll have to be patient a bit as we're stabilizing Nextcloud 16 at the moment. It will take a few more weeks before the final release, but you can also check out a beta release once ready: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by AndrewwHummer** [comment]
Thanks for the information. Will try the beta as soon its ready! :)

**Comment by tobiasKaminsky** [comment]
works for me also, but you QR needs to include http/https protocol, otherwise it will fail.

**Comment by marinofaggiana** [comment]
Should be obligatory the protocol in qrcode !? Otherwise I don't know if is http or https

**Comment by tobiasKaminsky** [comment]
I just created a qrcode on my own and on android we always first try https if no protocol is specified. It https is not working, we test http and show a warning that it is unsecure.

**Comment by tobiasKaminsky** [comment]
Background: It can happen that people generate the qr code on their own, for e.g. easy roll out of clients, etc. and therefore it should be as error prone as possible.

**Comment by ChristophWurst** [comment]
is there anything we have to change on the server?

**Comment by marinofaggiana** [comment]
Ok, I add this strange control, but for me the qrcode should be have the protocol.

**Comment by ChristophWurst** [comment]
If so, please open a ticket in the server repo and let me know about the exact format of the URL. I'm also unsure if we should or have to URL encode any parameter and how that is handled on the mobile apps.

**Comment by tobiasKaminsky** [comment]
> is there anything we have to change on the server?

```nc://login/user:tobi&password:XJdpw-R9kF3-Liy5C-MjNEZ-aTjSN&server:http://localhost/nc```

looks fine. 
However I have not tested it with withespaces/@ in userId, but I'll do now.

**Comment by ChristophWurst** [comment]
Okay, thanks for testing. Just let me know if we have to fix anything on the server-side :)

**Comment by marinofaggiana** [comment]
I have add the check whether server: contain protocol. If not add https:// by default.
