### ISSUE TITLE
saving problem with templates in encryption modus

### ISSUE THREAD

**Issue by mind22** [nextcloud/ios#376]
I have to double tap the saving button for e.g. a template (note etc.) in the encryption modus. So the template gets uploaded two times before the window closes. If i press the cancel button after the first tap on the saving button, i see one upload. But to disappear in a "normal way" i have to press two times.

iOS 2.17.8

**Comment by marinofaggiana** [comment]
the encryption module now is removed for the next protocol 2e2.
