### ISSUE TITLE
iOS 11 Video Upload Error: File not present, please reload.

### ISSUE THREAD

**Issue by candrist** [nextcloud/ios#377]
iPhone 6s iOS 11
iOS 2.17.8
FreeBSD 11
Nextcloud 12.0.2
Apache 2.4
PHP 7.0

Pictures are fine, only issue with videos over 10mb.

![17-09-19 18-17-17 2072](https://user-images.githubusercontent.com/11068001/30621483-9906e43c-9d68-11e7-8a64-c0995ab550e0.png)

**Comment by marinofaggiana** [comment]
Hi @candrist  verify the server configuration

**Comment by candrist** [comment]
do not exist issue for video > 10 MB or 100 MB, the error is write : file not present.

Is this the correct error, or how can I fix it?

**Comment by marinofaggiana** [comment]
@candrist have you resolved ?

**Comment by candrist** [comment]
I upgraded to the iPhone 8 and haven’t had the issue since. May have been an issue that I just needed to wipe my iPhone 6S and start over and it would have worked.
