### ISSUE TITLE
Can't login, get bad gateway (502)

### ISSUE THREAD

**Issue by socketwiz** [nextcloud/ios#378]
I've installed nextcloud v12.0.2 here: https://nextcloud.socketwiz.com and it seems to work fine.  I can login, etc...  I can also login with the desktop webdav app and that seems to work fine, it synced my files from the site to my local drive.  However when I try to login with the iOS app, I keep getting:

Error, It is not possible to connect to the server at this time.  Request failed: bad gateway (502)

If I try to request the webdav url with curl, it seems to work as expected:

`$ curl https://nextcloud.socketwiz.com/remote.php/webdav/`

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured</s:message>
</d:error>
```

Any idea why it doesn't seem to want to work in iOS?  I enter in `https://nextcloud.socketwiz.com/remote.php/webdav/` as the url with a valid username and password.

**Comment by rakekniven** [comment]
Have you tried to strip URL to `https://nextcloud.socketwiz.com/`?
Same behaviour then?

**Comment by socketwiz** [comment]
Thank you @rakekniven that seems to work.  My apologies, it was not obvious what the URL should be.
