### ISSUE TITLE
2.17.8 Crashed after search result is being tap (happens only to shared folders)

### ISSUE THREAD

**Issue by esolix** [nextcloud/ios#379]
Nextcloud Installed: 12.0.2
iOS Version tested : Both 10 (Last branch) and 11
Was able to reproduce it all more than 5 devices

1. Run a search for any term
2. If the result consists "Shared" folder by other user, tapping those shared folders would crash Nextcloud App (Shared files will work - only folder will crashed the ios app)
3. Owned files/folder will operate as it should and did not crash the app
4. No error indicator on server end (so i believe this is client issues)

Previous version of Nextcloud iOS works but not the 2.17.8

We also tested it on 3 different installation of Nextcloud (12.0.2) 

Thanks!

**Comment by rakekniven** [comment]
Cannot confirm. Same setup as yours. 
What kind of files crashes the app?
Tried pdf, mp3 and txt. Works well

**Comment by esolix** [comment]
Thanks for checking, files will not crash the app, only shared folder does. Search for a term, and tap on one of the shared folder on search result. Multiple ios devices tested and with 3different server environment (apache as web server, nginx as webserver and litespeed as webserver) all produces the same crash. No issue on Android

**Comment by rakekniven** [comment]
Did that already. Checked it once more and on my iPhone 5s  (iOS 10.3.3) the app is not crashing.

**Comment by esolix** [comment]
Thanks, I might need to look further, let me see if i can grab a crash log from the devices, on the server end there arent any error logged. Thanks, will update this as i find out more

PS. previous version did not crash

**Comment by rakekniven** [comment]
Hello @marinofaggiana Is Testflight helpful to solve this issue?

**Comment by jonathanpantall** [comment]
Hey all, I can confirm this bug. We're running Nextcloud v12.0.0. Thanks!

**Comment by marinofaggiana** [comment]
I think this is fixed ... who can tested ? @jonathanpantall @esolix ?

**Comment by marinofaggiana** [comment]
Confirm, fixed for the next 2.19.0

**Comment by rakekniven** [comment]
v2.19.0 is finalized and should be available soon in your local App Store.
