### ISSUE TITLE
question: Deleting local copy images without deleting thumbnails from cache 

### ISSUE THREAD

**Issue by ruvashev** [nextcloud/ios#38]
Hi!

I have a question.
When i open picture/audiofile/anything in nextcloud ios app it is downloaded and placed in app's cache. Thumbnails are in cache too - which is nice!
Now question... Is there a way to clear cache of local images/audio files keeping thumbnails? I.e. i would like to delete downloaded "local" copies of the files without regenerating thumbnails for 5k+ image files.

Thanks a lot for any help!

**Comment by marinofaggiana** [comment]
Thanks for you suggestion @ruvashev !

**Comment by ruvashev** [comment]
thanks a lot for quick reply Marino!

/Ruslan.

**Comment by marinofaggiana** [comment]
done.
