### ISSUE TITLE
No way to switch between grid and list view

### ISSUE THREAD

**Issue by danaivehr** [nextcloud/ios#380]
iOS app has a Grid view feature (aka Album view), which i found availible only from single photo view.

I think it's not a very natural way to get there:
* Go to folder with photos
* Touch one photo
* Wait while photo will be **downloaded** and opened in **full** resolution
* Touch "grid" icon in the left bottom corner
* Get to grid view with photo previews

I'd like to propose a more natural way:
* Go to folder with photos
* Touch menu icon in the right top corner
* Get to grid view with photo previews

Proposed way is more obvious and definately faster in case of highres photos 10+ MB

Please find an explaining attachment:

![image](https://user-images.githubusercontent.com/1226019/30773627-e5bc72a8-a07c-11e7-996e-81387200d452.png)

**Comment by marinofaggiana** [comment]
For the last version in beta the grip is removed.

**Comment by danaivehr** [comment]
Could you point to a discussion what are the reasons? Is there some alternative feature coming, or just this feature causes problems?

**Comment by marinofaggiana** [comment]
@danaivehr too many problem with iPhone X, required a new design :-)

**Comment by rubrik** [comment]
This makes it very difficult to convince an iPhone user that we should switch to Nextcloud. How should they look at their photos on their phoje? The full screen photos are the full-size originals and so take a long time to show, and the gallery overview only shows recent photos as far as I can tell. 😕

**Comment by allendustin** [comment]
The thumbnails using the iOS app under the standard view render it unusable.  Being able to switch from list view to grid view may address that issue.  I think serious consideration needs to be given to bringing the ability to switch between list view and grid view back.  My two cents.

**Comment by marinofaggiana** [comment]
> Being able to switch from list view to grid view may address that issue

It's in TODO, but for images/videos exists the "Photos" view .. no ?

**Comment by allendustin** [comment]
![image](https://user-images.githubusercontent.com/40801564/42231958-06c13638-7ebb-11e8-82cc-a33f2a1dc892.jpeg)

**Comment by allendustin** [comment]
I've blurred the images, but you can see that they are far too small in this list view to be able to see them enough to find what you're looking for.

**Comment by manolo4711** [comment]
Any Updates here? Grid view in nextcloud iOS App is for one of the most important enhancements for me. I can't fully understand with it's not possible or need a redesign. Grid view is already possible/active for the view "deleted files".

![image](https://user-images.githubusercontent.com/23011984/82762291-62067380-9e00-11ea-8437-4cf00310e3d0.png)

![image](https://user-images.githubusercontent.com/23011984/82762307-7cd8e800-9e00-11ea-9a44-0953202d5704.png)

**Comment by thgoebel** [comment]
Is this still an issue with the latest version  @marinofaggiana - it seems like grid view is available in all screens?

**Comment by marinofaggiana** [comment]
yes, we can close it, thanks @thgoebel
