### ISSUE TITLE
Use appropriate preview instead of full resolution in photo view

### ISSUE THREAD

**Issue by danaivehr** [nextcloud/ios#381]
It would be great to make photo browsing user experience better:

When i touch a photo in list, download is started and after completion full resolution photo is opened. One have to wait until download is finished (very noticable on 10+ MB photos), while he even doesn't need this download

Since Nextcloud has preview strored, it's better to use one with appropriate size (like in grid-album view), and download full resolution by request (i find it more  suitable) with some button (let's say "HD" button).

I think the first user reason to open a photo is to look on it, and *not* do downloud full resolution photo.

I also saw another request on this topic (#258) but i think it is quite different because suppose to use blured stretched icon instead of server preview with appropriate size and to load full resolution anyway.

May be some combination of #258 and this request would be good too.

Thank you for great app anyway!

**Comment by LeKoArts** [comment]
Any updates on that? @rakekniven
