### ISSUE TITLE
File Provider Crashes

### ISSUE THREAD

**Issue by togglecode** [nextcloud/ios#382]
- Create a new doc file with Microsoft Office iOS
- Save the file by clicking on "More"
- If the Nextcloud Document Provider is selected, the App will crash and not open

Nextcloud iOS 2.18.0 (Testflight)
Server 12

**Comment by togglecode** [comment]
This happens on iOs 10 btw

**Comment by marinofaggiana** [comment]
Yes Thanks , fix next beta

**Comment by marinofaggiana** [comment]
please try with build 9 thx

**Comment by jclgs** [comment]
Crash on my side with ios 10.

**Comment by marinofaggiana** [comment]
@jclgs I have tested with iOS 10 and Word, no crash

**Comment by togglecode** [comment]
I can confirm No crash build 00010 on my side

**Comment by marinofaggiana** [comment]
Thanks @togglecode , @jclgs ?

**Comment by jclgs** [comment]
Word, Escel ... Document Provider crash on both O365 app. We are seeing the Blue square with "Loading" and after that, nothing. O365 return me to Open Document window and nothing else happened

**Comment by marinofaggiana** [comment]
Try with reinstall Nextcloud

**Comment by jclgs** [comment]
Same result. it crashed

**Comment by jclgs** [comment]
My IOS is 10.3.2.

**Comment by marinofaggiana** [comment]
but with older version ? (not beta)

**Comment by jclgs** [comment]
The last stable version that you release few days or week ago, everything was fine.

**Comment by marinofaggiana** [comment]
No No AppStore stable version

**Comment by jclgs** [comment]
yes. I'm talking about the last AppStore version. it was running fine.

**Comment by marinofaggiana** [comment]
please try with version on AppStore

**Comment by marinofaggiana** [comment]
then update beta version testflight

**Comment by jclgs** [comment]
Ok. From AppStore version. it works fine. Testing now with the update beta version

**Comment by jclgs** [comment]
After the update to the beta version, it crashed.

**Comment by marinofaggiana** [comment]
Can u make a user for me for test on your server ?

**Comment by jclgs** [comment]
I can check to create you a user.
Is there a way for me to provide you securely those informations. I don't want that everybody start playing with that account. :)

**Comment by marinofaggiana** [comment]
oh! yes send me the user test on ios @ nextcloud . com

**Comment by jclgs** [comment]
Tested with an iPhone SE and it works. Maybe my iPhone 6S is having something.
