### ISSUE TITLE
Encryption - Padding

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#383]
@mario have you time for this issue ?

https://github.com/nextcloud/ios/blob/18cbc9fdfb0dddbb84756c259090b6bca9c3a4bf/iOSClient/Security/NCClientEncryption.m#L256

**Comment by mario** [comment]
What is the issue exactly? If you tell me what the problem is, I might be able to solve it :P

**Comment by marinofaggiana** [comment]
yes the issue is the compatibility from Android and Apple for enc/decr :  AES/GCM/NoPadding

**Comment by mario** [comment]
@marinofaggiana I've submitted a PR that should hopefully fix it. Please try it out.

**Comment by marinofaggiana** [comment]
You Rock \o/

**Comment by mario** [comment]
@marinofaggiana so it works? :)

cc @tobiasKaminsky @rullzer @karlitschek and whoever else is involved in encryption...

**Comment by marinofaggiana** [comment]
@tobiasKaminsky try decrypt : 

key: bGzWfQBj2lE4ZnysDWwsIg==
iv: rTBECYNekKF+a1HR7z32/Q==

https://cloud.twsweb.it/index.php/s/2W46JnLgQlHOprt

**Comment by marinofaggiana** [comment]
@mario where you are found the CommonCryptorSPI.h ??

Dear developer,

We have discovered one or more issues with your recent delivery for "Nextcloud". To process your delivery, the following issues must be corrected:

Non-public API usage:

The app references non-public symbols in Nextcloud: _CCCryptorGCM
The app references non-public symbols in PlugIns/Picker.appex/Picker: _CCCryptorGCM
The app references non-public symbols in PlugIns/Share.appex/Share: _CCCryptorGCM
The app references non-public symbols in PlugIns/PickerFileProvider.appex/PickerFileProvider: _CCCryptorGCM
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's nine-digit Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information page.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team

**Comment by mario** [comment]
It's part of an Apple internal API :P Too bad it can't pass xD

**Comment by mario** [comment]
@marinofaggiana if you can confirm encryption/decryption works across platforms this way, we can find a different way to implement it - but I'd like to know it works.

**Comment by marinofaggiana** [comment]
For now NO ... this API is private Apple ... tomorrow I try with a user library but now I have a little time for try ... iOS 11 and iPhoneX is too important, if you want : https://github.com/indisoluble/AesGcm try

**Comment by marinofaggiana** [comment]
@mario , @tobiasKaminsky who has decided for AES/GMC ? on iOS the is a big problem, please consider changing

**Comment by tobiasKaminsky** [comment]
@LukasReschke decided this as he did the initial draft and has the most knowledge about security.

**Comment by marinofaggiana** [comment]
ok @LukasReschke read here :)

**Comment by LukasReschke** [comment]
@marinofaggiana Can't you just use OpenSSL directly by embedding the C library?

**Comment by marinofaggiana** [comment]
OpenSSL required time for develop a wrapper and I have infinite issues and pending development ... and I don't know if this is a good choice for big file,  ... if not exists other possibility  ... but this 2e2 system take too time 🙊 (PHP and Java excluded)

**Comment by mario** [comment]
Can't https://github.com/x2on/OpenSSL-for-iPhone be used?

**Comment by marinofaggiana** [comment]
> Can't https://github.com/x2on/OpenSSL-for-iPhone be used?

@mario that is the OpenSSL library build .. it is only the script for compile lib static framework Xcode for create libcrypto.a

https://github.com/nextcloud/ios/tree/develop/Libraries%20external/openssl

**Comment by marinofaggiana** [comment]
I already use OpenSSL

**Comment by marinofaggiana** [comment]
@LukasReschke @tobiasKaminsky in this days I have write a wrapper OpenSSL and it seems to work ... @tobiasKaminsky can you send me another file encrypted of 3 4 MB or more for test (with key and iv) ? thanks

**Comment by tobiasKaminsky** [comment]
Why do you need such a big file? I have currently limited bandwidth, so I cannot do this within the next days.
Do I understand you correct that you can successfully decrypt a file which android encrypted? That would be great.
If so, can you then encrpyt a (small) file so that I can try to decrypt it with android?

**Comment by marinofaggiana** [comment]
ok soon a test

**Comment by marinofaggiana** [comment]
keyData = "bGzWfQBj2lE4ZnysDWwsIg=="
initVectorData = "rTBECYNekKF+a1HR7z32/Q=="

https://cloud.twsweb.it/index.php/s/41JClu7xGgXv1dH

**Comment by tobiasKaminsky** [comment]
@marinofaggiana 🎉 🎉 🎉 🎉 🎉 🎉 
I successfully decrypted your image, nice waterfall ;-)

**Comment by mario** [comment]
Congrats folks!

**Comment by marinofaggiana** [comment]
@tobiasKaminsky now the tag auth : length ? can you create a new encrypt with key,iv and tag ?

Tanks a lot.

**Comment by tobiasKaminsky** [comment]
https://cloud.nextcloud.com/s/NOuWoElFtJC6kVr

key: WANM0gRv+DhaexIsI0T3Lg==
iv: gKm3n+mJzeY26q4OfuZEqg==
authTag: PboI9tqHHX3QeAA22PIu4w==

AuthTag is computed in this way:
https://github.com/nextcloud/android/blob/71ed02deb709a60cdde5ed5485fe08167fcff19e/src/main/java/com/owncloud/android/utils/EncryptionUtils.java#L306-L307

In java the authtag is appended to the encrypted data.

**Comment by marinofaggiana** [comment]
@tobiasKaminsky : 

the Auth tag is an OpenSSL internal : 

https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption see EVP_CIPHER_CTX_ctrl

@LukasReschke is this ??

**Comment by rullzer** [comment]
Yes it is the same.

Do not that the Java implenetation add the Tag to the end of the cipher text.
So you should not read the last 16 bytes when decrypting.

**Comment by marinofaggiana** [comment]
Thanks @rullzer but a question, the e2e for desktop is ready ?

**Comment by rullzer** [comment]
It is being worked on

**Comment by marinofaggiana** [comment]
Who wrote (you) ? and where for make test together ?
