### ISSUE TITLE
Testflight 2.18.0 B0006 crashes on iOS11

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#384]
Hello,

just updated my iPad Pro to iOS11 and installed latest Testflight version.

App is not starting.
Splash screen is showing for just a second and then app is closing. No popups or anything else.

Please have a look

**Comment by marinofaggiana** [comment]
@rakekniven can you add more info, is update from Build 5 ? iOS ?

**Comment by rakekniven** [comment]
@marinofaggiana It is all there. Please see title of issue.

**Comment by marinofaggiana** [comment]
yes but before was build 5 ?

**Comment by rakekniven** [comment]
No, before it was Build 4

**Comment by marinofaggiana** [comment]
... DB is changed for new option ... try with reinstall from TestFlight sorry :-(

**Comment by rakekniven** [comment]
Reinstalled it and App is working again.

Will this happen to the user as well if App is final v2.18.0?

**Comment by marinofaggiana** [comment]
NO, never, when I close the beta I check the DB compatibility for old version.
