### ISSUE TITLE
2FA enable crashes app

### ISSUE THREAD

**Issue by wallenium** [nextcloud/ios#386]
I disabled 2FA because of The missing „Approve for 30 days“ Option i requested in The Core section.

To increase security, i enabled it again. Now, The latest test flight 2.18.0/0006 crashes. I would suggest showing a warning instead of crashing. 

Login Data is Stored, there is no simple possibility to change it After enabling 2FA in The App. Delete App is not a neat Solution ;)

**Comment by marinofaggiana** [comment]
I think this is not a 2FA issue

**Comment by wallenium** [comment]
when enabling the 2FA, it is not working. Instead the "enter Login data" Screen Pops up short, then the app Closes.I would suggest that the System tries to ask for the Code, but that does not work.
I used my normal Login data, as it is stored in the Settings. No app Password or similar things. It happens, when you enable 2FA on an existing System, and try to open the app...

**Comment by marinofaggiana** [comment]
I check the crash 2.18.0/0006 for found your issue (if exists). Are you "janstockem" ?

**Comment by marinofaggiana** [comment]
Try with the next build (7)

**Comment by wallenium** [comment]
Ok. I will.

Thanks a lot.

**Comment by marinofaggiana** [comment]
@wallenium try with (8) thanks

**Comment by wallenium** [comment]
Tested, working fine
