### ISSUE TITLE
New branching Model (git-flow)

### ISSUE THREAD

**Issue by anagromataf** [nextcloud/ios#39]
Maybe I have overseen it, but currently there is no separation of the production and the development branch.

I would suggest to use a branching modle like [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) to separate the production release from the development branch. This make it easier to publish new releases only containing fixes (hotfoots on master) and continue pushing new features forward.

I used it in a big project before and it worked quite well to manage developing new feature and fixing existing bugs.

**Comment by marinofaggiana** [comment]
Hi @anagromataf  thanks for your consideration, absolutely Yes, from new version i create Develop version for production.

Thanks

**Comment by jlfranklin** [comment]
Git-flow works great on large projects with lots of developers.  It also works great on personal projects!

**Comment by enoch85** [comment]
This is done.
