### ISSUE TITLE
Development question upload file

### ISSUE THREAD

**Issue by alexknobbe** [nextcloud/ios#393]
Hello all.
Can someone tell me where to find the name nextcloud in the code that is used within ios when you want to upload a file to nextcloud within nextcloud.

So when you click on upload file you get the option to select source. There you see all apps including nextcloud and I want to change that name.

**Comment by marinofaggiana** [comment]
hi @alexknobbe : Share extension , Picker extension and PikerFileProvider extension

**Comment by alexknobbe** [comment]
Thank you @marinofaggiana

**Comment by alexknobbe** [comment]
Sorry @marinofaggiana, i cant find nextcloud in the files that you pointed me to.
