### ISSUE TITLE
File Provider Beta 2.18.0 (12) Saving File O365 not working and still not downloading file each time.

### ISSUE THREAD

**Issue by jclgs** [nextcloud/ios#397]
Hi.

I'm testing the beta 2.18.0 (12) for the problem with O365 and Nextcloud. The beta (12) include fix for the issue with O365 and the Cache of Nextcloud app.

With that beta version (12), saving a modified files no longer work on the NextCloud/O365 combo and NextCloud/O365 is still taking the file in cache and not downloading it each time like it should be.

Here is the link to the post on the Help Section.
https://help.nextcloud.com/t/ios-stop-using-cache/21705

**Comment by marinofaggiana** [comment]
Try next build, thx

**Comment by jclgs** [comment]
Yes I know. Will test it and let you know. Thanks

**Comment by jclgs** [comment]
I will test the next build when it will be available,

Question: I understand that we need to go back into the NextCloud app to trigger the upload, but is this something that will be solved in future that if a file is modified, the trigger will be lauched automatically without the need to go back into the NextCloud app?

That way, we modify a file into O365 and do not need to worry about the NextCloud app. Don't know if possible, but an option in the NextCloud app like "Auto Upload New/Modified File": ON/OFF with a setting "Trigger Auto Upload of New/Modify file every":  1m, 2m 5m, 10m, 20m ....

Just a suggestion. It's probably more complicated than what I think. :)

**Comment by marinofaggiana** [comment]
This implementation required a new driver low-level for the use with "ios extension", for now is not possible, but in future is a ToDo list as the compatibility with thew new File App of iOS 11.

**Comment by jclgs** [comment]
I just tested. Saving file works now.

But O365 and Document Provider still continue to use the file in the cache and not the updated version on the CIFS server. I added a value in my Excel File from my laptop directly on the CIFS server and the NextCloud IOS app still use the cache version because the value added in the excel file with my laptop is not the in file opened in the IPhone.

**Comment by marinofaggiana** [comment]
oh! true, lost old path ...

**Comment by jclgs** [comment]
Good job. Working good on my side.

I notice something different but maybe this is Microsoft who change something. When creating a new document in O365, we no longer have the choice to select More ... Location and after NextCloud. The only way to get a new file save into the NextCloud server is in O365, select "Send a copy" and after we can select NextCloud.

But this is not a big deal. I do not see people creating a new entire Excel document with their iPhone or iPad.

**Comment by marinofaggiana** [comment]
This is a new of iOS 11, required new manage API, .... next version ;) I close this issue.
