### ISSUE TITLE
Shows wrong cache usage (Settings/Advanced/Clear Cache)

### ISSUE THREAD

**Issue by doomi** [nextcloud/ios#398]
It shows a wrong cache usage in
Settings/Advanced/Clear Cache:

used 279.01 GB

I have an 128GB iPhone 6s.
Nextcloud app is using 62MB as of iOS settings/Storage usage.

![img_8831](https://user-images.githubusercontent.com/2828694/31822949-12ab7064-b5dd-11e7-8224-ff655c5b00b6.PNG)

**Comment by rakekniven** [comment]
@doomi Which app version are you using?

**Comment by doomi** [comment]
I always use the current version. already updated once or twice since filing the report.
right now it's Nextcloud for iOS 2.18.2.00001

currently the cache usage shows 279.94GB :)

**Comment by paulstewartis** [comment]
I have the same problem, although not as dramatic. iOS says the app is using ~400MB and the app says it is using ~3GB. Clearing the cache does not help. I even logged out of my accounts and deleted the app.

**Comment by doomi** [comment]
It’s getting worse
![ebd66c30-11eb-46e2-9a77-befc9f89c5ea](https://user-images.githubusercontent.com/2828694/34753731-8a4ce218-f5f4-11e7-877c-a14f6b258abc.png)

**Comment by doomi** [comment]
There seems to be two issues: cache size and iOS storage usage. I finally could clear the cache and for now it looks ok (10MB). I will report on that in the future.

I think I found the cause of the second issue. I configured Google drive as external storage and there‘s about 270GB used. my Nextcloud usage is about 30GB. So together it‘s those 300GB iOS is reporting.

**Comment by doomi** [comment]
I disabled the external storage plugin on the server and reinstalled nextcloud on my iPhone, now it‘s showing the correct usage again!
I had to delete and reinstall the iPhone app. clearing cache and iPhone reboot didnot work.

Btw: my iPhone backup in iTunes was also 300gb in size! I will see if it‘s smaller now...

**Comment by doomi** [comment]
for a year now I didn't find out why my iPhone backup with iTunes was about 300GB in size, but I only have an iPhone with 128GB! it took about 2 days to complete!
now that I disabled external storage it not only shows the correct size in the iPhone settings, but the backup is now the correct size too!

so the iPhone backup downloads and includes the external storage!!!
so guys, this is a big issue, not only a wrong usage display problem!

**Comment by rakekniven** [comment]
@doomi Please open seperate issue regarding your last post.

**Comment by doomi** [comment]
@rakekniven ok, I will open a new issue. But I‘m pretty sure if this bug is fixed (by excluding external storage) it will also fix the backup issue.

**Comment by rakekniven** [comment]
@doomi Thanks for filing new issue. So we close this?

**Comment by doomi** [comment]
@rakekniven No!! (Why?!)

**Comment by rakekniven** [comment]
You are right, misread one of your comments.

**Comment by marinofaggiana** [comment]
I Remove it, the calculate is too imprecise

**Comment by rakekniven** [comment]
Just for the records:
https://github.com/nextcloud/ios/commit/a97768770972935497f355f89b59b273f24b137b

**Comment by doomi** [comment]
Removing the display of the size does not resolve the problem of using the wrong cache directories.
Is there a reason to not use the official cache directory defined by Apple standards? Then iOS could automatically delete the cache if the device gets full and iTunes would not backup the cache, neither.
