### ISSUE TITLE
Default upload folder should be the last used, not 'Files'

### ISSUE THREAD

**Issue by doomi** [nextcloud/ios#399]
When manually uploading a file it always defaults to the folder 'Files'.
Which in my case doesn't even exist.

For best usability it should preserve the last selected folder (of the most recent upload).
Or make it configurable in the settings.

**Comment by marinofaggiana** [comment]
The form manual upload get the current folder

**Comment by doomi** [comment]
Sorry, I did't write this clear enough.
In my workflow, a manual upload is from another app.
So when sending a file to the nextcloud app (file provider?).
It defaults to 'Folder' in both variants ('Import with nextcloud' and 'nextcloud').

![img_8834](https://user-images.githubusercontent.com/2828694/31829104-e7fe84fc-b5ee-11e7-987d-58436b60d7f9.PNG)
![img_8832](https://user-images.githubusercontent.com/2828694/31828965-72fe6398-b5ee-11e7-8f0f-5fcc3fb79d60.PNG)
![img_8833](https://user-images.githubusercontent.com/2828694/31828966-7340bd24-b5ee-11e7-9b2e-9b0edd67c6bc.PNG)

**Comment by doomi** [comment]
an option in setting would be nice to configure either ‚last used folder‘ or a specific default folder.
but a default folder which doesn’t even exist is just wrong...

**Comment by doomi** [comment]
The issue still exists.
In the sharing screen it‘s called now ‚copy to nextcloud‘ and still defaults to the non existing folder ‚files‘.
