### ISSUE TITLE
Extracting Frameworks/Libraries

### ISSUE THREAD

**Issue by anagromataf** [nextcloud/ios#40]
I saw, that this has already been started. I would suggest to extract frameworks from the main iOS app project into dependencies managed by cocoa pods or carthage (personally I prefer carthage, but this is just my personal preference).

Is there a concrete plan how to handle the implementation of the business logic of the app (accessing the server, syncing files, etc.)? I would found it nice, if this can be moved into a framework, which can be used in other apps (not only the library to access the server API, but also the management of the local state).

**Comment by marinofaggiana** [comment]
@anagromataf for now we are busy for develop a new version with new API, after we can talk about it, whats do you think ?

**Comment by anagromataf** [comment]
@marinofaggiana Sure, This is not a top priority. Thinks need to be planned.
