### ISSUE TITLE
Feature request: UI improvement - file deletion

### ISSUE THREAD

**Issue by tessus** [nextcloud/ios#400]
The fact that 'delete' just deletes the file from the server is very confusing. I also use the Android app a lot, which asks, if you wanted to delete the file locally or on the server.

I'm pretty sure, you don't want to introduce such a dialog, but is there any chance you could add another icon next to the trash bin to allow the deletion of the local file? e.g. a trash bin with an L overlayed.

**Comment by doomi** [comment]
fyi: there is more>remove from cache

**Comment by tessus** [comment]
@doomi I know.

The point is that the behaviour is different to the Android app. So when using this app, you have to remember that in this case `delete` will remove the file from the server.

I'm just saying that if you have a nextcloud client on different client OSes, the general behaviour should be the same. The UI and how things are accomplished can be different, but the general behavior should be the same. If those clients were not under the mantle of the nextcloud brand, the story is a different one.
But you have the main project nextcloud and 2 mobile clients. They should work the same or similar.
I know they can't be 100% the same, because the APIs provided by Google and Apple are different.

That's why I said: the general behaviour should be the same.

**Comment by tessus** [comment]
Any update on this? Any comment on my last update?

**Comment by tessus** [comment]
Ping. Any comment from a dev?

**Comment by veddox** [comment]
@doomi I fail to find that feature... (App version 2.20.8, iOS 11.3.1)

**Comment by veddox** [comment]
Related issues: #217 and #547

**Comment by rwat1** [comment]
The Android version of NC App has this feature. It's called "On Device".   The iOS version is lagging in basic features, I'm switching over to Android.

**Comment by doomi** [comment]
Now it asks if you want to delete or remove from cache. Closed?

**Comment by tessus** [comment]
Yes, we can close this issue now.

My thanks go out to the devs!
