### ISSUE TITLE
Module compiled with Swift 3.1 cannot be imported in Swift 3.2 

### ISSUE THREAD

**Issue by victormylle** [nextcloud/ios#401]
Hello
I downloaded all the files and changed everything in capabilities, there is still one error 
. It says that the "Module compiled with Swift 3.1 cannot be imported in Swift 3.2 ". I already tried to use the newest version of realmSwift for swift 4 but then there are other errors.
Please help me
Thank you

**Comment by marinofaggiana** [comment]
Hi @victormylle use Xcode 8 fot the Master branch

**Comment by victormylle** [comment]
Will this work for ios 12? @marinofaggiana

**Comment by victormylle** [comment]
Sorry ios11

**Comment by djitn** [comment]
Maybe you could try this guide to run applications on iOS 11 with Xcode 8? [https://medium.com/swiftist/how-to-use-ios-11-beta-installed-device-with-xcode-8-c255b916aca5](url)
