### ISSUE TITLE
V. 2.18.0

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#403]
@rakekniven version close and publicate in AppStore.

* More compatibility with iOS 11 and with iPhone X
* Removed Crypto Cloud System, for decrypt your files download the App : Crypto Cloud for Nextcloud (it's free)
* Removed grid view on Photo/Video reader
* Added on AutoUpload "More compatibility" for save image in JPEG instead of HEIF 
* Removed cache on Document Provider

thanks

**Comment by rakekniven** [comment]
Hello @marinofaggiana 

Just checked issue and only two issue are marked for v2.18.0 milestone.
One is still open.

Could you please check issues and compare to your change list in your post?

Thank you.

**Comment by rakekniven** [comment]
Did some maintenance. Please close when you are done.

**Comment by rakekniven** [comment]
Which milestone is next?
v2.19.0?
v2.18.1?

Will there be a version 2.17.9?

**Comment by marinofaggiana** [comment]
@rakekniven  for the future : 

Minor version (bugfix only) is 2.18.x where X = 1,2,3 ....

Major version (new feature) 2.X.0 where X = 18,19,20 ...

BIG new version (very big new feature, I think for the new e2e-encryption stable) X.0.0 where X = 3,4,5 .....

**Comment by rakekniven** [comment]
Hello @marinofaggiana ,

I know this semantic versioning.
The question I have is: 
Which versions are you working on in the next time?
Which milestones do we need to add here: https://github.com/nextcloud/ios/milestones ?

Would be perfect if you would assign issues to milestones. 🥇

**Comment by marinofaggiana** [comment]
2.18.1

Fix : crash when save select images/videos without permission
Fix : change the "pages" anymore in excel sheets with multiple "pages"

**Comment by rakekniven** [comment]
Added milestone for v2.18.1
Please add milestone to related issues.

Will close this now.
