### ISSUE TITLE
Upload Video (.mov) file error:File not present,please reload.

### ISSUE THREAD

**Issue by togglecode** [nextcloud/ios#405]
Hello,

I am trying to upload a **.mov** file with size of **87Mb** and **10Mb** with the stable version 2.18.0.00017 and I have the following problem:

**Error: File not present,please reload.**

After that the .mov file will be uploaded but with 0.00 bytes.
I tried with both iOS 10.3 and iOS 11.1 on Nextcloud 12 Server.

![ezgif com-optimize](https://user-images.githubusercontent.com/17141698/32373093-d4393490-c097-11e7-8975-2c963d210162.gif)

**Comment by marinofaggiana** [comment]
Hi @togglecode it's a mov from camera iPhone (video) or ... ?

**Comment by togglecode** [comment]
Hello @marinofaggiana yes from Camera. Even if I take a video with iPhone 5 (48 sec, 96mb) and try to upload (or use autoupload for video) only a file with 0 bytes will be uploaded.

**Comment by marinofaggiana** [comment]
I have tested with a old iPhone 5 video 107 MB 01:14, no issue.

**Comment by togglecode** [comment]
ok so here is the deal,

I wanted to show you some logs, so I had to swtich to the development branch because of swift 4.0.2 Releam update.

there I also get the same issue (the logs aren't that helpful), however I get a different error message. 

![17-11-06 12-40-34 0954](https://user-images.githubusercontent.com/17141698/32439806-afb65908-c2f0-11e7-8653-26d1c1ac71f7.png)


A colleague of mine has also the same issue, but he has an iPhone 6, he says if he change the fps of the video to 1080p 60fps or 4k he cannot upload the video.

**Comment by togglecode** [comment]
I send you the video I am trying to upload with a link to ios [at] nextcloud [dot] com with the subject "Video I am trying to upload". I was never able to upload this file (Store App or Development branch) both had errors.

**Comment by spridarn** [comment]
Hi,

I have the same problem with random videos that I recorded with my iPhone 7 sometimes gets 0 kb in size. This is my log output 
| 2017-11-07, 13:06:34   | Failure | Upload 2017-11-07 12-46-15-5584.mov                                                                  | Error: File not present, please reload. Selector: uploadAutoUpload                                                                                                                                       |
| 2017-11-07, 13:06:04   | Failure | Upload 2017-11-07 12-46-15-5584.mov                                                                  | Video export failed [Error Domain=AVFoundationErrorDomain Code=-11847 "Operation Interrupted" UserInfo={NSLocalizedRecoverySuggestion=Stop other operations and try again., NSLocalizedDescription=Opera |

**Comment by spridarn** [comment]
@togglecode: how did you do that movie of your screen? Some app on the phone?

**Comment by togglecode** [comment]
On iOS 11 you can use [screen recording](https://support.apple.com/en-us/HT207935) and then convert them to [gifs](https://ezgif.com/video-to-gif) (careful about the size)
On older iOS version you need to use use [QuickTime](http://osxdaily.com/2016/02/15/howto-record-iphone-screen-mac-quicktime/)

**Comment by togglecode** [comment]
@marinofaggiana as of the newest Nextcloud iOS update:

After I try to upload the video which I sent you per email, user will get "Video export failed" for multiple times. After that it is not possible to upload any other video and the user keeps getting the error over and over again because of the dispatch_async implemented.

Clearing cache or removing the account is also not helping, the only way is to deinstall and re-install the App.

**Comment by marinofaggiana** [comment]
@togglecode  dispatch_async removed wit new version 2.18.2 available now ... have you a issue of crash ?

**Comment by spridarn** [comment]
@marinofaggiana is this release in AppStore or TestFlight?

**Comment by togglecode** [comment]
No crash, I just get the Video export failed error over and over again from this line, until "too many error, file deleted". After that I cannot upload any videos anymore :sweat_smile:

https://github.com/nextcloud/ios/blob/cdc49cefdcbd072c9942c5fd4e8f62c2303c2e94/iOSClient/Networking/CCNetworking.m#L843-L850

**Comment by marinofaggiana** [comment]
@togglecode very strange ... this line of code it's for video lenght = 0 this routine of export has a issue but now I don't have time for review

**Comment by togglecode** [comment]
@marinofaggiana ok :+1:, I just hope you can re-produce the testcase with the file I sent you. Let me know if you need more information about something.

**Comment by marinofaggiana** [comment]
@togglecode try with last beta TestFlifgt

**Comment by togglecode** [comment]
@marinofaggiana works with build (6), I mean all those files which I had issues can get uploaded now, should I close the issue?

**Comment by marinofaggiana** [comment]
Yes thanks
