### ISSUE TITLE
Version 2.18.1 + 2.18.2

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#406]
@rakekniven : 

* Fixed : iPhone X UI
* Fixed : crash when save selected images/videos without permission
* Fixed : Microsoft Excel sheets with multiple "pages" now works
* Fixed : upload and save photo / video on camera roll

Thanks a lot

**Comment by filipp** [comment]
I'm not able to upload pictures from the iPad camera roll. Not sure if this related the latest update, but the same command with the same version of NC works OK on an iPhone. Here's a screenshot of where it gets stuck.
![img_6113](https://user-images.githubusercontent.com/100739/32542793-64f9a8a6-c47c-11e7-94a6-8f836deafb8d.JPG)

**Comment by rakekniven** [comment]
Hello @marinofaggiana 
Just updated https://github.com/nextcloud/ios/blob/master/CHANGELOG.md
Please merge https://github.com/nextcloud/ios/pull/409

Next time you (or I) have to create tag for release when merging develop branch to master.
AFAICS I cannot create tag for release if commit is some commits behind master. The web UI does simply not allow me to do it.
