### ISSUE TITLE
Folders on top doesn't work anymore

### ISSUE THREAD

**Issue by c4539** [nextcloud/ios#408]
After updating the app to 2.18.2.00001, "folders on top" doesn't work anymore.

**Comment by rakekniven** [comment]
AFAIK this will be included in v2.19.0

**Comment by jasondaigo** [comment]
it also doesnt work for my; didnt recognize it earlier. ican sorty by name and date.up and down aand down and up; but folders are never on top;

**Comment by c4539** [comment]
Sorry @rakekniven , haven't seen you edit. I looks really like the "folder on top" never works, regardless of the combination of the other settings (sort by ... and group by ...). Interesting thing: When I activate "group by file type", folders get in the "unknown" group ... not sure whether this used to be the same in earlier versions of the app.

**Comment by marinofaggiana** [comment]
Fixed on 2.19.0 now in beta

**Comment by rakekniven** [comment]
v2.19.0 is finalized and should be available soon in your local App Store.

**Comment by mnag-hoststar** [comment]
Would it be possible to say in what commit the code was added. We cannot update our whole repo at once at this time and I only need this bit of code at the moment.

**Comment by rakekniven** [comment]
See referenced commit above.
https://github.com/nextcloud/ios/commit/a2920dd3b05d0f47f330bdf0e0f60740c17caa36

**Comment by mnag-hoststar** [comment]
@rakekniven Ah. I'm terribly sorry. I'm rather new to this, so I overlooked the reference. Thank you for pointing it out.
