### ISSUE TITLE
No insertion possible in database

### ISSUE THREAD

**Issue by pci06** [nextcloud/ios#41]
Hi,
When nextcloud sms try to sync with the server, I got an HTTP 500 error and in the nextcloud.log:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params ["pierre", "2017-01-23 12:32:54", "2017-01-23 12:32:54", "11", "1483619299547", 14615, "+00123456789", "Oui et toi \ud83d\ude0a", 0, 1]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x8A' for column 'sms_msg' at row 1

I've check the sms_msg column definition and it is as follow:
![image](https://cloud.githubusercontent.com/assets/5950585/22204319/a31ef8be-e171-11e6-92ba-7f13bc0606a7.png)

Thus none of the both apps (client side and server side) are working...

Pierre.

**Comment by marinofaggiana** [comment]
Hi @pci06 this is repository only for iOS Version.

https://github.com/nextcloud

**Comment by pci06** [comment]
Hi @marinofaggiana, sorry, I did a mistake.
I close this one.
Thank you.
