### ISSUE TITLE
Featur Request: Upload as JPEG at "Upload the whole camera roll"

### ISSUE THREAD

**Issue by chriseatworld** [nextcloud/ios#410]
Would be nice, if it's possible to upload also the camera roll in JPEG format.

**Comment by joelfischerr** [comment]
You mean to convert the photos from png/heic to JPEG before uploading them?

**Comment by rakekniven** [comment]
@chriseatworld You are on iOS11, right?
Please check your iOS settings regarding optimized format. Make sure you are using "Automatic" and you should be done.
