### ISSUE TITLE
iCloud Backup Size

### ISSUE THREAD

**Issue by HFlor** [nextcloud/ios#411]
It is not possible to exclude the local data from Nextcloud from the backup. For example, I have 4 movies from my account in the cache (6GB) and my backup in the iCloud fails at the 5GB size, even if all the apps from the backup are off.

**Comment by KingMarcin** [comment]
Offline files and the cache are probably saved in the "Documents" or "Library" folder. Both of these folders are [backed up in iCloud](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html). It would be better to keep these files in the "Library/Caches" subdirectory which is [not being backed up](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1).

**Comment by marinofaggiana** [comment]
@KingMarcin , no, the files cache are saved in the group directory for share data with extension (document provider included) : 

https://developer.apple.com/documentation/foundation/filemanager/1412643-containerurl

Cheers.

**Comment by marinofaggiana** [comment]
Try test 2.23.2 Build 5 Thanks

**Comment by KingMarcin** [comment]
Great, this issue seems to be fixed in the new build. After reinstalling the app I downloaded a few folders for offline and looked at some files to fill the cache and created a new iCloud Backup. The app now only uses 3,7 MB. 

(I still wonder what's in there, though. The login information and settings shouldn't take up that much space, I think, but maybe they do? Still, it's just a few megabytes, so I think this issue can be closed.)

**Comment by marinofaggiana** [comment]
> (I still wonder what's in there, though. The login information and settings shouldn't take up that much space, I think, but maybe they do? Still, it's just a few megabytes, so I think this issue can be closed.)

ohhh several file, the database, but not BIG file(s) ... Re Open if exists yet the issue.

**Comment by doomi** [comment]
I hope this also solves #484 (iTunes backup)
