### ISSUE TITLE
Comment if you want to join the iOS beta 2.19.0 via Testflight – and then please open issues for any problems you encounter :)

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#412]
The new beta for Nextcloud iOS 2.17.2 is open, write your Apple account email address here if you want receive the invite for TestFlight :

https://itunes.apple.com/it/app/testflight/id899247664?mt=8

You do not like to show your email address here? Send email to ios @ nextcloud dot com

Do not create issues related to this beta on that topic, open a new issue instead.

Please test this issues :
- New e2e function with Nextcloud 13 (Experimental mode, use only for test)
- Settings : “Most Compatible” move from “Auto Upload” to “Advanced”
- Bugfix iOS 11 and iPhone X

** VERIFY on trash if you don't receive the email from iTunes **

**Comment by andyxh** [comment]
I’d like to be added

**Comment by rakekniven** [comment]
Hello @andyxh Please see my first topic.
Please add your email address used with your Apple Account here or send it to ios @ nextcloud dot com

**Comment by NotSoSuper** [comment]
notsosuper at icloud dot com

Thanks!

**Comment by alinmechenici** [comment]
Alin at highwaybusiness.com pls!

**Comment by thoschl** [comment]
hotspot108 at online.de

**Comment by DP19** [comment]
davidjpait at gmail.com

Thanks!

**Comment by MAGALY956** [comment]
Thanks

**Comment by marinofaggiana** [comment]
@MAGALY956 email ?

**Comment by hmbarbosa** [comment]
hmbarbosa@gmail.com please cheers

**Comment by jsturrtle** [comment]
jkap_123@yahoo.com

Thanks

**Comment by marinofaggiana** [comment]
@rakekniven  close version

**Comment by shock143** [comment]
anas@altunji.com
Thanks

**Comment by rakekniven** [comment]
Hello @shock143 You posted at an old closed issue.
Please add your email address to #513
