### ISSUE TITLE
Searchbar in "Files" view is messed up

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#413]
App version : 2.19.0 0002 Testflight
iOS version : 11.1

1. Open "Files" view. No searchbar is visible.
![2017-11-21 10-20-23-0302](https://user-images.githubusercontent.com/2069590/33070547-ab4d6428-ceb8-11e7-83b1-01375695e900.png)

1. Switch to "Favorites". Do nothing.
![2017-11-21 10-20-41-0303](https://user-images.githubusercontent.com/2069590/33070555-af4e0d16-ceb8-11e7-951e-bb16521dd9ff.png)

1. Switch back to "Files". Now part of the searchbar is visible. Only the input box.
![2017-11-21 10-20-50-0304](https://user-images.githubusercontent.com/2069590/33070558-b1a246e0-ceb8-11e7-988e-c7b2ea8585e7.png)

1. I am not able to hide search bar. Whenever I swipe file list to top and try to hide it it jumps down again. Sometimes only partly in limited height (see disappeared text in searchbar)
![2017-11-21 10-21-08-0305](https://user-images.githubusercontent.com/2069590/33070560-b380239c-ceb8-11e7-8a9e-f84d751a885b.png)

**Comment by marinofaggiana** [comment]
Yes this is a bug of iOS 11 ... I search a workaround ...

**Comment by rakekniven** [comment]
Looks good so far with Testflight 2.19.0 0003.
