### ISSUE TITLE
iOS Beta APP issues

### ISSUE THREAD

**Issue by andyxh** [nextcloud/ios#415]
Search bar is very laggy, sometime it disappears. Also the background upload doesn’t work very well you have to open the app to upload pictures and unable to upload videos.

**Comment by marinofaggiana** [comment]
Search bar is very laggy ... the new system of ios 11 is a disaster .... why unable to upload video ?

**Comment by andyxh** [comment]
![17-11-19 11-11-13 0648](https://user-images.githubusercontent.com/24574019/33134320-0e18ad04-cf65-11e7-828b-42d9fac3c57f.jpg)
Getting the following error when trying to upload videos

**Comment by marinofaggiana** [comment]
it's a private video ? can u send me this ?

**Comment by andyxh** [comment]
Unfortunately, the video is private sorry :(  When I try to upload it it show one item like in the picture but I never comes to the transfer and then I get a different error too unable to "Video export failed"
![17-11-22 09-31-25 0671](https://user-images.githubusercontent.com/24574019/33135498-2706b2ea-cf68-11e7-96f8-6f8163c2dd57.png)

![17-11-22 09-18-59 0670](https://user-images.githubusercontent.com/24574019/33135339-c47492b4-cf67-11e7-9a13-4713b5bb4e04.png)

**Comment by marinofaggiana** [comment]
try with next build (5) thx

**Comment by andyxh** [comment]
Will do! I’ll keep you posted :) thank you

**Comment by andyxh** [comment]
Okay, so I updated to build (5). So first I got this error message then the upload went through. but during the process that I think it was trying to export the Video from the phone to the app the whole nextcloud app froze and I wasn't able to do anything. make the hone freeze too. Also this video is about 900MB. It seems like only on large videos the nextcloud iOS seems to have issues. Hope this helps you :)
![17-11-22 13-30-19 0682](https://user-images.githubusercontent.com/24574019/33146538-31233c90-cf8a-11e7-9f3a-3e7a81a285f8.png)

**Comment by marinofaggiana** [comment]
yes, fixed, thanks

**Comment by andyxh** [comment]
You’re Welcome, testing it out, let you know the outcome.

**Comment by andyxh** [comment]
All fixed!!!! Thank you

**Comment by andyxh** [comment]
I have another issues maybe you can fix. So everyone I take a picture or video. The nextcloud does not pick it up automatically and upload it all my settings are on. I open the app and then it starts to upload all my new picture but like I said all settings are on

**Comment by andyxh** [comment]
Any status on the automatic uploads? looks like it’s not picking up the new photos automatically I have to open up the app then it knows I had 160 new photos and it started to upload

**Comment by marinofaggiana** [comment]
Read old several post, automatic upload it’s ok, I close this issue . 1 issue only for thread.

**Comment by andyxh** [comment]
Okay, but I can confirm that there's still issues with it.
