### ISSUE TITLE
iOS 11 nextcloud auto upload issues

### ISSUE THREAD

**Issue by andyxh** [nextcloud/ios#416]
Hello, the auto uploads future is not working properly. The app doesn’t know that I have new photos or videos to upload while all is running in the background. I have to open the app then it scans for the new pictures and videos and starts to upload them right away!

**Comment by c4539** [comment]
Hi @andyxh , if I remember correctly, I had the same issue after installing the latest update. Have you checked whether the app has the "use my location while running in background" permission?
