### ISSUE TITLE
Request: Connect to multiple Nextcloud instances

### ISSUE THREAD

**Issue by sunjam** [nextcloud/ios#420]
I'd like to be able to have login credentials stored for more than one Nextcloud instance.  Example: Home instance in Location A, Work instance in Location B, and Friend instance in Location C.  All set up with their own potentially independent folders + sync settings.

**Comment by marinofaggiana** [comment]
Sorry I don’t understand... multiuser ? Already exists.. where is the difference?

**Comment by rakekniven** [comment]
Open app.
Select more from bottom bar
Your account.
Go to "Manage account"
See "Add account".

You are done.

**Comment by sunjam** [comment]
I see.  The issue is `>` symbol was not clearly the "More" option on the main screen.  Would you consider adding a second link to `Credentials` under the "Settings" tab with just the name `Credentials.`

**Comment by rakekniven** [comment]
Personally I think it is ok. We better ask @jancborchardt 

@sunjam Is my image showing the issue correctly?

![2017-12-13 17-12-51-0389](https://user-images.githubusercontent.com/2069590/33949186-34ae9d5a-e029-11e7-8b3f-59291c66be5d.png)

**Comment by jancborchardt** [comment]
@marinofaggiana is the whole header area clickable to perform the action? Not only the >

@sunjam did you try clicking the header?

**Comment by marinofaggiana** [comment]
@jancborchardt all area

**Comment by jancborchardt** [comment]
Ok, then I would also say it's fine. Let's see if it comes up again.

It's also mentioned in the initial setup slideshow as well as in the appstore screenshots, like on Android, right?

**Comment by marinofaggiana** [comment]
mmmm only this ... Add image and change text ?
![schermata 2017-12-14 alle 14 13 37](https://user-images.githubusercontent.com/8616947/33993960-01e38b82-e0d9-11e7-8cb3-095374285d9e.png)

**Comment by jancborchardt** [comment]
Actually in that popover, there should always be a last entry saying "Add account" with + as symbol on the left. Ok @marinofaggiana? :)

**Comment by marinofaggiana** [comment]
Ok, I add

**Comment by sunjam** [comment]
@marinofaggiana @rakekniven @jancborchardt 
Thanks!
