### ISSUE TITLE
Developer question: Realm Error (Xcode)

### ISSUE THREAD

**Issue by suttonau** [nextcloud/ios#428]
\

**Comment by suttonau** [comment]
@marinofaggiana Hi, I'm having a similar error as @supportreq had earlier this year. I am creating a custom version after changing the bundle identifier I'm starting to get this error - I don't know much about Realm Configuration so any advice you have would immensely help:

Fatal error: A Realm Configuration must specify a path or an in-memory identifier.: file /Users/marinofaggiana/Desktop/realm-cocoa/RealmSwift/RealmConfiguration.swift, line 219
2017-12-14 15:11:50.337286-0500 Nextcloud[30804:20029933] Fatal error: A Realm Configuration must specify a path or an in-memory identifier.: file /Users/marinofaggiana/Desktop/realm-cocoa/RealmSwift/RealmConfiguration.swift, line 219

I have ensured that all bundle and group IDs have been changed, is there anything else I'm possibly missing?

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/424
