### ISSUE TITLE
Feature Request: Photo Upload

### ISSUE THREAD

**Issue by user321321** [nextcloud/ios#442]
Often I need to upload photos in nextcloud. Currently I have to create a photo with the iPhone, then open the Nextcloud app and select and upload the photo. Then I have to open the iPhone app again and delete the picture from the iPhone, because I don't need the photo on the iphone.

It would be great if the Nextcloud app at "+" (add new files) would have an option to create a photo and upload it directly. It should not be stored in the photo memory of the iPhone, but only in the Nextcloud App.

**Comment by doomi** [comment]
Would auto upload be a workaround for your workflow?
Make photos, they will be uploaded automatically, then just delete all photos in the Nextcloud album.

**Comment by user321321** [comment]
In my tests, autoupload does not upload new images immediately. I need the images but directly in nextcloud.
Thus, this workaround is not a solution.

It would be nice if nextcloud would add this simple function.

**Comment by doomi** [comment]
@user321321 now you can make photos directly out of the iOS app. But it still saves it to the phone, though.

**Comment by marinofaggiana** [comment]
>  But it still saves it to the phone, though.

Yes, I know it's bad but, it is a security ...
