### ISSUE TITLE
IOS APP Photo Issues "high priority"

### ISSUE THREAD

**Issue by andyxh** [nextcloud/ios#444]
behavior:                                                                                                                                                      

Photos are not loading since the new update                                                                                        

iOS version
11.2.1

App version
2.19.1

Nextcloud version:
Nextcloud 13 Beta 3

![17-12-30 10-12-29 1273](https://user-images.githubusercontent.com/24574019/34455731-dc32e4ea-ed4a-11e7-9a89-b7abb1c7445e.png)

@marinofaggiana

**Comment by marinofaggiana** [comment]
(Preview ??) Verify your server.

**Comment by andyxh** [comment]
Before the update all the old picture poluldated.  No issue on server end it the app that’s the issue

**Comment by marinofaggiana** [comment]
Nothing modify to the API Thumbnail ... can u try with another demo Server ?

**Comment by andyxh** [comment]
Yes issue on other server. If I upload a photo then it showes up. But old photos won’t populate unless I click on the photos then they’ll show.

**Comment by andyxh** [comment]
Same issue on other server, I don’t think this is a server issue.

**Comment by andyxh** [comment]
Any updates on this?

**Comment by marinofaggiana** [comment]
@andyxh if u want can create a account test for debug ?

**Comment by andyxh** [comment]
Yes I can. What email would you like me send it too ?

**Comment by marinofaggiana** [comment]
ios @ nextcloud dot com

**Comment by andyxh** [comment]
Email has been sent

**Comment by andyxh** [comment]
Hey I just wanted to let you know that once I installed the beta iOS that was just Released everything is now working! Didnt change anything on the server

Sent from my iPhone 7 Plus

On Jan 5, 2018, at 6:06 AM, Marino Faggiana <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #444<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnextcloud%2Fios%2Fissues%2F444&data=02%7C01%7C%7C45730dedc2b442c133d608d55434b0d5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636507507631888098&sdata=uReXSf2g6IQgy3gEbcFSveqkkT7QSzIq1zPiG7KiC%2F0%3D&reserved=0>.

**Comment by marinofaggiana** [comment]
Yes, I know , I have only removed the control for now for errata configuration E2E (file marked as encrypted do not have the thumbnail API !!) ... to prevent issue as your ... but your db is dirty ...

**Comment by andyxh** [comment]
Okay thanks!

Sent from my iPhone 7 Plus

On Jan 5, 2018, at 7:52 AM, Marino Faggiana <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I know , I have only removed the control for now for errata configuration E2E (file marked as encrypted do not have the thumbnail API !!) ... to prevent issue as your ... but your db is dirty ...
