### ISSUE TITLE
Dynamic change of app icon

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/ios#446]
- According to theming
- adjusting to the current active account or maybe only if there is only one account to not make changes too noisy

![9986bb49-c2c0-483e-ac67-8f95c98a86b8](https://user-images.githubusercontent.com/19711361/34468265-82f43e26-ef05-11e7-84df-59d3a69ee526.gif)

@nextcloud/designers @marinofaggiana

**Comment by jancborchardt** [comment]
Let's do it according to theming of the main account for now. :) (no choices like in the example you showed) to keep it simple.

**Comment by MariusBluem** [comment]
This was only to show that it is possible ;)

**Comment by emresaracoglu** [comment]
This is a great idea 👍

**Comment by emresaracoglu** [comment]
Is this feature on the road map? 

cc @marinofaggiana

**Comment by marinofaggiana** [comment]
No, sorry @emresaracoglu
