### ISSUE TITLE
Negative file size

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/ios#448]
### Expected behaviour

The app should show a positive and correct file size.

### Actual behaviour

Only the iOS app (web, desktop client and android app show the correct size) shows a negative file size in byte.

### Steps to reproduce

Don´t know. Any ideas how to get more detailed infomation?

### App configuration

**iOS version:** 10.3.3

**App version:** 2.18.1.00002

### Server configuration

**Operating system**: CentOS

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** 12.0.4

### Screenshots

![iOS](https://user-images.githubusercontent.com/1869584/34482562-180ddacc-efb9-11e7-9fda-c3f53c822503.PNG)

**Comment by marinofaggiana** [comment]
Hi, thanks for you report, try with the next build, are u a TestFlight user ?

**Comment by splitt3r** [comment]
Not yet. How to join?

**Comment by marinofaggiana** [comment]
@splitt3r look :  https://github.com/nextcloud/ios/issues/449

**Comment by rakekniven** [comment]
Hello @splitt3r Can you provide some feedback?

**Comment by splitt3r** [comment]
The file should be 2,4 Gb instead of the negative size. The Web UI + the Android app show the correct size. Perhaps i could share it with you if you give me your Federated Cloud ID.

**Comment by rakekniven** [comment]
Hello @splitt3r are you now a Testflight user?

**Comment by splitt3r** [comment]
Didn´t recieve an invite. Will email you again.

**Comment by splitt3r** [comment]
Now it´s -1.6 GB instead of -......bytes

**Comment by marinofaggiana** [comment]
@splitt3r this is a normal file ? -17289....

**Comment by splitt3r** [comment]
I moved the file to another oC instance with more space and shared it with the Nc instance but the size is still wrong (tested with Nc 12 + Nc 13). I will try to reupload to the Nc instances to see what´s happening.

**Comment by marinofaggiana** [comment]
@splitt3r I have tested without issue ... (big dimension file) can you create a account test with this issue ?

**Comment by splitt3r** [comment]
You have an email.
