### ISSUE TITLE
Move app and system info to suitable section

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#455]
See screenshot:

<img width="320" alt="2018-01-08 16-53-450524" src="https://user-images.githubusercontent.com/2069590/34729909-3622425a-f55e-11e7-8ae4-a6747cd41969.png">

IMHO the information about app and server version should be below "INFORMATION" header.

**Comment by doomi** [comment]
In my app it is down there...
![ebc750be-6811-4deb-a4eb-2d2ff8d4a9ad](https://user-images.githubusercontent.com/2828694/34754501-2b7d6596-f5f9-11e7-808a-eb9bb2082eef.png)

**Comment by rakekniven** [comment]
Hmmh, @marinofaggiana Did you change that recently?

**Comment by marinofaggiana** [comment]
Yes ... this issue is only in TestFlight (view the E2E option)

**Comment by rakekniven** [comment]
But the E2E option is one above and should not be related? Please see both screenshots.

**Comment by marinofaggiana** [comment]
yes, no worry ;)

**Comment by rakekniven** [comment]
@marinofaggiana I don't worry.
I spend time to report issues and to help improving the app.
And you do not give me a good explanation. You just say "no worry" ???

**Comment by marinofaggiana** [comment]
No No, it's only a issue of version on TestFlight but not for the stable version

**Comment by marinofaggiana** [comment]
A question for you @rakekniven, have you tested the E2E ?

**Comment by rakekniven** [comment]
No, sorry.

**Comment by doomi** [comment]
@marinofaggiana I think you can close this issue, it looks correct.
