### ISSUE TITLE
New function: allow plain text editing for markdown (.md)

### ISSUE THREAD

**Issue by MarcusE1W** [nextcloud/ios#471]
Hi.

I would like to suggest to extend the ability to edit plain text files to 
- Markdown files (ending .md, .markdown, ...)

It would enable the same functionality  to edit these files like the .txt files, so not much would have to be added. 

So I am not suggesting to add markdown functionality, just to treat text files with this ending (.md) like plain text files (.txt)

Related Issue: #162. #472

**Comment by rakekniven** [comment]
Hello @marinofaggiana Is it a big task to make editing available for md files like you did for txt?

**Comment by marinofaggiana** [comment]
Hi @rakekniven not for now, other priorities, sorry.

**Comment by ViViDboarder** [comment]
Just pushed a PR that should fix this.

**Comment by MarcusE1W** [comment]
Implemented :-)
