### ISSUE TITLE
New function: allow plain text editing for org-mode (.org)

### ISSUE THREAD

**Issue by MarcusE1W** [nextcloud/ios#472]
Hi.

I would like to suggest to extend the ability to edit plain text files to

- Org Mode files (ending .org)

It would enable the same functionality to edit these files like the .txt files, so not much would have to be added.

So I am not suggesting to add org-mode functionality, just to treat text files with endings .org like plain text files (.txt)

Related Issue: #162. #471

**Comment by ViViDboarder** [comment]
Just pushed a PR that should fix this.

**Comment by rakekniven** [comment]
Works!
