### ISSUE TITLE
Auto Photo Upload - specify directory

### ISSUE THREAD

**Issue by benyanke** [nextcloud/ios#481]
Feature request to specify directory for auto uploading. For example, I'd like to make it more clear for my users I support the difference between the auto uploaded photos and the curated photo library which is shared.

**Comment by rakekniven** [comment]
Settings has been available in older versions and has been removed. This wasn't done by accident. See older issues, have it not present at the moment.

**Comment by benyanke** [comment]
Any idea as to why?

**Comment by rakekniven** [comment]
Please use the search function

**Comment by doomi** [comment]
It‘s now done like this:
swipe left on a folder you want to use, select the three dots, select „folder for automatic upload“

It‘s completely unintuitive!

**Comment by rakekniven** [comment]
Related issue https://github.com/nextcloud/ios/issues/228

**Comment by benyanke** [comment]
Adding this screenshot here, so future people finding this ticket don't need to dig.

![image](https://user-images.githubusercontent.com/4274911/35737279-9ca33b70-07f0-11e8-9b44-23de13e97e18.png)
