### ISSUE TITLE
Error E2E app nextcloud

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/ios#488]
I downloaded the latest version of Nextcloud but when I go to activate the encryption e2e I generate this error as attached
![img_0081](https://user-images.githubusercontent.com/35575744/35903813-04c85cb4-0be1-11e8-840b-3d0ac17ea29a.PNG)

**Comment by marinofaggiana** [comment]
this is the last version on AppStore ? 2.19.3 ? this version is without the E2E ... only the version on TestFlight has the E2E activated :-)

**Comment by tigernero79** [comment]
the voice to encrypt was inserted directly into the iPhone application so I think I have the latest version I'm trying to encrypt the folder and I get that error I'm doing it directly from the iPhone

**Comment by marinofaggiana** [comment]
Send me the version of nextcloud ios please

**Comment by tigernero79** [comment]
the time to get home and confirm the version, I have iphone 5 at home that's why cmq is the latest version available on the play store, is there anything else to enable server-side encryption e2e? because I have updated to nextcloud 13 and the tech preview version on windows client does not give me the possibility to encrypt e2e

**Comment by tigernero79** [comment]
Version 2.19.3.00001 on iPhone 5

**Comment by marinofaggiana** [comment]
Have u install the preview testflight version ? and your server nextcloud has the module e2e correctly install ?

**Comment by tigernero79** [comment]
No test version Onlus android,

nextcloud 13 does not already have the E2E modules installed? do I have to do it manually?

**Comment by marinofaggiana** [comment]
ok it's only a "view" bug

**Comment by tigernero79** [comment]
in nextcloud 13 the module e2e must be enabled separately?

**Comment by marinofaggiana** [comment]
yes and the version on nextcloud available on TestFlight

**Comment by seimsel** [comment]
When can we expect the version with e2e in the app store?

**Comment by marinofaggiana** [comment]
soon ;-) in experimental mode
