### ISSUE TITLE
During upload all pending items should be shown

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#49]
* take multiple photos (>10)
* go to the Nextcloud app - it shows the count in the icon and inside the app in the lower left
* go into the photos folder / or the upload panel (swipe down from header)

### Actual behaviour

* only 2 files are shown that are pending for upload

### Expected behaviour

* all pending files should be shown

cc @marinofaggiana @jancborchardt

**Comment by marinofaggiana** [comment]
@MorrisJobke mmm no ... 10 (max in view) ... 2 ?

**Comment by MorrisJobke** [comment]
> P.S. Take "manual Upload" or "Automatic Upload (All)" ?

Both

**Comment by marinofaggiana** [comment]
Try, in manual max 10 in queue. 
In automatic 1,2 ... 3 .. 2 ... 1 ...  ... minimum possible for preserve the memory ..... 😄

**Comment by MorrisJobke** [comment]
From a users perspective it's confusing. It looks like only one image is queued:

![2017-02-07 11-06-39 2542](https://cloud.githubusercontent.com/assets/245432/22702388/27938938-ed26-11e6-9475-632a18f7460f.png)

And especially worse is the actual folder, because there you see all existing and the currently uploaded. It would be nice to also see what is queued for upload (the image says "2 to upload" but only one is listed and once it's finished the next pops up):

![2017-02-07 11-06-50 2543](https://cloud.githubusercontent.com/assets/245432/22702430/4c4332ba-ed26-11e6-9e85-a880b7201fb2.png)

@nextcloud/designers What do you think?


> minimum possible for preserve the memory ..... 😄

Is this really that memory intensive? It's one entry in the whole list or 10 ... and usually this list is really long (at least in my case - there are only 7 days in February and I already have 134 entries in this folder 😉 )

**Comment by marinofaggiana** [comment]
TELCEL ... are you sure that this is not automatic upload ? upload photos after (+) button ?
Are two modality completely different ... for the memory is complicated for me explain this ... 

Automatic upload system is used also for option "upload ALL" (users with 50.000+ photos) and I don't use queue in memory (too many crashes from iOS for intensive use of CPU ... )  if i load a video in background of several MB ios crash app with use intensive of CPU or low memory ... now iPhone 6s, 7 or 7+ is good but iPhone 5 is too small ... etc. etc. etc. 

When we meet i will explain this 😃 

For visualisation queue [enhancement]

**Comment by MorrisJobke** [comment]
> are you sure that this is not automatic upload ?

This is with automatic upload. I just asked to improve the visual layout and user feedback here :)

**Comment by jancborchardt** [comment]
Totally agree with @MorrisJobke here. Every queued file should be shown as one individual entry (because you should also be able to cancel them individually).

**Comment by marinofaggiana** [comment]
done.

**Comment by MorrisJobke** [comment]
Thanks 👌
