### ISSUE TITLE
Long time app wasn't opened and all pending uploads didn't happen

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#50]
* have the app installed
* take some photos
* don't open the app (in this case over 1 month)
* there are no pending upload on the next open

@marinofaggiana Could this because the app was updated in between and somehow this list of pending uploads vanished somehow?

**Comment by marinofaggiana** [comment]
Yes, possible, it's changed the system from V. 2.16

**Comment by MorrisJobke** [comment]
> Yes, possible, it's changed the system from V. 2.16

That's basically the same as data loss and should never happen. 😉

**Comment by marinofaggiana** [comment]
Before 2.16 the Automatic Upload All was in "beta" and the struct data was temporary, now it is final and close.

**Comment by MorrisJobke** [comment]
> Before 2.16 the Automatic Upload All was in "beta" and the struct data was temporary, now it is final and close.

Okay - I will trust you on this and will check if this is fixed in the future.
