### ISSUE TITLE
E2E module deactivated but entry digit always present

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/ios#502]
I noticed that if I disable or delete E2E module in the iOS application the digit entry is always present what is not correct. in the Android application it disappears. it would be right to make it disappear even for iOS

**Comment by marinofaggiana** [comment]
@tobiasKaminsky if the capabilities e2e is false you remove locally passphrase and keys ?

**Comment by tigernero79** [comment]
I guess not, on Android I think he queries the server and asks if module is active or not. if the answer is no, the voice no longer competes. at least I think so.

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky if the capabilities e2e is false you remove locally passphrase and keys ?

No, keys are removed locally only if the user removes his account.

**Comment by rakekniven** [comment]
Release is out. Closing here
