### ISSUE TITLE
Disable encryption feature per server

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#51]
It should be possible to disable the encryption feature of the iOS client from the server, because it would render those files unusable from other devices/web.

I would propose that we expose this as a capabilities feature on the server, where the server announces to the iOS app to not use encryption and then the iOS app hides all those UI elements.

cc @karlitschek @rullzer @marinofaggiana Does that make sense to you?

**Comment by oparoz** [comment]
Wouldn't it be better to just remove it all together and re-implement the feature across all mobile devices?
It would also improve the onboarding experience.

**Comment by MorrisJobke** [comment]
> Wouldn't it be better to just remove it all together and re-implement the feature across all mobile platforms?
> It would also improve the onboarding experience.

I'm also fine with removing it completely. And regarding the re-implementation: I don't think that we will go this way in the near future, because major pain point here is the key exchange between multiple devices.

**Comment by marinofaggiana** [comment]
For now is not possible, this is too integrated on App but in a few month will add to optional (or removed)... but is correct for me discuss it right now

**Comment by Razva** [comment]
Folks, this is terrible! I created users for my family because I would like them to see the pics I take with my twins. All they can see is a list of "gibberish". 👎 

You *really* need to allow us to upload unecrypted content!

I think that files should be uploaded unencrypted by default, and allow a specific folder to be encrypted. Or if it is to hard to implement, allow users that have higher security needs to encrypt all their data. But again, 99% of us want their content unencrypted by default.

**Comment by mario** [comment]
Yup, based on my experience this (aka encryption) really should be removed as soon as possible.

**Comment by MariusBluem** [comment]
I'd vote for removing it completely (also as the safe of credit cards, ...) since this is nowhere else in Nextcloud 😁

**Comment by jancborchardt** [comment]
Yup, from a user experience point this really hinders everything, starting from the first run experience. @marinofaggiana this is one of the highest priorities regarding improving the UX. :)

**Comment by jasonbayton** [comment]
Add my voice for disabling it.

**Comment by oparoz** [comment]
@anagromataf - Feel free to remove it all if you fancy cleaning up the app :)

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/65#issuecomment-279529979

**Comment by enoch85** [comment]
Remove it completely, if you want encryption you enable it on the server side, not in a smartphone app. My 2 cents.

**Comment by jasonbayton** [comment]
> @enoch85 if you want encryption you enable it on the server side, not in a smartphone app. My 2 cents.

Client-side encryption is vastly superior, but it's too disconnected in its current state from the server, turning the server into more of a vault than a collaborative platform. Perhaps when it's rolled out to all clients the server can do some magic around the public keys to allow sharing.

**Comment by enoch85** [comment]
@jasonbayton Ok, maybe I misinterpreted this function then...

In that case, 2FA to lock your account would be nice-to-have on the client side. Not encryption, but at least some protection for you files (afaik you can't access your files on iOS? by connecting it to a computer).

**Comment by marinofaggiana** [comment]
done.
