### ISSUE TITLE
Gentle reminder: please include info in Version History

### ISSUE THREAD

**Issue by sunjam** [nextcloud/ios#510]
Bug Fixes and Improvements is not helpful as Version History.  Please remember to add details.
![bba7bdda-8937-4660-a08b-426316de5210](https://user-images.githubusercontent.com/1787238/36562579-469fbd84-17cc-11e8-9a72-e52b00567cb1.jpeg)

**Comment by emresaracoglu** [comment]
Hi,

You can see: 

https://github.com/nextcloud/ios/milestone/24

**Comment by rakekniven** [comment]
See https://github.com/nextcloud/ios/blob/master/CHANGELOG.md
