### ISSUE TITLE
Cannot close docx document

### ISSUE THREAD

**Issue by danieltuzes** [nextcloud/ios#512]
I've just installed the nextcloud onto iphone 4s. If I successfully log in to nc and open a docx, I cannot close it, because I cannot see the options at the bottom of the screen. I know it should exist, because if I make a long tap, the zoom function appears. And if I move this lil window to the bottom, in the zoomed area I'm able to see the buttons, but still cannot touch them.

## Nextcloud version
11.0.3

## iOS version
9.3.5 (13G36)

## App version
2.20.3.

**Comment by marinofaggiana** [comment]
HI @danieltuzes can you post a capture of screen ?

**Comment by danieltuzes** [comment]
Sure.
![img_0471](https://user-images.githubusercontent.com/6088393/36795450-5e3c715e-1ca3-11e8-977e-a1d47d26e8ed.PNG)
I don't if this has anything to do with a similar problem: if I mistype the address of the server, I cannot try again, couse I'm navigated to a site from where I don't know hot to go back. 
![img_0470](https://user-images.githubusercontent.com/6088393/36795599-c0edde82-1ca3-11e8-9a12-52a899ce124b.PNG)

**Comment by marinofaggiana** [comment]
@danieltuzes please correct your server/network configuration and connect correctly the app with server, this is the home (example) of Nextcloud iOS on iPhone 4s : 

![simulator screen shot - iphone 4s - 2018-02-28 at 16 46 04](https://user-images.githubusercontent.com/8616947/36796876-e2edf51e-1ca6-11e8-9e07-9dde902c58eb.png)

**Comment by danieltuzes** [comment]
What do you mean by "please correct your server/network configuration"? You mean on the server side? What is the correct configuration?

No, for me the home doesn't look like that. I don't have the bottom line.

**Comment by marinofaggiana** [comment]
Flow login is indispensable, you have not login correctly  ... /**nextxloud** ... flow ... etc. 

<img width="505" alt="schermata 2018-02-28 alle 17 12 12" src="https://user-images.githubusercontent.com/8616947/36798317-8ae81602-1caa-11e8-9122-8b60788fbc03.png">

**Comment by danieltuzes** [comment]
I have chosen "Revert to old web login method", cause I've found it better. Then I didn't want go back to "Revert to old login method". Old is bad, I thought, but it is the only working way.

**Comment by danieltuzes** [comment]
Yes, I misspelled it intentionally. But in this case, I cannot go back, as I said. And if I can log in successfully, there's the problem wit docx still, if I used the web login method.

**Comment by danieltuzes** [comment]
So the problems occurs under web login method.

**Comment by marinofaggiana** [comment]
@rullzer how I make for check the correct URL without that the user use the login as browser ?

**Comment by marinofaggiana** [comment]
I think you use the web login for navigate to the server ... and you don't use the iOS App ... but I do not know how you do it

**Comment by danieltuzes** [comment]
You type the address and (the made up) login credentials and if in the  
error message you've got is error 404, then wrong address, in case error  
code 401, then wrong credentials. One could make it better, but that's a  
feature request.

**Comment by rullzer** [comment]
@marinofaggiana you need to add a check for the nextcloud version. The new login flow is only available from 12 up ;)

@danieltuzes I would suggest you upgrade your server to the latest shiny version of nextcloud.

**Comment by marinofaggiana** [comment]
@rullzer I don't know the nextcloud version before the authentication ... (??) exists an API for know the version ?

**Comment by rullzer** [comment]
<server>/status.php gives you that info

**Comment by marinofaggiana** [comment]
oh yes, true
