### ISSUE TITLE
Comment if you want to join the iOS beta via Testflight – and then please open issues for any problems you encounter :)

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#513]
The new beta for Nextcloud iOS app is open, write your Apple account email address here if you want receive the invite for TestFlight :

https://itunes.apple.com/it/app/testflight/id899247664?mt=8

You do not like to show your email address here? Send email to ios @ nextcloud dot com

Do not create issues related to this beta on that topic, open a new issue instead.

Please test this issues of the milestone.
See https://github.com/nextcloud/ios/milestone/26

**VERIFY on Spam if you don't receive the email from Apple**

**Comment by rakekniven** [comment]
@marinofaggiana For your information.

**Comment by rwat1** [comment]
I want to help out :) emailed.

**Comment by rwat1** [comment]
Just a quick question, if I install the beta version, it will uninstall (and delete photos? delete settings?) of my nextcloud app?  I'm just worried that I lose my settings like cache or photos?

**Comment by rakekniven** [comment]
Settings are still there AFAIK.
About Photos and cache I am not sure.

**Comment by rakekniven** [comment]
Renamed issue and removed version string. We can use this single Testflight issue thread to inform about new Testflight versions and invite people.

**Comment by rakekniven** [comment]
Testftlight offers first build for next release v2.20.5
Please join to Testflight and check issue listed at 
https://github.com/nextcloud/ios/milestone/27

**Comment by marinofaggiana** [comment]
@rakekniven new milestone v2.20.6 created.

**Comment by rakekniven** [comment]
Testftlight offers first build for next release v2.20.6

Please join to Testflight and check issue listed at

How to join? Please read:

The new beta for Nextcloud iOS app is open, write your Apple account email address here if you want receive the invite for TestFlight :

https://itunes.apple.com/it/app/testflight/id899247664?mt=8

You do not like to show your email address here? Send email to ios @ nextcloud dot com

Do not create issues related to this beta on that topic, open a new issue instead.

Please test this issues of the milestone.
See https://github.com/nextcloud/ios/milestone/28

**VERIFY on Spam if you don't receive the email from Apple**

**Comment by sebastiaanveld** [comment]
would be great!

**Comment by ReginaMv** [comment]
HI! Can I get an invitation as well?

**Comment by NoName805** [comment]
I want to be a tester, emailed few days ago but still no news.

**Comment by marinofaggiana** [comment]
@NoName805 what's your email ?

**Comment by NoName805** [comment]
@marinofaggiana im at noname dot hk

**Comment by marinofaggiana** [comment]
@rakekniven 2.20.6 is available and close

**Comment by rakekniven** [comment]
@marinofaggiana Please merge https://github.com/nextcloud/ios/pull/539

To all testers: Thank you!

We will let you know here as soon as next Testflight is ready for you.

Enjoy and provide feedback.

**Comment by rakekniven** [comment]
Testftlight offers first build for next release v2.20.7

Please join to Testflight and check issue listed at

How to join? Please read:

The new beta for Nextcloud iOS app is open, write your Apple account email address here if you want receive the invite for TestFlight :

https://itunes.apple.com/it/app/testflight/id899247664?mt=8

You do not like to show your email address here? Send email to ios @ nextcloud dot com

Do not create issues related to this beta on that topic, open a new issue instead.

Please test this issues of the milestone.
See https://github.com/nextcloud/ios/milestone/29

**VERIFY on Spam if you don't receive the email from Apple**

**Comment by marinofaggiana** [comment]
@rakekniven 2.20.7 closed. Thanks

**Comment by marinofaggiana** [comment]
@rakekniven 2.20.8 is out. thanks

**Comment by shock143** [comment]
anas@altunji.com
Thanks

**Comment by thiphariel** [comment]
Still available ?

**Comment by cscholz** [comment]
I‘ve beta tester are still requiered please add me

**Comment by shock143** [comment]
Please send invitation to anas@altunji.com

**Comment by DrRSatzteil** [comment]
Please send an invitation to drrsatzteil@web.de. Thanks!

**Comment by marinofaggiana** [comment]
For all, use this link: https://testflight.apple.com/join/GjNbfo2a

**Comment by alxzhdanov** [comment]
I want to rollback to previous version. I need a code. Thank you.

**Comment by rakekniven** [comment]
We can close here, or? @marinofaggiana

**Comment by Mccarthy90** [comment]
Cole_90@icloud. Would love a link, thanks guys.

**Comment by thisIsTheFoxe** [comment]
@Mccarthy90 thanks for your interest. Have you tried [the link in the Readme](https://github.com/nextcloud/ios#testflight)? Please use that one if possible. If you can't join the TestFlight Beta via that link please let us know..
