### ISSUE TITLE
Show favorites first, then folders and then files

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#514]
* current sort order is purely by name - no matter the type of the entry (folders and files mixed)
* I expect the iOS app to show the same order as in the web and on android, where the order is: Favorites first, then folders and then files.

cc @nextcloud/designers @marinofaggiana

**Comment by marinofaggiana** [comment]
@MorrisJobke @MariusBluem this order (fav,dir,files) is only for option "Folder on Top" (now is default ON when install Nextcloud NC)

**Comment by MorrisJobke** [comment]
Thanks works 👍
