### ISSUE TITLE
Dynamic menu items

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#52]
Same as the Android version, but for iOS: nextcloud/android#555

Capabilities API would expose menu items to be added to the sidebar. The menu items would simply open a web page, and the API would expose title and the URL. Typically stuff like "Help": "link to help page" and "About us": "link to about us page".

We are currently planing the API and then I will update this ticket here with the details.

@jancborchardt Maybe we need a similar side bar for all the categories on the iOS side too. Be prepared that we need some UX help for this one, because currently I have no idea where to put those entries in the current app. 

@marinofaggiana Feel free to suggest something.

**Comment by MorrisJobke** [comment]
@MariusBluem Another use case for the sidebar.

**Comment by jancborchardt** [comment]
Seems we could put them in the settings for now.

But yes, I am not totally opposed to a sidebar for the iOS app. Other apps like Netflix and even Apple Mail (for the folders) do it too.

**Comment by marinofaggiana** [comment]
Apple mail do not use sidebar. Apple do not use sidebar

**Comment by MorrisJobke** [comment]
It's broken: #129

**Comment by marinofaggiana** [comment]
The menu is available only for "custom" ! .... ? or for too "Standard" Version ?

**Comment by jancborchardt** [comment]
@marinofaggiana Apple Mail doesn’t use a sidebar, but a system of the folder list being to the left. It technically isn’t a sidebar, but visually very close.
And widely used apps like Netflix and Google Maps use a sidebar. :) 

Anyhow, a better alternative would be how Maps.me does it, as mentioned in issue: https://github.com/nextcloud/ios/issues/134#issuecomment-289396839

**Comment by marinofaggiana** [comment]
Google Maps, Google Drive it's Android porting (all product google use sidebar), Mail use a normal "Segue" for  NavigationViewController but start from page 1 (0 is the first) and this is not a sidebar bat a normal page (sidebar is totally else), Netflix does what it wants ;)

**Comment by MorrisJobke** [comment]
> Mail use a normal "Segue" for NavigationViewController but start from page 1 (0 is the first) and this is not a sidebar bat a normal page (sidebar is totally else

I don't care how it is called. It looks like a sidebar and fits the requirements we have (place for a list of menu items). I would go for this.

**Comment by jancborchardt** [comment]
(@MorrisJobke just as question: would the Maps.me style also work, when the container coming out in the bottom is scrollable?)

**Comment by MorrisJobke** [comment]
> I don't care how it is called. It looks like a sidebar and fits the requirements we have (place for a list of menu items). I would go for this.

@marinofaggiana Sorry for the hard sounding words: what I meant is: there should be a list with menu entries. And it's fine if it is not a sidebar but a separate view. 😉

**Comment by MorrisJobke** [comment]
> (@MorrisJobke just as question: would the Maps.me style also work, when the container coming out in the bottom is scrollable?)

Need to check back on this.

**Comment by marinofaggiana** [comment]
Boys ... next days after the last issue on API proxy I find a solution

**Comment by jancborchardt** [comment]
@marinofaggiana and I will look at this tomorrow. We have two main options:
1. Do it like Apple Mail (their account list), with the list coming in from the left and the button on the top left. This would be very flexible and pretty much exactly like in the Android app. This is also pretty standardized and since it’s used by Apple Mail, people are used to this.
2. Do it like Maps.me and have the possibility for a long scrollable list in there. This is a bit nicer integrated with the bottom bar.

What we do have to decide is what we would like better for our own app too so we don’t do duplicate work. Any strong opinions @eppfel @LukasReschke @MorrisJobke?

**Comment by marinofaggiana** [comment]
Maps.me tab bar is a good solution but only for 4..5 items ... It's sufficiently ??? And AMX ? Amx want the same thing for ios and Android or the sidebar " compulsorily " ?

2) It's necessary a design mockup, a good Interface required several week, exists iPhone iPad in landscape in portrait in split mode and iPhone plus with a mix for iPhone & iPad ... 

What should be placed in the new menu (sidebar for example ? ) ... it's important identifier the possibility 

:-)


"Leave your opinion on App Store, it is important to us"

Marino Faggiana (ios@nextcloud.com)
Nextcloud App iOS Project Manager

oOo - Nextcloud - A safe home for all your data

**Comment by marinofaggiana** [comment]
Maps.me tab bar is a good solution but only for 4..5 items ... It's sufficiently ?

It's necessary a design mockup, a good Interface required several week, exists iPhone iPad in landscape in portrait in split mode and iPhone plus with a mix  iPhone & iPad ... 

What should be placed in the new menu (sidebar for example ? ) ... 
it's important identifier the possibility ...  
:-)

**Comment by marinofaggiana** [comment]
Sorry reopen (iPhone) :-)

**Comment by MorrisJobke** [comment]
> What should be placed in the new menu (sidebar for example ? ) ...

Stuff like:

* uploads
* activities
* menu items from the server side configurable menu
* account switcher

So basically all the items, that are now quite hidden. They should be made discoverable - which means: give somebody the app (without the tutorial, because nearly everybody skips tutorials) and then the person should be able to find all the stuff, without the need for swipe gestures from a given point in the UI.

**Comment by marinofaggiana** [comment]
Ok , the Apple Mail style ...

**Comment by MorrisJobke** [comment]
> Ok , the Apple Mail style ...

Thank you very much - sorry for being that annoying about this, but it is also tricky to communicate this on my side 😉

**Comment by jancborchardt** [comment]
> Ok , the Apple Mail style ...

Exactly, as we talked about. :)

**Comment by marinofaggiana** [comment]
- done in solution menu : more -

**Comment by jancborchardt** [comment]
Extra huge cheers all around that we solved this by the way. :) It looks and feels quite nice and simple!
