### ISSUE TITLE
change navigation/status bar to grey as the tab bar 

### ISSUE THREAD

**Issue by supportreq** [nextcloud/ios#528]
is there a way i can change the navigation and the status bar colour to grey colour as the tab bar..

please advice.. can this be done using the NCBrand file

**Comment by marinofaggiana** [comment]
Hi @supportreq 
yes use NCBrand.swift and change : 

@objc public let customer: UIColor = UIColor(red: 0.0/255.0, green: 130.0/255.0, blue: 201.0/255.0, alpha: 1.0)

If you don't want use the theming color server : 

@objc public let use_themingColor: Bool = false

Cheers

**Comment by supportreq** [comment]
@marinofaggiana how do i change colour for the back button and the menu?? currently it shows as white..
