### ISSUE TITLE
Where is the code generating and drawing the red 'number of remaining files' counter that is on the Files button?

### ISSUE THREAD

**Issue by JSzaszvari** [nextcloud/ios#529]
Hi There

I'm using a custom version of the App that we have modified to suit our environment - But there is one change I'm struggling to figure out.

The red icon that appears on the "Files" button which shows how many files are left to download after adding to favorites, I'm trying to shift this one button over to the right (Onto the actual Favorites button) 

I've received feedback from our users that it would make more sense if the files remaining indicator sat on the actual favorites button

Example

Default:
![simulator screen shot - iphone 7 - 2018-03-10 at 23 36 13 copy](https://user-images.githubusercontent.com/872463/37242545-5cb5188a-24bf-11e8-8fd6-fcf47525db91.png)

What I want to do:

![2](https://user-images.githubusercontent.com/872463/37242573-d7fff668-24bf-11e8-826b-65c0d49e933e.png)

(It's called Offline Files not Favorites in the version we have deployed) 

I just can't find where it's drawing that actual number and placing it on the button.

If anyone could point me in the right direction that would be much appreciated. 
Thanks

**Comment by marinofaggiana** [comment]
Hi @JSzaszvari 
https://github.com/nextcloud/ios/blob/643504b9a33759379a1167eeb572d92821d11985/iOSClient/AppDelegate.m#L831

Bur required a different routine for select the "normal" download for the download for the favorite ...

Cheers

**Comment by JSzaszvari** [comment]
@marinofaggiana Thanks, I appreciate it.
