### ISSUE TITLE
File search

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#53]
Implement file search which would be similar to what the server frontend does. 

The API can be found at nextcloud/server#676 and is basically the same as nextcloud/android#558

@nextcloud/designers How should this look like on iOS. Maybe @jancborchardt and @mario can help here.

Best would be to immediately filter the current view on the search term and then show the search results as they are received from the server. Right, @jancborchardt?

The search results should show a list with
- name
- folder name
- when clicking on it it should directly open this file (just like clicking on it in the file list)
- long clicking on the file should show "go to folder"

as reference the current web view:

<img width="1254" alt="bildschirmfoto 2017-01-11 um 14 52 07" src="https://cloud.githubusercontent.com/assets/5836855/22114934/60bd2878-de6b-11e6-98d6-353d82cdac26.png">

cc @marinofaggiana 

@oparoz Anything I forgot?

**Comment by disaster123** [comment]
It would be great if it would be possible to work with +,-,"and" and "or" like you can at google.

**Comment by MorrisJobke** [comment]
> It would be great if it would be possible to work with +,-,"and" and "or" like you can at google.

First of all: we do a basic search. Then we can look into refine this.

**Comment by jancborchardt** [comment]
> Best would be to immediately filter the current view on the search term and then show the search results as they are received from the server. Right, @jancborchardt?

Exactly. That provides the quickest feedback while giving detailed results when they come in. The layout should be exactly the same as the file list itself.

**Comment by marinofaggiana** [comment]
This is the solution for search : 

Roof folder, two possibilities 

- search in this folder (filter)
- search in ALL folder (search in all server folders)
![1](https://cloud.githubusercontent.com/assets/8616947/24101630/5e8a0660-0d79-11e7-8d94-f97d6f329854.png)

All subfolder, two possibilities

- search in this folder (filter)
- search here and subfolders 

![2](https://cloud.githubusercontent.com/assets/8616947/24101756/c380629e-0d79-11e7-80de-1410d35ddc87.png)

All possibilities are so fulfilled :)

**Comment by MorrisJobke** [comment]
It's basically done. I opened bug reports for broken stuff:

#126 & #127

**Comment by supportreq** [comment]
@MorrisJobke is this change added to master?? i tried compiling the new version but did not get search here and subfolders option.. please advice.. [Is it server dependent??]

**Comment by mario** [comment]
@supportreq it is server dependant, yes.

**Comment by supportreq** [comment]
@mario which server version onwards will it work??

**Comment by mario** [comment]
12

**Comment by supportreq** [comment]
should i pull it from the server master branch?

**Comment by mario** [comment]
Yup
