### ISSUE TITLE
upload a file(txt,pdf....) which already exist,will overwrite the old one.

### ISSUE THREAD

**Issue by 523164818** [nextcloud/ios#537]
Expected behaviour

not overwrite the old one;rename the new one,and upload。
or give some message about going to overwrite.

Actual behaviour

overwrite the old one with no message.

Steps to reproduce

1.upload a.txt
2.reupload a.txt

iOS version

ios 11

App version

2.20.5

Server configuration

'instanceid' => 'ociw4r7g4e6x',
'passwordsalt' => 'X1DzF+WhLnOo8b2kOfdeKOl7rqUf0I',
'secret' => 'ZxcYdW/WxdJmK5zrnN7lPxC2d4jiKXcJyyaUVRanG0o9mUrx',
'trusted_domains' =>
array (
0 => '10.221.12.72',
),
'datadirectory' => '/var/www/coral-server/data',
'dbtype' => 'mysql',
'version' => '14.0.0.1',
'overwrite.cli.url' => 'http://10.221.12.72',
'dbname' => 'coralcloud',
'dbhost' => 'localhost',
'dbport' => '',
'dbtableprefix' => 'oc_',
'dbuser' => 'coralcloud',
'dbpassword' => '123456',
'installed' => true,
'ldapIgnoreNamingRules' => false,
'ldapProviderFactory' => 'OCA\User_LDAP\LDAPProviderFactory',
Operating system:
ubuntu 16.04
Web server:
apache2
Database:
mysql
PHP version:
7.0.25
Nextcloud version: (see Nextcloud admin page)
14.0.0

**Comment by rakekniven** [comment]
Hello @523164818 Please check your posting and do NOT post passwords and other sensitive data to GitHub.

Back to your issue:

Renaming is not an option IMHO. You do not get a warning or renamed file while editing a file on your desktop as well.

Enable "versions" app on your server and you are done. This is a core app and you can simple enable it.
