### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#54]
The iOS app should be able to receive Nextcloud notifications. The API is currently developed in https://github.com/nextcloud/notifications/pull/59.

Most of the items in https://github.com/nextcloud/android/issues/559 are also valid for the iOS app. @jancborchardt and @mario  could you help to sketch out how it should exactly behave?

cc @nickvergessen @LukasReschke because you discussed this already during the hackweek. Could you outline the way how this should be implemented on iOS to help @marinofaggiana 

cc @oparoz

**Comment by nickvergessen** [comment]
There seems to be a misunderstanding. nextcloud/notifications#59 is only for push notifications. Pulling is already done and documented in https://github.com/nextcloud/notifications/blob/master/docs/ocs-endpoint-v2.md

I already explained that to Marino when he was in Stuttgart before the hackweek.
The iOS app should always pull when it is opened, this also helps when one of the pushes didn't go through. So notifications development on iOS can already be done, apart from the push-stuff

**Comment by marinofaggiana** [comment]
The iOS Notification is done. (improvements in the future)

**Comment by MorrisJobke** [comment]
> The iOS Notification is done. (improvements in the future)

I have seen this. We need to think about how they are presented, because nowadays is a modal that pops up for every notification, which was quite annoying last time.

**Comment by marinofaggiana** [comment]
He he try last beta

**Comment by MorrisJobke** [comment]
> He he try last beta

I will and report back.

**Comment by marinofaggiana** [comment]
@MorrisJobke i have problem with a field of Notification : 

"icon": "http://localhost/img/icon.svg" [example]

SVG is not a compatible image ... 

i have alert @nickvergessen

**Comment by MorrisJobke** [comment]
> SVG is not a compatible image ...

We only have SVGs. As it seems only PNGs and JPEGs are natively supported we maybe look into providing PNGs here. What resolution do they need to have? Do we maybe want to reuse the preview generator for this conversion? cc @nickvergessen @rullzer

**Comment by nickvergessen** [comment]
SVG previews need imagick, we can try and if not just use a default icon? Anyway I would expect the iOS to do that, or allow something like `/preview?svg=full-path-to-svg` or something like that.
Because I don't break the API or deliver pngs all the time.

**Comment by marinofaggiana** [comment]
now i use 🔔 for each record but is not good ... (see Beta)

**Comment by marinofaggiana** [comment]
@nickvergessen @LukasReschke please issue proxy server ... look my email

**Comment by nickvergessen** [comment]
Should work now

**Comment by marinofaggiana** [comment]
https://push-notifications.nextcloud.com/device?pushToken=284ffc388c96b4bf82451cfa834c38ac3946204961cbd2d2c8f43193a99ff08c ... etc.
error 404 

My error ?

**Comment by nickvergessen** [comment]
Yes, browser is "GET", but the server only accepts POST and DELETE.
I send you the curl commands again

**Comment by marinofaggiana** [comment]
No @nickvergessen this is not a browser GET but my API with requestMethod "POST" and return 404.

**Comment by marinofaggiana** [comment]
@nickvergessen @LukasReschke with the new token (firebase) the subscribingPushProxy return error 500 ...

**Comment by marinofaggiana** [comment]
@LukasReschke ping 😄

**Comment by nickvergessen** [comment]
Will have a look tomorrow and debug this.

**Comment by nickvergessen** [comment]
Fixed, the database on the live server was still for the apns tokens (64 chars) so the fcm tokens (up to 4000 chars) didn't fit.

I redeployed the database and also pulled the latest changes. Please try again.

**Comment by marinofaggiana** [comment]
@nickvergessen for coherence is not possible : 

Subscribing at the Nextcloud server : 

PushToken (PushTokenHash) sha 512

------------------

Subscribing at the Push Proxy :

"pushToken": "{{PushToken}}", <------ (PushTokenHash) sha 512 

Whats do you think ?

**Comment by nickvergessen** [comment]
No:
* the server should not know the push token, only the hash
* the push proxy needs the push token
