### ISSUE TITLE
Old Feature request - Photos

### ISSUE THREAD

**Issue by gt2416** [nextcloud/ios#540]
Since the new update on the iOS app the photos tab now shows all media from the server.
Can we please please get an option to revert back ? 

Using this as my family cloud, it is very intuitive for non - tech people to be able to see their backed up photos the same way as the ios native photos app. This is one of the main reasons I was able to get them to switch from iCloud. 
Now however, because I have external storage and a lot of movies and stuff on the server. It really isn't usable like this, or at least its very non-intuitive especially for non tech people who just want to backup their photos and access it in a familiar way. Also Thumbnails dont generate for most of the media from the server and makes that tab very clumsy and terrible to use. (I have a ton of movies / tv shows on my server).  

Could you please provide the option at least to only use a certain folder or the entire server. This really changes the fundamental way I (and presumably others) use the app. 
I also have a folder of videos I would rather no one see, this used to be fine, just put those files in another folder, which isnt possible anymore. 

Thank You for your constant continued support to the app !

**Comment by marinofaggiana** [comment]
Yes, I think this is a good question, I will add a option ;-)

**Comment by gt2416** [comment]
Thank you guys so much ! Really appreciate it 👍

**Comment by rwat1** [comment]
@marinofaggiana

Hi Marino, you posted [here ](https://github.com/nextcloud/ios/issues/540#issuecomment-375221029) saying you will add an Option... I cannot find it in V 2.20.8 this "Option" to turn On (view all media on folder) or turn off (no view all media on folder in Photos tab).

I cannot find it in the Settings?

Thank you Marino,

**Comment by gt2416** [comment]
It was implemented in the very next version. I was talking for an option to CHOOSE the media folder.,
Not to turn the media on or off. In the photos tab there is a folder icon in the top left that lets you CHOOSE the media folder.

**Comment by rwat1** [comment]
@gt2416 

Ok, I upgraded to 2.20.9, and I see this option now.

Gotcha.
