### ISSUE TITLE
iOS testflight, trying to reset E2E

### ISSUE THREAD

**Issue by monoprix** [nextcloud/ios#546]
Hello everyone,

I am currently using the latest Testflight version of NC on the latest version of iOS. A provider hosts an instance of NC 13 for me. The host provides me with an instance on a server at the end of which is attached an external storage box.

A few versions of NC ago–about 2 weeks ago–I enabled E2E through the app, but before I was able to copy the entire passphrase the app crashed. I disabled E2E on the app, but when trying to re-enable it, I was asked for the previous passphrase. Since then, I’ve tried signing out, clearing the cache, uninstalling the app, revoking the app from within the browser, and every time I try to re-enable E2E, I get the same request for the original passphase. I then tried installing on another device, and again, when trying to activate E2E, I was asked for the original passphrase.

Is there anyway of resetting E2E so that my device can once again use E2E? The NC instance is brand new, I don’t have any files on it and I deleted all the folders. Is there anyway of resetting E2E so that my device can once again use E2E?

Any help is really appreciated. I’m stumped.

**Comment by marinofaggiana** [comment]
Hi @monoprix  he certificate of e2ee are saved on server, remove it on server side.
