### ISSUE TITLE
Display the currently used and total quota

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#55]
The Android app shows this in the bottom of the sidebar:

<img width="450" alt="bildschirmfoto 2017-02-05 um 16 40 07" src="https://cloud.githubusercontent.com/assets/245432/22630543/bfc022b8-ebc1-11e6-86c3-5728e1fda9e8.png">

@nextcloud/designers Do you have an idea where to put this in the iOS app? Should we maybe streamline the UI of both apps and introduce a sidebar on iOS as well to also show all the other categories?

**Comment by MorrisJobke** [comment]
The information is already visible in the settings ("Settings" -> "Cloud account") as number, but not as progress bar. Maybe we add the progress bar there? cc @oparoz @karlitschek

**Comment by MariusBluem** [comment]
The apps should have the same UI over all platforms 😁 (...but of course we should not miss platform-specific aspects) - A sidebar for example is nearly used nowhere in iOS, but - I think this would be the easiest solution 😅

**Comment by MorrisJobke** [comment]
> The apps should have the same UI over all platforms 😁 (...but of course we should not miss platform-specific aspects) - A sidebar for example is nearly used nowhere in iOS, but - I think this would be the easiest solution 😅

Mmmh ... on the other hand, we also need a place where we can link to the activities view (#58) and the sidebar would be a good fit for this.

**Comment by marinofaggiana** [comment]
No, sider bar in iOS it's horrible and hated by all, for me remove this too in Android ...horrible

**Comment by oparoz** [comment]
@marinofaggiana What is the alternative?

**Comment by marinofaggiana** [comment]
on iOS this are Settings (apart google Drive) see Instagram Twitter etc. 

![schermata 2017-02-06 alle 16 29 52](https://cloud.githubusercontent.com/assets/8616947/22653403/873420d4-ec89-11e6-9484-f1dda93b4e3b.png)

Now is "CLOUD ACCOUNT" but next i can create a new view with icon and user data (tel, email ...) 

?

**Comment by oparoz** [comment]
I think this would work for quota and plan management if we can load a webview from within settings to make it work.
@MorrisJobke See what they think?

**Comment by marinofaggiana** [comment]
But WebView it's only for plan, not for user information (quota, username, photo, tel, etc)

**Comment by MorrisJobke** [comment]
> @MorrisJobke See what they think?


For this one here (show the quota bar) it's fine to have it in settings 👍

**Comment by marinofaggiana** [comment]
done, tomorrow beta.
