### ISSUE TITLE
Feature Request:  Share file without downloading in iOS client

### ISSUE THREAD

**Issue by sunjam** [nextcloud/ios#554]
I’d like to be able to share or re-share a file from the iOS client without having to download it first.  Example would be this 70+ mb gif I just want to send as a url link to a forum.
![805c8713-629b-4be9-9421-a767387f872d](https://user-images.githubusercontent.com/1787238/38635642-da963efe-3d7a-11e8-8d77-8200de225c4d.jpeg)

**Comment by marinofaggiana** [comment]
Hi @sunjam it's already so

**Comment by sunjam** [comment]
@marinofaggiana Hi, I don’t see how sharing is possible **without downloading** the file.  Here is what I see when I attempt to share a file listed in Nextcloud iOS client without downloading...
- it attempts to download
- until the file diwnloads via the iOS client, no sharing options are presented
![3024e817-c781-4821-8288-4ddf2b20109a](https://user-images.githubusercontent.com/1787238/38689482-a6e5c064-3e30-11e8-84b5-5b4bd6df4171.jpeg)

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/556
