### ISSUE TITLE
Update icons to use Nextcloud style

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#555]
As discussed @marinofaggiana :)

Header & bottom bar
- Notifications https://github.com/nextcloud/notifications/blob/master/img/notifications.svg
- Files https://github.com/nextcloud/server/blob/master/core/img/places/files-dark.svg
- Favorites https://github.com/nextcloud/server/blob/master/core/img/actions/star-dark.svg
- Upload https://github.com/nextcloud/server/blob/master/core/img/actions/add.svg
- Pictures https://github.com/nextcloud/server/blob/master/core/img/categories/multimedia.svg
- Menu https://github.com/nextcloud/server/blob/master/core/img/actions/menu.svg

Top bar menu
- Select https://github.com/nextcloud/server/blob/master/settings/img/admin.svg
- Folders on top https://github.com/nextcloud/server/blob/master/core/img/places/files-dark.svg

File list
- Share (50% opacity when not shared) https://github.com/nextcloud/server/blob/master/core/img/actions/share.svg
- Shared by link https://github.com/nextcloud/server/blob/master/core/img/actions/public.svg
- More https://github.com/nextcloud/server/blob/master/core/img/actions/more.svg

File menu
- Share https://github.com/nextcloud/server/blob/master/core/img/actions/share.svg
- Details https://github.com/nextcloud/server/blob/master/core/img/actions/info.svg
- Rename https://github.com/nextcloud/server/blob/master/core/img/actions/rename.svg
- Move https://github.com/nextcloud/server/blob/master/core/img/actions/external.svg
- Delete https://github.com/nextcloud/server/blob/master/core/img/actions/delete-hover.svg

More menu
- Activity https://github.com/nextcloud/activity/blob/master/img/activity-dark.svg
- Settings https://github.com/nextcloud/server/blob/master/core/img/actions/settings-dark.svg

Credentials
- Edit password https://github.com/nextcloud/server/blob/master/core/img/actions/rename.svg
- Remove account https://github.com/nextcloud/server/blob/master/core/img/actions/delete-hover.svg
- Add account https://github.com/nextcloud/server/blob/master/core/img/actions/add.svg

**Comment by jancborchardt** [comment]
@marinofaggiana nice, all icons are replaced? :) Awesome!

**Comment by marinofaggiana** [comment]
yes @jancborchardt, soon the beta in testflight, please download it for look

**Comment by marinofaggiana** [comment]
ping @jancborchardt

**Comment by marinofaggiana** [comment]
![simulator screen shot - iphone x - 2018-06-20 at 12 06 17](https://user-images.githubusercontent.com/8616947/41652107-8570edb8-7482-11e8-9dce-fc9242b7c557.png)
![simulator screen shot - iphone x - 2018-06-20 at 12 06 25](https://user-images.githubusercontent.com/8616947/41652108-859638c0-7482-11e8-9398-90a961053206.png)
![simulator screen shot - iphone x - 2018-06-20 at 12 06 36](https://user-images.githubusercontent.com/8616947/41652110-85b5174a-7482-11e8-8c70-1cda0014d75c.png)
![simulator screen shot - iphone x - 2018-06-20 at 12 04 52](https://user-images.githubusercontent.com/8616947/41652111-85d3bdf8-7482-11e8-9e9a-62f042506544.png)
![simulator screen shot - iphone x - 2018-06-20 at 12 05 01](https://user-images.githubusercontent.com/8616947/41652113-85f1a14c-7482-11e8-8631-6c2f59967cc2.png)
![simulator screen shot - iphone x - 2018-06-20 at 12 05 14](https://user-images.githubusercontent.com/8616947/41652114-86102252-7482-11e8-9229-0743ea37819a.png)
![simulator screen shot - iphone x - 2018-06-20 at 12 05 21](https://user-images.githubusercontent.com/8616947/41652117-86328900-7482-11e8-82b6-95f72110e35b.png)
![simulator screen shot - iphone x - 2018-06-20 at 12 05 27](https://user-images.githubusercontent.com/8616947/41652119-873162c2-7482-11e8-9023-953fdbcb0645.png)
![simulator screen shot - iphone x - 2018-06-20 at 12 05 38](https://user-images.githubusercontent.com/8616947/41652121-8819f0d2-7482-11e8-9328-0298138d41d5.png)
![simulator screen shot - iphone x - 2018-06-20 at 12 05 45](https://user-images.githubusercontent.com/8616947/41652123-889499fe-7482-11e8-9011-0c6249bee08d.png)
![simulator screen shot - iphone x - 2018-06-20 at 12 05 59](https://user-images.githubusercontent.com/8616947/41652124-88c64e72-7482-11e8-9f62-e3f5034d0c7c.png)
![simulator screen shot - iphone x - 2018-06-20 at 12 06 10](https://user-images.githubusercontent.com/8616947/41652125-88e5d3aa-7482-11e8-9f42-9358ddbe0528.png)

**Comment by jancborchardt** [comment]
Ok, looking awesome! :) Thank you so much!! :tada:
