### ISSUE TITLE
Feature request:  Share folder via iOS client / Manage “File Drops”

### ISSUE THREAD

**Issue by sunjam** [nextcloud/ios#556]
Hi! Currently only file sharing is supported on iOS.  I’d like to see support for folder sharing added.

- folder sharing, even if empty, from iOS client
- ability to define folder as a [**file drop**](https://nextcloud.com/file-drop/) from iOS
- - Upload only
- - read and write
- - optional password
- - optional expiration

**Comment by marinofaggiana** [comment]
@sunjam it's possible sharing file and directory.

**Comment by sunjam** [comment]
How would I share a folder from within the iOS client?  When I select a folder it automatically opens to display the files contents, which are all I can select.  No sharing options are visible for folders that are not already shared via the web interface.
![c82a246d-339f-4916-99e9-1b3b1fe5cb40](https://user-images.githubusercontent.com/1787238/38689910-a80eefaa-3e31-11e8-932b-c5564dfff7b3.jpeg)

On File Drop functionality
I do not see this functionality in the mobile client either.

**Comment by marinofaggiana** [comment]
Not select file or folder, swipe on left on file or folder for the menu or swipe on right for favorite.

**Comment by sunjam** [comment]
> Not select file or folder, swipe on left on file or folder for the menu or swipe on right for favorite.

**Thanks.  I see, but I find this layout confusing; could it be possible to add that info somehow outside of a first run wizard... let me show you**

![60be9391-b81d-4fac-9dab-63b7bbb20331](https://user-images.githubusercontent.com/1787238/38708699-57553b24-3e6c-11e8-8c87-ca359f9a88ed.jpeg)
**It would be nice to add all of the above items to this folder menu (screen cap below) as well, even if displayed in a sub-folder.**

![6b4032c0-70f0-47fe-9bea-1398d925f7bd](https://user-images.githubusercontent.com/1787238/38708857-0dc60564-3e6d-11e8-9703-812cfdef87ad.jpeg)

![056d433a-1d50-47f3-928e-de0d2e83f3f8](https://user-images.githubusercontent.com/1787238/38708700-576e3c6e-3e6c-11e8-939a-d0866ad3f622.jpeg)
- When adding a share url to a folder or file, it would make sense for that url to be automatically copied to the clipboard.
- What does manually setting an Automatic Upload folder accomplish?
- Once a folder is set to Automatic Upload, how do you turn the Automatic Upload option off again?  There are a lot fewer options on that folder now, too...
![0e4bdebd-0a13-4b5c-8a08-a1dd8bae0da9](https://user-images.githubusercontent.com/1787238/38709094-09debd82-3e6e-11e8-900b-7de9c02aa7e8.jpeg)
![6d4e097c-3489-417e-9ddf-89cd4c65dd9c](https://user-images.githubusercontent.com/1787238/38709092-09ad6ade-3e6e-11e8-93fc-c10603f5d0d4.jpeg)
![bf7e42f1-ae7b-400c-84b4-dec54691e1db](https://user-images.githubusercontent.com/1787238/38709093-09c61516-3e6e-11e8-8bf8-463e251e83ba.jpeg)

- Any possibility for adding [file drop support](https://nextcloud.com/file-drop/) to the iOS client?

**Comment by marinofaggiana** [comment]
is in TODO a restyling , cheers.

**Comment by sunjam** [comment]
*Quick thought*
Has there been any consideration to re-styling how the swipe right and left are assigned in regards to files and folders?

Example: 
Allowing user to change swipe right from **Favorite** to any one of these:
![722050c7-7872-4163-88b4-73e31d1769ca](https://user-images.githubusercontent.com/1787238/38756005-c3333458-3f1c-11e8-986c-a34906998769.jpeg)

You could incorporate the delete option directly into the top of that menu... right at the top where the folder name is displayed, on it’s immediate right.  If you swipe the delete icon left across the folder, you are taken to the usual confirmation...
![17c4c44e-02b3-44e8-b141-475583c3cba0](https://user-images.githubusercontent.com/1787238/38756256-bdbf314c-3f1d-11e8-9a95-9701d033389c.jpeg)

This would now free up Swipe Left to access the three dot menu in a single gesture.
![8b7bf12f-376a-4bdd-96d9-b91eca723a37](https://user-images.githubusercontent.com/1787238/38756278-d2ef45a2-3f1d-11e8-94cf-5aeb6badf479.jpeg)

**Comment by johkoenig** [comment]
Folder sharing is implemented in v3.0.10 (or earlier) with all possible settings.
For swiping options, please open a new ticket.
