### ISSUE TITLE
Feature request: Implement (WebDAV) Search

### ISSUE THREAD

**Issue by barrydegraaff** [nextcloud/ios#557]
Since Nextcloud 12 Nextcloud supports WebDAV Search. It would be nice to have a search box in the app that allows searching through my Nextcloud file store. And would make a great addition to this app.

I am willing to donate between EUR 50-100 if that helps.

Implementing Search is not very hard, I did it a couple of months back in my Zimbra Nextcloud Client.

Even helped with some upstream patches in Nextcloud, so the road should be clear of obstacles.
https://github.com/Zimbra-Community/owncloud-zimlet/ and
https://github.com/Zimbra-Community/owncloud-zimlet/issues/147  (on issues fixed)

**Comment by marinofaggiana** [comment]
Hi @barrydegraaff I don't understand your question, the search is available from several version ...

![simulator screen shot - iphone x - 2018-04-13 at 10 26 03](https://user-images.githubusercontent.com/8616947/38724702-4eb032e6-3f05-11e8-82d2-a300c4ba1ec7.png)

**Comment by barrydegraaff** [comment]
I am so stp*d
