### ISSUE TITLE
iOS 11.3 version of application does not want to build to device

### ISSUE THREAD

**Issue by Undefinable1993** [nextcloud/ios#558]
Hello! I wanted to build the application to an iPad with iOS 11.3 so I had to change my Deployment Target from 11.2 to 11.3 and now it does not want to build to a device. I had to update to the latest Xcode (9.3) before I could change the Deployment Target to 11.3. Ever since then I get a "**dyld: Library not loaded: @rpath/libswiftCore.dylib**" error. 
At the bottom, it also says **"Reason: Incompatible library version: RealmSwift requires version 1.0.0 or later, but libswiftCore.dylib provides version".**
I googled the problem and everywhere it says that I should change the Compatibility Version in Build Settings and I did but it still says the same. I have also tried updating the Realm but still nothing.
I am still quite new to iOS development. Am I missing something?
Thank you in advance.

**Comment by rakekniven** [comment]
@Undefinable1993 Still open?
