### ISSUE TITLE
Share photos from the photo view via link

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#56]
* open the photo view from the bottom menu
* click on a photo
* there is a button to share via the installed apps (FB, Twitter, Instagram, ...) but there is no way to share this photo via a Nextcloud share link

Expected: Also have an option to share via Nextcloud link sharing

**Comment by rakekniven** [comment]
Hello Morris, has that issue been solved? Just trying Testflight version 2.17 0033 and do not find the described solution.

**Comment by MorrisJobke** [comment]
> Hello Morris, has that issue been solved? Just trying Testflight version 2.17 0033 and do not find the described solution.

There it is:

![2017-03-24 17-25-05 3296](https://cloud.githubusercontent.com/assets/245432/24316845/f19986b6-10b6-11e7-9a0b-c27c00e0079f.png)

I did the exact steps that are described in this issue - same app version also from TestFlight.

**Comment by rakekniven** [comment]
Hmm, saturday afternoon after a lot of sun :-)
Still not see the option to share item to nextcloud users or public link ...

**Comment by MorrisJobke** [comment]
Right - I mixed this ticket I'm with the share to Facebook 🙈

**Comment by MorrisJobke** [comment]
@marinofaggiana This one is still missing

**Comment by marinofaggiana** [comment]
Oh ! Yes true

**Comment by rakekniven** [comment]
@MorrisJobke What is the green label for?

**Comment by rakekniven** [comment]
Function works like expected.

**Comment by MorrisJobke** [comment]
> @MorrisJobke What is the green label for?

Some internal stuff for us.
