### ISSUE TITLE
Feature request: Scanning documents with camera (like e.g. DropBox)

### ISSUE THREAD

**Issue by laberkeks** [nextcloud/ios#561]
It would be a great full feature if it would be possible scanning documents with the iOS app like e.g. with the Dropbox app

**Comment by laberkeks** [comment]
Scanbot is not really working for me, because I'm using more then one Nextcloud Servers.
And it's not possible to select the destination for each file.

**Comment by sunjam** [comment]
> Scanbot is not really working for me, because I'm using more then one Nextcloud Servers.

Additional webdav accounts is a pro feature afaik... costs 4.99 iirc

> And it's not possible to select the destination for each file.

Yes it is.
![1c3bc4ad-0c3d-4f5b-a21b-1ca38ad22f65](https://user-images.githubusercontent.com/1787238/39708952-6700a6d4-51cd-11e8-84bc-263b2659ef15.jpeg)

**Comment by veddox** [comment]
You can scan from the iOS Notes app and upload to Nextcloud from there...

**Comment by sunjam** [comment]
@laberkeks I submitted a request for Scanbot to support multiple owncloud amd webdav accounts. [ Please add your voice here to make it higher priority.](https://support.scanbot.io/hc/en-us/requests/new)

> thanks for using Scanbot and reaching out to us. Unfortunately adding multiple accounts at once is not possible yet. I will put this on our feature request list and suggest it to our developers in the next meeting. Note that we try to work this list from top to bottom sorted by number of request, so I can't guarantee you, that we will add this feature anytime soon.

**Comment by medcloud** [comment]
+1 for this feature : it would be great to have such a feature !

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/644

**Comment by rakekniven** [comment]
Hello @marinofaggiana 
The scanning feature sounds very interesting and I gave it a try.

The workflow was not clear for me.
After first launch I had a close sign, but no image.
The plus icon is just there, no header what to top area is.
PDF as export is nice, can we have jpg as well?

**Comment by marinofaggiana** [comment]
@rakekniven do you use iOS 11 or more ?

**Comment by rakekniven** [comment]
Yes, I have 11.4.1

**Comment by marinofaggiana** [comment]
https://cloud.nextcloud.com/s/XZxrLZabirZ6yzD

**Comment by marinofaggiana** [comment]
problem of permission to Photo-camera access ?

**Comment by rakekniven** [comment]
Hooray, great video.
Now I got it.

Already adapted german translation.
Please think of iPhone SE users. 

"Drag below the images for make your PDF document" is too big.
Proposal:
"Drag images down for PDF creation"

**Comment by rakekniven** [comment]
I have been prompted to grant access and allowed it for sure.

**Comment by marinofaggiana** [comment]
ok !! thanks now I change it in "Drag images down for PDF creation"

**Comment by marinofaggiana** [comment]
do you not view a camera image ?

**Comment by rakekniven** [comment]
Great, every sunday I digitize some docs. As soon as jpg will be possible I will happily use this app to do this and provide feedback for sure.
