### ISSUE TITLE
High data usage when idle

### ISSUE THREAD

**Issue by LukeLR** [nextcloud/ios#567]
### Expected behaviour
When the App is in the foreground but no operations are performed, it should transfer nearly no data.

### Actual behaviour
When the App is in the foreground and no operations are performed, a high data usage can be measured (easily 15-20 MB per Minute).

### Steps to reproduce
Use the app on mobile data. Check the mobile data usage for Nextcloud before starting the app. Open the app, and leave it in the foreground for a couple of minutes. Switch back to the settings app using multitasking, and check the data usage for Nextcloud again. In my case, it's severely higher even withoug any operations performed.

### iOS version
iOS 11.3

### App version
2.20.8.00003

### Server configuration

**Operating system**:
```
$ uname -r
4.16.2-2-ARCH
```
**Web server:**
```
$ httpd -v
Server version: Apache/2.4.33 (Unix)
Server built:   Apr  2 2018 12:13:59
```
**Database:**
```
$ mysql --version
mysql  Ver 15.1 Distrib 10.1.32-MariaDB, for Linux (x86_64) using readline 5.1
```
**PHP version:**
```
$ php -v
PHP 7.2.4 (cli) (built: Mar 28 2018 16:40:43) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.4, Copyright (c) 1999-2018, by Zend Technologies
```
**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Comment by marinofaggiana** [comment]
@LukeLR no suspicious traffic found on iOS Nextcloud, please use a proxy for monitor the traffic
