### ISSUE TITLE
Long folder name clutters visual elements

### ISSUE THREAD

**Issue by sunjam** [nextcloud/ios#568]
A longer folder name causes it to be overlapped by the Nextcloud icon in both landscape and portfolio view on iOS 11.
![f8deca7b-89cd-48a2-bc8c-4dd6e2fbacc6](https://user-images.githubusercontent.com/1787238/39251674-bdc1682e-4858-11e8-93f8-4c714a573aea.jpeg)

**Comment by rakekniven** [comment]
@jancborchardt Should the name be shortened like "Mystery Box ... bits"?

**Comment by sunjam** [comment]
@rakekniven 
_Mystery Box ... bits_ next to **...** menu could also be confusing.

**Comment by jancborchardt** [comment]
It should be middle ellipsizing just like we do everywhere else. In addition, also activating the reduction of character spacing so we get a bit more space first. @marinofaggiana

**Comment by rakekniven** [comment]
@marinofaggiana Will you fix this for v2.20.0 ?

**Comment by marinofaggiana** [comment]
mmm I don't have this overlapped ... @sunjam please more info, thx

![schermata 2018-07-24 alle 10 18 41](https://user-images.githubusercontent.com/8616947/43125658-f8b91c6a-8f2a-11e8-9301-9a00b29ada31.png)

**Comment by rakekniven** [comment]
Could not reproduce it as well.

![2018-07-24 12-10-06-0958](https://user-images.githubusercontent.com/2069590/43134994-329f4986-8f44-11e8-8e2e-5a71e2e94125.png)

**Comment by rakekniven** [comment]
Closed due to inactivity.
