### ISSUE TITLE
User information screen

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#57]
* iOS version of https://github.com/nextcloud/android/issues/554
* server API can be found here: https://github.com/nextcloud/server/pull/3232

There should be a view in the iOS that holds all the user information available on the server.

Maybe the best place for this is in "Settings" -> "Cloud Account". There is already a proposal of how this looks on the Android side, maybe we adopt this for iOS:

![device-2017-02-08-231317](https://cloud.githubusercontent.com/assets/1315170/22759968/bce450ce-ee54-11e6-8d90-0ae9a61dbef3.png)

cc @nextcloud/designers for ideas how to do this. maybe @MariusBluem also have a nice idea how this could look like or has examples of how other apps handle this.
  

@marinofaggiana Or maybe you have an idea for this already in mind :)

**Comment by jancborchardt** [comment]
Interface-wise it could be pretty similar to the Android one. Of course the list should be done with iOS default list elements. :)

**Comment by MorrisJobke** [comment]
For reference: This is how the default iOS contact looks like:

![2017-02-13 10-47-53 2612](https://cloud.githubusercontent.com/assets/245432/22892970/f74df19c-f1d9-11e6-9176-85b0adda482b.png)

I would design it likewise

**Comment by jancborchardt** [comment]
Awesome. Yep, we should just do it exactly the same.

**Comment by MorrisJobke** [comment]
Implemented:

![2017-02-23 21-31-28 2720](https://cloud.githubusercontent.com/assets/245432/23289594/722c1f86-fa10-11e6-8859-fc6dc6a1dee7.jpg)
![bildschirmfoto 2017-02-23 um 21 31 54](https://cloud.githubusercontent.com/assets/245432/23289593/7229cb8c-fa10-11e6-935b-c0cd34064755.jpg)

**Comment by MorrisJobke** [comment]
One followup #94

**Comment by jancborchardt** [comment]
In the future we will need the proper full-size layout too (like you posted in https://github.com/nextcloud/ios/issues/57#issuecomment-279449547 @MorrisJobke) because you will be able to see other people’s profiles.

Just FYI @marinofaggiana
