### ISSUE TITLE
File Document Provider Extension V 2.21.0 - TestFlight

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#570]
Comment here for issue with the integration of Nextcloud with iOS Files : 

![simulator screen shot - iphone x - 2018-05-04 at 12 25 36](https://user-images.githubusercontent.com/8616947/39623561-4474b332-4f96-11e8-898c-3ded46851580.png)

**Comment by thoschl** [comment]
Fantastic Work! Thank you very much. I found one issue: When trying to create a document from Pages, Numbers or Keynote I see a Error Message "Der Vorgang konnte nicht abgeschlossen werden. (com.apple.DocumentManager-Fehler 1."

**Comment by marinofaggiana** [comment]
Thanks @thoschl it's already in the bug list

**Comment by manches** [comment]
HI, another bug.

When you tray to save something, like a photo and you press "save to files", you select a photo and save it on the nextcloud folder and it should close everything after uploading, but it stays on the screen that ask you to select to upload somewhere and you have to cancel to go back.

**Comment by marinofaggiana** [comment]
Yes @manches , true, thanks, this issue is connected with the (com.apple.DocumentManager-Fehler 1)  for now I don't find a solution 👎

**Comment by Zegorax** [comment]
New bug : 

If you go to an app (Let's say Pages, Numbers, Lori Pro, etc etc) the app can't create a new file.

**Comment by marinofaggiana** [comment]
Soon next build (13/14) with several bugfix and improvements, a thanks a to Ziqiao Chen Engineer of Apple for help !

**Comment by thoschl** [comment]
Almost perfect. I created a Pages Document in Pages-App. A File "leer.pages" was created. I tried to rename it into "works.pages" but Files-App shows still "leer.pages". Nexcloud-App itself showed "works.pages". I decided to delete the document in Nextcloud-App -> worked. But Files-App does neither refresh the name nor deleted the file.

**Comment by Zegorax** [comment]
I still have a problem.

If I use the app Lori Pro, I can't create any document. Can someone investigate this ?

**Comment by Zegorax** [comment]
Is it possible to look into this ?

**Comment by marinofaggiana** [comment]
@Zegorax , sorry I don't have this App

**Comment by marinofaggiana** [comment]
@thoschl try the new build 15, thanks

**Comment by Zegorax** [comment]
The app is free, can you test it ? That's the only thing that prevents me from using Nextcloud with my scholar cloud

Cordialement, Luca Verardo

**Comment by marinofaggiana** [comment]
@Zegorax I have look the file and this is not compatible with Nextcloud format (Dropbox as well ... ), Lori Pro create a packet (directory) and not a file ... sorry.

**Comment by Zegorax** [comment]
Hmm, that's annoying :(
 Is there a workaround or a fix that could be applied in the future ?

**Comment by marinofaggiana** [comment]
No, this format is not compatible with "other" Cloud except iCloud Drive.

**Comment by marinofaggiana** [comment]
@rakekniven version closed. thanks a lot for your work.

**Comment by rakekniven** [comment]
Release is out.
