### ISSUE TITLE
Feature request: PDF Annotation on top of PDF.js

### ISSUE THREAD

**Issue by GithubWingi** [nextcloud/ios#572]
Hi,

I'm kind of looking for a convenient way to get annotations on my nextcloud files, and I've came to the conclusion that an application intagrated with the web interface would be the most user friendly way to do so.

Do you plan any way to get PDF fiels opend the way they are at the moment (just like with pdf.js inside of browser) with another tool that would enable the annotations to happen ?

Thanks a lot for your insights !

Sorry I just realised this is in the IOS branch, when I should have posted it in the server ? section ... I'm not sure how to delete/reassign this post.

**Comment by rakekniven** [comment]
This better fits in server. 
Currently GitHub offers no way to move issues to other repositories.  Please file a new one at server.
Will close this here.
