### ISSUE TITLE
Filter files by "Activity", "Shared", "Favorites"

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#58]
We maybe should here as well look into the activities view, because this is the only way, how an external app can access this information.

The idea of this is to have a common view of the recent actions that happened to your files/nextcloud account.

@jancborchardt already did a rough mockup of this view:

![img_20170124_113357](https://cloud.githubusercontent.com/assets/925062/22245246/47e67ea4-e22f-11e6-99ba-a2d21fc4ae3b.jpg)

@jancborchardt Should this be the same on iOS? I think so.

@marinofaggiana What do you think?

@karlitschek @oparoz Does that make sense?

@nextcloud/designers @mario Feel free to comment on this as well :)

**Comment by MorrisJobke** [comment]
To get an understanding how this maybe look like check out the activity app:

![bildschirmfoto 2017-02-05 um 17 04 38](https://cloud.githubusercontent.com/assets/245432/22630770/3d221a92-ebc5-11e6-8fd6-80a2e9f15c95.png)
![bildschirmfoto 2017-02-05 um 17 05 07](https://cloud.githubusercontent.com/assets/245432/22630771/3d36c5b4-ebc5-11e6-93e7-a90fe8ff54a5.png)


@jancborchardt Or am I wrong here? The idea was to bring the activity stream to the app, right?

**Comment by marinofaggiana** [comment]
Yes for me it's but, [https://github.com/nextcloud/activity/tree/master/docs](url) we are too far behind ......

**Comment by MorrisJobke** [comment]
> is not possible !

What does this mean? Not possible within the time we have?

**Comment by marinofaggiana** [comment]
@MorrisJobke ping i am ready for activity API ... please where is the correct Documentation ?

Thanks

**Comment by MorrisJobke** [comment]
> @MorrisJobke ping i am ready for activity API ... please where is the correct Documentation ?
> 
> Thanks

@mario What API do you use?

@nickvergessen Is there a public activity API?

**Comment by marinofaggiana** [comment]
@mario @nickvergessen ping ... API ! please.

**Comment by nickvergessen** [comment]
> The documentation is here: http://lukasreschke.github.io/OpenCloudMeshSpecification/#activity

As per email from 24th february...

**Comment by marinofaggiana** [comment]
yes.

**Comment by marinofaggiana** [comment]
i want crate the interface as this :

![3d36c5b4-ebc5-11e6-93e7-a90fe8ff54a5-1](https://cloud.githubusercontent.com/assets/8616947/23518659/79f792a4-ff74-11e6-850b-19c60ef4ee8b.png)

but the API is insufficient ... for example this is a record : 

FILE : /Photos/2017/03/2017-03-01 15-39-09 4056.jpg
LINK : https://cloud.xxxx.com/index.php/apps/files/?dir=/Photos/2017/03
SUBJECT : **You created** Photos/2017/03/2017-03-01 15-39-09 4056.jpg, Photos/2017/03/2017-03-01 15-43-10 4057.jpg, Photos/2017/03/2017-03-01 18-52-05 4058.jpg **and** Photos/2017/03/2017-03-01 19-59-41 4059.gif

😭

**Comment by MorrisJobke** [comment]
> @MorrisJobke i think, for this version, only text without images ...

Yes. Text is enough. The images needs to be fetched via the previews endpoint I guess.

**Comment by MorrisJobke** [comment]
> Yes. Text is enough. The images needs to be fetched via the previews endpoint I guess.

@mario @rullzer How to access the previews? How does the android app does it?

**Comment by mario** [comment]
Example:
http://mario.localhost/nextcloud/index.php/apps/files/api/v1/thumbnail/512/512/images.jpeg

Where last part is remote path to an image. Obviously 512/512 is the size of the image.

**Comment by marinofaggiana** [comment]
Thumbnails is't the problem, the problem is the file list in the subject...

**Comment by mario** [comment]
I am not sure I understand entirely? @MorrisJobke ?

**Comment by marinofaggiana** [comment]
This API required a new design , now it insufficient. For this first version only text without type of activity, thumbnail etc.

**Comment by mario** [comment]
More important thing: You need to have action buttons in there.

**Comment by MorrisJobke** [comment]
> This API required a new design , now is insufficient. For this first version only text without type of activity, thumbnail etc.

Why? It is already sufficient for the Desktop clients. What is the problem with this from your point of view and what is not accomplishable?

**Comment by nickvergessen** [comment]
Yeah currently only the API that is used by the desktop client is available. it was very few information only. The other API is not completly done.

@mario there are no action buttons on activities, thats notifications...

**Comment by mario** [comment]
@nickvergessen ah yup! :)

**Comment by marinofaggiana** [comment]
![simulator screen shot 03 mar 2017 13 41 06](https://cloud.githubusercontent.com/assets/8616947/23551488/243f89f4-0017-11e7-99f0-8835b4b551e2.png)

**Comment by MorrisJobke** [comment]
> Add API Activity Server log, go to in Control Center (on title bar tab "File" swipe down) then swipe right / left for look Transfer / Activity form.

I guess we need to think about where to place those two items. Because it is not discoverable by now. I would not know that this feature exists, because it's a magic gesture on a random UI Element 🤔

@jancborchardt Ideas where to put this?

**Comment by marinofaggiana** [comment]
it's sufficent a small tutorial .. these features are not essential .. for me ...

**Comment by MorrisJobke** [comment]
> it's sufficent a small tutorial .. these features are not essential .. for me ...

But maybe for others 😉

**Comment by MorrisJobke** [comment]
@marinofaggiana Where can I find the overview of shared files?

**Comment by marinofaggiana** [comment]
do not exists
