### ISSUE TITLE
New 3 dots on cell + Improvements UI UX

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#590]
<img width="373" alt="schermata 2018-06-12 alle 10 39 32" src="https://user-images.githubusercontent.com/8616947/41279687-7954dde2-6e2d-11e8-89f7-17fd7436c88c.png">
<img width="363" alt="schermata 2018-06-12 alle 10 40 02" src="https://user-images.githubusercontent.com/8616947/41279695-7be7d154-6e2d-11e8-908e-c31d6d1eb731.png">
<img width="342" alt="schermata 2018-06-12 alle 10 42 44" src="https://user-images.githubusercontent.com/8616947/41279696-7dd69f4a-6e2d-11e8-9c47-804ed3317ac5.png">
<img width="346" alt="schermata 2018-06-12 alle 10 49 21" src="https://user-images.githubusercontent.com/8616947/41280084-5a0c3eb6-6e2e-11e8-9778-a5a2a50fc136.png">

@jancborchardt :

- image 1 : 3 dots always  gray ?
- image 2 is the result for swipe right ... (remove swipe ... ?)
- image 3 open menu option 3 dots
- image 4 swipe left

Jan, whats do you think ?

BIG image : 

![18-06-12 10-56-49 7418](https://user-images.githubusercontent.com/8616947/41280644-b9d2ffa0-6e2f-11e8-8a48-758c10877775.png)

**Comment by jancborchardt** [comment]
Looking good! :)

- We could now remove the 3-dot-entry from the swipe action. Especially on image 2 it’s obvious that there’s duplication. Swiping then is only a shortcut for Favorite and Delete, both which are accessible via the already visible 3-dot-menu.
- There should be a bit more whitespace between the 3-dots and the link icon. Currently they seem to be squished together. Should line up with the notification and sorting icons in the header?

What do you think @MariusBluem @MorrisJobke? :)

**Comment by MorrisJobke** [comment]
> We could now remove the 3-dot-entry from the swipe action. Especially on image 2 it’s obvious that there’s duplication. Swiping then is only a shortcut for Favorite and Delete, both which are accessible via the already visible 3-dot-menu.

Makes total sense 👍 

I would make it a little bit more transparent, because currently it's too intense gray IMO. But beside that looks good 👍

**Comment by marinofaggiana** [comment]
Thanks guys ... work in progress

**Comment by rakekniven** [comment]
@marinofaggiana Is this issue done? You referenced it to milestone. Release is done and issue is open.
Please update information

**Comment by marinofaggiana** [comment]
yes, done.
