### ISSUE TITLE
Upload "+" Button Floating Mid-Screen in iOS 12

### ISSUE THREAD

**Issue by nickian** [nextcloud/ios#592]
Not sure if the current version is supposed to support iOS 12 yet, since it's still in beta right now, but when loading up NextCloud, the upload "+" button in the middle is floating in the middle of the screen and is not clickable.

![img_0d5935f2ced6-1](https://user-images.githubusercontent.com/590678/41449703-eb444e58-701f-11e8-81d4-a1732a04031d.jpeg)

**Comment by marinofaggiana** [comment]
mmm Nice !!
