### ISSUE TITLE
Nextcloud icon

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#597]
@jancborchardt  can you help me ? :-) 

<img width="584" alt="schermata 2018-06-21 alle 16 49 51" src="https://user-images.githubusercontent.com/8616947/41726819-3d947928-7573-11e8-822e-396a2298ac70.png">

**Comment by jancborchardt** [comment]
Yes – the proper icon with the bigger background is at https://github.com/nextcloud/promo/blob/master/nextcloud-icon-background.png
Source SVG at https://github.com/nextcloud/promo/blob/master/nextcloud-icon-background.svg

![](https://raw.githubusercontent.com/nextcloud/promo/master/nextcloud-icon-background.png)

**Comment by rakekniven** [comment]
Added milestone. This looks like an easy task for you @marinofaggiana 
Feel free to remove milestone assignment if it does not fit in your scheduel.

**Comment by rakekniven** [comment]
@marinofaggiana Is this done?

**Comment by rakekniven** [comment]
Could not find related commit :-(
But it is done.

**Comment by jancborchardt** [comment]
@rakekniven thanks so much for testing! :)
