### ISSUE TITLE
Wrong user agent is used

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/ios#60]
Nextcloud servers assume the the iOS app uses a user agent that matches the following Regex:
https://github.com/nextcloud/server/blob/d907666232468503ab6ed2bdac44b6500be2beb6/lib/public/IRequest.php#L79-L79
```php
const USER_AGENT_CLIENT_IOS = '/^Mozilla\/5\.0 \(iOS\) ownCloud\-iOS.*$/';
```

But it seems like the user agent was changed to "Nextcloud-iOS":
https://github.com/nextcloud/ios/blame/47107a9116e162701a38bed69999efe0528abd7c/iOSClient/Utility/CCUtility.m#L382-L388

This means that the app broke the server's compatibility. We can of course adjust the user agent regex, but please don't change it anymore without notifying us.
I also thought that we talked about this in the beginning, but maybe that was android only.

**Comment by marinofaggiana** [comment]
I knew not @nickvergessen, put in back ownCloud ?

**Comment by nickvergessen** [comment]
When was this changed?

**Comment by marinofaggiana** [comment]
mmmm same version ago

**Comment by nickvergessen** [comment]
Well since we also need to fix the server for those versions that have been released in the meantime, you can also just leave it I guess. Just remember to always notify us when this is changed in the future. Maybe you can add a warning into the source code.

**Comment by marinofaggiana** [comment]
ok, for me it's the same 😄
