### ISSUE TITLE
Some design issues

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/ios#605]
1. Grey backgrounds (as seen in stock iOS-applications and Nextcloud Talk) - maybe you can sit together with @Ivansss & create a standard overview-page which is working everywhere...

2. Icons should be not black - they should be greyed a bit (as seen in the screenshot of Nextcloud Talk)

**Nextcloud Talk:**
![img_2851](https://user-images.githubusercontent.com/19711361/41906640-aada76a8-793e-11e8-8abc-723e4979238d.jpg)
**Nextcloud Files:**
![img_2850](https://user-images.githubusercontent.com/19711361/41906641-abebf56c-793e-11e8-9483-682ef59a1446.jpg)

3. Additional icons on file options (Share, Rename, ...) should be greyed too and not in the theming color (or Nextcloud blue); The favorite star should be in the star-color of course 😉 

![img_2852](https://user-images.githubusercontent.com/19711361/41906783-1dc3de52-793f-11e8-9d24-9c198932ffb2.jpg)

As discussed with @jancborchardt and @Ivansss

**Comment by MariusBluem** [comment]
4. File-icons are blurry

![img_2853](https://user-images.githubusercontent.com/19711361/41907500-5fbe0984-7941-11e8-95a5-8a276825a6a0.jpg)

**Comment by jancborchardt** [comment]
Additional:

- Delete icon should be last in list, and also delete-red
- The rows are not high enough, or the layout changed from before? File name and grey info below are squished together too much
- "Folder for automatic upload" should not be shown for every single folder, but rather in the "Photos" section (or even Settings)

**Comment by marinofaggiana** [comment]
Do you like ?
![schermata 2018-06-27 alle 10 09 12](https://user-images.githubusercontent.com/8616947/41961303-67554dea-79f2-11e8-9a21-dcd2cc85caec.png)

**Comment by MariusBluem** [comment]
Star should be yellow, or not? This is not iOS standard, right?

**Comment by marinofaggiana** [comment]
I don't like ... red, blue, yellow, gray ...

**Comment by marinofaggiana** [comment]
@jancborchardt 

<img width="370" alt="schermata 2018-06-27 alle 14 48 41" src="https://user-images.githubusercontent.com/8616947/41974805-4094e39c-7a19-11e8-9a9d-e23351cd0357.png">

**Comment by marinofaggiana** [comment]
@jancborchardt @MariusBluem new plus button : 

![simulator screen shot - iphone x - 2018-06-28 at 12 21 20](https://user-images.githubusercontent.com/8616947/42028869-e1043abc-7acd-11e8-854c-ddc736203aa2.png)

**Comment by jancborchardt** [comment]
Yay, everything looks much better @marinofaggiana, great work! :) (Sorry for late reply, was out of office last week.)

**Comment by MariusBluem** [comment]
- [ ] grey in "+ Add file" is not the same as in files details settings
- [ ] remove "Folder for autoupload" since this should be setted in media-section and not in files-view

@jancborchardt

**Comment by rakekniven** [comment]
Splitted it and added open items to another issue. Release is out.
