### ISSUE TITLE
Version 2.22.0 - TestFlight

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#607]
First build 0/6

- Nextcloud iOS and Apple Files App now are totally integrated !! Nextcloud iOS use the same archive of Files.

<img width="1002" alt="schermata 2018-07-02 alle 12 11 41" src="https://user-images.githubusercontent.com/8616947/42158586-27aec1aa-7df1-11e8-8add-01e8676e0326.png">

Why this is important ?? Read this post :  

<img width="1122" alt="schermata 2018-07-11 alle 11 36 22" src="https://user-images.githubusercontent.com/8616947/42563663-1602ddb4-84ff-11e8-879f-b59cc59177fc.png">

- Rewrite the queue for download & upload, now more flexible and integrated in Apple Files App
- Queue upload : now are visible all new files in "wait to upload" state
- Improvements UI/UX
- New button and progress and text for download/upload as Apple Files App

<img width="339" alt="schermata 2018-07-02 alle 12 46 54" src="https://user-images.githubusercontent.com/8616947/42160020-0cc41c46-7df6-11e8-9390-29e8a5fa95a3.png">

- **New gesture : do you want cancel all transfers ? long press on "Stop button" in a transfer.**
- In Auto Upload if already exists the file, the file is skipped 
- In Copy/Paste if already exists the file the new file is renamed with progressive number 
- Several small improvements & bugfix

**Comment by marinofaggiana** [comment]
Build 7

- Improvement Photo view 

<img width="584" alt="schermata 2018-07-02 alle 15 06 54" src="https://user-images.githubusercontent.com/8616947/42165903-b5c53326-7e09-11e8-8d71-0a578f5ca98b.png">

**Comment by marinofaggiana** [comment]
@tobiasKaminsky news for Photo View

**Comment by maprambo** [comment]
When holding a file or folder in Files, the menu with the clipboard shows a „Custom Action“, which opens a weird view.

**Comment by marinofaggiana** [comment]
@maprambo can you post a screenshot ?

**Comment by marinofaggiana** [comment]
Build 7

- Improvements "Photos" view with improvement delete image/video 

<img width="581" alt="schermata 2018-07-02 alle 15 10 12" src="https://user-images.githubusercontent.com/8616947/42279123-11b9c374-7f9d-11e8-897d-6a234875f648.png">

**Comment by marinofaggiana** [comment]
@tobiasKaminsky (for you)

**Comment by rwat1** [comment]
@marinofaggiana a bug report....just updated to 2.22.0 (7), now in Photos tab, is says: "Search in Progress..." > "No photos or videos uploaded yet".  Back in 2.22.0 (6), I did not have this problem and could see all photos. Now in 2.22.0 (7), I cannot see any Photos in Photos Tab.

Also, I really really liked the Transfers view, why did you get rid of it? Noooo.... that's like a step backwards.

**Comment by marinofaggiana** [comment]
@rwat1 
(1) clear cache ?
(2) yes thx fix soon
(3) it's in work in progress, be patient this is a beta non a stable version ;-)

> TODO : Rewrite Activity View with the transfers integration

**Comment by marinofaggiana** [comment]
Build (8)

- Fix view 
- Fix new Photos view

**Comment by NoName805** [comment]
Any idea make upload queue list back so I can restart the jobs when some  tasks got stuck.

**Comment by marinofaggiana** [comment]
Build (9)

- small UI/UX
- improvements Upload routine

**Comment by marinofaggiana** [comment]
Build (10)

- Bugfix
- Transfer view again available

**Comment by marinofaggiana** [comment]
Build (11)

- small UI/UX fix
- fix show toolbar for external sites

**Comment by frake65** [comment]
It‘s likely a nice-to-have, but with larger pics I had the issue, that I can neither cancel the download nor have it going to the background, but must wait for the file to complete. - sometimes annoying.

**Comment by marinofaggiana** [comment]
@frake65 why not ? touch inside the Stop icon ...

**Comment by frake65** [comment]
Which icon? On Iphone X I only see a blue square with the slowly filling circle inside pn white background - no other icons or menu (photos area)
Touching the square does not make any difference...

**Comment by marinofaggiana** [comment]
https://cloud.twsweb.it/index.php/s/ekLH5BrcE2GaaAW

Stop download ( touch inside the gray square )

**Comment by marinofaggiana** [comment]
Build (12)

- Improvements function: delete (speeded)
- Modify setting favorite: now you do not need to download the file

**Comment by marinofaggiana** [comment]
Build (13)

- Add select All

**Comment by rakekniven** [comment]
Not possible to edit md files with b13

Also creating a file called "test.md" is uploading file "test.txt"

**Comment by rakekniven** [comment]
No, I am using Testflight

**Comment by rakekniven** [comment]
Good catch. You are right.

**Comment by JJ-OpusVL** [comment]
I'm testing b12 in TestFlight, using the Pretext markdown editor (https://itunes.apple.com/us/app/pretext/id1347707000?mt=8) and have found a couple of errors using the document picker directly in iOS apps.

**Cannot create new files directly from an app**

1. Open Pretext
2. Navigate to a Nextcloud folder
3. Click "Create Document"
4. Enter a filename and click "Create"
5. Add text to the file and click "Close"
6. The new file is **not** uploaded to Nextcloud
7. File size is shown as "Zero KB"
8. Opening the file gives the error "The file doesn't exist"

This problem also occurs from other apps using the iOS document picker, e.g. Textor and IA Writer.


**Editing an existing file gives an error after closing**

1. Open Pretext
2. Locate an existing file
3. Open the file and make changes
4. Click "Close"
5. File changes are saved to NextCloud as expected
6. File manager display shows "Content Unavailable - The folder contents could not be displayed because of an unknown error - Try again"
7. Clicking "Try again" displays the folder contents correctly

**Comment by marinofaggiana** [comment]
@JJ-OpusVL thx for your report, I don't know "Pretext markdown editor" but several App use a compress format for save their data, the issue is that this "compress format" it is seen as Directory and in not compatible with Nextcloud but is a iCloud format compatible.

**Comment by JJ-OpusVL** [comment]
@marinofaggiana thanks for your reply. The file format is plain text / markdown (.txt and .md). I have found the same issue with other applications that also try to create plain text files.

**Comment by marinofaggiana** [comment]
Build 14

- bugfix

**Comment by JJ-OpusVL** [comment]
@marinofaggiana I've re-tested using previous builds, and found that creating a new file from an app's document picker was working in 2.21.3.

**Comment by marinofaggiana** [comment]
Oh ! The name of app?

**Comment by marinofaggiana** [comment]
Build (15)

- Upload and/or auto upload photos new option : maintain original filename #619

**Comment by JJ-OpusVL** [comment]
@marinofaggiana I've tested with two different apps with the same result:

- Textor 
https://itunes.apple.com/app/textor/id1330406995?mt=8&at=1010lII4
- Pretext 
https://itunes.apple.com/app/pretext/id1347707000?mt=8

**Comment by marinofaggiana** [comment]
Build (16)

- Fixed File Provider Extension : creation new document. ( @JJ-OpusVL please test :-) )
- Fixed minor issue

**Comment by JJ-OpusVL** [comment]
@marinofaggiana Works perfectly now, thank you!

**Comment by marinofaggiana** [comment]
No @JJ-OpusVL thanks a lot for your support !!

**Comment by marinofaggiana** [comment]
Build 17

- Improvement UI/UX
- Improvement download file for offline signed as favorite

**Comment by michaelnew** [comment]
@marinofaggiana do you have any open spots for Testflight testing? I was a tester in the past but I think I've been removed from the list. Email is mikenew12@gmail.com

Sorry if this isn't the right place to ask. I couldn't find anywhere that seemed more appropriate.

**Comment by marinofaggiana** [comment]
Build 18 

- Several bugfix & Improvements

**Comment by rakekniven** [comment]
@marinofaggiana Your descriptions is way too general.  

> Several bugfix & Improvements

What to test for us?

**Comment by marinofaggiana** [comment]
@rakekniven this build fixed several internal bug registered from crash log, using it normally is the best test for me for this build.

**Comment by marinofaggiana** [comment]
Build 19

- Push Notification (try with comments a file or share federated
- New system for look a movie file, now is in streaming thanks to implementation of proxy http ;-)

**Comment by marinofaggiana** [comment]
Build 20

- bugfix
- add filter in "Photos" view for select only Images or only Video

![senza titolo](https://user-images.githubusercontent.com/8616947/43707270-f4c0280a-9967-11e8-8439-b4c13585181b.png)

**Comment by jancborchardt** [comment]
@marinofaggiana if there is a filter for photos or videos in the view, then it should be called "Media".

**Comment by marinofaggiana** [comment]
@jancborchardt sorry "Media" where ? in tab bar ?

**Comment by marinofaggiana** [comment]
Build 21

- Change name tab Photos to Media
- Change UX filter (Media tab)
- small fix

**Comment by marinofaggiana** [comment]
Build 22

- Fix UI/UX iPad
- Remove OpenIn... on "Media"

**Comment by andyxh** [comment]
When trying to view photos folder from files app on iPhone X iOS 11.4.1
![4896bd81-4fe3-47e5-ba9f-e973efe84ffc](https://user-images.githubusercontent.com/24574019/43856124-424fd920-9b0d-11e8-9e41-81d798d982b9.png)

**Comment by marinofaggiana** [comment]
Yes, this is (for now) a limit API of nc and the very low memory available for Files Provider ... I hope soon (NC 14) a new API with the control of result. Thanks for your report

**Comment by andyxh** [comment]
You’re Welcome! & thank you for the quick response.

Sent from my iPhone X

On Aug 8, 2018, at 1:28 PM, Marino Faggiana <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, this is (for now) a limit API of nc and the very low memory available for Files Provider ... I hope soon (NC 14) a new API with the control of result. Thanks for your report

**Comment by rwat1** [comment]
@marinofaggiana 

I'm trying to save space on my phone, but I don't want to "Delete All Cache Files" on my phone because there are some cache files I want to keep, and some I want to delete.

Is there a way to see a list of "Cache files" on NextCloud, like a filter search or list view?

**Comment by marinofaggiana** [comment]
@rwat1  No, not possible. sorry.

**Comment by marinofaggiana** [comment]
Build 23

- Bugfix optimizations photos
- Improvements optimizations photos

**Comment by marinofaggiana** [comment]
Build 24

- fix : preview on cell are now in Aspect Fill (bugfix)

**Comment by marinofaggiana** [comment]
Build 25 ** CLOSE VERSION **

- small bug fix
- remove advanced option : remove image/video after upload (now it is integrate in optimized resolution photo)

**Comment by marinofaggiana** [comment]
@rakekniven 2.22.0 version available in App Store. thanks

**Comment by rakekniven** [comment]
@marinofaggiana Which version will be next? v2.22.1?

**Comment by marinofaggiana** [comment]
yes, very soon for a small fix

**Comment by rwat1** [comment]
Thank you Marino for your hard work! Great job, keep up the good work 👍
