### ISSUE TITLE
Storagelimit is shown as -2 when using external storage app

### ISSUE THREAD

**Issue by ntimo** [nextcloud/ios#608]
### Steps to reproduce
1. Active the external storage App
2. Mount a storage (I only tested webdav)
3. Set the mount point to /
4. Open your iOS Nextcloud App and look at the storage limit

### Expected behaviour
It should show a unlimited max storage like the web version of nextcloud does

### Actual behaviour
It shows -2 here is a screenshot:
![bug](https://user-images.githubusercontent.com/6145026/41924421-43161564-796a-11e8-9718-4fca1b8f3d59.jpg)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Nginx

**Database:**
Mysql

**PHP version:**
7.2.4-fpm

**Nextcloud version:** (see Nextcloud admin page)
13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh installation

**Are you using external storage, if yes which one:** local/smb/sftp/...
webdav mounted to /

**Are you using encryption:** yes/no
yes

### iOS version
11.4

### App version
2.21.3.1

**Comment by marinofaggiana** [comment]
Hi, this is not a issue of iOS, I view only the data from API server ...

**Comment by ntimo** [comment]
Hello,
I already created a issue here: https://github.com/nextcloud/server/issues/10011. But there I was told to create a issue for the iOS app: 
"This is an issue within the iOS app. Thus please report it to the maintainers of that app in its repository: https://github.com/nextcloud/ios"

**Comment by mario** [comment]
@marinofaggiana @ntimo "-2" means that we don't know the available space.

@marinofaggiana the UI should represent this. So this is indeed an iOS bug.

**Comment by marinofaggiana** [comment]
mmmm I am not convinced ... @ntimo can you create a user test for me ? (ios @ nextcloud dot com)

**Comment by mario** [comment]
@marinofaggiana this is how we do it in Android :P

**Comment by marinofaggiana** [comment]
@mario I want lock the API return before modify the code

**Comment by marinofaggiana** [comment]
@mario I think that this is a bug of API Server side for the "quota" field in @"ocs/v2.php/cloud/user", now I have add a check for < 0 but this is not a good job

**Comment by mario** [comment]
@marinofaggiana I don't think so.

    /**
     * Quota return value for a not computed space value.
     */
    public static final long SPACE_NOT_COMPUTED = -1;

    /**
     * Quota return value for unknown space value.
     */
    public static final long SPACE_UNKNOWN = -2;

    /**
     * Quota return value for unlimited space.
     */
    public static final long SPACE_UNLIMITED = -3;

    /**
     * Quota return value for quota information not available.
     */
public static final long QUOTA_LIMIT_INFO_NOT_AVAILABLE = Long.MIN_VALUE;

**Comment by marinofaggiana** [comment]
oh !? @Mario where are this comment ?

**Comment by mario** [comment]
Here you go @marinofaggiana.

https://github.com/nextcloud/android-library/blob/ce0573bb8fb90f301636afe5dd42767e46da0391/src/com/owncloud/android/lib/resources/users/GetRemoteUserInfoOperation.java

**Comment by marinofaggiana** [comment]
No comment.

**Comment by mario** [comment]
You're welcome @marinofaggiana, always happy to help.
