### ISSUE TITLE
s/OWNCLOUD/NEXTCLOUD/ at ios-intro localization files :)

### ISSUE THREAD

**Issue by KB7777** [nextcloud/ios#61]
Here:
https://www.transifex.com/nextcloud/nextcloud/translate/#pl/ios-intro/92030610
https://www.transifex.com/nextcloud/nextcloud/translate/#pl/ios-intro/92030645
https://www.transifex.com/nextcloud/nextcloud/translate/#pl/ios-intro/92030649
https://www.transifex.com/nextcloud/nextcloud/translate/#pl/ios-intro/92030678
https://www.transifex.com/nextcloud/nextcloud/translate/#pl/ios-intro/92030680
https://www.transifex.com/nextcloud/nextcloud/translate/#pl/ios-intro/92030682

Maybe make an up-to-date one? :)

**Comment by marinofaggiana** [comment]
@KB7777 yes !
