### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by khashino** [nextcloud/ios#610]
## compile iOS app error
Hello 

I'm using XCODE 9.4.1
and SWIFT 4.1

when I compile the app I get this error 

error : 
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/behzad/Library/Developer/CoreSimulator/Devices/935932CF-4EC6-4C4E-BAF6-C03C8B234ABB/data/Containers/Bundle/Application/F0A3A321-CF73-421B-99B8-507ACCE7CC2F/Nextcloud.app/Frameworks/RealmSwift.framework/RealmSwift
  Reason: Incompatible library version: RealmSwift requires version 1.0.0 or later, but libswiftCore.dylib provides version 0.0.0
(lldb) 

I Hope U Can Help me

**Comment by marinofaggiana** [comment]
Hi, do you have used the source in Master Branch ?

**Comment by khashino** [comment]
Hi, Yes I Do , Im using Master Branch
