### ISSUE TITLE
Transifex 0%

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#617]
Hi @MorrisJobke ,
I have several issue with transifex for new Strings, can you remove the limit of % of “untranslated” for release always all dictionaries ?

**Comment by MorrisJobke** [comment]
Currently we require 75 % of the strings to be translated. Let me push it to 25%.

https://github.com/nextcloud/docker-ci/blob/master/translations/handleiOSTranslations.sh#L24

**Comment by MorrisJobke** [comment]
I triggered the sync again.
