### ISSUE TITLE
Status of push notifications 

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#618]
What is the status of push notifications on iOS. I don't receive them for this app, but I receive them for the iOS talk app.

cc @marinofaggiana

**Comment by marinofaggiana** [comment]
@mario @Ivansss what's the difference of push notification already present in nc ios ? (what's news ?)

thanks

**Comment by Ivansss** [comment]
what difference you mean @marinofaggiana? between iOS and Android you mean?

**Comment by marinofaggiana** [comment]
Mmmm no perhaps Mario knows

**Comment by MorrisJobke** [comment]
> @mario @Ivansss what's the difference of push notification already present in nc ios ? (what's news ?)

I never got a push notification in my app. I just wonder what is missing from the iOS app to support push notifications?

**Comment by marinofaggiana** [comment]
the push notification it's present from 2017 for (...), now is only commented, tomorrow i leave the comment an recreate the certificate, @mario please send me the info for firebase ... (test)

@MorrisJobke  

https://github.com/nextcloud/ios/blob/9dc95ca531e90cf39501bdeb3af2530baa8ba53f/iOSClient/AppDelegate.m#L40-L42

**Comment by mario** [comment]
I will send you a plist file today @ marinofaggiana. Can you show me message decryption code so I can review it?

**Comment by marinofaggiana** [comment]
Hi @mario 
> message decryption 

On push Notification ?

**Comment by mario** [comment]
Yes

**Comment by marinofaggiana** [comment]
@mario email.

**Comment by marinofaggiana** [comment]
done.
