### ISSUE TITLE
Two labels overlap in portrait mode

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#62]
Label for "cancel" (german word is abbrechen) and "nextcloud" overlap in portrait mode.
Landscape is fine. See attached screenshots.

![2017-01-09 20-00-10 6008](https://cloud.githubusercontent.com/assets/2069590/22864109/94df88ce-f14b-11e6-9ccf-8ce57fd240c1.png)
![2017-01-09 20-00-17 6009](https://cloud.githubusercontent.com/assets/2069590/22864111/981089a8-f14b-11e6-84e8-10d51401e152.png)

**Comment by marinofaggiana** [comment]
OMG @rakekniven ... in not possible change translation ?? the space on bar is automatic.

**Comment by rakekniven** [comment]
For sure I can try to shorten german words ... but I am sure the english will overlap as well on my iPhone 5S.

btw. is it possible to switch app language some how?

**Comment by marinofaggiana** [comment]
no @rakekniven for change app language change language on your iPhone

**Comment by luongthomas** [comment]
I would like to work on this issue.  How do you replicate this (my phone is already in German)

**Comment by rakekniven** [comment]
Hello @luongthomas .
The issue is very old and the client changed a lot. No need to spend attention to it.
