### ISSUE TITLE
Make string plural instead of two strings

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#622]
https://github.com/nextcloud/ios/blob/9dc95ca531e90cf39501bdeb3af2530baa8ba53f/iOSClient/Supporting%20Files/en.lproj/BKPasscodeView.strings#L59

"Try again in %d minutes" = "Try again in %d minutes";

"Try again in 1 minute" = "Try again in 1 minute";

Should be one string on Transifex.

**Comment by marinofaggiana** [comment]
@rakekniven this is a external library ... in future i want replace it.

**Comment by rakekniven** [comment]
So, no change needed.
