### ISSUE TITLE
apple tv app

### ISSUE THREAD

**Issue by lsmith77** [nextcloud/ios#626]
I would like to see an apple tv app, so that I can view photos without the help of an iOS device / airplay. ideally I want to be able to select folders and then get a slideshow of the images.

**Comment by rakekniven** [comment]
Not the focus of this mobile app at the moment.

**Comment by McPringle** [comment]
I have a lot of movies on my Nextcloud and it would be great to use an Apple TV app to watch then without the use of an iOS device.

**Comment by rakekniven** [comment]
This app is for iOS devices. Apple TV Apps are something different. Closing this

**Comment by AnderCrafter** [comment]
I do think it would be a cool idea

**Comment by cryptedbv** [comment]
Bump, this would be something pretty valuable for Nextcloud, as plenty and plenty of people use it to back up their Phone, that includes photos and videos. And there is nothing better than viewing this on a 55/65/77/x inch display in full glory. Anyhow, hope the team would consider this.
