### ISSUE TITLE
Please provide IPA file release to sideload without having to pay Apple

### ISSUE THREAD

**Issue by mailinglists35** [nextcloud/ios#63]
I am not a developer, I don't have access to Xcode to build from source and I would like to be able to install non-paid apps on my phone.
It would be nice if you could release a build IPA file. Then using third party freely available tools like Cydia Impactor I could easily sideload the app on my phone.
Of course the easiest way would be to release the app as free on appstore...

**Comment by mailinglists35** [comment]
> marinofaggiana closed this 3 hours ago

@marinofaggiana thank you for your subtle and silent way of responding to this issue.

**Comment by marinofaggiana** [comment]
ops sorry @mailinglists35 but we do not released IPA

**Comment by Somebodyisnobody** [comment]
Why do you not provide an ipa file?

**Comment by mailinglists35** [comment]
it seems to be free now, though:
  

  
https://apps.apple.com/us/app/nextcloud/id1125420102
  

  

  

  
  

  
  
>

**Comment by Somebodyisnobody** [comment]
Yeah I know but I cannot complete my account details on my Ipas, it's still loading until death so I cannot download it from the Appstore. Because it's an old iPad I applied the cydia-patch and would like to install the IPA via sideload :)

**Comment by migdal-or** [comment]
Please share the previous IPAs. Apples kick their users out of apps because they want us to upgrade to newer and newer hardware and software. I do not want to install newer Apple OSes and waste my electricity in watching bubbles. Please share an IPA available for sideload

**Comment by migdal-or** [comment]
Oh, thank you so much for the info on how to get the app.
You must login to apple appstore on a newer ios device, install the latest app version (and "purchase" for free the app to your account).
Then you are allowed to download the old app version to an outdated device.
I got a 2017 Ipad 10 with (jailbroken) ios 16 which I will NEVER update to the current version because I have zero interest in seeing crippled bubbles and AI slop.
So I have downloaded the nextclouds IPAs and can share them.

**Comment by migdal-or** [comment]
So, if anyone wanna this one, feel free to get it from https://hz.ru-vederko.ru:8083/index.php/s/2iqSebQyLR4wFeR
yes, my self-signed cert.

**Comment by mailinglists35** [comment]
that's not how it works

**Comment by migdal-or** [comment]
> that's not how it works

Please clarify what I could improve?
