### ISSUE TITLE
Too many slides in the welcome slideshow

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#64]
Currently it’s very cumbersome to scroll across all the 10 screens. We should reduce them to 3, like in the Android app.

1. A safe home for all your data (basically like on the website)
2. Your data, your rules (see https://github.com/nextcloud/android/pull/586 )
3. Instant upload

And then directly the log in boxes. cc @nextcloud/ios @eppfel @mabkenar

**Comment by marinofaggiana** [comment]
@jancborchardt help me for make the "text slide" at start ? thanks
