### ISSUE TITLE
Build fails (missing GoogleService-info.plist)

### ISSUE THREAD

**Issue by notmgsk** [nextcloud/ios#642]
The following error occurs when building master in XCode (9.4.1):

> /Users/mgsk/hackery/nextcloud-ios/GoogleService-Info.plist:0: error: reading data: The file “GoogleService-Info.plist” couldn’t be opened because there is no such file.

Any ideas how to fix it?

**Comment by freumichCH** [comment]
You can remove the GoogleService-Info.plist from the "Copy Bundle Resources" in "Nextcloud" project Targets. 

After that you should be able to build the project

**Comment by notmgsk** [comment]
Alternatively you can sign up for a [free firebase account](https://firebase.google.com/docs/ios/setup) which is easy enough. But @freumichCH's solution is better.

**Comment by GergesEid** [comment]
> You can remove the GoogleService-Info.plist from the "Copy Bundle Resources" in "Nextcloud" project Targets.
> 
> After that you should be able to build the project

This solution works for me.

**Comment by sirnacnud** [comment]
This is actually still an issue. If you remove `GoogleService-Info.plist` from Copy Bundle Resources, the app then crashes on launch with:

`*** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'`

**Comment by freumichCH** [comment]
I experience with 3.1.0 the same. 
Could be that FireBase is mandatory now

@sirnacnud Could you please open a new Issue for the 3.1.0 Version?

**Comment by freumichCH** [comment]
> Alternatively you can sign up for a [free firebase account](https://firebase.google.com/docs/ios/setup) which is easy enough. But @freumichCH's solution is better.

Suggestion of @notmgsk does work. Just create a Account for the firebase Console and follow the Guide:
https://firebase.google.com/docs/ios/setup

**Comment by sirnacnud** [comment]
> > Alternatively you can sign up for a [free firebase account](https://firebase.google.com/docs/ios/setup) which is easy enough. But @freumichCH's solution is better.
> 
> Suggestion of @notmgsk does work. Just create a Account for the firebase Console and follow the Guide:
> https://firebase.google.com/docs/ios/setup

Would it be an option to have Firebase disabled for debug builds? I just commented out the `[FIRApp configure]` in the AppDelegate to get around the runtime crash.

**Comment by marinofaggiana** [comment]
please remove GoogleService-Info.plist from project and set the NCBrand disable_crash_service to true
