### ISSUE TITLE
Version 2.22.3 - TestFlight 

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#644]
**Scans Document : required iOS 11**

![18-08-30 14-33-01 9383](https://user-images.githubusercontent.com/8616947/44851819-d038f900-ac61-11e8-8c00-410a8941b8d1.png)

**Comment by marinofaggiana** [comment]
@MariusBluem the landascape mode (for now) is unsupported

**Comment by rakekniven** [comment]
Build 7 is out.
Version closed.

**Comment by andatche** [comment]
I'd be interested in joining the iOS beta testers list please - "andatche" (at) "gmail.com"
