### ISSUE TITLE
Accessibility check with VoiceOver

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#646]
I did a short accessibility check of the app with VoiceOver (you can activate that in settings and test yourself). These uncovered some issues, cc @nextcloud/ios @nextcloud/accessibility:

- [ ] The upload button is unlabeled and has 2 elements (one tabulator, and one button inside). Should only be one element and labeled "Add or upload", of course translatable.
- [ ] In the header, the "Notification" icon label does not seem to be translatable, since it says "notifikation" in German too.
- [ ] The sort button says "navigation controller menu" (also in "Media" section). Should rather be "Sort".
- [ ] In the file list, it is not possible to get to the 3-dot-menu and open it. It should be selectable and have the label "Actions".
- [ ] In the detail view of a file, the "Share" and "Open file" labels do not seem to be translatable? 
- [ ] In the detail view, the "Previous file" and "Next file" buttons are unlabeled and say something like "item arrow right". Rather they should be labeled "Previous file" and "Next file".
- [ ] As soon as the controls vanish, it is not possible to get out of the detail view in VoiceOver mode. You need to close the app and open it again.
- [ ] In "Media", it is not possible to get to the media and open it. Only the headers are selectable. Instead, the media elements should be selectable too and their filename should be read out.
- [ ] In the "More" section, the top only reads the username, and it’s not apparent you can edit accounts there. This is not even apparent when you see the element. We could add a specific entry first in list saying "Accounts". Or a line below the name saying "Account settings".

This is only a first test and there might be more issues. Let us know if you are aware of anything @nextcloud/accessibility. Thanks!

**Comment by jancborchardt** [comment]
Actually the awesome @tyrylu already did a test at https://github.com/nextcloud/ios/issues/621 :) I added my findings there, closing this as duplicate.

**Comment by MarcoZehe** [comment]
Thanks for filing this, @jancborchardt! I recently started using the iOS app and saw most of these issues, too, just hadn't got around to filing them yet. A few pointers:

> As soon as the controls vanish, it is not possible to get out of the detail view in VoiceOver mode. You need to close the app and open it again.

This can be solved by implementing the appropriate method for the VoiceOver Z gesture, or VoiceOver Escape. Alternatively, one could make the item modal and tell users that way that the other elements are hidden and this should be dismissed with the scrub gesture.

A great example that shows many techniques that are also relevant here is [this year's sample app](https://developer.apple.com/documentation/uikit/accessibility/delivering_an_exceptional_accessibility_experience).

More information can also be found [here](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/iPhoneAccessibility/Making_Application_Accessible/Making_Application_Accessible.html#//apple_ref/doc/uid/TP40008785-CH102-SW4).

**Comment by jancborchardt** [comment]
@MarcoZehe sorry for the confusion, I only saw the existing issue after I posted this. Feel free to also post your comment at the issue @tyrylu opened at #621. Thanks!
