### ISSUE TITLE
Feature request : Upload/remove avatar

### ISSUE THREAD

**Issue by sm2017** [nextcloud/ios#647]
There is no option to set/remove avatar in ios client

**Comment by marinofaggiana** [comment]
Hi @sm2017 what's Upload/remove avatar ?

**Comment by MariusBluem** [comment]
> Hi @sm2017 what's Upload/remove avatar ?

The profile picture of the Nextcloud user 😉

**Comment by marinofaggiana** [comment]
@sm2017 the profile pictures is set on Nextcloud Server (image user)

**Comment by marinofaggiana** [comment]
No, it is not remotely imaginable for now :)
