### ISSUE TITLE
Use Nextcloud blue header with white logo and icons

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#66]
Just like in the Android app. It’s #0082c9:
![](https://lh3.googleusercontent.com/Uu96qLj9QWlNeAlEh4Lu14UEcpQi3Wypd8sQTAMPsBDuhHYY_5eNRWSMI6XpnKDS8dc=h900-rw)

@nextcloud/ios

**Comment by jancborchardt** [comment]
Same for the log in screen:
![](https://lh3.googleusercontent.com/2cziehMQcooHzWLxYS2yGpXyQbQ4YcF08hb6QG7D9UfpinLSiLoz3K7pJbz4Htx_GA=h900-rw)

**Comment by marinofaggiana** [comment]
@jancborchardt verify attachment ... 
<img width="714" alt="schermata 2017-02-13 alle 21 44 48" src="https://cloud.githubusercontent.com/assets/8616947/22902532/ab4d68de-f235-11e6-964f-74f39a100dea.png">

**Comment by jancborchardt** [comment]
Strange, they showed for me on desktop. Anyway, it's just screenshots of the Android app, see on the Play store: https://play.google.com/store/apps/details?id=com.nextcloud.client

**Comment by maprambo** [comment]
Just downloaded the new TestFlight v 2.17 (build 00017).
You were absolutely right, @jancborchardt, it looks great!
However, the status bar (with the carrier, battery and so on) has still a black font, while the icons from the Nextcloud app itself are white. I think it'd look better with a white status bar:

![black-old](https://cloud.githubusercontent.com/assets/7558730/23248752/4eac6d3c-f9a1-11e6-950f-93c8e7a00a80.jpg)
![white-new](https://cloud.githubusercontent.com/assets/7558730/23248755/51258eea-f9a1-11e6-8fa6-aadb3299faa1.jpg)

P.S.: my edit doesn't look that great, but I think you get what I mean.

**Comment by marinofaggiana** [comment]
today i test :

`[application setStatusBarStyle:UIStatusBarStyleLightContent];`

and post the capture
