### ISSUE TITLE
Use the Nextcloud file type icons

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#67]
The same ones we use on the server and the Android app:
![](https://raw.githubusercontent.com/nextcloud/screenshots/master/files/filelist.png)

You can get them from the server repository: https://github.com/nextcloud/server/tree/master/core/img/filetypes

cc @nextcloud/ios @marinofaggiana

**Comment by MariusBluem** [comment]
Done with https://github.com/nextcloud/ios/commit/7372cc6b37fd2eb9ece4412b20a760d9c93270d1 💪
