### ISSUE TITLE
Movie thumbnails not appearing in media screen

### ISSUE THREAD

**Issue by Algebro7** [nextcloud/ios#670]
I've upgraded to Nextcloud server 14.01 to get the media folder working on the iOS client, but I've noticed the thumbnails for video files do not show up in the app. Is this intentional or a bug? Photo thumbnails appear normally.

**Comment by marinofaggiana** [comment]
Hi @Algebro7 , please look to Nextcloud Server documentation, this is not a issue on client

**Comment by Algebro7** [comment]
Thanks, I've found the relevant page at https://docs.nextcloud.com/server/14/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=thumbnail#previews in case this confuses anyone else:

```
By default, Nextcloud can generate previews for the following filetypes:

    Image files
    Covers of MP3 files
    Text documents
```
