### ISSUE TITLE
Some design issues - Another part

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ios#673]
Originally posted by @MariusBluem in #605 

- [x] grey in "+ Add file" is not the same as in files details settings
- [ ] remove "Folder for autoupload" since this should be setted in media-section and not in files-view

@jancborchardt

**Comment by jancborchardt** [comment]
Agree with @MariusBluem’s feedback. :)

**Comment by MariusBluem** [comment]
![9c851977-8256-40b0-8c5d-6401c5b0f616](https://user-images.githubusercontent.com/19711361/46487206-bf9b1600-c7ff-11e8-8144-f26f7a343c8a.jpeg)
![6bab37c3-6c48-437f-aa1e-1ec407de8adc](https://user-images.githubusercontent.com/19711361/46487207-c033ac80-c7ff-11e8-9cac-af3bc817e742.jpeg)

**Comment by marinofaggiana** [comment]
The select of Automatic upload folder will be in Settings/Auto upload

**Comment by rakekniven** [comment]
Fixed on Testflight
