### ISSUE TITLE
Use file indicator icons to show if a file has been downloaded

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#68]
Just like we do in the Android app and with the desktop client:
![](https://lh3.googleusercontent.com/1EdoO8bTQIsUinqT__l6hCqR78CUdJ_n8LiOuur_M_JnpKWXQGRgvvTSiqSG_bDiNQ=h900-rw)

@nextcloud/android where are the icons in the Android repo so @marinofaggiana can copy them? :)

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/tree/master/res/drawable
ic_synced is the green one, for example

**Comment by stffabi** [comment]
Seems like this has been implemented with f9c9ca9d2535a4c41dee72cdc4a090a3304dbaa6. Could someon close this issue and attach it to the 2.17.4 milestone?

See also #265

**Comment by jancborchardt** [comment]
Thank you for the note @stffabi! :) Cleanup help is always appreciated!
