### ISSUE TITLE
Feature Request: rotated images before convert to pdf

### ISSUE THREAD

**Issue by bodscho** [nextcloud/ios#687]
If you take pictures in landscape mode and use them for a scanned document, it  would be helpful if it's possible to rotate them before converting into a document (pdf)
[scan 18-10-10 17-37-05.pdf](https://github.com/nextcloud/ios/files/2465386/scan.18-10-10.17-37-05.pdf)

Best regards

**Comment by marinofaggiana** [comment]
Please try the new build in TestFlight 2.22.5 (4)

**Comment by bodscho** [comment]
Works very well, also fixing the crash changing the subfolder
