### ISSUE TITLE
Improve file list layout

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#69]
Currently the file name is very high up and the modified date + file size is very far down. That creates a strange vertical gap.

- [ ] They should be moved closer together.
- [ ] Also, the modified date & file size should be greyed out a bit to take less attention from the file name.
- [ ] The grey background should be removed from the filetype icon (also, the server filetype icons should be used #67)

Similar to how we do in the Android app (also look at Apple Mail and other apps):
![](https://lh3.googleusercontent.com/orsCdCmz0_GuH8VY0w-9Ejchf07ZeAgDUMYg6CYqyAh0zarzCFoTxoezOn_jBbwJpg=h900-rw)

**Comment by jancborchardt** [comment]
@marinofaggiana now that the nice proper filetype icons are used, could you also check this out? :)

**Comment by marinofaggiana** [comment]
done

**Comment by jancborchardt** [comment]
@marinofaggiana really great improvements all around lately! :)

Next hackweek we should look at improving the settings and account switching.

**Comment by marinofaggiana** [comment]
;-)

https://cloud.twsweb.it/index.php/s/oXr9NMq654b59lv

**Comment by jancborchardt** [comment]
@marinofaggiana oh cool! Then I would say from the settings list, the whole "Cloud account" section can be removed and the relevant parts displayed in that new user accounts list. :)
