### ISSUE TITLE
Review UI 

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#695]
Hi,
with the opportunity to implement the Trash (API) I’m reviewing the UI, after 2 years need a modernization … this is the first draft with finally the possibility of switch very quickly the view (List / Grid), this is totally in swift and it will require a lot to be implemented in all views (several are in old object-c) but this is the start !

[In this trash view are 2 image : restore and more for delete the item]

**List :**

<img width="250" alt="schermata 2018-10-16 alle 15 42 39" src="https://user-images.githubusercontent.com/8616947/47021640-1d165780-d15c-11e8-9d05-3fe09968d279.png">

**Grid :** 

<img width="252" alt="schermata 2018-10-16 alle 15 42 48" src="https://user-images.githubusercontent.com/8616947/47021671-2b647380-d15c-11e8-8c95-6e95091bc319.png">

What's do you thing @tobiasKaminsky @MorrisJobke @nextcloud/designers

**Comment by tobiasKaminsky** [comment]
- in second line we have "size, relative/absolute time", eg: 29KB, Jan 9"
	- if time is < 60s, we use "seconds ago", which is shorter
- the revert button has a very large gap. 
- in grid view (on regular files) we hide the buttons, they are only available via long click (which is a common UI pattern on Android). This allows bigger previews.
	- I am unsure what to do on Trashbin (we do not yet have gridview on Trashbin)
- is it possible to move the list vs grid change button to header on top right? Otherwise space is "wasted".

For comparison:

![2018-10-17-150150](https://user-images.githubusercontent.com/5836855/47088172-1fd98100-d21e-11e8-9966-6fd03bee81fb.png) ![2018-10-17-150201](https://user-images.githubusercontent.com/5836855/47088175-1fd98100-d21e-11e8-8aac-9ea2754519ac.png)

**Comment by marinofaggiana** [comment]
News : 

![schermata 2018-10-19 alle 10 43 26](https://user-images.githubusercontent.com/8616947/47209060-b7aaac80-d38f-11e8-961b-6f655934fb01.png)

![schermata 2018-10-19 alle 10 43 38](https://user-images.githubusercontent.com/8616947/47209065-ba0d0680-d38f-11e8-9385-8a3a0817ed52.png)

![schermata 2018-10-19 alle 10 43 46](https://user-images.githubusercontent.com/8616947/47209070-bc6f6080-d38f-11e8-8abc-44f562723fce.png)

![schermata 2018-10-19 alle 10 44 02](https://user-images.githubusercontent.com/8616947/47209074-c002e780-d38f-11e8-91b1-883147f6d09e.png)


@tobiasKaminsky : (is it possible to move the list vs grid change button to header on top right? Otherwise space is "wasted"), this is the news, I want use the space on Navigation Controller for "Program menu") :-)

**Comment by tobiasKaminsky** [comment]
Looks very good.
Cross-posting to https://github.com/nextcloud/server/issues/11902#issuecomment-431294253
@jancborchardt

**Comment by jancborchardt** [comment]
Some more feedback – based on that we should use this view for all other views (not only deleted files) going forward, right?

- The view switching should not take one full row. Remember people are on mobile and content should have most screen space. Instead, on the top right there should be a 3-dot-menu, and possibly one of the entries outside of it (the most used one). The entries are:
  - List view (or "Grid view" if in list view currently)
  - Sort (→ which then opens a menu like this: https://twitter.com/jancborchardt/status/1046778096500834304 )
  - Restore all files
  - Remove deleted files (we never ever call it "trash")

- For images, showing the filename usually makes no sense as it’s something with `IMG_29841` or `12-10-18-14-18-…` or so. That’s why we should do it like on Android and images should get the full space, without title below.

- In Grid view, there’s generally a bit too much space around everything, creating large white gaps. The elements can be a bit closer together.

- In the List view, every row seems to have more whitespace to the top than to the bottom of the text. It should be visually equal.

- Much like in [the web interface](https://github.com/nextcloud/server/pull/11573), in the grid view the controls of a file should not be below the filename, but right next to it.

See the web interface for comparison (it’s not done yet, but we should try to keep things consistent, also with Android – so thanks for starting the discussion! :)
![](https://user-images.githubusercontent.com/14975046/46465926-39181180-c7ca-11e8-874a-bf69396c07e0.png)

**Comment by marinofaggiana** [comment]
Move in server discussion
