### ISSUE TITLE
Automatically set up sync for Calendar and Contacts

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#70]
iOS supports CalDAV and CardDAV natively. If the app notices that the server has Calendar and Contacts installed, we should ask users if they want to have it synced.

Additionally this should be in the settings, just like for the Android app.

cc @nextcloud/designers @nextcloud/ios

**Comment by rakekniven** [comment]
Not possible on iOS AFAIK. Already discussed that a while ago for ownCloud's app. Try to find issue ...

**Comment by rakekniven** [comment]
See https://github.com/owncloud/ios/issues/206 and https://github.com/owncloud/ios/issues/555 
@jancborchardt you have been part of the discussion :-) 

Anyway: Maybe the possibilities changed and I definetely like the idea.

**Comment by MariusBluem** [comment]
What is about integrating the iOS/OS X Autoconfig profiles into the app 🤔 
https://github.com/nextcloud/server/issues/1434

**Comment by MorrisJobke** [comment]
> What is about integrating the iOS/OS X Autoconfig profiles into the app 🤔
> nextcloud/server#1434

That is the way to go afaik.

**Comment by maprambo** [comment]
You could maybe use [this project](https://github.com/andris9/mobileconfig), it's written in js. It's missing CardDAV but maybe that's not a big deal to add as CalDAV is already existing and I don't think the structure used by apple is completely different here.

**Comment by jancborchardt** [comment]
Does any of our @nextcloud/ios people want to dive into implementing this? :)

**Comment by freechelmi** [comment]
That would be very cool indeed, especially for enterprise IOS users who would never enter those ""strange URLs" in their settings

**Comment by jancborchardt** [comment]
@marinofaggiana @Ivansss do you know how this is possible?

Anyone who knows more is also welcome to dive into this! :)

**Comment by marinofaggiana** [comment]
@jancborchardt, yes, is possible programmatically CardDAV account

**Comment by georgehrke** [comment]
@marinofaggiana We are exposing a configuration profile via WebDAV:
`/remote.php/dav/provisioning/apple-provisioning.mobileconfig`

Can your app just import that profile into iOS?

**Comment by tflidd** [comment]
I didn't know this feature and it wasn't documented so far. However regarding setting everything up, it seems pretty complicated especially when you consider 2FA. Are there native ways to implement this (ideally qr code).

Link to documentation issue: https://github.com/nextcloud/documentation/issues/6234

I just found, they manage to use a qr code instead of a link, so you can simply scan: https://www.fastmail.help/hc/en-us/articles/1500000279941-Set-up-iOS-devices-iOS-12- (authentication is still an issue and entering the current password schemes on a smartphone is a pain)

**Comment by marinofaggiana** [comment]
![IMG_B441C9C92EA0-1](https://user-images.githubusercontent.com/8616947/205883959-0b577314-5013-4d2c-bd2c-5b7d4f8ae20f.jpeg)
