### ISSUE TITLE
offline [INTERNAL TEST CLOSE]

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#706]
Add the possibility of set file/directory as available offline + new view "Manage file offline"

**Comment by jancborchardt** [comment]
The new view should probably be called "On device" as it is on Android. :) Maybe best talk to @tobiasKaminsky @AndyScherzinger for coordination?

**Comment by tobiasKaminsky** [comment]
On android we have "on device" which shows all files that are downloaded to the device in the same hierarchical structure. We omit empty folders:
- folder A: no files downloaded -> not shown
- folder B: 1 file downloaded -> show
(same for subfolders)

Available offline will be elimated, as we dicussed with Jan that this is a bit confusing. Manually downloaded files can be out of date, but "keep available offline" files gets synced.

So the new approach is to sync every downloaded file, but keep the conflicts silent:
https://github.com/nextcloud/android/pull/2886
