### ISSUE TITLE
Simplify »Upload / New« menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#71]
Currently clicking the **+** for upload / new folder opens a huge list of things:
![](http://a4.mzstatic.com/us/r30/Purple30/v4/25/82/99/258299c8-6c0c-54d8-de93-510473a9a398/screen696x696.jpeg)

Instead it should only be a small popover with:
- Upload photos or videos
- Create folder
- New note (also useful)
- More … (opens a list or expands the popover with the rest)

That would streamline the experience here.

**Comment by marinofaggiana** [comment]
@jancborchardt look the version in develop

**Comment by jancborchardt** [comment]
@marinofaggiana could you post a screenshot? I don't use macOS so can't test. Or is an iOS beta available via Testflight or similar?

**Comment by marinofaggiana** [comment]
@jancborchardt send me email for add you on Testflight.

**Comment by jancborchardt** [comment]
@marinofaggiana do you need my iCloud email, or normal one? I'm jan at nextcloud ;)

A screenshot would be nice either way so others cam review it too.

**Comment by marinofaggiana** [comment]
The new [+] option without crypto cloud mode.

![schermata 2017-02-14 alle 15 17 05](https://cloud.githubusercontent.com/assets/8616947/22932605/c89ceef8-f2c8-11e6-91d8-b6cf50811e89.png)
![schermata 2017-02-14 alle 15 17 19](https://cloud.githubusercontent.com/assets/8616947/22932607/ca90cfd6-f2c8-11e6-8635-90ec67c74c23.png)

**Comment by jancborchardt** [comment]
@marinofaggiana awesome, this is perfect! :) :tada:
