### ISSUE TITLE
Fetch preview only if dav property has-preview is true

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#715]
I just got the info by @rullzer that there is a dav property
<has-preview xmlns="http://nextcloud.org/ns"/>
which we can use to check if for a file a preview on server exists.

Only then it makes sense to download the preview.

If you are aware of this / use this already, please close.

**Comment by marinofaggiana** [comment]
@tobiasKaminsky no I don't know, where is ?

**Comment by tobiasKaminsky** [comment]
During PROPFIND on files you can also ask for has-preview thin NC namespace.
You then either get true or false back.
And only on true it makes sense to do a call to the server to get the image, though it then still could not work.
For instance a 0b jpg file returns "true" on has-preview, but still would fail to generate a preview.

**Comment by marinofaggiana** [comment]
oh! great, I test now , but from which version of NC ?

**Comment by rullzer** [comment]
Since 11 or so But you can always just request the property. If it does not exist webdav will return it as a 404

**Comment by rullzer** [comment]
And regarding trash. Please submit an issue to the server. With more details (the actual propfind you try to do, the error you get etc).
