### ISSUE TITLE
Comment if you want to join the iOS beta via Testflight – and then please open issues for any problems you encounter :)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#72]
It would be good if all our iOS users can run the Nextcloud beta app through Testflight. :)

@marinofaggiana can you add @LukasReschke (lukas at nextcloud) @MorrisJobke (morris at nextcloud) @karlitschek (frank at nextcloud)?

And maybe also others from @nextcloud/ios @nextcloud/mac want to help testing?

**Comment by marinofaggiana** [comment]
Morris & Frank are already some time ;)

@LukasReschke ?

**Comment by karlitschek** [comment]
already possible :-)

**Comment by jancborchardt** [comment]
This is more intended as an issue to get testers onboard ;)

**Comment by jancborchardt** [comment]
@marinofaggiana awesome! Then also invite @LukasReschke (lukas at nextcloud dot com) and @MariusBluem (marius at lineone dot io)

Anyone else? :)

**Comment by jacboy** [comment]
I'm in - hallo@jakoblicina.de is my Apple ID for TestFlight beta testing!

**Comment by timbru31** [comment]
I'm in, too. `me at timbrust dot de`

**Comment by togglecode** [comment]
hello, I would like to be a tester too.
office@huemer-dc.com

**Comment by marinofaggiana** [comment]
ok boys i add you for next beta 😄

**Comment by phedlund** [comment]
peter at peterandlinda dot com would like to join as well.

**Comment by marinofaggiana** [comment]
Yes, but please, comments,  bugs, problems etc. send report :smile:

**Comment by maprambo** [comment]
I'd like to join as well (`matthesp at t-online dot de` is my apple id)
The issues should be reported here in this GitHub repo, shouldn't they?

**Comment by jancborchardt** [comment]
@maprambo @phedlund @togglecode @timbru31 @jacboy thanks for being part of the iOS team! Please use and test the app and report issues in this Github repository. :)

Also added you to the @nextcloud/ios team. You are very welcome to help review the pull requests too: https://github.com/nextcloud/ios/pulls :tada: :heart_eyes:

**Comment by maprambo** [comment]
I don't want to bother anyone here, but I still got no invitation 😅

**Comment by marinofaggiana** [comment]
@maprambo  I add you now 😸

**Comment by maprambo** [comment]
Thanks!

**Comment by timbru31** [comment]
@marinofaggiana Sorry to bother, but could you re-send the TestFlight invitation? Successfully managed to strip the HTML off the mail and trash is already emptied :/

**Comment by marinofaggiana** [comment]
yes @timbru31 , new version beta today, new message

**Comment by Dirk23** [comment]
Is it still posible to join?
dirk at diehildebrands dot de

**Comment by marinofaggiana** [comment]
Hi @Dirk23 , sure !

**Comment by timbru31** [comment]
Haven't found an new invite in my postbox yet, too. Could you resend it? ☺️

**Comment by marinofaggiana** [comment]
@timbru31 write your email here please

**Comment by timbru31** [comment]
Still `me at timbrust dot de` :P

**Comment by marinofaggiana** [comment]
**Boys are you ready for the release public version ??**

**Comment by maprambo** [comment]
So all favorites are synced, without opt-out. I wanted to open a new issue for that but didn't manage to do that so far, I'll do it now.

**Comment by timbru31** [comment]
I'd like to test that #109 is just a bug on my end - exposing the password database which is synced in the root folder without a password/TouchID is a blocker IMHO

**Comment by marinofaggiana** [comment]
@timbru31 ... exit and ri-create user ?

**Comment by timbru31** [comment]
@marinofaggiana signing out and in again did not help

**Comment by marinofaggiana** [comment]
I don't understand  ... it's very strange ...

**Comment by derkostka** [comment]
I want to test the iOS client also. especially the sharing feature of documents is of interest. I hope 2.17 will come very soon!

**Comment by marinofaggiana** [comment]
@derkostka hi, your email for next beta

**Comment by hus2020** [comment]
@marinofaggiana pls add me to the test flight beta too. my email Id is hus2020@hotmail.com

**Comment by derkostka** [comment]
Hi
sebastian.kostka@gmail.com 

thanks!

**Comment by cal940** [comment]
@marinofaggiana: I would really like to join the beta program.

Apple ID: [carlsin94@me.com](mailto:carlsin94@me.com). I' m already unsing TestFlight some time.

thanks
Carlito

**Comment by emresaracoglu** [comment]
@marinofaggiana Im waiting your invite:)

**Comment by marinofaggiana** [comment]
@emresaracoglu  your email ?

**Comment by emresaracoglu** [comment]
@marinofaggiana hello@emresaracoglu.com

**Comment by marinofaggiana** [comment]
New 2.17.00032 is out !

**Comment by emresaracoglu** [comment]
@marinofaggiana Thanks!

**Comment by cal940** [comment]
Thanks, for adding me to the program. I really like the new beta.

**Comment by DidierLmn** [comment]
@marinofaggiana would it be possible for me to join the iOS beta as well? 
didier [dot] laumen [at] protonmail [dot] ch
Thanks.

**Comment by marinofaggiana** [comment]
@DidierLmn, done.

**Comment by rakekniven** [comment]
New 2.17.00033 is out !

**Comment by ho1ger** [comment]
Hi, I'd like to test as well: drscheme2017@gmail.com

Thx!

**Comment by ligocom** [comment]
hi, ligor.virlan@icloud.com my AppleId to join the IOS beta ...
Thx ,

**Comment by derkostka** [comment]
First feedback: Yesterdays beta flies ! No problems so far, sync is
considerably faster then in the official build. Please release asap :-)

Am 25.03.2017 18:21 schrieb "Ligocom" <notifications@github.com>:

**Comment by jancborchardt** [comment]
@derkostka can you please open a separate issue with more info? :) Thanks

@ligocom @ho1ger @DidierLmn @cal940 @emresaracoglu and everyone else in the program – make sure to please test and open issues if you encounter any. :) Your feedback is very valuable, and that’s why you are in the beta program.

**Comment by digitalknk** [comment]
hello can you please add `Jonathan AT Molina DOT io` :-) thanks!

**Comment by DidierLmn** [comment]
Thanks all, I will report issues when/if I encounter them.

**Comment by robposch** [comment]
I would also be interested to help. Not a developer but I can test new iOS builds if spmebody tells me how to report. :) Apple ID: poschenrieder.robert@gmail.com

**Comment by jancborchardt** [comment]
@robposch awesome! :) To report issues, just go to https://github.com/nextcloud/ios/issues and click »New issue« on the top right (green button) :) Then put in the details of the issue you encountered.

**Comment by haup** [comment]
hi, would like to test the app as well! :) Apple ID: tunkrig@googlemail.com

**Comment by tommyguuuun** [comment]
I'm in for testing, apple id is zanker[.]apple[@]gmail[.]com

**Comment by marinofaggiana** [comment]
New 2.17.00036 is out !

Please HARD test on Automatic Upload

**Comment by emresaracoglu** [comment]
There are 49 photos waiting to be transferred but only one is shown on the screen.

![inked2017-04-05 19-06-08 1381_li](https://cloud.githubusercontent.com/assets/297968/24716030/16ab0910-1a36-11e7-94f5-49af4b08faa4.jpg)

**Comment by marinofaggiana** [comment]
please @emresaracoglu not issue in this thread, take a new  ticket for a new argument.
However this "comportment" of queue 1/1 auto-upload is correct for now.

**Comment by emresaracoglu** [comment]
@marinofaggiana Understood :)

**Comment by derkostka** [comment]
@emresaracoglu , @marinofaggiana : i tested this also. in the past versions all files were uploaded correctly also. It seems that now, i either need to refresh (slide down) or close and re-open the app  to trigger uploading new files. I have once received an error "webdav resource locked", but could not reproduce. I think it came up after multiple concurrent "slide down" actions...

**Comment by marinofaggiana** [comment]
@derkostka not here, please open a new ticket.

**Comment by manches** [comment]
can i join? Apple ID: jlhernangomez@gmail.com

**Comment by wallenium** [comment]
i am already in since a couple of month. Still running the testflight Version only, so Errors will be detected as i use it on a daily base ;)

**Comment by marinofaggiana** [comment]
2.17.00040 Waiting For Review on App Store.

Thanks guys for your extraordinary work !

**Comment by marinofaggiana** [comment]
Close. Open new ticket for TestFlight when is open a new major release.

**Comment by manches** [comment]
Hi, 
With the version 2.17.00040, it crashes in a couple of seconds after opening. There are 5 photos pending to upload
Here is the IPS logs of the crash
https://pastebin.com/Fzn5Pga8

**Comment by emresaracoglu** [comment]
@manches Please open new ticket

**Comment by emresaracoglu** [comment]
@marinofaggiana I sent you an email this morning but I guess you have not noticed yet :) 
Could you send me a new invitation? (emsaracoglu at gmail)

**Comment by marinofaggiana** [comment]
sorry @emresaracoglu this is not possible, the version TestFlight is closed, wait next beta
