### ISSUE TITLE
Logo in Home as theming

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#722]
if is setting select (default) : use_themingLogo: Bool = true

Nextcloud:
<img width="425" alt="schermata 2018-11-13 alle 13 14 12" src="https://user-images.githubusercontent.com/8616947/48412795-0dcbff00-e746-11e8-9df2-e6568faca7ec.png">

Nextcloud iOS:
<img width="373" alt="schermata 2018-11-13 alle 13 13 58" src="https://user-images.githubusercontent.com/8616947/48412810-13c1e000-e746-11e8-8e1f-4ebccad1d0d2.png">

**Comment by rakekniven** [comment]
Works. Nice catch.

**Comment by maprambo** [comment]
For me, a square svg (with multiple colors) gives me just this:

![image](https://user-images.githubusercontent.com/7558730/49544584-75a3de80-f8db-11e8-9091-eed5ffba0958.png)

When scrolling, the logo goes over the edge, too:

![image](https://user-images.githubusercontent.com/7558730/49544636-9d934200-f8db-11e8-9659-eadef3b6b71c.png)

**Comment by marinofaggiana** [comment]
mmm @maprambo , interesting ... can you create a test account for me ... I want to watch if the issue is the SVG conversion library. Thanks

**Comment by wdfee** [comment]
In our case the usual home logo for desktop broswers is quite detailed with name and slogan. this is unreadable and far too small in the app header. Best option would be an extra upload in Nextcloud theming (for e.g. only logo without slogan).
A small hint about the best size would be helpful.

**Comment by rakekniven** [comment]
That's how it goes. People are creative and the story starts :-)

**Comment by marinofaggiana** [comment]
Sorry everyone but for the next version I remove this feature, the library for convert from SVG to PNG is good but not universal good and I have several issue and crash :(

**Comment by cestmoimeme** [comment]
Hi Marino
As @wdfee , I guess the option for an extra upload in Nextcloud theming , png type, could help .
Do you think it could be ok ?

**Comment by marinofaggiana** [comment]
@cestmoimeme this feature is closed. sorry

**Comment by cestmoimeme** [comment]
oups, so sad ... may I help ? what's the problem with the library svg-png ? or may be you just turn this off definitly ;) anyway, thank you for all the job you do !! :)

**Comment by HeyWatchOutDude** [comment]
Any idea if this feature will implemented again?

**Comment by cestmoimeme** [comment]
Same as HeyWatchOutDude](https://github.com/HeyWatchOutDude ... would be great to get that !
