### ISSUE TITLE
Fail open libreoffice documents with OOreader

### ISSUE THREAD

**Issue by jagallas** [nextcloud/ios#728]
The integration of the Nextcloud client with the OOreader reader on IoS devices (iphone / ipad) fails. When you try to open a Libreoffice document (ODT, ODS) through the NextCloud client with OOreader it gives an error that the document has zero size and does not open it. 

Server: NextCloud 13
Client iOS:  NextCloud 2.22.5

**Comment by marinofaggiana** [comment]
Duplicate. I close this. 

https://github.com/nextcloud/ios/issues/304
