### ISSUE TITLE
Ability to add non-encrypted txt note

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#73]
The "Add note" feature which creates and opens a txt file is super handy. It was removed in the beta unfortunately.

Could we add it back @marinofaggiana? Should show up in the "Plus" menu alongside adding folder and uploading.

**Comment by marinofaggiana** [comment]
<img width="278" alt="schermata 2017-02-15 alle 16 02 32" src="https://cloud.githubusercontent.com/assets/8616947/22979909/46f602a6-f398-11e6-97b1-2dc770c96e87.png">
<img width="280" alt="schermata 2017-02-15 alle 16 02 46" src="https://cloud.githubusercontent.com/assets/8616947/22979914/49a96a6a-f398-11e6-85fa-99fde5dc2eb1.png">
<img width="274" alt="schermata 2017-02-15 alle 16 02 56" src="https://cloud.githubusercontent.com/assets/8616947/22979919/4bae74f4-f398-11e6-8542-4ba556d50681.png">

In future, yes, in (main) menu for encrypted mode and not

**Comment by jancborchardt** [comment]
Ah ok, closing this because the feature request for non-encrypted notes already exists at https://github.com/nextcloud/ios/issues/21
