### ISSUE TITLE
Background upload causes never-finished upload

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#736]
* I use the "upload in background" upload of photos via wi-fi
* from time to time it happens that there are pending uploads in the "transfer" section
* expected: they vanish once they are uploaded
* actual:
  * I checked the upload directory on the server and those files are actually uploaded
  * the uploads stop at 100% - they never get removed or get any error
  * I *guess* that this is caused by the automatic upload in the background, because when I try to reproduce this by shooting a photo and checking the transfers then the upload properly finishes

Here is the transfer section (even waiting multiple minutes doesn't change anything and the network is stable):

![img_0342](https://user-images.githubusercontent.com/245432/49084412-ac308800-f24f-11e8-97bd-946415062a9e.PNG)

This is the folder it uploads to (check out the entry below which has the same file name):

![img_0343](https://user-images.githubusercontent.com/245432/49084449-c4a0a280-f24f-11e8-9032-745511920fdf.PNG)

**Comment by marinofaggiana** [comment]
Note for me: redesign  with collectionView
(check read file on server for state != k_metadataStatusNormal)

**Comment by ne20002** [comment]
I have similar problems. Seems as if when an error occured, the files are not tried to be uploaded again. Or, if the number of files ready for upload (first 5 for parallel upload?) are blocked with files with an error, no more uploads are tried at all.

**Comment by veddox** [comment]
Same here as ne20002 (no more uploads due to five erroneous uploads blocking queue). Unfortunately, the rogue uploads also cannot be cancelled, so they've been stuck there for almost two weeks!

**Comment by DrMurx** [comment]
Similar issue for me: there are 5 parallel upload streams, but they upload the same 5 files again and again which is particularly annoying if one of them is a 1 GB video.

I also notice what has been described above: if one of the 5 upload slots has an error, it's stuck and the slot won't be reused.

**Comment by MorrisJobke** [comment]
This is not happening anymore.
