### ISSUE TITLE
2.22.6

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#746]
Hi @rakekniven V. 2.22.6 closed and available on AppStore.

Thanks

**Comment by MorrisJobke** [comment]
@marinofaggiana What is this ticket about? About the tagging? I guess you are referring to 333c2aee8599ce366d17987547c0ab153e883585? 

To add a git tag you can do this:

If you did already other commits to master change to the commit:

```
git checkout 333c2aee8599ce366d17987547c0ab153e883585
```

Then tagging is done via:

```
git tag v2.22.6
git push --tags
```

**Comment by MorrisJobke** [comment]
I aded this tag.

**Comment by rakekniven** [comment]
Hello @MorrisJobke 
This issues are mainly for me to do the release.

**Comment by marinofaggiana** [comment]
@rakekniven :wink:

**Comment by rakekniven** [comment]
Hello @marinofaggiana Just seen there are 10 (!) open issues for this release.
See https://github.com/nextcloud/ios/milestone/41 

Could you please check them?

**Comment by marinofaggiana** [comment]
done.
