### ISSUE TITLE
Share link shows wrong password

### ISSUE THREAD

**Issue by togglecode** [nextcloud/ios#75]
1. Upload a file
2. Share the file with link
3. Set password
4. Press "done"
5. Password will be shown wrong

# Screenshot 1
![2017-02-16_16-53-20_0493](https://cloud.githubusercontent.com/assets/17141698/23029420/bdb62a2e-f46a-11e6-93c0-920f8d9a4437.png)

# Screenshot 2
![2017-02-16_16-53-39_0494](https://cloud.githubusercontent.com/assets/17141698/23029421/bdba0c20-f46a-11e6-86c4-7982489ad80a.png)

**Comment by marinofaggiana** [comment]
yes it's correct, ********************* the password length is hidden

**Comment by togglecode** [comment]
great 👍
