### ISSUE TITLE
Creating empty document not possible

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#753]
* open the iOS app
* click the "+" button
* click "Create new document"
* expected: being able to enter a name and click save
* actual: 
     * error with "Request failed: not found (404)" appears and I have no idea what to do with that
     * once the error is gone and entering a name works, but the "Save" button can't be clicked at all. Only the abort button works.

![img_f5be72a2693d-1](https://user-images.githubusercontent.com/245432/50095243-5c712b00-0215-11e9-9a20-eae2b95b39d4.jpeg)

This is the screen with the non-functional "Save" button.
![img_0432](https://user-images.githubusercontent.com/245432/50095266-6dba3780-0215-11e9-8adc-cd21f0b0ad52.PNG)

@marinofaggiana 

v 2.22.8.10

**Comment by sebastiaanveld** [comment]
Had this issue with CODE 3.x, after updating to CODE 4 RC1 this issue is still there.

**Comment by MorrisJobke** [comment]
Solved for me.
