### ISSUE TITLE
After the file is deleted, the ios11 recycle bin can't see the file, and the android recycle bin can see the file

### ISSUE THREAD

**Issue by 330201818** [nextcloud/ios#762]
After the file is deleted, the ios11 recycle bin can't see the file, and the android recycle bin can see the file
![ios](https://user-images.githubusercontent.com/15013924/50427576-e0e33e00-08e6-11e9-9ea5-84220b1071c1.jpg)
![az](https://user-images.githubusercontent.com/15013924/50427578-e3de2e80-08e6-11e9-93c2-837cf915bb52.jpg)

**Comment by maghog** [comment]
Have the same issue.
Nextcloud Server v14.0.4
iOS Client v2.22.7.4

**Comment by kruthoff** [comment]
Same issue.
Nextcloud server 14.0.4
iOS client 2.22.7
nginx, postgres on raspbian stretch

**Comment by 330201818** [comment]
Can respectable developers answer my questions?

**Comment by marinofaggiana** [comment]
Hi @330201818, can you make me a test account for debug ?

@tobiasKaminsky do you have any idea? I use PROFIND : 

<?xml version="1.0" encoding="UTF-8"?><D:propfind xmlns:D="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><D:prop><D:resourcetype/><D:getlastmodified/><id xmlns="http://owncloud.org/ns"/><D:getcontentlength/><nc:trashbin-filename/><nc:trashbin-original-location/><nc:trashbin-deletion-time/><nc:has-preview/></D:prop></D:propfind>

with this path: https://cloud.test.com/remote.php/dav/trashbin/marino/trash/

**Comment by tobiasKaminsky** [comment]
This is what I tested:

- created a new user on master
- uploaded & deleted a file
- verified it with web ui -> file is shown
- file is shown in android
- file is not shown in iOS
- but I can see "PROPFIND /nc/remote.php/dav/trashbin/up/trash/ HTTP/1.1", so it seems that it is queried, but not correctly parsed/ shown?

This is an example curl request, which also shows the file:

```
curl --request PROPFIND \
  --url http://localhost/nc/remote.php/dav/trashbin/up/trash/ \
  --header 'authorization: Basic dXA6dXA=' \
  --header 'ocs-apirequest: true' \
  --cookie 'ocjycgrudn78=vgovrq3bgraie6rs6ai2sl42ag; oc_sessionPassphrase=oyqxSU8b6n4N8Aj0yfObGeheppYvsdzgMhEkMgHw76nWBRLVRRM%252FZcjxqQ5QHtm3knScFxIKIjCzDasJYhLEYxRsvabseMjOqDSa%252BNSkI%252Fi%252FDrm6cKlWmA4QBr3NtcGI; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true'
```

**Comment by marinofaggiana** [comment]
@tobiasKaminsky tanks, I don't understand... I have make several test with 3 servers without this issue ... can you create an account for me with this issue ? possible ?

**Comment by tobiasKaminsky** [comment]
Unfortunately not. It only happens with latest master for me, but not on my public instance (NC15)
But you can try it on localhost with latest master.

**Comment by tobiasKaminsky** [comment]
BTW: since when is Trashbin supported? @rullzer

**Comment by marinofaggiana** [comment]
14 @tobiasKaminsky
