### ISSUE TITLE
Blue Header-Bar with white Nextcloud Logo

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/ios#77]
Should be blue with white fonts (and logo) instead of white with blue logo... what do you think?

![img_0441](https://cloud.githubusercontent.com/assets/19711361/23037412/866467b8-f486-11e6-9342-52dd69731c64.PNG)

@jancborchardt

**Comment by jancborchardt** [comment]
Yes – duplicate of https://github.com/nextcloud/ios/issues/66 ;)
