### ISSUE TITLE
Simple guide to opening latest iOS nextcloud app in Xcode

### ISSUE THREAD

**Issue by lozflan** [nextcloud/ios#777]
Bit of a newby interested in nextcloud  ...Is there a simple guide to getting the latest iOS nextcloud app (2.22.8) to open successfully in Xcode. Ive changed bundle identifiers in all 4 targets (Nextcloud, Share, File Provider Extension, and Notification Service Extension) to my relevant entries. Updated App Groups, Keychain Sharing, and iCloud in the Capabilities tab of all targets.

Getting various errors ie

Command PrecompileSwiftBridgingHeader failed with a nonzero exit code
‘UICKeyChainStore/UICKeyChainStore.h’ file not found
Failed to emit precompiled header ‘/Users/xxxx/Library/Developer/Xcode/DerivedData/Nextcloud-eugrkvlmneybcoglqlnyvjrkkviv/Build/Intermediates.noindex/PrecompiledHeaders/NotificationServiceExtension-Bridging-Header-swift_35ERPTWM779PL-clang_1K1Q4AEIVYC1Q.pch’ for bridging header ‘/Users/xxxx/Downloads/ios/Notification Service Extension/NotificationServiceExtension-Bridging-Header.h’

**Comment by balusreekanth** [comment]
nextcloud iOS project uses carthage   to build and copy dependencies  easily . Check dependencies  in  Carthage/Build/ directory in project directory.  It should contain all  frameworks like  UICKeyChainStore.framework. Under  Build Phases-> RunScript ,   you should see something like /usr/local/bin/carthage copy-frameworks   .

**Comment by andrevz** [comment]
Hello @marinofaggiana I have exactly the same issue currently using Xcode 10.2, Carthage/Build does not have the .framework, is there any additional configuration step or guide? thanks

**Comment by AwaisFayyaz** [comment]
> Hello @marinofaggiana I have exactly the same issue currently using Xcode 10.2, Carthage/Build does not have the .framework, is there any additional configuration step or guide? thanks

Hi andrevz,

I was having the same issue. As balusreekanth mentioned above, this project uses carthage as dependency manager. So we have to install dependencies using carthage. 

1. Install carthage
2. go to your project directory, open a terminal there and run this command to download and build dependencies 

`carthage bootstrap --platform iOS --no-use-binaries --cache-builds`

Please have a look at [this amazing medium](https://medium.com/wolox-driving-innovation/how-to-carthage-efficiently-4913b8378898) article for details on using carthage. 

I just built the project succesfully after running this command

**Comment by rygen** [comment]
Sorry for bringing this issue back, but after a long while without contributing to the app, I found myself again stuck without being able to build the project successfully. Same issues as already mentioned in this thread.

This makes it harder for potential contributors to join the project. As you all know, it can be quite a pain to get a project to build if you still have to find out further instructions for it to build (or look inside issues like this one).

I'm using Xcode 11.4 (Swift 5.2), which could explain the different results.
Following the instructions in the [README.md](https://github.com/nextcloud/ios/blob/master/README.md) brought me to a non building app.
`carthage build --platform ios` didn't work.

@AwaisFayyaz's suggestion took much **much** longer but did work:
`carthage bootstrap --platform ios --no-use-binaries --cache-builds`

Would you mind if I submit a PR to adapt [README.md](https://github.com/nextcloud/ios/blob/master/README.md) suggesting this extra step in case it doesn't build?

I also think building with the simulator should be suggested under "Start contributing". 
I know it's obvious for those experienced with iOS development and that this advice isn't specific to this project, but it's not obvious for someone starting out and wanting to contribute. Been there before and felt the frustration :)

**Comment by tarasis** [comment]
First thank you @AwaisFayyaz for that needed information. That has gotten me much closer to being able to build this app (its failing now building WeScan). Also running Xcode 11.4, on Catalina 10.15.4

I'm shocked there isn't a setup.md for this project like there is in the Android version, which clearly details the steps needed.

**Comment by akisv** [comment]
Is there any guide, how to set up and run next cloud in Xcode?
