### ISSUE TITLE
Push notification not shown full text for secondary account

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#782]
* having two Nextcloud instances with accounts
* configure both accounts inside the iOS app
* select account #1 
* getting a push notification on account #1 
* push notification is shown in full text in lock screen
* getting a push notification on account #2 
* actual: push notification is shown as "Nextcloud notification"
* expected: full text of push notification is shown

To test this I used this command on both instances:

```
sudo -u www-data php occ notification:generate morris "This is a nice text"
```

The top one is from account #1 and the second one from account #2.

![img_0956](https://user-images.githubusercontent.com/245432/52050661-8b3b2a80-2551-11e9-9513-e4a8066b6920.jpg)

**Comment by MorrisJobke** [comment]
cc @marinofaggiana

**Comment by nickvergessen** [comment]
Also Admin_notifications is the app id or object type and should not be shown to the user.

**Comment by MorrisJobke** [comment]
> Also Admin_notifications is the app id or object type and should not be shown to the user.

Ah - okay. I was a little bit confused, because I changed it to a free text on the server and it worked just fine 🙈

**Comment by MorrisJobke** [comment]
Tested and works now 👍
