### ISSUE TITLE
iOS client barfs on file/folder names containing question marks or asterisks

### ISSUE THREAD

**Issue by ApricotFarm** [nextcloud/ios#79]
(note: this occurs with file AND folder names, but I'll just refer to filenames for simmplicity)

The iOS client is not showing any asterisks "*" or question marks "?" in file or folder names. Any attempt to access these altered files fails, resulting in a "not found" or "unable to download" error. Refreshing the folder listing returns the filename(s) to the listing, but still missing the ? and * chars. This will continue to produce the same errors.

As a simple example, the file 
`20-037 Fox Chapel May 56*.jpg` 
on the server shows up as 
`20-037 Fox Chapel May 56.jpg`
on the iOS client.

The filenames are listed properly on the web app, and I have no trouble accessing them as named through the web interface (this includes the web interface as accessed on iOS).

This is a serious problem for me, as I use both of these characters quite frequently, and although I have not done extensive testing, I would guess that there are additional "special" characters (that are perfectly legal in filenames) that trigger this same behavior.

I would recommend a hotfix for this issue.

Server: Nextcloud 11.0.1 (stable)
running on Raspbian Jessie (fully updated), RPi 3B

**Comment by marinofaggiana** [comment]
Hi, this bug has already been fixed for the next version, thanks for your report

**Comment by ApricotFarm** [comment]
Great! Glad to hear it, and thanks for the quick response. Just FYI, I see that the dollar sign is affected as well.
