### ISSUE TITLE
Improve style and discoverability of notification actions

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#794]
This is how it looks right now:

The notification in the list:
![img_1059](https://user-images.githubusercontent.com/245432/52940410-ccf80d80-3366-11e9-859c-eb0b959281cb.PNG)

You then need to swipe to reveal the actions:
![img_1060](https://user-images.githubusercontent.com/245432/52940411-ccf80d80-3366-11e9-880a-f258c8bf03f2.PNG)

* the colors of the accept and decline buttons are not that good - maybe @nextcloud/designers have some presents, that can be used here
* the buttons are not discoverable - wouldn't it be best to show them inline? 

This is how it looks in the web UI:

<img width="397" alt="bildschirmfoto 2019-02-18 um 10 23 26" src="https://user-images.githubusercontent.com/245432/52940700-6e7f5f00-3367-11e9-8065-16b8fd0b827c.png">

This is how it looks in the Android app:

<img width="355" alt="bildschirmfoto 2019-02-18 um 10 28 08" src="https://user-images.githubusercontent.com/245432/52940892-e64d8980-3367-11e9-911e-f40c04deb846.png">

cc @tobiasKaminsky @nextcloud/designers @marinofaggiana

**Comment by marinofaggiana** [comment]
Yes, this is better ,make sense, ok

**Comment by MorrisJobke** [comment]
Still not solved.

**Comment by jancborchardt** [comment]
- Regarding discoverability: Swipe is only useful as a shortcut, but not the only way to use actions. In this case actually the actions should be shown right in the entry. (In other cases, a 3-dot icon should be displayed to open an action sheet.)
- About the colors: We could do it like we do on web and Android – use the primary color for the primary action (accept) and grey for decline.

**Comment by marinofaggiana** [comment]
@MorrisJobke @jancborchardt I had lost ! O [URGENT LIST]

**Comment by marinofaggiana** [comment]
@MorrisJobke how I can generate a Notification with action for test ? thanks

**Comment by tobiasKaminsky** [comment]
@marinofaggiana Morris is currently on parental leave.
Easiest way to generate a notfication (at least for me) is to have 2fa via notification enabled and then try to log in.

**Comment by marinofaggiana** [comment]
true ! thanks @tobiasKaminsky

**Comment by marinofaggiana** [comment]
@MorrisJobke available on TestFlight 2.23.8 build >= 2

**Comment by tobiasKaminsky** [comment]
Hm. I do only get 2.23.7 (9) offered.

**Comment by marinofaggiana** [comment]
yes it's yet in Apple review (waiting .... )

**Comment by tobiasKaminsky** [comment]
Looks really good :+1:

**Comment by marinofaggiana** [comment]
Add avatar, build 3

![Simulator Screen Shot - iPhone Xʀ - 2019-06-14 at 11 12 51](https://user-images.githubusercontent.com/8616947/59501911-d4ef3680-8e9c-11e9-97e0-ce9426b9eae1.png)

**Comment by tobiasKaminsky** [comment]
@jancborchardt this is a nice idea to how avatars here.
Shall we do this also on other clients & web? Then I create a meta ticket :-)

**Comment by jancborchardt** [comment]
@tobiasKaminsky yep – we have that in the Notifications and Activity in the web already. A meta ticket would be great – I have additional input on the layout and will create a mockup for it. :)

**Comment by MorrisJobke** [comment]
@marinofaggiana Awesome! 🎉 That looks really nice. I tested it and it works 👍
