### ISSUE TITLE
New view "Media"

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#796]
**Known Issues:** 

- Procedure too heavy with several cost of CPU and network for synchronized the internal DB with Nextcloud server.
- Old Object-c source code
- Image preview not resizable
- Difficult to update  

**New version algorithm:** 

- Start: verify the internal DB, if this is empty request it on server all image/video of 30 days old from now, if don't return metadata (or the total records are < 100) send a new request for the last 90gg .. after 180 gg ... 365 gg and if do not exists metadata send a request for "Distant past".

- Update: when you move the scrollbar (at the end of move) or go back in this view the procedure detect the "window" of date present on screen and send a request to server for this step of date (webDAV: lte - gte), verify it the difference of this records with the records in DB, if exists a difference update the view, otherwise it 'does not matter. 

- At the end of the collection: as start, send a request for other 30 day old from the last data, if don't return metadata (or the total records are < 100) send a new request for the last 90gg .. after 180 gg ... 365 gg and if do not exists metadata send a request for "Distant past".

- The download of preview happen only when the scroll bar is stops (reduce traffic on network)

- Now is possible (manually) required a refresh with the refresh Control.
 
- Now is possible resize the preview image (see capture below).

- Code in swift 4

- When start (DB empty) the time and, the network traffic, required is very very short and do not require wait.

- New Fast Scroll: https://github.com/marinofaggiana/FastScroll

![simulator screen shot - iphone xs max - 2019-02-19 at 11 58 04](https://user-images.githubusercontent.com/8616947/53010971-904c1500-343f-11e9-9291-d88049117b26.png)

![simulator screen shot - iphone xs max - 2019-02-19 at 13 09 34](https://user-images.githubusercontent.com/8616947/53014087-ae1d7800-3447-11e9-9b9c-9aa940f1fffd.png)

![simulator screen shot - iphone xs max - 2019-02-19 at 13 09 17](https://user-images.githubusercontent.com/8616947/53014118-cb524680-3447-11e9-9c18-ee6b49bfa30b.png)

**The first unstable version 2.23.1.0 well be available soon on TestFlight.**

**Comment by AndrewwHummer** [comment]
It seems like a very nice implementation of the Gallery feature!
Yes, it really hammers the Server DB, and creates high load, but, nah, what ever 😄 

-There seems to be an issue with the date annotation shown. In my app it stops at 12th of January 19, but scrolls down the pictues just fine.

-The pictures are more or less completely out of order, at least they are not sorted date wise.

-The app did crash only once.

-Yesterday it was not possible to scroll down to pictures beyond ~30 Days ago...

But still very nice step in the right direction.

**Comment by marinofaggiana** [comment]
Build 1:

- Improvements downloadThumbnail
- Add Fast Scroll (see figure)
- Add Activity Indicator below when load a new old items
- UI/UX

![simulator screen shot - iphone xs max - 2019-02-20 at 14 46 07](https://user-images.githubusercontent.com/8616947/53097509-e6918480-3521-11e9-9f4b-39af9f2241a5.png)

**Comment by marinofaggiana** [comment]
Hi @AndrewwHummer 

> -The pictures are more or less completely out of order, at least they are not sorted date wise.

mmm look 

> -The app did crash only once.

mmm no this is not good (how ?)

**Comment by AndrewwHummer** [comment]
The app crashed when I just scrolled down very far, at some point it started to lag and suddenly, IOS seemed to kill the app, just exiting to homescreen...

The funny stuff begins after Sunday 12 Janurary for me. Ah wait a second, thats where the old media Tab continuously crashed the app completely... I guess that there is something in my database that is not really straight....

**Comment by AndrewwHummer** [comment]
Ah damn, I just found out that the file creation date is used, so not the embeeded data information in the picture, or even the file name that could be interpreted. 
So no wonder that after the 12th January 19 there is no new date/new photos 💯 
And no wonder the pics are not in any specific order.

Is there a way to change the sorting?

**Comment by marinofaggiana** [comment]
@AndrewwHummer try the build 4

**Comment by AndrewwHummer** [comment]
It´s way more stable. I will test some things. But for now it seems like a huge improvment!

**Comment by jcreixell** [comment]
This is a great improvement over the previous media view. I can see my pictures from the last 30 days, however, when I scroll to the bottom I see a spinner but it never shows more pictures and eventually the spinner disappears. I am using 2.23.1. 

In any case, this is looking very promising :)

**Comment by marinofaggiana** [comment]
@jcreixell, strange, the date in your database are ok ?

**Comment by jcreixell** [comment]
@marinofaggiana I think so, at least in web it works well. Let me know if I can help with debugging.

**Comment by AndrewwHummer** [comment]
Oh! I have an idea: Often the media view exceeds the standard mysql connection limit of 100. Thus the database kills the connection to Nextcloud.
This would be noted prominently in the logs. So if you can: look at your mysql stats and look out for connections used and the connection limit.

Also take a look at the nextcloud server log! 👍  Maybe post the server log :)

**Comment by marinofaggiana** [comment]
Add 3D touch

**Comment by khlschrnk** [comment]
> Ah damn, I just found out that the file creation date is used, so not the embeeded data information in the picture, or even the file name that could be interpreted.
> So no wonder that after the 12th January 19 there is no new date/new photos 💯
> And no wonder the pics are not in any specific order.
> 
> Is there a way to change the sorting?

+1 on this. It is common for lots of media tools, especially while exporting media, to change the creation date of a file. The current mechanism always shows newest files (in terms of creation date of the file itself) first. This lead to a media view which is unsorted. So I'd love to see a possibility to sort for filename or even the creation date in the metadata.

Anyway, the media view is already a great enrichment!

**Comment by jcreixell** [comment]
@AndrewwHummer sorry, unfortunately I don't have access to these logs as I am using a hosted solution :(
