### ISSUE TITLE
Search Option

### ISSUE THREAD

**Issue by supportreq** [nextcloud/ios#8]
Waiting for this feature since a long time, there should be a search bar at the top which will allow users to directly search for their files instead of manually scrolling through the list..

**Comment by marinofaggiana** [comment]
hi @supportreq we are in wait of API, will arrive.

**Comment by disaster123** [comment]
+1

**Comment by disaster123** [comment]
What about just filtering the current view?

**Comment by MorrisJobke** [comment]
Let's track this over in #53 and close this one here. Sorry I didn't noticed this issue before.
