### ISSUE TITLE
Text string error

### ISSUE THREAD

**Issue by meneer** [nextcloud/ios#80]
parameter Text _rename_filename_ in ios-localizable is wrong: 
"Rename file name"
Should be just "Rename"

**Comment by jancborchardt** [comment]
@meneer can I ask you to submit a pull request? It should be very easy to find that string and change it. :)

**Comment by rakekniven** [comment]
Can I step in ?

**Comment by meneer** [comment]
Feel free to step in... I never pulled anything, just posted issues :)

**Comment by jancborchardt** [comment]
Good detail fix @rakekniven! :) Good to have you and also thanks for managing the milestone!
