### ISSUE TITLE
Help building release for iOS 8.4.1

### ISSUE THREAD

**Issue by nate2014jatc** [nextcloud/ios#800]
### App version: 2.18.0

**Nextcloud version:** 15.0.4

I know it's a very strange request, but I've got an older iPhone 4S that I can't update past iOS 8.4.1 for jailbreak reasons.

I should be able to install nearly anything I can build. I just need help getting that far.

**Comment by marinofaggiana** [comment]
Nextcloud iOS required iOS >= 10.

**Comment by nate2014jatc** [comment]
What about it makes iOS 10 mandatory?
even if I update to the latest available iOS release for my device I would still be unable to use the nextcloud app

**Comment by marinofaggiana** [comment]
Nextcloud iOS uses several technology available only from iOS 10 (better iOS 11 for AI, document provider.. and more ). 
The number of device in the world with iOS <= 9 does not justify the maintenance of compatibility with this old devices.
