### ISSUE TITLE
Link sharing fails if password enforcement is enabled for public links

### ISSUE THREAD

**Issue by schiessle** [nextcloud/ios#801]
Enabling password enforcement for public links in the Nextcloud admin settings will make the public link creation fail silently.

Instead, the iOS app should first ask the user for a password and then continue creating the link share with the password.

cc @Ivansss and @tobiasKaminsky because they helped testing it and on Android it works as expected so Tobias can probably help to have a unified UX.

**Comment by schiessle** [comment]
While implementing it, also keep the "Always ask for password" setting in mind:

![image](https://user-images.githubusercontent.com/1589737/53574198-65fd0480-3b6f-11e9-9618-62bed8d8c51c.png)

In this case we should ask the user for a password but also allow to continue without it. It basically works as a suggestion instead of an enforcement.

**Comment by marinofaggiana** [comment]
@schiessle  ... where is the "always ask for a password" in capabilities ... 


public =                     {
                        enabled = 1;
                        "expire_date" =                         {
                            enabled = 0;
                        };
                        password =                         {
                            enforced = 0;
                        };
                        "send_mail" = 0;
                        upload = 1;
                        "upload_files_drop" = 1;
                    };

**Comment by marinofaggiana** [comment]
@schiessle enforce password protection available on TestFlight V2.23.2 (Build 1) but NOT tested.

**Comment by tobiasKaminsky** [comment]
> but NOT tested.

Well…this should be tested before releasing:
- set up your own local nc master server
- connect app
- test
