### ISSUE TITLE
Files with size 0 behave weirdly

### ISSUE THREAD

**Issue by hactar** [nextcloud/ios#803]
I've noticed that the app behaves weirdly when dealing with files that have no data (fileSize 0). I've traced this to this check which is used all over the app. Notice how it checks fileSize > 0. Is this intended? Wouldn't be checking fileSystemNumber or something yield better results?

CCUtility.m:926:
```
+ (BOOL)fileProviderStorageExists:(NSString *)fileID fileNameView:(NSString *)fileNameView
{
    NSString *fileNamePath = [self getDirectoryProviderStorageFileID:fileID fileNameView:fileNameView];
    
    unsigned long long fileSize = [[[NSFileManager defaultManager] attributesOfItemAtPath:fileNamePath error:nil] fileSize];
    
    if (fileSize > 0) return true;
    else return false;
}
```

**Comment by marinofaggiana** [comment]
@hactar the document provider extension required that every file exists for to be view in list view, so a file with length = 0 do not exists.

**Comment by marinofaggiana** [comment]
@hactar it's this exhaustive for you?
