### ISSUE TITLE
Use »Folder« icon for Files navigation entry instead of Nextcloud logo

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#81]
The whole app is Nextcloud, so the Nextcloud logo for the »Files« section is misplaced. Instead, just use a normal folder icon there.

(Also see Use the Nextcloud file type icons #67)

**Comment by MariusBluem** [comment]
Seems to be fixed now 🙌:

![files_icon](https://cloud.githubusercontent.com/assets/19711361/23999086/8c81a818-0a57-11e7-8c6b-6990a81ad885.PNG)
