### ISSUE TITLE
Converting HEIF to JPEG loses metadata (like the GPS info)

### ISSUE THREAD

**Issue by mario** [nextcloud/ios#827]

**Comment by marinofaggiana** [comment]
I'm working on it

**Comment by mhls1981** [comment]
Would be great to also keep metadata for HEIF to JPEG such as original create data and time, especially for further processes such as cataloguing etc. Thanks!

**Comment by marinofaggiana** [comment]
@mhls1981 yes, fixed. Available from the next version.
