### ISSUE TITLE
Tracker in iOS app (Crashlytics)?

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/ios#829]
There seems to be a tracker of Google/Crashlytics integrated in the iOS app of Nextcloud.
The Android app was also affected, but there the trackers were already removed.

For more information, see [here](https://www.kuketz-blog.de/nextcloud-ios-app-mit-tracking/) and [here](https://help.nextcloud.com/t/tracker-in-nextcloud-client-app-for-android-on-ios-too/50473/6).

Can someone of the developers confirm or decline this issue?

If trackers are present in the app, these should be removed. Privacy is one of the core principles of Nextcloud and a tracker doesn't fit in the picture there.

**Comment by MorrisJobke** [comment]
cc @marinofaggiana

**Comment by jospoortvliet** [comment]
I replied in the original issue here https://help.nextcloud.com/t/tracker-in-nextcloud-client-app-for-android-on-ios-too/50473/8 …
- in short, the apps don't record or share any personal data, there used to be some minimal analytics in some apps but that is disabled since a while already. For push notifications we have to connect to google.

**Comment by DecaTec** [comment]
That you have to connect to Google for notifications, ok.
But a tracker (Crashlytics) should really be removed from the app as it's not clear what data gets submitted there.
In the Android app it was already removed, so it can't be _that_ important. The privacy should be more important than some crash analytic data imho.

**Comment by jospoortvliet** [comment]
@DecaTec you can look in the source if you are not sure what data is submitted - it is all there. Stability of the app seems quite important to me, don't you agree?

**Comment by DecaTec** [comment]
Sure, stability is quite important. The question is, if Crashlytics is such important for stability.
I just mean, the Android app removed the tracker. Did this result in more instability in the Android app?
Are there no other possibilities to collect crash reports than a tracker?

**Comment by DecaTec** [comment]
Great, at least it can be disabled by the user in the future. Thanks!
