### ISSUE TITLE
»Local storage« function is confusing and unnecessary

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#84]
By accident when clicking around in the app I found the »Local storage« sidesection of the »Offline« section (reachable only via clicking the barely visible white dots on the bottom).

It says:
> Copy here the files you want to have available offline, but that will no longer be synchronized with your cloud.

This is not something we do anywhere else with Nextcloud. Everything in the Nextcloud app you should be absolutely sure it is synchronized, not using any modes.

**Comment by marinofaggiana** [comment]
This "storage" it's for unpacked file and for share with iTunes.

**Comment by jancborchardt** [comment]
Is this not possible simply in the app itself, for files which are downloaded? Isn’t it simply possible to share with iTunes via the »Open with« hook?

cc @nextcloud/ios

**Comment by jancborchardt** [comment]
Ok @marinofaggiana – so let’s remove it as talked about. :)
