### ISSUE TITLE
No exit button when pdf preview

### ISSUE THREAD

**Issue by Crustulum** [nextcloud/ios#854]
When a Pdf files is opened viewing works fine. But when you want to close the pdf file (viewer) there is no arrow in the left upper corner or a cross to leave the pdf viewer.
Please add a way to open a other pdf document without completly restarting the app.

**Comment by marinofaggiana** [comment]
@Crustulum with iPad ?

**Comment by crustulumtheoneandonly** [comment]
@marinofaggiana yes with a iPad

**Comment by marinofaggiana** [comment]
why do you need an exit (back) button ?

**Comment by crustulumtheoneandonly** [comment]
I didn't recognized another way to leave the PDF view? (On Android you have at least the physical back button)

**Comment by crustulumtheoneandonly** [comment]
@marinofaggiana How can I close the document without restarting the app?

**Comment by marinofaggiana** [comment]
The interface of iPad don't have a back button because view always the last file open.

**Comment by crustulumtheoneandonly** [comment]
And how can I close the view?

**Comment by marinofaggiana** [comment]
Not possible close the view with this interface.

**Comment by crustulumtheoneandonly** [comment]
And can somebody add the option?

**Comment by marinofaggiana** [comment]
No, only if this function is really requested by users.

**Comment by crustulumtheoneandonly** [comment]
Would be important, I can't use the system professional else..

**Comment by marinofaggiana** [comment]
@crustulumtheoneandonly, for professional use please use this:

https://nextcloud.com/pricing/

**Comment by crustulumtheoneandonly** [comment]
I mean not directly professional use, I mean I can't recommend the app to anyone else if basic functionality isn't given.
Btw I already donated money and have only a privat server running..

**Comment by jospoortvliet** [comment]
I don't understand - on my ipad, it opens the PDF in the right bar. If I click another file, it opens the other file - no need to close it.
If I go full-screen, there's a back button on the top-left. Am I missing something here? Could you post a screenshot?
