### ISSUE TITLE
Nextcloud keep local copy of uploaded files

### ISSUE THREAD

**Issue by spridarn** [nextcloud/ios#862]
Hi,

I have running Nextcloud and the auto upload function for long time now. Earlier, maybe 6-12 months ago it was some option in the app saying that it should remove uploaded photos from local cache when they are uploaded. This function helped to have the Nextcloud local cache small at the phone. 
The last months I got a lot of message at my phone saying that storage is full and when checking Nextcloud cache is really big. When clearing the cache it is normal again. It this function removed or how is this working?

Nextcloud for iOS 2.35.5.1
Nextcloud server: 15.0.5

**Comment by marinofaggiana** [comment]
@spridarn yes this option was removed because  it generated too much confusion ... so when an file is uploaded remain in local cache

**Comment by spridarn** [comment]
@marinofaggiana ok any plans to implement this kind of function again? I think it is wrong that the storage at my phone should be full when I want to send my pictures to my own Nextcloud.

**Comment by marinofaggiana** [comment]
no, for now no, it was no longer actually required ...

**Comment by spridarn** [comment]
Sad I think the behavior now is wrong...
