### ISSUE TITLE
Search bar always visible

### ISSUE THREAD

**Issue by maprambo** [nextcloud/ios#88]
In app version 2.17 (build 00014), the new search bar is always visible when you open the app/a folder.
In native apps (like in settings) the search bar is hidden above the content and only visible when you scroll up though.

**Comment by marinofaggiana** [comment]
Hi @maprambo what's "native apps" ?

**Comment by maprambo** [comment]
I meant system/apple apps. sorry for that, my mistake.

**Comment by rakekniven** [comment]
Thought the same today after upgrading to build 00017. Only show search when swiping down. Apple system settings use it and other well designed apps like Things. Hiding search bar saves some space and search is not used each time opening folder view.

![2017-02-23 20-56-54 6097](https://cloud.githubusercontent.com/assets/2069590/23276721/b48e237e-fa0b-11e6-90de-2d00955831e3.jpg) > ![2017-02-23 20-57-01 6098](https://cloud.githubusercontent.com/assets/2069590/23276723/b6d0ad32-fa0b-11e6-8de7-71c9167ac952.jpg)

**Comment by rakekniven** [comment]
@jancborchardt What is your comment on here?

**Comment by marinofaggiana** [comment]
Report for next version, Show or Hide search bar on Load view ?

**Comment by rakekniven** [comment]
Hide it at load view. See my screenshots above. The second one show default view.

**Comment by jancborchardt** [comment]
Agree with everything said by @maprambo and @rakekniven, good feedback :)

**Comment by rakekniven** [comment]
Works for me. @marinofaggiana You can close it if you like or do you have open tasks on this?
