### ISSUE TITLE
Add support for download as / print from collabora

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/ios#884]
Collabora offers a download as (with different file types) and print option in the menu. When the user accesses those, a one-time URL is generated and opened. Since the webview is not able to save those files/forward them to some printing mechanism, Collabora introduced a post message that richdocuments now forwards to the mobile clients with https://github.com/nextcloud/richdocuments/pull/533

If the user clicks the option a message `downloadAs` will be called on the `RichDocumentsMobileInterface`.

The message contains two arguments:

- Type: which is a string either download or print

- URL: containing the URL to fetch the file

On Android @tobiasKaminsky mentioned that this will work fine to just hand the url over to some kind of system download manager. Not sure how this can be done on iOS. Feel free to ping me if you have further questions.

**Comment by tobiasKaminsky** [comment]
Please note that server is sending a JSON as string, e.g:
"{ "Type": "print", "URL": "https://…" }

**Comment by marinofaggiana** [comment]
@juliushaertl @oparoz available today TestFlight V 2.23.8 build 6

**Comment by tobiasKaminsky** [comment]
Tested and working :-)

**Comment by juliushaertl** [comment]
Already fixed
