### ISSUE TITLE
Settings order

### ISSUE THREAD

**Issue by maprambo** [nextcloud/ios#89]
In version 2.17 (build 00014), in the app settings, there are the password settings first, then the settings concerning the Nextcloud account and then everything else.

Imo, it would look cleaner if the settings were ordered this way:

1. Nextcloud account
    - Image and name
    - Email
    - Space (maybe with a bar showing the percentage)
    - Url
    - Server version
    - Change account settings
2. Password settings (maybe rename it to "Local encryption settings" to prevent confusion)
3. Everything else

**Comment by marinofaggiana** [comment]
Change all Settings, this post is old. close
