### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/ios#9]
Currently we have **ios-translations** as a repository ... I think we should import it here and kill it 🔥 
Simplicity FTW 💪 

@marinofaggiana @MorrisJobke

**Comment by MorrisJobke** [comment]
@marinofaggiana We should coordinate it ;)

**Comment by marinofaggiana** [comment]
Hi yes, it's possible copy (the activate) language from Transifex to this ?

**Comment by MorrisJobke** [comment]
sure :)

**Comment by MorrisJobke** [comment]
> Hi yes, it's possible copy (the activate) language from Transifex to this ?

Where should it be? In some subfolder?

**Comment by marinofaggiana** [comment]
Folder : 

iOSClient/cs.lproj
iOSClient/de.lproj
iOSClient/en.lproj
iOSClient/fr.lproj
iOSClient/it.lproj
iOSClient/nl.lproj

Note :  how i make know if a new language is ready for pubblication ?

**Comment by MorrisJobke** [comment]
> Note : how i make know if a new language is ready for pubblication ?

It appears in there ;)

**Comment by marinofaggiana** [comment]
@MorrisJobke i think another problem on nextcloud-bot ... please modify

**Comment by MorrisJobke** [comment]
> @MorrisJobke i think another problem on nextcloud-bot ... please modify

? I only know that the nextcloudbot is currently not running, but I can fix this on Tuesday first.

**Comment by marinofaggiana** [comment]
why stop running ? ok for Tuesday

**Comment by MorrisJobke** [comment]
Because the server somehow stopped and I'm abroad and therefore can't fix it.

**Comment by marinofaggiana** [comment]
ok, @MorrisJobke when you ready please use this.

**Comment by MorrisJobke** [comment]
The cron job now runs against this repo \o/

**Comment by marinofaggiana** [comment]
oook ! good

**Comment by marinofaggiana** [comment]
Hi Morris, problem, for me de.lproj is the directory language for German but for transifex is de_DE.lproj

**Comment by MorrisJobke** [comment]
> Hi Morris, problem, for me de.lproj is the directory language for German but for transifex is de_DE.lproj

There is de(informal version of german) and de_DE (formal version of german).

**Comment by marinofaggiana** [comment]
Morris, my project use format xx.lproj (de.lproj) .... de_DE isn't correct.

**Comment by MorrisJobke** [comment]
But there are languages that have multiple translations in different countries. How to handle this?

**Comment by marinofaggiana** [comment]
yes, i18n, for example Portuguese is pt.lproj, Portuguese-Portugal is pt-PT.lproj but German its **de.lproj** not de_DE.lproj

**Comment by MorrisJobke** [comment]
> yes, i18n, for example Portuguese is pt.lproj, Portuguese-Portugal is pt-PT.lproj but German its de.lproj not de_DE.lproj, and informal please leave it to the translators transifex, not here in the code.

I killed it.
