### ISSUE TITLE
Offline tab

### ISSUE THREAD

**Issue by maprambo** [nextcloud/ios#90]
Imo it's confusing that there is a seperation between the local files and favorites that are synced. 
Is it possible to just list them under another? 
Even when not, the slider in v 2.17 (build 00014) to change the tab on the bottom is only working when you swipe _directly_ on the little bar. It would be more intuitive if it was like on the home screen and if you could swipe on the whole screen.

**Comment by maprambo** [comment]
Well or you could remove it completely just like in #84

**Comment by rakekniven** [comment]
Hello Marino,

just reopened issue as it is present in latest Testflight version 2.17 (0027).
My screens show very tiny white dots.
If you leave this function in version 2.17 I have two ideas:
1. Highlight dots a little more
2. Use whole screen to swipe (change) between favorites and local storage.

![2017-03-08 19-26-06 6107](https://cloud.githubusercontent.com/assets/2069590/23859312/7b8bc5ee-0803-11e7-8ae2-60aefacb161d.png)

![2017-03-08 19-26-11 6108](https://cloud.githubusercontent.com/assets/2069590/23859311/7b8b83ea-0803-11e7-9067-12c4298b6f91.png)

**Comment by rakekniven** [comment]
Fixed for me in v2.17 0028

**Comment by marinofaggiana** [comment]
ok close this issue
