### ISSUE TITLE
Plus button

### ISSUE THREAD

**Issue by maprambo** [nextcloud/ios#91]
The new "plus" button in v 2.17 (build 00014) has some confusing bugs atm:

1. When uploading photos, you are asked for the directory. It is good to be able to choose the photos folder set in the settings for direct upload, but chosing another folder than this or the one you're currently in is unnecessary. I think a dialog with two buttons ("This folder", "Photos") would do the job better here.
2. You can press the plus button when you're in other tabs, like in "offline" or "settings" and i.e. create a new folder from there. It would be better that when the button is pressed outside of "Files", the "Files" view would just come up and that you could first choose the directory and then press the button again.

**Comment by maprambo** [comment]
Why was this closed?

**Comment by bencomp** [comment]
I wonder if this is still an issue in recent versions of the app (but don't have iOS myself to verify).
