### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by jean-io** [nextcloud/ios#910]
Hi,

[iOS 13](https://www.apple.com/ios/ios-13-preview/) beta is out for developers and it brings dark mode to iPhones. 

1. Can Nextcloud app get a dark mode too?
2. Can it be automatically turn on and off depending on system wide dark mode?

If it could be done, it would be great :heart_eyes:

Thank

**Comment by marinofaggiana** [comment]
Hi, secure this is in ToDo !

**Comment by marinofaggiana** [comment]
![Simulator Screen Shot - iPhone Xʀ (develop) - 2019-09-05 at 15 58 31](https://user-images.githubusercontent.com/8616947/64409670-a8a51980-d089-11e9-996e-02e3cb43c0dc.png)

**Comment by ricain** [comment]
Nice :+1: this looks really good!

Is auto toogle part of v2.24.0 too?

**Comment by marinofaggiana** [comment]
When available iOS 13, yes.

**Comment by marinofaggiana** [comment]
@inthreedee thanks for you report. 👍

**Comment by inthreedee** [comment]
I’ve noticed a couple more places where the dark theme is not applied:

1. The keyboard when editing a file
2. The rename dialogue box
3. The lock screen

I’m traveling this weekend and can’t attach screenshots directly from my iPhone. If you need clarification, let me know and I will attach the screenshots as soon as I am able.

**Comment by ricain** [comment]
Hi, updated to iOS 13 and my Nextcloud app to v2.24.0 but I cannot find auto toggle to comply with system wide dark mode.

Is it normal? Where can I find this setting?

**Comment by marinofaggiana** [comment]
The (auto) is not yet available, for now use the manual switch in beta

**Comment by ricain** [comment]
ok

**Comment by wiswedel** [comment]
Dark mode is available now. @jean-io, please open a follow-up ticket for the auto-toggle if necessary.

**Comment by jean-io** [comment]
No need for a follow up issue.

Thank @marinofaggiana for the great job!

**Comment by thorrrr** [comment]
Hello i am on IOS 16 on iPad & iPhone and this option is not available!
Please can you tell me how to switch it on?
