### ISSUE TITLE
Possible iOS 13 - NC app incompatibility (Needs confirmation)

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/ios#913]
I'm running the current iOS 13 beta version on my iPhone. I noticed that the fotos app has been restructured quite a lot and I have the feeling that the new structure has an impact on apps that access the camera roll like the nextcloud app.

When I open the fotos app, I see a folder "recently used" which has **all** of my photos in it. No matter if I have taken them on the phone or if they were synched to the phone via iTunes. Oddly, nextcloud app starts to push all photos it finds in that folder to the nextcloud server, which of cause is not the correct behavior. 

I do not know for sure if this is a bug in the iOS beta or if they really changed something, which means that the nextcloud app must be updated for being able to cope with the new/changed feature.

**Comment by marinofaggiana** [comment]
Hi, sorry but for the iOS version in beta I don't verify nothing.

**Comment by ho1ger** [comment]
That issue solved itself. The behavior of the "recently used" folder is back to normal.
