### ISSUE TITLE
IOS13 beta NextCloud crash when trying to select a video

### ISSUE THREAD

**Issue by maxlehot1234** [nextcloud/ios#915]
Hi everyone,

I am able to upload photos from my iphone library but directly when the nextcloud app "see" a video, the app crash so I am not able to select a video from the list.

I know ios13 was on beta, but just want to report the bug so you can fix it for the final version ;)

Thanks again for this app ;)

**Comment by marinofaggiana** [comment]
Hi, sorry but for the iOS version in beta I don't verify nothing.

**Comment by marinofaggiana** [comment]
reopen if persists in Stable version.
