### ISSUE TITLE
Preview images and refresh option on photos tab

### ISSUE THREAD

**Issue by maprambo** [nextcloud/ios#92]
On the photos tab, there are only icons of a cloud with an arrow if the photo is not downloaded yet.
In the file list, there are (I think even server generated) preview images for all the photos. I think it would be great to have these in the photo tab, too (maybe cached?).
Also, I like the option to save only compressed images - but I see no option to download the high-res one to share directly via Telegram & co. Also, an auto deletion for photos that are not viewed often could save some space.
Also, there's no option to reload the photos (i.e. when uploading from multiple devices is set up). A pull-to-refresh and maybe one refresh around every time the app is opened, just like in the files view,  would be handy here.
Btw, I'm using v 2.17 (build 00014).

**Comment by maprambo** [comment]
The preview generation works great in v 2.17 build 00018 👍 
But don't close this issue so far as the second and third point weren't implemented yet.

**Comment by yamlfd** [comment]
I'm on 2.17.5 and the thumbnals are not loaded and not loaded async. Thumbnails are 100% pre-generated on server side. 

![img_0125](https://user-images.githubusercontent.com/4450722/28747547-ee3f11b2-74a1-11e7-8970-97f5e8c01120.PNG)

**Comment by TylerTemp** [comment]
Any process on this? Still exists on 2018 :(

**Comment by marinofaggiana** [comment]
Sorry, no issue for this ...
