### ISSUE TITLE
Feature request: remove autouploaded files from cache

### ISSUE THREAD

**Issue by veddox** [nextcloud/ios#921]
One major reason for autouploading pictures is to save storage space on the phone. However, these pictures are retained in the NC cache, thus effectively *doubling* the storage space they use, until one gets around to clearing the cache manually (currently a very tedious task, cf. #217).

It would be nice to have a setting that leads to autouploaded images automatically being removed from the cache, thus saving disk space and effort.

**Comment by marinofaggiana** [comment]
Available from the 2.23.8 (24) in TestFlight.

Add option in Settings/Advanced.

**Comment by veddox** [comment]
Oh wow, that was quick! Thank you very much, I hadn't expected such prompt service :smile:
