### ISSUE TITLE
Cache Problems

### ISSUE THREAD

**Issue by snowbolzer** [nextcloud/ios#938]
I use several IOS Devices to work with Numbers. I store the files to nextcloud using actual IOS Client (2.23.8.30) and actual IOS (12.4.1) on a hosted Nextcloud Server (15.0.11). The Problem exists since approxiamtely 1 year. Before it worked.
If i change the files content on one Device in Numbers, the file seems not to be uploaded correctly. I have to swipe in nextcloud app to upload it. If the file was opened on another device sometimes the file is not updated but even if so it can´t be saved. There is an Error "You are not allowed to safe to folder (cryptic foldernam)". If I clear the Cache in Properties of Nextcloud App before it works. On MAcbook everything works properly. 
That is not really workflow to clear cache every time. Isn´t it possible to disable caching in IOS Nextcloud App and to force upload every time the file is closed.

**Comment by marinofaggiana** [comment]
Hi, try wit the Beta version:

Nextcloud TestFlight

https://testflight.apple.com/join/GjNbfo2a

**Comment by snowbolzer** [comment]
hi marino, 
seems to work fine with cache disabled. Will keep on testing.
regard
achim

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by snowbolzer** [comment]
>Hi, try wit the Beta version: ...

@marinofaggiana 
seems to work fine with cache disabled in settings. Will keep on testing.
regard
achim


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by snowbolzer** [comment]
>Hi, try wit the Beta version: ...

@marinofaggiana where to report bigs if i find one?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marinofaggiana** [comment]
Here, you can create an issue (if do not exists).

**Comment by fractalf** [comment]
@snowbolzer where did you disable cache? Is that a beta only feature? I have problems backing up an iPhone with 6GB of photo and only 2GB of storage left. Since the app cache the photoes it's backing up :/

**Comment by snowbolzer** [comment]
>@snowbolzer where did you disable cache? Is that a beta only feature? I have problems backing up an iPhone with 6GB of photo and only 2GB of storage left. Since the app cache the photoes it's backing up :/

@fractalf at the moment its a feature in the beta. hope it will be in the upcoming version

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by snowbolzer** [comment]
@marinofaggiana @fractalf problem is solved in my case and works in 2.24.1.00 by disabling cache in  settings

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
