### ISSUE TITLE
Refine address layout

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#94]
![adresse](https://cloud.githubusercontent.com/assets/245432/23289815/f135d802-fa11-11e6-89bc-0ed3d827d56d.png)

followup to #57 

name, street, city and phone number should be on separate lines and not on a single line.

cc @marinofaggiana

**Comment by marinofaggiana** [comment]
done

**Comment by MorrisJobke** [comment]
Thanks @marinofaggiana
