### ISSUE TITLE
opening files in files app or numbers / no upload

### ISSUE THREAD

**Issue by snowbolzer** [nextcloud/ios#956]
### App version 2.24.1.0

**Nextcloud version:** 16.0.4

when trying to open a file from the nextcloud folder in numbers there is an error which says, that the file ist corrupted an can not be opened. Same if I try to open the file in files app. The only ay to open the files is to open them in nextcloud app and then "send" them to numbers. Now the files are opened and can also be opened the ways that went wrong above. 

If I change anything in the files it is shown in numbers but not uploaded to nextcloud server. If I open it again, there is an old date of last saving but the changes are shown. after restarting Numbers the changes are gone. Only the file could be opened as usual.

caching the files local is turned off.

Tested on Iphone 7 Plus, IPad Air 2, Iphone SE and 2 different Nextcloud Servers.

Any suggestions or further questions?

Think this is related to #941 ?

**Comment by Zigulle** [comment]
Hello, 

I have the same but in various applications. 
1. In Marvin (iOS-ebook-reader app) - when I try to open an ePub in Marvin using the file app, the error "Oops Your Book couldn't be imported because it is damaged or encrypted" ist shown.
2. In any office365 app it is not possible to select a file. When i tap on a .docx file in word, nothing happened!!! Its the same in excel or powerpoint.
3. I could not open any pdf in PDF expert. Its the same as in office385!

Nextcloud version: 17.0
App version: 2.24.10

**Comment by snowbolzer** [comment]
Seems it was my fault. Had the beta of 2.24. running in testflight on my devices and installled the release just over it. Now I deleted the app an installed it again and now it seems to work again properly.
Found it, because the update info in appstore did not appear.

**Comment by ingmarcosp** [comment]
I have the same problem with the lasted version. 
iOS 13.2
Nextcloud client 2.24.4

**Comment by Zigulle** [comment]
Hi,

this issue is solved in the TestFlight version.

**Comment by snowbolzer** [comment]
> Hi,
> 
> this issue is solved in the TestFlight version.

Testflight version doesnt work. Can‘t open any files using files app, Numbers, pages only a plain site is shown
![F9F6E388-4561-42BD-84E6-53AEE6C3F577](https://user-images.githubusercontent.com/35323201/68764812-ad52f480-061b-11ea-931b-0ecc6c9b1314.png)

**Comment by marinofaggiana** [comment]
This issue is solved with the 2.25.0 in TestFlight

**Comment by snowbolzer** [comment]
@marinofaggiana 
seems also to be solved in 2.24.4.1 didn‘t get a updateinfo in appstore, but when installing it new there was the update info. Testflight version i found was a old one i think 2.23?

**Comment by snowbolzer** [comment]
seems to be solved in 2.25.0 Tested it all night long, and it works. Only thing i miss is the ability to see multiple servers in Files App and opening files on a specific server without switching server in Nextcloud App.
Thank you for your work @marinofaggiana
