### ISSUE TITLE
iOS app users should be able to take over credentials from the other app (Files & Talk)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/ios#958]
@marinofaggiana @Ivansss you mentioned that the apps need to be in the same namespace / by the same developer for the credentials to be shared.

Is this not something we wanted to do, moving the apps under the same account? cc @karlitschek 

Would be cool because re-typing credentials is really cumbersome. Ideally, if you already have the Nextcloud iOS app, the Nextcloud Talk iOS app should automatically log you in.

**Comment by jancborchardt** [comment]
Transfered to main iOS app repo, reopening. :)

**Comment by marinofaggiana** [comment]
Not possible move the app NC for iOS.

**Comment by marinofaggiana** [comment]
We have already verify with Apple (yet 10 gg ago) and the App cannot be moved, so we need, if possible, search another street.

**Comment by jancborchardt** [comment]
Yes, moving is not possible as was mentioned before already. The way to go would basically be to release a "new" version of the Files app in the Nextcloud org, where the Talk app already is, and slowly move over the existing users.

The longer we wait, the worse the issue is going to get. Especially if at some point we will have other apps than Files and Talk. cc @karlitschek @jospoortvliet

**Comment by karlitschek** [comment]
@marinofaggiana We have to work on a solution. I will email you.

**Comment by splitt3r** [comment]
Are there any updates on this topic?

**Comment by jancborchardt** [comment]
As far as I know this is resolved now since the app was recently also moved under the Nextcloud organization / publisher. Does that mean this specific issue is also fixed @marinofaggiana @tobiasKaminsky, or is anything additional needed for it?

**Comment by marinofaggiana** [comment]
Not yet, but from today the new version under the Nextcloud organization is available on Apple Store, so from the next version we can share the credential with the other Nextcloud iOS products (Talk, ...)

**Comment by tobiasKaminsky** [comment]
Duplicate (and already implemented) of #2221
