### ISSUE TITLE
Server URLs in punycode are treated as invalid

### ISSUE THREAD

**Issue by GeckoEidechse** [nextcloud/ios#959]
### Expected behaviour                                                                                         

Connecting to a server where the domain contains special characters should be no different as when connecting to a standard ASCII encoded domain. Behind the scenes the client should convert the address to [punycode](https://en.wikipedia.org/wiki/Punycode) in order to retrieve the IP of the server.

### Actual behaviour

When trying to connect to a server where the domain contains special characters it results in an error message saying "Connection error: unsupported URL".

Using the *old login method* does not work either and returns the error message "Error: It is not possible to connect to the server at this time. The request timed out."

### Steps to reproduce                                                                                         

Connect to any domain that uses special characters.

### iOS version

13.1.2

### App version

2.24.1

### Additional notes

This is a duplicate of #305 which was closed due to the lack of response of the person opening the issue.

Encoding the domain to [punycode](https://en.wikipedia.org/wiki/Punycode) by hand and then using the resulting domain to connect does work, e.g. turning `https://exämple.de/` into `https://xn--exmple-cua.de/` and entering the later in the *server address field*.

**Comment by stjosh** [comment]
Seeing the same issue in 2.24.4.1 . Any activity planned here?

**Comment by johkoenig** [comment]
punycode is accepted in v3.0.14
