### ISSUE TITLE
Question for contribution

### ISSUE THREAD

**Issue by dtree0520** [nextcloud/ios#973]
i'm korean university student.
Recently, i used nextcloud application in my iphone. i think, it is quite useful and it has good information and interface. So i want our korean to know this application using opensource. But because text file like readme is written in English, people might have trouble in interpreting English.
So can i Translate text file like readme or contributing guidelines into Korean?

**Comment by marinofaggiana** [comment]
Hi, sorry for the delay but the read.me exists only in English because it's the standard language for everybody.

**Comment by tflidd** [comment]
Nextcloud is an open source project. All the user interfaces are translated into various languages (managed on transifex). Contributions, interactions with other contributors here, comments in the code etc. should be done in English so everybody can understand (most of the people here are no native English speakers).

If you want to give students or other people the contributing guidelines in Korean to help to start, you can do that. It's just if you submit stuff here, it then should be somehow in English so everybody can follow and you don't have a Korean, Russian and Spanish subcommunity.
