### ISSUE TITLE
Feature request: Ability to change file name in 'Copy to Nextcloud'

### ISSUE THREAD

**Issue by uivc** [nextcloud/ios#993]
Ability to change file name in the destination dialog when triggering the 'Copy to Nextcloud' in Share-options within other apps (e.g. scanners, file browsers, etc.). 

Currently when tapping the file name, nothing happens, only highlights the row.

<img src=https://user-images.githubusercontent.com/5981561/68761394-43831c80-0614-11ea-9f57-4a1fe5b714ef.JPG width=300>
<img src=https://user-images.githubusercontent.com/5981561/68761400-454ce000-0614-11ea-8b85-37ae62017630.JPG width=300>

**Comment by doomi** [comment]
Yes, I would like this too!

**Comment by rules76** [comment]
I think that it could be a great improvement, like adding the ability to remember the last used folder and the correct name folder in "Destination" when selected, rather than generic "Files".

**Comment by doomi** [comment]
> I think that it could be a great improvement, like adding the ability to remember the last used folder and the correct name folder in "Destination" when selected, rather than generic "Files".

I opened bug #399 in 2017 about the default „Files“ folder, but it got ignored...
